
import { 
  LayoutDashboard, Film, Code2, Wrench, Server, Settings, Clipboard, Cpu, Image as ImageIcon,
  FileText, Calculator, Palette, Search, Shield, RefreshCcw, Type, Globe, Database, Wifi,
  QrCode, Hash, Binary, Lock, Edit3, Terminal, Upload, Download, Play, AlignLeft, ArrowLeftRight,
  Link, BarChart, Clock, Phone, Key, FileJson, CheckCircle, Check
} from "lucide-react";
import { FileNode, ViewType, TaskItem, ToolCategory, ToolConfig, ToolUISchema } from "./types";
import { API_ENDPOINTS } from "./endpoints";

export { API_ENDPOINTS }; // Re-export for compatibility

export const APP_NAME = "NEXUS // ORBIT";
export const APP_VERSION = "v3.4.0-beta";

export const TRANSLATIONS = {
  en: {
    nav: {
      media: "Media",
      moviesBooks: "Movies & Books",
      code: "Code Node",
    tools: "Tools",
    api: "API Tester",
    settings: "Settings",
    tools_dashboard: {
      search_placeholder: "Search tools...",
      all_tools: "All Tools",
      favorites: "Favorites",
      history: "History",
      recent_history: "Recent History",
      all_utilities: "All Utilities",
      clear_history: "Clear History",
      clear: "Clear",
      no_history: "No history yet.",
      no_favorites: "No favorites yet.",
      no_tools_found: "No tools found.",
      tools_available: "Tools Available",
      recent: "Recent",
      add_to_favorites: "Add to favorites",
      remove_from_favorites: "Remove from favorites"
    },
      system: "System Info",
      vocabulary: "Vocabulary",
      aiTools: "AI Tools",
      aiManagement: "AI Management",
      devHistory: "AI History",
      mcp: "MCP Manager",
      octane: "Octane Tasks",
      globalTasks: "Global Tasks",
      taskCenter: "Task Center",
      server: "Server Manager",
      inviteCodes: "Invite Codes",
      dbManager: "Database Manager"
    },
    mediaHub: {
      segMovies: "Movies",
      segBooks: "Books",
      segFiles: "Files",
      searchPlaceholder: "Search…",
      refresh: "Refresh",
      emptyPrompt: "Select an item to view it here."
    },
    header: {
      system_online: "System Online",
      system_offline: "Offline Mode",
      login: "Login",
      logout: "Logout",
      logged_in_as: "Logged in as:",
      guest: "Guest",
      titles: {
        media: "Media",
        movies_books: "Movies & Books - Subtitle / Sentence Browser",
        code: "Code Browser - Core Node Directory",
        tools: "Developer Utilities",
        api: "API Testing Interface",
        system: "System Information Dashboard",
        vocabulary: "Vocabulary Learning Center",
        ai_tools: "AI Tools Suite",
        ai_management: "AI Management — Gateway, Providers & Rate Limits",
        dev_history: "AI Dev History — Prompts & Sessions",
        mcp: "MCP Manager",
        octane: "Octane Timer Tasks Monitor",
        global_tasks: "Global Tasks & Workers Monitor",
        task_center: "Task Center — Scheduler & Queue Management",
        server: "Server Management Dashboard",
        invite_codes: "Invite Code Management",
        db_manager: "Database Manager",
        settings: "Settings"
      }
    },
    devHistoryView: {
      title: "AI Dev History",
      subtitle: "Prompts & sessions across Claude / Codex / Gemini / Cursor",
      refresh: "Refresh",
      refreshing: "Refreshing…",
      sessions: "Sessions",
      prompts: "Prompts",
      allTools: "All tools",
      allUsers: "All users",
      notDevMachine: "Not a developer machine — no AI-tool history found.",
      empty: "No records yet. Click Refresh to extract.",
      selectSession: "Select a session to view its transcript.",
      subagent: "sub-agent",
      generatedAt: "Updated",
      project: "Project",
      user: "User",
      messages: "messages",
      search: "Search…",
      copy: "Copy",
      copied: "Copied",
      edit: "Edit",
      save: "Save",
      cancel: "Cancel",
      edited: "edited",
      loadError: "Failed to load."
    },
    moviesBooksView: {
      sourcesTitle: "Sources",
      movies: "Movies",
      books: "Books",
      searchPlaceholder: "Search title...",
      refresh: "Refresh",
      sentences: "Sentences",
      items: "items",
      segment: "Segment",
      formatFull: "Full",
      formatTiny: "Tiny 2x2",
      selectPrompt: "Select a movie or book to begin",
      pickSentence: "Pick a sentence to play its clip",
      noSentences: "No sentences for this source.",
      emptyList: "Nothing here yet.",
      loadError: "Failed to load.",
      offline: "Offline — backend unreachable.",
      noAiFields: "No AI analysis for this sentence.",
      explanation: "Explanation",
      grammar: "Grammar",
      aiCommentary: "AI Commentary",
      specialUsage: "Special Usage"
    },
    login: {
      title: "Identity Verification",
      subtitle: "Please authenticate to access core systems.",
      username: "Username / ID",
      password: "Password",
      confirm_password: "Confirm Password",
      email: "Email (Optional)",
      nickname: "Nickname (Optional)",
      registration_code: "Registration Code (Optional)",
      submit: "Authenticate",
      cancel: "Cancel",
      processing: "Verifying...",
      register_title: "Create Account",
      register_subtitle: "Register to access core systems.",
      register_submit: "Register",
      register_processing: "Creating account...",
      switch_to_login: "Already have an account? Login",
      switch_to_register: "Don't have an account? Register",
      login_success: "Login successful",
      register_success: "Registration successful",
      passwords_do_not_match: "Passwords do not match",
      available_codes: "Available Codes:",
      errors: {
        AUTH_USER_NOT_FOUND: "Account does not exist. Please check your username or email.",
        AUTH_INVALID_PASSWORD: "Incorrect password. Please try again.",
        AUTH_INVALID_CREDENTIALS: "Invalid credentials. Please check and try again.",
        AUTH_VALIDATION_FAILED: "Username and password are required.",
        default: "Login failed. Please try again."
      }
    },
    system: {
      title: "System Information",
      subtitle: "Real-time system configuration and status",
      tabs: {
        server: "Server",
        php: "PHP",
        laravel: "Laravel",
        database: "Database",
        cache: "Cache",
        queue: "Queue",
        routes: "Routes"
      },
      fields: {
        hostname: "Hostname",
        operating_system: "Operating System",
        server_time: "Server Time",
        timezone: "Timezone",
        uptime: "Uptime",
        cpu_model: "CPU Model",
        cpu_cores: "CPU Cores",
        version: "Version",
        memory_limit: "Memory Limit",
        max_execution_time: "Max Execution Time",
        upload_max_size: "Upload Max Size",
        post_max_size: "Post Max Size",
        display_errors: "Display Errors",
        extensions: "Extensions",
        environment: "Environment",
        debug_mode: "Debug Mode",
        app_url: "App URL",
        app_name: "App Name",
        locale: "Locale",
        cache_status: "Cache Status",
        config_cached: "Config Cached",
        routes_cached: "Routes Cached",
        events_cached: "Events Cached",
        views_cached: "Views Cached",
        service_name: "Service Name",
        enabled: "Enabled",
        active: "Active",
        inactive: "Inactive",
        yes: "Yes",
        no: "No",
        not_available: "Not available"
      },
      refresh: "Refresh",
      auto_refresh: "Auto Refresh",
      last_updated: "Last Updated"
    },
    vocabulary: {
      title: "Vocabulary Learning",
      translate: "Translate",
      source_lang: "Source Language",
      target_lang: "Target Language",
      input_placeholder: "Enter text to translate...",
      auto_detect: "Auto Detect",
      clear: "Clear",
      history: "Translation History",
      recent_logs_dock: "Recent Logs",
      learning_tasks: "Learning Tasks",
      auto_refresh: "Auto-refresh (5s)",
      refresh: "Refresh",
      failed: "failed",
      no_logs: "No recent logs yet",
      logs_moved_hint: "Recent logs moved to the floating dock (bottom-left).",
      open_logs_dock: "Open logs",
      delete_library: "Delete library",
      delete_library_confirm: "Delete library \"{name}\"? Words created by this upload are removed; built-in dictionary data is not affected.",
      delete_library_success: "Library \"{name}\" deleted",
      delete_library_failed: "Failed to delete library",
      login_required: "Please log in first — this action requires authentication.",
      cancel: "Cancel",
      translate_failed: "Translation failed",
      tts_success: "Audio generated",
      tts_failed: "TTS generation failed",
      upload_success: "Upload complete",
      upload_failed: "Upload failed",
      export_success: "Export complete",
      export_failed: "Export failed. Please try again.",
      export_no_words: "No words available to export for the selected scope.",
      export_popup_blocked: "Please allow pop-ups to export as PDF (Print).",
      export_server: "Server export complete: {filename}",
      export_fallback_html: "PDF was generated as printable HTML — open the downloaded file and use your browser's \"Save as PDF\".",
      export_fallback_client: "Server export unavailable (404) — fell back to in-browser export.",
      extracting: "Extracting...",
      extract_done: "+{added} added, {skipped} skipped",
      extract_failed: "Extraction failed",
      extract_requires_update: "Extraction requires a backend update (no document_id returned) — the file was uploaded without extraction.",
      review_empty: "All caught up! No words due for review.",
      review_login_hint: "Log in to load your personal review queue.",
      review_load_failed: "Failed to load review queue",
      review_submit_failed: "Failed to save review result",
      stats_login_hint: "Log in to see your learning statistics.",
      stats_load_failed: "Failed to load statistics"
    },
    mcp: {
      title: "MCP Manager",
      tabs: {
        screenshots: "Screenshots",
        tasks: "Task Dispatch",
        placeholder: "Placeholder",
        voice: "Voice Subtitle",
        ocr: "OCR",
        settings: "Settings"
      },
      screenshots: {
        upload: "Upload",
        refresh: "Refresh",
        latest: "Latest",
        clear_all: "Clear All",
        search_placeholder: "Search screenshots...",
        no_screenshots: "No screenshots found",
        upload_hint: "Click Upload button, drag & drop, or paste (Ctrl+V) images here",
        view: "View",
        download: "Download",
        delete: "Delete",
        copy_url: "Copy URL",
        image_url: "Image URL",
        description: "Description",
        delete_confirm: "Delete this screenshot?",
        clear_all_confirm: "⚠️ DANGER: This will permanently delete ALL screenshots. This action cannot be undone. Are you sure?",
        clear_all_final: "Final confirmation: Delete ALL screenshots?",
        upload_mode: "Upload Mode",
        single_upload: "Single Upload",
        batch_upload: "Batch Upload",
        batch_desc: "Upload each image separately",
        merge_upload: "Merge Upload",
        merge_desc: "Merge multiple images into one",
        drop_here: "Drop images here",
        paste_hint: "or paste with Ctrl+V / Cmd+V",
        stats_total: "Total Screenshots",
        search_by_filename: "Search screenshots by filename...",
        upload_dialog_title: "Select Upload Mode",
        single_file_upload: "Single File Upload",
        single_file_desc: "Upload one image",
        multi_file_upload: "Multi-File Upload",
        multi_file_desc: "Batch upload or merge multiple images",
        drop_or_click: "Drag images here or click to upload",
        supported_formats: "Supports JPG, PNG, GIF, WebP and more",
        batch_mode: "📚 Batch Mode",
        merge_mode: "🔗 Merge Mode",
        load_failed: "Failed to load screenshots",
        stats_load_failed: "Failed to load screenshot statistics",
        search_failed: "Search failed",
        load_image_failed: "Failed to load image",
        toast: {
          copied: "Copied to clipboard!",
          copy_failed: "Copy failed",
          copy_failed_manual: "Copy failed, please copy manually"
        }
      },
      common: {
        retry: "Retry",
        cancel: "Cancel",
        create: "Create",
        refresh: "Refresh",
        delete: "Delete",
        save: "Save",
        copy: "Copy",
        add: "Add",
        reset: "Reset",
        loading: "Loading...",
        all: "All",
        today: "Today",
        latest: "Latest",
        this_week: "This Week",
        storage_used: "Storage Used",
        total: "Total",
        pending: "Pending",
        processing: "Processing",
        in_progress: "In Progress",
        completed: "Completed",
        failed: "Failed",
        clear_all: "Clear All",
        select_all: "Select All",
        deselect_all: "Deselect All",
        size: "Size:",
        error_label: "Error:"
      },
      tasks: {
        categories: "Categories",
        create_category: "Create Category",
        category_name_placeholder: "Category name...",
        category_created: "Category created",
        create_category_failed: "Failed to create category",
        no_categories: "No categories available",
        view_files: "View Files",
        view_files_title: "View files in this category",
        add_new_task: "Add New Task",
        task_content: "Task Content",
        task_content_placeholder: "Enter task content or paste markdown...",
        file_name_optional: "File Name (optional)",
        priority: "Priority",
        priority_low: "Low",
        priority_normal: "Normal",
        priority_high: "High",
        priority_urgent: "Urgent",
        add_task: "Add Task",
        queue_title: "Task Queue",
        search_tasks_placeholder: "Search tasks...",
        no_tasks: "No tasks in this queue yet",
        no_tasks_hint: "Add a task above to get started",
        edit_status: "Edit status",
        hide_content: "Hide content",
        view_content: "View content",
        delete_task: "Delete task",
        no_content: "(no content)",
        created_label: "Created:",
        completed_label: "Completed:",
        prompt_mapping: "Prompt Mapping",
        prompt_file_path: "Prompt File Path",
        prompt_content: "Prompt Content",
        prompt_content_placeholder: "Enter prompt content...",
        variables: "Variables",
        save_prompt_mapping: "Save Prompt Mapping",
        delete_task_confirm: "Delete this task? This cannot be undone.",
        task_deleted: "Task deleted",
        delete_task_failed: "Failed to delete task",
        select_category_hint: "Select a category to view tasks",
        category_files: "Category Files",
        files_total_prefix: "Total:",
        files_total_suffix: "files",
        no_files: "No files in this category",
        load_categories_failed: "Failed to load categories",
        load_tasks_failed: "Failed to load tasks",
        search_failed: "Search failed"
      },
      placeholder: {
        stats_total: "Total Generated",
        generate_title: "Generate Placeholder",
        width: "Width (px)",
        height: "Height (px)",
        text_optional: "Text (optional)",
        text_placeholder: "Placeholder Image",
        bg_color: "Background Color",
        text_color: "Text Color",
        format: "Format",
        mode: "Mode",
        mode_simple: "Simple",
        mode_real: "Realistic",
        generate: "Generate",
        preview: "Preview",
        generated_alt: "Generated placeholder",
        dimensions_label: "Dimensions:",
        format_label: "Format:",
        file_size_label: "File Size:",
        no_placeholder: "No placeholder generated",
        no_placeholder_hint: "Fill the form and click Generate",
        recent: "Recent",
        refresh_history: "Refresh history",
        cleanup: "Cleanup",
        cleanup_title: "Clean up old placeholders",
        cleanup_confirm: "Clean up old placeholder images? This will remove unused placeholders to free up storage space.",
        delete_confirm: "Delete this placeholder?",
        no_history: "No history",
        stats_load_failed: "Failed to load placeholder statistics",
        generate_failed: "Failed to generate placeholder"
      },
      voice: {
        stats_total: "Total Items",
        add_to_queue: "Add to Voice Queue",
        type_text: "Text",
        type_url: "URL",
        type_voice: "Voice",
        type_image: "Image",
        choose_image: "Choose Image",
        description_placeholder: "Description (optional)...",
        add_image_to_queue: "Add Image to Queue",
        content_placeholder_text: "Enter text...",
        content_placeholder_url: "Enter URL...",
        content_placeholder_voice: "Enter voice content...",
        now_playing: "Now Playing",
        queue: "Queue",
        all_groups: "All Groups",
        all_categories: "All Categories",
        clear_queue_title: "Clear entire queue",
        group_name_placeholder: "Group name",
        edit_group: "Edit group",
        played_prefix: "Played",
        played_suffix: "x",
        queue_empty: "Queue is empty",
        background_tasks: "Background Tasks",
        no_background_tasks: "No background tasks",
        delete_task: "Delete task",
        created_label: "Created:",
        updated_label: "Updated:",
        delete_selected_confirm_prefix: "Delete",
        delete_selected_confirm_suffix: "selected item(s)?",
        clear_queue_confirm: "Clear entire voice queue? This cannot be undone.",
        delete_tasks_confirm_prefix: "Delete",
        delete_tasks_confirm_suffix: "background task(s)?",
        load_queue_failed: "Failed to load voice queue",
        stats_load_failed: "Failed to load voice statistics",
        groups_load_failed: "Failed to load voice groups",
        languages_load_failed: "Failed to load supported languages",
        categories_load_failed: "Failed to load voice categories",
        settings_load_failed: "Failed to load voice settings",
        tasks_load_failed: "Failed to load background tasks"
      },
      ocr: {
        title: "OCR Recognition",
        engine: "OCR Engine",
        loading_engine_info: "Loading engine info...",
        accuracy_label: "Accuracy:",
        languages_label: "Languages:",
        speed_label: "Speed:",
        upload_image: "Upload Image",
        choose_image: "Choose Image",
        preview: "Preview",
        preview_alt: "OCR Preview",
        recognize: "Recognize",
        smart_recognize_title: "Smart recognition with automatic engine selection",
        batch_recognition: "Batch Recognition",
        choose_multiple_images: "Choose Multiple Images",
        selected_prefix: "Selected:",
        selected_suffix: "image(s)",
        batch_recognize: "Batch Recognize",
        batch_results: "Batch Results",
        recognition_result: "Recognition Result",
        image_label: "Image",
        confidence_label: "Confidence:",
        copy_text: "Copy Text",
        no_text_detected: "No text detected",
        no_result: "No recognition result",
        no_result_hint: "Upload an image and click Recognize",
        engines_load_failed: "Failed to load OCR engines",
        engine_info_load_failed: "Failed to load engine info",
        recognize_failed: "OCR recognition failed",
        smart_recognize_failed: "Smart OCR recognition failed",
        batch_recognize_failed: "Batch OCR recognition failed"
      },
      settings: {
        title: "Settings",
        coming_soon: "Settings panel coming soon..."
      }
    },
    octane: {
      title: "Octane Timer Tasks",
      subtitle: "Real-time task scheduling and execution monitoring",
      timer_status: "Timer Status",
      total_tasks: "Total Tasks",
      running_tasks: "Running Tasks",
      completed_tasks: "Completed Tasks",
      failed_tasks: "Failed Tasks"
    },
    taskCenter: {
      title: "Task Center",
      subtitle: "Unified management of the scheduler layer (Octane timers) and the queue layer (global_tasks + workers)",
      tabs: {
        overview: "Overview",
        scheduler: "Scheduler",
        queue: "Task Queue",
        workers: "Workers",
        assist: "Assist Requests"
      },
      refresh: "Refresh",
      auto_refresh: "Auto-refresh",
      retry: "Retry",
      load_failed: "Failed to load task center overview",
      last_updated: "Last updated:",
      chips: {
        scheduler_running: "Scheduler running",
        scheduler_stopped: "Scheduler stopped",
        queue_pending: "pending",
        workers_online: "workers online"
      },
      roles: {
        producer: "Producer",
        consumer: "Consumer",
        maintainer: "Maintainer"
      },
      overview: {
        scheduler_card: "Scheduler Layer",
        scheduler_card_sub: "Octane timers (in-process cron)",
        queue_card: "Task Queue",
        queue_card_sub: "global_tasks (persistent, distributed)",
        workers_card: "Executors / Workers",
        workers_card_sub: "Distributed worker nodes",
        ticks: "ticks",
        uptime: "uptime",
        timer_tasks: "timer tasks",
        maintain_loop: "Maintain: timeout release / retention purge",
        known_workers: {
          pycore: "pycore (Google Translate)",
          chrome: "Chrome extension (Bing dictionary)",
          internal_ai: "laravel-internal-ai (AI fallback)"
        },
        relations_title: "Scheduler ⇄ Queue Relations",
        relations_columns: {
          timer: "Timer Task",
          role: "Role",
          target: "Target Task Type",
          interval: "Interval",
          runs: "Runs",
          errors: "Errors",
          registered: "Registered"
        },
        no_relations: "No scheduler ⇄ queue relations registered",
        explainer_title: "How the two layers relate",
        explainer:
          "Scheduler layer = in-process cron (state lives in Octane worker memory, lost on restart). Queue layer = DB-persisted distributed queue with a 7-state lifecycle (pending → assigned → processing → completed / completed_demo / failed / cancelled). Timer tasks act as the queue's producers (scan & enqueue), consumer (the internal AI worker drains tasks no external worker picked up) and maintainer (timeout release + retention purge). The pycore end is isomorphic: PyHeartbeat ≈ scheduler layer, the local TaskManager ≈ local task records."
      },
      workers_panel: {
        stats: {
          total: "Total",
          online: "Online",
          busy: "Busy",
          offline: "Offline",
          total_completed: "Total Completed",
          total_failed: "Total Failed"
        },
        role_hints: {
          pycore_translate: "pycore Google Translate worker — external Python end, processes word_translation tasks",
          internal_ai: "Laravel internal AI self-filler — driven by the consumer timer task, drains stale queue tasks",
          generic: "Generic external worker"
        }
      },
      covers: {
        title: "Cover Generation & AI",
        subtitle: "Vocabulary library covers — queue status, Laravel AI (gemini) and pycore image backends (appqyv1_cover_generation timer task)",
        refresh: "Refresh",
        retry_failed: "Retry failed",
        load_failed: "Failed to load cover status",
        task: {
          enabled: "Timer enabled",
          disabled: "Timer disabled",
          batch: "batch",
          retry_delay: "retry delay"
        },
        queue: {
          pending: "Pending",
          retry: "Retry",
          processing: "Processing",
          ready: "Ready",
          failed: "Failed",
          leased: "Assist-leased"
        },
        queue_total: "total",
        leased_hint: "Leased to a third-party assist worker (e.g. pycore)",
        laravel_ai: "Laravel AI",
        pycore: "pycore",
        configured: "Configured",
        not_configured: "Not configured",
        probe_available: "Probe OK",
        probe_failed: "Probe failed",
        not_probed: "Not probed",
        reachable: "Reachable",
        unreachable: "Unreachable",
        image_capable: "Image capable",
        not_image_capable: "No image provider",
        no_providers: "No provider info",
        provider_image_mark: "image-capable",
        recent_failures: "Recent failures",
        no_failures: "No recent failures",
        confirm_title: "Retry failed covers",
        confirm_message: "Reset all {count} failed cover task(s) back to the retry queue? They will be regenerated on the next scheduler run.",
        confirm: "Retry",
        cancel: "Cancel",
        retry_success: "{count} failed cover(s) queued for retry",
        retry_error: "Cover retry request failed"
      }
    },
    globalTasks: {
      title: "Global Tasks",
      subtitle: "Distributed worker queue — global tasks & workers",
      auto_refresh: "Auto-refresh",
      refresh: "Refresh",
      retry: "Retry",
      load_failed: "Failed to load global tasks",
      timeout_hint: "Request timed out — the Laravel server did not respond in time.",
      network_hint: "Network unreachable — is laravel_main running on this host?",
      stats: {
        pending: "Pending",
        assigned: "Assigned",
        processing: "Processing",
        completed: "Completed",
        completed_demo_suffix: "demo",
        failed: "Failed",
        cancelled: "Cancelled",
        total: "Total",
        workers: "Workers",
        online: "online",
        busy: "busy",
        offline: "offline"
      },
      filter: "Filter:",
      search_placeholder: "Filter by app name or task type...",
      tasks_suffix: "tasks",
      columns: {
        task_id: "Task ID",
        app_name: "App",
        task_type: "Task Type",
        execution_type: "Execution",
        status: "Status",
        progress: "Progress",
        assigned_to: "Assigned To",
        created_at: "Created",
        actions: "Actions"
      },
      cancel: "Cancel",
      cancel_failed: "Cancel failed",
      cancelled_ok: "Task cancelled",
      no_tasks: "No tasks found with current filter",
      workers: {
        title: "Workers",
        columns: {
          worker: "Worker",
          status: "Status",
          processors: "Processor Types",
          completed: "Completed",
          failed: "Failed",
          current_task: "Current Task",
          last_heartbeat: "Last Heartbeat"
        },
        no_workers: "No workers registered"
      },
      detail: {
        title: "Task Detail",
        loading: "Loading live task detail…",
        live: "Live data",
        status: "Status",
        progress: "Progress",
        app_name: "App",
        task_type: "Task Type",
        execution_type: "Execution Type",
        assigned_to: "Assigned To",
        error: "Error",
        result: "Result",
        result_truncated: "(result truncated)",
        no_result: "No result",
        created_at: "Created At",
        updated_at: "Updated At",
        priority: "Priority",
        retries: "Retries / Max · Timeout",
        completed_at: "Completed At",
        payload: "Payload",
        capability: "Capability",
        lane: "Lane",
        fast_tier: "Fast lane",
        timeline: "Event Timeline",
        no_events: "No events yet",
        phase: "Current Phase",
        elapsed: "Elapsed",
        attempt: "Attempt",
        bump: "Bump to top",
        bumping: "Bumping…",
        bumped_ok: "Bumped to priority",
        bump_failed: "Bump failed",
        live_stream: "Streaming live",
        stream_offline: "Snapshot (stream offline)"
      },
      sort: "Sort:",
      sort_default: "Default",
      sort_priority_desc: "Priority ↓",
      sort_priority_asc: "Priority ↑",
      fast_only: "Fast lane only",
      never: "Never",
      just_now: "just now",
      last_updated: "Last updated:"
    },
    api_tester: {
      title: "API Testing Dashboard",
      search_placeholder: "Search by #ID, path, or description...",
      select_app: "Select App",
      endpoints: "endpoints",
      endpoint: "endpoint",
      shared_headers: "Shared Headers",
      save: "Save",
      reset: "Reset",
      copy_headers: "Copy headers JSON",
      authentication: "Authentication",
      required: "Required",
      optional: "Optional",
      controller: "Controller",
      parameters: "Parameters",
      response_format: "Response Format",
      endpoint_url: "Endpoint URL",
      request_params: "Request Parameters (JSON)",
      load_params: "Load",
      save_params: "Save",
      send_request: "Send Request",
      sending: "Sending...",
      response: "Response",
      no_endpoints: "No endpoints found",
      select_send: "Select and send an API request",
      view_response: "to view the response here",
      empty_body: "(empty response body)",
      copy_response: "Copy response"
    },
    media_browser: {
      title: "Media Browser",
      upload: "Upload",
      new_folder: "New Folder",
      refresh: "Refresh",
      fullscreen: "Fullscreen",
      auto_play: "Auto Play",
      next: "Next",
      no_preview: "No preview available",
      loading: "Loading...",
      error: "Error loading media",
      folder_name: "Folder Name",
      create_folder: "Create Folder",
      cancel: "Cancel",
      upload_files: "Upload Files",
      drop_files: "Drop files here or click to upload"
    },
    code_browser: {
      title: "Code Browser",
      search: "Search files...",
      no_files: "No files found",
      loading: "Loading...",
      error: "Error loading files"
    },
    settings: {
      title: "Settings",
      api_config: "API Configuration",
      base_url: "Base URL",
      api_key: "API Key",
      save: "Save",
      reset: "Reset to Default",
      reset_to_origin: "Reset to Origin",
      test_connection: "Test Connection",
      saved: "Settings saved successfully",
      reset_success: "Settings reset to default",
      reset_to_origin_success: "Settings reset to browser origin",
      test_success: "Connection successful",
      test_error: "Connection failed",
      current_origin: "Current origin",
      browser_origin: "Browser Origin",
      auth_required: "Settings page requires authentication. Please login to continue."
    },
    invite_codes: {
      auth_required: "Invite Code Manager requires admin access. Please login with admin account."
    },
    server_manager: {
      auth_required: "Server Manager requires authentication. Please login to continue."
    },
    db_manager: {
      auth_required: "Database Manager requires login. Please authenticate to manage connections, tables and backups.",
      credentials: {
        tab: "Credentials",
        title: "Credentials",
        superuser: "Superuser",
        driver: "Driver",
        password_auth: "Password auth",
        supported: "supported",
        not_applicable: "not applicable",
        sync_note: "Changing or resetting the password also re-syncs Laravel's own config so this connection keeps working afterward. Password auth applies to pgsql / mysql only.",
        no_password_note: "This file-based database has no password; credential controls are disabled.",
        change: "Change password",
        change_desc: "Set a new password for the user. Laravel's config is re-synced automatically.",
        new_password: "New password",
        confirm_password: "Confirm password",
        passwords_no_match: "Passwords do not match.",
        change_and_sync: "Change & sync",
        change_success: "Password changed & synced to Laravel config",
        change_not_synced: "Password changed, but Laravel config was NOT synced — connections may break until re-synced.",
        reset: "Reset root password",
        reset_desc: "Generate a fresh strong password. It is shown once — record it immediately.",
        reset_and_generate: "Reset & generate",
        reset_confirm: "The current password stops working immediately. The new one is shown only once.",
        reset_success: "Root password reset & synced to Laravel config",
        reset_not_synced: "Password reset, but Laravel config was NOT synced — connections may break until re-synced.",
        new_password_title: "New password — store it now",
        store_now_warning: "Store this password now — it will not be shown again.",
        stored_it: "I've stored it",
        synced_note: "This password was synced to Laravel's credential store, so connections keep working.",
        not_synced_note: "WARNING: this password was NOT synced to Laravel's credential store — re-sync manually or connections will break.",
        copy: "Copy",
        copied: "Copied"
      }
    },
    auth: {
      login_hint: "Sign in to continue.",
      use_login_window: "Use the login window to authenticate."
    },
    common: {
      close: "Close"
    },
    server: {
      title: "Server Manager",
      subtitle: "Nginx sites, SSL certificates, and system management",
      tabs: {
        nginx: "Nginx Sites",
        ssl: "SSL Certificates",
        system: "System Status",
        files: "File Manager",
        executor: "Code Executor",
        unified: "Unified Manager"
      },
      nginx: {
        sites: "Nginx Sites",
        create_site: "Create Site",
        site_name: "Site Name",
        domain: "Domain",
        site_type: "Site Type",
        www_dir: "Web Directory",
        php_mode: "PHP Mode",
        swoole_port: "Swoole Port",
        ssl_enabled: "SSL Enabled",
        enabled: "Enabled",
        disabled: "Disabled",
        enable: "Enable",
        disable: "Disable",
        delete: "Delete Site",
        view_config: "View Config",
        test_config: "Test Config",
        reload: "Reload Nginx",
        refresh: "Refresh",
        create: "Create Site",
        update: "Update Site",
        test: "Test Configuration",
        status: "Nginx Status",
        installed: "Installed",
        not_installed: "Not Installed",
        running: "Running",
        stopped: "Stopped",
        version: "Version",
        start: "Start",
        stop: "Stop",
        restart: "Restart",
        logs: "Nginx Logs",
        access_log: "Access Log",
        error_log: "Error Log",
        lines: "Lines",
        refresh_status: "Refresh Status",
        install_hint_title: "Nginx is not installed",
        config_test: "Config Test",
        sites_count: "Sites",
        service_manager: "Service Manager",
        processes: "processes",
        valid: "Valid",
        invalid: "Invalid",
        copy: "Copy",
        copied: "Copied to clipboard",
        no_log_file: "Log file does not exist",
        install: "Install nginx",
        installing: "Installing… this can take several minutes",
        install_success: "Nginx installed successfully",
        install_failed: "Nginx installation failed",
        already_installed: "Nginx is already installed",
        install_guidance: "Nginx is not installed. Use the Install button in the status card above, or run the manual command.",
        metrics_active: "Active",
        metrics_requests: "Requests",
        metrics_memory: "Mem",
        metrics_cpu: "CPU",
        metrics_unavailable: "Metrics unavailable — nginx stub_status is not configured",
        main_config: "nginx.conf",
        worker_processes: "worker_processes",
        worker_connections: "worker_connections",
        conf_d_files: "conf.d files",
        config_file_missing: "Configuration file does not exist",
        truncated: "(truncated)",
        backups: "Config Backups",
        backups_empty: "No backups found",
        backup_restore: "Restore",
        backup_restore_title: "Restore backup",
        backup_restore_message: "Restore backup {file}? The current config will be backed up first.",
        backup_restored: "Backup restored",
        backup_type_update: "update",
        backup_type_delete: "delete",
        cert_expires_in: "expires in {days}d",
        cert_expired: "expired",
        renew_cert: "Renew cert",
        renew_cert_started: "Certificate renewal started for {domain}",
        renew_cert_failed: "Certificate renewal failed",
        confirm_stop: "Stop nginx? All sites served by nginx will go offline.",
        confirm_restart: "Restart nginx? Connections will be briefly interrupted.",
        edit_config: "Configuration",
        save: "Save",
        saving: "Saving…",
        config_saved: "Configuration saved",
        config_save_failed: "Save failed",
        config_load_failed: "Failed to load configuration (read-only view unavailable)",
        auto_follow: "Follow",
        filter_placeholder: "Filter keyword…",
        scanned_lines: "scanned {n} lines",
        batch: "Batch",
        batch_enable: "Enable selected",
        batch_disable: "Disable selected",
        batch_test: "Test",
        batch_selected: "{n} selected",
        batch_summary: "Batch {action}: {ok} succeeded, {fail} failed",
        no_sites: "No nginx sites found",
        site_enabled: "Site {site} enabled",
        site_disabled: "Site {site} disabled",
        port_in_use: "Port {port} is already in use by {holder}",
        cancel: "Cancel",
        close: "Close",
        ports: "Ports",
        modified: "Modified"
      },
      ssl: {
        certificates: "SSL Certificates",
        generate: "Generate Certificate",
        renew: "Renew All",
        renew_all: "Renew All Certificates",
        domain: "Domain",
        expiry_date: "Expiry Date",
        days_until_expiry: "Days Until Expiry",
        status: "Status",
        ok: "OK",
        warning: "Warning",
        critical: "Critical",
        certbot_detect: "Detect Certbot",
        certbot_install: "Install Certbot"
      },
      system: {
        title: "System Status",
        cpu: "CPU",
        memory: "Memory",
        disk: "Disk",
        services: "Services",
        refresh: "Refresh",
        processes: "Processes",
        storage: "Storage",
        permissions: "Permissions"
      },
      files: {
        title: "File Manager",
        browse: "Browse",
        download: "Download",
        preview: "Preview",
        info: "File Info",
        path: "Path",
        size: "Size",
        modified: "Modified",
        permissions: "Permissions"
      },
      executor: {
        title: "Code Executor",
        scripts: "Predefined Scripts",
        execute: "Execute",
        logs: "Execution Logs",
        status: "Status",
        category: "Category",
        timeout: "Timeout",
        output: "Output"
      },
      unified: {
        title: "Unified Manager",
        apps: "Applications",
        deploy: "Deploy",
        start: "Start",
        stop: "Stop",
        restart: "Restart",
        status: "Status",
        logs: "Logs",
        service_name: "Service Name",
        port: "Port"
      },
      messages: {
        confirm_reset: "Are you sure you want to reset to default settings?",
        confirm_renew_certs: "Are you sure you want to renew all certificates?",
        confirm_install_certbot: "Are you sure you want to install Certbot?",
        confirm_delete_site: "Are you sure you want to delete site: {site}?",
        cert_generation_started: "Certificate generation started",
        cert_renewal_started: "Certificate renewal started",
        certbot_installation_started: "Certbot installation started",
        nginx_reloaded: "Nginx reloaded successfully",
        site_deleted: "Site deleted successfully",
        nginx_config_valid: "Nginx configuration is valid!",
        nginx_config_errors: "Configuration errors:",
        operation_failed: "Operation failed",
        action_completed: "Action {action} completed",
        failed_to_load: "Failed to load",
        failed_to_generate_cert: "Failed to generate certificate",
        failed_to_renew_certs: "Failed to renew certificates",
        failed_to_install_certbot: "Failed to install Certbot"
      }
    }
  },
  zh: {
    nav: {
      media: "媒体",
      moviesBooks: "影片与书籍",
      code: "代码节点",
      tools: "工具箱",
      api: "API 测试",
      settings: "系统设置",
      system: "系统信息",
      vocabulary: "词汇学习",
      aiManagement: "AI 管理",
      devHistory: "AI 记录",
      mcp: "MCP 管理器",
      octane: "Octane 任务",
      globalTasks: "全局任务",
      taskCenter: "任务中心",
      server: "服务器管理",
      inviteCodes: "邀请码管理",
      dbManager: "数据库管理"
    },
    mediaHub: {
      segMovies: "影片",
      segBooks: "书籍",
      segFiles: "文件",
      searchPlaceholder: "搜索…",
      refresh: "刷新",
      emptyPrompt: "选择一个项目以在此查看。"
    },
    header: {
      system_online: "系统在线",
      system_offline: "离线模式",
      login: "登录",
      logout: "登出",
      logged_in_as: "当前用户:",
      guest: "访客",
      titles: {
        media: "媒体",
        movies_books: "影片与书籍 - 字幕 / 句子浏览器",
        code: "代码浏览器 - 核心节点目录",
        tools: "开发者实用工具",
        api: "API 测试接口",
        system: "系统信息仪表板",
        vocabulary: "词汇学习中心",
        ai_tools: "AI 工具套件",
        ai_management: "AI 管理 — 网关、提供商与速率限制",
        dev_history: "AI 开发记录 — 提示词与会话",
        mcp: "MCP 管理器",
        octane: "Octane 定时任务监控",
        global_tasks: "全局任务与工作节点监控",
        task_center: "任务中心 — 调度与队列管理",
        server: "服务器管理仪表板",
        invite_codes: "邀请码管理",
        db_manager: "数据库管理",
        settings: "系统设置"
      }
    },
    devHistoryView: {
      title: "AI 开发记录",
      subtitle: "Claude / Codex / Gemini / Cursor 的提示词与会话",
      refresh: "刷新",
      refreshing: "刷新中…",
      sessions: "会话",
      prompts: "提示词",
      allTools: "全部工具",
      allUsers: "全部用户",
      notDevMachine: "非开发机 — 未找到 AI 工具历史记录。",
      empty: "暂无记录。点击“刷新”进行提取。",
      selectSession: "选择一个会话以查看其记录。",
      subagent: "子代理",
      generatedAt: "更新于",
      project: "项目",
      user: "用户",
      messages: "条消息",
      search: "搜索…",
      copy: "复制",
      copied: "已复制",
      edit: "编辑",
      save: "保存",
      cancel: "取消",
      edited: "已编辑",
      loadError: "加载失败。"
    },
    moviesBooksView: {
      sourcesTitle: "资源",
      movies: "影片",
      books: "书籍",
      searchPlaceholder: "搜索标题...",
      refresh: "刷新",
      sentences: "句子",
      items: "条",
      segment: "片段",
      formatFull: "完整",
      formatTiny: "迷你 2x2",
      selectPrompt: "选择一部影片或一本书开始",
      pickSentence: "选择一个句子以播放其片段",
      noSentences: "该资源没有句子。",
      emptyList: "暂无内容。",
      loadError: "加载失败。",
      offline: "离线 — 无法连接后端。",
      noAiFields: "该句子没有 AI 分析。",
      explanation: "解释",
      grammar: "语法",
      aiCommentary: "AI 点评",
      specialUsage: "特殊用法"
    },
    login: {
      title: "身份验证",
      subtitle: "请验证身份以访问核心系统。",
      username: "用户名 / ID",
      password: "密码",
      confirm_password: "确认密码",
      email: "邮箱（可选）",
      nickname: "昵称（可选）",
      registration_code: "注册码（可选）",
      submit: "验证登录",
      cancel: "取消",
      processing: "验证中...",
      register_title: "创建账户",
      register_subtitle: "注册以访问核心系统。",
      register_submit: "注册",
      register_processing: "创建账户中...",
      switch_to_login: "已有账户？登录",
      switch_to_register: "没有账户？注册",
      login_success: "登录成功",
      register_success: "注册成功",
      passwords_do_not_match: "两次密码输入不一致",
      available_codes: "可用邀请码:",
      errors: {
        AUTH_USER_NOT_FOUND: "账号不存在，请检查用户名或邮箱。",
        AUTH_INVALID_PASSWORD: "密码错误，请重试。",
        AUTH_INVALID_CREDENTIALS: "凭证无效，请检查后重试。",
        AUTH_VALIDATION_FAILED: "请输入用户名和密码。",
        default: "登录失败，请重试。"
      }
    },
    system: {
      title: "系统信息",
      subtitle: "实时系统配置和状态",
      tabs: {
        server: "服务器",
        php: "PHP",
        laravel: "Laravel",
        database: "数据库",
        cache: "缓存",
        queue: "队列",
        routes: "路由"
      },
      fields: {
        hostname: "主机名",
        operating_system: "操作系统",
        server_time: "服务器时间",
        timezone: "时区",
        uptime: "运行时间",
        cpu_model: "CPU 型号",
        cpu_cores: "CPU 核心数",
        version: "版本",
        memory_limit: "内存限制",
        max_execution_time: "最大执行时间",
        upload_max_size: "最大上传大小",
        post_max_size: "POST 最大大小",
        display_errors: "显示错误",
        extensions: "扩展",
        environment: "环境",
        debug_mode: "调试模式",
        app_url: "应用 URL",
        app_name: "应用名称",
        locale: "语言区域",
        cache_status: "缓存状态",
        config_cached: "配置已缓存",
        routes_cached: "路由已缓存",
        events_cached: "事件已缓存",
        views_cached: "视图已缓存",
        service_name: "服务名称",
        enabled: "已启用",
        active: "活动",
        inactive: "未活动",
        yes: "是",
        no: "否",
        not_available: "不可用"
      },
      refresh: "刷新",
      auto_refresh: "自动刷新",
      last_updated: "最后更新"
    },
    vocabulary: {
      title: "词汇学习",
      translate: "翻译",
      source_lang: "源语言",
      target_lang: "目标语言",
      input_placeholder: "输入要翻译的文本...",
      auto_detect: "自动检测",
      clear: "清除",
      history: "翻译历史",
      recent_logs_dock: "最近日志",
      learning_tasks: "学习任务",
      auto_refresh: "自动刷新（5秒）",
      refresh: "刷新",
      failed: "失败",
      no_logs: "暂无最近日志",
      logs_moved_hint: "最近日志已移至左下角的悬浮面板。",
      open_logs_dock: "打开日志",
      delete_library: "删除词库",
      delete_library_confirm: "确定删除词库 \"{name}\"？该上传创建的单词将被删除；内置词典数据不受影响。",
      delete_library_success: "词库 \"{name}\" 已删除",
      delete_library_failed: "删除词库失败",
      login_required: "请先登录——此操作需要身份验证。",
      cancel: "取消",
      translate_failed: "翻译失败",
      tts_success: "语音生成成功",
      tts_failed: "语音生成失败",
      upload_success: "上传成功",
      upload_failed: "上传失败",
      export_success: "导出完成",
      export_failed: "导出失败，请重试。",
      export_no_words: "所选范围内没有可导出的单词。",
      export_popup_blocked: "请允许弹出窗口以导出 PDF（打印）。",
      export_server: "服务器导出完成：{filename}",
      export_fallback_html: "PDF 以可打印 HTML 形式生成——请打开下载的文件并使用浏览器的“另存为 PDF”。",
      export_fallback_client: "服务器导出不可用（404），已改用浏览器内导出。",
      extracting: "正在提取…",
      extract_done: "新增 {added} 个，跳过 {skipped} 个",
      extract_failed: "提取失败",
      extract_requires_update: "提取功能需要后端更新（未返回 document_id）——文件已上传但未执行提取。",
      review_empty: "全部完成！当前没有需要复习的单词。",
      review_login_hint: "登录后即可加载你的个人复习队列。",
      review_load_failed: "复习队列加载失败",
      review_submit_failed: "复习结果保存失败",
      stats_login_hint: "登录后查看你的学习统计。",
      stats_load_failed: "统计数据加载失败"
    },
    mcp: {
      title: "MCP 管理器",
      tabs: {
        screenshots: "截图",
        tasks: "任务分发",
        placeholder: "占位图",
        voice: "语音字幕",
        ocr: "OCR识别",
        settings: "设置"
      },
      screenshots: {
        upload: "上传",
        refresh: "刷新",
        latest: "最新",
        clear_all: "清空全部",
        search_placeholder: "搜索截图...",
        no_screenshots: "未找到截图",
        upload_hint: "点击上传按钮、拖放或粘贴（Ctrl+V）图片到这里",
        view: "查看",
        download: "下载",
        delete: "删除",
        copy_url: "复制链接",
        image_url: "图片链接",
        description: "描述",
        delete_confirm: "确定删除此截图？",
        clear_all_confirm: "⚠️ 危险操作：这将永久删除所有截图，此操作无法撤销。确定继续？",
        clear_all_final: "最终确认：删除所有截图？",
        upload_mode: "上传模式",
        single_upload: "单图上传",
        batch_upload: "批量上传",
        batch_desc: "每张图片分别保存",
        merge_upload: "合并上传",
        merge_desc: "多张图片合成一张",
        drop_here: "拖放图片到这里",
        paste_hint: "或使用 Ctrl+V / Cmd+V 粘贴",
        stats_total: "总截图数",
        search_by_filename: "按文件名搜索截图...",
        upload_dialog_title: "选择上传模式",
        single_file_upload: "单文件上传",
        single_file_desc: "上传一张图片",
        multi_file_upload: "多文件上传",
        multi_file_desc: "批量上传或合并多张图片",
        drop_or_click: "拖拽图片到这里或点击上传",
        supported_formats: "支持 JPG, PNG, GIF, WebP 等格式",
        batch_mode: "📚 批量模式",
        merge_mode: "🔗 合并模式",
        load_failed: "截图加载失败",
        stats_load_failed: "截图统计加载失败",
        search_failed: "搜索失败",
        load_image_failed: "图片加载失败",
        toast: {
          copied: "已复制到剪贴板！",
          copy_failed: "复制失败",
          copy_failed_manual: "复制失败，请手动复制"
        }
      },
      common: {
        retry: "重试",
        cancel: "取消",
        create: "创建",
        refresh: "刷新",
        delete: "删除",
        save: "保存",
        copy: "复制",
        add: "添加",
        reset: "重置",
        loading: "加载中...",
        all: "全部",
        today: "今日",
        latest: "最新",
        this_week: "本周",
        storage_used: "已用存储",
        total: "总计",
        pending: "等待中",
        processing: "处理中",
        in_progress: "进行中",
        completed: "已完成",
        failed: "失败",
        clear_all: "清空全部",
        select_all: "全选",
        deselect_all: "取消全选",
        size: "大小：",
        error_label: "错误："
      },
      tasks: {
        categories: "分类",
        create_category: "新建分类",
        category_name_placeholder: "分类名称...",
        category_created: "分类创建成功",
        create_category_failed: "分类创建失败",
        no_categories: "暂无分类",
        view_files: "查看文件",
        view_files_title: "查看该分类下的文件",
        add_new_task: "添加新任务",
        task_content: "任务内容",
        task_content_placeholder: "输入任务内容或粘贴 Markdown...",
        file_name_optional: "文件名（可选）",
        priority: "优先级",
        priority_low: "低",
        priority_normal: "普通",
        priority_high: "高",
        priority_urgent: "紧急",
        add_task: "添加任务",
        queue_title: "任务队列",
        search_tasks_placeholder: "搜索任务...",
        no_tasks: "队列中还没有任务",
        no_tasks_hint: "在上方添加任务即可开始",
        edit_status: "编辑状态",
        hide_content: "隐藏内容",
        view_content: "查看内容",
        delete_task: "删除任务",
        no_content: "（无内容）",
        created_label: "创建时间：",
        completed_label: "完成时间：",
        prompt_mapping: "提示词映射",
        prompt_file_path: "提示词文件路径",
        prompt_content: "提示词内容",
        prompt_content_placeholder: "输入提示词内容...",
        variables: "变量",
        save_prompt_mapping: "保存提示词映射",
        delete_task_confirm: "删除此任务？此操作无法撤销。",
        task_deleted: "任务已删除",
        delete_task_failed: "任务删除失败",
        select_category_hint: "选择一个分类以查看任务",
        category_files: "分类文件",
        files_total_prefix: "共",
        files_total_suffix: "个文件",
        no_files: "该分类下没有文件",
        load_categories_failed: "分类加载失败",
        load_tasks_failed: "任务加载失败",
        search_failed: "搜索失败"
      },
      placeholder: {
        stats_total: "已生成总数",
        generate_title: "生成占位图",
        width: "宽度 (px)",
        height: "高度 (px)",
        text_optional: "文字（可选）",
        text_placeholder: "占位图片",
        bg_color: "背景颜色",
        text_color: "文字颜色",
        format: "格式",
        mode: "模式",
        mode_simple: "简单",
        mode_real: "真实",
        generate: "生成",
        preview: "预览",
        generated_alt: "生成的占位图",
        dimensions_label: "尺寸：",
        format_label: "格式：",
        file_size_label: "文件大小：",
        no_placeholder: "尚未生成占位图",
        no_placeholder_hint: "填写表单后点击生成",
        recent: "最近",
        refresh_history: "刷新历史",
        cleanup: "清理",
        cleanup_title: "清理旧占位图",
        cleanup_confirm: "清理旧的占位图？这将删除未使用的占位图以释放存储空间。",
        delete_confirm: "删除此占位图？",
        no_history: "暂无历史记录",
        stats_load_failed: "占位图统计加载失败",
        generate_failed: "占位图生成失败"
      },
      voice: {
        stats_total: "总条目数",
        add_to_queue: "添加到语音队列",
        type_text: "文本",
        type_url: "链接",
        type_voice: "语音",
        type_image: "图片",
        choose_image: "选择图片",
        description_placeholder: "描述（可选）...",
        add_image_to_queue: "添加图片到队列",
        content_placeholder_text: "输入文本...",
        content_placeholder_url: "输入链接...",
        content_placeholder_voice: "输入语音内容...",
        now_playing: "正在播放",
        queue: "队列",
        all_groups: "全部分组",
        all_categories: "全部分类",
        clear_queue_title: "清空整个队列",
        group_name_placeholder: "分组名称",
        edit_group: "编辑分组",
        played_prefix: "已播放",
        played_suffix: "次",
        queue_empty: "队列为空",
        background_tasks: "后台任务",
        no_background_tasks: "暂无后台任务",
        delete_task: "删除任务",
        created_label: "创建时间：",
        updated_label: "更新时间：",
        delete_selected_confirm_prefix: "删除",
        delete_selected_confirm_suffix: "个选中条目？",
        clear_queue_confirm: "清空整个语音队列？此操作无法撤销。",
        delete_tasks_confirm_prefix: "删除",
        delete_tasks_confirm_suffix: "个后台任务？",
        load_queue_failed: "语音队列加载失败",
        stats_load_failed: "语音统计加载失败",
        groups_load_failed: "语音分组加载失败",
        languages_load_failed: "支持语言列表加载失败",
        categories_load_failed: "语音分类加载失败",
        settings_load_failed: "语音设置加载失败",
        tasks_load_failed: "后台任务加载失败"
      },
      ocr: {
        title: "OCR 识别",
        engine: "OCR 引擎",
        loading_engine_info: "正在加载引擎信息...",
        accuracy_label: "准确率：",
        languages_label: "支持语言：",
        speed_label: "速度：",
        upload_image: "上传图片",
        choose_image: "选择图片",
        preview: "预览",
        preview_alt: "OCR 预览",
        recognize: "识别",
        smart_recognize_title: "智能识别（自动选择引擎）",
        batch_recognition: "批量识别",
        choose_multiple_images: "选择多张图片",
        selected_prefix: "已选择",
        selected_suffix: "张图片",
        batch_recognize: "批量识别",
        batch_results: "批量识别结果",
        recognition_result: "识别结果",
        image_label: "图片",
        confidence_label: "置信度：",
        copy_text: "复制文本",
        no_text_detected: "未检测到文本",
        no_result: "暂无识别结果",
        no_result_hint: "上传图片后点击识别",
        engines_load_failed: "OCR 引擎加载失败",
        engine_info_load_failed: "引擎信息加载失败",
        recognize_failed: "OCR 识别失败",
        smart_recognize_failed: "智能 OCR 识别失败",
        batch_recognize_failed: "批量 OCR 识别失败"
      },
      settings: {
        title: "设置",
        coming_soon: "设置面板即将上线..."
      }
    },
    octane: {
      title: "Octane 定时任务",
      subtitle: "实时任务调度和执行监控",
      timer_status: "定时器状态",
      total_tasks: "总任务数",
      running_tasks: "运行中任务",
      completed_tasks: "已完成任务",
      failed_tasks: "失败任务"
    },
    taskCenter: {
      title: "任务中心",
      subtitle: "统一管理调度层（Octane 定时器）与队列层（global_tasks + 工作节点）",
      tabs: {
        overview: "总览",
        scheduler: "定时调度",
        queue: "任务队列",
        workers: "工作节点",
        assist: "协助请求"
      },
      refresh: "刷新",
      auto_refresh: "自动刷新",
      retry: "重试",
      load_failed: "加载任务中心总览失败",
      last_updated: "最后更新：",
      chips: {
        scheduler_running: "调度器运行中",
        scheduler_stopped: "调度器已停止",
        queue_pending: "等待中",
        workers_online: "节点在线"
      },
      roles: {
        producer: "生产",
        consumer: "消费",
        maintainer: "维护"
      },
      overview: {
        scheduler_card: "定时调度层",
        scheduler_card_sub: "Octane 定时器（进程内 cron）",
        queue_card: "任务队列",
        queue_card_sub: "global_tasks（持久化分布式队列）",
        workers_card: "执行者 / 工作节点",
        workers_card_sub: "分布式工作节点",
        ticks: "tick 次数",
        uptime: "运行时长",
        timer_tasks: "个定时任务",
        maintain_loop: "维护：超时释放 / 保留期清理",
        known_workers: {
          pycore: "pycore（Google 翻译）",
          chrome: "Chrome 扩展（Bing 词典）",
          internal_ai: "laravel-internal-ai（AI 兜底）"
        },
        relations_title: "调度 ⇄ 队列关系",
        relations_columns: {
          timer: "定时任务",
          role: "角色",
          target: "目标任务类型",
          interval: "间隔",
          runs: "运行次数",
          errors: "错误次数",
          registered: "已注册"
        },
        no_relations: "没有已注册的调度 ⇄ 队列关系",
        explainer_title: "两层任务机制的关系",
        explainer:
          "调度层 = 进程内 cron（状态在 Octane worker 内存中，重启即失）。队列层 = DB 持久化分布式队列，7 状态生命周期（pending → assigned → processing → completed / completed_demo / failed / cancelled）。定时任务充当队列的生产者（扫描入队）、消费者（内部 AI worker 兜底消化无外部节点认领的任务）与维护者（超时释放 + 保留期清理）。pycore 端同构：PyHeartbeat ≈ 调度层，本地 TaskManager ≈ 本地任务记录。"
      },
      workers_panel: {
        stats: {
          total: "总数",
          online: "在线",
          busy: "繁忙",
          offline: "离线",
          total_completed: "累计完成",
          total_failed: "累计失败"
        },
        role_hints: {
          pycore_translate: "pycore Google 翻译节点 — 外部 Python 端，处理 word_translation 任务",
          internal_ai: "Laravel 内部 AI 兜底节点 — 由消费者定时任务驱动，消化滞留的队列任务",
          generic: "通用外部工作节点"
        }
      },
      covers: {
        title: "封面生成与 AI",
        subtitle: "词库封面 — 队列状态、Laravel AI（gemini）与 pycore 图像后端（appqyv1_cover_generation 定时任务）",
        refresh: "刷新",
        retry_failed: "重试失败任务",
        load_failed: "加载封面状态失败",
        task: {
          enabled: "定时任务已启用",
          disabled: "定时任务已禁用",
          batch: "批量",
          retry_delay: "重试间隔"
        },
        queue: {
          pending: "等待中",
          retry: "待重试",
          processing: "处理中",
          ready: "已就绪",
          failed: "失败",
          leased: "第三方处理中"
        },
        queue_total: "总数",
        leased_hint: "已租约给第三方协助节点（如 pycore）",
        laravel_ai: "Laravel AI",
        pycore: "pycore",
        configured: "已配置",
        not_configured: "未配置",
        probe_available: "探测可用",
        probe_failed: "探测失败",
        not_probed: "未探测",
        reachable: "可达",
        unreachable: "不可达",
        image_capable: "支持图像生成",
        not_image_capable: "无图像供应商",
        no_providers: "无供应商信息",
        provider_image_mark: "支持图像",
        recent_failures: "最近失败",
        no_failures: "暂无最近失败",
        confirm_title: "重试失败的封面",
        confirm_message: "将全部 {count} 个失败的封面任务重置回重试队列？下一次调度运行时将重新生成。",
        confirm: "重试",
        cancel: "取消",
        retry_success: "已将 {count} 个失败封面加入重试队列",
        retry_error: "封面重试请求失败"
      }
    },
    globalTasks: {
      title: "全局任务",
      subtitle: "分布式工作队列 — 全局任务与工作节点",
      auto_refresh: "自动刷新",
      refresh: "刷新",
      retry: "重试",
      load_failed: "加载全局任务失败",
      timeout_hint: "请求超时 — Laravel 服务器未及时响应。",
      network_hint: "网络不可达 — laravel_main 是否在该主机上运行？",
      stats: {
        pending: "等待中",
        assigned: "已分配",
        processing: "处理中",
        completed: "已完成",
        completed_demo_suffix: "演示",
        failed: "失败",
        cancelled: "已取消",
        total: "总数",
        workers: "工作节点",
        online: "在线",
        busy: "繁忙",
        offline: "离线"
      },
      filter: "筛选：",
      search_placeholder: "按应用名或任务类型筛选...",
      tasks_suffix: "个任务",
      columns: {
        task_id: "任务 ID",
        app_name: "应用",
        task_type: "任务类型",
        execution_type: "执行方式",
        status: "状态",
        progress: "进度",
        assigned_to: "分配给",
        created_at: "创建时间",
        actions: "操作"
      },
      cancel: "取消",
      cancel_failed: "取消失败",
      cancelled_ok: "任务已取消",
      no_tasks: "当前筛选条件下没有任务",
      workers: {
        title: "工作节点",
        columns: {
          worker: "节点",
          status: "状态",
          processors: "处理器类型",
          completed: "已完成",
          failed: "失败",
          current_task: "当前任务",
          last_heartbeat: "最近心跳"
        },
        no_workers: "没有已注册的工作节点"
      },
      detail: {
        title: "任务详情",
        loading: "正在加载实时任务详情…",
        live: "实时数据",
        status: "状态",
        progress: "进度",
        app_name: "应用",
        task_type: "任务类型",
        execution_type: "执行方式",
        assigned_to: "分配给",
        error: "错误",
        result: "结果",
        result_truncated: "（结果已截断）",
        no_result: "无结果",
        created_at: "创建时间",
        updated_at: "更新时间",
        priority: "优先级",
        retries: "重试 / 上限 · 超时",
        completed_at: "完成时间",
        payload: "任务负载",
        capability: "能力",
        lane: "通道",
        fast_tier: "快速通道",
        timeline: "事件时间线",
        no_events: "暂无事件",
        phase: "当前阶段",
        elapsed: "已耗时",
        attempt: "尝试",
        bump: "提到最前",
        bumping: "提升中…",
        bumped_ok: "已提升优先级至",
        bump_failed: "提升失败",
        live_stream: "实时推送中",
        stream_offline: "快照（推送离线）"
      },
      sort: "排序：",
      sort_default: "默认",
      sort_priority_desc: "优先级 ↓",
      sort_priority_asc: "优先级 ↑",
      fast_only: "仅快速通道",
      never: "从未",
      just_now: "刚刚",
      last_updated: "最后更新："
    },
    api_tester: {
      title: "API 测试仪表板",
      search_placeholder: "按 #ID、路径或描述搜索...",
      select_app: "选择应用",
      endpoints: "个端点",
      endpoint: "端点",
      shared_headers: "共享请求头",
      save: "保存",
      reset: "重置",
      copy_headers: "复制请求头 JSON",
      authentication: "身份验证",
      required: "必需",
      optional: "可选",
      controller: "控制器",
      parameters: "参数",
      response_format: "响应格式",
      endpoint_url: "端点 URL",
      request_params: "请求参数 (JSON)",
      load_params: "加载",
      save_params: "保存",
      send_request: "发送请求",
      sending: "发送中...",
      response: "响应",
      no_endpoints: "未找到端点",
      select_send: "选择并发送 API 请求",
      view_response: "以在此处查看响应",
      empty_body: "（空响应体）",
      copy_response: "复制响应"
    },
    media_browser: {
      title: "媒体浏览器",
      upload: "上传",
      new_folder: "新建文件夹",
      refresh: "刷新",
      fullscreen: "全屏",
      auto_play: "自动播放",
      next: "下一个",
      no_preview: "无可用预览",
      loading: "加载中...",
      error: "加载媒体错误",
      folder_name: "文件夹名称",
      create_folder: "创建文件夹",
      cancel: "取消",
      upload_files: "上传文件",
      drop_files: "拖放文件到这里或点击上传"
    },
    code_browser: {
      title: "代码浏览器",
      search: "搜索文件...",
      no_files: "未找到文件",
      loading: "加载中...",
      error: "加载文件错误"
    },
    settings: {
      title: "系统设置",
      api_config: "API 配置",
      base_url: "基础 URL",
      api_key: "API 密钥",
      save: "保存",
      reset: "重置为默认",
      reset_to_origin: "恢复到同源",
      test_connection: "测试连接",
      saved: "设置保存成功",
      reset_success: "已重置为默认设置",
      reset_to_origin_success: "已恢复为浏览器同源地址",
      test_success: "连接成功",
      test_error: "连接失败",
      current_origin: "当前源",
      browser_origin: "浏览器源",
      auth_required: "设置页面需要身份验证。请登录后继续。"
    },
    invite_codes: {
      auth_required: "邀请码管理需要管理员权限。请使用管理员账户登录。"
    },
    server_manager: {
      auth_required: "服务器管理需要身份验证。请登录后继续。"
    },
    db_manager: {
      auth_required: "数据库管理需要登录。请登录后管理连接、表与备份。",
      credentials: {
        tab: "凭据",
        title: "凭据",
        superuser: "超级用户",
        driver: "驱动",
        password_auth: "密码认证",
        supported: "支持",
        not_applicable: "不适用",
        sync_note: "修改或重置密码时，也会同步 Laravel 自身的配置（凭据存储），以保证该连接继续可用。密码认证仅适用于 pgsql / mysql。",
        no_password_note: "该基于文件的数据库没有密码；凭据控制已禁用。",
        change: "修改密码",
        change_desc: "为该用户设置新密码。Laravel 配置会自动重新同步。",
        new_password: "新密码",
        confirm_password: "确认密码",
        passwords_no_match: "两次输入的密码不一致。",
        change_and_sync: "修改并同步",
        change_success: "密码已修改并同步到 Laravel 配置",
        change_not_synced: "密码已修改，但 Laravel 配置未同步——在重新同步前连接可能中断。",
        reset: "重置 root 密码",
        reset_desc: "生成一个全新的强密码。仅显示一次——请立即记录。",
        reset_and_generate: "重置并生成",
        reset_confirm: "当前密码将立即失效。新密码仅显示一次。",
        reset_success: "root 密码已重置并同步到 Laravel 配置",
        reset_not_synced: "密码已重置，但 Laravel 配置未同步——在重新同步前连接可能中断。",
        new_password_title: "新密码——请立即保存",
        store_now_warning: "请立即保存此密码——它不会再次显示。",
        stored_it: "我已保存",
        synced_note: "该密码已同步到 Laravel 的凭据存储，连接将继续可用。",
        not_synced_note: "警告：该密码未同步到 Laravel 的凭据存储——请手动重新同步，否则连接将中断。",
        copy: "复制",
        copied: "已复制"
      }
    },
    auth: {
      login_hint: "请登录以继续。",
      use_login_window: "请在弹出的登录窗口中完成验证。"
    },
    common: {
      close: "关闭"
    },
    server: {
      title: "服务器管理",
      subtitle: "Nginx 站点、SSL 证书和系统管理",
      tabs: {
        nginx: "Nginx 站点",
        ssl: "SSL 证书",
        system: "系统状态",
        files: "文件管理",
        executor: "代码执行",
        unified: "统一管理器"
      },
      nginx: {
        sites: "Nginx 站点",
        create_site: "创建站点",
        site_name: "站点名称",
        domain: "域名",
        site_type: "站点类型",
        www_dir: "网站目录",
        php_mode: "PHP 模式",
        swoole_port: "Swoole 端口",
        ssl_enabled: "启用 SSL",
        enabled: "已启用",
        disabled: "已禁用",
        enable: "启用",
        disable: "禁用",
        delete: "删除站点",
        view_config: "查看配置",
        test_config: "测试配置",
        reload: "重载 Nginx",
        refresh: "刷新",
        create: "创建站点",
        update: "更新站点",
        test: "测试配置",
        status: "Nginx 状态",
        installed: "已安装",
        not_installed: "未安装",
        running: "运行中",
        stopped: "已停止",
        version: "版本",
        start: "启动",
        stop: "停止",
        restart: "重启",
        logs: "Nginx 日志",
        access_log: "访问日志",
        error_log: "错误日志",
        lines: "行数",
        refresh_status: "刷新状态",
        install_hint_title: "Nginx 未安装",
        config_test: "配置检测",
        sites_count: "站点",
        service_manager: "服务管理器",
        processes: "个进程",
        valid: "有效",
        invalid: "无效",
        copy: "复制",
        copied: "已复制到剪贴板",
        no_log_file: "日志文件不存在",
        install: "安装 Nginx",
        installing: "安装中…可能需要几分钟",
        install_success: "Nginx 安装成功",
        install_failed: "Nginx 安装失败",
        already_installed: "Nginx 已安装",
        install_guidance: "Nginx 尚未安装。请使用上方状态卡中的安装按钮，或手动执行安装命令。",
        metrics_active: "活跃连接",
        metrics_requests: "请求数",
        metrics_memory: "内存",
        metrics_cpu: "CPU",
        metrics_unavailable: "指标不可用 — 未配置 nginx stub_status",
        main_config: "nginx.conf",
        worker_processes: "worker_processes",
        worker_connections: "worker_connections",
        conf_d_files: "conf.d 文件",
        config_file_missing: "配置文件不存在",
        truncated: "（已截断）",
        backups: "配置备份",
        backups_empty: "暂无备份",
        backup_restore: "恢复",
        backup_restore_title: "恢复备份",
        backup_restore_message: "确定恢复备份 {file} 吗？当前配置会先自动备份。",
        backup_restored: "备份已恢复",
        backup_type_update: "更新",
        backup_type_delete: "删除",
        cert_expires_in: "{days} 天后到期",
        cert_expired: "已过期",
        renew_cert: "续期证书",
        renew_cert_started: "已开始为 {domain} 续期证书",
        renew_cert_failed: "证书续期失败",
        confirm_stop: "停止 Nginx？由 Nginx 提供服务的站点将全部下线。",
        confirm_restart: "重启 Nginx？连接会短暂中断。",
        edit_config: "配置",
        save: "保存",
        saving: "保存中…",
        config_saved: "配置已保存",
        config_save_failed: "保存失败",
        config_load_failed: "配置加载失败（无法显示只读内容）",
        auto_follow: "自动跟随",
        filter_placeholder: "过滤关键字…",
        scanned_lines: "已扫描 {n} 行",
        batch: "批量",
        batch_enable: "启用所选",
        batch_disable: "禁用所选",
        batch_test: "测试",
        batch_selected: "已选 {n} 个",
        batch_summary: "批量{action}：成功 {ok} 个，失败 {fail} 个",
        no_sites: "未找到 Nginx 站点",
        site_enabled: "站点 {site} 已启用",
        site_disabled: "站点 {site} 已禁用",
        port_in_use: "端口 {port} 已被 {holder} 占用",
        cancel: "取消",
        close: "关闭",
        ports: "端口",
        modified: "修改时间"
      },
      ssl: {
        certificates: "SSL 证书",
        generate: "生成证书",
        renew: "续期全部",
        domain: "域名",
        expiry_date: "到期日期",
        days_until_expiry: "剩余天数",
        status: "状态",
        ok: "正常",
        warning: "警告",
        critical: "紧急",
        renew_all: "续期全部证书",
        certbot_detect: "检测 Certbot",
        certbot_install: "安装 Certbot"
      },
      system: {
        title: "系统状态",
        cpu: "CPU",
        memory: "内存",
        disk: "磁盘",
        services: "服务",
        refresh: "刷新",
        processes: "进程",
        storage: "存储",
        permissions: "权限"
      },
      files: {
        title: "文件管理",
        browse: "浏览",
        download: "下载",
        preview: "预览",
        info: "文件信息",
        path: "路径",
        size: "大小",
        modified: "修改时间",
        permissions: "权限"
      },
      executor: {
        title: "代码执行",
        scripts: "预定义脚本",
        execute: "执行",
        logs: "执行日志",
        status: "状态",
        category: "分类",
        timeout: "超时",
        output: "输出"
      },
      unified: {
        title: "统一管理器",
        apps: "应用列表",
        deploy: "部署",
        start: "启动",
        stop: "停止",
        restart: "重启",
        status: "状态",
        logs: "日志",
        service_name: "服务名称",
        port: "端口"
      },
      messages: {
        confirm_reset: "确定要重置为默认设置吗？",
        confirm_renew_certs: "确定要续期所有证书吗？",
        confirm_install_certbot: "确定要安装 Certbot 吗？",
        confirm_delete_site: "确定要删除站点: {site} 吗？",
        cert_generation_started: "证书生成已开始",
        cert_renewal_started: "证书续期已开始",
        certbot_installation_started: "Certbot 安装已开始",
        nginx_reloaded: "Nginx 重载成功",
        site_deleted: "站点删除成功",
        nginx_config_valid: "Nginx 配置有效！",
        nginx_config_errors: "配置错误：",
        operation_failed: "操作失败",
        action_completed: "操作 {action} 已完成",
        failed_to_generate_cert: "证书生成失败",
        failed_to_renew_certs: "证书续期失败",
        failed_to_install_certbot: "Certbot 安装失败"
      }
    }
  }
};

export const MOCK_FILE_TREE: FileNode[] = [
  // ... (Existing Mock File Tree - kept same)
  {
    id: 'root',
    name: 'wwwroot',
    type: 'folder',
    isOpen: true,
    children: [
      {
        id: 'laravel_db',
        name: 'laravel_db',
        type: 'folder',
        isOpen: true,
        children: [
          { id: 'static', name: 'static', type: 'folder', isOpen: true, children: [
            { id: 'img1', name: 'cyber_bg.jpg', type: 'file', fileType: 'image', size: '2.4 MB', date: '2025-01-10' },
            { id: 'aud1', name: 'alert_notification.mp3', type: 'file', fileType: 'audio', size: '150 KB', date: '2025-01-12' },
            { id: 'vid1', name: 'intro_sequence.mp4', type: 'file', fileType: 'video', size: '45 MB', date: '2025-01-15' },
            { id: 'doc1', name: 'readme.txt', type: 'file', fileType: 'text', size: '2 KB', date: '2025-01-05' },
            { id: 'code1', name: 'config.json', type: 'file', fileType: 'code', size: '5 KB', date: '2025-01-08' }
          ] }
        ]
      }
    ]
  }
];

export const MOCK_CODE_TREE: FileNode[] = [
    {
    id: 'core',
    name: 'core_node',
    type: 'folder',
    isOpen: true,
    children: []
    }
];

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: 'crypto',
    name: 'Crypto & Security',
    icon: Shield,
    tools: [
      { id: 'cry1', name: 'UUID Generator', status: 'available' },
      { id: 'cry_ulid', name: 'ULID Generator', status: 'available' },
      { id: 'cry_token', name: 'Token Generator', status: 'available' },
      { id: 'ut4', name: 'Password Generator', status: 'available' },
      { id: 'ut5', name: 'Password Strength', status: 'available' },
      { id: 'cry_hash', name: 'Hash Generator', status: 'available' },
      { id: 'cry_bcrypt', name: 'Bcrypt Hash/Verify', status: 'available' },
      { id: 'cry_enc', name: 'AES Encrypt', status: 'available' },
      { id: 'cry_dec', name: 'AES Decrypt', status: 'available' },
      { id: 'cry_hmac', name: 'HMAC Generator', status: 'available' },
      { id: 'cry_rsa', name: 'RSA Key Generator', status: 'available' },
      { id: 'cry_otp_gen', name: 'OTP Generator', status: 'available' },
      { id: 'cry_otp_ver', name: 'OTP Verify', status: 'available' },
      { id: 'cry_bip39', name: 'BIP39 Passphrase', status: 'todo' },
      { id: 'cry_basic_auth', name: 'Basic Auth Header', status: 'available' },
    ]
  },
  {
    id: 'converters',
    name: 'Converters',
    icon: RefreshCcw,
    tools: [
      { id: 'cv1', name: 'Base64 Converter', status: 'available' },
      { id: 'cv2', name: 'URL Encoder', status: 'available' },
      { id: 'cv4', name: 'Case Converter', status: 'available' },
      { id: 'cv11', name: 'JSON ⇄ YAML', status: 'available' },
      { id: 'cv6', name: 'Timestamp Converter', status: 'available' },
      { id: 'conv_temp', name: 'Temperature Converter', status: 'available' },
      { id: 'conv_roman', name: 'Roman Numerals', status: 'available' },
      { id: 'col1', name: 'HEX to RGB', status: 'available' },
    ]
  },
  {
    id: 'web',
    name: 'Web Tools',
    icon: Globe,
    tools: [
      { id: 'web_jwt', name: 'JWT Parser', status: 'available' },
      { id: 'web_md', name: 'Markdown to HTML', status: 'available' },
      { id: 'gen1', name: 'QR Code Generator', status: 'available' },
      { id: 'web_wifi', name: 'WiFi QR Code', status: 'available' },
      { id: 'web_url_parse', name: 'URL Parser', status: 'todo' }, // Placeholder
    ]
  },
  {
    id: 'formatters',
    name: 'Formatters',
    icon: FileJson,
    tools: [
      { id: 'fmt1', name: 'JSON Formatter', status: 'available' },
      { id: 'web_json_min', name: 'JSON Minify', status: 'available' },
      { id: 'fmt4', name: 'SQL Formatter', status: 'available' },
      { id: 'web_xml', name: 'XML Formatter', status: 'available' },
      { id: 'web_yaml', name: 'YAML Formatter', status: 'available' },
    ]
  },
  {
    id: 'image',
    name: 'Image Tools',
    icon: ImageIcon,
    tools: [
      { id: 'img2', name: 'Image Compressor', status: 'available' },
      { id: 'adv_img_crop', name: 'Image Cropper', status: 'available' },
    ]
  },
  {
    id: 'pdf',
    name: 'PDF Tools',
    icon: FileText,
    tools: [
      { id: 'adv_pdf_split', name: 'PDF Splitter', status: 'available' },
    ]
  },
  {
    id: 'calc',
    name: 'Calculators',
    icon: Calculator,
    tools: [
      { id: 'calc1', name: 'Age Calculator', status: 'available' },
    ]
  },
  {
    id: 'text_adv',
    name: 'Text Advanced',
    icon: Edit3,
    tools: [
      { id: 'ta4', name: 'Word Counter', status: 'available' },
    ]
  }
];

export const MOCK_TASKS: TaskItem[] = [
    { 
      id: 'task1', 
      title: 'Init System', 
      size: '1KB', 
      date: '2025-01-01', 
      status: 'done', 
      promptText: 'Initialize system core parameters and establish neural handshake protocol. Ensure all subsystems are green.', 
      audioSegments: [
        { id: 'seg1', text: "Initializing system core...", duration: 2.5 },
        { id: 'seg2', text: "Establishing neural handshake...", duration: 3.2 },
        { id: 'seg3', text: "Handshake complete. Subsystems green.", duration: 2.8 },
        { id: 'seg4', text: "System online.", duration: 1.5 }
      ] 
    }
];

export const DEFAULT_API_CONFIGS: Record<string, ToolConfig> = {
  'calc1': { toolId: 'calc1', apiUrl: '', mode: 'local' }, 
  'col1': { toolId: 'col1', apiUrl: '', mode: 'local' }, 
  'ut4': { toolId: 'ut4', apiUrl: '', mode: 'local' }, 
  'ta4': { toolId: 'ta4', apiUrl: '', mode: 'local' }, 
};

// --- TOOL UI SCHEMAS ---
export const TOOL_UI_SCHEMAS: Record<string, ToolUISchema> = {
  // --- Crypto ---
  'cry1': {
    id: 'cry1', title: 'UUID Generator', description: 'Generate UUID v4 identifiers.',
    inputs: [{ id: 'count', label: 'Count', type: 'number', defaultValue: 1 }, { id: 'uppercase', label: 'Uppercase', type: 'checkbox' }],
    actions: [{ id: 'gen', label: 'Generate', icon: Shield, apiPath: '/api/ittools/v1/crypto/uuid/generate' }],
    outputs: [{ id: 'uuids', label: 'UUIDs', type: 'json' }]
  },
  'cry_ulid': {
    id: 'cry_ulid', title: 'ULID Generator', description: 'Generate Universally Unique Lexicographically Sortable Identifiers.',
    inputs: [{ id: 'count', label: 'Count', type: 'number', defaultValue: 1 }],
    actions: [{ id: 'gen', label: 'Generate', icon: Shield, apiPath: '/api/ittools/v1/crypto/ulid/generate' }],
    outputs: [{ id: 'ulids', label: 'ULIDs', type: 'json' }]
  },
  'cry_token': {
    id: 'cry_token', title: 'Token Generator', description: 'Generate random security tokens.',
    inputs: [
        { id: 'length', label: 'Length', type: 'number', defaultValue: 32 },
        { id: 'charset', label: 'Charset', type: 'select', options: [{label:'Alphanumeric', value:'alphanumeric'}, {label:'Hex', value:'hex'}, {label:'Numeric', value:'numeric'}] }
    ],
    actions: [{ id: 'gen', label: 'Generate', icon: Key, apiPath: '/api/ittools/v1/crypto/token/generate' }],
    outputs: [{ id: 'tokens', label: 'Tokens', type: 'json' }]
  },
  'cry_hash': {
    id: 'cry_hash', title: 'Hash Generator', description: 'Calculate MD5, SHA1, SHA256, SHA512 hashes.',
    inputs: [
        { id: 'text', label: 'Text', type: 'textarea' },
        { id: 'algorithm', label: 'Algorithm', type: 'select', options: [{label:'SHA256', value:'sha256'}, {label:'MD5', value:'md5'}, {label:'SHA1', value:'sha1'}, {label:'SHA512', value:'sha512'}] }
    ],
    actions: [{ id: 'hash', label: 'Calculate Hash', icon: Hash, apiPath: '/api/ittools/v1/crypto/hash' }],
    outputs: [{ id: 'hash', label: 'Hash Value', type: 'text' }]
  },
  'cry_bcrypt': {
    id: 'cry_bcrypt', title: 'Bcrypt Hash & Verify', description: 'Generate or verify Bcrypt password hashes.',
    inputs: [
        { id: 'password', label: 'Password', type: 'text' },
        { id: 'rounds', label: 'Rounds (Hash only)', type: 'number', defaultValue: 10 },
        { id: 'hash', label: 'Existing Hash (Verify only)', type: 'text', placeholder: '$2y$10$...' }
    ],
    actions: [
        { id: 'hash', label: 'Generate Hash', icon: Lock, apiPath: '/api/ittools/v1/crypto/bcrypt/hash' },
        { id: 'verify', label: 'Verify Hash', icon: CheckCircle, apiPath: '/api/ittools/v1/crypto/bcrypt/verify' }
    ],
    outputs: [{ id: 'hash', label: 'Generated Hash', type: 'text' }, { id: 'valid', label: 'Verification Result', type: 'json' }]
  },
  'ut5': {
    id: 'ut5', title: 'Password Strength', description: 'Analyze password entropy.',
    inputs: [{ id: 'password', label: 'Password', type: 'text' }],
    actions: [{ id: 'check', label: 'Analyze', icon: Shield, apiPath: '/api/ittools/v1/crypto/password/analyze' }],
    outputs: [{ id: 'score', label: 'Analysis', type: 'json' }]
  },
  'cry_enc': {
      id: 'cry_enc', title: 'AES Encryption', description: 'Encrypt text using AES.',
      inputs: [{ id: 'text', label: 'Text', type: 'textarea' }, { id: 'key', label: 'Key', type: 'text' }],
      actions: [{ id: 'encrypt', label: 'Encrypt', icon: Lock, apiPath: '/api/ittools/v1/crypto/encrypt' }],
      outputs: [{ id: 'encrypted', label: 'Encrypted Text', type: 'text' }]
  },
  'cry_dec': {
      id: 'cry_dec', title: 'AES Decryption', description: 'Decrypt AES text.',
      inputs: [{ id: 'encrypted', label: 'Encrypted Data', type: 'textarea' }, { id: 'key', label: 'Key', type: 'text' }],
      actions: [{ id: 'decrypt', label: 'Decrypt', icon: Lock, apiPath: '/api/ittools/v1/crypto/decrypt' }],
      outputs: [{ id: 'decrypted', label: 'Decrypted Text', type: 'text' }]
  },
  'cry_hmac': {
      id: 'cry_hmac', title: 'HMAC Generator', description: 'Create Hash-based Message Authentication Codes.',
      inputs: [
          { id: 'text', label: 'Text', type: 'textarea' },
          { id: 'secret', label: 'Secret Key', type: 'text' },
          { id: 'algorithm', label: 'Algorithm', type: 'select', options: [{label:'SHA256', value:'sha256'}, {label:'SHA512', value:'sha512'}] }
      ],
      actions: [{ id: 'gen', label: 'Generate', icon: Hash, apiPath: '/api/ittools/v1/crypto/hmac' }],
      outputs: [{ id: 'hmac', label: 'HMAC', type: 'text' }]
  },
  'cry_rsa': {
      id: 'cry_rsa', title: 'RSA Key Generator', description: 'Generate RSA Key Pairs.',
      inputs: [{ id: 'key_size', label: 'Key Size', type: 'select', options: [{label:'2048 bit', value:'2048'}, {label:'4096 bit', value:'4096'}] }],
      actions: [{ id: 'gen', label: 'Generate Keys', icon: Shield, apiPath: '/api/ittools/v1/crypto/rsa/generate' }],
      outputs: [{ id: 'publicKey', label: 'Public Key', type: 'text' }, { id: 'privateKey', label: 'Private Key', type: 'text' }]
  },
  'cry_otp_gen': {
      id: 'cry_otp_gen', title: 'OTP Generator', description: 'Generate TOTP Secret and Code.',
      inputs: [],
      actions: [{ id: 'gen', label: 'Generate Secret', icon: Clock, apiPath: '/api/ittools/v1/crypto/otp/generate' }],
      outputs: [{ id: 'otp', label: 'Current OTP', type: 'text' }, { id: 'secret', label: 'Secret', type: 'text' }]
  },
  'cry_otp_ver': {
      id: 'cry_otp_ver', title: 'OTP Verifier', description: 'Verify TOTP Codes.',
      inputs: [{ id: 'otp', label: 'OTP Code', type: 'text' }, { id: 'secret', label: 'Secret Key', type: 'text' }],
      actions: [{ id: 'ver', label: 'Verify', icon: Check, apiPath: '/api/ittools/v1/crypto/otp/verify' }],
      outputs: [{ id: 'valid', label: 'Is Valid?', type: 'json' }]
  },
  'cry_bip39': {
      id: 'cry_bip39', title: 'BIP39 Generator', description: 'Generate Mnemonic Phrases.',
      inputs: [{ id: 'strength', label: 'Strength', type: 'select', options: [{label:'128 bit', value:'128'}, {label:'256 bit', value:'256'}] }],
      actions: [{ id: 'gen', label: 'Generate', icon: Key, apiPath: '/api/ittools/v1/crypto/bip39/generate' }],
      outputs: [{ id: 'mnemonics', label: 'Mnemonic', type: 'json' }]
  },
  'cry_basic_auth': {
      id: 'cry_basic_auth', title: 'Basic Auth Generator', description: 'Create HTTP Basic Auth Headers.',
      inputs: [{ id: 'username', label: 'Username', type: 'text' }, { id: 'password', label: 'Password', type: 'text' }],
      actions: [{ id: 'gen', label: 'Generate', icon: Lock, apiPath: '/api/ittools/v1/crypto/basic-auth' }],
      outputs: [{ id: 'header', label: 'Header Key', type: 'text' }, { id: 'value', label: 'Header Value', type: 'text' }]
  },

  // --- Converters ---
  'cv1': {
    id: 'cv1', title: 'Base64 Tool', description: 'Encode/Decode Base64.',
    inputs: [{ id: 'text', label: 'Input', type: 'textarea' }, { id: 'encoded', label: 'Encoded Input', type: 'textarea' }],
    actions: [
        { id: 'enc', label: 'Encode', icon: Play, apiPath: '/api/ittools/v1/converter/base64/encode' },
        { id: 'dec', label: 'Decode', icon: Play, apiPath: '/api/ittools/v1/converter/base64/decode' }
    ],
    outputs: [{ id: 'encoded', label: 'Encoded', type: 'text' }, { id: 'decoded', label: 'Decoded', type: 'text' }]
  },
  'cv2': {
      id: 'cv2', title: 'URL Tool', description: 'Encode/Decode URLs.',
      inputs: [{ id: 'url', label: 'URL', type: 'textarea' }, { id: 'encoded', label: 'Encoded URL', type: 'textarea' }],
      actions: [
          { id: 'enc', label: 'Encode', icon: Link, apiPath: '/api/ittools/v1/converter/url/encode' },
          { id: 'dec', label: 'Decode', icon: Link, apiPath: '/api/ittools/v1/converter/url/decode' }
      ],
      outputs: [{ id: 'encoded', label: 'Encoded', type: 'text' }, { id: 'decoded', label: 'Decoded', type: 'text' }]
  },
  'cv4': {
    id: 'cv4', title: 'Case Converter', description: 'Convert text casing.',
    inputs: [{ id: 'text', label: 'Text Input', type: 'textarea' }],
    actions: [{ id: 'convert', label: 'Convert', icon: Type, apiPath: '/api/ittools/v1/converter/case' }],
    outputs: [{ id: 'snake_case', label: 'Snake Case', type: 'text' }, { id: 'camelCase', label: 'Camel Case', type: 'text' }]
  },
  'cv11': {
      id: 'cv11', title: 'JSON <> YAML', description: 'Convert between JSON and YAML.',
      inputs: [{ id: 'json', label: 'JSON Input', type: 'textarea' }, { id: 'yaml', label: 'YAML Input', type: 'textarea' }],
      actions: [
          { id: 'to_yaml', label: 'To YAML', icon: RefreshCcw, apiPath: '/api/ittools/v1/converter/json-to-yaml' },
          { id: 'to_json', label: 'To JSON', icon: RefreshCcw, apiPath: '/api/ittools/v1/converter/yaml-to-json' }
      ],
      outputs: [{ id: 'yaml', label: 'YAML Result', type: 'text' }, { id: 'json', label: 'JSON Result', type: 'text' }]
  },
  'conv_temp': {
      id: 'conv_temp', title: 'Temperature Converter', description: 'Convert C/F/K.',
      inputs: [
          { id: 'value', label: 'Value', type: 'number' },
          { id: 'from', label: 'From Unit', type: 'select', options: [{label:'Celsius', value:'celsius'}, {label:'Fahrenheit', value:'fahrenheit'}, {label:'Kelvin', value:'kelvin'}] }
      ],
      actions: [{ id: 'conv', label: 'Convert', icon: RefreshCcw, apiPath: '/api/ittools/v1/converter/temperature' }],
      outputs: [{ id: 'celsius', label: 'Celsius', type: 'text' }, { id: 'fahrenheit', label: 'Fahrenheit', type: 'text' }, { id: 'kelvin', label: 'Kelvin', type: 'text' }]
  },
  'conv_roman': {
      id: 'conv_roman', title: 'Roman Numerals', description: 'Convert Roman to Arabic.',
      inputs: [{ id: 'roman', label: 'Roman Numeral', type: 'text' }],
      actions: [{ id: 'conv', label: 'Convert', icon: Hash, apiPath: '/api/ittools/v1/converter/roman/to-arabic' }],
      outputs: [{ id: 'arabic', label: 'Arabic Number', type: 'text' }]
  },
  'cv6': {
    id: 'cv6', title: 'Timestamp Converter', description: 'Convert DateTime formats.',
    inputs: [
      { id: 'input', label: 'Date String', type: 'text' },
      { id: 'inputFormat', label: 'Format', type: 'select', options: [{label: 'ISO 8601', value: 'iso8601'}, {label: 'Unix Timestamp', value: 'unix'}] }
    ],
    actions: [{ id: 'conv', label: 'Convert', icon: Clock, apiPath: '/api/ittools/v1/converter/datetime' }],
    outputs: [{ id: 'iso8601', label: 'ISO', type: 'text' }, { id: 'unix', label: 'Unix', type: 'text' }]
  },

  // --- Web Tools & Formatters ---
  'fmt1': {
    id: 'fmt1', title: 'JSON Formatter', description: 'Prettify JSON.',
    inputs: [{ id: 'json', label: 'Raw JSON', type: 'textarea' }, { id: 'indent', label: 'Indent', type: 'number', defaultValue: 2 }],
    actions: [{ id: 'fmt', label: 'Beautify', icon: AlignLeft, apiPath: '/api/ittools/v1/web/json/prettify' }],
    outputs: [{ id: 'prettified', label: 'Formatted JSON', type: 'text' }]
  },
  'web_json_min': {
    id: 'web_json_min', title: 'JSON Minifier', description: 'Minify JSON.',
    inputs: [{ id: 'json', label: 'JSON', type: 'textarea' }],
    actions: [{ id: 'min', label: 'Minify', icon: AlignLeft, apiPath: '/api/ittools/v1/web/json/minify' }],
    outputs: [{ id: 'minified', label: 'Minified JSON', type: 'text' }]
  },
  'web_xml': {
      id: 'web_xml', title: 'XML Formatter', description: 'Format XML string.',
      inputs: [{ id: 'xml', label: 'XML', type: 'textarea' }],
      actions: [{ id: 'fmt', label: 'Format', icon: AlignLeft, apiPath: '/api/ittools/v1/web/xml/format' }],
      outputs: [{ id: 'formatted', label: 'Result', type: 'text' }]
  },
  'web_yaml': {
      id: 'web_yaml', title: 'YAML Formatter', description: 'Format YAML string.',
      inputs: [{ id: 'yaml', label: 'YAML', type: 'textarea' }],
      actions: [{ id: 'fmt', label: 'Format', icon: AlignLeft, apiPath: '/api/ittools/v1/web/yaml/format' }],
      outputs: [{ id: 'formatted', label: 'Result', type: 'text' }]
  },
  'fmt4': {
      id: 'fmt4', title: 'SQL Formatter', description: 'Format SQL queries.',
      inputs: [{ id: 'sql', label: 'SQL', type: 'textarea' }],
      actions: [{ id: 'fmt', label: 'Format', icon: AlignLeft, apiPath: '/api/ittools/v1/web/sql/format' }],
      outputs: [{ id: 'formatted', label: 'Formatted SQL', type: 'text' }]
  },
  'web_md': {
      id: 'web_md', title: 'Markdown to HTML', description: 'Render Markdown.',
      inputs: [{ id: 'markdown', label: 'Markdown', type: 'textarea' }],
      actions: [{ id: 'conv', label: 'Convert', icon: FileText, apiPath: '/api/ittools/v1/web/markdown/to-html' }],
      outputs: [{ id: 'html', label: 'HTML Preview', type: 'html' }]
  },
  'web_jwt': {
      id: 'web_jwt', title: 'JWT Parser', description: 'Decode JSON Web Tokens.',
      inputs: [{ id: 'token', label: 'JWT Token', type: 'textarea' }],
      actions: [{ id: 'parse', label: 'Parse', icon: Lock, apiPath: '/api/ittools/v1/web/jwt/parse' }],
      outputs: [{ id: 'header', label: 'Header', type: 'json' }, { id: 'payload', label: 'Payload', type: 'json' }]
  },
  'gen1': {
    id: 'gen1', title: 'QR Code Generator', description: 'Generate QR codes.',
    inputs: [{ id: 'text', label: 'Content', type: 'text' }, { id: 'size', label: 'Size (px)', type: 'number', defaultValue: 300 }],
    actions: [{ id: 'gen', label: 'Generate', icon: QrCode, apiPath: '/api/ittools/v1/web/qr-code/generate' }],
    outputs: [{ id: 'qrCodeUrl', label: 'QR Code', type: 'image-preview' }]
  },
  'web_wifi': {
      id: 'web_wifi', title: 'WiFi QR Code', description: 'Generate WiFi Access QR.',
      inputs: [
          { id: 'ssid', label: 'SSID', type: 'text' },
          { id: 'password', label: 'Password', type: 'text' },
          { id: 'encryption', label: 'Encryption', type: 'select', options: [{label:'WPA/WPA2', value:'WPA'}, {label:'WEP', value:'WEP'}, {label:'None', value:'nopass'}] }
      ],
      actions: [{ id: 'gen', label: 'Generate', icon: Wifi, apiPath: '/api/ittools/v1/web/wifi-qr-code/generate' }],
      outputs: [{ id: 'qrCodeUrl', label: 'WiFi QR', type: 'image-preview' }]
  },

  // --- Advanced ---
  'img2': {
    id: 'img2', title: 'Image Compressor', description: 'Reduce image size.',
    inputs: [{ id: 'image', label: 'Images', type: 'file', accept: 'image/*' }, { id: 'quality', label: 'Quality (%)', type: 'number', defaultValue: 80 }],
    actions: [{ id: 'compress', label: 'Compress', icon: Upload, apiPath: '/api/ittools/v1/advanced/image/compress' }],
    outputs: [{ id: 'image_data', label: 'Optimized Image', type: 'image-preview' }]
  },
  'adv_img_crop': {
    id: 'adv_img_crop', title: 'Image Cropper', description: 'Crop images.',
    inputs: [
        { id: 'image', label: 'Image', type: 'file', accept: 'image/*' },
        { id: 'width', label: 'Width (px)', type: 'number', defaultValue: 300 },
        { id: 'height', label: 'Height (px)', type: 'number', defaultValue: 300 }
    ],
    actions: [{ id: 'crop', label: 'Crop', icon: Upload, apiPath: '/api/ittools/v1/advanced/image/crop' }],
    outputs: [{ id: 'image_data', label: 'Result', type: 'image-preview' }]
  },
  'adv_pdf_split': {
      id: 'adv_pdf_split', title: 'PDF Splitter', description: 'Split PDF pages.',
      inputs: [{ id: 'pdf', label: 'PDF File', type: 'file', accept: 'application/pdf' }, { id: 'ranges', label: 'Ranges (1-2,5)', type: 'text' }],
      actions: [{ id: 'split', label: 'Split', icon: Upload, apiPath: '/api/ittools/v1/advanced/pdf/split' }],
      outputs: [{ id: 'files', label: 'Files', type: 'json' }]
  }
};
