// const { env } = require("#@global_vars");
const path = require(`path`)
const { gdir, appname, isServer } = require('#@global_vars');
const {
    ROOT_APP_CACHE_DIR,
    ROOT_APP_STATIC_DIR,
    APP_METADATA_DIR,
} = gdir;
const SHARE_DIR = ROOT_APP_STATIC_DIR ? path.join(ROOT_APP_STATIC_DIR, 'share') : null;
const WWWROOT_DIR = SHARE_DIR;
const ALLOW_DOWNLOAD_DIR = SHARE_DIR;

const SKIP_DIRS = [
    'node_modules',
    '.git',
    '.get',
    '.svn',
    '.hg',
    '__pycache__',
    '.DS_Store',
    'Thumbs.db',
    '.idea',
    '.vscode',
    'dist',
    'build',
    'out',
    'logs',
    'tmp',
    'temp',
    '.cache',
    '.next',
    '.nuxt',
    '.expo',
    '.angular',
    '.meteor',
    '.serverless',
    '.venv',
    '.env',
    '.history',
    '.sass-cache',
    '.nyc_output',
    '.parcel-cache',
    '.eslintcache',
    '.turbo',
    '.vercel',
    '.firebase',
    '.netlify',
    '.output',
    '.tmp',
    '.log',
    '.coverage',
    '.pytest_cache',
    '.tox',
    '.mypy_cache',
    '.pytest_cache',
    '.cache-loader',
    '.gradle',
    '.idea',
    '.settings',
    '.classpath',
    '.project',
    '.c9',
    '.sublime-project',
    '.sublime-workspace',
    '.yarn',
    '.pnp',
    '.pnp.js',
    '.history',
    '.npm',
    '.nvm',
    '.rbenv',
    '.bundle',
    '.jekyll-metadata',
    '.sass-cache',
    '.jekyll-cache',
    '.next',
    '.expo',
    '.angular',
    '.meteor',
    '.serverless',
    '.venv',
    '.env',
    '.history',
    '.sass-cache',
    '.nyc_output',
    '.parcel-cache',
    '.eslintcache',
    '.turbo',
    '.vercel',
    '.firebase',
    '.netlify',
    '.output',
    '.tmp',
    '.log',
    '.coverage',
    '.pytest_cache',
    '.tox',
    '.mypy_cache',
    '.pytest_cache',
    '.cache-loader',
    '.gradle',
    '.idea',
    '.settings',
    '.classpath',
    '.project',
    '.c9',
    '.sublime-project',
    '.sublime-workspace',
    '.yarn',
    '.pnp',
    '.pnp.js',
    '.history',
    '.npm',
    '.nvm',
    '.rbenv',
    '.bundle',
    '.jekyll-metadata',
    '.sass-cache',
    '.jekyll-cache'
];
const UPLOAD_DIRS_CACHE_TTL = 5000;
const UPDATE_CACHE_DIR = path.join(ROOT_APP_CACHE_DIR, 'update_cache');

const config = {
    HTTP_PORT: 3900,
    SHARE_DIR: SHARE_DIR,
    WWWROOT_DIR: WWWROOT_DIR,
    SKIP_DIRS: SKIP_DIRS,
    UPLOAD_DIRS_CACHE_TTL: UPLOAD_DIRS_CACHE_TTL,
    UPDATE_CACHE_DIR: UPDATE_CACHE_DIR,
    ALLOW_DOWNLOAD_DIR: ALLOW_DOWNLOAD_DIR,
}

module.exports = config;

