# -*- coding: utf-8 -*-
"""
Per-engine test parameter definitions for every TTS engine.

Each entry declares the fields the engine accepts for a live test call,
plus metadata that the frontend uses to render the correct form controls.
The field keys match the kwargs accepted by ``tts_test()`` /
``synthesize_engine()`` in ``tts_orchestrator.py``.
"""

from typing import Any, Dict, List

# Shared language options used by every engine that accepts a language field.
_COMMON_LANGS: List[Dict[str, str]] = [
    {"value": "en", "label": "English"},
    {"value": "zh", "label": "中文"},
    {"value": "ja", "label": "日本語"},
    {"value": "ko", "label": "한국어"},
    {"value": "es", "label": "Español"},
    {"value": "fr", "label": "Français"},
]

# ---- per-engine definitions ------------------------------------------------


TTS_ENGINE_TEST_PARAMS: Dict[str, Dict[str, Any]] = {
    # -- inline / cloud engines (not managed by tts_service_manager) ----------
    "edge": {
        "fields": ["text", "language", "rate", "gender"],
        "text_default": "The quick brown fox jumps over the lazy dog.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "rate_hint": "e.g. -20% or +10%",
        "rate_placeholder": "-20%",
        "gender_options": [
            {"value": "", "label": "Default"},
            {"value": "female", "label": "Female"},
            {"value": "male", "label": "Male"},
        ],
        "accent_aware": True,
        "note": "Microsoft Edge TTS (online). Rate-limited; 403 triggers cooldown.",
    },
    "streamelements": {
        "fields": ["text", "language", "accent"],
        "text_default": "This is a test of the StreamElements text to speech engine.",
        "language_options": [{"value": "en", "label": "English"}],
        "language_default": "en",
        "accent_options": [
            {"value": "us", "label": "US (Joanna)"},
            {"value": "uk", "label": "UK (Amy)"},
        ],
        "accent_default": "us",
        "lang_restriction": "en",
        "requires_key": True,
        "key_env": "STREAMELEMENTS_API_KEY",
        "note": "StreamElements speech endpoint (online). English only; needs API key.",
    },
    "gtts_web": {
        "fields": ["text", "language"],
        "text_default": "Hello, this is a Google Translate text to speech test.",
        "text_max_chars": 200,
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "note": "Google Translate web TTS (online, keyless). ~200 char cap.",
    },
    "azure": {
        "fields": ["text", "language", "rate"],
        "text_default": "This is an Azure Speech synthesis test.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "rate_hint": "SSML prosody rate",
        "rate_placeholder": "1.0",
        "requires_key": True,
        "key_env": "AZURE_SPEECH_KEY",
        "quota": "free-F0",
        "note": "Azure Speech cloud (free F0 ~0.5M chars/mo). API fallback.",
    },

    # -- managed model engines (in-process, loaded on first call) -------------
    "sherpa": {
        "fields": ["text", "language", "speed"],
        "text_default": "The quick brown fox jumps over the lazy dog.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "speed_default": 1.0,
        "speed_min": 0.5,
        "speed_max": 2.0,
        "speed_step": 0.1,
        "model_managed": True,
        "model_idle_unload_s": 60,
        "note": "Sherpa-ONNX Kokoro offline (CPU). Fast once loaded.",
    },
    "kokoro": {
        "fields": ["text", "language", "speed"],
        "text_default": "The quick brown fox jumps over the lazy dog.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "speed_default": 1.0,
        "speed_min": 0.5,
        "speed_max": 2.0,
        "speed_step": 0.1,
        "model_managed": True,
        "model_idle_unload_s": 60,
        "note": "Kokoro-82M via sherpa-onnx (zh/en offline). KOKORO_TTS_MODEL_DIR for weights.",
    },
    "melotts": {
        "fields": ["text", "language", "speed"],
        "text_default": "This is a MeloTTS synthesis test.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "speed_default": 1.0,
        "speed_min": 0.5,
        "speed_max": 2.0,
        "speed_step": 0.1,
        "model_managed": True,
        "model_idle_unload_s": 60,
        "long_wait": True,
        "note": "MeloTTS offline (torch GPU→CPU auto). First run downloads HF weights.",
    },
    "qwen3tts": {
        "fields": ["text", "language", "speaker", "instruct"],
        "text_default": "Hello, this is a test of the Qwen text to speech engine.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "speaker_placeholder": "Ryan",
        "speaker_hint": "Ryan (en) / Vivian (zh) / Ono_Anna (ja) / Sohee (ko)",
        "instruct_placeholder": "cheerful and energetic",
        "instruct_hint": "Voice style / emotion instruction (env QWEN3TTS_INSTRUCT)",
        "model_managed": True,
        "model_idle_unload_s": 60,
        "long_wait": True,
        "note": "Qwen3-TTS in-process (Alibaba). First run downloads HF model; 2–5 min cold start.",
    },
    "bark": {
        "fields": ["text", "language"],
        "text_default": "Hello, this is a Bark text to speech test.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "lang_ignored": True,
        "model_managed": True,
        "model_idle_unload_s": 60,
        "long_wait": True,
        "note": "Bark via transformers (suno/bark). Ignores language/speed; uses BARK_VOICE_PRESET.",
    },
    "parler": {
        "fields": ["text", "language", "description"],
        "text_default": "This is a Parler TTS test with a natural voice description.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "lang_ignored": True,
        "speed_ignored": True,
        "description_placeholder": "A clear, close recording with a neutral tone at moderate speed.",
        "description_hint": "Natural-language voice description (env PARLER_DESCRIPTION)",
        "model_managed": True,
        "model_idle_unload_s": 60,
        "long_wait": True,
        "note": "Parler-TTS in-process (HF). Voice description steers the output style.",
    },
    "voxcpm2": {
        "fields": ["text", "language", "cfg_value", "timesteps"],
        "text_default": "This is a VoxCPM2 synthesis test.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "lang_ignored": True,
        "speed_ignored": True,
        "cfg_value_default": 2.0,
        "cfg_value_min": 1.0,
        "cfg_value_max": 10.0,
        "cfg_value_step": 0.5,
        "cfg_value_hint": "Classifier-free guidance strength",
        "timesteps_default": 10,
        "timesteps_min": 1,
        "timesteps_max": 50,
        "timesteps_hint": "Inference timesteps (fewer = faster, more = higher quality)",
        "model_managed": True,
        "model_idle_unload_s": 60,
        "long_wait": True,
        "note": "VoxCPM2 in-process (OpenBMB). GPU strongly recommended; cfg/timesteps tune quality.",
    },

    # -- managed server engines (subprocess HTTP API, single-active) ----------
    "chattts": {
        "fields": ["text", "language", "speed", "voice"],
        "text_default": "Hello, this is a ChatTTS dialogue test [oral_2][laugh_0].",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "speed_default": 1.0,
        "speed_min": 0.5,
        "speed_max": 2.0,
        "speed_step": 0.1,
        "voice_placeholder": "alloy",
        "voice_hint": "OpenAI-compatible voice name (env CHATTTS_VOICE)",
        "server_managed": True,
        "server_env": "CHATTTS_URL",
        "long_wait": True,
        "note": "ChatTTS local API (dialogue; laughs/sighs). Server auto-started on first use.",
    },
    "cosyvoice": {
        "fields": ["text", "language", "speed", "speaker_id", "instruct"],
        "text_default": "你好，这是一个CosyVoice语音合成测试。",
        "language_options": _COMMON_LANGS,
        "language_default": "zh",
        "speed_default": 1.0,
        "speed_min": 0.5,
        "speed_max": 2.0,
        "speed_step": 0.1,
        "speaker_id_placeholder": "中文女",
        "speaker_id_hint": "Speaker id for sft/instruct mode (env COSYVOICE_SPK_ID)",
        "instruct_placeholder": "用温柔的语气说话",
        "instruct_hint": "Instruction for instruct/instruct2 mode (env COSYVOICE_INSTRUCT)",
        "server_managed": True,
        "server_env": "COSYVOICE_URL",
        "needs_reference": True,
        "reference_hint": "COSYVOICE_REF_AUDIO needed for zero_shot mode",
        "long_wait": True,
        "note": "CosyVoice local API (multilingual clone + emotion). Needs SPK_ID or REF_AUDIO.",
    },
    "gptsovits": {
        "fields": ["text", "language", "speed", "prompt_text", "prompt_lang"],
        "text_default": "这是一个GPT-SoVITS语音克隆测试。",
        "language_options": [
            {"value": "zh", "label": "中文"},
            {"value": "en", "label": "English"},
            {"value": "ja", "label": "日本語"},
            {"value": "ko", "label": "한국어"},
            {"value": "yue", "label": "粤语"},
        ],
        "language_default": "zh",
        "speed_default": 1.0,
        "speed_min": 0.5,
        "speed_max": 2.0,
        "speed_step": 0.1,
        "prompt_text_placeholder": "参考音频的文本内容",
        "prompt_text_hint": "Transcript of the reference clip (env GPTSOVITS_PROMPT_TEXT)",
        "prompt_lang_options": [
            {"value": "zh", "label": "中文"},
            {"value": "en", "label": "English"},
            {"value": "ja", "label": "日本語"},
            {"value": "ko", "label": "한국어"},
        ],
        "prompt_lang_default": "zh",
        "prompt_lang_hint": "Language of the reference audio (env GPTSOVITS_PROMPT_LANG)",
        "server_managed": True,
        "server_env": "GPTSOVITS_URL",
        "needs_reference": True,
        "reference_hint": "GPTSOVITS_REF_AUDIO must be set to an existing wav file",
        "long_wait": True,
        "note": "GPT-SoVITS local API (voice clone). GPTSOVITS_REF_AUDIO required.",
    },
    "f5tts": {
        "fields": ["text", "language", "speed"],
        "text_default": "This is an F5-TTS flow matching synthesis test.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "speed_default": 1.0,
        "speed_min": 0.5,
        "speed_max": 2.0,
        "speed_step": 0.1,
        "speed_ignored": True,
        "server_managed": True,
        "server_env": "F5TTS_URL",
        "needs_reference": True,
        "reference_hint": "F5TTS_REF_AUDIO + F5TTS_REF_TEXT both required",
        "long_wait": True,
        "note": "F5-TTS local API (flow-matching clone). REF_AUDIO + REF_TEXT required.",
    },
    "fishspeech": {
        "fields": ["text", "language", "speed"],
        "text_default": "This is a Fish Speech synthesis test.",
        "language_options": _COMMON_LANGS,
        "language_default": "en",
        "speed_default": 1.0,
        "speed_min": 0.5,
        "speed_max": 2.0,
        "speed_step": 0.1,
        "lang_ignored": True,
        "speed_ignored": True,
        "server_managed": True,
        "server_env": "FISHSPEECH_URL",
        "dual_mode": True,
        "note": "Fish Speech / Fish Audio. Local server OR FISH_API_KEY cloud SDK.",
    },
}


def get_tts_engine_params(engine: str) -> Dict[str, Any]:
    """Return the test-parameter schema for a TTS engine, or an empty dict if unknown."""
    return TTS_ENGINE_TEST_PARAMS.get((engine or "").strip().lower(), {})


__all__ = ["TTS_ENGINE_TEST_PARAMS", "get_tts_engine_params"]
