<!-- 
  This file was automatically generated by switch-app-entry.js
  Source: pages/index.pymatrix.vue
  Generated at: 2025-10-30T20:20:04.091Z
  App Entry: pymatrix
  
  DO NOT EDIT THIS FILE DIRECTLY
  Edit pages/index.pymatrix.vue instead
-->
<template>
  <NuxtLayout name="default">
    <PyMatrixMain />
  </NuxtLayout>
</template>

<script setup lang="ts">
import PyMatrixMain from '~/apps/app_pymatrix/pages_app_pymatrix/index-pymatrix.vue';

useHead({
  title: 'pyMatrix - Device Control',
  meta: [
    { name: 'description', content: 'Android device mirroring and group control system' }
  ]
});
</script>
