"""Embed the manifest default candidate: default/ forms, inline SVG module, flavor icon and favicon set.

Usage: python embed_default.py [--id <candidate id>]   (defaults to manifest.default)
"""
from __future__ import annotations

import argparse
import shutil

from brand_common import *
from forms import *

UI_ROOT = BRAND_DIR.parents[3]
DEFAULT_DIR = BRAND_DIR / "default"
TS_FILE = BRAND_DIR / "cmBrandDefault.generated.ts"
FLAVOR_DIR = UI_ROOT / "flavors" / "codemart"
ICON_SIZE = 512
ICON_MARK_FRACTION = 0.74
ICON_BACKGROUND = "#ffffff"
FAVICON_SIZES = {"favicon-32.png": 32, "apple-touch-icon-180.png": 180, "icon-192.png": 192, "icon-512.png": 512}
FAVICON_DARK_CSS = "@media (prefers-color-scheme: dark){path{fill:#fff}}"


def viewbox(form: str) -> tuple[int, int, int, int]:
    x0, y0, x1, y1 = FORM_BBOX[form]
    return x0 - PAD, y0 - PAD, x1 - x0 + 2 * PAD, y1 - y0 + 2 * PAD


def icon_svg(layers: dict) -> str:
    x0, y0, x1, y1 = MARK_BBOX
    scale = ICON_SIZE * ICON_MARK_FRACTION / (x1 - x0)
    tx = (ICON_SIZE - (x1 - x0) * scale) / 2 - x0 * scale
    ty = (ICON_SIZE - (y1 - y0) * scale) / 2 - y0 * scale
    body = layer_group(layers, "mark", "ink")
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {ICON_SIZE} {ICON_SIZE}"><title>CodeMart</title>'
            f'<rect width="{ICON_SIZE}" height="{ICON_SIZE}" fill="{ICON_BACKGROUND}"/>'
            f'<g transform="translate({tx:.2f} {ty:.2f}) scale({scale:.4f})">{body}</g></svg>')


def favicon_svg(layers: dict) -> str:
    x0, y0, w, h = viewbox("mark")
    body = layer_group(layers, "mark", "ink")
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x0} {y0} {w} {h}"><title>CodeMart</title>'
            f'<style>{FAVICON_DARK_CSS}</style>{body}</svg>')


def ts_module(cid: str, layers: dict) -> str:
    forms = {}
    for form in FORM_BBOX:
        x0, y0, w, h = viewbox(form)
        inner = "".join(f'<g>{layer_group(layers, g, "current")}</g>' for g in FORM_GROUPS[form])
        forms[form] = {"viewBox": f"{x0} {y0} {w} {h}", "width": w, "height": h, "body": inner}
    return (f"// Generated by assets/brand/tools/embed_default.py from candidate {cid}; do not edit.\n"
            f"export const CM_BRAND_DEFAULT_ID = {json.dumps(cid)};\n"
            f"export const CM_BRAND_FORMS = {json.dumps(forms, indent=2)} as const;\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--id", default="")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    cid = args.id or manifest["default"]
    src = CANDIDATES_DIR / cid
    layers = json.loads((src / "layers.json").read_text())
    DEFAULT_DIR.mkdir(parents=True, exist_ok=True)
    for old in DEFAULT_DIR.iterdir():
        old.unlink()
    for f in src.iterdir():
        if f.suffix in (".svg", ".png"):
            shutil.copy2(f, DEFAULT_DIR / f.name)
    (DEFAULT_DIR / "default-id.txt").write_text(cid + "\n")
    TS_FILE.write_text(ts_module(cid, layers), encoding="utf-8")
    FLAVOR_DIR.mkdir(parents=True, exist_ok=True)
    icon = icon_svg(layers)
    (FLAVOR_DIR / "icon.svg").write_text(icon, encoding="utf-8")
    (FLAVOR_DIR / "favicon.svg").write_text(favicon_svg(layers), encoding="utf-8")
    for name, size in FAVICON_SIZES.items():
        render_svg(icon, size).save(FLAVOR_DIR / name)
    manifest["default"] = cid
    MANIFEST.write_text(json.dumps(manifest, indent=1, ensure_ascii=False))
    print("embedded", cid)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
