<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>DotApps.d3d4tester.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>SourceDir</_Parameter1>
      <_Parameter2>$(MSBuildThisFileDirectory)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\dotcore\DotCore.Foundations\DotCore.Foundations.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.Common\DotCore.Common.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.Utils\DotCore.Utils.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.UITheme\DotCore.UITheme.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.UIInspect\DotCore.UIInspect.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.ScreenCapture\DotCore.ScreenCapture.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.TemplateMatcher\DotCore.TemplateMatcher.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.Utils.ImageColor\DotCore.Utils.ImageColor.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.Utils.ImagePreprocess\DotCore.Utils.ImagePreprocess.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.MinimapPath\DotCore.MinimapPath.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.YoloDetect\DotCore.YoloDetect.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.VocAnnotator\DotCore.VocAnnotator.csproj" />
    <ProjectReference Include="..\..\..\dotcore\DotCore.YoloTrain\DotCore.YoloTrain.csproj" />
  </ItemGroup>
</Project>
