// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

import 'localization_keys_app_qy.dart';

/// English localization for QY App
class EnAppQy {
  static const Map<String, String> values = {
    // App Identity
    QyAppLocalizationKeys.qyAppName: 'QY App',
    QyAppLocalizationKeys.qyAppDescription: 'A comprehensive QY learning platform',
    QyAppLocalizationKeys.qyAppSlogan: 'Learn, Build, Grow',
    QyAppLocalizationKeys.qyAppVersion: 'Version 1.0.0',
    QyAppLocalizationKeys.qyAppSettings: 'App Settings',
    QyAppLocalizationKeys.qySloganWords: 'Empower Your Learning Journey',
    QyAppLocalizationKeys.qySloganEyes: 'Keep your eyes on knowledge',
    QyAppLocalizationKeys.qyLetsStart: 'Let\'s Start',
    QyAppLocalizationKeys.qyDoNotHaveAccount: 'Don\'t have an account?',
    QyAppLocalizationKeys.qySignupForFree: 'Sign up for free',
    QyAppLocalizationKeys.qyWelcome: 'Welcome Back',
    QyAppLocalizationKeys.qyGreeting: 'Hello, learner!',
    QyAppLocalizationKeys.qyWelcomeBack: 'Welcome back',
    QyAppLocalizationKeys.qyGuestMode: 'Guest mode',

    // Common Actions
    QyAppLocalizationKeys.qyHome: 'Home',
    QyAppLocalizationKeys.qyMenu: 'Menu',
    QyAppLocalizationKeys.qySocial: 'Social',
    QyAppLocalizationKeys.qySupport: 'Support',
    QyAppLocalizationKeys.qyNext: 'Next',
    QyAppLocalizationKeys.qyPrevious: 'Previous',
    QyAppLocalizationKeys.qySkip: 'Skip',
    QyAppLocalizationKeys.qyCancel: 'Cancel',
    QyAppLocalizationKeys.qyConfirm: 'Confirm',
    QyAppLocalizationKeys.qySave: 'Save',
    QyAppLocalizationKeys.qyDelete: 'Delete',
    QyAppLocalizationKeys.qyEdit: 'Edit',
    QyAppLocalizationKeys.qyBack: 'Back',
    QyAppLocalizationKeys.qyClose: 'Close',
    QyAppLocalizationKeys.qyOk: 'OK',
    QyAppLocalizationKeys.qyYes: 'Yes',
    QyAppLocalizationKeys.qyNo: 'No',
    QyAppLocalizationKeys.qyContinue: 'Continue',
    QyAppLocalizationKeys.qySubmit: 'Submit',
    QyAppLocalizationKeys.qyRetry: 'Retry',
    QyAppLocalizationKeys.qyRefresh: 'Refresh',
    QyAppLocalizationKeys.qySearch: 'Search',
    QyAppLocalizationKeys.qySearchPlaceholder: 'Search...',
    QyAppLocalizationKeys.qyEnterSearchText: 'Enter search text',
    QyAppLocalizationKeys.qyFilter: 'Filter',
    QyAppLocalizationKeys.qySort: 'Sort',
    QyAppLocalizationKeys.qyClear: 'Clear',
    QyAppLocalizationKeys.qyReset: 'Reset',
    QyAppLocalizationKeys.qyTopUp: 'Top up',

    // Status Messages
    QyAppLocalizationKeys.qySuccess: 'Success',
    QyAppLocalizationKeys.qyError: 'Error',
    QyAppLocalizationKeys.qyWarning: 'Warning',
    QyAppLocalizationKeys.qyInfo: 'Information',
    QyAppLocalizationKeys.qyLoading: 'Loading...',
    QyAppLocalizationKeys.qyCompleted: 'Completed',
    QyAppLocalizationKeys.qyPending: 'Pending',
    QyAppLocalizationKeys.qyFailed: 'Failed',

    // Authentication
    QyAppLocalizationKeys.qySignIn: 'Sign In',
    QyAppLocalizationKeys.qySignUp: 'Sign Up',
    QyAppLocalizationKeys.qySignOut: 'Sign Out',
    QyAppLocalizationKeys.qyLogout: 'Logout',
    QyAppLocalizationKeys.qyLogoutConfirm: 'Are you sure you want to log out?',
    QyAppLocalizationKeys.qyLogoutSuccess: 'You have been logged out successfully',
    QyAppLocalizationKeys.qyLogoutFailed: 'Logout failed, please try again',
    QyAppLocalizationKeys.qyYesLogout: 'Yes, logout',
    QyAppLocalizationKeys.qyLogin: 'Login',
    QyAppLocalizationKeys.qyRegister: 'Register',
    QyAppLocalizationKeys.qyForgotPassword: 'Forgot Password',
    QyAppLocalizationKeys.qyResetPassword: 'Reset Password',
    QyAppLocalizationKeys.qyChangePassword: 'Change Password',
    QyAppLocalizationKeys.qyEmail: 'Email',
    QyAppLocalizationKeys.qyPassword: 'Password',
    QyAppLocalizationKeys.qyConfirmPassword: 'Confirm Password',
    QyAppLocalizationKeys.qyUsername: 'Username',
    QyAppLocalizationKeys.qyRememberMe: 'Remember Me',
    QyAppLocalizationKeys.qyCreateAccount: 'Create Account',
    QyAppLocalizationKeys.qyHaveAccount: 'Already have an account?',
    QyAppLocalizationKeys.qyNoAccount: 'Don\'t have an account?',

    // Profile & Settings
    QyAppLocalizationKeys.qyProfile: 'Profile',
    QyAppLocalizationKeys.qyMyProfile: 'My Profile',
    QyAppLocalizationKeys.qyEditProfile: 'Edit Profile',
    QyAppLocalizationKeys.qyPersonalInfo: 'Personal Information',
    QyAppLocalizationKeys.qyFirstName: 'First Name',
    QyAppLocalizationKeys.qyLastName: 'Last Name',
    QyAppLocalizationKeys.qyFullName: 'Full Name',
    QyAppLocalizationKeys.qyPhoneNumber: 'Phone Number',
    QyAppLocalizationKeys.qyAddress: 'Address',
    QyAppLocalizationKeys.qyBirthDate: 'Birth Date',
    QyAppLocalizationKeys.qyGender: 'Gender',
    QyAppLocalizationKeys.qyAvatar: 'Avatar',
    QyAppLocalizationKeys.qyBio: 'Bio',
    QyAppLocalizationKeys.qySettings: 'Settings',
    QyAppLocalizationKeys.qyGeneralSettings: 'General Settings',
    QyAppLocalizationKeys.qyAccountSettings: 'Account Settings',
    QyAppLocalizationKeys.qyPrivacySettings: 'Privacy Settings',
    QyAppLocalizationKeys.qyNotificationSettings: 'Notification Settings',
    QyAppLocalizationKeys.qyLanguageSettings: 'Language Settings',
    QyAppLocalizationKeys.qyThemeSettings: 'Theme Settings',
    QyAppLocalizationKeys.qyBiometricAuth: 'Biometric Authentication',
    QyAppLocalizationKeys.qyDarkMode: 'Dark Mode',
    QyAppLocalizationKeys.qyLightMode: 'Light Mode',
    QyAppLocalizationKeys.qySystemMode: 'System Mode',
    QyAppLocalizationKeys.qyLanguage: 'Language',
    QyAppLocalizationKeys.qyLanguageEnglish: 'English',
    QyAppLocalizationKeys.qyLanguageChinese: 'Chinese',
    QyAppLocalizationKeys.qyNotifications: 'Notifications',
    QyAppLocalizationKeys.qyPrivacy: 'Privacy',
    QyAppLocalizationKeys.qyPrivacySecurity: 'Privacy & Security',
    QyAppLocalizationKeys.qySecurity: 'Security',
    QyAppLocalizationKeys.qyHelp: 'Help',
    QyAppLocalizationKeys.qyHelpSupport: 'Help & Support',
    QyAppLocalizationKeys.qySupport: 'Support',
    QyAppLocalizationKeys.qyAbout: 'About',
    QyAppLocalizationKeys.qyAboutDescription: 'Learn more about the QY App',
    QyAppLocalizationKeys.qyTerms: 'Terms of Service',
    QyAppLocalizationKeys.qyPrivacyPolicy: 'Privacy Policy',

    // Dashboard & Stats
    QyAppLocalizationKeys.qyDashboard: 'Dashboard',
    QyAppLocalizationKeys.qyInbox: 'Inbox',
    QyAppLocalizationKeys.qyMessages: 'Messages',
    QyAppLocalizationKeys.qyChat: 'Chat',
    QyAppLocalizationKeys.qyContacts: 'Contacts',
    QyAppLocalizationKeys.qyFriends: 'Friends',
    QyAppLocalizationKeys.qyGroups: 'Groups',
    QyAppLocalizationKeys.qyFeed: 'Feed',
    QyAppLocalizationKeys.qyNews: 'News',
    QyAppLocalizationKeys.qyEvents: 'Events',
    QyAppLocalizationKeys.qyCalendar: 'Calendar',
    QyAppLocalizationKeys.qyTasks: 'Tasks',
    QyAppLocalizationKeys.qyProjects: 'Projects',
    QyAppLocalizationKeys.qyMyPrayers: 'My Prayers',
    QyAppLocalizationKeys.qyMyDonations: 'My Donations',
    QyAppLocalizationKeys.qyMyFundraising: 'My Fundraising',
    QyAppLocalizationKeys.qyInviteFriends: 'Invite Friends',
    QyAppLocalizationKeys.qyShareApp: 'Share App',
    QyAppLocalizationKeys.qyHomeTopMenuPrayer: 'Prayer',
    QyAppLocalizationKeys.qyFeature: 'Feature',
    QyAppLocalizationKeys.qyFeaturePreview: 'Preview',
    QyAppLocalizationKeys.qyFeatureComingSoon: 'Coming Soon',
    QyAppLocalizationKeys.qyDisaster: 'Disaster Relief',
    QyAppLocalizationKeys.qyEducation: 'Education',
    QyAppLocalizationKeys.qyEnvironment: 'Environment',
    QyAppLocalizationKeys.qyHumanity: 'Humanitarian',
    QyAppLocalizationKeys.qyMedical: 'Medical Aid',
    QyAppLocalizationKeys.qyOrphanage: 'Orphanage',

    // Learning statistics
    QyAppLocalizationKeys.qyCommunity: 'Community',
    QyAppLocalizationKeys.qyGlobalSearch: 'Global Search',
    QyAppLocalizationKeys.qyAiSearch: 'AI Search',
    QyAppLocalizationKeys.qyPlaceholderSearchContent: 'Search content...',
    QyAppLocalizationKeys.qyLearningProgress: 'Learning Progress',
    QyAppLocalizationKeys.qyStudyDuration: 'Study Duration',
    QyAppLocalizationKeys.qyAccuracyRate: 'Accuracy Rate',
    QyAppLocalizationKeys.qyReviewCount: 'Review Count',
    QyAppLocalizationKeys.qyWordLearning: 'Word Learning',
    QyAppLocalizationKeys.qyInterest: 'Interest',
    QyAppLocalizationKeys.qyIAm: 'I am',
  };

  /// Get locales for runCommonApp
  static List<Map<String, String>> get locales => [values];
}
