// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

import 'localization_keys_app_qy.dart';

/// English localization for QY App
class EnAppQy {
  static const Map<String, String> values = {
    // App Identity
    QyAppLocalizationKeys.qyAppName: 'QY App',
    QyAppLocalizationKeys.qyAppDescription: 'A comprehensive QY learning platform',
    QyAppLocalizationKeys.qyAppSlogan: 'Learn, Build, Grow',
    QyAppLocalizationKeys.qyAppVersion: 'Version 1.0.0',
    QyAppLocalizationKeys.qyAppSettings: 'App Settings',
    QyAppLocalizationKeys.qySloganWords: 'Empower Your Learning Journey',
    QyAppLocalizationKeys.qySloganEyes: 'Keep your eyes on knowledge',
    QyAppLocalizationKeys.qyLetsStart: 'Let\'s Start',
    QyAppLocalizationKeys.qyDoNotHaveAccount: 'Don\'t have an account?',
    QyAppLocalizationKeys.qySignupForFree: 'Sign up for free',
    QyAppLocalizationKeys.qyWelcome: 'Welcome Back',
    QyAppLocalizationKeys.qyGreeting: 'Hello, learner!',
    QyAppLocalizationKeys.qyWelcomeBack: 'Welcome back',
    QyAppLocalizationKeys.qyGuestMode: 'Guest mode',

    // Common Actions
    QyAppLocalizationKeys.qyHome: 'Home',
    QyAppLocalizationKeys.qyMenu: 'Menu',
    QyAppLocalizationKeys.qySocial: 'Social',
    QyAppLocalizationKeys.qySupport: 'Support',
    QyAppLocalizationKeys.qyNext: 'Next',
    QyAppLocalizationKeys.qyPrevious: 'Previous',
    QyAppLocalizationKeys.qySkip: 'Skip',
    QyAppLocalizationKeys.qyCancel: 'Cancel',
    QyAppLocalizationKeys.qyConfirm: 'Confirm',
    QyAppLocalizationKeys.qySave: 'Save',
    QyAppLocalizationKeys.qyDelete: 'Delete',
    QyAppLocalizationKeys.qyEdit: 'Edit',
    QyAppLocalizationKeys.qyBack: 'Back',
    QyAppLocalizationKeys.qyClose: 'Close',
    QyAppLocalizationKeys.qyOk: 'OK',
    QyAppLocalizationKeys.qyYes: 'Yes',
    QyAppLocalizationKeys.qyNo: 'No',
    QyAppLocalizationKeys.qyContinue: 'Continue',
    QyAppLocalizationKeys.qySubmit: 'Submit',
    QyAppLocalizationKeys.qyRetry: 'Retry',
    QyAppLocalizationKeys.qyRefresh: 'Refresh',
    QyAppLocalizationKeys.qySearch: 'Search',
    QyAppLocalizationKeys.qySearchPlaceholder: 'Search...',
    QyAppLocalizationKeys.qyEnterSearchText: 'Enter search text',
    QyAppLocalizationKeys.qyFilter: 'Filter',
    QyAppLocalizationKeys.qySort: 'Sort',
    QyAppLocalizationKeys.qyClear: 'Clear',
    QyAppLocalizationKeys.qyReset: 'Reset',
    QyAppLocalizationKeys.qyTopUp: 'Top up',

    // Status Messages
    QyAppLocalizationKeys.qySuccess: 'Success',
    QyAppLocalizationKeys.qyError: 'Error',
    QyAppLocalizationKeys.qyWarning: 'Warning',
    QyAppLocalizationKeys.qyInfo: 'Information',
    QyAppLocalizationKeys.qyLoading: 'Loading...',
    QyAppLocalizationKeys.qyCompleted: 'Completed',
    QyAppLocalizationKeys.qyPending: 'Pending',
    QyAppLocalizationKeys.qyFailed: 'Failed',

    // Authentication
    QyAppLocalizationKeys.qySignIn: 'Sign In',
    QyAppLocalizationKeys.qySignUp: 'Sign Up',
    QyAppLocalizationKeys.qySignOut: 'Sign Out',
    QyAppLocalizationKeys.qyLogout: 'Logout',
    QyAppLocalizationKeys.qyLogoutConfirm: 'Are you sure you want to log out?',
    QyAppLocalizationKeys.qyLogoutSuccess: 'You have been logged out successfully',
    QyAppLocalizationKeys.qyLogoutFailed: 'Logout failed, please try again',
    QyAppLocalizationKeys.qyYesLogout: 'Yes, logout',
    QyAppLocalizationKeys.qyLogin: 'Login',
    QyAppLocalizationKeys.qyRegister: 'Register',
    QyAppLocalizationKeys.qyForgotPassword: 'Forgot Password',
    QyAppLocalizationKeys.qyResetPassword: 'Reset Password',
    QyAppLocalizationKeys.qyChangePassword: 'Change Password',
    QyAppLocalizationKeys.qyEmail: 'Email',
    QyAppLocalizationKeys.qyPassword: 'Password',
    QyAppLocalizationKeys.qyConfirmPassword: 'Confirm Password',
    QyAppLocalizationKeys.qyUsername: 'Username',
    QyAppLocalizationKeys.qyRememberMe: 'Remember Me',
    QyAppLocalizationKeys.qyCreateAccount: 'Create Account',
    QyAppLocalizationKeys.qyHaveAccount: 'Already have an account?',
    QyAppLocalizationKeys.qyNoAccount: 'Don\'t have an account?',

    // Profile & Settings
    QyAppLocalizationKeys.qyProfile: 'Profile',
    QyAppLocalizationKeys.qyMyProfile: 'My Profile',
    QyAppLocalizationKeys.qyEditProfile: 'Edit Profile',
    QyAppLocalizationKeys.qyPersonalInfo: 'Personal Information',
    QyAppLocalizationKeys.qyFirstName: 'First Name',
    QyAppLocalizationKeys.qyLastName: 'Last Name',
    QyAppLocalizationKeys.qyFullName: 'Full Name',
    QyAppLocalizationKeys.qyPhoneNumber: 'Phone Number',
    QyAppLocalizationKeys.qyAddress: 'Address',
    QyAppLocalizationKeys.qyBirthDate: 'Birth Date',
    QyAppLocalizationKeys.qyGender: 'Gender',
    QyAppLocalizationKeys.qyAvatar: 'Avatar',
    QyAppLocalizationKeys.qyBio: 'Bio',
    QyAppLocalizationKeys.qySettings: 'Settings',
    QyAppLocalizationKeys.qyGeneralSettings: 'General Settings',
    QyAppLocalizationKeys.qyAccountSettings: 'Account Settings',
    QyAppLocalizationKeys.qyPrivacySettings: 'Privacy Settings',
    QyAppLocalizationKeys.qyNotificationSettings: 'Notification Settings',
    QyAppLocalizationKeys.qyLanguageSettings: 'Language Settings',
    QyAppLocalizationKeys.qyThemeSettings: 'Theme Settings',
    QyAppLocalizationKeys.qyBiometricAuth: 'Biometric Authentication',
    QyAppLocalizationKeys.qyDarkMode: 'Dark Mode',
    QyAppLocalizationKeys.qyLightMode: 'Light Mode',
    QyAppLocalizationKeys.qySystemMode: 'System Mode',
    QyAppLocalizationKeys.qyLanguage: 'Language',
    QyAppLocalizationKeys.qyLanguageEnglish: 'English',
    QyAppLocalizationKeys.qyLanguageChinese: 'Chinese',
    QyAppLocalizationKeys.qyNotifications: 'Notifications',
    QyAppLocalizationKeys.qyPrivacy: 'Privacy',
    QyAppLocalizationKeys.qyPrivacySecurity: 'Privacy & Security',
    QyAppLocalizationKeys.qySecurity: 'Security',
    QyAppLocalizationKeys.qyHelp: 'Help',
    QyAppLocalizationKeys.qyHelpSupport: 'Help & Support',
    QyAppLocalizationKeys.qyAbout: 'About',
    QyAppLocalizationKeys.qyAboutDescription: 'Learn more about the QY App',
    QyAppLocalizationKeys.qyTerms: 'Terms of Service',
    QyAppLocalizationKeys.qyPrivacyPolicy: 'Privacy Policy',
    QyAppLocalizationKeys.qyDisplayLayoutSettings: 'Display layout settings',
    QyAppLocalizationKeys.qyCompatibilitySettings: 'Compatibility settings',

    // Dashboard & Stats
    QyAppLocalizationKeys.qyDashboard: 'Dashboard',
    QyAppLocalizationKeys.qyInbox: 'Inbox',
    QyAppLocalizationKeys.qyMessages: 'Messages',
    QyAppLocalizationKeys.qyChat: 'Chat',
    QyAppLocalizationKeys.qyContacts: 'Contacts',
    QyAppLocalizationKeys.qyFriends: 'Friends',
    QyAppLocalizationKeys.qyGroups: 'Groups',
    QyAppLocalizationKeys.qyFeed: 'Feed',
    QyAppLocalizationKeys.qyNews: 'News',
    QyAppLocalizationKeys.qyEvents: 'Events',
    QyAppLocalizationKeys.qyCalendar: 'Calendar',
    QyAppLocalizationKeys.qyTasks: 'Tasks',
    QyAppLocalizationKeys.qyProjects: 'Projects',
    QyAppLocalizationKeys.qyMyPrayers: 'My Prayers',
    QyAppLocalizationKeys.qyMyDonations: 'My Donations',
    QyAppLocalizationKeys.qyMyFundraising: 'My Fundraising',
    QyAppLocalizationKeys.qyInviteFriends: 'Invite Friends',
    QyAppLocalizationKeys.qyShareApp: 'Share App',
    QyAppLocalizationKeys.qyHomeTopMenuPrayer: 'Prayer',
    QyAppLocalizationKeys.qyFeature: 'Feature',
    QyAppLocalizationKeys.qyFeaturePreview: 'Preview',
    QyAppLocalizationKeys.qyFeatureComingSoon: 'Coming Soon',
    QyAppLocalizationKeys.qyDisaster: 'Disaster Relief',
    QyAppLocalizationKeys.qyEducation: 'Education',
    QyAppLocalizationKeys.qyEnvironment: 'Environment',
    QyAppLocalizationKeys.qyHumanity: 'Humanitarian',
    QyAppLocalizationKeys.qyMedical: 'Medical Aid',
    QyAppLocalizationKeys.qyOrphanage: 'Orphanage',
    QyAppLocalizationKeys.qyDailyStudyReminder: 'Daily study reminder',
    QyAppLocalizationKeys.qyPersonalizedRecommendations: 'Personalized recommendation settings',
    QyAppLocalizationKeys.qySyncSettings: 'Sync settings',
    QyAppLocalizationKeys.qyNotLoggedIn: 'Not logged in',
    QyAppLocalizationKeys.qyUser: 'User',
    QyAppLocalizationKeys.qyClearCacheTitle: 'Clear cache',
    QyAppLocalizationKeys.qyClearCacheMessage: 'Are you sure you want to clear the cache? This will remove {size} MB of data.',
    QyAppLocalizationKeys.qyCacheCleared: 'Cache cleared successfully.',
    QyAppLocalizationKeys.qyHelpCenterInProgress: 'Help center feature is under development...',

    // Learning statistics
    QyAppLocalizationKeys.qyCommunity: 'Community',
    QyAppLocalizationKeys.qyGlobalSearch: 'Global Search',
    QyAppLocalizationKeys.qyAiSearch: 'AI Search',
    QyAppLocalizationKeys.qyPlaceholderSearchContent: 'Search content...',
    QyAppLocalizationKeys.qyLearningProgress: 'Learning Progress',
    QyAppLocalizationKeys.qyStudyDuration: 'Study Duration',
    QyAppLocalizationKeys.qyAccuracyRate: 'Accuracy Rate',
    QyAppLocalizationKeys.qyReviewCount: 'Review Count',
    QyAppLocalizationKeys.qyWordLearning: 'Word Learning',
    QyAppLocalizationKeys.qyInterest: 'Interest',
    QyAppLocalizationKeys.qyIAm: 'I am',

    QyAppLocalizationKeys.qyCertificateCenter: 'Certificate Center',
    QyAppLocalizationKeys.qyCertificateCenterSubtitle: 'View your learning achievements',
    QyAppLocalizationKeys.qyCertificateEarned: 'Earned',
    QyAppLocalizationKeys.qyCertificateInProgress: 'In Progress',
    QyAppLocalizationKeys.qyCertificateTotalPoints: 'Total Points',
    QyAppLocalizationKeys.qyCertificateLocked: 'Locked',
    QyAppLocalizationKeys.qyCertificateUnlocked: 'Unlocked',
    QyAppLocalizationKeys.qyCertificateEarnedDate: 'Earned Date',
    QyAppLocalizationKeys.qyCertificateNumber: 'Certificate No.',
    QyAppLocalizationKeys.qyCertificateIssueDate: 'Issue Date',
    QyAppLocalizationKeys.qyCertificateKeepWorking: 'Keep working to unlock this certificate!',
    QyAppLocalizationKeys.qyCertificateShareToWechat: 'Share to WeChat',
    QyAppLocalizationKeys.qyCertificateShareToMoments: 'Share to Moments',
    QyAppLocalizationKeys.qyCertificateSaveImage: 'Save Image',
    QyAppLocalizationKeys.qyCertificateCopyLink: 'Copy Link',
    QyAppLocalizationKeys.qyCertificateDownloadInProgress: 'Certificate download feature is under development...',
    QyAppLocalizationKeys.qyCertificateShareInProgress: 'Certificate share feature is under development...',
    QyAppLocalizationKeys.qyCertificateDescription: 'This certificate is issued by the English Learning Platform\n\nThis certifies that the student has completed the relevant learning requirements,\nachieved the corresponding learning standards, and this certificate is issued as encouragement.',
    QyAppLocalizationKeys.qyCertificateLevelBeginner: 'Beginner',
    QyAppLocalizationKeys.qyCertificateLevelIntermediate: 'Intermediate',
    QyAppLocalizationKeys.qyCertificateLevelAdvanced: 'Advanced',
    QyAppLocalizationKeys.qyCertificateLevelExpert: 'Expert',
    QyAppLocalizationKeys.qyCertificateBadgeNewbie: 'Newbie',
    QyAppLocalizationKeys.qyCertificateBadgeDiligent: 'Diligent',
    QyAppLocalizationKeys.qyCertificateBadgePersistent: 'Persistent',
    QyAppLocalizationKeys.qyCertificateBadgePerfectAttendance: 'Perfect Attendance',
    QyAppLocalizationKeys.qyCertificateBadgeExpert: 'Expert',
    QyAppLocalizationKeys.qyCertificateBadgeExcellent: 'Excellent',

    QyAppLocalizationKeys.qyCertBasicEnglishTitle: 'Basic English Certificate',
    QyAppLocalizationKeys.qyCertBasicEnglishDesc: 'Complete basic English learning course',
    QyAppLocalizationKeys.qyCertWordMasterTitle: 'Word Master',
    QyAppLocalizationKeys.qyCertWordMasterDesc: 'Master 1000 words in total',
    QyAppLocalizationKeys.qyCertListeningMasterTitle: 'Listening Master',
    QyAppLocalizationKeys.qyCertListeningMasterDesc: 'Complete listening practice for 30 consecutive days',
    QyAppLocalizationKeys.qyCertPerfectAttendanceTitle: 'Perfect Attendance Award',
    QyAppLocalizationKeys.qyCertPerfectAttendanceDesc: 'Study continuously for 90 days without interruption',
    QyAppLocalizationKeys.qyCertVocabularyExpertTitle: 'Vocabulary Expert Certification',
    QyAppLocalizationKeys.qyCertVocabularyExpertDesc: 'Master 5000 advanced vocabulary words',
    QyAppLocalizationKeys.qyCertIeltsHighScoreTitle: 'IELTS High Score Certificate',
    QyAppLocalizationKeys.qyCertIeltsHighScoreDesc: 'IELTS score above 7.5',

    QyAppLocalizationKeys.qyAuthWelcomeMessage: 'Welcome',
    QyAppLocalizationKeys.qyAuthAppSlogan: 'Shanbay Words - Remember Words, Record Changes',
    QyAppLocalizationKeys.qyAuthPhoneLogin: 'Phone Login',
    QyAppLocalizationKeys.qyAuthWechatLogin: 'WeChat Login',
    QyAppLocalizationKeys.qyAuthQQLogin: 'QQ Login',
    QyAppLocalizationKeys.qyAuthGoogleLogin: 'Google Login',
    QyAppLocalizationKeys.qyAuthGithubLogin: 'Github Login',
    QyAppLocalizationKeys.qyAuthMoreOptions: 'More Options',
    QyAppLocalizationKeys.qyAuthCollapseOptions: 'Collapse',
    QyAppLocalizationKeys.qyAuthPhoneNumber: 'Phone Number',
    QyAppLocalizationKeys.qyAuthPhonePlaceholder: 'Enter phone number',
    QyAppLocalizationKeys.qyAuthVerificationCode: 'Verification Code',
    QyAppLocalizationKeys.qyAuthCodePlaceholder: 'Enter verification code',
    QyAppLocalizationKeys.qyAuthGetCode: 'Get Code',
    QyAppLocalizationKeys.qyAuthResendCode: 'Resend',
    QyAppLocalizationKeys.qyAuthCodeSent: 'Code sent',
    QyAppLocalizationKeys.qyAuthCodeSendFailed: 'Failed to send code',
    QyAppLocalizationKeys.qyAuthLoginButton: 'Login',
    QyAppLocalizationKeys.qyAuthRegisterButton: 'Register',
    QyAppLocalizationKeys.qyAuthLoginSuccess: 'Login successful',
    QyAppLocalizationKeys.qyAuthLoginFailed: 'Login failed',
    QyAppLocalizationKeys.qyAuthRegisterSuccess: 'Registration successful',
    QyAppLocalizationKeys.qyAuthRegisterFailed: 'Registration failed',
    QyAppLocalizationKeys.qyAuthSkipLogin: 'Skip Login',
    QyAppLocalizationKeys.qyAuthGuestMode: 'Guest Mode',
    QyAppLocalizationKeys.qyAuthAgreement: 'User Agreement',
    QyAppLocalizationKeys.qyAuthAgreementPrefix: 'By logging in, you agree to',
    QyAppLocalizationKeys.qyAuthTermsOfService: 'Terms of Service',
    QyAppLocalizationKeys.qyAuthAnd: 'and',
    QyAppLocalizationKeys.qyAuthPrivacyPolicy: 'Privacy Policy',
    QyAppLocalizationKeys.qyAuthMustAgree: 'Please agree to the user agreement first',
    QyAppLocalizationKeys.qyAuthPhoneInvalid: 'Please enter a valid phone number',
    QyAppLocalizationKeys.qyAuthCodeInvalid: 'Please enter verification code',
    QyAppLocalizationKeys.qyAuthCodeLength: 'Please enter a 6-digit code',
    QyAppLocalizationKeys.qyAuthSeconds: 'seconds',
    QyAppLocalizationKeys.qyAuthWelcomeTitle: 'Welcome',
    QyAppLocalizationKeys.qyAuthSelectCountry: 'Select Country/Region',
    QyAppLocalizationKeys.qyAuthCountryCode: 'Country Code',
    QyAppLocalizationKeys.qyAuthVerifyPhone: 'Verify Phone',
    QyAppLocalizationKeys.qyAuthVerifyPhoneHint: 'Enter code to verify your phone',
    QyAppLocalizationKeys.qyAuthForgotPassword: 'Forgot Password',
    QyAppLocalizationKeys.qyAuthResetPassword: 'Reset Password',
    QyAppLocalizationKeys.qyAuthNewPassword: 'New Password',
    QyAppLocalizationKeys.qyAuthConfirmNewPassword: 'Confirm New Password',
    QyAppLocalizationKeys.qyAuthPasswordMismatch: 'Passwords do not match',
    QyAppLocalizationKeys.qyAuthPasswordTooShort: 'Password must be at least 6 characters',
    QyAppLocalizationKeys.qyAuthCreatePin: 'Create PIN',
    QyAppLocalizationKeys.qyAuthEnterPin: 'Enter PIN',
    QyAppLocalizationKeys.qyAuthConfirmPin: 'Confirm PIN',
    QyAppLocalizationKeys.qyAuthPinMismatch: 'PIN does not match',
    QyAppLocalizationKeys.qyAuthCongratulations: 'Congratulations',
    QyAppLocalizationKeys.qyAuthAccountCreated: 'Account Created',
    QyAppLocalizationKeys.qyAuthAccountCreatedDesc: 'Your account has been created successfully',
    QyAppLocalizationKeys.qyAuthGetStarted: 'Get Started',
    QyAppLocalizationKeys.qyAuthLoginModeSwitch: 'Switch to Login',
    QyAppLocalizationKeys.qyAuthRegisterModeSwitch: 'Switch to Register',
    QyAppLocalizationKeys.qyAuthWechatLoginFailed: 'WeChat login failed',
    QyAppLocalizationKeys.qyAuthThirdPartyLogin: 'Third-Party Login',

    QyAppLocalizationKeys.qySettingsPlayerCompatibility: 'Player compatibility',
    QyAppLocalizationKeys.qySettingsFeedback: 'Feedback',
    QyAppLocalizationKeys.qySettingsFeedbackInProgress: 'Feedback feature is under development...',
    QyAppLocalizationKeys.qySettingsAboutInProgress: 'About page feature is under development...',
    QyAppLocalizationKeys.qySettingsTermsInProgress: 'User agreement feature is under development...',
    QyAppLocalizationKeys.qySettingsPrivacyInProgress: 'Privacy policy feature is under development...',

    QyAppLocalizationKeys.qySettingsDailyReminder: 'Daily reminder',
    QyAppLocalizationKeys.qySettingsEnableDailyReminder: 'Enable daily reminder',
    QyAppLocalizationKeys.qySettingsEnableDailyReminderSubtitle: 'Daily study reminder at fixed time',
    QyAppLocalizationKeys.qySettingsReminderTime: 'Reminder time',
    QyAppLocalizationKeys.qySettingsVibrationReminder: 'Vibration reminder',
    QyAppLocalizationKeys.qySettingsVibrationReminderSubtitle: 'Vibrate on study reminder',
    QyAppLocalizationKeys.qySettingsSoundReminder: 'Sound reminder',
    QyAppLocalizationKeys.qySettingsSoundReminderSubtitle: 'Play sound on study reminder',
    QyAppLocalizationKeys.qySettingsReminderDate: 'Reminder date',
    QyAppLocalizationKeys.qySettingsRemindEveryday: 'Remind every day',
    QyAppLocalizationKeys.qySettingsWeekdayMonday: 'Mon',
    QyAppLocalizationKeys.qySettingsWeekdayTuesday: 'Tue',
    QyAppLocalizationKeys.qySettingsWeekdayWednesday: 'Wed',
    QyAppLocalizationKeys.qySettingsWeekdayThursday: 'Thu',
    QyAppLocalizationKeys.qySettingsWeekdayFriday: 'Fri',
    QyAppLocalizationKeys.qySettingsWeekdaySaturday: 'Sat',
    QyAppLocalizationKeys.qySettingsWeekdaySunday: 'Sun',

    QyAppLocalizationKeys.qySettingsFontSettings: 'Font settings',
    QyAppLocalizationKeys.qySettingsFont: 'Font',
    QyAppLocalizationKeys.qySettingsAppearanceSettings: 'Appearance settings',
    QyAppLocalizationKeys.qySettingsInterfaceLayout: 'Interface layout',
    QyAppLocalizationKeys.qySettingsStandardMode: 'Standard mode',
    QyAppLocalizationKeys.qySettingsAccessibility: 'Accessibility',
    QyAppLocalizationKeys.qySettingsHighContrast: 'High contrast',
    QyAppLocalizationKeys.qySettingsHighContrastSubtitle: 'Improve contrast between text and background',
    QyAppLocalizationKeys.qySettingsLargeFontMode: 'Large font mode',
    QyAppLocalizationKeys.qySettingsLargeFontModeSubtitle: 'Suitable for users with poor vision',
    QyAppLocalizationKeys.qySettingsSelectFont: 'Select font',
    QyAppLocalizationKeys.qySettingsLayoutInProgress: 'Layout settings feature is under development...',

    QyAppLocalizationKeys.qySettingsModify: 'Modify',
    QyAppLocalizationKeys.qySettingsRebind: 'Rebind',
    QyAppLocalizationKeys.qySettingsBind: 'Bind',
    QyAppLocalizationKeys.qySettingsAccountBinding: 'Account binding',
    QyAppLocalizationKeys.qySettingsPhone: 'Phone',
    QyAppLocalizationKeys.qySettingsNotBound: 'Not bound',
    QyAppLocalizationKeys.qySettingsWechat: 'WeChat',
    QyAppLocalizationKeys.qySettingsWeibo: 'Weibo',
    QyAppLocalizationKeys.qySettingsQQ: 'QQ',
    QyAppLocalizationKeys.qySettingsAccountDeletion: 'Account deletion',
    QyAppLocalizationKeys.qySettingsAccountDeletionSubtitle: 'Delete all data, permanent deletion',
    QyAppLocalizationKeys.qySettingsDeleteAccount: 'Delete',
    QyAppLocalizationKeys.qySettingsChangeUsername: 'Change username',
    QyAppLocalizationKeys.qySettingsEnterNewUsername: 'Enter new username',
    QyAppLocalizationKeys.qySettingsUsernameUpdated: 'Username updated',
    QyAppLocalizationKeys.qySettingsChangePasswordTitle: 'Change password',
    QyAppLocalizationKeys.qySettingsEnterNewPassword: 'Enter new password',
    QyAppLocalizationKeys.qySettingsConfirmNewPassword: 'Confirm new password',
    QyAppLocalizationKeys.qySettingsPasswordUpdated: 'Password updated',
    QyAppLocalizationKeys.qySettingsPhoneBinding: 'Phone binding',
    QyAppLocalizationKeys.qySettingsPhoneBindingInProgress: 'Phone binding feature is under development...',
    QyAppLocalizationKeys.qySettingsWechatBinding: 'WeChat binding',
    QyAppLocalizationKeys.qySettingsWechatBindingInProgress: 'WeChat binding feature is under development...',
    QyAppLocalizationKeys.qySettingsWeiboBinding: 'Weibo binding',
    QyAppLocalizationKeys.qySettingsWeiboBindingInProgress: 'Weibo binding feature is under development...',
    QyAppLocalizationKeys.qySettingsQQBinding: 'QQ binding',
    QyAppLocalizationKeys.qySettingsQQBindingInProgress: 'QQ binding feature is under development...',
    QyAppLocalizationKeys.qySettingsDeletionWarning: 'Warning: This operation is irreversible!',
    QyAppLocalizationKeys.qySettingsAfterDeletion: 'After account deletion:',
    QyAppLocalizationKeys.qySettingsDeletionDataLoss: 'All learning data will be permanently deleted',
    QyAppLocalizationKeys.qySettingsDeletionCourseLoss: 'Purchased courses and services will be unavailable',
    QyAppLocalizationKeys.qySettingsDeletionAccountClear: 'Account information will be completely cleared',
    QyAppLocalizationKeys.qySettingsConfirmDeletion: 'Are you sure you want to delete your account?',
    QyAppLocalizationKeys.qySettingsFinalConfirmation: 'Final confirmation',
    QyAppLocalizationKeys.qySettingsFinalConfirmationMessage: 'Please confirm again: Do you really want to permanently delete your account?',
    QyAppLocalizationKeys.qySettingsLetMeThink: 'Let me think again',
    QyAppLocalizationKeys.qySettingsAccountDeletionInProgress: 'Account deletion feature is under development...',

    QyAppLocalizationKeys.qySettingsSmartRecommendation: 'Smart recommendation',
    QyAppLocalizationKeys.qySettingsAutoRecommend: 'Auto recommend',
    QyAppLocalizationKeys.qySettingsAutoRecommendSubtitle: 'Recommend words based on learning history',
    QyAppLocalizationKeys.qySettingsDifficulty: 'Difficulty',
    QyAppLocalizationKeys.qySettingsDifficultySettings: 'Difficulty settings',
    QyAppLocalizationKeys.qySettingsDifficultyBeginner: 'Beginner',
    QyAppLocalizationKeys.qySettingsDifficultyIntermediate: 'Intermediate',
    QyAppLocalizationKeys.qySettingsDifficultyAdvanced: 'Advanced',
    QyAppLocalizationKeys.qySettingsDifficultyExpert: 'Expert',
    QyAppLocalizationKeys.qySettingsInterestTags: 'Interest tags',
    QyAppLocalizationKeys.qySettingsInterestTagsSelected: '{count} interest tags selected',
    QyAppLocalizationKeys.qySettingsRecommendationFrequency: 'Recommendation frequency',
    QyAppLocalizationKeys.qySettingsRecommendationStrength: 'Recommendation strength',
    QyAppLocalizationKeys.qySettingsSelectDifficulty: 'Select difficulty',
    QyAppLocalizationKeys.qySettingsDifficultyBeginnerDesc: 'Suitable for beginners, basic vocabulary',
    QyAppLocalizationKeys.qySettingsDifficultyIntermediateDesc: 'Suitable for learners with some foundation',
    QyAppLocalizationKeys.qySettingsDifficultyAdvancedDesc: 'Suitable for advanced learners, professional vocabulary',
    QyAppLocalizationKeys.qySettingsDifficultyExpertDesc: 'Suitable for expert learners, academic vocabulary',
  };

  /// Get locales for runCommonApp
  static List<Map<String, String>> get locales => [values];
}
