// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

import 'localization_keys_app_qy.dart';

/// Chinese localization for QY App
class ZhAppQy {
  static const Map<String, String> values = {
    // App Identity
    QyAppLocalizationKeys.qyAppName: 'QY 应用',
    QyAppLocalizationKeys.qyAppDescription: '综合学习与成长的平台',
    QyAppLocalizationKeys.qyAppSlogan: '学习、构建、成长',
    QyAppLocalizationKeys.qyAppVersion: '版本 1.0.0',
    QyAppLocalizationKeys.qyAppSettings: '应用设置',
    QyAppLocalizationKeys.qySloganWords: '赋能你的学习旅程',
    QyAppLocalizationKeys.qySloganEyes: '让目光专注于知识',
    QyAppLocalizationKeys.qyLetsStart: '开始体验',
    QyAppLocalizationKeys.qyDoNotHaveAccount: '还没有账号？',
    QyAppLocalizationKeys.qySignupForFree: '立即免费注册',
    QyAppLocalizationKeys.qyWelcome: '欢迎回来',
    QyAppLocalizationKeys.qyGreeting: '你好，学习者！',
    QyAppLocalizationKeys.qyWelcomeBack: '欢迎回来',
    QyAppLocalizationKeys.qyGuestMode: '访客模式',

    // Common Actions
    QyAppLocalizationKeys.qyHome: '首页',
    QyAppLocalizationKeys.qyMenu: '菜单',
    QyAppLocalizationKeys.qySocial: '社交',
    QyAppLocalizationKeys.qySupport: '支持',
    QyAppLocalizationKeys.qyNext: '下一步',
    QyAppLocalizationKeys.qyPrevious: '上一步',
    QyAppLocalizationKeys.qySkip: '跳过',
    QyAppLocalizationKeys.qyCancel: '取消',
    QyAppLocalizationKeys.qyConfirm: '确认',
    QyAppLocalizationKeys.qySave: '保存',
    QyAppLocalizationKeys.qyDelete: '删除',
    QyAppLocalizationKeys.qyEdit: '编辑',
    QyAppLocalizationKeys.qyBack: '返回',
    QyAppLocalizationKeys.qyClose: '关闭',
    QyAppLocalizationKeys.qyOk: '确定',
    QyAppLocalizationKeys.qyYes: '是',
    QyAppLocalizationKeys.qyNo: '否',
    QyAppLocalizationKeys.qyContinue: '继续',
    QyAppLocalizationKeys.qySubmit: '提交',
    QyAppLocalizationKeys.qyRetry: '重试',
    QyAppLocalizationKeys.qyRefresh: '刷新',
    QyAppLocalizationKeys.qySearch: '搜索',
    QyAppLocalizationKeys.qySearchPlaceholder: '搜索…',
    QyAppLocalizationKeys.qyEnterSearchText: '请输入搜索内容',
    QyAppLocalizationKeys.qyFilter: '筛选',
    QyAppLocalizationKeys.qySort: '排序',
    QyAppLocalizationKeys.qyClear: '清除',
    QyAppLocalizationKeys.qyReset: '重置',
    QyAppLocalizationKeys.qyTopUp: '充值',

    // Status Messages
    QyAppLocalizationKeys.qySuccess: '成功',
    QyAppLocalizationKeys.qyError: '错误',
    QyAppLocalizationKeys.qyWarning: '警告',
    QyAppLocalizationKeys.qyInfo: '提示',
    QyAppLocalizationKeys.qyLoading: '加载中...',
    QyAppLocalizationKeys.qyCompleted: '已完成',
    QyAppLocalizationKeys.qyPending: '待处理',
    QyAppLocalizationKeys.qyFailed: '失败',

    // General exercise/learning
    QyAppLocalizationKeys.qyCorrect: '正确',
    QyAppLocalizationKeys.qyIncorrect: '错误',
    QyAppLocalizationKeys.qyCorrectAnswer: '正确答案',
    QyAppLocalizationKeys.qyYourAnswer: '你的答案',
    QyAppLocalizationKeys.qyProgress: '进度',
    QyAppLocalizationKeys.qyListenAndType: '听音打字',
    QyAppLocalizationKeys.qyTypeHere: '在此输入',
    QyAppLocalizationKeys.qyPlayAgain: '再次播放',

    // Authentication
    QyAppLocalizationKeys.qySignIn: '登录',
    QyAppLocalizationKeys.qySignUp: '注册',
    QyAppLocalizationKeys.qySignOut: '退出',
    QyAppLocalizationKeys.qyLogout: '退出登录',
    QyAppLocalizationKeys.qyLogoutConfirm: '确定要退出当前账号吗？',
    QyAppLocalizationKeys.qyLogoutSuccess: '已成功退出登录',
    QyAppLocalizationKeys.qyLogoutFailed: '退出失败，请重试',
    QyAppLocalizationKeys.qyYesLogout: '确认退出',
    QyAppLocalizationKeys.qyLogin: '登录',
    QyAppLocalizationKeys.qyRegister: '注册',
    QyAppLocalizationKeys.qyForgotPassword: '忘记密码',
    QyAppLocalizationKeys.qyResetPassword: '重置密码',
    QyAppLocalizationKeys.qyChangePassword: '修改密码',
    QyAppLocalizationKeys.qyEmail: '邮箱',
    QyAppLocalizationKeys.qyPassword: '密码',
    QyAppLocalizationKeys.qyConfirmPassword: '确认密码',
    QyAppLocalizationKeys.qyUsername: '用户名',
    QyAppLocalizationKeys.qyRememberMe: '记住我',
    QyAppLocalizationKeys.qyCreateAccount: '创建账号',
    QyAppLocalizationKeys.qyHaveAccount: '已有账号？',
    QyAppLocalizationKeys.qyNoAccount: '还没有账号？',

    // Profile & Settings
    QyAppLocalizationKeys.qyProfile: '个人中心',
    QyAppLocalizationKeys.qyMyProfile: '我的资料',
    QyAppLocalizationKeys.qyEditProfile: '编辑资料',
    QyAppLocalizationKeys.qyPersonalInfo: '个人信息',
    QyAppLocalizationKeys.qyFirstName: '名字',
    QyAppLocalizationKeys.qyLastName: '姓氏',
    QyAppLocalizationKeys.qyFullName: '姓名',
    QyAppLocalizationKeys.qyPhoneNumber: '电话号码',
    QyAppLocalizationKeys.qyAddress: '地址',
    QyAppLocalizationKeys.qyBirthDate: '出生日期',
    QyAppLocalizationKeys.qyGender: '性别',
    QyAppLocalizationKeys.qyAvatar: '头像',
    QyAppLocalizationKeys.qyBio: '个性签名',
    QyAppLocalizationKeys.qySettings: '设置',
    QyAppLocalizationKeys.qyGeneralSettings: '通用设置',
    QyAppLocalizationKeys.qyAccountSettings: '账号设置',
    QyAppLocalizationKeys.qyPrivacySettings: '隐私设置',
    QyAppLocalizationKeys.qyNotificationSettings: '通知设置',
    QyAppLocalizationKeys.qyLanguageSettings: '语言设置',
    QyAppLocalizationKeys.qyThemeSettings: '主题设置',
    QyAppLocalizationKeys.qyReminderSettings: '提醒设置',
    QyAppLocalizationKeys.qyReminderSettingsDesc: '自定义学习提醒与打卡计划',
    QyAppLocalizationKeys.qyRecommendSettings: '推荐设置',
    QyAppLocalizationKeys.qyRecommendSettingsDesc: '根据学习进度智能推荐内容',
    QyAppLocalizationKeys.qyOtherSettings: '其他设置',
    QyAppLocalizationKeys.qyDisplayMode: '显示模式',
    QyAppLocalizationKeys.qyAboutUs: '关于我们',
    QyAppLocalizationKeys.qyCheckForUpdate: '检测更新',
    QyAppLocalizationKeys.qyNetworkDiagnostics: '网络检测',
    QyAppLocalizationKeys.qyBiometricAuth: '生物识别登录',
    QyAppLocalizationKeys.qyDarkMode: '深色模式',
    QyAppLocalizationKeys.qyLightMode: '浅色模式',
    QyAppLocalizationKeys.qySystemMode: '跟随系统',
    QyAppLocalizationKeys.qyLanguage: '语言',
    QyAppLocalizationKeys.qyLanguageEnglish: '英文',
    QyAppLocalizationKeys.qyLanguageChinese: '中文',
    QyAppLocalizationKeys.qyNotifications: '通知',
    QyAppLocalizationKeys.qyPrivacy: '隐私',
    QyAppLocalizationKeys.qyPrivacySecurity: '隐私与安全',
    QyAppLocalizationKeys.qySecurity: '安全',
    QyAppLocalizationKeys.qyHelp: '帮助',
    QyAppLocalizationKeys.qyHelpSupport: '帮助与支持',
    QyAppLocalizationKeys.qyAbout: '关于',
    QyAppLocalizationKeys.qyAboutDescription: '了解 QY 应用的详细信息',
    QyAppLocalizationKeys.qyTerms: '服务条款',
    QyAppLocalizationKeys.qyPrivacyPolicy: '隐私政策',
    QyAppLocalizationKeys.qyDisplayLayoutSettings: '显示布局设置',
    QyAppLocalizationKeys.qyCompatibilitySettings: '兼容性设置',

    // Dashboard & Stats
    QyAppLocalizationKeys.qyDashboard: '仪表盘',
    QyAppLocalizationKeys.qyInbox: '收件箱',
    QyAppLocalizationKeys.qyMessages: '消息',
    QyAppLocalizationKeys.qyChat: '聊天',
    QyAppLocalizationKeys.qyContacts: '联系人',
    QyAppLocalizationKeys.qyFriends: '好友',
    QyAppLocalizationKeys.qyGroups: '群组',
    QyAppLocalizationKeys.qyFeed: '动态',
    QyAppLocalizationKeys.qyNews: '资讯',
    QyAppLocalizationKeys.qyEvents: '活动',
    QyAppLocalizationKeys.qyCalendar: '日历',
    QyAppLocalizationKeys.qyTasks: '任务',
    QyAppLocalizationKeys.qyProjects: '项目',
    QyAppLocalizationKeys.qyMyPrayers: '我的祈祷',
    QyAppLocalizationKeys.qyMyDonations: '我的捐赠',
    QyAppLocalizationKeys.qyMyFundraising: '我的募捐',
    QyAppLocalizationKeys.qyInviteFriends: '邀请好友',
    QyAppLocalizationKeys.qyShareApp: '分享应用',
    QyAppLocalizationKeys.qyHomeTopMenuPrayer: '祈祷',
    QyAppLocalizationKeys.qyFeature: '功能',
    QyAppLocalizationKeys.qyFeaturePreview: '功能预览',
    QyAppLocalizationKeys.qyFeatureComingSoon: '敬请期待',
    QyAppLocalizationKeys.qyDisaster: '灾害救援',
    QyAppLocalizationKeys.qyEducation: '教育发展',
    QyAppLocalizationKeys.qyEnvironment: '环境守护',
    QyAppLocalizationKeys.qyHumanity: '人道主义',
    QyAppLocalizationKeys.qyMedical: '医疗援助',
    QyAppLocalizationKeys.qyOrphanage: '孤儿关怀',
    QyAppLocalizationKeys.qyDailyStudyReminder: '每日学习提醒',
    QyAppLocalizationKeys.qyPersonalizedRecommendations: '个性化推荐设置',
    QyAppLocalizationKeys.qySyncSettings: '同步设置',
    QyAppLocalizationKeys.qyNotLoggedIn: '未登录',
    QyAppLocalizationKeys.qyUser: '用户',
    QyAppLocalizationKeys.qyClearCacheTitle: '清除缓存',
    QyAppLocalizationKeys.qyClearCacheMessage: '确定要清除缓存吗？这将删除 {size} MB 的数据。',
    QyAppLocalizationKeys.qyCacheCleared: '缓存已清除',
    QyAppLocalizationKeys.qyHelpCenterInProgress: '帮助中心功能开发中...',

    // Learning statistics
    QyAppLocalizationKeys.qyCommunity: '社区',
    QyAppLocalizationKeys.qyGlobalSearch: '全局搜索',
    QyAppLocalizationKeys.qyAiSearch: 'AI 搜索',
    QyAppLocalizationKeys.qyPlaceholderSearchContent: '搜索内容…',
    QyAppLocalizationKeys.qyLearningProgress: '学习进度',
    QyAppLocalizationKeys.qyStudyDuration: '学习时长',
    QyAppLocalizationKeys.qyAccuracyRate: '准确率',
    QyAppLocalizationKeys.qyReviewCount: '复习次数',
    QyAppLocalizationKeys.qyWordLearning: '词汇学习',
    QyAppLocalizationKeys.qyInterest: '兴趣',
    QyAppLocalizationKeys.qyIAm: '我是',

    QyAppLocalizationKeys.qyCertificateCenter: '证书中心',
    QyAppLocalizationKeys.qyCertificateCenterSubtitle: '查看你的学习成就',
    QyAppLocalizationKeys.qyCertificateEarned: '已获得',
    QyAppLocalizationKeys.qyCertificateInProgress: '进行中',
    QyAppLocalizationKeys.qyCertificateTotalPoints: '总积分',
    QyAppLocalizationKeys.qyCertificateLocked: '未解锁',
    QyAppLocalizationKeys.qyCertificateUnlocked: '已解锁',
    QyAppLocalizationKeys.qyCertificateEarnedDate: '获得时间',
    QyAppLocalizationKeys.qyCertificateNumber: '证书编号',
    QyAppLocalizationKeys.qyCertificateIssueDate: '颁发日期',
    QyAppLocalizationKeys.qyCertificateKeepWorking: '继续努力，早日解锁这个证书！',
    QyAppLocalizationKeys.qyCertificateShareToWechat: '分享到微信',
    QyAppLocalizationKeys.qyCertificateShareToMoments: '分享到朋友圈',
    QyAppLocalizationKeys.qyCertificateSaveImage: '保存图片',
    QyAppLocalizationKeys.qyCertificateCopyLink: '复制链接',
    QyAppLocalizationKeys.qyCertificateDownloadInProgress: '证书下载功能开发中...',
    QyAppLocalizationKeys.qyCertificateShareInProgress: '证书分享功能开发中...',
    QyAppLocalizationKeys.qyCertificateDescription:
        '此证书由扇贝单词英语学习平台颁发\n\n兹证明学员已完成相关学习要求，\n达到相应学习标准，特发此证以资鼓励。',
    QyAppLocalizationKeys.qyCertificateLevelBeginner: '初级',
    QyAppLocalizationKeys.qyCertificateLevelIntermediate: '中级',
    QyAppLocalizationKeys.qyCertificateLevelAdvanced: '高级',
    QyAppLocalizationKeys.qyCertificateLevelExpert: '专家',
    QyAppLocalizationKeys.qyCertificateBadgeNewbie: '新手',
    QyAppLocalizationKeys.qyCertificateBadgeDiligent: '勤奋',
    QyAppLocalizationKeys.qyCertificateBadgePersistent: '坚持',
    QyAppLocalizationKeys.qyCertificateBadgePerfectAttendance: '全勤',
    QyAppLocalizationKeys.qyCertificateBadgeExpert: '专家',
    QyAppLocalizationKeys.qyCertificateBadgeExcellent: '卓越',

    QyAppLocalizationKeys.qyCertBasicEnglishTitle: '英语学习初级证书',
    QyAppLocalizationKeys.qyCertBasicEnglishDesc: '完成基础英语学习课程',
    QyAppLocalizationKeys.qyCertWordMasterTitle: '单词掌握达人',
    QyAppLocalizationKeys.qyCertWordMasterDesc: '累计掌握1000个单词',
    QyAppLocalizationKeys.qyCertListeningMasterTitle: '听力挑战大师',
    QyAppLocalizationKeys.qyCertListeningMasterDesc: '连续30天完成听力练习',
    QyAppLocalizationKeys.qyCertPerfectAttendanceTitle: '学习全勤奖',
    QyAppLocalizationKeys.qyCertPerfectAttendanceDesc: '连续学习90天不间断',
    QyAppLocalizationKeys.qyCertVocabularyExpertTitle: '词汇专家认证',
    QyAppLocalizationKeys.qyCertVocabularyExpertDesc: '掌握5000个高阶词汇',
    QyAppLocalizationKeys.qyCertIeltsHighScoreTitle: '雅思高分证书',
    QyAppLocalizationKeys.qyCertIeltsHighScoreDesc: '雅思考试7.5分以上',

    QyAppLocalizationKeys.qyAuthWelcomeMessage: '欢迎使用',
    QyAppLocalizationKeys.qyAuthAppSlogan: '扇贝单词 记住单词，记录改变',
    QyAppLocalizationKeys.qyAuthPhoneLogin: '手机号登录',
    QyAppLocalizationKeys.qyAuthWechatLogin: '微信登录',
    QyAppLocalizationKeys.qyAuthQQLogin: 'QQ登录',
    QyAppLocalizationKeys.qyAuthGoogleLogin: 'Google登录',
    QyAppLocalizationKeys.qyAuthGithubLogin: 'Github登录',
    QyAppLocalizationKeys.qyAuthMoreOptions: '更多登录方式',
    QyAppLocalizationKeys.qyAuthCollapseOptions: '收起',
    QyAppLocalizationKeys.qyAuthPhoneNumber: '手机号',
    QyAppLocalizationKeys.qyAuthPhonePlaceholder: '请输入手机号',
    QyAppLocalizationKeys.qyAuthVerificationCode: '验证码',
    QyAppLocalizationKeys.qyAuthCodePlaceholder: '请输入验证码',
    QyAppLocalizationKeys.qyAuthGetCode: '获取验证码',
    QyAppLocalizationKeys.qyAuthResendCode: '重新发送',
    QyAppLocalizationKeys.qyAuthCodeSent: '验证码已发送',
    QyAppLocalizationKeys.qyAuthCodeSendFailed: '发送验证码失败',
    QyAppLocalizationKeys.qyAuthLoginButton: '登录',
    QyAppLocalizationKeys.qyAuthRegisterButton: '注册',
    QyAppLocalizationKeys.qyAuthLoginSuccess: '登录成功',
    QyAppLocalizationKeys.qyAuthLoginFailed: '登录失败',
    QyAppLocalizationKeys.qyAuthRegisterSuccess: '注册成功',
    QyAppLocalizationKeys.qyAuthRegisterFailed: '注册失败',
    QyAppLocalizationKeys.qyAuthSkipLogin: '跳过登录',
    QyAppLocalizationKeys.qyAuthGuestMode: '访客模式',
    QyAppLocalizationKeys.qyAuthAgreement: '用户协议',
    QyAppLocalizationKeys.qyAuthAgreementPrefix: '登录即表示同意',
    QyAppLocalizationKeys.qyAuthTermsOfService: '服务条款',
    QyAppLocalizationKeys.qyAuthAnd: '和',
    QyAppLocalizationKeys.qyAuthPrivacyPolicy: '隐私政策',
    QyAppLocalizationKeys.qyAuthMustAgree: '请先同意用户协议',
    QyAppLocalizationKeys.qyAuthPhoneInvalid: '请输入有效的手机号',
    QyAppLocalizationKeys.qyAuthCodeInvalid: '请输入验证码',
    QyAppLocalizationKeys.qyAuthCodeLength: '请输入6位数字验证码',
    QyAppLocalizationKeys.qyAuthSeconds: '秒',
    QyAppLocalizationKeys.qyAuthWelcomeTitle: '欢迎',
    QyAppLocalizationKeys.qyAuthSelectCountry: '选择国家/地区',
    QyAppLocalizationKeys.qyAuthCountryCode: '国家代码',
    QyAppLocalizationKeys.qyAuthVerifyPhone: '验证手机号',
    QyAppLocalizationKeys.qyAuthVerifyPhoneHint: '请输入验证码以验证您的手机号',
    QyAppLocalizationKeys.qyAuthForgotPassword: '忘记密码',
    QyAppLocalizationKeys.qyAuthResetPassword: '重置密码',
    QyAppLocalizationKeys.qyAuthNewPassword: '新密码',
    QyAppLocalizationKeys.qyAuthConfirmNewPassword: '确认新密码',
    QyAppLocalizationKeys.qyAuthPasswordMismatch: '两次输入的密码不一致',
    QyAppLocalizationKeys.qyAuthPasswordTooShort: '密码长度至少6位',
    QyAppLocalizationKeys.qyAuthCreatePin: '创建PIN码',
    QyAppLocalizationKeys.qyAuthEnterPin: '输入PIN码',
    QyAppLocalizationKeys.qyAuthConfirmPin: '确认PIN码',
    QyAppLocalizationKeys.qyAuthPinMismatch: 'PIN码不匹配',
    QyAppLocalizationKeys.qyAuthCongratulations: '恭喜',
    QyAppLocalizationKeys.qyAuthAccountCreated: '账号创建成功',
    QyAppLocalizationKeys.qyAuthAccountCreatedDesc: '您的账号已成功创建，现在可以开始使用了',
    QyAppLocalizationKeys.qyAuthGetStarted: '开始使用',
    QyAppLocalizationKeys.qyAuthLoginModeSwitch: '切换到登录',
    QyAppLocalizationKeys.qyAuthRegisterModeSwitch: '切换到注册',
    QyAppLocalizationKeys.qyAuthWechatLoginFailed: '微信登录失败',
    QyAppLocalizationKeys.qyAuthThirdPartyLogin: '第三方登录',

    QyAppLocalizationKeys.qySettingsPlayerCompatibility: '播放器兼容性',
    QyAppLocalizationKeys.qySettingsFeedback: '意见反馈',
    QyAppLocalizationKeys.qySettingsFeedbackInProgress: '意见反馈功能开发中...',
    QyAppLocalizationKeys.qySettingsAboutInProgress: '关于页面功能开发中...',
    QyAppLocalizationKeys.qySettingsTermsInProgress: '用户协议功能开发中...',
    QyAppLocalizationKeys.qySettingsPrivacyInProgress: '隐私政策功能开发中...',

    QyAppLocalizationKeys.qySettingsDailyReminder: '每日提醒',
    QyAppLocalizationKeys.qySettingsEnableDailyReminder: '开启每日提醒',
    QyAppLocalizationKeys.qySettingsEnableDailyReminderSubtitle: '每天固定时间提醒学习',
    QyAppLocalizationKeys.qySettingsReminderTime: '提醒时间',
    QyAppLocalizationKeys.qySettingsVibrationReminder: '震动提醒',
    QyAppLocalizationKeys.qySettingsVibrationReminderSubtitle: '学习提醒时震动',
    QyAppLocalizationKeys.qySettingsSoundReminder: '声音提醒',
    QyAppLocalizationKeys.qySettingsSoundReminderSubtitle: '学习提醒时播放声音',
    QyAppLocalizationKeys.qySettingsReminderDate: '提醒日期',
    QyAppLocalizationKeys.qySettingsRemindEveryday: '每天提醒',
    QyAppLocalizationKeys.qySettingsWeekdayMonday: '周一',
    QyAppLocalizationKeys.qySettingsWeekdayTuesday: '周二',
    QyAppLocalizationKeys.qySettingsWeekdayWednesday: '周三',
    QyAppLocalizationKeys.qySettingsWeekdayThursday: '周四',
    QyAppLocalizationKeys.qySettingsWeekdayFriday: '周五',
    QyAppLocalizationKeys.qySettingsWeekdaySaturday: '周六',
    QyAppLocalizationKeys.qySettingsWeekdaySunday: '周日',

    QyAppLocalizationKeys.qySettingsFontSettings: '字体设置',
    QyAppLocalizationKeys.qySettingsFont: '字体',
    QyAppLocalizationKeys.qySettingsAppearanceSettings: '外观设置',
    QyAppLocalizationKeys.qySettingsInterfaceLayout: '界面布局',
    QyAppLocalizationKeys.qySettingsStandardMode: '标准模式',
    QyAppLocalizationKeys.qySettingsAccessibility: '辅助功能',
    QyAppLocalizationKeys.qySettingsHighContrast: '高对比度',
    QyAppLocalizationKeys.qySettingsHighContrastSubtitle: '提高文字和背景的对比度',
    QyAppLocalizationKeys.qySettingsLargeFontMode: '大字体模式',
    QyAppLocalizationKeys.qySettingsLargeFontModeSubtitle: '适合视力不佳的用户',
    QyAppLocalizationKeys.qySettingsSelectFont: '选择字体',
    QyAppLocalizationKeys.qySettingsLayoutInProgress: '界面布局设置功能开发中...',

    QyAppLocalizationKeys.qySettingsModify: '修改',
    QyAppLocalizationKeys.qySettingsRebind: '换绑',
    QyAppLocalizationKeys.qySettingsBind: '绑定',
    QyAppLocalizationKeys.qySettingsAccountBinding: '账号绑定',
    QyAppLocalizationKeys.qySettingsPhone: '手机',
    QyAppLocalizationKeys.qySettingsNotBound: '尚未绑定',
    QyAppLocalizationKeys.qySettingsWechat: '微信',
    QyAppLocalizationKeys.qySettingsWeibo: '新浪微博',
    QyAppLocalizationKeys.qySettingsQQ: 'QQ',
    QyAppLocalizationKeys.qySettingsAccountDeletion: '账号注销',
    QyAppLocalizationKeys.qySettingsAccountDeletionSubtitle: '删除所有数据，永久注销',
    QyAppLocalizationKeys.qySettingsDeleteAccount: '注销',
    QyAppLocalizationKeys.qySettingsChangeUsername: '修改用户名',
    QyAppLocalizationKeys.qySettingsEnterNewUsername: '请输入新用户名',
    QyAppLocalizationKeys.qySettingsUsernameUpdated: '用户名已更新',
    QyAppLocalizationKeys.qySettingsChangePasswordTitle: '修改密码',
    QyAppLocalizationKeys.qySettingsEnterNewPassword: '请输入新密码',
    QyAppLocalizationKeys.qySettingsConfirmNewPassword: '请确认新密码',
    QyAppLocalizationKeys.qySettingsPasswordUpdated: '密码已更新',
    QyAppLocalizationKeys.qySettingsPhoneBinding: '手机号绑定',
    QyAppLocalizationKeys.qySettingsPhoneBindingInProgress: '手机号绑定功能开发中...',
    QyAppLocalizationKeys.qySettingsWechatBinding: '微信绑定',
    QyAppLocalizationKeys.qySettingsWechatBindingInProgress: '微信绑定功能开发中...',
    QyAppLocalizationKeys.qySettingsWeiboBinding: '微博绑定',
    QyAppLocalizationKeys.qySettingsWeiboBindingInProgress: '微博绑定功能开发中...',
    QyAppLocalizationKeys.qySettingsQQBinding: 'QQ绑定',
    QyAppLocalizationKeys.qySettingsQQBindingInProgress: 'QQ绑定功能开发中...',
    QyAppLocalizationKeys.qySettingsDeletionWarning: '警告：此操作不可恢复！',
    QyAppLocalizationKeys.qySettingsAfterDeletion: '注销账号后：',
    QyAppLocalizationKeys.qySettingsDeletionDataLoss: '所有学习数据将被永久删除',
    QyAppLocalizationKeys.qySettingsDeletionCourseLoss: '购买的课程和服务将无法使用',
    QyAppLocalizationKeys.qySettingsDeletionAccountClear: '账户信息将被彻底清除',
    QyAppLocalizationKeys.qySettingsConfirmDeletion: '确定要注销账号吗？',
    QyAppLocalizationKeys.qySettingsFinalConfirmation: '最终确认',
    QyAppLocalizationKeys.qySettingsFinalConfirmationMessage:
        '请再次确认：您真的要永久注销账号吗？',
    QyAppLocalizationKeys.qySettingsLetMeThink: '我再想想',
    QyAppLocalizationKeys.qySettingsAccountDeletionInProgress: '账号注销功能开发中...',

    QyAppLocalizationKeys.qySettingsSmartRecommendation: '智能推荐',
    QyAppLocalizationKeys.qySettingsAutoRecommend: '自动推荐',
    QyAppLocalizationKeys.qySettingsAutoRecommendSubtitle: '基于学习历史智能推荐单词',
    QyAppLocalizationKeys.qySettingsDifficulty: '难度',
    QyAppLocalizationKeys.qySettingsDifficultySettings: '难度设置',
    QyAppLocalizationKeys.qySettingsDifficultyBeginner: '初级',
    QyAppLocalizationKeys.qySettingsDifficultyIntermediate: '中级',
    QyAppLocalizationKeys.qySettingsDifficultyAdvanced: '高级',
    QyAppLocalizationKeys.qySettingsDifficultyExpert: '专家',
    QyAppLocalizationKeys.qySettingsInterestTags: '兴趣标签',
    QyAppLocalizationKeys.qySettingsInterestTagsSelected: '已选择 {count} 个兴趣标签',
    QyAppLocalizationKeys.qySettingsRecommendationFrequency: '推荐频率',
    QyAppLocalizationKeys.qySettingsRecommendationStrength: '推荐强度',
    QyAppLocalizationKeys.qySettingsSelectDifficulty: '选择难度',
    QyAppLocalizationKeys.qySettingsDifficultyBeginnerDesc: '适合初学者，基础词汇',
    QyAppLocalizationKeys.qySettingsDifficultyIntermediateDesc: '适合有一定基础的学习者',
    QyAppLocalizationKeys.qySettingsDifficultyAdvancedDesc: '适合高级学习者，专业词汇',
    QyAppLocalizationKeys.qySettingsDifficultyExpertDesc: '适合专家级学习者，学术词汇',

    // Word Book Module
    QyAppLocalizationKeys.qyWordBook: '回词表',
    QyAppLocalizationKeys.qyWords: '词',
    QyAppLocalizationKeys.qyCorpus: '语料库',
    QyAppLocalizationKeys.qyWordBookExampleSentence: '例句',
    QyAppLocalizationKeys.qyWordBookPronunciation: '发音',
    QyAppLocalizationKeys.qyWordBookMastered: '已掌握',
    QyAppLocalizationKeys.qyWordBookMasteryLevel: '掌握度',
    QyAppLocalizationKeys.qyWordBookNewWord: '新词',
    QyAppLocalizationKeys.qyWordBookLearning: '学习中',
    QyAppLocalizationKeys.qyWordBookAll: '全部',
    QyAppLocalizationKeys.qyNoWordBooks: '暂无词书',
    QyAppLocalizationKeys.qyPlayingAudio: '播放音频中',
    QyAppLocalizationKeys.qyExcellent: '优秀',
    QyAppLocalizationKeys.qyGoodJob: '做得好',
    QyAppLocalizationKeys.qyKeepPracticing: '继续练习',
    QyAppLocalizationKeys.qyYourScore: '你的得分',
    QyAppLocalizationKeys.qyDictation: '听写',
    QyAppLocalizationKeys.qyListenAndWrite: '听写',
    QyAppLocalizationKeys.qyTypeWhatYouHear: '输入你听到的内容',
    QyAppLocalizationKeys.qyEnterSentence: '输入句子',
    QyAppLocalizationKeys.qyFinish: '完成',
    QyAppLocalizationKeys.qyCheck: '检查',
    QyAppLocalizationKeys.qyFlashcards: '单词卡片',
    QyAppLocalizationKeys.qyTapToFlip: '点击翻转',
    QyAppLocalizationKeys.qyDefinition: '释义',
    QyAppLocalizationKeys.qyExamples: '例句',
    QyAppLocalizationKeys.qySynonyms: '同义词',
    QyAppLocalizationKeys.qyFlip: '翻转',
    QyAppLocalizationKeys.qyMarkedAsKnown: '已标记为已掌握',
    QyAppLocalizationKeys.qyMarkedForReview: '已标记为需复习',
    QyAppLocalizationKeys.qyReviewComplete: '复习完成',
    QyAppLocalizationKeys.qyReviewed: '已复习',
    QyAppLocalizationKeys.qyWordReview: '单词复习',
    QyAppLocalizationKeys.qyTapToHide: '点击隐藏',
    QyAppLocalizationKeys.qyTapToReveal: '点击显示',
    QyAppLocalizationKeys.qyMasteryLevel: '掌握程度',
    QyAppLocalizationKeys.qyLastReviewed: '上次复习',
    QyAppLocalizationKeys.qyNeedReview: '需要复习',
    QyAppLocalizationKeys.qyKnown: '已掌握',
    QyAppLocalizationKeys.qyHideDefinition: '隐藏释义',
    QyAppLocalizationKeys.qyShowDefinition: '显示释义',

    // Word Listening Module
    QyAppLocalizationKeys.qyListeningPlay: '播放',
    QyAppLocalizationKeys.qyListeningStop: '停止',
    QyAppLocalizationKeys.qyListeningLoop: '循环',
    QyAppLocalizationKeys.qyListeningOn: '开启',
    QyAppLocalizationKeys.qyListeningOff: '关闭',
    QyAppLocalizationKeys.qyListeningSpeedSlow: '慢速',
    QyAppLocalizationKeys.qyListeningSpeedNormal: '正常',
    QyAppLocalizationKeys.qyListeningSpeedFast: '快速',
    QyAppLocalizationKeys.qyListeningCategoryDaily: '日常词汇',
    QyAppLocalizationKeys.qyListeningCategoryDailyDesc: '基础日常用语',
    QyAppLocalizationKeys.qyListeningCategoryBusiness: '商务英语',
    QyAppLocalizationKeys.qyListeningCategoryBusinessDesc: '职场商务词汇',
    QyAppLocalizationKeys.qyListeningCategoryAcademic: '学术词汇',
    QyAppLocalizationKeys.qyListeningCategoryAcademicDesc: '学术专业术语',
    QyAppLocalizationKeys.qyListeningCategoryTravel: '旅游英语',
    QyAppLocalizationKeys.qyListeningCategoryTravelDesc: '旅行交流词汇',
    QyAppLocalizationKeys.qyListeningCategoryTech: '科技词汇',
    QyAppLocalizationKeys.qyListeningCategoryTechDesc: '科学技术术语',
    QyAppLocalizationKeys.qyListeningCategoryMedical: '医学词汇',
    QyAppLocalizationKeys.qyListeningCategoryMedicalDesc: '医疗健康术语',
    QyAppLocalizationKeys.qyListeningDictationBeginner: '初级听写',
    QyAppLocalizationKeys.qyListeningDictationBeginnerDesc: '基础词汇，慢速播放',
    QyAppLocalizationKeys.qyListeningDictationIntermediate: '中级听写',
    QyAppLocalizationKeys.qyListeningDictationIntermediateDesc: '常用词汇，标准语速',
    QyAppLocalizationKeys.qyListeningDictationAdvanced: '高级听写',
    QyAppLocalizationKeys.qyListeningDictationAdvancedDesc: '专业词汇，快速播放',
    QyAppLocalizationKeys.qyListeningDictationExpert: '专家听写',
    QyAppLocalizationKeys.qyListeningDictationExpertDesc: '复杂句子，原速播放',
    QyAppLocalizationKeys.qyListeningDictation: '单词听写',
    QyAppLocalizationKeys.qyListeningDictationTitle: '听写训练',
    QyAppLocalizationKeys.qyListeningDictationDesc: '通过听写提升拼写和听力能力',
    QyAppLocalizationKeys.qyListeningQuestionNumber: '第 {index} / {total} 题',
    QyAppLocalizationKeys.qyListeningAccuracy: '正确率',
    QyAppLocalizationKeys.qyListeningProgress: '练习进度',
    QyAppLocalizationKeys.qyListeningPlayWord: '播放单词',
    QyAppLocalizationKeys.qyListeningStopPlay: '停止播放',
    QyAppLocalizationKeys.qyListeningPlayCount: '播放次数',
    QyAppLocalizationKeys.qyListeningEnterWord: '请输入听到的单词',
    QyAppLocalizationKeys.qyListeningInputPlaceholder: '在此输入单词...',
    QyAppLocalizationKeys.qyListeningSubmitAnswer: '提交答案',
    QyAppLocalizationKeys.qyListeningHint: '提示',
    QyAppLocalizationKeys.qyListeningHintMessage:
        '提示：这个词以 "{letter}" 开头，共 {length} 个字母',
    QyAppLocalizationKeys.qyListeningCorrect: '回答正确！',
    QyAppLocalizationKeys.qyListeningIncorrect: '回答错误',
    QyAppLocalizationKeys.qyListeningCorrectAnswer: '正确答案',
    QyAppLocalizationKeys.qyListeningMeaning: '词义',
    QyAppLocalizationKeys.qyListeningExample: '例句',
    QyAppLocalizationKeys.qyListeningPrevious: '上一题',
    QyAppLocalizationKeys.qyListeningNext: '下一题',
    QyAppLocalizationKeys.qyListeningComplete: '完成',
    QyAppLocalizationKeys.qyListeningPracticeComplete: '练习完成！',
    QyAppLocalizationKeys.qyListeningCorrectAnswers: '正确答案',
    QyAppLocalizationKeys.qyListeningTodayListening: '今日听力',
    QyAppLocalizationKeys.qyListeningLearnedWords: '已学词汇',
    QyAppLocalizationKeys.qyListeningStreakDays: '连续天数',
    QyAppLocalizationKeys.qyListeningTodayPractice: '今日练习',
    QyAppLocalizationKeys.qyListeningWeekPractice: '本周练习',
    QyAppLocalizationKeys.qyListeningTotalTime: '总练习时长',
    QyAppLocalizationKeys.qyListeningContinuousDays: '连续学习',
    QyAppLocalizationKeys.qyListeningDailyAverage: '平均每日',
    QyAppLocalizationKeys.qyListeningFreeTitle: '自由听力',
    QyAppLocalizationKeys.qyListeningFreeDesc: '选择类别，自由练习',
    QyAppLocalizationKeys.qyListeningSpeed: '播放速度',
    QyAppLocalizationKeys.qyListeningCurrentWord: '当前单词',
    QyAppLocalizationKeys.qyListeningNextWordTip: '切换到下一个单词',
    QyAppLocalizationKeys.qyListeningStats: '听力统计',
    QyAppLocalizationKeys.qyListeningAddToVocab: '添加到生词本',
    QyAppLocalizationKeys.qyListeningPracticing: '练习中',
    QyAppLocalizationKeys.qyListeningDailyChallenge: '每日挑战',
    QyAppLocalizationKeys.qyListeningUnlockTip: '完成当前级别后解锁',
    QyAppLocalizationKeys.qyListeningHelp: '听写训练帮助',
    QyAppLocalizationKeys.qyListeningHelpContent:
        '1. 选择适合的难度级别\n2. 点击播放按钮听取单词发音\n3. 在输入框中拼写听到的单词\n4. 提交答案查看结果',
    QyAppLocalizationKeys.qyListeningHelpTips:
        '• 可以重复播放单词发音\n• 注意大小写\n• 可以使用提示功能\n• 坚持每天练习效果更佳',
    QyAppLocalizationKeys.qyListeningGotIt: '知道了',
    QyAppLocalizationKeys.qyListeningDailyChallengeComingSoon: '每日挑战功能开发中...',
    QyAppLocalizationKeys.qyListeningSelectCategory: '选择词汇类别开始听力练习',
    QyAppLocalizationKeys.qyListeningPlaylist: '播放列表',
    QyAppLocalizationKeys.qyListeningMinutes: '分钟',
    QyAppLocalizationKeys.qyListeningDays: '天',

    // Word Listening - Sleep Mode
    QyAppLocalizationKeys.qyListeningSleepTitle: '睡眠听力',
    QyAppLocalizationKeys.qyListeningSleepSubtitle: '舒缓词汇，助眠入眠',
    QyAppLocalizationKeys.qyListeningSleepCategorySoothing: '舒缓词汇',
    QyAppLocalizationKeys.qyListeningSleepCategoryNature: '自然词汇',
    QyAppLocalizationKeys.qyListeningSleepCategoryStory: '故事词汇',
    QyAppLocalizationKeys.qyListeningSleepCategoryPoetry: '诗歌词汇',
    QyAppLocalizationKeys.qyListeningSleepCategoryMeditation: '冥想词汇',
    QyAppLocalizationKeys.qyListeningSleepSelectCategory: '选择词汇类别',
    QyAppLocalizationKeys.qyListeningSleepDuration: '播放时长',
    QyAppLocalizationKeys.qyListeningSleepMinutes: '{minutes}分钟',
    QyAppLocalizationKeys.qyListeningSleepTipsTitle: '睡眠小贴士',
    QyAppLocalizationKeys.qyListeningSleepTip1: '• 睡前1小时避免使用电子设备',
    QyAppLocalizationKeys.qyListeningSleepTip2: '• 保持卧室温度在18-22°C',
    QyAppLocalizationKeys.qyListeningSleepTip3: '• 使用柔和的背景音乐',
    QyAppLocalizationKeys.qyListeningSleepTip4: '• 调整屏幕亮度至最低',
    QyAppLocalizationKeys.qyListeningSleepStart: '开始睡眠听力',
    QyAppLocalizationKeys.qyListeningSleepPlaying: '正在播放舒缓词汇...',
    QyAppLocalizationKeys.qyListeningSleepRemainingTime: '剩余时间: {time}',
    QyAppLocalizationKeys.qyListeningSleepProgress: '播放进度',
    QyAppLocalizationKeys.qyListeningSleepEnd: '结束睡眠模式',
    QyAppLocalizationKeys.qyListeningSleepPrevious: '上一个词汇',
    QyAppLocalizationKeys.qyListeningSleepNext: '下一个词汇',
    QyAppLocalizationKeys.qyListeningSleepEndTitle: '睡眠模式结束',
    QyAppLocalizationKeys.qyListeningSleepEndMessage:
        '希望您有一个美好的睡眠！\n已播放 {minutes} 分钟舒缓词汇。',
    QyAppLocalizationKeys.qyListeningSleepContinue: '继续听力',

    // Courses
    QyAppLocalizationKeys.qyCoursesTitle: '课程中心',
    QyAppLocalizationKeys.qyCoursesFeatured: '精选课程',
    QyAppLocalizationKeys.qyCoursesCategories: '课程分类',
    QyAppLocalizationKeys.qyCoursesTagline: '专业师资 • 系统学习',
    QyAppLocalizationKeys.qyCoursesCount: '{count} 个课程',
    QyAppLocalizationKeys.qyCoursesInDev: '{name}功能开发中...',
    QyAppLocalizationKeys.qyCourseHotCategoriesTitle: '热门分类',
    QyAppLocalizationKeys.qyCourseCategoryCet: '四六级',
    QyAppLocalizationKeys.qyCourseCategoryPostgraduate: '考研',
    QyAppLocalizationKeys.qyCourseCategoryOral: '实用口语',
    QyAppLocalizationKeys.qyCourseCategoryPython: 'Python',
    QyAppLocalizationKeys.qyCourseCategoryReading: '阅读',
    QyAppLocalizationKeys.qyCourseCategoryCollege: '大学生备考',
    QyAppLocalizationKeys.qyCourseLearningFocusTitle: '学习方向',
    QyAppLocalizationKeys.qyCourseFocusEfficientTitle: '高效备考',
    QyAppLocalizationKeys.qyCourseFocusEfficientSubtitle: '6 周冲刺计划',
    QyAppLocalizationKeys.qyCourseFocusDailyTitle: '日常口语',
    QyAppLocalizationKeys.qyCourseFocusDailySubtitle: '地道表达合集',
    QyAppLocalizationKeys.qyCourseFocusCareerTitle: '职场提升',
    QyAppLocalizationKeys.qyCourseFocusCareerSubtitle: '商务写作 + 演讲',
    QyAppLocalizationKeys.qyCourseVipLabel: '大会员年卡',
    QyAppLocalizationKeys.qyCourseVipHeadline: '职场提升从小白到高手',
    QyAppLocalizationKeys.qyCourseVipSubhead: '职场商务口语计划 · 全年最低价',
    QyAppLocalizationKeys.qyCourseVipBenefit1: '全年最低价 · 加赠千语大会员年卡',
    QyAppLocalizationKeys.qyCourseVipBenefit2: '单词 / 阅读 / 听力口语 / 考研 全覆盖',
    QyAppLocalizationKeys.qyCourseVipBenefit3: 'AI 智能学习路径 · 随时随地练习',
    QyAppLocalizationKeys.qyCourseVipCta: '去开通',
    QyAppLocalizationKeys.qyCoursePlanBadgeAdvanced: '进阶计划',
    QyAppLocalizationKeys.qyCoursePlanBadgeFlagship: '旗舰课程',
    QyAppLocalizationKeys.qyCoursePlanTitleCareerUpgrade: '职场提升从小白到高手',
    QyAppLocalizationKeys.qyCoursePlanDescriptionCareerUpgrade:
        '循序渐进掌握商务沟通、会议表达与项目汇报能力。',
    QyAppLocalizationKeys.qyCoursePlanDuration12Weeks: '12 周',
    QyAppLocalizationKeys.qyCoursePlanTitleBusinessCommunication: '职场商务口语计划',
    QyAppLocalizationKeys.qyCoursePlanDescriptionBusinessCommunication:
        '真实场景还原，打造沉浸式情景对话能力。',
    QyAppLocalizationKeys.qyCoursePlanDuration24Lessons: '24 节',
    QyAppLocalizationKeys.qyCoursePlanActionExperience: '立即体验',
    QyAppLocalizationKeys.qyCoursePlanActionDetails: '查看详情',
    QyAppLocalizationKeys.qyCoursePlanActionStart: '立即开始',
    QyAppLocalizationKeys.qyCourseOpening: '课程打开中',
    QyAppLocalizationKeys.qyCourseVipSnackbar: '大会员权益加载中...',
    QyAppLocalizationKeys.qyCoursePythonZoneTitle: 'Python 学习专区',
    QyAppLocalizationKeys.qyCourseDigitalSkill: '数字时代硬技能',
    QyAppLocalizationKeys.qyCoursePythonPathTitle: 'Python 全栈学习路径',
    QyAppLocalizationKeys.qyCoursePythonPathDescription:
        '21 天入门，14 天进阶，数据分析与案例实战一站掌握。',
    QyAppLocalizationKeys.qyCourseBadgeIntro: '入门',
    QyAppLocalizationKeys.qyCourseBadgeIntermediate: '进阶',
    QyAppLocalizationKeys.qyCourseBadgePopular: '热门',
    QyAppLocalizationKeys.qyCourseBadgePractical: '实战',
    QyAppLocalizationKeys.qyCourseVipFreeTag: '大会员年卡免费',
    QyAppLocalizationKeys.qyCoursePythonIntroTitle: 'Python 21天入门',
    QyAppLocalizationKeys.qyCoursePythonIntroSubtitle: '除了英语，再学一门未来新语言',
    QyAppLocalizationKeys.qyCoursePythonAdvanceTitle: 'Python 14天进阶',
    QyAppLocalizationKeys.qyCoursePythonAdvanceSubtitle: '高手晋级修炼',
    QyAppLocalizationKeys.qyCoursePythonDataTitle: 'Python 数据分析',
    QyAppLocalizationKeys.qyCoursePythonDataSubtitle: '编程赋能数据，创造高效未来',
    QyAppLocalizationKeys.qyCoursePythonCasesTitle: '数据分析案例实战',
    QyAppLocalizationKeys.qyCoursePythonCasesSubtitle: '数据思维 + 三大数据分析利器',
    QyAppLocalizationKeys.qyCourseExperienceZoneTitle: '体验区',
    QyAppLocalizationKeys.qyCourseVipExperienceSubtitle: '全年最低价 · 还加赠千语大会员年卡',
    QyAppLocalizationKeys.qyCourseVipCoverage: '畅享「单词 + 阅读 + 听力口语 + 考研」全站会员权益。',
    QyAppLocalizationKeys.qyCoursePlanCategoryIelts: '雅思',
    QyAppLocalizationKeys.qyCoursePlanCategoryGaokao: '高考',
    QyAppLocalizationKeys.qyCoursePlanCategoryMiddle: '初中/中考',
    QyAppLocalizationKeys.qyCoursePlanAllSkillTagline: '听说读写 · 全能学习计划',
    QyAppLocalizationKeys.qyCoursePlanAllSkillDescription: '整周训练搭配直播点评，能力全面提升。',
    QyAppLocalizationKeys.qyCoursePlanClassicTitle: '精读原版经典',
    QyAppLocalizationKeys.qyCoursePlanClassicName: '7天英文原版入门计划',
    QyAppLocalizationKeys.qyCoursePlanClassicStats: '3.1万人 · 7天',
    QyAppLocalizationKeys.qyCoursePlanOralTitle: '积累地道口语',
    QyAppLocalizationKeys.qyCoursePlanOralName: '7天生活英语计划',
    QyAppLocalizationKeys.qyCoursePlanOralStats: '1.2万人 · 7天',
    QyAppLocalizationKeys.qyCoursePlanReadingTitle: '阅读写作 · 专项拓展',
    QyAppLocalizationKeys.qyCoursePlanViewMore: '查看更多',
    QyAppLocalizationKeys.qyCoursePlanTextbookSync: '教材同步',
    QyAppLocalizationKeys.qyCoursePlanTextbookTitle: '译林七年级拓展学习（上册）',
    QyAppLocalizationKeys.qyCoursePlanReadingBrand: '千语阅读',
    QyAppLocalizationKeys.qyCoursePlanFurtherStudy: 'Further Study配套读本',
    QyAppLocalizationKeys.qyCoursePlanTextbookGrade: '译林七年级',
    QyAppLocalizationKeys.qyCoursePlanMoreComing: '更多学习计划敬请期待',

    // Course Detail
    QyAppLocalizationKeys.qyCourseContinue: '继续学习',
    QyAppLocalizationKeys.qyCourseContinueCoding: '继续编程',
    QyAppLocalizationKeys.qyCourseOverview: '概览',
    QyAppLocalizationKeys.qyCourseLessons: '课程',
    QyAppLocalizationKeys.qyCourseProjects: '项目',
    QyAppLocalizationKeys.qyCourseProgress: '进度',
    QyAppLocalizationKeys.qyOverview: '概览',
    QyAppLocalizationKeys.qyCurriculum: '课程大纲',
    QyAppLocalizationKeys.qyReviews: '评价',
    QyAppLocalizationKeys.qyUserReviews: '用户评价',
    QyAppLocalizationKeys.qyAboutCourse: '课程介绍',
    QyAppLocalizationKeys.qyInstructor: '讲师',
    QyAppLocalizationKeys.qyLevel: '难度',
    QyAppLocalizationKeys.qyDuration: '时长',
    QyAppLocalizationKeys.qyPrice: '价格',
    QyAppLocalizationKeys.qyEnrolled: '已报名',
    QyAppLocalizationKeys.qyEnrollNow: '立即报名',
    QyAppLocalizationKeys.qyCourseEnrolled: '已加入课程',
    QyAppLocalizationKeys.qyCourseUnenrolled: '未加入',
    QyAppLocalizationKeys.qyLessonComplete: '课程完成',
    QyAppLocalizationKeys.qyCongratulations: '恭喜',
    QyAppLocalizationKeys.qySection: '小节',
    QyAppLocalizationKeys.qyPause: '暂停',
    QyAppLocalizationKeys.qyPlay: '播放',
    QyAppLocalizationKeys.qyQuestions: '问题',
    QyAppLocalizationKeys.qyStartQuiz: '开始测验',
    QyAppLocalizationKeys.qyOverallProgress: '总体进度',
    QyAppLocalizationKeys.qyLessonsCompleted: '课程完成',
    QyAppLocalizationKeys.qyRemaining: '剩余',
    QyAppLocalizationKeys.qyAvgScore: '平均分',
    QyAppLocalizationKeys.qyChapters: '章节',
    QyAppLocalizationKeys.qyLessons: '课时',
    QyAppLocalizationKeys.qyHelpful: '有帮助',
    QyAppLocalizationKeys.qySearchCourses: '搜索课程',
    QyAppLocalizationKeys.qyBusiness: '商务',
    QyAppLocalizationKeys.qyTestPrep: '考试准备',
    QyAppLocalizationKeys.qyGeneral: '通用',
    QyAppLocalizationKeys.qyAcademic: '学术',
    QyAppLocalizationKeys.qyRecentSearches: '最近搜索',
    QyAppLocalizationKeys.qyPopularSearches: '热门搜索',
    QyAppLocalizationKeys.qyDownloading: '下载中',
    QyAppLocalizationKeys.qySharing: '分享中',
    QyAppLocalizationKeys.qyCertificate: '证书',
    QyAppLocalizationKeys.qyCertificateOfCompletion: '结业证书',
    QyAppLocalizationKeys.qyThisCertifies: '特此证明',
    QyAppLocalizationKeys.qyHasSuccessfullyCompleted: '已成功完成',
    QyAppLocalizationKeys.qyCompletionDate: '完成日期',
    QyAppLocalizationKeys.qyFinalScore: '最终成绩',
    QyAppLocalizationKeys.qyVerifiedCertificate: '认证证书',
    QyAppLocalizationKeys.qyCertificateId: '证书编号',
    QyAppLocalizationKeys.qyIssued: '颁发',
    QyAppLocalizationKeys.qyStatus: '状态',
    QyAppLocalizationKeys.qyValid: '有效',
    QyAppLocalizationKeys.qyPrint: '打印',
    QyAppLocalizationKeys.qyCourseLearningProgress: '编程学习进度',
    QyAppLocalizationKeys.qyCourseCompletedLessons:
        '已完成 {completed}/{total} 节课',
    QyAppLocalizationKeys.qyCourseConsecutiveDays: '连续 {days} 天',
    QyAppLocalizationKeys.qyCourseProjectsCompleted: '完成项目 {count} 个',
    QyAppLocalizationKeys.qyCourseLinesOfCode: '编程 {lines} 行',
    QyAppLocalizationKeys.qyCourseInfo: '课程信息',
    QyAppLocalizationKeys.qyCourseDuration: '课程时长',
    QyAppLocalizationKeys.qyCourseCodePractice: '代码练习',
    QyAppLocalizationKeys.qyCourseDifficultyProgression: '难度递进',
    QyAppLocalizationKeys.qyCourseRating: '课程评分',
    QyAppLocalizationKeys.qyCourseFeatures: '课程特色',
    QyAppLocalizationKeys.qyCourseInstructor: '授课导师',
    QyAppLocalizationKeys.qyCourseLearningPath: '学习路径',
    QyAppLocalizationKeys.qyCourseCurriculum: '课程内容',
    QyAppLocalizationKeys.qyCourseWeek: '第{week}周',
    QyAppLocalizationKeys.qyCourseModule: '模块',
    QyAppLocalizationKeys.qyCourseCompleted: '已完成',
    QyAppLocalizationKeys.qyCourseInProgress: '学习中',
    QyAppLocalizationKeys.qyCourseLocked: '未解锁',
    QyAppLocalizationKeys.qyCourseStart: '开始学习',
    QyAppLocalizationKeys.qyCourseResume: '继续学习',

    // Common
    QyAppLocalizationKeys.qyCommonOk: '好的',
    QyAppLocalizationKeys.qyCommonGotIt: '知道了',

    // Home Page
    QyAppLocalizationKeys.qyHomeStudy: '单词',
    QyAppLocalizationKeys.qyHomeCourse: '课程',
    QyAppLocalizationKeys.qyHomeAi: 'AI学',
    QyAppLocalizationKeys.qyHomeDiscover: '发现',
    QyAppLocalizationKeys.qyHomeProfile: '我的',
    QyAppLocalizationKeys.qyHomeMoreFeatures: '更多功能',
    QyAppLocalizationKeys.qyHomeConsolidate: '巩固',
    QyAppLocalizationKeys.qyHomeWordTest: '单词测试',
    QyAppLocalizationKeys.qyHomePortableListening: '随身听',
    QyAppLocalizationKeys.qyHomePhrase: '短语',
    QyAppLocalizationKeys.qyHomeSpeedReview: '极速刷词',
    QyAppLocalizationKeys.qyHomeExtension: '扩展',
    QyAppLocalizationKeys.qyHomeReading: '阅读',
    QyAppLocalizationKeys.qyHomeListeningSpeaking: '听力口语',
    QyAppLocalizationKeys.qyHomeLearnSettings: '学习设置',
    QyAppLocalizationKeys.qyHomeLearnData: '学习数据',
    QyAppLocalizationKeys.qyHomeLearned: '已学',
    QyAppLocalizationKeys.qyHomeWordsTotal: '词',
    QyAppLocalizationKeys.qyHomeNewWords: '新学词',
    QyAppLocalizationKeys.qyHomeReviewWords: '复习词',
    QyAppLocalizationKeys.qyHomeStartLearning: '开始学习',
    QyAppLocalizationKeys.qyHomeCheckInDays: '打卡天数',
    QyAppLocalizationKeys.qyHomeBadges: '徽章数',

    // Login Page
    QyAppLocalizationKeys.qyLoginSlogan1: 'Every word',
    QyAppLocalizationKeys.qyLoginSlogan2: 'counts here',
    QyAppLocalizationKeys.qyLoginPhoneNumber: '手机号',
    QyAppLocalizationKeys.qyLoginByPhone: '手机号登录',
    QyAppLocalizationKeys.qyLoginByWechat: '微信登录',
    QyAppLocalizationKeys.qyLoginByAccount: '千语账号',
    QyAppLocalizationKeys.qyLoginByWeibo: '微博',
    QyAppLocalizationKeys.qyLoginRememberWords: '记住单词',
    QyAppLocalizationKeys.qyLoginRecordChange: '记录改变',
    QyAppLocalizationKeys.qyPleaseEnterPhone: '请输入手机号',
    QyAppLocalizationKeys.qyPleaseAgreeTerms: '请同意服务条款',
    QyAppLocalizationKeys.qyPleaseCompleteForm: '请完成表单',
    QyAppLocalizationKeys.qyEnterPhone: '输入手机号',
    QyAppLocalizationKeys.qyEnterCode: '输入验证码',
    QyAppLocalizationKeys.qySendCode: '发送验证码',
    QyAppLocalizationKeys.qyAgreeToTermsPrefix: '我同意',
    QyAppLocalizationKeys.qyUserAgreement: '用户协议',
    QyAppLocalizationKeys.qyAnd: '和',
    QyAppLocalizationKeys.qyGetCode: '获取验证码',
    QyAppLocalizationKeys.qyOtherLoginMethods: '其他登录方式',
    QyAppLocalizationKeys.qyWechat: '微信',
    QyAppLocalizationKeys.qyQyAccount: '千语账号',
    QyAppLocalizationKeys.qyWeibo: '微博',

    // Common
    QyAppLocalizationKeys.qyGuest: '游客',
    QyAppLocalizationKeys.qySearching: '搜索中',
    QyAppLocalizationKeys.qyCourse: '课程',
    QyAppLocalizationKeys.qyViewAll: '查看全部',

    // Course Categories
    QyAppLocalizationKeys.qyCourseCategoryFeatured: '精选',
    QyAppLocalizationKeys.qyCourseCategoryIelts: '雅思',
    QyAppLocalizationKeys.qyCourseCategoryGaokao: '高考',
    QyAppLocalizationKeys.qyCourseCategoryMiddle: '中学',

    // Course Details
    QyAppLocalizationKeys.qyTodayFeatured: '今日推荐',
    QyAppLocalizationKeys.qyUpdatedDaily: '每日更新',
    QyAppLocalizationKeys.qyCourseListening: '听力',
    QyAppLocalizationKeys.qyCourseLevelIntermediate: '中级',
    QyAppLocalizationKeys.qyCourseFood: '食品',
    QyAppLocalizationKeys.qyCourseReading: '阅读',
    QyAppLocalizationKeys.qyCourseLevelBeginner: '初级',
    QyAppLocalizationKeys.qyRecommendedCourses: '推荐课程',
    QyAppLocalizationKeys.qyExclusivePlans: '专属计划',
    QyAppLocalizationKeys.qyStartLearning: '开始学习',
    QyAppLocalizationKeys.qyContinueLearning: '继续学习',
    QyAppLocalizationKeys.qyPlanName: '计划名称',
    QyAppLocalizationKeys.qyPlanDescription: '计划描述',
    QyAppLocalizationKeys.qyLessonCompleted: '已完成课程',
    QyAppLocalizationKeys.qyTotalLessons: '总课程数',
    QyAppLocalizationKeys.qyFreeLesson: '免费',
    QyAppLocalizationKeys.qyPremiumLesson: '会员',

    // Course Plans
    QyAppLocalizationKeys.qyViewPlans: '查看计划',
    QyAppLocalizationKeys.qyVipPromotionTitle: 'VIP推广',
    QyAppLocalizationKeys.qyVipYearCard: '年度VIP',
    QyAppLocalizationKeys.qyVipBenefits: 'VIP权益',
    QyAppLocalizationKeys.qyActivateNow: '立即激活',
    QyAppLocalizationKeys.qyLearningPlans: '学习计划',
    QyAppLocalizationKeys.qyNoPlansYet: '暂无计划',
    QyAppLocalizationKeys.qyCreateFirstPlan: '创建第一个计划',
    QyAppLocalizationKeys.qySelectGoal: '选择目标',
    QyAppLocalizationKeys.qySelectTime: '选择时间',
    QyAppLocalizationKeys.qySelectCourse: '选择课程',
    QyAppLocalizationKeys.qyDiscoverPerfectPlan: '发现你的完美计划',
    QyAppLocalizationKeys.qyNoPlans: '暂无计划',
    QyAppLocalizationKeys.qyAllPlans: '所有计划',
    QyAppLocalizationKeys.qyJoined: '已加入',
    QyAppLocalizationKeys.qyJoinPlan: '加入计划',

    // Word Learning
    QyAppLocalizationKeys.qyGeneralSearch: '通用搜索',
    QyAppLocalizationKeys.qyBookSearch: '书籍搜索',
    QyAppLocalizationKeys.qyTotal: '总计',
    QyAppLocalizationKeys.qyLearned: '已学',
    QyAppLocalizationKeys.qyStarting: '开始',
    QyAppLocalizationKeys.qyWordNewWordBook: '新单词书',
    QyAppLocalizationKeys.qyWordProgress: '单词进度',
    QyAppLocalizationKeys.qyWordPaused: '已暂停',
    QyAppLocalizationKeys.qyWordResume: '恢复',
    QyAppLocalizationKeys.qyWordPause: '暂停',
    QyAppLocalizationKeys.qyWordCompleted: '已完成',
    QyAppLocalizationKeys.qyWordUnlocked: '已解锁',
    QyAppLocalizationKeys.qyWordLocked: '已锁定',
    QyAppLocalizationKeys.qyWordBookDesc: '词书描述',
    QyAppLocalizationKeys.qyWordVocabulary: '词汇',

    // Word Listening AI Explain
    QyAppLocalizationKeys.qyListeningAIExplainTitle: 'AI解析',
    QyAppLocalizationKeys.qyListeningAIAnalyzing: 'AI正在分析中...',
    QyAppLocalizationKeys.qyListeningAIAnalysis: 'AI分析',
    QyAppLocalizationKeys.qyListeningEtymology: '词源',
    QyAppLocalizationKeys.qyListeningSynonyms: '同义词',
    QyAppLocalizationKeys.qyListeningAntonyms: '反义词',
    QyAppLocalizationKeys.qyListeningCollocations: '搭配',
    QyAppLocalizationKeys.qyListeningStartPractice: '开始练习',
    QyAppLocalizationKeys.qyListeningBackToStudy: '返回学习',
    QyAppLocalizationKeys.qyListeningShareInDev: '分享功能开发中',
    QyAppLocalizationKeys.qyListeningPracticeInDev: '练习功能开发中',
  };

  /// Get locales for runCommonApp
  static List<Map<String, String>> get locales => [values];
}
