// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

import 'localization_keys_app_qy.dart';

/// Chinese localization for QY App
class ZhAppQy {
  static const Map<String, String> values = {
    // App Identity
    QyAppLocalizationKeys.qyAppName: 'QY 应用',
    QyAppLocalizationKeys.qyAppDescription: '综合学习与成长的平台',
    QyAppLocalizationKeys.qyAppSlogan: '学习、构建、成长',
    QyAppLocalizationKeys.qyAppVersion: '版本 1.0.0',
    QyAppLocalizationKeys.qyAppSettings: '应用设置',
    QyAppLocalizationKeys.qySloganWords: '赋能你的学习旅程',
    QyAppLocalizationKeys.qySloganEyes: '让目光专注于知识',
    QyAppLocalizationKeys.qyLetsStart: '开始体验',
    QyAppLocalizationKeys.qyDoNotHaveAccount: '还没有账号？',
    QyAppLocalizationKeys.qySignupForFree: '立即免费注册',
    QyAppLocalizationKeys.qyWelcome: '欢迎回来',
    QyAppLocalizationKeys.qyGreeting: '你好，学习者！',
    QyAppLocalizationKeys.qyWelcomeBack: '欢迎回来',
    QyAppLocalizationKeys.qyGuestMode: '访客模式',

    // Common Actions
    QyAppLocalizationKeys.qyHome: '首页',
    QyAppLocalizationKeys.qyMenu: '菜单',
    QyAppLocalizationKeys.qySocial: '社交',
    QyAppLocalizationKeys.qySupport: '支持',
    QyAppLocalizationKeys.qyNext: '下一步',
    QyAppLocalizationKeys.qyPrevious: '上一步',
    QyAppLocalizationKeys.qySkip: '跳过',
    QyAppLocalizationKeys.qyCancel: '取消',
    QyAppLocalizationKeys.qyConfirm: '确认',
    QyAppLocalizationKeys.qySave: '保存',
    QyAppLocalizationKeys.qyDelete: '删除',
    QyAppLocalizationKeys.qyEdit: '编辑',
    QyAppLocalizationKeys.qyBack: '返回',
    QyAppLocalizationKeys.qyClose: '关闭',
    QyAppLocalizationKeys.qyOk: '确定',
    QyAppLocalizationKeys.qyYes: '是',
    QyAppLocalizationKeys.qyNo: '否',
    QyAppLocalizationKeys.qyContinue: '继续',
    QyAppLocalizationKeys.qySubmit: '提交',
    QyAppLocalizationKeys.qyRetry: '重试',
    QyAppLocalizationKeys.qyRefresh: '刷新',
    QyAppLocalizationKeys.qySearch: '搜索',
    QyAppLocalizationKeys.qySearchPlaceholder: '搜索…',
    QyAppLocalizationKeys.qyEnterSearchText: '请输入搜索内容',
    QyAppLocalizationKeys.qyFilter: '筛选',
    QyAppLocalizationKeys.qySort: '排序',
    QyAppLocalizationKeys.qyClear: '清除',
    QyAppLocalizationKeys.qyReset: '重置',
    QyAppLocalizationKeys.qyTopUp: '充值',

    // Status Messages
    QyAppLocalizationKeys.qySuccess: '成功',
    QyAppLocalizationKeys.qyError: '错误',
    QyAppLocalizationKeys.qyWarning: '警告',
    QyAppLocalizationKeys.qyInfo: '提示',
    QyAppLocalizationKeys.qyLoading: '加载中...',
    QyAppLocalizationKeys.qyCompleted: '已完成',
    QyAppLocalizationKeys.qyPending: '待处理',
    QyAppLocalizationKeys.qyFailed: '失败',

    // Authentication
    QyAppLocalizationKeys.qySignIn: '登录',
    QyAppLocalizationKeys.qySignUp: '注册',
    QyAppLocalizationKeys.qySignOut: '退出',
    QyAppLocalizationKeys.qyLogout: '退出登录',
    QyAppLocalizationKeys.qyLogoutConfirm: '确定要退出当前账号吗？',
    QyAppLocalizationKeys.qyLogoutSuccess: '已成功退出登录',
    QyAppLocalizationKeys.qyLogoutFailed: '退出失败，请重试',
    QyAppLocalizationKeys.qyYesLogout: '确认退出',
    QyAppLocalizationKeys.qyLogin: '登录',
    QyAppLocalizationKeys.qyRegister: '注册',
    QyAppLocalizationKeys.qyForgotPassword: '忘记密码',
    QyAppLocalizationKeys.qyResetPassword: '重置密码',
    QyAppLocalizationKeys.qyChangePassword: '修改密码',
    QyAppLocalizationKeys.qyEmail: '邮箱',
    QyAppLocalizationKeys.qyPassword: '密码',
    QyAppLocalizationKeys.qyConfirmPassword: '确认密码',
    QyAppLocalizationKeys.qyUsername: '用户名',
    QyAppLocalizationKeys.qyRememberMe: '记住我',
    QyAppLocalizationKeys.qyCreateAccount: '创建账号',
    QyAppLocalizationKeys.qyHaveAccount: '已有账号？',
    QyAppLocalizationKeys.qyNoAccount: '还没有账号？',

    // Profile & Settings
    QyAppLocalizationKeys.qyProfile: '个人中心',
    QyAppLocalizationKeys.qyMyProfile: '我的资料',
    QyAppLocalizationKeys.qyEditProfile: '编辑资料',
    QyAppLocalizationKeys.qyPersonalInfo: '个人信息',
    QyAppLocalizationKeys.qyFirstName: '名字',
    QyAppLocalizationKeys.qyLastName: '姓氏',
    QyAppLocalizationKeys.qyFullName: '姓名',
    QyAppLocalizationKeys.qyPhoneNumber: '电话号码',
    QyAppLocalizationKeys.qyAddress: '地址',
    QyAppLocalizationKeys.qyBirthDate: '出生日期',
    QyAppLocalizationKeys.qyGender: '性别',
    QyAppLocalizationKeys.qyAvatar: '头像',
    QyAppLocalizationKeys.qyBio: '个性签名',
    QyAppLocalizationKeys.qySettings: '设置',
    QyAppLocalizationKeys.qyGeneralSettings: '通用设置',
    QyAppLocalizationKeys.qyAccountSettings: '账号设置',
    QyAppLocalizationKeys.qyPrivacySettings: '隐私设置',
    QyAppLocalizationKeys.qyNotificationSettings: '通知设置',
    QyAppLocalizationKeys.qyLanguageSettings: '语言设置',
    QyAppLocalizationKeys.qyThemeSettings: '主题设置',
    QyAppLocalizationKeys.qyBiometricAuth: '生物识别登录',
    QyAppLocalizationKeys.qyDarkMode: '深色模式',
    QyAppLocalizationKeys.qyLightMode: '浅色模式',
    QyAppLocalizationKeys.qySystemMode: '跟随系统',
    QyAppLocalizationKeys.qyLanguage: '语言',
    QyAppLocalizationKeys.qyLanguageEnglish: '英文',
    QyAppLocalizationKeys.qyLanguageChinese: '中文',
    QyAppLocalizationKeys.qyNotifications: '通知',
    QyAppLocalizationKeys.qyPrivacy: '隐私',
    QyAppLocalizationKeys.qyPrivacySecurity: '隐私与安全',
    QyAppLocalizationKeys.qySecurity: '安全',
    QyAppLocalizationKeys.qyHelp: '帮助',
    QyAppLocalizationKeys.qyHelpSupport: '帮助与支持',
    QyAppLocalizationKeys.qyAbout: '关于',
    QyAppLocalizationKeys.qyAboutDescription: '了解 QY 应用的详细信息',
    QyAppLocalizationKeys.qyTerms: '服务条款',
    QyAppLocalizationKeys.qyPrivacyPolicy: '隐私政策',
    QyAppLocalizationKeys.qyDisplayLayoutSettings: '显示布局设置',
    QyAppLocalizationKeys.qyCompatibilitySettings: '兼容性设置',

    // Dashboard & Stats
    QyAppLocalizationKeys.qyDashboard: '仪表盘',
    QyAppLocalizationKeys.qyInbox: '收件箱',
    QyAppLocalizationKeys.qyMessages: '消息',
    QyAppLocalizationKeys.qyChat: '聊天',
    QyAppLocalizationKeys.qyContacts: '联系人',
    QyAppLocalizationKeys.qyFriends: '好友',
    QyAppLocalizationKeys.qyGroups: '群组',
    QyAppLocalizationKeys.qyFeed: '动态',
    QyAppLocalizationKeys.qyNews: '资讯',
    QyAppLocalizationKeys.qyEvents: '活动',
    QyAppLocalizationKeys.qyCalendar: '日历',
    QyAppLocalizationKeys.qyTasks: '任务',
    QyAppLocalizationKeys.qyProjects: '项目',
    QyAppLocalizationKeys.qyMyPrayers: '我的祈祷',
    QyAppLocalizationKeys.qyMyDonations: '我的捐赠',
    QyAppLocalizationKeys.qyMyFundraising: '我的募捐',
    QyAppLocalizationKeys.qyInviteFriends: '邀请好友',
    QyAppLocalizationKeys.qyShareApp: '分享应用',
    QyAppLocalizationKeys.qyHomeTopMenuPrayer: '祈祷',
    QyAppLocalizationKeys.qyFeature: '功能',
    QyAppLocalizationKeys.qyFeaturePreview: '功能预览',
    QyAppLocalizationKeys.qyFeatureComingSoon: '敬请期待',
    QyAppLocalizationKeys.qyDisaster: '灾害救援',
    QyAppLocalizationKeys.qyEducation: '教育发展',
    QyAppLocalizationKeys.qyEnvironment: '环境守护',
    QyAppLocalizationKeys.qyHumanity: '人道主义',
    QyAppLocalizationKeys.qyMedical: '医疗援助',
    QyAppLocalizationKeys.qyOrphanage: '孤儿关怀',
    QyAppLocalizationKeys.qyDailyStudyReminder: '每日学习提醒',
    QyAppLocalizationKeys.qyPersonalizedRecommendations: '个性化推荐设置',
    QyAppLocalizationKeys.qySyncSettings: '同步设置',
    QyAppLocalizationKeys.qyNotLoggedIn: '未登录',
    QyAppLocalizationKeys.qyUser: '用户',
    QyAppLocalizationKeys.qyClearCacheTitle: '清除缓存',
    QyAppLocalizationKeys.qyClearCacheMessage: '确定要清除缓存吗？这将删除 {size} MB 的数据。',
    QyAppLocalizationKeys.qyCacheCleared: '缓存已清除',
    QyAppLocalizationKeys.qyHelpCenterInProgress: '帮助中心功能开发中...',

    // Learning statistics
    QyAppLocalizationKeys.qyCommunity: '社区',
    QyAppLocalizationKeys.qyGlobalSearch: '全局搜索',
    QyAppLocalizationKeys.qyAiSearch: 'AI 搜索',
    QyAppLocalizationKeys.qyPlaceholderSearchContent: '搜索内容…',
    QyAppLocalizationKeys.qyLearningProgress: '学习进度',
    QyAppLocalizationKeys.qyStudyDuration: '学习时长',
    QyAppLocalizationKeys.qyAccuracyRate: '准确率',
    QyAppLocalizationKeys.qyReviewCount: '复习次数',
    QyAppLocalizationKeys.qyWordLearning: '词汇学习',
    QyAppLocalizationKeys.qyInterest: '兴趣',
    QyAppLocalizationKeys.qyIAm: '我是',

    QyAppLocalizationKeys.qyCertificateCenter: '证书中心',
    QyAppLocalizationKeys.qyCertificateCenterSubtitle: '查看你的学习成就',
    QyAppLocalizationKeys.qyCertificateEarned: '已获得',
    QyAppLocalizationKeys.qyCertificateInProgress: '进行中',
    QyAppLocalizationKeys.qyCertificateTotalPoints: '总积分',
    QyAppLocalizationKeys.qyCertificateLocked: '未解锁',
    QyAppLocalizationKeys.qyCertificateUnlocked: '已解锁',
    QyAppLocalizationKeys.qyCertificateEarnedDate: '获得时间',
    QyAppLocalizationKeys.qyCertificateNumber: '证书编号',
    QyAppLocalizationKeys.qyCertificateIssueDate: '颁发日期',
    QyAppLocalizationKeys.qyCertificateKeepWorking: '继续努力，早日解锁这个证书！',
    QyAppLocalizationKeys.qyCertificateShareToWechat: '分享到微信',
    QyAppLocalizationKeys.qyCertificateShareToMoments: '分享到朋友圈',
    QyAppLocalizationKeys.qyCertificateSaveImage: '保存图片',
    QyAppLocalizationKeys.qyCertificateCopyLink: '复制链接',
    QyAppLocalizationKeys.qyCertificateDownloadInProgress: '证书下载功能开发中...',
    QyAppLocalizationKeys.qyCertificateShareInProgress: '证书分享功能开发中...',
    QyAppLocalizationKeys.qyCertificateDescription: '此证书由扇贝单词英语学习平台颁发\n\n兹证明学员已完成相关学习要求，\n达到相应学习标准，特发此证以资鼓励。',
    QyAppLocalizationKeys.qyCertificateLevelBeginner: '初级',
    QyAppLocalizationKeys.qyCertificateLevelIntermediate: '中级',
    QyAppLocalizationKeys.qyCertificateLevelAdvanced: '高级',
    QyAppLocalizationKeys.qyCertificateLevelExpert: '专家',
    QyAppLocalizationKeys.qyCertificateBadgeNewbie: '新手',
    QyAppLocalizationKeys.qyCertificateBadgeDiligent: '勤奋',
    QyAppLocalizationKeys.qyCertificateBadgePersistent: '坚持',
    QyAppLocalizationKeys.qyCertificateBadgePerfectAttendance: '全勤',
    QyAppLocalizationKeys.qyCertificateBadgeExpert: '专家',
    QyAppLocalizationKeys.qyCertificateBadgeExcellent: '卓越',

    QyAppLocalizationKeys.qyCertBasicEnglishTitle: '英语学习初级证书',
    QyAppLocalizationKeys.qyCertBasicEnglishDesc: '完成基础英语学习课程',
    QyAppLocalizationKeys.qyCertWordMasterTitle: '单词掌握达人',
    QyAppLocalizationKeys.qyCertWordMasterDesc: '累计掌握1000个单词',
    QyAppLocalizationKeys.qyCertListeningMasterTitle: '听力挑战大师',
    QyAppLocalizationKeys.qyCertListeningMasterDesc: '连续30天完成听力练习',
    QyAppLocalizationKeys.qyCertPerfectAttendanceTitle: '学习全勤奖',
    QyAppLocalizationKeys.qyCertPerfectAttendanceDesc: '连续学习90天不间断',
    QyAppLocalizationKeys.qyCertVocabularyExpertTitle: '词汇专家认证',
    QyAppLocalizationKeys.qyCertVocabularyExpertDesc: '掌握5000个高阶词汇',
    QyAppLocalizationKeys.qyCertIeltsHighScoreTitle: '雅思高分证书',
    QyAppLocalizationKeys.qyCertIeltsHighScoreDesc: '雅思考试7.5分以上',

    QyAppLocalizationKeys.qyAuthWelcomeMessage: '欢迎使用',
    QyAppLocalizationKeys.qyAuthAppSlogan: '扇贝单词 记住单词，记录改变',
    QyAppLocalizationKeys.qyAuthPhoneLogin: '手机号登录',
    QyAppLocalizationKeys.qyAuthWechatLogin: '微信登录',
    QyAppLocalizationKeys.qyAuthQQLogin: 'QQ登录',
    QyAppLocalizationKeys.qyAuthGoogleLogin: 'Google登录',
    QyAppLocalizationKeys.qyAuthGithubLogin: 'Github登录',
    QyAppLocalizationKeys.qyAuthMoreOptions: '更多登录方式',
    QyAppLocalizationKeys.qyAuthCollapseOptions: '收起',
    QyAppLocalizationKeys.qyAuthPhoneNumber: '手机号',
    QyAppLocalizationKeys.qyAuthPhonePlaceholder: '请输入手机号',
    QyAppLocalizationKeys.qyAuthVerificationCode: '验证码',
    QyAppLocalizationKeys.qyAuthCodePlaceholder: '请输入验证码',
    QyAppLocalizationKeys.qyAuthGetCode: '获取验证码',
    QyAppLocalizationKeys.qyAuthResendCode: '重新发送',
    QyAppLocalizationKeys.qyAuthCodeSent: '验证码已发送',
    QyAppLocalizationKeys.qyAuthCodeSendFailed: '发送验证码失败',
    QyAppLocalizationKeys.qyAuthLoginButton: '登录',
    QyAppLocalizationKeys.qyAuthRegisterButton: '注册',
    QyAppLocalizationKeys.qyAuthLoginSuccess: '登录成功',
    QyAppLocalizationKeys.qyAuthLoginFailed: '登录失败',
    QyAppLocalizationKeys.qyAuthRegisterSuccess: '注册成功',
    QyAppLocalizationKeys.qyAuthRegisterFailed: '注册失败',
    QyAppLocalizationKeys.qyAuthSkipLogin: '跳过登录',
    QyAppLocalizationKeys.qyAuthGuestMode: '访客模式',
    QyAppLocalizationKeys.qyAuthAgreement: '用户协议',
    QyAppLocalizationKeys.qyAuthAgreementPrefix: '登录即表示同意',
    QyAppLocalizationKeys.qyAuthTermsOfService: '服务条款',
    QyAppLocalizationKeys.qyAuthAnd: '和',
    QyAppLocalizationKeys.qyAuthPrivacyPolicy: '隐私政策',
    QyAppLocalizationKeys.qyAuthMustAgree: '请先同意用户协议',
    QyAppLocalizationKeys.qyAuthPhoneInvalid: '请输入有效的手机号',
    QyAppLocalizationKeys.qyAuthCodeInvalid: '请输入验证码',
    QyAppLocalizationKeys.qyAuthCodeLength: '请输入6位数字验证码',
    QyAppLocalizationKeys.qyAuthSeconds: '秒',
    QyAppLocalizationKeys.qyAuthWelcomeTitle: '欢迎',
    QyAppLocalizationKeys.qyAuthSelectCountry: '选择国家/地区',
    QyAppLocalizationKeys.qyAuthCountryCode: '国家代码',
    QyAppLocalizationKeys.qyAuthVerifyPhone: '验证手机号',
    QyAppLocalizationKeys.qyAuthVerifyPhoneHint: '请输入验证码以验证您的手机号',
    QyAppLocalizationKeys.qyAuthForgotPassword: '忘记密码',
    QyAppLocalizationKeys.qyAuthResetPassword: '重置密码',
    QyAppLocalizationKeys.qyAuthNewPassword: '新密码',
    QyAppLocalizationKeys.qyAuthConfirmNewPassword: '确认新密码',
    QyAppLocalizationKeys.qyAuthPasswordMismatch: '两次输入的密码不一致',
    QyAppLocalizationKeys.qyAuthPasswordTooShort: '密码长度至少6位',
    QyAppLocalizationKeys.qyAuthCreatePin: '创建PIN码',
    QyAppLocalizationKeys.qyAuthEnterPin: '输入PIN码',
    QyAppLocalizationKeys.qyAuthConfirmPin: '确认PIN码',
    QyAppLocalizationKeys.qyAuthPinMismatch: 'PIN码不匹配',
    QyAppLocalizationKeys.qyAuthCongratulations: '恭喜',
    QyAppLocalizationKeys.qyAuthAccountCreated: '账号创建成功',
    QyAppLocalizationKeys.qyAuthAccountCreatedDesc: '您的账号已成功创建，现在可以开始使用了',
    QyAppLocalizationKeys.qyAuthGetStarted: '开始使用',
    QyAppLocalizationKeys.qyAuthLoginModeSwitch: '切换到登录',
    QyAppLocalizationKeys.qyAuthRegisterModeSwitch: '切换到注册',
    QyAppLocalizationKeys.qyAuthWechatLoginFailed: '微信登录失败',
    QyAppLocalizationKeys.qyAuthThirdPartyLogin: '第三方登录',

    QyAppLocalizationKeys.qySettingsPlayerCompatibility: '播放器兼容性',
    QyAppLocalizationKeys.qySettingsFeedback: '意见反馈',
    QyAppLocalizationKeys.qySettingsFeedbackInProgress: '意见反馈功能开发中...',
    QyAppLocalizationKeys.qySettingsAboutInProgress: '关于页面功能开发中...',
    QyAppLocalizationKeys.qySettingsTermsInProgress: '用户协议功能开发中...',
    QyAppLocalizationKeys.qySettingsPrivacyInProgress: '隐私政策功能开发中...',

    QyAppLocalizationKeys.qySettingsDailyReminder: '每日提醒',
    QyAppLocalizationKeys.qySettingsEnableDailyReminder: '开启每日提醒',
    QyAppLocalizationKeys.qySettingsEnableDailyReminderSubtitle: '每天固定时间提醒学习',
    QyAppLocalizationKeys.qySettingsReminderTime: '提醒时间',
    QyAppLocalizationKeys.qySettingsVibrationReminder: '震动提醒',
    QyAppLocalizationKeys.qySettingsVibrationReminderSubtitle: '学习提醒时震动',
    QyAppLocalizationKeys.qySettingsSoundReminder: '声音提醒',
    QyAppLocalizationKeys.qySettingsSoundReminderSubtitle: '学习提醒时播放声音',
    QyAppLocalizationKeys.qySettingsReminderDate: '提醒日期',
    QyAppLocalizationKeys.qySettingsRemindEveryday: '每天提醒',
    QyAppLocalizationKeys.qySettingsWeekdayMonday: '周一',
    QyAppLocalizationKeys.qySettingsWeekdayTuesday: '周二',
    QyAppLocalizationKeys.qySettingsWeekdayWednesday: '周三',
    QyAppLocalizationKeys.qySettingsWeekdayThursday: '周四',
    QyAppLocalizationKeys.qySettingsWeekdayFriday: '周五',
    QyAppLocalizationKeys.qySettingsWeekdaySaturday: '周六',
    QyAppLocalizationKeys.qySettingsWeekdaySunday: '周日',

    QyAppLocalizationKeys.qySettingsFontSettings: '字体设置',
    QyAppLocalizationKeys.qySettingsFont: '字体',
    QyAppLocalizationKeys.qySettingsAppearanceSettings: '外观设置',
    QyAppLocalizationKeys.qySettingsInterfaceLayout: '界面布局',
    QyAppLocalizationKeys.qySettingsStandardMode: '标准模式',
    QyAppLocalizationKeys.qySettingsAccessibility: '辅助功能',
    QyAppLocalizationKeys.qySettingsHighContrast: '高对比度',
    QyAppLocalizationKeys.qySettingsHighContrastSubtitle: '提高文字和背景的对比度',
    QyAppLocalizationKeys.qySettingsLargeFontMode: '大字体模式',
    QyAppLocalizationKeys.qySettingsLargeFontModeSubtitle: '适合视力不佳的用户',
    QyAppLocalizationKeys.qySettingsSelectFont: '选择字体',
    QyAppLocalizationKeys.qySettingsLayoutInProgress: '界面布局设置功能开发中...',

    QyAppLocalizationKeys.qySettingsModify: '修改',
    QyAppLocalizationKeys.qySettingsRebind: '换绑',
    QyAppLocalizationKeys.qySettingsBind: '绑定',
    QyAppLocalizationKeys.qySettingsAccountBinding: '账号绑定',
    QyAppLocalizationKeys.qySettingsPhone: '手机',
    QyAppLocalizationKeys.qySettingsNotBound: '尚未绑定',
    QyAppLocalizationKeys.qySettingsWechat: '微信',
    QyAppLocalizationKeys.qySettingsWeibo: '新浪微博',
    QyAppLocalizationKeys.qySettingsQQ: 'QQ',
    QyAppLocalizationKeys.qySettingsAccountDeletion: '账号注销',
    QyAppLocalizationKeys.qySettingsAccountDeletionSubtitle: '删除所有数据，永久注销',
    QyAppLocalizationKeys.qySettingsDeleteAccount: '注销',
    QyAppLocalizationKeys.qySettingsChangeUsername: '修改用户名',
    QyAppLocalizationKeys.qySettingsEnterNewUsername: '请输入新用户名',
    QyAppLocalizationKeys.qySettingsUsernameUpdated: '用户名已更新',
    QyAppLocalizationKeys.qySettingsChangePasswordTitle: '修改密码',
    QyAppLocalizationKeys.qySettingsEnterNewPassword: '请输入新密码',
    QyAppLocalizationKeys.qySettingsConfirmNewPassword: '请确认新密码',
    QyAppLocalizationKeys.qySettingsPasswordUpdated: '密码已更新',
    QyAppLocalizationKeys.qySettingsPhoneBinding: '手机号绑定',
    QyAppLocalizationKeys.qySettingsPhoneBindingInProgress: '手机号绑定功能开发中...',
    QyAppLocalizationKeys.qySettingsWechatBinding: '微信绑定',
    QyAppLocalizationKeys.qySettingsWechatBindingInProgress: '微信绑定功能开发中...',
    QyAppLocalizationKeys.qySettingsWeiboBinding: '微博绑定',
    QyAppLocalizationKeys.qySettingsWeiboBindingInProgress: '微博绑定功能开发中...',
    QyAppLocalizationKeys.qySettingsQQBinding: 'QQ绑定',
    QyAppLocalizationKeys.qySettingsQQBindingInProgress: 'QQ绑定功能开发中...',
    QyAppLocalizationKeys.qySettingsDeletionWarning: '警告：此操作不可恢复！',
    QyAppLocalizationKeys.qySettingsAfterDeletion: '注销账号后：',
    QyAppLocalizationKeys.qySettingsDeletionDataLoss: '所有学习数据将被永久删除',
    QyAppLocalizationKeys.qySettingsDeletionCourseLoss: '购买的课程和服务将无法使用',
    QyAppLocalizationKeys.qySettingsDeletionAccountClear: '账户信息将被彻底清除',
    QyAppLocalizationKeys.qySettingsConfirmDeletion: '确定要注销账号吗？',
    QyAppLocalizationKeys.qySettingsFinalConfirmation: '最终确认',
    QyAppLocalizationKeys.qySettingsFinalConfirmationMessage: '请再次确认：您真的要永久注销账号吗？',
    QyAppLocalizationKeys.qySettingsLetMeThink: '我再想想',
    QyAppLocalizationKeys.qySettingsAccountDeletionInProgress: '账号注销功能开发中...',

    QyAppLocalizationKeys.qySettingsSmartRecommendation: '智能推荐',
    QyAppLocalizationKeys.qySettingsAutoRecommend: '自动推荐',
    QyAppLocalizationKeys.qySettingsAutoRecommendSubtitle: '基于学习历史智能推荐单词',
    QyAppLocalizationKeys.qySettingsDifficulty: '难度',
    QyAppLocalizationKeys.qySettingsDifficultySettings: '难度设置',
    QyAppLocalizationKeys.qySettingsDifficultyBeginner: '初级',
    QyAppLocalizationKeys.qySettingsDifficultyIntermediate: '中级',
    QyAppLocalizationKeys.qySettingsDifficultyAdvanced: '高级',
    QyAppLocalizationKeys.qySettingsDifficultyExpert: '专家',
    QyAppLocalizationKeys.qySettingsInterestTags: '兴趣标签',
    QyAppLocalizationKeys.qySettingsInterestTagsSelected: '已选择 {count} 个兴趣标签',
    QyAppLocalizationKeys.qySettingsRecommendationFrequency: '推荐频率',
    QyAppLocalizationKeys.qySettingsRecommendationStrength: '推荐强度',
    QyAppLocalizationKeys.qySettingsSelectDifficulty: '选择难度',
    QyAppLocalizationKeys.qySettingsDifficultyBeginnerDesc: '适合初学者，基础词汇',
    QyAppLocalizationKeys.qySettingsDifficultyIntermediateDesc: '适合有一定基础的学习者',
    QyAppLocalizationKeys.qySettingsDifficultyAdvancedDesc: '适合高级学习者，专业词汇',
    QyAppLocalizationKeys.qySettingsDifficultyExpertDesc: '适合专家级学习者，学术词汇',
  };

  /// Get locales for runCommonApp
  static List<Map<String, String>> get locales => [values];
}
