// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

import 'localization_keys_app_qy.dart';

/// Chinese localization for QY App
class ZhAppQy {
  static const Map<String, String> values = {
    // App Identity
    QyAppLocalizationKeys.qyAppName: 'QY 应用',
    QyAppLocalizationKeys.qyAppDescription: '综合学习与成长的平台',
    QyAppLocalizationKeys.qyAppSlogan: '学习、构建、成长',
    QyAppLocalizationKeys.qyAppVersion: '版本 1.0.0',
    QyAppLocalizationKeys.qyAppSettings: '应用设置',
    QyAppLocalizationKeys.qySloganWords: '赋能你的学习旅程',
    QyAppLocalizationKeys.qySloganEyes: '让目光专注于知识',
    QyAppLocalizationKeys.qyLetsStart: '开始体验',
    QyAppLocalizationKeys.qyDoNotHaveAccount: '还没有账号？',
    QyAppLocalizationKeys.qySignupForFree: '立即免费注册',
    QyAppLocalizationKeys.qyWelcome: '欢迎回来',
    QyAppLocalizationKeys.qyGreeting: '你好，学习者！',
    QyAppLocalizationKeys.qyWelcomeBack: '欢迎回来',
    QyAppLocalizationKeys.qyGuestMode: '访客模式',

    // Common Actions
    QyAppLocalizationKeys.qyHome: '首页',
    QyAppLocalizationKeys.qyMenu: '菜单',
    QyAppLocalizationKeys.qySocial: '社交',
    QyAppLocalizationKeys.qySupport: '支持',
    QyAppLocalizationKeys.qyNext: '下一步',
    QyAppLocalizationKeys.qyPrevious: '上一步',
    QyAppLocalizationKeys.qySkip: '跳过',
    QyAppLocalizationKeys.qyCancel: '取消',
    QyAppLocalizationKeys.qyConfirm: '确认',
    QyAppLocalizationKeys.qySave: '保存',
    QyAppLocalizationKeys.qyDelete: '删除',
    QyAppLocalizationKeys.qyEdit: '编辑',
    QyAppLocalizationKeys.qyBack: '返回',
    QyAppLocalizationKeys.qyClose: '关闭',
    QyAppLocalizationKeys.qyOk: '确定',
    QyAppLocalizationKeys.qyYes: '是',
    QyAppLocalizationKeys.qyNo: '否',
    QyAppLocalizationKeys.qyContinue: '继续',
    QyAppLocalizationKeys.qySubmit: '提交',
    QyAppLocalizationKeys.qyRetry: '重试',
    QyAppLocalizationKeys.qyRefresh: '刷新',
    QyAppLocalizationKeys.qySearch: '搜索',
    QyAppLocalizationKeys.qySearchPlaceholder: '搜索…',
    QyAppLocalizationKeys.qyEnterSearchText: '请输入搜索内容',
    QyAppLocalizationKeys.qyFilter: '筛选',
    QyAppLocalizationKeys.qySort: '排序',
    QyAppLocalizationKeys.qyClear: '清除',
    QyAppLocalizationKeys.qyReset: '重置',
    QyAppLocalizationKeys.qyTopUp: '充值',

    // Status Messages
    QyAppLocalizationKeys.qySuccess: '成功',
    QyAppLocalizationKeys.qyError: '错误',
    QyAppLocalizationKeys.qyWarning: '警告',
    QyAppLocalizationKeys.qyInfo: '提示',
    QyAppLocalizationKeys.qyLoading: '加载中...',
    QyAppLocalizationKeys.qyCompleted: '已完成',
    QyAppLocalizationKeys.qyPending: '待处理',
    QyAppLocalizationKeys.qyFailed: '失败',

    // Authentication
    QyAppLocalizationKeys.qySignIn: '登录',
    QyAppLocalizationKeys.qySignUp: '注册',
    QyAppLocalizationKeys.qySignOut: '退出',
    QyAppLocalizationKeys.qyLogout: '退出登录',
    QyAppLocalizationKeys.qyLogoutConfirm: '确定要退出当前账号吗？',
    QyAppLocalizationKeys.qyLogoutSuccess: '已成功退出登录',
    QyAppLocalizationKeys.qyLogoutFailed: '退出失败，请重试',
    QyAppLocalizationKeys.qyYesLogout: '确认退出',
    QyAppLocalizationKeys.qyLogin: '登录',
    QyAppLocalizationKeys.qyRegister: '注册',
    QyAppLocalizationKeys.qyForgotPassword: '忘记密码',
    QyAppLocalizationKeys.qyResetPassword: '重置密码',
    QyAppLocalizationKeys.qyChangePassword: '修改密码',
    QyAppLocalizationKeys.qyEmail: '邮箱',
    QyAppLocalizationKeys.qyPassword: '密码',
    QyAppLocalizationKeys.qyConfirmPassword: '确认密码',
    QyAppLocalizationKeys.qyUsername: '用户名',
    QyAppLocalizationKeys.qyRememberMe: '记住我',
    QyAppLocalizationKeys.qyCreateAccount: '创建账号',
    QyAppLocalizationKeys.qyHaveAccount: '已有账号？',
    QyAppLocalizationKeys.qyNoAccount: '还没有账号？',

    // Profile & Settings
    QyAppLocalizationKeys.qyProfile: '个人中心',
    QyAppLocalizationKeys.qyMyProfile: '我的资料',
    QyAppLocalizationKeys.qyEditProfile: '编辑资料',
    QyAppLocalizationKeys.qyPersonalInfo: '个人信息',
    QyAppLocalizationKeys.qyFirstName: '名字',
    QyAppLocalizationKeys.qyLastName: '姓氏',
    QyAppLocalizationKeys.qyFullName: '姓名',
    QyAppLocalizationKeys.qyPhoneNumber: '电话号码',
    QyAppLocalizationKeys.qyAddress: '地址',
    QyAppLocalizationKeys.qyBirthDate: '出生日期',
    QyAppLocalizationKeys.qyGender: '性别',
    QyAppLocalizationKeys.qyAvatar: '头像',
    QyAppLocalizationKeys.qyBio: '个性签名',
    QyAppLocalizationKeys.qySettings: '设置',
    QyAppLocalizationKeys.qyGeneralSettings: '通用设置',
    QyAppLocalizationKeys.qyAccountSettings: '账号设置',
    QyAppLocalizationKeys.qyPrivacySettings: '隐私设置',
    QyAppLocalizationKeys.qyNotificationSettings: '通知设置',
    QyAppLocalizationKeys.qyLanguageSettings: '语言设置',
    QyAppLocalizationKeys.qyThemeSettings: '主题设置',
    QyAppLocalizationKeys.qyBiometricAuth: '生物识别登录',
    QyAppLocalizationKeys.qyDarkMode: '深色模式',
    QyAppLocalizationKeys.qyLightMode: '浅色模式',
    QyAppLocalizationKeys.qySystemMode: '跟随系统',
    QyAppLocalizationKeys.qyLanguage: '语言',
    QyAppLocalizationKeys.qyLanguageEnglish: '英文',
    QyAppLocalizationKeys.qyLanguageChinese: '中文',
    QyAppLocalizationKeys.qyNotifications: '通知',
    QyAppLocalizationKeys.qyPrivacy: '隐私',
    QyAppLocalizationKeys.qyPrivacySecurity: '隐私与安全',
    QyAppLocalizationKeys.qySecurity: '安全',
    QyAppLocalizationKeys.qyHelp: '帮助',
    QyAppLocalizationKeys.qyHelpSupport: '帮助与支持',
    QyAppLocalizationKeys.qyAbout: '关于',
    QyAppLocalizationKeys.qyAboutDescription: '了解 QY 应用的详细信息',
    QyAppLocalizationKeys.qyTerms: '服务条款',
    QyAppLocalizationKeys.qyPrivacyPolicy: '隐私政策',
    QyAppLocalizationKeys.qyDisplayLayoutSettings: '显示布局设置',
    QyAppLocalizationKeys.qyCompatibilitySettings: '兼容性设置',

    // Dashboard & Stats
    QyAppLocalizationKeys.qyDashboard: '仪表盘',
    QyAppLocalizationKeys.qyInbox: '收件箱',
    QyAppLocalizationKeys.qyMessages: '消息',
    QyAppLocalizationKeys.qyChat: '聊天',
    QyAppLocalizationKeys.qyContacts: '联系人',
    QyAppLocalizationKeys.qyFriends: '好友',
    QyAppLocalizationKeys.qyGroups: '群组',
    QyAppLocalizationKeys.qyFeed: '动态',
    QyAppLocalizationKeys.qyNews: '资讯',
    QyAppLocalizationKeys.qyEvents: '活动',
    QyAppLocalizationKeys.qyCalendar: '日历',
    QyAppLocalizationKeys.qyTasks: '任务',
    QyAppLocalizationKeys.qyProjects: '项目',
    QyAppLocalizationKeys.qyMyPrayers: '我的祈祷',
    QyAppLocalizationKeys.qyMyDonations: '我的捐赠',
    QyAppLocalizationKeys.qyMyFundraising: '我的募捐',
    QyAppLocalizationKeys.qyInviteFriends: '邀请好友',
    QyAppLocalizationKeys.qyShareApp: '分享应用',
    QyAppLocalizationKeys.qyHomeTopMenuPrayer: '祈祷',
    QyAppLocalizationKeys.qyFeature: '功能',
    QyAppLocalizationKeys.qyFeaturePreview: '功能预览',
    QyAppLocalizationKeys.qyFeatureComingSoon: '敬请期待',
    QyAppLocalizationKeys.qyDisaster: '灾害救援',
    QyAppLocalizationKeys.qyEducation: '教育发展',
    QyAppLocalizationKeys.qyEnvironment: '环境守护',
    QyAppLocalizationKeys.qyHumanity: '人道主义',
    QyAppLocalizationKeys.qyMedical: '医疗援助',
    QyAppLocalizationKeys.qyOrphanage: '孤儿关怀',
    QyAppLocalizationKeys.qyDailyStudyReminder: '每日学习提醒',
    QyAppLocalizationKeys.qyPersonalizedRecommendations: '个性化推荐设置',
    QyAppLocalizationKeys.qySyncSettings: '同步设置',
    QyAppLocalizationKeys.qyNotLoggedIn: '未登录',
    QyAppLocalizationKeys.qyUser: '用户',
    QyAppLocalizationKeys.qyClearCacheTitle: '清除缓存',
    QyAppLocalizationKeys.qyClearCacheMessage: '确定要清除缓存吗？这将删除 {size} MB 的数据。',
    QyAppLocalizationKeys.qyCacheCleared: '缓存已清除',
    QyAppLocalizationKeys.qyHelpCenterInProgress: '帮助中心功能开发中...',

    // Learning statistics
    QyAppLocalizationKeys.qyCommunity: '社区',
    QyAppLocalizationKeys.qyGlobalSearch: '全局搜索',
    QyAppLocalizationKeys.qyAiSearch: 'AI 搜索',
    QyAppLocalizationKeys.qyPlaceholderSearchContent: '搜索内容…',
    QyAppLocalizationKeys.qyLearningProgress: '学习进度',
    QyAppLocalizationKeys.qyStudyDuration: '学习时长',
    QyAppLocalizationKeys.qyAccuracyRate: '准确率',
    QyAppLocalizationKeys.qyReviewCount: '复习次数',
    QyAppLocalizationKeys.qyWordLearning: '词汇学习',
    QyAppLocalizationKeys.qyInterest: '兴趣',
    QyAppLocalizationKeys.qyIAm: '我是',
  };

  /// Get locales for runCommonApp
  static List<Map<String, String>> get locales => [values];
}
