# =============================================================================
# Command Content Generator for Special Software Environment Manager
# =============================================================================
# 
# Description:
# This module is responsible for generating batch command content for various AI tools (Claude, Droid, etc.)
# Includes environment variable setup, MCP synchronization, upgrade checks and other complete functionality
#
# Key Features:
# 1. Dynamic generation of batch script content
# 2. Support for multiple AI tool command generation
# 3. Integrated MCP server synchronization functionality
# 4. Support for environment variable setup and validation
# 5. Detailed user interaction and confirmation mechanisms
#
# Author: AI Assistant
# Created: 2025-01-24
# Version: 1.0
# =============================================================================

#region Import Dependencies
# Import common functions module
. (Join-Path (Split-Path $PSScriptRoot -Parent) "win_common\CommonFunc.ps1")
#endregion

#region Core Command Content Generation Functions

<#
.SYNOPSIS
    Generate complete batch command content

.DESCRIPTION
    Generate batch script content including environment variable setup, MCP synchronization, tool startup and other functionality based on configuration information

.PARAMETER ConfigName
    Configuration name (e.g. "Claude AI", "Factory AI Droid")

.PARAMETER CommandPrefix
    Command prefix (e.g. "claude", "droid")

.PARAMETER PsCommand
    PowerShell command (e.g. "claude", "droid")

.PARAMETER FileNumber
    File number (used to generate unique filename)

.PARAMETER EnvCommands
    Environment variable setup command array

.PARAMETER PsEnvVars
    PowerShell environment variable string

.PARAMETER McpSection
    MCP synchronization section content

.EXAMPLE
    $content = New-CommandContent -ConfigName "Claude AI" -CommandPrefix "claude" -PsCommand "claude" -FileNumber 1 -EnvCommands $envCmds -PsEnvVars $psVars -McpSection $mcp
#>
function New-CommandContent {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ConfigName,
        
        [Parameter(Mandatory=$true)]
        [string]$CommandPrefix,
        
        [Parameter(Mandatory=$true)]
        [string]$PsCommand,
        
        [Parameter(Mandatory=$true)]
        [int]$FileNumber,
        
        [Parameter(Mandatory=$true)]
        [array]$EnvCommands,
        
        [Parameter(Mandatory=$true)]
        [string]$PsEnvVars,
        
        [Parameter(Mandatory=$false)]
        [string]$McpSection = ""
    )
    
    # Generate file header information
    $header = @"
@echo off
REM $ConfigName Global File #$FileNumber
REM Generated on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
REM 
REM This file is automatically generated by Special Software Environment Manager
REM Contains environment variable setup, MCP synchronization and tool startup functionality
REM 
REM Configuration Information:
REM   - Tool Name: $ConfigName
REM   - Command Prefix: $CommandPrefix
REM   - PowerShell Command: $PsCommand
REM   - File Number: $FileNumber
REM   - Generation Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
REM
"@

    # Generate environment variable setup section
    $envSection = @"

REM =============================================================================
REM Environment Variable Setup Section
REM =============================================================================
REM Set environment variables required for tool execution
REM These variables will remain valid throughout the batch script execution
REM
$($EnvCommands -join "`n")
REM
REM Environment variable setup completed
REM =============================================================================
"@

    # Generate MCP synchronization section (if provided)
    $mcpSectionContent = ""
    if (-not [string]::IsNullOrWhiteSpace($McpSection)) {
        $mcpSectionContent = @"

REM =============================================================================
REM MCP Server Synchronization Section
REM =============================================================================
REM Synchronize MCP server configurations to ensure tools can access the latest server settings
REM This section generates appropriate synchronization logic based on different tool types
REM
$McpSection
REM
REM MCP synchronization completed
REM =============================================================================
"@
    }

    # Generate tool startup section
    $launchSection = @"

REM =============================================================================
REM Tool Startup Section
REM =============================================================================
REM Launch target tool using configured environment variables
REM PowerShell command will inherit all set environment variables
REM
echo.
echo ============================================================
echo Starting $ConfigName
echo ============================================================
echo.
echo Executing command: $PsCommand
echo.
echo Complete PowerShell command: powershell -NoProfile -ExecutionPolicy Bypass -Command "$PsEnvVars; $PsCommand"
echo.
echo Press any key to continue execution...
pause >nul

REM Execute PowerShell command, passing all environment variables
powershell -NoProfile -ExecutionPolicy Bypass -Command "$PsEnvVars; $PsCommand"

REM Check execution result
if %ERRORLEVEL% EQU 0 (
    echo.
    echo [SUCCESS] $ConfigName started successfully
) else (
    echo.
    echo [ERROR] $ConfigName startup failed, exit code: %ERRORLEVEL%
)

echo.
echo ============================================================
echo Execution completed
echo ============================================================
pause
"@

    # Combine all sections
    $fullContent = @"
$header
$envSection
$mcpSectionContent
$launchSection
"@

    return $fullContent
}

<#
.SYNOPSIS
    Generate MCP synchronization section for Claude AI

.DESCRIPTION
    Generate batch content for Claude AI including upgrade checks and MCP synchronization

.PARAMETER None

.EXAMPLE
    $mcpContent = New-ClaudeMcpSection
#>
function New-ClaudeMcpSection {
    return @"

REM Prompt for upgrade and sync MCP configuration
echo.
echo ============================================================
echo Claude Code - Pre-Launch Tasks
echo ============================================================
echo.
echo Available tasks:
echo   [1] Upgrade Claude Code to latest version (runs in separate window)
echo   [2] Sync MCP server configurations (runs now)
echo.

REM Ask user if they want to upgrade
set /p UPGRADE_CHOICE="Do you want to upgrade Claude Code? (y/N): "
if /i "%UPGRADE_CHOICE%"=="y" (
    echo.
    echo [INFO] Launching AI tools upgrade in separate window...
    start "AI Tools Upgrade" "D:\programing\core_node_a\scripts\pytools\claude_tools\upgrade_claude_code.bat" all
    echo [SUCCESS] Upgrade window opened
) else (
    echo [INFO] Skipping upgrade
)

echo.
echo ============================================================
echo Syncing MCP Server Configurations...
echo ============================================================
echo.

REM Run MCP sync for Claude
python -u "D:\programing\core_node_a\scripts\pytools\claude_tools\sync_mcp_servers.py" --target claude

set MCP_EXIT_CODE=%ERRORLEVEL%

if %MCP_EXIT_CODE% EQU 0 (
    echo [SUCCESS] MCP configuration sync completed
) else (
    echo [WARNING] MCP sync exited with code: %MCP_EXIT_CODE%
)

echo.
echo ============================================================
echo Press Enter to start Claude Code...
echo ============================================================
set /p CONTINUE="Press Enter to continue..."
"@
}

<#
.SYNOPSIS
    Generate MCP synchronization section for Factory AI Droid

.DESCRIPTION
    Generate batch content for Factory AI Droid MCP synchronization

.PARAMETER None

.EXAMPLE
    $mcpContent = New-DroidMcpSection
#>
function New-DroidMcpSection {
    return @"

echo.
echo ============================================================
echo Factory AI Droid - Pre-Launch Tasks
echo ============================================================
echo.
echo Syncing MCP Server Configurations...
echo.

REM Run MCP sync for Droid
python -u "D:\programing\core_node_a\scripts\pytools\claude_tools\sync_mcp_servers.py" --target droid

set MCP_EXIT_CODE=%ERRORLEVEL%

if %MCP_EXIT_CODE% EQU 0 (
    echo [SUCCESS] MCP configuration sync completed
) else (
    echo [WARNING] MCP sync exited with code: %MCP_EXIT_CODE%
)

echo.
echo ============================================================
echo Press Enter to start Factory AI Droid...
echo ============================================================
set /p CONTINUE="Press Enter to continue..."
"@
}

<#
.SYNOPSIS
    Generate corresponding MCP synchronization section based on tool type

.DESCRIPTION
    Generate corresponding MCP synchronization and pre-launch task content based on different AI tool types

.PARAMETER ToolType
    Tool type ("claude" or "droid")

.EXAMPLE
    $mcpContent = Get-McpSectionByToolType -ToolType "claude"
#>
function Get-McpSectionByToolType {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ToolType
    )
    
    switch ($ToolType.ToLower()) {
        "claude" {
            return New-ClaudeMcpSection
        }
        "droid" {
            return New-DroidMcpSection
        }
        default {
            Write-ColorMessage -Message "Unknown tool type: $ToolType" -Type "Warning"
            return ""
        }
    }
}

<#
.SYNOPSIS
    Generate environment variable setup commands

.DESCRIPTION
    Generate corresponding batch setup commands based on environment variable configuration

.PARAMETER Variables
    Environment variable configuration array

.PARAMETER UserInputs
    User input environment variable values

.EXAMPLE
    $envCommands = New-EnvironmentCommands -Variables $config.Variables -UserInputs $userInputs
#>
function New-EnvironmentCommands {
    param(
        [Parameter(Mandatory=$true)]
        [array]$Variables,
        
        [Parameter(Mandatory=$true)]
        [hashtable]$UserInputs
    )
    
    $envCommands = @()
    $psEnvVars = @()
    
    foreach ($var in $Variables) {
        $userInput = $UserInputs[$var.Name]
        
        if (-not [string]::IsNullOrWhiteSpace($userInput)) {
            # Add batch commands
            $envCommands += "echo Setting $($var.Name)=$userInput"
            $envCommands += "set $($var.Name)=$userInput"
            
            # Add PowerShell environment variables
            $psEnvVars += "`$env:$($var.Name)='$userInput'"
        } else {
            $envCommands += "echo Skipping $($var.Name) (not set)"
            $envCommands += "REM set $($var.Name)=  # Not set"
        }
    }
    
    return @{
        EnvCommands = $envCommands
        PsEnvVars = $psEnvVars -join "; "
    }
}

<#
.SYNOPSIS
    Preview generated command content

.DESCRIPTION
    Display command content preview before generating actual file

.PARAMETER Content
    Content to preview

.PARAMETER FilePath
    Target file path

.EXAMPLE
    Show-CommandPreview -Content $batchContent -FilePath $targetPath
#>
function Show-CommandPreview {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Content,
        
        [Parameter(Mandatory=$true)]
        [string]$FilePath
    )
    
    Write-ColorMessage -Message "`nPreview of generated batch file:" -Type "Info"
    Write-ColorMessage -Message "File path: $FilePath" -Type "Info"
    Write-ColorMessage -Message ("=" * 50) -Type "Info"
    Write-Host $Content -ForegroundColor Cyan
    Write-ColorMessage -Message ("=" * 50) -Type "Info"
}

<#
.SYNOPSIS
    Confirm command generation

.DESCRIPTION
    Ask user whether to confirm command file generation

.PARAMETER None

.EXAMPLE
    $confirmed = Confirm-CommandGeneration
#>
function Confirm-CommandGeneration {
    Write-ColorMessage -Message "Press Enter to generate file, any other key to cancel" -Type "Info"
    $confirm = Read-Host "Confirm"
    
    if ($confirm -ne '') {
        Write-ColorMessage -Message "Command generation cancelled." -Type "Warning"
        return $false
    }
    
    return $true
}

#endregion

#region Advanced Command Generation Functions

<#
.SYNOPSIS
    Generate complete command content (advanced interface)

.DESCRIPTION
    This is the main interface for generating command content, integrating all necessary functionality

.PARAMETER Config
    Configuration object

.PARAMETER CommandPrefix
    Command prefix

.PARAMETER PsCommand
    PowerShell command

.PARAMETER FileNumber
    File number

.PARAMETER UserInputs
    User input environment variable values

.PARAMETER ShowPreview
    Whether to show preview (default: true)

.PARAMETER RequireConfirmation
    Whether to require user confirmation (default: true)

.EXAMPLE
    $result = New-CompleteCommandContent -Config $config -CommandPrefix "claude" -PsCommand "claude" -FileNumber 1 -UserInputs $inputs
#>
function New-CompleteCommandContent {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config,
        
        [Parameter(Mandatory=$true)]
        [string]$CommandPrefix,
        
        [Parameter(Mandatory=$true)]
        [string]$PsCommand,
        
        [Parameter(Mandatory=$true)]
        [int]$FileNumber,
        
        [Parameter(Mandatory=$true)]
        [hashtable]$UserInputs,
        
        [Parameter(Mandatory=$false)]
        [bool]$ShowPreview = $true,
        
        [Parameter(Mandatory=$false)]
        [bool]$RequireConfirmation = $true
    )
    
    try {
        # 1. Generate environment variable commands
        $envResult = New-EnvironmentCommands -Variables $Config.Variables -UserInputs $UserInputs
        
        # 2. Generate MCP synchronization section
        $mcpSection = Get-McpSectionByToolType -ToolType $PsCommand
        
        # 3. Generate complete command content
        $commandContent = New-CommandContent -ConfigName $Config.Title -CommandPrefix $CommandPrefix -PsCommand $PsCommand -FileNumber $FileNumber -EnvCommands $envResult.EnvCommands -PsEnvVars $envResult.PsEnvVars -McpSection $mcpSection
        
        # 4. Show preview (if needed)
        if ($ShowPreview) {
            $targetPath = "D:\programing\core_node_a\.winenvs\${CommandPrefix}${FileNumber}.bat"
            Show-CommandPreview -Content $commandContent -FilePath $targetPath
        }
        
        # 5. User confirmation (if needed)
        if ($RequireConfirmation) {
            $confirmed = Confirm-CommandGeneration
            if (-not $confirmed) {
                return @{
                    Success = $false
                    Message = "User cancelled command generation"
                    Content = $null
                }
            }
        }
        
        return @{
            Success = $true
            Message = "Command content generated successfully"
            Content = $commandContent
            EnvCommands = $envResult.EnvCommands
            PsEnvVars = $envResult.PsEnvVars
            McpSection = $mcpSection
        }
        
    } catch {
        return @{
            Success = $false
            Message = "Error occurred while generating command content: $($_.Exception.Message)"
            Content = $null
        }
    }
}

#endregion

#region Export Functions
# Note: Export-ModuleMember can only be used inside a module
# These functions are available when the script is dot-sourced
# Available functions:
# - New-CommandContent
# - New-ClaudeMcpSection
# - New-DroidMcpSection
# - Get-McpSectionByToolType
# - New-EnvironmentCommands
# - Show-CommandPreview
# - Confirm-CommandGeneration
# - New-CompleteCommandContent
#endregion

# =============================================================================
# Module initialization completed
# =============================================================================
Write-ColorMessage -Message "CommandContentGenerator module loaded" -Type "Success"
