# =============================================================================
# Command Content Generator for Special Software Environment Manager
# =============================================================================
# 
# Description:
# This module is responsible for generating batch command content for various AI tools (Claude, Droid, etc.)
# Includes environment variable setup, MCP synchronization, upgrade checks and other complete functionality
#
# Key Features:
# 1. Dynamic generation of batch script content
# 2. Support for multiple AI tool command generation
# 3. Integrated MCP server synchronization functionality
# 4. Support for environment variable setup and validation
# 5. Detailed user interaction and confirmation mechanisms
#
# Author: AI Assistant
# Created: 2025-01-24
# Version: 1.0
# =============================================================================

#region Import Dependencies
$scriptParentDir = Split-Path $PSScriptRoot -Parent
$winCommonDir = Join-Path $scriptParentDir "win_common"
$commonFuncPath = Join-Path $winCommonDir "CommonFunc.ps1"
$secretManagerPath = Join-Path $winCommonDir "SecretManager.ps1"

. $commonFuncPath

if (Test-Path $secretManagerPath) {
    . $secretManagerPath
    Write-ColorMessage -Message "SecretManager module loaded" -Type "Success"
} else {
    Write-ColorMessage -Message "SecretManager not found, will use direct values" -Type "Warning"
}
#endregion

#region Core Command Content Generation Functions

<#
.SYNOPSIS
    Generate complete batch command content

.DESCRIPTION
    Generate batch script content including environment variable setup, MCP synchronization, tool startup and other functionality based on configuration information

.PARAMETER ConfigName
    Configuration name (e.g. "Claude AI", "Factory AI Droid")

.PARAMETER CommandPrefix
    Command prefix (e.g. "claude", "droid")

.PARAMETER PsCommand
    PowerShell command (e.g. "claude", "droid")

.PARAMETER FileNumber
    File number (used to generate unique filename)

.PARAMETER EnvCommands
    Environment variable setup command array

.PARAMETER PsEnvVars
    PowerShell environment variable string

.PARAMETER McpSection
    MCP synchronization section content

.EXAMPLE
    $content = New-CommandContent -ConfigName "Claude AI" -CommandPrefix "claude" -PsCommand "claude" -FileNumber 1 -EnvCommands $envCmds -PsEnvVars $psVars -McpSection $mcp
#>
function New-CommandContent {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ConfigName,

        [Parameter(Mandatory=$true)]
        [string]$CommandPrefix,

        [Parameter(Mandatory=$true)]
        [string]$PsCommand,

        [Parameter(Mandatory=$true)]
        [int]$FileNumber,

        [Parameter(Mandatory=$true)]
        [array]$Variables,

        [Parameter(Mandatory=$false)]
        [string]$McpSection = "",

        [Parameter(Mandatory=$false)]
        [string]$FileName = ""
    )

    $scriptDir = Split-Path $PSScriptRoot -Parent
    $winCommonDir = Join-Path $scriptDir "win_common"
    $secretManagerPath = Join-Path $winCommonDir "SecretManager.ps1"

    $header = @"
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

<#
.SYNOPSIS
    $ConfigName Global File #$FileNumber

.DESCRIPTION
    This file is automatically generated by Special Software Environment Manager
    Contains environment variable setup, MCP synchronization and tool startup functionality

.NOTES
    - Tool Name: $ConfigName
    - Command Prefix: $CommandPrefix
    - PowerShell Command: $PsCommand
    - File Number: $FileNumber
    - File Name: $FileName
    - Generation Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#>

Set-StrictMode -Version Latest
`$ErrorActionPreference = "Stop"
"@
    
    $fileNameDisplay = ""
    if (-not [string]::IsNullOrWhiteSpace($FileName)) {
        $fileNameDisplay = @"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Running: $FileName" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
"@
    }

    $scriptParentDir = Split-Path $PSScriptRoot -Parent
    $winCommonDir = Join-Path $scriptParentDir "win_common"
    $absoluteSecretManagerPath = Join-Path $winCommonDir "SecretManager.ps1"

    $loadSecretManager = @"

#region Load SecretManager
`$secretManagerPath = "$absoluteSecretManagerPath"

if (Test-Path `$secretManagerPath) {
    . `$secretManagerPath
    Write-Host "[INFO] SecretManager loaded successfully" -ForegroundColor Green
} else {
    Write-Host "[WARNING] SecretManager not found at: `$secretManagerPath" -ForegroundColor Yellow
    Write-Host "[WARNING] Environment variables will not be loaded" -ForegroundColor Yellow
}
#endregion

#region Load Environment Variables from SecretManager
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Loading Environment Variables" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

"@

    $varLoadingCode = ""
    foreach ($var in $Variables) {
        $secretKeyName = "$($var.Name)_$FileNumber"
        $varLoadingCode += @"
`$env:$($var.Name) = Get-SecretKey -KeyName "$secretKeyName"
if (`$env:$($var.Name)) {
    Write-Host "[SUCCESS] Loaded $($var.Name) = `$(`$env:$($var.Name))" -ForegroundColor Green
} else {
    Write-Host "[WARNING] Failed to load $($var.Name)" -ForegroundColor Yellow
}

"@
    }

    $buildCommandCode = @"

#region Build Launch Command Display
`$envVarsParts = @()

"@

    foreach ($var in $Variables) {
        $buildCommandCode += @"
if (`$env:$($var.Name)) {
    `$envVarsParts += "```$env:$($var.Name)='`$(`$env:$($var.Name))'"
}

"@
    }

    $buildCommandCode += @"
`$envVarsCommand = `$envVarsParts -join '; '
if (`$envVarsCommand) {
    `$fullCommandDisplay = "`$envVarsCommand; $PsCommand"
} else {
    `$fullCommandDisplay = "$PsCommand"
}
#endregion

"@

    $envSection = $loadSecretManager + $varLoadingCode + $buildCommandCode

    $mcpSectionContent = ""
    if (-not [string]::IsNullOrWhiteSpace($McpSection)) {
        $mcpSectionContent = @"

#region MCP Server Synchronization
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "MCP Server Synchronization" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

$McpSection
#endregion

"@
    }

    $launchSection = @"

#region Launch Tool
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Press Enter to start $ConfigName..." -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
`$null = Read-Host "Press Enter to continue"

Write-Host ""
Write-Host "Executing: $PsCommand" -ForegroundColor White
Write-Host ""
Write-Host "PowerShell Command: powershell -NoProfile -ExecutionPolicy Bypass -Command ```"`$fullCommandDisplay```"" -ForegroundColor White
Write-Host ""
Write-Host "Press any key to continue..." -ForegroundColor Yellow
`$null = `$host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
powershell -NoProfile -ExecutionPolicy Bypass -Command `$fullCommandDisplay

Write-Host ""
pause
#endregion
"@

    $fullContent = @"
$header
$fileNameDisplay
$envSection
$mcpSectionContent
$launchSection
"@

    return $fullContent
}

<#
.SYNOPSIS
    Get MCP sync script path for a specific tool

.DESCRIPTION
    Dynamically construct the MCP synchronization script path for different AI tools
    Convention: {toolname}_sync_mcp_servers.py in pytools\ai_tools\

.PARAMETER ToolType
    Tool type (e.g., "claude", "droid")

.EXAMPLE
    $scriptPath = Get-McpSyncScriptPath -ToolType "claude"
#>
function Get-McpSyncScriptPath {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ToolType
    )

    $scriptParentDir = Split-Path $PSScriptRoot -Parent
    $shellsDir = Split-Path $scriptParentDir -Parent
    $scriptsDir = Split-Path $shellsDir -Parent
    $syncScriptPath = Join-Path $scriptsDir "pytools\ai_tools\${ToolType}_sync_mcp_servers.py"

    return $syncScriptPath
}

<#
.SYNOPSIS
    Get pre-launch script path for a specific tool

.DESCRIPTION
    Dynamically construct the pre-launch script path for different AI tools
    Convention: {toolname}_pre_launch.ps1 in pytools\ai_tools\

.PARAMETER ToolType
    Tool type (e.g., "claude", "droid")

.EXAMPLE
    $scriptPath = Get-PreLaunchScriptPath -ToolType "claude"
#>
function Get-PreLaunchScriptPath {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ToolType
    )

    $scriptParentDir = Split-Path $PSScriptRoot -Parent
    $shellsDir = Split-Path $scriptParentDir -Parent
    $scriptsDir = Split-Path $shellsDir -Parent
    $preLaunchScriptPath = Join-Path $scriptsDir "pytools\ai_tools\${ToolType}_pre_launch.ps1"

    return $preLaunchScriptPath
}

<#
.SYNOPSIS
    Get update/upgrade script path for a specific tool

.DESCRIPTION
    Dynamically construct the update/upgrade script path for different AI tools
    Convention: {toolname}_update.bat in pytools\ai_tools\

.PARAMETER ToolType
    Tool type (e.g., "claude", "droid")

.EXAMPLE
    $scriptPath = Get-UpdateScriptPath -ToolType "claude"
#>
function Get-UpdateScriptPath {
    param(
        [Parameter(Mandatory=$true)]
        [string]$ToolType
    )

    $scriptParentDir = Split-Path $PSScriptRoot -Parent
    $shellsDir = Split-Path $scriptParentDir -Parent
    $scriptsDir = Split-Path $shellsDir -Parent
    $updateScriptPath = Join-Path $scriptsDir "pytools\ai_tools\${ToolType}_update.bat"

    return $updateScriptPath
}

<#
.SYNOPSIS
    Generate generic MCP synchronization section for any AI tool

.DESCRIPTION
    Generate PowerShell content for any AI tool including pre-launch script, upgrade checks and MCP synchronization
    This is the core function that all tool-specific functions should use

.PARAMETER ToolType
    Tool type (e.g., "claude", "droid")

.PARAMETER ToolDisplayName
    Display name for the tool (e.g., "Claude Code", "Factory AI Droid")

.PARAMETER TargetName
    Target name for MCP sync (e.g., "claude", "droid")

.PARAMETER SupportUpgrade
    Whether the tool supports upgrade functionality (default: true)

.PARAMETER FileName
    The PowerShell file name that will be executed

.EXAMPLE
    $mcpContent = New-GenericMcpSection -ToolType "claude" -ToolDisplayName "Claude Code" -TargetName "claude" -SupportUpgrade $true
#>
function New-GenericMcpSection {
    param(
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]$ToolType,

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]$ToolDisplayName,

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]$TargetName,

        [Parameter(Mandatory=$false)]
        [bool]$SupportUpgrade = $true,

        [Parameter(Mandatory=$false)]
        [string]$FileName = ""
    )

    try {
        $updateScriptPath = Get-UpdateScriptPath -ToolType $ToolType
        $syncScriptPath = Get-McpSyncScriptPath -ToolType $ToolType
        $preLaunchScriptPath = Get-PreLaunchScriptPath -ToolType $ToolType
    } catch {
        Write-Error "Failed to get script paths for tool type '${ToolType}': $($_.Exception.Message)"
        throw
    }

    $preLaunchSection = @"
# Execute pre-launch script if it exists
if (Test-Path "${preLaunchScriptPath}") {
    `$currentWorkingDir = Get-Location
    Write-Host "[INFO] Executing pre-launch script: ${preLaunchScriptPath}" -ForegroundColor Cyan
    Write-Host "[INFO] Working Directory: `$currentWorkingDir" -ForegroundColor Cyan
    Write-Host ""
    & "${preLaunchScriptPath}" -WorkingDirectory "`$currentWorkingDir"
    Write-Host ""
}
"@

    $upgradeSection = ""
    if ($SupportUpgrade) {
        $upgradeSection = @"

Write-Host "Available tasks:" -ForegroundColor White
Write-Host "  [1] Upgrade ${ToolDisplayName} to latest version (runs in separate window)" -ForegroundColor White
Write-Host "  [2] Sync MCP server configurations (runs now)" -ForegroundColor White
Write-Host ""

`$upgradeChoice = Read-Host "Do you want to upgrade ${ToolDisplayName}? (y/N)"
if (`$upgradeChoice -eq "y" -or `$upgradeChoice -eq "Y") {
    Write-Host ""
    Write-Host "[INFO] Launching ${ToolDisplayName} upgrade in separate window..." -ForegroundColor Yellow
    Start-Process -FilePath "${updateScriptPath}" -WindowStyle Normal
    Write-Host "[SUCCESS] Upgrade window opened" -ForegroundColor Green
} else {
    Write-Host "[INFO] Skipping upgrade" -ForegroundColor Cyan
}

"@
    }

    $syncSection = @"
`$currentWorkingDir = Get-Location
Write-Host ""
Write-Host "Syncing MCP Server Configurations..." -ForegroundColor Yellow
Write-Host ""
Write-Host "[INFO] Executing: python -u ```"${syncScriptPath}```" --target ${TargetName} --working-dir ```"`$currentWorkingDir```"" -ForegroundColor Cyan
Write-Host "[INFO] Working Directory: `$currentWorkingDir" -ForegroundColor Cyan
Write-Host ""

python -u "${syncScriptPath}" --target ${TargetName} --working-dir "`$currentWorkingDir"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Press Enter to start ${ToolDisplayName}..." -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
`$null = Read-Host "Press Enter to continue"
"@

    return @"
Write-Host "${ToolDisplayName} - Pre-Launch Tasks" -ForegroundColor Yellow
Write-Host ""

$preLaunchSection
$upgradeSection
$syncSection
"@
}

<#
.SYNOPSIS
    Generate MCP synchronization section for Claude AI

.DESCRIPTION
    Generate PowerShell content for Claude AI including upgrade checks and MCP synchronization

.PARAMETER FileName
    The PowerShell file name that will be executed

.EXAMPLE
    $mcpContent = New-ClaudeMcpSection -FileName "claude1.ps1"
#>
function New-ClaudeMcpSection {
    param(
        [Parameter(Mandatory=$false)]
        [string]$FileName = ""
    )

    return New-GenericMcpSection -ToolType "claude" -ToolDisplayName "Claude Code" -TargetName "claude" -SupportUpgrade $true -FileName $FileName
}

<#
.SYNOPSIS
    Generate MCP synchronization section for Factory AI Droid

.DESCRIPTION
    Generate PowerShell content for Factory AI Droid MCP synchronization

.PARAMETER FileName
    The PowerShell file name that will be executed

.EXAMPLE
    $mcpContent = New-DroidMcpSection -FileName "droid1.ps1"
#>
function New-DroidMcpSection {
    param(
        [Parameter(Mandatory=$false)]
        [string]$FileName = ""
    )

    return New-GenericMcpSection -ToolType "droid" -ToolDisplayName "Factory AI Droid" -TargetName "droid" -SupportUpgrade $true -FileName $FileName
}

<#
.SYNOPSIS
    Get tool configuration by tool type

.DESCRIPTION
    Get standardized tool configuration including display name, target name, and upgrade support

.PARAMETER ToolType
    Tool type (e.g., "claude", "droid")

.EXAMPLE
    $config = Get-ToolConfiguration -ToolType "claude"
#>
function Get-ToolConfiguration {
    param(
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]$ToolType
    )

    $toolConfigs = @{
        "claude" = @{
            DisplayName = "Claude Code"
            TargetName = "claude"
            SupportUpgrade = $true
        }
        "droid" = @{
            DisplayName = "Factory AI Droid"
            TargetName = "droid"
            SupportUpgrade = $true
        }
    }

    $normalizedType = $ToolType.ToLower()
    if ($toolConfigs.ContainsKey($normalizedType)) {
        return $toolConfigs[$normalizedType]
    } else {
        Write-Warning "Unknown tool type: ${ToolType}. Using default configuration."
        return @{
            DisplayName = $ToolType
            TargetName = $normalizedType
            SupportUpgrade = $true
        }
    }
}

<#
.SYNOPSIS
    Generate corresponding MCP synchronization section based on tool type

.DESCRIPTION
    Generate corresponding MCP synchronization and pre-launch task content based on different AI tool types

.PARAMETER ToolType
    Tool type ("claude" or "droid")

.PARAMETER FileName
    The batch file name that will be executed

.EXAMPLE
    $mcpContent = Get-McpSectionByToolType -ToolType "claude" -FileName "claude1.bat"
#>
function Get-McpSectionByToolType {
    param(
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]$ToolType,

        [Parameter(Mandatory=$false)]
        [string]$FileName = ""
    )

    try {
        $config = Get-ToolConfiguration -ToolType $ToolType

        return New-GenericMcpSection `
            -ToolType $ToolType.ToLower() `
            -ToolDisplayName $config.DisplayName `
            -TargetName $config.TargetName `
            -SupportUpgrade $config.SupportUpgrade `
            -FileName $FileName
    } catch {
        Write-Error "Failed to generate MCP section for tool type '${ToolType}': $($_.Exception.Message)"
        return ""
    }
}

<#
.SYNOPSIS
    Generate environment variable setup commands

.DESCRIPTION
    Generate corresponding batch setup commands based on environment variable configuration
    Values are read from SecretManager instead of being stored as plaintext in batch files.

    Key naming convention:
    - For "Add Command" operation: {VariableName}_{FileName} (uppercase, without .bat extension)
    - For "Set XXXX Environment Variables" operation: {VariableName}_DEFAULT (uppercase)

.PARAMETER Variables
    Environment variable configuration array

.PARAMETER UserInputs
    User input environment variable values (used as fallback if SecretManager read fails)

.PARAMETER FileName
    Batch file name (without extension) for key naming

.PARAMETER UseSecretManager
    Whether to use SecretManager for reading values (default: true)

.EXAMPLE
    $envCommands = New-EnvironmentCommands -Variables $config.Variables -UserInputs $userInputs -FileName "claude1"
#>
function New-EnvironmentCommands {
    param(
        [Parameter(Mandatory=$true)]
        [array]$Variables,

        [Parameter(Mandatory=$true)]
        [hashtable]$UserInputs,

        [Parameter(Mandatory=$false)]
        [string]$FileName = "",

        [Parameter(Mandatory=$false)]
        [bool]$UseSecretManager = $true
    )

    $envCommands = @()
    $psEnvVars = @()
    $secretManagerAvailable = (Get-Command Get-SecretKey -ErrorAction SilentlyContinue) -ne $null

    $fileNumber = ""
    if (-not [string]::IsNullOrWhiteSpace($FileName)) {
        if ($FileName -match "(\d+)\.bat$") {
            $fileNumber = $matches[1]
        }
    }

    foreach ($var in $Variables) {
        $varValue = $null
        $secretKeyName = ""

        if ($UseSecretManager -and $secretManagerAvailable) {
            if (-not [string]::IsNullOrWhiteSpace($fileNumber)) {
                $secretKeyName = "$($var.Name)_$fileNumber"
            } else {
                $secretKeyName = "$($var.Name)_DEFAULT"
            }

            try {
                $varValue = Get-SecretKey -KeyName $secretKeyName -ErrorAction SilentlyContinue
                if ([string]::IsNullOrWhiteSpace($varValue)) {
                    $varValue = $null
                }
            } catch {
                $varValue = $null
            }
        }

        if ([string]::IsNullOrWhiteSpace($varValue) -and $UserInputs.ContainsKey($var.Name)) {
            $varValue = $UserInputs[$var.Name]
        }

        if (-not [string]::IsNullOrWhiteSpace($varValue)) {
            $envCommands += "echo Setting $($var.Name)=[LOADED FROM SECRET]"
            $envCommands += "set $($var.Name)=$varValue"
            $psEnvVars += "`$env:$($var.Name)='$varValue'"
        } else {
            $envCommands += "echo Skipping $($var.Name) (not set)"
            $envCommands += "REM set $($var.Name)=  # Not set"
        }
    }

    return @{
        EnvCommands = $envCommands
        PsEnvVars = $psEnvVars -join "; "
    }
}

<#
.SYNOPSIS
    Preview generated command content

.DESCRIPTION
    Display command content preview before generating actual file

.PARAMETER Content
    Content to preview

.PARAMETER FilePath
    Target file path

.EXAMPLE
    Show-CommandPreview -Content $batchContent -FilePath $targetPath
#>
function Show-CommandPreview {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Content,
        
        [Parameter(Mandatory=$true)]
        [string]$FilePath
    )
    
    Write-ColorMessage -Message "`nPreview of generated batch file:" -Type "Info"
    Write-ColorMessage -Message "File path: $FilePath" -Type "Info"
    Write-ColorMessage -Message ("=" * 50) -Type "Info"
    Write-Host $Content -ForegroundColor Cyan
    Write-ColorMessage -Message ("=" * 50) -Type "Info"
}

<#
.SYNOPSIS
    Confirm command generation

.DESCRIPTION
    Ask user whether to confirm command file generation

.PARAMETER None

.EXAMPLE
    $confirmed = Confirm-CommandGeneration
#>
function Confirm-CommandGeneration {
    Write-ColorMessage -Message "Press Enter to generate file, any other key to cancel" -Type "Info"
    $confirm = Read-Host "Confirm"
    
    if ($confirm -ne '') {
        Write-ColorMessage -Message "Command generation cancelled." -Type "Warning"
        return $false
    }
    
    return $true
}

#endregion

#region Advanced Command Generation Functions

<#
.SYNOPSIS
    Generate complete command content (advanced interface)

.DESCRIPTION
    This is the main interface for generating command content, integrating all necessary functionality

.PARAMETER Config
    Configuration object

.PARAMETER CommandPrefix
    Command prefix

.PARAMETER PsCommand
    PowerShell command

.PARAMETER FileNumber
    File number

.PARAMETER UserInputs
    User input environment variable values

.PARAMETER ShowPreview
    Whether to show preview (default: true)

.PARAMETER RequireConfirmation
    Whether to require user confirmation (default: true)

.EXAMPLE
    $result = New-CompleteCommandContent -Config $config -CommandPrefix "claude" -PsCommand "claude" -FileNumber 1 -UserInputs $inputs
#>
function New-CompleteCommandContent {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config,
        
        [Parameter(Mandatory=$true)]
        [string]$CommandPrefix,
        
        [Parameter(Mandatory=$true)]
        [string]$PsCommand,
        
        [Parameter(Mandatory=$true)]
        [int]$FileNumber,
        
        [Parameter(Mandatory=$true)]
        [hashtable]$UserInputs,
        
        [Parameter(Mandatory=$false)]
        [bool]$ShowPreview = $true,
        
        [Parameter(Mandatory=$false)]
        [bool]$RequireConfirmation = $true,
        
        [Parameter(Mandatory=$false)]
        [string]$FileName = ""
    )
    
    try {
        # 1. Generate MCP synchronization section
        $mcpSection = Get-McpSectionByToolType -ToolType $PsCommand -FileName $FileName

        # 2. Generate complete command content
        $commandContent = New-CommandContent -ConfigName $Config.Title -CommandPrefix $CommandPrefix -PsCommand $PsCommand -FileNumber $FileNumber -Variables $Config.Variables -McpSection $mcpSection -FileName $FileName

        # 3. Show preview (if needed)
        if ($ShowPreview) {
            $winenvsDir = Join-Path $Global:CORE_NODE_DIR $Global:WINENVS_DIR
            $targetPath = Join-Path $winenvsDir "${CommandPrefix}${FileNumber}.ps1"
            Show-CommandPreview -Content $commandContent -FilePath $targetPath
        }

        # 4. User confirmation (if needed)
        if ($RequireConfirmation) {
            $confirmed = Confirm-CommandGeneration
            if (-not $confirmed) {
                return @{
                    Success = $false
                    Message = "User cancelled command generation"
                    Content = $null
                }
            }
        }

        return @{
            Success = $true
            Message = "Command content generated successfully"
            Content = $commandContent
            McpSection = $mcpSection
        }

    } catch {
        return @{
            Success = $false
            Message = "Error occurred while generating command content: $($_.Exception.Message)"
            Content = $null
        }
    }
}

#endregion

#region Export Functions
# Note: Export-ModuleMember can only be used inside a module
# These functions are available when the script is dot-sourced
#
# Core Path Functions:
# - Get-McpSyncScriptPath        : Get MCP sync script path for a tool
# - Get-PreLaunchScriptPath      : Get pre-launch script path for a tool
# - Get-UpdateScriptPath         : Get update script path for a tool
#
# Core Configuration Functions:
# - Get-ToolConfiguration        : Get tool configuration (display name, target name, etc.)
#
# Core MCP Section Functions:
# - New-GenericMcpSection        : Generic MCP section generator (used by all tools)
# - New-ClaudeMcpSection         : Claude-specific wrapper (calls New-GenericMcpSection)
# - New-DroidMcpSection          : Droid-specific wrapper (calls New-GenericMcpSection)
# - Get-McpSectionByToolType     : Get MCP section by tool type (uses Get-ToolConfiguration)
#
# Command Generation Functions:
# - New-CommandContent           : Generate complete command content
# - New-EnvironmentCommands      : Generate environment variable setup commands
# - New-CompleteCommandContent   : Main interface for generating command content
#
# UI/Helper Functions:
# - Show-CommandPreview          : Preview generated command content
# - Confirm-CommandGeneration    : Confirm command generation
#
# File naming conventions:
# - MCP sync scripts: {toolname}_sync_mcp_servers.py in pytools\ai_tools\
# - Pre-launch scripts: {toolname}_pre_launch.ps1 in pytools\ai_tools\
# - Update scripts: {toolname}_update.bat in pytools\ai_tools\
#
# Adding new tools (Method 1 - Configuration-based, Recommended):
# 1. Add tool configuration to Get-ToolConfiguration function's $toolConfigs hashtable
# 2. Create {toolname}_sync_mcp_servers.py
# 3. Create {toolname}_update.bat
# 4. (Optional) Create {toolname}_pre_launch.ps1
# 5. Use Get-McpSectionByToolType -ToolType "{toolname}" (auto-configured)
#
# Adding new tools (Method 2 - Custom wrapper function):
# 1. Create {toolname}_sync_mcp_servers.py
# 2. Create {toolname}_update.bat
# 3. (Optional) Create {toolname}_pre_launch.ps1
# 4. Add configuration in Get-ToolConfiguration (optional)
# 5. Add new function: New-{ToolName}McpSection that calls New-GenericMcpSection
#endregion

# =============================================================================
# Module initialization completed
# =============================================================================
Write-ColorMessage -Message "CommandContentGenerator module loaded" -Type "Success"
