#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Windows Startup Manager - Auto-start on Windows Boot

Manages Windows startup entries for pycore_module_caller.
Creates/removes startup scripts in Windows Startup folder.

Features:
- Creates .bat script that uses pythonw.exe for background execution
- 5-second delay before closing console (for debugging startup issues)
- Toggle on/off with automatic file replacement
- Supports current user startup folder

Usage:
    from pycore.callmodule.platform.windows_startup_manager import WindowsStartupManager

    manager = WindowsStartupManager()

    # Check status
    if manager.is_enabled():
        print("Auto-start enabled")

    # Enable auto-start
    manager.enable()

    # Disable auto-start
    manager.disable()

    # Toggle
    manager.toggle()
"""

import os
import sys
from pathlib import Path
from typing import Optional


class WindowsStartupManager:
    """
    Manages Windows startup entries for pycore_module_caller

    Creates startup script in user's Startup folder that launches
    the application using pythonw.exe (no console window).
    """

    def __init__(self, app_name: str = "PyCore_RPC_Server"):
        """
        Initialize startup manager

        Args:
            app_name: Application name for startup script
        """
        self.app_name = app_name
        self.script_name = f"{app_name}.bat"

        # Windows Startup folder (current user)
        startup_folder = Path(os.environ.get('APPDATA', '')) / \
                        'Microsoft' / 'Windows' / 'Start Menu' / 'Programs' / 'Startup'

        self.startup_folder = startup_folder
        self.script_path = self.startup_folder / self.script_name

        # Get paths
        self.python_exe = sys.executable  # python.exe
        self.pythonw_exe = self._get_pythonw_path()  # pythonw.exe

        # Get pycore_module_caller.py path
        self.launcher_script = self._get_launcher_path()

    def _get_pythonw_path(self) -> Path:
        """
        Get pythonw.exe path from python.exe path

        Returns:
            Path to pythonw.exe
        """
        python_dir = Path(self.python_exe).parent
        pythonw_exe = python_dir / "pythonw.exe"

        if not pythonw_exe.exists():
            # Fallback to python.exe if pythonw.exe not found
            return Path(self.python_exe)

        return pythonw_exe

    def _get_launcher_path(self) -> Path:
        """
        Get pycore_module_caller.py path

        Returns:
            Path to launcher script
        """
        # Detect if running from source or installed
        current_file = Path(__file__)

        # Try to find pycore_module_caller.py
        # Assume: pycore/callmodule/platform/windows_startup_manager.py
        # Target: pycore_module_caller.py (3 levels up)

        possible_paths = [
            current_file.parent.parent.parent.parent / "pycore_module_caller.py",  # Source tree
            Path(sys.executable).parent / "Scripts" / "pycore_module_caller.py",  # Installed
        ]

        for path in possible_paths:
            if path.exists():
                return path

        # Fallback: use current directory
        return Path.cwd() / "pycore_module_caller.py"

    def _generate_startup_script(self) -> str:
        """
        Generate Windows batch script for startup

        Returns:
            Script content as string
        """
        script = f'''@echo off
REM ================================================================
REM PyCore RPC Server - Auto Start Script
REM Generated by Windows Startup Manager
REM ================================================================

echo [PyCore] Starting RPC Server...
echo [PyCore] Python: {self.pythonw_exe}
echo [PyCore] Script: {self.launcher_script}
echo.

REM Start server using pythonw.exe (no console window after this script closes)
start "" "{self.pythonw_exe}" "{self.launcher_script}"

echo [PyCore] Server started in background (using pythonw.exe)
echo [PyCore] Check system tray for icon
echo.
echo This window will close in 5 seconds...
echo If you see errors above, please report them for fixing.
echo.

REM Wait 5 seconds to allow viewing startup messages/errors
timeout /t 5 /nobreak >nul

REM Close this console window
exit
'''
        return script

    def is_enabled(self) -> bool:
        """
        Check if auto-start is enabled

        Returns:
            True if startup script exists
        """
        return self.script_path.exists()

    def enable(self) -> dict:
        """
        Enable auto-start on Windows boot

        Creates startup script in Windows Startup folder.
        If script already exists, it will be replaced.

        Returns:
            Result dict with success status and message
        """
        try:
            # Ensure startup folder exists
            self.startup_folder.mkdir(parents=True, exist_ok=True)

            # Generate script
            script_content = self._generate_startup_script()

            # Write script (will replace if exists)
            with open(self.script_path, 'w', encoding='utf-8') as f:
                f.write(script_content)

            return {
                "success": True,
                "enabled": True,
                "message": f"Auto-start enabled: {self.script_path}",
                "script_path": str(self.script_path)
            }

        except Exception as e:
            return {
                "success": False,
                "enabled": False,
                "message": f"Failed to enable auto-start: {e}",
                "error": str(e)
            }

    def disable(self) -> dict:
        """
        Disable auto-start on Windows boot

        Removes startup script from Windows Startup folder.

        Returns:
            Result dict with success status and message
        """
        try:
            if self.script_path.exists():
                self.script_path.unlink()  # Delete file
                return {
                    "success": True,
                    "enabled": False,
                    "message": "Auto-start disabled (script removed)",
                    "script_path": str(self.script_path)
                }
            else:
                return {
                    "success": True,
                    "enabled": False,
                    "message": "Auto-start already disabled (script not found)",
                    "script_path": str(self.script_path)
                }

        except Exception as e:
            return {
                "success": False,
                "enabled": self.is_enabled(),
                "message": f"Failed to disable auto-start: {e}",
                "error": str(e)
            }

    def toggle(self) -> dict:
        """
        Toggle auto-start on/off

        Returns:
            Result dict with success status and message
        """
        if self.is_enabled():
            return self.disable()
        else:
            return self.enable()

    def get_status(self) -> dict:
        """
        Get current auto-start status

        Returns:
            Status dict with details
        """
        enabled = self.is_enabled()

        return {
            "enabled": enabled,
            "script_path": str(self.script_path),
            "script_exists": self.script_path.exists(),
            "startup_folder": str(self.startup_folder),
            "python_exe": str(self.python_exe),
            "pythonw_exe": str(self.pythonw_exe),
            "launcher_script": str(self.launcher_script),
            "launcher_exists": self.launcher_script.exists()
        }


# Test
if __name__ == "__main__":
    from pycore import ColorPrint

    ColorPrint.blue("=" * 70)
    ColorPrint.blue(" WINDOWS STARTUP MANAGER TEST")
    ColorPrint.blue("=" * 70)

    manager = WindowsStartupManager()

    # Get status
    ColorPrint.blue("\n[1] Current Status:")
    status = manager.get_status()
    for key, value in status.items():
        print(f"  {key}: {value}")

    # Test enable
    ColorPrint.blue("\n[2] Testing Enable:")
    result = manager.enable()
    ColorPrint.green(f"  {result['message']}")

    # Check status
    ColorPrint.blue("\n[3] Status After Enable:")
    print(f"  Enabled: {manager.is_enabled()}")

    # Show script content
    if manager.script_path.exists():
        ColorPrint.blue("\n[4] Generated Script Content:")
        with open(manager.script_path, 'r', encoding='utf-8') as f:
            ColorPrint.yellow(f.read())

    # Test disable
    ColorPrint.blue("\n[5] Testing Disable:")
    result = manager.disable()
    ColorPrint.green(f"  {result['message']}")

    # Final status
    ColorPrint.blue("\n[6] Final Status:")
    print(f"  Enabled: {manager.is_enabled()}")

    ColorPrint.blue("=" * 70)
    ColorPrint.blue(" TEST COMPLETED")
    ColorPrint.blue("=" * 70)
