import { defineAsyncComponent } from 'vue';

const TOOL_COMPONENT_MAP: Record<string, () => Promise<any>> = {
  hash_text: () => import('./crypto/HashTextTool.vue'),
  token_generator: () => import('./crypto/TokenGeneratorTool.vue'),
  bcrypt: () => import('./crypto/BcryptTool.vue'),
  uuid_generator: () => import('./crypto/UUIDGeneratorTool.vue'),
  ulid_generator: () => import('./crypto/ULIDGeneratorTool.vue'),
  bip39_generator: () => import('./crypto/Bip39GeneratorTool.vue'),
  hmac_generator: () => import('./crypto/HmacGeneratorTool.vue'),
  rsa_key_pair_generator: () => import('./crypto/RsaKeyPairGeneratorTool.vue'),
  otp_code_generator_and_validator: () => import('./crypto/OtpTool.vue'),
  encryption: () => import('./crypto/EncryptionTool.vue'),
  password_strength_analyser: () => import('./crypto/PasswordStrengthTool.vue'),
  basic_auth_generator: () => import('./crypto/BasicAuthTool.vue'),
  base64_string_converter: () => import('./converter/Base64ConverterTool.vue'),
  base64_file_converter: () => import('./converter/Base64FileConverterTool.vue'),
  url_encoder: () => import('./converter/UrlConverterTool.vue'),
  case_converter: () => import('./converter/CaseConverterTool.vue'),
  color_converter: () => import('./converter/ColorConverterTool.vue'),
  slugify_string: () => import('./converter/SlugifyTool.vue'),
  temperature_converter: () => import('./converter/TemperatureConverterTool.vue'),
  date_time_converter: () => import('./converter/DateTimeConverterTool.vue'),
  json_to_yaml_converter: () => import('./converter/JsonToYamlTool.vue'),
  yaml_to_json_converter: () => import('./converter/YamlToJsonTool.vue'),
  json_to_xml_converter: () => import('./converter/JsonToXmlTool.vue'),
  xml_to_json_converter: () => import('./converter/XmlToJsonTool.vue'),
  markdown_to_html_converter: () => import('./converter/MarkdownToHtmlTool.vue'),
  list_converter: () => import('./converter/ListConverterTool.vue'),
  text_to_binary: () => import('./converter/TextEncodingTool.vue'),
  text_to_unicode: () => import('./converter/TextEncodingTool.vue'),
  text_to_nato_alphabet: () => import('./converter/TextEncodingTool.vue'),
  integer_base_converter: () => import('./converter/IntegerBaseConverterTool.vue'),
  roman_numeral_converter: () => import('./converter/RomanNumeralConverterTool.vue'),
  json_to_toml_converter: () => import('./converter/JsonToTomlTool.vue'),
  toml_to_json_converter: () => import('./converter/TomlToJsonTool.vue'),
  toml_to_yaml_converter: () => import('./converter/TomlToYamlTool.vue'),
  yaml_to_toml_converter: () => import('./converter/YamlToTomlTool.vue'),
  html_entities: () => import('./converter/HtmlEntitiesTool.vue'),
  json_prettify: () => import('./web/JsonPrettifyTool.vue'),
  json_minify: () => import('./web/JsonMinifyTool.vue'),
  json_diff: () => import('./web/JsonDiffTool.vue'),
  json_to_csv_converter: () => import('./web/JsonToCsvTool.vue'),
  url_parser: () => import('./web/UrlParserTool.vue'),
  jwt_parser: () => import('./web/JwtParserTool.vue'),
  qr_code_generator: () => import('./web/QrCodeGeneratorTool.vue'),
  wifi_qr_code_generator: () => import('./web/WifiQrCodeGeneratorTool.vue'),
  meta_tag_generator: () => import('./web/MetaTagGeneratorTool.vue'),
  http_status_codes: () => import('./web/HttpStatusCodesTool.vue'),
  mime_types: () => import('./web/MimeTypesTool.vue'),
  html_wysiwyg_editor: () => import('./web/HtmlWysiwygEditorTool.vue'),
  sql_prettify: () => import('./web/SqlPrettifyTool.vue'),
  xml_formatter: () => import('./web/XmlFormatterTool.vue'),
  yaml_viewer: () => import('./web/YamlViewerTool.vue'),
  user_agent_parser: () => import('./web/UserAgentParserTool.vue'),
  math_evaluator: () => import('./math/MathEvaluatorTool.vue'),
  percentage_calculator: () => import('./math/PercentageCalculatorTool.vue'),
  eta_calculator: () => import('./math/EtaCalculatorTool.vue'),
  benchmark_builder: () => import('./math/BenchmarkBuilderTool.vue'),
  chronometer: () => import('./math/ChronometerTool.vue'),
  ipv4_address_converter: () => import('./network/Ipv4AddressConverterTool.vue'),
  ipv4_subnet_calculator: () => import('./network/Ipv4SubnetCalculatorTool.vue'),
  ipv4_range_expander: () => import('./network/Ipv4RangeExpanderTool.vue'),
  ipv6_ula_generator: () => import('./network/Ipv6UlaGeneratorTool.vue'),
  mac_address_generator: () => import('./network/MacAddressGeneratorTool.vue'),
  mac_address_lookup: () => import('./network/MacAddressLookupTool.vue')
};

export const getToolComponent = (toolId: string | null | undefined) => {
  if (!toolId) return null;
  const loader = TOOL_COMPONENT_MAP[toolId];
  return loader ? defineAsyncComponent(loader) : null;
};
