<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>DotCore.YoloRecord</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="OpenCvSharp4.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotCore.ScreenCapture\DotCore.ScreenCapture.csproj" />
    <ProjectReference Include="..\DotCore.VocAnnotator\DotCore.VocAnnotator.csproj" />
  </ItemGroup>
</Project>
