# =============================================================================
# Ark CLI (Volcano Ark / GLM) Launch Script #3 - v4 [arkcli -> Claude]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Flow: check tools -> arkcli configure model -> arkcli Agent Plan MCP
#   -> add ark-docs-mcp -> optional API/model force -> launch claude.
# Isolated user profile: D:\programing\Users\ark3
# Optional secrets (if present): ARKCLI_PROFILE / ARKCLI_MODEL /
#   ARKCLI_MCP_PROFILE / ARKCLI_OV_RESOURCE / ARKCLI_API / ARKCLI_API_KEY
#   for slot #3.
# ARKCLI_API_KEY set: skip arkcli -> plain Claude under ark3 user dir
#   (Claude data stays in that custom profile); ARKCLI_API -> ANTHROPIC_BASE_URL.
# Else: arkcli configure/MCP; ARKCLI_API still forces ANTHROPIC_BASE_URL after.
# Model: ARKCLI_MODEL set -> Use model xxx? [Y/n] (Y=xxx);
#   empty -> Use model kimi-k3? [Y/n]; any N -> auto ark-code-latest.
# Agent Teams: OFF by default. Pass -team / --team to enable.
# Extra CLI args are forwarded to claude (e.g. ark3.ps1 -p "hi").
# =============================================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Variables declared at the top of the file (project rule).
$arkcliCmd = $null
$arkcliOk = $false
$arkcliCheckResult = $null
$arkcliInstallResult = $null
$claudeCmd = $null
$claudeOk = $false
$pnpmExe = $null
$pnpmCmd = $null
$loginChoice = $null
$exitCode = 0
$scriptActualPath = $null
$item = $null
$scriptCurrentPath = $null
$scriptsDirPath = $null
$projectRootPath = $null
$shellsWinPath = $null
$winCommonDirPath = $null
$windowsPathFunctionScript = $null
$globalVarsScript = $null
$secretDir = $null
$arkUserBase = $null
$arkUserDir = $null
$claudeConfigDir = $null
$arkcliHomeDir = $null
$arkcliProfile = $null
$arkcliModel = $null
$arkcliMcpProfile = $null
$arkcliOvResource = $null
$arkcliApi = $null
$arkcliApiKey = $null
$usePlainClaude = $false
$maskedApiKey = $null
$apiKeyEnvState = $null
$modelChoice = $null
$forceModel = $false
$resolvedModel = $null
$promptArkModel = "kimi-k3"
$fallbackArkModel = "ark-code-latest"
$configureArgs = $null
$mcpArgs = $null
$mcpOutput = $null
$mcpExit = 0
$mcpResult = $null
$docsGetOutput = $null
$docsGetExit = 0
$docsGetResult = $null
$docsUrlFound = $null
$docsAddResult = $null
$ultraSettingsJson = $null
$ultraSettingsFile = $null
$claudeArgs = $null
$teammateMode = $null
$enableTeam = $false
$enableUltra = $false
$ultraChoice = $null
$prevEap = $null
$hasAgentPlanMcp = $false
$hasDocsMcp = $false
$runMcpSetup = $true
$reconfigMcpChoice = $null
$detectedMcpNames = $null
$homeClaudeJson = $null
$configClaudeJson = $null
$mcpName = $null
$userArgs = $null
$arg = $null

$env:DISABLE_AUTOUPDATER = "1"
$env:CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = "1"

$ultraSettingsJson = '{"ultracode":true}'
$ultraSettingsFile = Join-Path $env:TEMP "ark3_ultracode_settings.json"
# Parse -team/--team (opt-in Agent Teams); remaining args forwarded to claude.
$userArgs = @()
foreach ($arg in @($args)) {
    if ($arg -eq "-team" -or $arg -eq "--team") {
        $enableTeam = $true
    } else {
        $userArgs += $arg
    }
}
if ($enableTeam) {
    $env:CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "1"
    $teammateMode = "in-process"
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Ark CLI (Volcano Ark / GLM) #3 - v4 [arkcli -> Claude]" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Initialize path variables (resolve symlinks, then scripts/project roots).
$scriptActualPath = $PSCommandPath
$item = Get-Item -LiteralPath $PSCommandPath
if ($item -and $item -is [System.IO.FileInfo] -and $item.LinkType) {
    $scriptActualPath = $item.Target
}
$scriptCurrentPath = Split-Path $scriptActualPath -Parent
if (-not $scriptCurrentPath) {
    $scriptCurrentPath = $PSScriptRoot
    if (-not $scriptCurrentPath) {
        $scriptCurrentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
    }
}
$scriptsDirPath = Split-Path $scriptCurrentPath -Parent
$projectRootPath = Split-Path $scriptsDirPath -Parent

# Ensure PATH + absolute pnpm path (Global:PNPM_EXE_PATH from Step4_InstallNodeJS).
$shellsWinPath = Join-Path $scriptsDirPath "shells"
$shellsWinPath = Join-Path $shellsWinPath "win"
$winCommonDirPath = Join-Path $shellsWinPath "win_common"
$windowsPathFunctionScript = Join-Path $winCommonDirPath "WindowsPathFunction.ps1"
$globalVarsScript = Join-Path $winCommonDirPath "GlobalVars.ps1"
. $globalVarsScript
. $windowsPathFunctionScript
Set-CoreNodePaths

# Isolated Claude + arkcli user profile (map path: D:\programing\Users\ark3).
# arkcli ByteCloud migrate requires ~/.arkcli to be a REAL directory (not a junction
# or symlink). Path-mapping may have left junctions pointing at the host profile;
# replace those with real dirs (materialize copy once) before any arkcli call.
$arkUserBase = "D:\programing\Users"
$arkUserDir = Join-Path $arkUserBase "ark3"
if (-not (Test-Path -LiteralPath $arkUserDir)) {
    New-Item -ItemType Directory -Path $arkUserDir -Force | Out-Null
    Write-Host "[INFO] Created Ark user dir: $arkUserDir" -ForegroundColor Cyan
}

function Ensure-RealHomeDotDir {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )
    $item = $null
    $linkTarget = $null
    $isReparse = $false
    if (Test-Path -LiteralPath $Path) {
        $item = Get-Item -LiteralPath $Path -Force
        $isReparse = [bool]($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint)
        if ($isReparse) {
            if ($item.Target) {
                $linkTarget = [string](@($item.Target)[0])
            }
            # rmdir removes the junction/symlink only; target contents stay.
            cmd /c rmdir "$Path" | Out-Null
            New-Item -ItemType Directory -Path $Path -Force | Out-Null
            if (-not [string]::IsNullOrWhiteSpace($linkTarget) -and (Test-Path -LiteralPath $linkTarget)) {
                & robocopy $linkTarget $Path /E /NFL /NDL /NJH /NJS /nc /ns /np | Out-Null
            }
            Write-Host "[INFO] Replaced junction/symlink with real directory: $Path" -ForegroundColor Yellow
            return
        }
        return
    }
    New-Item -ItemType Directory -Path $Path -Force | Out-Null
}

$claudeConfigDir = Join-Path $arkUserDir ".claude"
$arkcliHomeDir = Join-Path $arkUserDir ".arkcli"
Ensure-RealHomeDotDir -Path $claudeConfigDir
Ensure-RealHomeDotDir -Path $arkcliHomeDir
$env:USERPROFILE = $arkUserDir
$env:HOME = $arkUserDir
$env:USER_HOME = $arkUserDir
$env:HOMEPATH = $arkUserDir
$env:USER_DIR = $arkUserDir
$env:CLAUDE_CONFIG_DIR = $claudeConfigDir
Write-Host "[INFO] USERPROFILE       = $env:USERPROFILE" -ForegroundColor Cyan
Write-Host "[INFO] CLAUDE_CONFIG_DIR = $env:CLAUDE_CONFIG_DIR" -ForegroundColor Cyan
Write-Host "[INFO] ARKCLI home       = $arkcliHomeDir (real directory)" -ForegroundColor Cyan

function Read-SecretFile {
    param([string]$FilePath)
    $value = ""
    if (Test-Path -LiteralPath $FilePath) {
        try {
            $bytes = [System.IO.File]::ReadAllBytes($FilePath)
            if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
                $bytes = $bytes[3..($bytes.Length - 1)]
            }
            $content = [System.Text.Encoding]::UTF8.GetString($bytes)
            $lines = $content -split "`r?`n"
            foreach ($line in $lines) {
                $trimmedLine = $line.Trim()
                if ($trimmedLine) {
                    $value = $trimmedLine
                    break
                }
            }
        }
        catch {
            $value = ""
        }
    }
    return $value
}

$secretDir = Join-Path $projectRootPath ".secret_keys\.secret_ignore"
$arkcliProfile = Read-SecretFile (Join-Path $secretDir "ARKCLI_PROFILE_3")
$arkcliModel = Read-SecretFile (Join-Path $secretDir "ARKCLI_MODEL_3")
$arkcliMcpProfile = Read-SecretFile (Join-Path $secretDir "ARKCLI_MCP_PROFILE_3")
$arkcliOvResource = Read-SecretFile (Join-Path $secretDir "ARKCLI_OV_RESOURCE_3")
$arkcliApi = Read-SecretFile (Join-Path $secretDir "ARKCLI_API_3")
$arkcliApiKey = Read-SecretFile (Join-Path $secretDir "ARKCLI_API_KEY_3")
if ([string]::IsNullOrWhiteSpace($arkcliProfile) -and -not [string]::IsNullOrWhiteSpace($env:ARKCLI_PROFILE)) {
    $arkcliProfile = $env:ARKCLI_PROFILE
}
if ([string]::IsNullOrWhiteSpace($arkcliModel) -and -not [string]::IsNullOrWhiteSpace($env:ARKCLI_MODEL)) {
    $arkcliModel = $env:ARKCLI_MODEL
}
if ([string]::IsNullOrWhiteSpace($arkcliMcpProfile) -and -not [string]::IsNullOrWhiteSpace($env:ARKCLI_MCP_PROFILE)) {
    $arkcliMcpProfile = $env:ARKCLI_MCP_PROFILE
}
if ([string]::IsNullOrWhiteSpace($arkcliOvResource) -and -not [string]::IsNullOrWhiteSpace($env:ARKCLI_OV_RESOURCE)) {
    $arkcliOvResource = $env:ARKCLI_OV_RESOURCE
}
if ([string]::IsNullOrWhiteSpace($arkcliApi) -and -not [string]::IsNullOrWhiteSpace($env:ARKCLI_API)) {
    $arkcliApi = $env:ARKCLI_API
}
if ([string]::IsNullOrWhiteSpace($arkcliApiKey) -and -not [string]::IsNullOrWhiteSpace($env:ARKCLI_API_KEY)) {
    $arkcliApiKey = $env:ARKCLI_API_KEY
}
if (-not [string]::IsNullOrWhiteSpace($arkcliApi)) {
    $arkcliApi = $arkcliApi.TrimEnd('/')
    foreach ($suffix in @('/v1/chat/completions', '/chat/completions', '/v1/messages', '/messages')) {
        if ($arkcliApi.ToLower().EndsWith($suffix)) {
            $arkcliApi = $arkcliApi.Substring(0, $arkcliApi.Length - $suffix.Length).TrimEnd('/')
            break
        }
    }
}
$usePlainClaude = -not [string]::IsNullOrWhiteSpace($arkcliApiKey)

function Get-MaskedSecret {
    param([string]$Value)
    if ([string]::IsNullOrEmpty($Value)) { return "[empty]" }
    $len = $Value.Length
    if ($len -le 4) {
        return ("*" * $len)
    }
    if ($len -le 8) {
        $keep = 1
    } else {
        $keep = 4
    }
    $middleLen = $len - (2 * $keep)
    if ($middleLen -lt 1) { $middleLen = 1 }
    return ($Value.Substring(0, $keep) + ("*" * $middleLen) + $Value.Substring($len - $keep))
}

function Resolve-PnpmExe {
    $exe = $Global:PNPM_EXE_PATH
    if (-not $exe -or -not (Test-Path -LiteralPath $exe)) {
        $cmd = Get-Command pnpm -ErrorAction SilentlyContinue
        if ($cmd) { $exe = [string]$cmd.Source }
    }
    if (-not $exe -or -not (Test-Path -LiteralPath $exe)) {
        Write-Host "[ERROR] pnpm not found (run Step4_InstallNodeJS.ps1 first)." -ForegroundColor Red
        exit 1
    }
    return $exe
}

# Capture stdout+stderr as text without letting stderr notes become terminating
# errors under $ErrorActionPreference = Stop (e.g. arkcli OpenViking skip note).
function Invoke-ExternalCaptured {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,
        [string[]]$ArgumentList = @()
    )
    $capturedLines = @()
    $capturedExit = 0
    $savedEap = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $raw = & $FilePath @ArgumentList 2>&1
        foreach ($entry in @($raw)) {
            if ($null -eq $entry) { continue }
            if ($entry -is [System.Management.Automation.ErrorRecord]) {
                $capturedLines += [string]$entry.ToString()
            } else {
                $capturedLines += [string]$entry
            }
        }
        $capturedExit = $LASTEXITCODE
        if ($null -eq $capturedExit) { $capturedExit = 0 }
    } finally {
        $ErrorActionPreference = $savedEap
    }
    return [pscustomobject]@{
        ExitCode = [int]$capturedExit
        Output   = ($capturedLines -join [Environment]::NewLine)
    }
}

# 1) Ensure arkcli is installed (skipped in plain Claude / API KEY mode).
if (-not $usePlainClaude) {
$arkcliCmd = Get-Command arkcli -ErrorAction SilentlyContinue
if ($arkcliCmd) {
    $arkcliCheckResult = Invoke-ExternalCaptured -FilePath $arkcliCmd.Source -ArgumentList @("--version")
    if ([int]$arkcliCheckResult.ExitCode -eq 0) { $arkcliOk = $true }
}
if (-not $arkcliOk) {
    Write-Host "arkcli is missing or unhealthy; installing @volcengine/ark-cli@latest via pnpm..." -ForegroundColor Yellow
    $pnpmExe = Resolve-PnpmExe
    $arkcliInstallResult = Invoke-ExternalCaptured -FilePath $pnpmExe -ArgumentList @("add", "--global", "@volcengine/ark-cli@latest")
    if (-not [string]::IsNullOrWhiteSpace([string]$arkcliInstallResult.Output)) {
        Write-Host ([string]$arkcliInstallResult.Output).Trim()
    }
    if ([int]$arkcliInstallResult.ExitCode -ne 0) {
        Write-Host "[ERROR] pnpm install of @volcengine/ark-cli failed." -ForegroundColor Red
        exit 1
    }
    $arkcliCmd = Get-Command arkcli -ErrorAction SilentlyContinue
    if ($arkcliCmd) {
        $arkcliCheckResult = Invoke-ExternalCaptured -FilePath $arkcliCmd.Source -ArgumentList @("--version")
        if ([int]$arkcliCheckResult.ExitCode -eq 0) { $arkcliOk = $true }
    }
    if (-not $arkcliOk) {
        Write-Host "[ERROR] arkcli is unavailable after pnpm installation." -ForegroundColor Red
        if (($null -ne $arkcliCheckResult) -and -not [string]::IsNullOrWhiteSpace([string]$arkcliCheckResult.Output)) {
            Write-Host ([string]$arkcliCheckResult.Output).Trim() -ForegroundColor Red
        }
        exit 1
    }
}
}

# 2) Ensure claude is installed and working (idempotent).
$claudeCmd = Get-Command claude -ErrorAction SilentlyContinue
if ($claudeCmd) {
    & claude --version *> $null
    if ($LASTEXITCODE -eq 0) { $claudeOk = $true }
}
if (-not $claudeOk) {
    Write-Host "claude not found; installing @anthropic-ai/claude-code via pnpm..." -ForegroundColor Yellow
    $pnpmExe = Resolve-PnpmExe
    & $pnpmExe add -g "@anthropic-ai/claude-code"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] pnpm install of @anthropic-ai/claude-code failed." -ForegroundColor Red
        exit 1
    }
    $claudeCmd = Get-Command claude -ErrorAction SilentlyContinue
    if (-not $claudeCmd) {
        Write-Host "[ERROR] claude installed but not on PATH. Restart your shell and re-run this script." -ForegroundColor Red
        exit 1
    }
}

Write-Host "claude: $(& claude --version 2>$null | Select-Object -First 1)" -ForegroundColor White
Write-Host "Isolated user dir: $arkUserDir (Claude data/config for this slot)" -ForegroundColor Cyan
if ($usePlainClaude) {
    Write-Host "Mode: plain Claude (ARKCLI_API_KEY set — skip arkcli)" -ForegroundColor Yellow
    Write-Host "  Purpose: use Claude under Ark custom user dir without arkcli." -ForegroundColor DarkGray
    if ([string]::IsNullOrWhiteSpace($arkcliApi)) {
        Write-Host "[ERROR] ARKCLI_API_KEY is set but ARKCLI_API (BASE_URL) is empty." -ForegroundColor Red
        Write-Host "        Plain Claude needs both: ARKCLI_API + ARKCLI_API_KEY." -ForegroundColor Yellow
        Write-Host "        Example BASE_URL: https://api.example.com (Anthropic-compatible, no /v1/chat/completions)." -ForegroundColor Yellow
        exit 1
    }
    # Match claudevolc/claudealibaba: AUTH_TOKEN + BASE_URL only.
    # Do NOT set ANTHROPIC_API_KEY — it can force official Anthropic auth and cause API errors.
    $env:ANTHROPIC_BASE_URL = $arkcliApi
    $env:ANTHROPIC_AUTH_TOKEN = $arkcliApiKey
    Remove-Item Env:ANTHROPIC_API_KEY -ErrorAction SilentlyContinue
    $maskedApiKey = Get-MaskedSecret $arkcliApiKey
    Write-Host "ARKCLI_API_KEY: $maskedApiKey -> ANTHROPIC_AUTH_TOKEN" -ForegroundColor White
    Write-Host "ANTHROPIC_BASE_URL: $env:ANTHROPIC_BASE_URL (set now)" -ForegroundColor White
} else {
    Write-Host "arkcli: $(& arkcli --version 2>$null | Select-Object -First 1)" -ForegroundColor White
    Write-Host "Mode: arkcli -> Claude" -ForegroundColor White
}
if (-not [string]::IsNullOrWhiteSpace($arkcliProfile)) {
    Write-Host "ARKCLI_PROFILE: $arkcliProfile" -ForegroundColor White
}
if (-not [string]::IsNullOrWhiteSpace($arkcliModel)) {
    Write-Host "ARKCLI_MODEL: $arkcliModel (Use model? [Y/n]; N -> auto ark-code-latest)" -ForegroundColor White
} else {
    Write-Host "ARKCLI_MODEL: (empty — Use model kimi-k3? [Y/n]; N -> auto ark-code-latest)" -ForegroundColor DarkGray
}
if (-not [string]::IsNullOrWhiteSpace($arkcliMcpProfile)) {
    Write-Host "ARKCLI_MCP_PROFILE: $arkcliMcpProfile" -ForegroundColor White
}
if (-not [string]::IsNullOrWhiteSpace($arkcliApi)) {
    Write-Host "ARKCLI_API: $arkcliApi (ANTHROPIC_BASE_URL)" -ForegroundColor White
} elseif ($usePlainClaude) {
    Write-Host "ARKCLI_API: (empty — set with ARKCLI_API_KEY for Anthropic-compatible BASE_URL)" -ForegroundColor Yellow
}
if ($enableTeam) {
    Write-Host "Agent Teams: ON (-team) CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 --teammate-mode in-process" -ForegroundColor Green
} else {
    Write-Host "Agent Teams: OFF (default). Tip: pass -team to enable Agent Teams." -ForegroundColor DarkGray
}
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

if (-not $usePlainClaude) {
# Optional auth login (opt-in, default No).
$loginChoice = Read-Host "Run 'arkcli auth login' now? [y/N]"
if ($loginChoice -eq 'y' -or $loginChoice -eq 'Y') {
    & arkcli auth login
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] arkcli auth login failed." -ForegroundColor Red
        exit $LASTEXITCODE
    }
}

# Stage A: configure Claude model/provider (Coding Plan or Agent Plan).
Write-Host ""
Write-Host "[INFO] Stage A: arkcli helper configure claude-code ..." -ForegroundColor Cyan
$configureArgs = @("helper", "configure", "claude-code")
if (-not [string]::IsNullOrWhiteSpace($arkcliProfile)) {
    $configureArgs += @("--profile", $arkcliProfile)
}
if (-not [string]::IsNullOrWhiteSpace($arkcliModel)) {
    $configureArgs += @("--model", $arkcliModel)
}
& arkcli @configureArgs
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] arkcli helper configure failed. Stopping to avoid a wrong Claude provider." -ForegroundColor Red
    exit $LASTEXITCODE
}

# Detect existing Ark MCP for this isolated slot (file-based; no secrets printed).
# Agent Plan MCP lives in HOME\.claude.json; ark-docs-mcp in CLAUDE_CONFIG_DIR\.claude.json.
function Get-ClaudeMcpServerNames {
    param([string]$JsonPath)
    $names = @()
    if (-not $JsonPath -or -not (Test-Path -LiteralPath $JsonPath)) {
        return $names
    }
    try {
        $json = Get-Content -LiteralPath $JsonPath -Raw -ErrorAction Stop | ConvertFrom-Json
        if ($null -ne $json.mcpServers) {
            $names = @($json.mcpServers.PSObject.Properties.Name)
        }
    } catch {
        $names = @()
    }
    return $names
}

$hasAgentPlanMcp = $false
$hasDocsMcp = $false
$detectedMcpNames = @()
$homeClaudeJson = Join-Path $env:HOME ".claude.json"
$configClaudeJson = Join-Path $env:CLAUDE_CONFIG_DIR ".claude.json"
foreach ($mcpName in @(Get-ClaudeMcpServerNames $homeClaudeJson) + @(Get-ClaudeMcpServerNames $configClaudeJson)) {
    if ([string]::IsNullOrWhiteSpace($mcpName)) { continue }
    if ($detectedMcpNames -notcontains $mcpName) {
        $detectedMcpNames += $mcpName
    }
    if ($mcpName -match '(?i)askecho|datapro|openviking') {
        $hasAgentPlanMcp = $true
    }
    if ($mcpName -eq "ark-docs-mcp") {
        $hasDocsMcp = $true
    }
}

$runMcpSetup = $true
if ($hasAgentPlanMcp -or $hasDocsMcp) {
    Write-Host ""
    Write-Host "[INFO] Existing Ark MCP detected for this slot:" -ForegroundColor Cyan
    if ($hasAgentPlanMcp) {
        Write-Host "  - Agent Plan MCP (askecho / dataPro / openviking)" -ForegroundColor White
    }
    if ($hasDocsMcp) {
        Write-Host "  - ark-docs-mcp" -ForegroundColor White
    }
    if ($detectedMcpNames.Count -gt 0) {
        Write-Host ("  Names: " + ($detectedMcpNames -join ", ")) -ForegroundColor DarkGray
    }
    $reconfigMcpChoice = Read-Host "Reconfigure MCP (helper mcp + ark-docs-mcp)? [y/N]"
    if ($reconfigMcpChoice -eq 'y' -or $reconfigMcpChoice -eq 'Y') {
        $runMcpSetup = $true
        Write-Host "[INFO] Will reconfigure MCP." -ForegroundColor Yellow
    } else {
        $runMcpSetup = $false
        Write-Host "[INFO] Keeping existing MCP; skipping Stages B/C." -ForegroundColor Green
    }
}

if ($runMcpSetup) {
# Stage B: inject Agent Plan built-in MCP (soft-fail when Coding Plan only).
# OpenViking skip notes on stderr must NOT abort the launcher.
Write-Host ""
Write-Host "[INFO] Stage B: arkcli helper mcp claude-code ..." -ForegroundColor Cyan
$mcpArgs = @("helper", "mcp", "claude-code")
if (-not [string]::IsNullOrWhiteSpace($arkcliMcpProfile)) {
    $mcpArgs += @("--profile", $arkcliMcpProfile)
}
if (-not [string]::IsNullOrWhiteSpace($arkcliOvResource)) {
    $mcpArgs += @("--ov-resource", $arkcliOvResource)
}
$mcpResult = Invoke-ExternalCaptured -FilePath "arkcli" -ArgumentList $mcpArgs
$mcpExit = [int]$mcpResult.ExitCode
$mcpOutput = [string]$mcpResult.Output
if ($mcpExit -ne 0) {
    if ($mcpOutput -match '(?i)agent[- ]?plan|no agent plan|未找到.*[Aa]gent|[Aa]gent.*not found|not found.*profile|openviking|已跳过') {
        Write-Host "[WARN] Agent Plan MCP incomplete or unavailable; continuing so Claude can still start." -ForegroundColor Yellow
        if (-not [string]::IsNullOrWhiteSpace($mcpOutput)) {
            Write-Host $mcpOutput.Trim() -ForegroundColor DarkYellow
        }
    } else {
        Write-Host "[ERROR] arkcli helper mcp failed:" -ForegroundColor Red
        if (-not [string]::IsNullOrWhiteSpace($mcpOutput)) {
            Write-Host $mcpOutput.Trim() -ForegroundColor Red
        }
        exit $mcpExit
    }
} else {
    Write-Host "[OK] Agent Plan MCP configured." -ForegroundColor Green
    if ($mcpOutput -match '(?i)openviking|已跳过') {
        Write-Host "[INFO] arkcli note (non-fatal):" -ForegroundColor DarkYellow
        Write-Host $mcpOutput.Trim() -ForegroundColor DarkYellow
    }
}

# Stage C: idempotent public Ark docs MCP.
Write-Host ""
Write-Host "[INFO] Stage C: ensure ark-docs-mcp ..." -ForegroundColor Cyan
$docsGetResult = Invoke-ExternalCaptured -FilePath "claude" -ArgumentList @("mcp", "get", "ark-docs-mcp")
$docsGetExit = [int]$docsGetResult.ExitCode
$docsGetOutput = [string]$docsGetResult.Output
if ($docsGetExit -eq 0) {
    $docsUrlFound = $null
    if ($docsGetOutput -match 'https?://\S+') {
        $docsUrlFound = $Matches[0].TrimEnd('.', ',', ')', ']')
    }
    if ($docsUrlFound -and ($docsUrlFound -ne "https://sd6j8o9hu8aldae0o6es0.apigateway-cn-beijing.volceapi.com/mcp")) {
        Write-Host "[WARN] ark-docs-mcp already exists with a different URL:" -ForegroundColor Yellow
        Write-Host "       existing: $docsUrlFound" -ForegroundColor Yellow
        Write-Host "       expected: https://sd6j8o9hu8aldae0o6es0.apigateway-cn-beijing.volceapi.com/mcp" -ForegroundColor Yellow
        Write-Host "[WARN] Leaving existing MCP entry unchanged." -ForegroundColor Yellow
    } else {
        Write-Host "[OK] ark-docs-mcp already present; skipping add." -ForegroundColor Green
    }
} else {
    $docsAddResult = Invoke-ExternalCaptured -FilePath "claude" -ArgumentList @(
        "mcp", "add", "--transport", "http", "--scope", "user", "ark-docs-mcp", "https://sd6j8o9hu8aldae0o6es0.apigateway-cn-beijing.volceapi.com/mcp"
    )
    if ([int]$docsAddResult.ExitCode -ne 0) {
        Write-Host "[ERROR] Failed to add ark-docs-mcp." -ForegroundColor Red
        if (-not [string]::IsNullOrWhiteSpace([string]$docsAddResult.Output)) {
            Write-Host ([string]$docsAddResult.Output).Trim() -ForegroundColor Red
        }
        exit ([int]$docsAddResult.ExitCode)
    }
    Write-Host "[OK] Added ark-docs-mcp." -ForegroundColor Green
}
} # end if ($runMcpSetup)
} # end if (-not $usePlainClaude)

# Force API base before Claude (post-arkcli override, or re-assert plain mode).
# Isolated arkN HOME/CLAUDE_CONFIG_DIR already set; Claude data stays there.
if (-not [string]::IsNullOrWhiteSpace($arkcliApi)) {
    $env:ANTHROPIC_BASE_URL = $arkcliApi
    Write-Host ""
    Write-Host "[INFO] Forced ANTHROPIC_BASE_URL = $env:ANTHROPIC_BASE_URL (from ARKCLI_API)" -ForegroundColor Cyan
}
if ($usePlainClaude) {
    $env:ANTHROPIC_AUTH_TOKEN = $arkcliApiKey
    Remove-Item Env:ANTHROPIC_API_KEY -ErrorAction SilentlyContinue
}

# Model (after arkcli configure, before Claude):
# - ARKCLI_MODEL set -> Use model xxx? [Y/n] (Y/Enter = xxx)
# - empty -> Use model kimi-k3? [Y/n] (Y/Enter = kimi-k3)
# - any N -> auto-force ark-code-latest (tip only, no 2nd Y/N)
$forceModel = $false
$resolvedModel = $null
Write-Host ""
if (-not [string]::IsNullOrWhiteSpace($arkcliModel)) {
    $modelChoice = Read-Host "Use model ${arkcliModel}? [Y/n]"
    if ($modelChoice -eq 'n' -or $modelChoice -eq 'N') {
        $resolvedModel = $fallbackArkModel
        $forceModel = $true
        Write-Host "[INFO] Declined $arkcliModel; auto-set model = $resolvedModel" -ForegroundColor Green
    } else {
        $resolvedModel = $arkcliModel
        $forceModel = $true
    }
} else {
    $modelChoice = Read-Host "Use model kimi-k3? [Y/n]"
    if ($modelChoice -eq 'n' -or $modelChoice -eq 'N') {
        $resolvedModel = $fallbackArkModel
        $forceModel = $true
        Write-Host "[INFO] Declined kimi-k3; auto-set model = $resolvedModel" -ForegroundColor Green
    } else {
        $resolvedModel = $promptArkModel
        $forceModel = $true
    }
}
if ($forceModel) {
    $env:ANTHROPIC_MODEL = $resolvedModel
    $env:CLAUDE_CODE_SUBAGENT_MODEL = $resolvedModel
    $env:ANTHROPIC_DEFAULT_HAIKU_MODEL = $resolvedModel
    $env:ANTHROPIC_DEFAULT_SONNET_MODEL = $resolvedModel
    Write-Host "[INFO] Forced model = $resolvedModel (main + subagents + background)" -ForegroundColor Cyan
}

# Permission bypass always; Agent Teams only when -team was passed.
$claudeArgs = @("--permission-mode", "bypassPermissions", "--dangerously-skip-permissions")
if ($enableTeam) {
    $claudeArgs = @("--teammate-mode", $teammateMode) + $claudeArgs
}
if ($forceModel) {
    $claudeArgs = @("--model", $resolvedModel) + $claudeArgs
}
# Ultracode: opt-in prompt (default No).
$ultraChoice = Read-Host "Enable ultracode? [y/N]"
if ($ultraChoice -eq 'y' -or $ultraChoice -eq 'Y') {
    $enableUltra = $true
    [System.IO.File]::WriteAllText($ultraSettingsFile, $ultraSettingsJson)
    $claudeArgs += @("--settings", $ultraSettingsFile)
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
if ($usePlainClaude) {
    Write-Host "Press Enter to start Ark CLI (Volcano Ark / GLM) #3 [plain Claude / API KEY]..." -ForegroundColor Yellow
} else {
    Write-Host "Press Enter to start Ark CLI (Volcano Ark / GLM) #3 [arkcli -> Claude]..." -ForegroundColor Yellow
}
if (-not $enableTeam) {
    Write-Host "Tip: re-run with -team to enable Agent Teams (e.g. ark3.ps1 -team)" -ForegroundColor DarkGray
}
Write-Host "============================================================" -ForegroundColor Cyan
$null = Read-Host "Press Enter to continue"

if ($userArgs.Count -gt 0) {
    $claudeArgs += $userArgs
}

# Re-assert plain-Claude gateway env immediately before exec (avoid stale session vars).
if ($usePlainClaude) {
    $env:ANTHROPIC_BASE_URL = $arkcliApi
    $env:ANTHROPIC_AUTH_TOKEN = $arkcliApiKey
    Remove-Item Env:ANTHROPIC_API_KEY -ErrorAction SilentlyContinue
    if ([string]::IsNullOrWhiteSpace($maskedApiKey)) {
        $maskedApiKey = Get-MaskedSecret $arkcliApiKey
    }
}

Write-Host ""
Write-Host "Executing: claude $($claudeArgs -join ' ')" -ForegroundColor White
if ($usePlainClaude) {
    $apiKeyEnvState = "[cleared]"
    if (-not [string]::IsNullOrWhiteSpace($env:ANTHROPIC_API_KEY)) {
        $apiKeyEnvState = "[set-conflict]"
    }
    Write-Host "Environment: ANTHROPIC_BASE_URL='$($env:ANTHROPIC_BASE_URL)', ANTHROPIC_AUTH_TOKEN='$maskedApiKey', ANTHROPIC_MODEL='$($env:ANTHROPIC_MODEL)', ANTHROPIC_API_KEY=$apiKeyEnvState" -ForegroundColor White
}
Write-Host ""

& claude @claudeArgs
$exitCode = $LASTEXITCODE
if ($null -eq $exitCode) { $exitCode = 0 }

if ((-not [string]::IsNullOrWhiteSpace($ultraSettingsFile)) -and (Test-Path -LiteralPath $ultraSettingsFile)) {
    Remove-Item $ultraSettingsFile -Force -ErrorAction SilentlyContinue
}

exit $exitCode
