# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

<#
.SYNOPSIS
    Codex CLI Environment Variables Global File #1

.DESCRIPTION
    This file is automatically generated by Special Software Environment Manager
    Contains environment variable setup and tool startup functionality for Codex CLI

.NOTES
    - Tool Name: Codex CLI Environment Variables
    - Command Prefix: codex
    - PowerShell Command: codex
    - File Number: 1
    - File Name: codex1.ps1
    - Generation Time: 2025-01-27
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Running: codex1.ps1" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

#region Load Environment Variables
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Loading Environment Variables" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Set API Key
$env:OPENAI_API_KEY = "cr_d48129e9dd3f7ed60087a1e52f7246754f23fc49710e7b3c24117aa3a1be9889"

if ($env:OPENAI_API_KEY) {
    Write-Host "[SUCCESS] Loaded OPENAI_API_KEY" -ForegroundColor Green
    Write-Host "OPENAI_API_KEY=$($env:OPENAI_API_KEY)" -ForegroundColor White
} else {
    Write-Host "[WARNING] Failed to load OPENAI_API_KEY" -ForegroundColor Yellow
}

# Set Base URL
$env:OPENAI_BASE_URL = "https://api.fastaicode.top/openai/"

if ($env:OPENAI_BASE_URL) {
    Write-Host "[SUCCESS] Loaded OPENAI_BASE_URL" -ForegroundColor Green
    Write-Host "OPENAI_BASE_URL=$($env:OPENAI_BASE_URL)" -ForegroundColor White
} else {
    Write-Host "[WARNING] Failed to load OPENAI_BASE_URL" -ForegroundColor Yellow
}

#region Build Launch Command Display
$envVarsParts = @()
if ($env:OPENAI_API_KEY) {
    $envVarsParts += "`$env:OPENAI_API_KEY='$($env:OPENAI_API_KEY)'"
}
if ($env:OPENAI_BASE_URL) {
    $envVarsParts += "`$env:OPENAI_BASE_URL='$($env:OPENAI_BASE_URL)'"
}
$envVarsCommand = $envVarsParts -join '; '
if ($envVarsCommand) {
    $fullCommandDisplay = "$envVarsCommand; codex"
} else {
    $fullCommandDisplay = "codex"
}
#endregion

#region Launch Tool
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Press Enter to start Codex CLI Environment Variables..." -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
$null = Read-Host "Press Enter to continue"

Write-Host ""
Write-Host "Executing: codex" -ForegroundColor White
Write-Host ""
Write-Host "PowerShell Command: powershell -NoProfile -ExecutionPolicy Bypass -Command `"$fullCommandDisplay`"" -ForegroundColor White
Write-Host ""
Write-Host "Press any key to continue..." -ForegroundColor Yellow
$null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
powershell -NoProfile -ExecutionPolicy Bypass -Command $fullCommandDisplay

Write-Host ""
pause
#endregion

