# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

<#
.SYNOPSIS
    Codex CLI Global File #1

.DESCRIPTION
    This file is automatically generated by Special Software Environment Manager
    Contains environment variable setup, MCP synchronization and tool startup functionality

.NOTES
    - Tool Name: Codex CLI
    - Command Prefix: codex
    - PowerShell Command: codex --yolo
    - File Number: 1
    - File Name: codex1.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Ensure DISABLE_AUTOUPDATER is set for Claude Code
$env:DISABLE_AUTOUPDATER = "1"
$env:CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = "1"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Running: codex1.ps1" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

#region Upgrade Codex CLI (npm)
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Codex CLI - Upgrade Check" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
$codexUpgradeChoice = Read-Host "Upgrade Codex CLI via 'npm install -g @openai/codex'? (y/N)"
if ($codexUpgradeChoice -eq "y" -or $codexUpgradeChoice -eq "Y") {
    Write-Host "[INFO] Running: npm install -g @openai/codex" -ForegroundColor Cyan
    npm install -g "@openai/codex"
    Write-Host "[SUCCESS] Codex CLI upgrade complete" -ForegroundColor Green
} else {
    Write-Host "[INFO] Skipping Codex CLI upgrade" -ForegroundColor Cyan
}
Write-Host ""
#endregion


#region Initialize Path Variables
$scriptActualPath = $PSCommandPath
$item = Get-Item -LiteralPath $PSCommandPath
if ($item -and $item -is [System.IO.FileInfo] -and $item.LinkType) {
    $scriptActualPath = $item.Target
}
$scriptCurrentPath = Split-Path $scriptActualPath -Parent
if (-not $scriptCurrentPath) {
    $scriptCurrentPath = $PSScriptRoot
    if (-not $scriptCurrentPath) {
        $scriptCurrentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
    }
}
$scriptsDirPath = Split-Path $scriptCurrentPath -Parent
$projectRootPath = Split-Path $scriptsDirPath -Parent
$shellsDirPath = Join-Path $scriptsDirPath "shells"
$winDirPath = Join-Path $shellsDirPath "win"
$winCommonDirPath = Join-Path $winDirPath "win_common"
$pytoolsDirPath = Join-Path $scriptsDirPath "pytools"
$aiToolsDirPath = Join-Path $pytoolsDirPath "ai_tools"
Write-Host "[DEBUG] Script Path: $scriptCurrentPath" -ForegroundColor DarkGray
Write-Host "[DEBUG] Scripts Dir: $scriptsDirPath" -ForegroundColor DarkGray
Write-Host "[DEBUG] Project Root: $projectRootPath" -ForegroundColor DarkGray
#endregion

# Ensure PATH is prepared via WindowsPathFunction script
$windowsPathFunctionScript = Join-Path $winCommonDirPath "WindowsPathFunction.ps1"
. $windowsPathFunctionScript
Set-CoreNodePaths

#region Custom User Directory (Codex1)
# Isolate codex's ~/.codex (config.toml, auth, sessions) per launch slot.
$codexUserBase = "D:\programing\Users"
$codexUserDir = Join-Path $codexUserBase "Codex1"
if (-not (Test-Path $codexUserDir)) {
    New-Item -ItemType Directory -Path $codexUserDir -Force | Out-Null
    Write-Host "[INFO] Created Codex user dir: $codexUserDir" -ForegroundColor Cyan
}
# Explicitly set ALL user-directory env vars so codex + node use this profile.
$env:USERPROFILE = $codexUserDir
$env:HOME = $codexUserDir
$env:USER_HOME = $codexUserDir
$env:HOMEPATH = $codexUserDir
$env:USER_DIR = $codexUserDir
# CODEX_HOME is the ONLY reliable way to relocate codex's config dir (it does
# NOT honor USERPROFILE for ~/.codex on Windows - it reads CODEX_HOME first,
# else the real C:\Users\<user>\.codex which has a stale auth.json + default
# config that overrides this slot's config). Force it to this slot's .codex.
$env:CODEX_HOME = Join-Path $env:USERPROFILE ".codex"
if (-not (Test-Path $env:CODEX_HOME)) {
    New-Item -ItemType Directory -Path $env:CODEX_HOME -Force | Out-Null
}
Write-Host "[INFO] USERPROFILE = $env:USERPROFILE" -ForegroundColor Cyan
Write-Host "[INFO] CODEX_HOME   = $env:CODEX_HOME" -ForegroundColor Cyan
Write-Host "[INFO] Codex home   = $env:CODEX_HOME" -ForegroundColor Cyan
#endregion


#region Load Environment Variables from Secret Files
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Loading Environment Variables" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Secret files directory
$secretDir = Join-Path $projectRootPath ".secret_keys\.secret_ignore"
Write-Host "[DEBUG] Secret directory: $secretDir" -ForegroundColor DarkGray
Write-Host "[DEBUG] Project root: $projectRootPath" -ForegroundColor DarkGray

function Read-SecretFile {
    <#
    .SYNOPSIS
        Reads secret value from file with UTF-8 BOM handling.
    
    .DESCRIPTION
        Enhanced function to read secret files from .secret_keys\.secret_ignore directory.
        Handles UTF-8 BOM, empty lines, and provides detailed error messages.
    
    .PARAMETER FilePath
        Full path to the secret file to read.
    
    .OUTPUTS
        String. The secret value (first non-empty line) or empty string if failed.
    #>
    param(
        [Parameter(Mandatory=$true)]
        [string]$FilePath
    )
    
    $value = ""
    $fixInstruction = "Run dd.cmd (Secret Decryption Fix) to decrypt secret files"
    
    if (-not (Test-Path $FilePath)) {
        Write-Host "[WARNING] Secret file not found: $FilePath" -ForegroundColor Yellow
        Write-Host "[ACTION] $fixInstruction" -ForegroundColor Yellow
        return ""
    }
    
    try {
        # Read file content using System.IO.File for reliable UTF-8 handling
        $bytes = [System.IO.File]::ReadAllBytes($FilePath)
        
        # Check for UTF-8 BOM (EF BB BF) and remove it if present
        if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
            $bytes = $bytes[3..($bytes.Length - 1)]
        }
        
        # Convert bytes to string using UTF-8 encoding
        $content = [System.Text.Encoding]::UTF8.GetString($bytes)
        
        # Get first non-empty line
        $lines = $content -split "`r?`n"
        foreach ($line in $lines) {
            $trimmedLine = $line.Trim()
            if ($trimmedLine) {
                $value = $trimmedLine
                break
            }
        }
    } catch {
        Write-Host "[ERROR] Failed to read secret file: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "[ACTION] $fixInstruction" -ForegroundColor Yellow
        $value = ""
    }
    
    if (-not $value) {
        Write-Host "[WARNING] Secret value is empty or file is empty: $FilePath" -ForegroundColor Yellow
        Write-Host "[ACTION] $fixInstruction" -ForegroundColor Yellow
    }
    
    return $value
}

function Get-SecretValue {
    <#
    .SYNOPSIS
        Gets secret value by key name and sets environment variable.
    
    .DESCRIPTION
        Enhanced function that reads secret from file and provides detailed logging.
        Calls Read-SecretFile for actual file reading.
    
    .PARAMETER KeyName
        Secret key name (filename in .secret_ignore directory).
    
    .OUTPUTS
        String. The secret value or empty string if failed.
    #>
    param([string]$KeyName)
    Write-Host "[DEBUG] Loading secret key: $KeyName" -ForegroundColor DarkGray

    $secretFile = Join-Path $secretDir $KeyName
    Write-Host "[DEBUG] Secret file path: $secretFile" -ForegroundColor DarkGray
    
    # Call enhanced read function
    $value = Read-SecretFile -FilePath $secretFile

    if ($value) {
        Write-Host "[DEBUG] Returned value length: $($value.Length)" -ForegroundColor DarkGray
        Write-Host "[DEBUG] Value: $value" -ForegroundColor DarkGray
    }

    return $value
}

$env:OPENAI_API_KEY = Get-SecretValue "OPENAI_API_KEY_1"
if ($env:OPENAI_API_KEY) {
    Write-Host "[SUCCESS] Loaded OPENAI_API_KEY = $($env:OPENAI_API_KEY)" -ForegroundColor Green
} else {
    Write-Host "[WARNING] Failed to load OPENAI_API_KEY" -ForegroundColor Yellow
}

$env:OPENAI_BASE_URL = Get-SecretValue "OPENAI_BASE_URL_1"
if ($env:OPENAI_BASE_URL) {
    Write-Host "[SUCCESS] Loaded OPENAI_BASE_URL = $($env:OPENAI_BASE_URL)" -ForegroundColor Green
} else {
    Write-Host "[WARNING] Failed to load OPENAI_BASE_URL" -ForegroundColor Yellow
}

$env:CODEX_MODEL = Get-SecretValue "CODEX_MODEL_1"
if ($env:CODEX_MODEL) {
    Write-Host "[SUCCESS] Loaded CODEX_MODEL = $($env:CODEX_MODEL)" -ForegroundColor Green
} else {
    Write-Host "[WARNING] Failed to load CODEX_MODEL" -ForegroundColor Yellow
}



#region Build Launch Command Display
$envVarsParts = @()

if ($env:OPENAI_API_KEY) {
    $envVarsParts += "`$env:OPENAI_API_KEY='$($env:OPENAI_API_KEY)'"
}

if ($env:OPENAI_BASE_URL) {
    $envVarsParts += "`$env:OPENAI_BASE_URL='$($env:OPENAI_BASE_URL)'"
}

if ($env:CODEX_MODEL) {
    $envVarsParts += "`$env:CODEX_MODEL='$($env:CODEX_MODEL)'"
}

$envVarsCommand = $envVarsParts -join '; '
if ($envVarsCommand) {
    $fullCommandDisplay = "$envVarsCommand; codex --yolo"
} else {
    $fullCommandDisplay = "codex --yolo"
}
#endregion



#region Codex Config (py helper -> config.toml + AGENTS.md, wire_api=responses)
$codexConfigHelper = Join-Path $aiToolsDirPath "codex_config_helper.py"
$codexHomeDir = $env:CODEX_HOME
if (-not $codexHomeDir) { $codexHomeDir = Join-Path $env:USERPROFILE ".codex" }
$codexBaseUrl = $env:OPENAI_BASE_URL
$codexModel = $env:CODEX_MODEL
if (-not $codexModel) { $codexModel = "gpt-5-codex" }
if (Test-Path $codexConfigHelper) {
    Write-Host "[INFO] Ensuring Codex config.toml (wire_api=responses, supports_websockets=false, no wss fallback)..." -ForegroundColor Cyan
    python "$codexConfigHelper" --codex-home "$codexHomeDir" --base-url "$codexBaseUrl" --model "$codexModel"
} else {
    Write-Host "[WARN] codex_config_helper.py not found: $codexConfigHelper" -ForegroundColor Yellow
    Write-Host "[WARN] Codex may fall back to the OpenAI WebSocket (401 on non-OpenAI keys)." -ForegroundColor Yellow
}
#endregion


#region MCP Server Synchronization
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "MCP Server Synchronization" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Codex CLI - Pre-Launch Tasks" -ForegroundColor Yellow
Write-Host ""

# Execute pre-launch script if it exists
$preLaunchScript = Join-Path $aiToolsDirPath "codex_pre_launch.ps1"
if (Test-Path $preLaunchScript) {
    $currentWorkingDir = Get-Location
    Write-Host "[INFO] Executing pre-launch script: $preLaunchScript" -ForegroundColor Cyan
    Write-Host "[INFO] Working Directory: $currentWorkingDir" -ForegroundColor Cyan
    Write-Host ""
    & $preLaunchScript -WorkingDirectory "$currentWorkingDir"
    Write-Host ""
}


$syncScript = Join-Path $aiToolsDirPath "codex_sync_mcp_servers.py"
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Syncing MCP Server Configurations (Always Required)" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "[INFO] Executing: python -u `"$syncScript`"" -ForegroundColor Cyan
Write-Host ""

python -u "$syncScript"

if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "[WARNING] MCP synchronization failed" -ForegroundColor Yellow
    Write-Host "[INFO] Continuing anyway..." -ForegroundColor Cyan
} else {
    Write-Host ""
    Write-Host "[SUCCESS] MCP synchronization completed" -ForegroundColor Green
}


#endregion



#region Backup and Restore Check
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Backup and Restore System" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Check if tool command exists
$toolExists = $false
$toolCommand = Get-Command codex -ErrorAction SilentlyContinue
if ($toolCommand) {
    $toolExists = $true
    Write-Host "[OK] Codex AI command found: $($toolCommand.Source)" -ForegroundColor Green
} else {
    Write-Host "[NOT FOUND] Codex AI command not available" -ForegroundColor Red
}

# Backup script path
$backupScript = Join-Path $aiToolsDirPath "ai_tools_backup_restore.py"

if (-not (Test-Path $backupScript)) {
    Write-Host "[WARNING] Backup script not found, skipping backup/restore" -ForegroundColor Yellow
} else {
    if ($toolExists) {
        # Tool exists - offer backup
        Write-Host ""
        Write-Host "[INFO] Codex AI is available" -ForegroundColor Cyan
        Write-Host "[INFO] You can create a backup before running" -ForegroundColor Cyan
        Write-Host ""

        $backupChoice = Read-Host "Create backup of Codex AI? (check existing backups first) (y/N)"
        if ($backupChoice -eq "y" -or $backupChoice -eq "Y") {
            Write-Host ""
            Write-Host "[INFO] Starting backup process..." -ForegroundColor Yellow
            python -u "$backupScript" codex backup
            Write-Host ""
        } else {
            Write-Host "[INFO] Skipping backup" -ForegroundColor Cyan
        }
    } else {
        # Tool not found - offer restore
        Write-Host ""
        Write-Host "[ERROR] Codex AI command not found!" -ForegroundColor Red
        Write-Host "[INFO] You can restore from a previous backup" -ForegroundColor Cyan
        Write-Host ""

        $restoreChoice = Read-Host "Restore Codex AI from backup? (Y/n)"
        if ($restoreChoice -ne "n" -and $restoreChoice -ne "N") {
            Write-Host ""
            Write-Host "[INFO] Listing available backups..." -ForegroundColor Yellow
            python -u "$backupScript" codex list
            Write-Host ""

            $confirmRestore = Read-Host "Proceed with restore from latest backup? (Y/n)"
            if ($confirmRestore -ne "n" -and $confirmRestore -ne "N") {
                Write-Host ""
                Write-Host "[INFO] Starting restore process..." -ForegroundColor Yellow
                python -u "$backupScript" codex restore
                Write-Host ""

                # Re-check if tool exists after restore
                $toolCommand = Get-Command codex -ErrorAction SilentlyContinue
                if ($toolCommand) {
                    Write-Host "[SUCCESS] Codex AI restored successfully!" -ForegroundColor Green
                } else {
                    Write-Host "[WARNING] Restore completed but command still not found" -ForegroundColor Yellow
                    Write-Host "[INFO] You may need to restart your terminal or check PATH" -ForegroundColor Cyan
                }
            } else {
                Write-Host "[INFO] Restore cancelled" -ForegroundColor Cyan
            }
        } else {
            Write-Host "[INFO] Skipping restore" -ForegroundColor Cyan
            Write-Host "[WARNING] Codex AI will not be available" -ForegroundColor Yellow
        }
    }
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
#endregion

# AI Tool Repair and npx Fallback
if (-not (Get-Command codex -ErrorAction SilentlyContinue)) {
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "Tool Not Found - Repair Options Available" -ForegroundColor Yellow
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "[WARNING] Codex AI command not available" -ForegroundColor Yellow
    Write-Host ""
    
    # Code Relationship: Generated scripts -> dd.sh smart permissions (Linux only)
    # Windows scripts detect missing tools and suggest Linux dd.sh for comprehensive repair
    # dd.sh smart_permissions.sh provides full repair functionality on Linux systems
    Write-Host "[SOLUTION] For comprehensive tool repair:" -ForegroundColor Cyan
    Write-Host "  1. Switch to Linux/WSL environment" -ForegroundColor Gray
    Write-Host "  2. Run: sudo $projectRootPath/dd.sh" -ForegroundColor Gray
    Write-Host ""
    Write-Host "[INFO] Linux dd.sh provides:" -ForegroundColor Cyan
    Write-Host "  - AI tools repair from user directories" -ForegroundColor Gray
    Write-Host "  - Package manager reinstallation" -ForegroundColor Gray
    Write-Host "  - Symlink fixing for /usr/local/bin" -ForegroundColor Gray
    Write-Host "  - Permission fixes for all components" -ForegroundColor Gray
    Write-Host ""
    Write-Host "[INFO] On Windows: Using npx fallback (temporary solution)" -ForegroundColor Cyan
    Write-Host ""
}

# Final check and npx fallback
if (-not (Get-Command codex -ErrorAction SilentlyContinue)) {
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "Using npx Fallback (No Installation Required)" -ForegroundColor Yellow
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "[INFO] Running Codex AI via npx (temporary solution)" -ForegroundColor Cyan
    Write-Host "[INFO] For permanent fix: Use Linux environment + dd.sh" -ForegroundColor Cyan
    Write-Host ""

    # Generate npx fallback command
    $envVarsPartsNpx = @()
    if ($env:OPENAI_API_KEY) {
        $envVarsPartsNpx += "`$env:OPENAI_API_KEY='$($env:OPENAI_API_KEY)'"
    }
    if ($env:OPENAI_BASE_URL) {
        $envVarsPartsNpx += "`$env:OPENAI_BASE_URL='$($env:OPENAI_BASE_URL)'"
    }
    if ($env:CODEX_MODEL) {
        $envVarsPartsNpx += "`$env:CODEX_MODEL='$($env:CODEX_MODEL)'"
    }

    $envVarsCommandNpx = $envVarsPartsNpx -join '; '
    if ($envVarsCommandNpx) {
        $fullCommandDisplay = "$envVarsCommandNpx; npx -y @openai/codex"
    } else {
        $fullCommandDisplay = "npx -y @openai/codex"
    }

    Write-Host "[INFO] Using command: $fullCommandDisplay" -ForegroundColor Cyan
    Write-Host ""
}


#region Variable Summary + Single Continue
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Variable Summary" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "OPENAI_API_KEY = $env:OPENAI_API_KEY" -ForegroundColor Gray
Write-Host "OPENAI_BASE_URL = $env:OPENAI_BASE_URL" -ForegroundColor Gray
Write-Host "CODEX_MODEL = $env:CODEX_MODEL" -ForegroundColor Gray
Write-Host "Codex home: $env:USERPROFILE\.codex" -ForegroundColor Gray
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Press Enter to start Codex CLI..." -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
$null = Read-Host "Press Enter to continue"
#endregion

#region Launch Tool
Write-Host ""
Write-Host "Executing: codex --yolo" -ForegroundColor White
powershell -NoProfile -ExecutionPolicy Bypass -Command $fullCommandDisplay
#endregion
