# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

<#
.SYNOPSIS
    Codex CLI Environment Variables Global File #1

.DESCRIPTION
    This file is automatically generated by Special Software Environment Manager
    Contains environment variable setup, MCP synchronization and tool startup functionality

.NOTES
    - Tool Name: Codex CLI Environment Variables
    - Command Prefix: codex
    - PowerShell Command: codex
    - File Number: 1
    - File Name: codex1.ps1
    - Generation Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Running: codex1.ps1" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

#region Load SecretManager
$secretManagerPath = "D:\programing\core_node\scripts\shells\win\win_common\SecretManager.ps1"

if (Test-Path $secretManagerPath) {
    . $secretManagerPath
    Write-Host "[INFO] SecretManager loaded successfully" -ForegroundColor Green
} else {
    Write-Host "[WARNING] SecretManager not found at: $secretManagerPath" -ForegroundColor Yellow
    Write-Host "[WARNING] Environment variables will not be loaded" -ForegroundColor Yellow
}
#endregion

#region Load Environment Variables from SecretManager
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Loading Environment Variables" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
$env:OPENAI_API_KEY = Get-SecretKey -KeyName "OPENAI_API_KEY_1"
if ($env:OPENAI_API_KEY) {
    Write-Host "[SUCCESS] Loaded OPENAI_API_KEY = $($env:OPENAI_API_KEY)" -ForegroundColor Green
} else {
    Write-Host "[WARNING] Failed to load OPENAI_API_KEY" -ForegroundColor Yellow
}
$env:OPENAI_BASE_URL = Get-SecretKey -KeyName "OPENAI_BASE_URL_1"
if ($env:OPENAI_BASE_URL) {
    Write-Host "[SUCCESS] Loaded OPENAI_BASE_URL = $($env:OPENAI_BASE_URL)" -ForegroundColor Green
} else {
    Write-Host "[WARNING] Failed to load OPENAI_BASE_URL" -ForegroundColor Yellow
}

#region Build Launch Command Display
$envVarsParts = @()
if ($env:OPENAI_API_KEY) {
    $envVarsParts += "`$env:OPENAI_API_KEY='$($env:OPENAI_API_KEY)'"
}
if ($env:OPENAI_BASE_URL) {
    $envVarsParts += "`$env:OPENAI_BASE_URL='$($env:OPENAI_BASE_URL)'"
}
$envVarsCommand = $envVarsParts -join '; '
if ($envVarsCommand) {
    $fullCommandDisplay = "$envVarsCommand; codex"
} else {
    $fullCommandDisplay = "codex"
}
#endregion


#region MCP Server Synchronization
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "MCP Server Synchronization" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Codex CLI - Pre-Launch Tasks" -ForegroundColor Yellow
Write-Host ""

# Execute pre-launch script if it exists
if (Test-Path "D:\programing\core_node\scripts\pytools\ai_tools\codex_pre_launch.ps1") {
    $currentWorkingDir = Get-Location
    Write-Host "[INFO] Executing pre-launch script: D:\programing\core_node\scripts\pytools\ai_tools\codex_pre_launch.ps1" -ForegroundColor Cyan
    Write-Host "[INFO] Working Directory: $currentWorkingDir" -ForegroundColor Cyan
    Write-Host ""
    & "D:\programing\core_node\scripts\pytools\ai_tools\codex_pre_launch.ps1" -WorkingDirectory "$currentWorkingDir"
    Write-Host ""
}

Write-Host "Available tasks:" -ForegroundColor White
Write-Host "  [1] Upgrade Codex CLI to latest version (runs in separate window)" -ForegroundColor White
Write-Host "  [2] Sync MCP server configurations (runs now)" -ForegroundColor White
Write-Host ""

$upgradeChoice = Read-Host "Do you want to upgrade Codex CLI? (y/N)"
if ($upgradeChoice -eq "y" -or $upgradeChoice -eq "Y") {
    Write-Host ""
    Write-Host "[INFO] Launching Codex CLI upgrade in separate window..." -ForegroundColor Yellow
    Start-Process -FilePath "D:\programing\core_node\scripts\pytools\ai_tools\codex_update.bat" -WindowStyle Normal
    Write-Host "[SUCCESS] Upgrade window opened" -ForegroundColor Green
} else {
    Write-Host "[INFO] Skipping upgrade" -ForegroundColor Cyan
}

Write-Host ""
Write-Host "Syncing MCP Server Configurations..." -ForegroundColor Yellow
Write-Host ""
Write-Host "[INFO] Executing: python codex_sync_mcp_servers.py" -ForegroundColor Cyan
Write-Host ""

python "D:\programing\core_node\scripts\pytools\ai_tools\codex_sync_mcp_servers.py"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Press Enter to start Codex CLI..." -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
$null = Read-Host "Press Enter to continue"
#endregion


#region Launch Tool
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Press Enter to start Codex CLI Environment Variables..." -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
$null = Read-Host "Press Enter to continue"

Write-Host ""
Write-Host "Executing: codex" -ForegroundColor White
Write-Host ""
Write-Host "PowerShell Command: powershell -NoProfile -ExecutionPolicy Bypass -Command `"$fullCommandDisplay`"" -ForegroundColor White
Write-Host ""
Write-Host "Press any key to continue..." -ForegroundColor Yellow
$null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
powershell -NoProfile -ExecutionPolicy Bypass -Command $fullCommandDisplay

Write-Host ""
pause
#endregion
