# =============================================================================
# Kimi Code CLI Launch Script #1 [Kimi For Coding]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Flow: isolate profile (D:\.tmp\Users\Kimi1) -> load secrets
#   -> pnpm upgrade prompt [y/N] -> model selection [1-4] (default 1, 5s timeout)
#   -> kimi provider catalog add kimi-for-coding (non-interactive provider setup)
#   -> config.toml default_permission_mode = "auto" (no approve prompts)
#   -> Chrome MCP service ensure (idempotent) + MCP config registration
#   -> launch kimi --auto.
# Secrets: KIMI_API_KEY_1 (required),
#   KIMI_BASE_URL_1 (optional --base-url override).

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptPath = $null
$scriptsDirPath = $null
$coreNodePath = $null
$shellsWinPath = $null
$winCommonDirPath = $null
$windowsPathFunctionScript = $null
$serviceContractScript = $null
$kimiUserBaseDirPath = "D:\.tmp\Users"
$kimiUserDirPath = $null
$kimiSecretDirPath = $null
$kimiApiKeySecretPath = $null
$kimiBaseUrlSecretPath = $null
$kimiApiKey = ""
$kimiBaseUrl = ""
$kimiCodeHomeCandidatePath = $null
$kimiCodeHomePath = $null
$kimiConfigTomlPath = $null
$kimiMcpConfigPath = $null
$permissionLine = 'default_permission_mode = "auto"'
$permissionFound = $false
$configLines = @()
$configLineIndex = 0
$utf8Encoding = $null
$mcpChromeHost = $null
$mcpChromeUrl = $null
$mcpChromePort = 0
$mcpConfig = $null
$mcpServersProperty = $null
$mcpServers = $null
$chromeMcpConfig = $null
$chromeMcpProperty = $null
$mcpJson = $null
$modelPick = $null
$modelDeadline = $null
$modelKey = $null
$aiCliProvisionCommonScript = $null
$kimiCommand = $null
$kimiModel = "k3-256k"
$kimiModelLabel = "kimi k3 256K"
$providerArgs = @()
$providerExitCode = 0
$kimiArgs = @("--auto")
$displayArgs = $null

$scriptPath = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($scriptPath)) {
    $scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
}
$scriptsDirPath = Split-Path $scriptPath -Parent
$coreNodePath = Split-Path $scriptsDirPath -Parent
$shellsWinPath = Join-Path $scriptsDirPath "shells"
$shellsWinPath = Join-Path $shellsWinPath "win"
$winCommonDirPath = Join-Path $shellsWinPath "win_common"
$windowsPathFunctionScript = Join-Path $winCommonDirPath "WindowsPathFunction.ps1"
$serviceContractScript = Join-Path $winCommonDirPath "ServiceContract.ps1"
. $windowsPathFunctionScript
. $serviceContractScript
Set-CoreNodePaths

$mcpChromeHost = Get-ServiceContractHost -Name "loopback"
$mcpChromePort = Get-ServiceContractPort -Name "mcp_chrome"
$mcpChromeUrl = New-ServiceContractUrl -Protocol "http" -HostName $mcpChromeHost -Port $mcpChromePort -Path "mcp"

# Isolated per-slot user profile: D:\.tmp\Users\Kimi1
$kimiUserDirPath = Join-Path $kimiUserBaseDirPath "Kimi1"
if (-not (Test-Path -LiteralPath $kimiUserDirPath)) {
    New-Item -ItemType Directory -Path $kimiUserDirPath -Force | Out-Null
}
$env:USERPROFILE = $kimiUserDirPath
$env:HOME = $kimiUserDirPath
$env:USER_HOME = $kimiUserDirPath
$env:HOMEPATH = $kimiUserDirPath
$env:USER_DIR = $kimiUserDirPath
Write-Host "[INFO] User Profile: $kimiUserDirPath" -ForegroundColor White

if ([string]::IsNullOrWhiteSpace($env:KIMI_CODE_HOME)) {
    $kimiCodeHomeCandidatePath = Join-Path $kimiUserDirPath ".kimi-code"
} elseif ([System.IO.Path]::IsPathRooted($env:KIMI_CODE_HOME)) {
    $kimiCodeHomeCandidatePath = $env:KIMI_CODE_HOME
} else {
    $kimiCodeHomeCandidatePath = Join-Path (Get-Location).Path $env:KIMI_CODE_HOME
}
if (-not (Test-Path -LiteralPath $kimiCodeHomeCandidatePath)) {
    New-Item -ItemType Directory -Path $kimiCodeHomeCandidatePath -Force | Out-Null
}
$kimiCodeHomePath = (Resolve-Path -LiteralPath $kimiCodeHomeCandidatePath).Path
$kimiConfigTomlPath = Join-Path $kimiCodeHomePath "config.toml"
$kimiMcpConfigPath = Join-Path $kimiCodeHomePath "mcp.json"

$kimiSecretDirPath = Join-Path $coreNodePath ".secret_keys"
$kimiSecretDirPath = Join-Path $kimiSecretDirPath ".secret_ignore"
$kimiApiKeySecretPath = Join-Path $kimiSecretDirPath "KIMI_API_KEY_1"
$kimiBaseUrlSecretPath = Join-Path $kimiSecretDirPath "KIMI_BASE_URL_1"

function Read-KimiSecretFile {
    param([string]$FilePath)
    $value = ""
    if (-not (Test-Path -LiteralPath $FilePath)) {
        return $value
    }
    try {
        $bytes = [System.IO.File]::ReadAllBytes($FilePath)
        if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
            $bytes = $bytes[3..($bytes.Length - 1)]
        }
        $content = [System.Text.Encoding]::UTF8.GetString($bytes)
        foreach ($line in ($content -split "`r?`n")) {
            $trimmedLine = $line.Trim()
            if ($trimmedLine) {
                $value = $trimmedLine
                break
            }
        }
    } catch {
        $value = ""
    }
    return $value
}

$kimiApiKey = Read-KimiSecretFile -FilePath $kimiApiKeySecretPath
$kimiBaseUrl = Read-KimiSecretFile -FilePath $kimiBaseUrlSecretPath

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "kimi1.ps1" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan

$kimiCommand = Get-Command kimi -ErrorAction SilentlyContinue
if ($null -eq $kimiCommand) {
    throw "kimi is not available on PATH."
}

# Shared launcher helpers (scripts/shells/win/win_common/AiCliProvisionCommon.ps1):
# masked secret display, and the version check + optional upgrade, which prompts
# only when a newer version is published, defaults to N and auto-skips after 5 seconds.
$aiCliProvisionCommonScript = Join-Path $winCommonDirPath "AiCliProvisionCommon.ps1"
. $aiCliProvisionCommonScript

Write-Host "[INFO] KIMI_API_KEY_1: $(Get-AiCliMaskedSecret -Value $kimiApiKey)" -ForegroundColor White
Write-Host "[INFO] KIMI_BASE_URL_1: $(if ([string]::IsNullOrWhiteSpace($kimiBaseUrl)) { "[empty]" } else { $kimiBaseUrl })" -ForegroundColor White
if ([string]::IsNullOrWhiteSpace($kimiApiKey)) {
    Write-Host "[WARN] KIMI_API_KEY_1 is empty; provider setup will fail." -ForegroundColor Yellow
}

Invoke-AiCliUpgradePrompt -Tool "kimi"

# Model selection (default 1 = kimi k3 256K / k3-256k; auto-selects after 5s).
Write-Host "Select model (default 1 = kimi k3 256K / k3-256k; auto-select in 5 seconds):" -ForegroundColor Yellow
Write-Host "  [1] kimi k3 256K (k3-256k)" -ForegroundColor White
Write-Host "  [2] kimi k3 1M (k3)" -ForegroundColor White
Write-Host "  [3] kimi2.8 preview (kimi-for-coding, 1M)" -ForegroundColor White
Write-Host "  [4] kimi2.7 code highspeed (kimi-for-coding-highspeed, 256K)" -ForegroundColor White
Write-Host "Model number [1-4] (Enter or timeout = 1): " -ForegroundColor Yellow -NoNewline
$modelDeadline = (Get-Date).AddSeconds(5)
while ((Get-Date) -lt $modelDeadline) {
    if ([Console]::KeyAvailable) {
        $modelKey = [Console]::ReadKey($true)
        if ($modelKey.Key -ne [ConsoleKey]::Enter) {
            $modelPick = [string]$modelKey.KeyChar
            Write-Host $modelPick
        }
        break
    }
    Start-Sleep -Milliseconds 100
}
while ([Console]::KeyAvailable) {
    [Console]::ReadKey($true) | Out-Null
}
if ([string]::IsNullOrWhiteSpace($modelPick)) {
    Write-Host "1 (auto)"
}
switch ($modelPick) {
    "2" { $kimiModel = "k3"; $kimiModelLabel = "kimi k3 1M" }
    "3" { $kimiModel = "kimi-for-coding"; $kimiModelLabel = "kimi2.8 preview" }
    "4" { $kimiModel = "kimi-for-coding-highspeed"; $kimiModelLabel = "kimi2.7 code highspeed" }
    default { $kimiModel = "k3-256k"; $kimiModelLabel = "kimi k3 256K" }
}
Write-Host "[INFO] Model: $kimiModelLabel ($kimiModel)" -ForegroundColor White

# Non-interactive provider setup (official kimi provider command).
if (-not [string]::IsNullOrWhiteSpace($kimiApiKey)) {
    $providerArgs = @("provider", "catalog", "add", "kimi-for-coding", "--api-key", $kimiApiKey, "--default-model", $kimiModel)
    if (-not [string]::IsNullOrWhiteSpace($kimiBaseUrl)) {
        $providerArgs += @("--base-url", $kimiBaseUrl)
    }
    & $kimiCommand.Source @providerArgs
    $providerExitCode = $LASTEXITCODE
    if ($providerExitCode -ne 0) {
        Write-Host "[WARN] Automatic provider setup failed (exit $providerExitCode)." -ForegroundColor Yellow
        Write-Host "[INFO] Manual setup: run kimi, type /provider, choose Known third-party -> Kimi For Coding," -ForegroundColor White
        Write-Host "[INFO]   and paste this key: $kimiApiKey" -ForegroundColor White
    } else {
        Write-Host "[INFO] Provider kimi-for-coding configured (default model: $kimiModel)." -ForegroundColor Green
    }
} else {
    Write-Host "[INFO] Manual setup: run kimi, type /provider, choose Known third-party -> Kimi For Coding," -ForegroundColor White
    Write-Host "[INFO]   and paste the key saved via the environment manager." -ForegroundColor White
}

# Permission mode: Never Ask (disables "Approve once" prompts) by default.
$utf8Encoding = New-Object System.Text.UTF8Encoding($false)
if (Test-Path -LiteralPath $kimiConfigTomlPath) {
    $configLines = [System.IO.File]::ReadAllLines($kimiConfigTomlPath)
    $permissionFound = $false
    for ($configLineIndex = 0; $configLineIndex -lt $configLines.Count; $configLineIndex++) {
        if ($configLines[$configLineIndex] -match '^\s*default_permission_mode\s*=') {
            $configLines[$configLineIndex] = $permissionLine
            $permissionFound = $true
            break
        }
    }
    if (-not $permissionFound) {
        $configLines = @($permissionLine) + $configLines
    }
    [System.IO.File]::WriteAllLines($kimiConfigTomlPath, [string[]]$configLines, $utf8Encoding)
} else {
    [System.IO.File]::WriteAllText($kimiConfigTomlPath, $permissionLine + "`r`n", $utf8Encoding)
}
Write-Host "[INFO] Permission mode: auto (Never Ask; approve prompts disabled) in $kimiConfigTomlPath" -ForegroundColor Green

# Chrome MCP (apps/mcp-chrome): idempotent background service, then slot MCP registration.
Invoke-AiCliChromeServiceEnsure

if (Test-Path -LiteralPath $kimiMcpConfigPath) {
    $mcpConfig = Get-Content -Raw -LiteralPath $kimiMcpConfigPath | ConvertFrom-Json
} else {
    $mcpConfig = [PSCustomObject]@{}
}
if ($null -eq $mcpConfig) {
    $mcpConfig = [PSCustomObject]@{}
}
$mcpServersProperty = $mcpConfig.PSObject.Properties["mcpServers"]
if ($null -eq $mcpServersProperty) {
    $mcpServers = [PSCustomObject]@{}
    $mcpConfig | Add-Member -MemberType NoteProperty -Name "mcpServers" -Value $mcpServers
} elseif ($null -eq $mcpServersProperty.Value) {
    $mcpServers = [PSCustomObject]@{}
    $mcpServersProperty.Value = $mcpServers
} else {
    $mcpServers = $mcpServersProperty.Value
}
$chromeMcpConfig = [PSCustomObject]@{
    url = $mcpChromeUrl
}
$chromeMcpProperty = $mcpServers.PSObject.Properties["chrome"]
if ($null -eq $chromeMcpProperty) {
    $mcpServers | Add-Member -MemberType NoteProperty -Name "chrome" -Value $chromeMcpConfig
} else {
    $chromeMcpProperty.Value = $chromeMcpConfig
}
$mcpJson = $mcpConfig | ConvertTo-Json -Depth 20
[System.IO.File]::WriteAllText($kimiMcpConfigPath, $mcpJson, $utf8Encoding)
Write-Host "[INFO] Chrome MCP registered in Kimi Code: $kimiMcpConfigPath" -ForegroundColor Green


$displayArgs = if ($args.Count -gt 0) {
    [string]::Format("; extra args: {0}", ($args -join " "))
} else {
    ""
}

Write-Host "[INFO] Launch: kimi --auto (Never Ask mode; provider kimi-for-coding, model $kimiModel)$displayArgs" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

& $kimiCommand.Source @kimiArgs @args
