<#
.SYNOPSIS
    SSH Connection Global File #3

.DESCRIPTION
    This file is automatically generated by Special Software Environment Manager
    Contains SSH connection setup with encrypted password storage

.NOTES
    - Configuration: SSH Connection
    - SSH Connection: Loaded dynamically from secret key SSH_CONNECTION_3
    - File Number: 3
    - File Name: ssh3.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Running: ssh3.ps1" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

#region Initialize Path Variables
$scriptActualPath = $PSCommandPath
$item = Get-Item -LiteralPath $PSCommandPath
if ($item -and $item -is [System.IO.FileInfo] -and $item.LinkType) {
    $scriptActualPath = $item.Target
}
$scriptCurrentPath = Split-Path $scriptActualPath -Parent
if (-not $scriptCurrentPath) {
    $scriptCurrentPath = $PSScriptRoot
    if (-not $scriptCurrentPath) {
        $scriptCurrentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
    }
}
$scriptsDirPath = Split-Path $scriptCurrentPath -Parent
$projectRootPath = Split-Path $scriptsDirPath -Parent
$shellsDirPath = Join-Path $scriptsDirPath "shells"
$winDirPath = Join-Path $shellsDirPath "win"
$winCommonDirPath = Join-Path $winDirPath "win_common"
Write-Host "[DEBUG] Script Path: $scriptCurrentPath" -ForegroundColor DarkGray
Write-Host "[DEBUG] Scripts Dir: $scriptsDirPath" -ForegroundColor DarkGray
Write-Host "[DEBUG] Project Root: $projectRootPath" -ForegroundColor DarkGray
#endregion

$windowsPathFunctionScript = Join-Path $winCommonDirPath "WindowsPathFunction.ps1"
. $windowsPathFunctionScript
Set-CoreNodePaths

#region Load SSH Configuration via PyCore caller
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Loading SSH Configuration" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Ensure GlobalVars loaded: Read-SecretValue (node secret_crypto.js read) and SECRET_CRYPTO_JS
$globalVarsPath = Join-Path $winCommonDirPath "GlobalVars.ps1"
. $globalVarsPath

$fixScriptPath = Join-Path $winCommonDirPath "SecretDecryptionCheck.ps1"
$fixInstruction = "Run dd.cmd (Secret Decryption Fix) or powershell -ExecutionPolicy Bypass -File `"$fixScriptPath`""
Write-Host "[DEBUG] Secret reader: $Global:SECRET_CRYPTO_JS read" -ForegroundColor DarkGray
Write-Host "[DEBUG] Project root: $projectRootPath" -ForegroundColor DarkGray
function Get-SSHSecret {
    param([string]$KeyName)
    $result = ""
    Write-Host "[DEBUG] Loading SSH secret key: $KeyName" -ForegroundColor DarkGray

    $result = Read-SecretValue -Name $KeyName
    if (-not $result) {
        Write-Host "[WARNING] Secret reader failed for $KeyName" -ForegroundColor Yellow
        Write-Host "[ACTION] $fixInstruction" -ForegroundColor Yellow
        return ""
    }
    return $result
}

$sshConnection = Get-SSHSecret "SSH_CONNECTION_3"
if ($sshConnection) {
    Write-Host "[SUCCESS] SSH Connection loaded = $sshConnection" -ForegroundColor Green
} else {
    Write-Host "[ERROR] SSH_CONNECTION not found" -ForegroundColor Red
    Write-Host "Press any key to exit..." -ForegroundColor Yellow
    $null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}

$sshPassword = Get-SSHSecret "SSH_PASSWORD_3"
if ($sshPassword) {
    Write-Host "[SUCCESS] SSH password loaded ($($sshPassword.Length) chars; displayed only when a password login is needed)" -ForegroundColor Green
} else {
    Write-Host "[INFO] No password configured (using SSH key authentication)" -ForegroundColor Yellow
}
#endregion

#region Execute SSH Connection
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Connecting to SSH Server" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

if ([string]::IsNullOrWhiteSpace($sshConnection)) {
    Write-Host "[ERROR] SSH connection string is empty" -ForegroundColor Red
    Write-Host "Press any key to exit..." -ForegroundColor Yellow
    $null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}

if ($sshPassword) {
    # Extract user and host from connection string (e.g. root@1.2.3.4)
    $sshUser = ""
    $sshHost = ""
    if ($sshConnection -match '^(.+)@(.+)$') {
        $sshUser = $Matches[1]
        $sshHost = $Matches[2]
    }

    # SSH Key setup guide
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "  SSH Key Setup Guide (passwordless login)" -ForegroundColor Cyan
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  After login, run these commands on the SERVER to enable" -ForegroundColor White
    Write-Host "  SSH key authentication (no password next time):" -ForegroundColor White
    Write-Host ""
    Write-Host "  --- Step 1: Generate key on LOCAL machine (if not exists) ---" -ForegroundColor Yellow
    Write-Host ""
    $localKeyPath = Join-Path $env:USERPROFILE ".ssh\id_ed25519"
    $localPubPath = "$localKeyPath.pub"
    Write-Host "  # Check if key already exists:" -ForegroundColor DarkGray
    Write-Host "  if (!(Test-Path `"$localPubPath`")) { ssh-keygen -t ed25519 -f `"$localKeyPath`" -N `"`" }" -ForegroundColor Green
    Write-Host ""
    Write-Host "  --- Step 2: Copy key to server (run on LOCAL) ---" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  # Option A: One-liner (works on all distros):" -ForegroundColor DarkGray
    Write-Host "  type `"$localPubPath`" | ssh $sshConnection `"mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys`"" -ForegroundColor Green
    Write-Host ""
    Write-Host "  # Option B: If ssh-copy-id is available (Git Bash / WSL):" -ForegroundColor DarkGray
    Write-Host "  ssh-copy-id -i `"$localPubPath`" $sshConnection" -ForegroundColor Green
    Write-Host ""
    Write-Host "  --- Step 3: Verify (run on LOCAL) ---" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  ssh $sshConnection `"echo 'SSH key auth OK'`"" -ForegroundColor Green
    Write-Host ""
    Write-Host "  --- Notes ---" -ForegroundColor Yellow
    Write-Host "  * Works on Debian/Ubuntu/CentOS/RHEL/AlmaLinux/Fedora" -ForegroundColor DarkGray
    Write-Host "  * Safe if server already has other keys (appends, not overwrites)" -ForegroundColor DarkGray
    Write-Host "  * Safe if local machine has other keys (ed25519 is separate from rsa)" -ForegroundColor DarkGray
    Write-Host "  * If server has SELinux: ssh $sshConnection `"restorecon -Rv ~/.ssh`"" -ForegroundColor DarkGray
    Write-Host "  * If using custom port: ssh -p PORT $sshConnection" -ForegroundColor DarkGray
    Write-Host ""

    # Display password for copy-paste
    Write-Host "============================================================" -ForegroundColor Yellow
    Write-Host "  SSH PASSWORD (Copy this to clipboard):" -ForegroundColor Yellow
    Write-Host "  $sshPassword" -ForegroundColor Green
    Write-Host "============================================================" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "[INFO] SSH will prompt for password. Please paste the password above when prompted." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Executing: ssh $sshConnection" -ForegroundColor White
    Write-Host ""

    # Execute SSH connection - it will prompt for password
    & ssh $sshConnection
} else {
    # No password configured, use SSH key authentication
    Write-Host "[INFO] No password configured, using SSH key authentication" -ForegroundColor Cyan
    Write-Host "Executing: ssh $sshConnection" -ForegroundColor White
    Write-Host ""

    & ssh $sshConnection
}

Write-Host ""
Write-Host "SSH session ended" -ForegroundColor Cyan
Write-Host ""
Write-Host "Press any key to exit..." -ForegroundColor Yellow
$null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
#endregion
