# -*- coding: utf-8 -*-
"""Interface a Laravel worker composer offers to its components."""

from typing import Any, Dict, List, Protocol


class LaravelWorkerHost(Protocol):
    worker_id: str
    worker_name: str
    PULL_LIMIT: int
    WORKER_ID_PREFIX: str
    compute_identity: Dict[str, Any]

    @property
    def log_prefix(self) -> str: ...

    def active_base_url(self) -> str: ...

    def identity_params(self) -> Dict[str, Any]: ...

    def offer_params(self) -> Dict[str, Any]: ...

    def pull_task_types(self) -> List[str]: ...

    def full_sync_enabled(self) -> bool: ...

    def lane_halt_requested(self) -> bool: ...

    def inflight_count(self) -> int: ...

    def dispatch_headroom(self) -> int: ...

    def results_blocked(self) -> bool: ...

    def pending_result_task_ids(self, task_ids: List[str]) -> List[str]: ...

    def run_pull_cycle(self, prefer_remote: bool = False) -> Dict[str, Any]: ...

    def accept_task(self, task: Dict[str, Any], base_url: str = "", allow_backlog: bool = False) -> Dict[str, Any]: ...

    def laravel_online(self, base_url: str) -> None: ...

    def registration_renewed(self) -> None: ...

    def apply_local_queue_order(self, task_type: str, ordered_ids: List[str]) -> None: ...
