#!/usr/bin/env python3
"""
SystemD Service File Generator
Handles generation of systemd service files and wrapper scripts
"""

import os
from pathlib import Path
from typing import Optional, Dict, List, Tuple


class ServiceFileGenerator:
    """Generates systemd service files and wrapper scripts"""

    def __init__(self, wrapper_script_dir: str = "/var/_core_node/unified_manager/temp_scripts"):
        self.wrapper_script_dir = Path(wrapper_script_dir)
        self.service_file_dir = Path("/etc/systemd/system")

    def ensure_wrapper_dir(self) -> None:
        """Ensure wrapper script directory exists"""
        self.wrapper_script_dir.mkdir(parents=True, exist_ok=True)

    def generate_wrapper_script(
        self,
        service_name: str,
        execute_command: str,
        working_directory: Optional[str] = None,
        environment_vars: Optional[str] = None,
        is_build_service: bool = False
    ) -> str:
        """
        Generate wrapper script for systemd service
        No compound commands - all commands are separate lines in the script
        Returns: path to wrapper script
        """
        self.ensure_wrapper_dir()

        wrapper_script_path = self.wrapper_script_dir / f"{service_name}.sh"

        # Build script content line by line
        lines = ["#!/bin/bash", "set -e", ""]

        if is_build_service:
            lines.append("echo \"Starting built application...\"")
            if working_directory:
                lines.append(f"echo \"Working directory: {working_directory}\"")
            lines.append(f"echo \"Command: {execute_command}\"")
            lines.append("echo \"\"")
            lines.append("")

            # Change to working directory if specified
            if working_directory:
                lines.append(f"cd \"{working_directory}\"")
                lines.append("")

            # Export environment variables if specified
            if environment_vars:
                lines.append(f"export {environment_vars}")
                lines.append("")

            # Execute command directly (no exec with compound commands)
            lines.append(f"{execute_command}")
        else:
            # Dev service wrapper
            lines.append("echo \"Starting development application...\"")
            if working_directory:
                lines.append(f"echo \"Working directory: {working_directory}\"")
            lines.append(f"echo \"Command: {execute_command}\"")
            lines.append("echo \"\"")
            lines.append("")

            # Change to working directory if specified
            if working_directory:
                lines.append(f"cd \"{working_directory}\"")
                lines.append("")

            # Export environment variables if specified
            if environment_vars:
                lines.append(f"export {environment_vars}")
                lines.append("")

            # Execute command directly
            lines.append(f"exec {execute_command}")

        content = "\n".join(lines) + "\n"

        # Write wrapper script
        wrapper_script_path.write_text(content, encoding='utf-8')

        # Make executable
        os.chmod(wrapper_script_path, 0o755)

        return str(wrapper_script_path)

    def generate_service_file_content(
        self,
        service_name: str,
        description: str,
        wrapper_script_path: str,
        working_directory: str,
        user: str = "root",
        cpu_quota: str = "50%",
        memory_max: str = "1G"
    ) -> str:
        """
        Generate systemd service file content (as string, not written to disk)
        Returns: service file content as string
        """
        content = f"""[Unit]
Description={description}
After=network.target

[Service]
Type=simple
User={user}
WorkingDirectory={working_directory}
ExecStart={wrapper_script_path}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
CPUQuota={cpu_quota}
MemoryMax={memory_max}
MemoryHigh=0M

[Install]
WantedBy=multi-user.target
"""
        return content

    def create_build_service(
        self,
        app_name: str,
        app_path: str,
        framework_type: str,
        execute_command: str,
        working_directory: Optional[str] = None,
        environment_vars: Optional[str] = None,
        service_suffix: str = "-build"
    ) -> Tuple[bool, str, str, str]:
        """
        Create build service (wrapper script + generate service file content)
        Returns: (success, service_name, wrapper_script_path, service_file_content)
        """
        try:
            service_name = f"webapp-{app_name}{service_suffix}"
            description = f"{app_name}{service_suffix} ({framework_type}) - Auto-generated by Unified Manager"

            # Generate wrapper script (can be written without sudo)
            wrapper_script_path = self.generate_wrapper_script(
                service_name=service_name,
                execute_command=execute_command,
                working_directory=working_directory,
                environment_vars=environment_vars,
                is_build_service=True
            )

            # Generate service file content (Shell will write it with sudo)
            service_file_content = self.generate_service_file_content(
                service_name=service_name,
                description=description,
                wrapper_script_path=wrapper_script_path,
                working_directory=app_path
            )

            return True, service_name, wrapper_script_path, service_file_content

        except Exception as e:
            return False, "", "", f"Failed to create build service: {str(e)}"

    def create_dev_service(
        self,
        app_name: str,
        app_path: str,
        framework_type: str,
        execute_command: str
    ) -> Tuple[bool, str, str]:
        """
        Create dev service (wrapper script + systemd service file)
        Returns: (success, service_name, message)
        """
        try:
            service_name = f"webapp-{app_name}"
            description = f"{app_name} ({framework_type}) - Auto-generated by Unified Manager"

            # Generate wrapper script
            wrapper_script_path = self.generate_wrapper_script(
                service_name=service_name,
                execute_command=execute_command,
                working_directory=app_path,
                is_build_service=False
            )

            # Generate service file
            service_file_path = self.generate_service_file(
                service_name=service_name,
                description=description,
                wrapper_script_path=wrapper_script_path,
                working_directory=app_path
            )

            return True, service_name, f"Dev service files created: {service_file_path}"

        except Exception as e:
            return False, "", f"Failed to create dev service: {str(e)}"

    def get_service_patterns_to_remove(
        self,
        app_name: str,
        is_build_service: bool
    ) -> List[str]:
        """
        Get list of service names to remove for mutual exclusion
        If creating build service, return normal service patterns
        If creating normal service, return build service patterns
        """
        patterns = ["webapp", "nuxt", "laravel", "flutter", "app"]
        service_names = []

        if is_build_service:
            # Creating build service - remove normal services
            for pattern in patterns:
                service_names.append(f"{pattern}-{app_name}")
        else:
            # Creating normal service - remove build services
            for pattern in patterns:
                service_names.append(f"{pattern}-{app_name}-build")

        return service_names

    def remove_wrapper_script(self, service_name: str) -> bool:
        """Remove wrapper script for a service"""
        wrapper_script_path = self.wrapper_script_dir / f"{service_name}.sh"
        if wrapper_script_path.exists():
            wrapper_script_path.unlink()
            return True
        return False


__all__ = ['ServiceFileGenerator']
