import 'localization_keys_app_codemart.dart';

final Map<String, String> enAppCodemart = {
  LocalizationKeysAppCodemart.codemartAppName: 'CodeMart',
  LocalizationKeysAppCodemart.codemartWelcome: 'Welcome to CodeMart',
  LocalizationKeysAppCodemart.codemartLogin: 'Login',
  LocalizationKeysAppCodemart.codemartRegister: 'Register',
  LocalizationKeysAppCodemart.codemartLogout: 'Logout',
  LocalizationKeysAppCodemart.codemartEmail: 'Email',
  LocalizationKeysAppCodemart.codemartPassword: 'Password',
  LocalizationKeysAppCodemart.codemartUsername: 'Username',
  LocalizationKeysAppCodemart.codemartName: 'Name',
  LocalizationKeysAppCodemart.codemartProfile: 'Profile',
  LocalizationKeysAppCodemart.codemartSettings: 'Settings',
  LocalizationKeysAppCodemart.codemartDeveloper: 'Developer',
  LocalizationKeysAppCodemart.codemartClient: 'Client',
  LocalizationKeysAppCodemart.codemartArchitect: 'Architect',
  LocalizationKeysAppCodemart.codemartReviewer: 'Reviewer',
  LocalizationKeysAppCodemart.codemartRegisterAsDeveloper: 'Register as Developer',
  LocalizationKeysAppCodemart.codemartRegisterAsClient: 'Register as Client',
  LocalizationKeysAppCodemart.codemartEmailVerification: 'Email Verification',
  LocalizationKeysAppCodemart.codemartPhoneVerification: 'Phone Verification',
  LocalizationKeysAppCodemart.codemartKycVerification: 'KYC Verification',
  LocalizationKeysAppCodemart.codemartPaymentDeposit: 'Payment Deposit',
  LocalizationKeysAppCodemart.codemartVerificationComplete: 'Verification Complete',
  LocalizationKeysAppCodemart.codemartProjects: 'Projects',
  LocalizationKeysAppCodemart.codemartCreateProject: 'Create Project',
  LocalizationKeysAppCodemart.codemartProjectTitle: 'Project Title',
  LocalizationKeysAppCodemart.codemartProjectDescription: 'Project Description',
  LocalizationKeysAppCodemart.codemartProjectBudget: 'Budget',
  LocalizationKeysAppCodemart.codemartProjectStatus: 'Status',
  LocalizationKeysAppCodemart.codemartProjectComplexity: 'Complexity',
  LocalizationKeysAppCodemart.codemartProjectStartDate: 'Start Date',
  LocalizationKeysAppCodemart.codemartProjectEndDate: 'End Date',
  LocalizationKeysAppCodemart.codemartProjectSkills: 'Required Skills',
  LocalizationKeysAppCodemart.codemartTasks: 'Tasks',
  LocalizationKeysAppCodemart.codemartTaskHall: 'Task Hall',
  LocalizationKeysAppCodemart.codemartTaskTitle: 'Task Title',
  LocalizationKeysAppCodemart.codemartTaskDescription: 'Task Description',
  LocalizationKeysAppCodemart.codemartTaskStatus: 'Task Status',
  LocalizationKeysAppCodemart.codemartTaskPriority: 'Priority',
  LocalizationKeysAppCodemart.codemartAcceptTask: 'Accept Task',
  LocalizationKeysAppCodemart.codemartSubmitTask: 'Submit Task',
  LocalizationKeysAppCodemart.codemartPayments: 'Payments',
  LocalizationKeysAppCodemart.codemartWallet: 'Wallet',
  LocalizationKeysAppCodemart.codemartBalance: 'Balance',
  LocalizationKeysAppCodemart.codemartEarnings: 'Earnings',
  LocalizationKeysAppCodemart.codemartTransactions: 'Transactions',
  LocalizationKeysAppCodemart.codemartSubmit: 'Submit',
  LocalizationKeysAppCodemart.codemartCancel: 'Cancel',
  LocalizationKeysAppCodemart.codemartConfirm: 'Confirm',
  LocalizationKeysAppCodemart.codemartSave: 'Save',
  LocalizationKeysAppCodemart.codemartEdit: 'Edit',
  LocalizationKeysAppCodemart.codemartDelete: 'Delete',
  LocalizationKeysAppCodemart.codemartBack: 'Back',
  LocalizationKeysAppCodemart.codemartNext: 'Next',
  LocalizationKeysAppCodemart.codemartPrevious: 'Previous',
  LocalizationKeysAppCodemart.codemartFinish: 'Finish',
  LocalizationKeysAppCodemart.codemartLoading: 'Loading...',
  LocalizationKeysAppCodemart.codemartError: 'Error',
  LocalizationKeysAppCodemart.codemartSuccess: 'Success',
  LocalizationKeysAppCodemart.codemartNoData: 'No Data',

  // Language Settings
  LocalizationKeysAppCodemart.codemartLanguageSettings: 'Language Settings',
  LocalizationKeysAppCodemart.codemartLanguageRestartMessage: 'The app will restart after changing language',
  LocalizationKeysAppCodemart.codemartApplyLanguage: 'Apply Language',
  LocalizationKeysAppCodemart.codemartLanguageChanged: 'Language changed',
  LocalizationKeysAppCodemart.codemartLanguageEnglish: 'English',
  LocalizationKeysAppCodemart.codemartLanguageChinese: '中文',
  LocalizationKeysAppCodemart.codemartLanguageSpanish: 'Español',
  LocalizationKeysAppCodemart.codemartLanguageFrench: 'Français',
  LocalizationKeysAppCodemart.codemartLanguageGerman: 'Deutsch',
  LocalizationKeysAppCodemart.codemartLanguageJapanese: '日本語',
  LocalizationKeysAppCodemart.codemartLanguageKorean: '한국어',
  LocalizationKeysAppCodemart.codemartLanguagePortuguese: 'Português',

  // Common UI Strings
  LocalizationKeysAppCodemart.codemartQuickActions: 'Quick Actions',
  LocalizationKeysAppCodemart.codemartUser: 'User',
  LocalizationKeysAppCodemart.codemartRetry: 'Retry',
  LocalizationKeysAppCodemart.codemartAdd: 'Add',

  // Login & Registration
  LocalizationKeysAppCodemart.codemartDontHaveAccount: "Don't have an account? ",
  LocalizationKeysAppCodemart.codemartPleaseEnterEmail: 'Please enter your email',
  LocalizationKeysAppCodemart.codemartPleaseEnterValidEmail: 'Please enter a valid email',
  LocalizationKeysAppCodemart.codemartPleaseEnterPassword: 'Please enter your password',
  LocalizationKeysAppCodemart.codemartPasswordMinLength: 'Password must be at least 6 characters',
  LocalizationKeysAppCodemart.codemartLoginFailed: 'Login failed',
  LocalizationKeysAppCodemart.codemartLoginError: 'Login error',
  LocalizationKeysAppCodemart.codemartEnterVerificationCode: 'Enter verification code sent to your email',
  LocalizationKeysAppCodemart.codemartVerificationCode: 'Verification Code',
  LocalizationKeysAppCodemart.codemartEnterPhoneVerificationCode: 'Enter verification code sent to your phone',

  // Settings
  LocalizationKeysAppCodemart.codemartAccount: 'Account',
  LocalizationKeysAppCodemart.codemartEditProfileInfo: 'Edit your profile information',
  LocalizationKeysAppCodemart.codemartManagePaymentsTransactions: 'Manage payments and transactions',
  LocalizationKeysAppCodemart.codemartPreferences: 'Preferences',
  LocalizationKeysAppCodemart.codemartNotifications: 'Notifications',
  LocalizationKeysAppCodemart.codemartManageNotificationPreferences: 'Manage notification preferences',
  LocalizationKeysAppCodemart.codemartLanguage: 'Language',
  LocalizationKeysAppCodemart.codemartChangeAppLanguage: 'Change app language',
  LocalizationKeysAppCodemart.codemartTheme: 'Theme',
  LocalizationKeysAppCodemart.codemartLightDarkSystem: 'Light, Dark, or System',
  LocalizationKeysAppCodemart.codemartPrivacySecurity: 'Privacy & Security',
  LocalizationKeysAppCodemart.codemartPrivacy: 'Privacy',
  LocalizationKeysAppCodemart.codemartManagePrivacySettings: 'Manage privacy settings',
  LocalizationKeysAppCodemart.codemartSecurity: 'Security',
  LocalizationKeysAppCodemart.codemartPasswordAuthentication: 'Password and authentication',
  LocalizationKeysAppCodemart.codemartSupport: 'Support',
  LocalizationKeysAppCodemart.codemartHelpSupport: 'Help & Support',
  LocalizationKeysAppCodemart.codemartFaqsContactSupport: 'FAQs and contact support',
  LocalizationKeysAppCodemart.codemartAbout: 'About',
  LocalizationKeysAppCodemart.codemartAppVersionInfo: 'App version and information',
  LocalizationKeysAppCodemart.codemartTermsConditions: 'Terms & Conditions',
  LocalizationKeysAppCodemart.codemartApp: 'App',
  LocalizationKeysAppCodemart.codemartClearCache: 'Clear Cache',
  LocalizationKeysAppCodemart.codemartFreeUpStorage: 'Free up storage space',
  LocalizationKeysAppCodemart.codemartClearCacheConfirm: 'Are you sure you want to clear app cache?',
  LocalizationKeysAppCodemart.codemartCacheCleared: 'Cache cleared',
  LocalizationKeysAppCodemart.codemartReportBug: 'Report a Bug',

  // Projects
  LocalizationKeysAppCodemart.codemartSelectStartEndDates: 'Please select start and end dates',
  LocalizationKeysAppCodemart.codemartAddAtLeastOneSkill: 'Please add at least one skill',
  LocalizationKeysAppCodemart.codemartFailedCreateProject: 'Failed to create project',
  LocalizationKeysAppCodemart.codemartFailedLoadProjects: 'Failed to load projects',
  LocalizationKeysAppCodemart.codemartAddSkill: 'Add Skill',
  LocalizationKeysAppCodemart.codemartSkillName: 'Skill name',
  LocalizationKeysAppCodemart.codemartSkillPlaceholder: 'e.g., Flutter, Python, Node.js',
  LocalizationKeysAppCodemart.codemartErrorPickingFiles: 'Error picking files',
  LocalizationKeysAppCodemart.codemartPleaseEnterProjectTitle: 'Please enter project title',
  LocalizationKeysAppCodemart.codemartPleaseEnterProjectDescription: 'Please enter project description',
  LocalizationKeysAppCodemart.codemartPleaseEnterBudget: 'Please enter budget',
  LocalizationKeysAppCodemart.codemartPleaseEnterValidNumber: 'Please enter valid number',
  LocalizationKeysAppCodemart.codemartBudgetType: 'Budget Type',
  LocalizationKeysAppCodemart.codemartNotSelected: 'Not selected',
  LocalizationKeysAppCodemart.codemartNoSkillsAdded: 'No skills added yet',
  LocalizationKeysAppCodemart.codemartAttachmentsOptional: 'Attachments (Optional)',
  LocalizationKeysAppCodemart.codemartAddFiles: 'Add Files',
  LocalizationKeysAppCodemart.codemartAttachDocumentsHint: 'Attach project documents, designs, or specifications (PDF, DOC, XLS, etc.)',
  LocalizationKeysAppCodemart.codemartBudget: 'Budget',
  LocalizationKeysAppCodemart.codemartComplexity: 'Complexity',

  // Tasks
  LocalizationKeysAppCodemart.codemartFailedLoadTasks: 'Failed to load tasks',

  // Profile
  LocalizationKeysAppCodemart.codemartUserNotLoggedIn: 'User not logged in',
  LocalizationKeysAppCodemart.codemartRating: 'Rating',
  LocalizationKeysAppCodemart.codemartVerification: 'Verification',
  LocalizationKeysAppCodemart.codemartSkills: 'Skills',
  LocalizationKeysAppCodemart.codemartCompany: 'Company',
  LocalizationKeysAppCodemart.codemartNotSpecified: 'Not specified',
  LocalizationKeysAppCodemart.codemartTotalProjects: 'Total Projects',
};
