import 'localization_keys_app_codemart.dart';

final Map<String, String> enAppCodemart = {
  LocalizationKeysAppCodemart.codemartAppName: 'CodeMart',
  LocalizationKeysAppCodemart.codemartWelcome: 'Welcome to CodeMart',
  LocalizationKeysAppCodemart.codemartLogin: 'Login',
  LocalizationKeysAppCodemart.codemartRegister: 'Register',
  LocalizationKeysAppCodemart.codemartLogout: 'Logout',
  LocalizationKeysAppCodemart.codemartEmail: 'Email',
  LocalizationKeysAppCodemart.codemartPassword: 'Password',
  LocalizationKeysAppCodemart.codemartUsername: 'Username',
  LocalizationKeysAppCodemart.codemartName: 'Name',
  LocalizationKeysAppCodemart.codemartProfile: 'Profile',
  LocalizationKeysAppCodemart.codemartSettings: 'Settings',
  LocalizationKeysAppCodemart.codemartDeveloper: 'Developer',
  LocalizationKeysAppCodemart.codemartClient: 'Client',
  LocalizationKeysAppCodemart.codemartArchitect: 'Architect',
  LocalizationKeysAppCodemart.codemartReviewer: 'Reviewer',
  LocalizationKeysAppCodemart.codemartRegisterAsDeveloper: 'Register as Developer',
  LocalizationKeysAppCodemart.codemartRegisterAsClient: 'Register as Client',
  LocalizationKeysAppCodemart.codemartEmailVerification: 'Email Verification',
  LocalizationKeysAppCodemart.codemartPhoneVerification: 'Phone Verification',
  LocalizationKeysAppCodemart.codemartKycVerification: 'KYC Verification',
  LocalizationKeysAppCodemart.codemartPaymentDeposit: 'Payment Deposit',
  LocalizationKeysAppCodemart.codemartVerificationComplete: 'Verification Complete',
  LocalizationKeysAppCodemart.codemartProjects: 'Projects',
  LocalizationKeysAppCodemart.codemartCreateProject: 'Create Project',
  LocalizationKeysAppCodemart.codemartProjectTitle: 'Project Title',
  LocalizationKeysAppCodemart.codemartProjectDescription: 'Project Description',
  LocalizationKeysAppCodemart.codemartProjectBudget: 'Budget',
  LocalizationKeysAppCodemart.codemartProjectStatus: 'Status',
  LocalizationKeysAppCodemart.codemartProjectComplexity: 'Complexity',
  LocalizationKeysAppCodemart.codemartProjectStartDate: 'Start Date',
  LocalizationKeysAppCodemart.codemartProjectEndDate: 'End Date',
  LocalizationKeysAppCodemart.codemartProjectSkills: 'Required Skills',
  LocalizationKeysAppCodemart.codemartTasks: 'Tasks',
  LocalizationKeysAppCodemart.codemartTaskHall: 'Task Hall',
  LocalizationKeysAppCodemart.codemartTaskTitle: 'Task Title',
  LocalizationKeysAppCodemart.codemartTaskDescription: 'Task Description',
  LocalizationKeysAppCodemart.codemartTaskStatus: 'Task Status',
  LocalizationKeysAppCodemart.codemartTaskPriority: 'Priority',
  LocalizationKeysAppCodemart.codemartAcceptTask: 'Accept Task',
  LocalizationKeysAppCodemart.codemartSubmitTask: 'Submit Task',
  LocalizationKeysAppCodemart.codemartPayments: 'Payments',
  LocalizationKeysAppCodemart.codemartWallet: 'Wallet',
  LocalizationKeysAppCodemart.codemartBalance: 'Balance',
  LocalizationKeysAppCodemart.codemartEarnings: 'Earnings',
  LocalizationKeysAppCodemart.codemartTransactions: 'Transactions',
  LocalizationKeysAppCodemart.codemartSubmit: 'Submit',
  LocalizationKeysAppCodemart.codemartCancel: 'Cancel',
  LocalizationKeysAppCodemart.codemartConfirm: 'Confirm',
  LocalizationKeysAppCodemart.codemartSave: 'Save',
  LocalizationKeysAppCodemart.codemartEdit: 'Edit',
  LocalizationKeysAppCodemart.codemartDelete: 'Delete',
  LocalizationKeysAppCodemart.codemartBack: 'Back',
  LocalizationKeysAppCodemart.codemartNext: 'Next',
  LocalizationKeysAppCodemart.codemartPrevious: 'Previous',
  LocalizationKeysAppCodemart.codemartFinish: 'Finish',
  LocalizationKeysAppCodemart.codemartLoading: 'Loading...',
  LocalizationKeysAppCodemart.codemartError: 'Error',
  LocalizationKeysAppCodemart.codemartSuccess: 'Success',
  LocalizationKeysAppCodemart.codemartNoData: 'No Data',
};
