#!/usr/bin/env python3
"""
Generate cross-platform variable KEY definition files
Generate variable KEY definitions from build_vars.py for PowerShell and Bash
Ensure all scripts use unified variable KEYs
"""

import sys
from pathlib import Path

# Import variable definitions
from build_vars import BuildVars


def generate_powershell_keys(output_file: Path):
    """Generate PowerShell variable KEY definitions"""
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# VarKeys.ps1\n")
        f.write("# Auto-generated variable KEY definitions - DO NOT EDIT MANUALLY\n")
        f.write("# Generated by generate_var_keys.py from build_vars.py\n\n")

        f.write("# Variable KEY definition class\n")
        f.write("class VarKeys {\n")

        keys = BuildVars.get_all_keys()
        for key_name, key_value in sorted(keys.items()):
            # Convert to PowerShell style constant name
            f.write(f"    static [string] ${key_name} = \"{key_value}\"\n")

        f.write("}\n")

    print(f"Generated PowerShell keys: {output_file}")


def generate_bash_keys(output_file: Path):
    """Generate Bash variable KEY definitions"""
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("#!/bin/bash\n")
        f.write("# var_keys.sh\n")
        f.write("# Auto-generated variable KEY definitions - DO NOT EDIT MANUALLY\n")
        f.write("# Generated by generate_var_keys.py from build_vars.py\n\n")

        keys = BuildVars.get_all_keys()
        for key_name, key_value in sorted(keys.items()):
            # Bash variable naming convention: all uppercase
            bash_var_name = f"VAR_KEY_{key_name}"
            f.write(f"readonly {bash_var_name}=\"{key_value}\"\n")

        f.write("\n# Export all variable KEYs\n")
        for key_name, _ in sorted(keys.items()):
            bash_var_name = f"VAR_KEY_{key_name}"
            f.write(f"export {bash_var_name}\n")

    print(f"Generated Bash keys: {output_file}")


def generate_documentation(output_file: Path):
    """Generate variable KEY documentation"""
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Variable KEY Center\n\n")
        f.write("> **Note**: This document is auto-generated by `generate_var_keys.py`, DO NOT EDIT MANUALLY\n\n")
        f.write("## All Variable KEY Definitions\n\n")
        f.write("All variables have a unified prefix `mcpchrome_` to avoid multi-project conflicts.\n\n")

        keys = BuildVars.get_all_keys()

        # Group by category
        categories = {
            "Basic Environment": ["PROJECT_ROOT", "PLATFORM", "VARS_DIR"],
            "Dependency Versions": ["NODE_VERSION", "PNPM_VERSION", "NODE_INSTALLED", "PNPM_INSTALLED"],
            "Path Variables": ["BUILD_OUTPUT_DIR", "EXTENSION_PATH", "NATIVE_PATH", "SHARED_PATH", "MANIFEST_PATH", "NODE_MODULES_EXISTS"],
            "Build Commands": ["CMD_CHECK_DEPS", "CMD_INSTALL", "CMD_BUILD_SHARED", "CMD_BUILD_NATIVE", "CMD_BUILD_EXTENSION", "CMD_REGISTER"],
            "Status Flags": ["ERROR", "SHOULD_INSTALL", "BUILD_RETRY_MAX"],
            "UI Display": ["UI_TITLE", "UI_STEP_1", "UI_STEP_2", "UI_STEP_3", "UI_STEP_4", "UI_STEP_5", "UI_STEP_6"],
        }

        for category, key_names in categories.items():
            f.write(f"### {category}\n\n")
            f.write("| Constant Name | Variable KEY | Description |\n")
            f.write("|---------------|--------------|-------------|\n")

            for key_name in key_names:
                if key_name in keys:
                    key_value = keys[key_name]
                    # Get comment from class definition
                    f.write(f"| `{key_name}` | `{key_value}` | |\n")

            f.write("\n")

        f.write("## Usage Examples\n\n")

        f.write("### Python\n\n")
        f.write("```python\n")
        f.write("from build_vars import BuildVars\n")
        f.write("from var_manager import get_instance\n\n")
        f.write("vm = get_instance()\n")
        f.write("vm.set(BuildVars.PROJECT_ROOT, \"/path/to/project\")\n")
        f.write("root = vm.get(BuildVars.PROJECT_ROOT)\n")
        f.write("```\n\n")

        f.write("### PowerShell\n\n")
        f.write("```powershell\n")
        f.write(". .\\VarKeys.ps1\n")
        f.write("Import-Module .\\VarManager.ps1\n\n")
        f.write("Set-Var -Key ([VarKeys]::PROJECT_ROOT) -Value \"C:\\path\\to\\project\"\n")
        f.write("$root = Get-Var -Key ([VarKeys]::PROJECT_ROOT)\n")
        f.write("```\n\n")

        f.write("### Bash\n\n")
        f.write("```bash\n")
        f.write("source ./var_keys.sh\n")
        f.write("source ./var_manager.sh\n\n")
        f.write("set_var \"$VAR_KEY_PROJECT_ROOT\" \"/path/to/project\"\n")
        f.write("root=$(get_var \"$VAR_KEY_PROJECT_ROOT\")\n")
        f.write("```\n\n")

        f.write("## Adding New Variables\n\n")
        f.write("1. Add new KEY definition in `BuildVars` class in `build_vars.py`\n")
        f.write("2. Run `python generate_var_keys.py` to regenerate all KEY files\n")
        f.write("3. Use new KEY to set variables in `build_orchestrator.py`\n")
        f.write("4. Use new KEY to read variables in `start.ps1` or `start.sh`\n")

    print(f"Generated documentation: {output_file}")


def main():
    """Main function"""
    script_dir = Path(__file__).parent

    # Generate PowerShell KEY file
    ps_output = script_dir / "VarKeys.ps1"
    generate_powershell_keys(ps_output)

    # Generate Bash KEY file
    bash_output = script_dir / "var_keys.sh"
    generate_bash_keys(bash_output)

    # Generate documentation
    doc_output = script_dir / "VAR_KEYS.md"
    generate_documentation(doc_output)

    print("\nAll variable key files generated successfully!")
    print("Please commit these files to version control.")


if __name__ == "__main__":
    main()
