#!/bin/bash
# var_keys.sh
# Auto-generated variable KEY definitions - DO NOT EDIT MANUALLY
# Generated by generate_var_keys.py from build_vars.py

readonly VAR_KEY_BUILD_OUTPUT_DIR="mcpchrome_build_output_dir"
readonly VAR_KEY_BUILD_RETRY_MAX="mcpchrome_build_retry_max"
readonly VAR_KEY_CMD_BUILD_EXTENSION="mcpchrome_cmd_build_extension"
readonly VAR_KEY_CMD_BUILD_NATIVE="mcpchrome_cmd_build_native"
readonly VAR_KEY_CMD_BUILD_SHARED="mcpchrome_cmd_build_shared"
readonly VAR_KEY_CMD_CHECK_DEPS="mcpchrome_cmd_check_deps"
readonly VAR_KEY_CMD_INSTALL="mcpchrome_cmd_install"
readonly VAR_KEY_CMD_REGISTER="mcpchrome_cmd_register"
readonly VAR_KEY_ERROR="mcpchrome_error"
readonly VAR_KEY_EXTENSION_PATH="mcpchrome_extension_path"
readonly VAR_KEY_MANIFEST_PATH="mcpchrome_manifest_path"
readonly VAR_KEY_NATIVE_PATH="mcpchrome_native_path"
readonly VAR_KEY_NODE_INSTALLED="mcpchrome_node_installed"
readonly VAR_KEY_NODE_MODULES_EXISTS="mcpchrome_node_modules_exists"
readonly VAR_KEY_NODE_VERSION="mcpchrome_node_version"
readonly VAR_KEY_PLATFORM="mcpchrome_platform"
readonly VAR_KEY_PNPM_INSTALLED="mcpchrome_pnpm_installed"
readonly VAR_KEY_PNPM_VERSION="mcpchrome_pnpm_version"
readonly VAR_KEY_PREFIX="mcpchrome_"
readonly VAR_KEY_PROJECT_ROOT="mcpchrome_project_root"
readonly VAR_KEY_SHARED_PATH="mcpchrome_shared_path"
readonly VAR_KEY_SHOULD_INSTALL="mcpchrome_should_install"
readonly VAR_KEY_UI_STEP_1="mcpchrome_ui_step_1"
readonly VAR_KEY_UI_STEP_2="mcpchrome_ui_step_2"
readonly VAR_KEY_UI_STEP_3="mcpchrome_ui_step_3"
readonly VAR_KEY_UI_STEP_4="mcpchrome_ui_step_4"
readonly VAR_KEY_UI_STEP_5="mcpchrome_ui_step_5"
readonly VAR_KEY_UI_STEP_6="mcpchrome_ui_step_6"
readonly VAR_KEY_UI_TITLE="mcpchrome_ui_title"
readonly VAR_KEY_VARS_DIR="mcpchrome_vars_dir"

# Export all variable KEYs
