<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>DotApps.d3d4tester.Tools.BnProbe</RootNamespace>
    <AssemblyName>bnprobe</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\D3D4TesterCore\D3D4TesterCore.csproj" />
  </ItemGroup>
</Project>
