# -*- coding: utf-8 -*-
"""Central environment-backed service and worker configuration."""

import os


LARAVEL_WORKER_API_URL = os.getenv(
    "LARAVEL_WORKER_API_URL",
    "http://127.0.0.1:9000",
)
TRAY_BACKEND = "native"
UI_ENABLE_TRAY = TRAY_BACKEND == "pyside"
TRANSLATION_QUEUE_MONITOR_INTERVAL = int(
    os.getenv("TRANSLATION_QUEUE_MONITOR_INTERVAL", "30")
)
SENTENCE_QUEUE_MONITOR_INTERVAL = int(
    os.getenv("SENTENCE_QUEUE_MONITOR_INTERVAL", "15")
)
TRANSLATION_QUEUE_BUMP_TTL_SECONDS = int(
    os.getenv("TRANSLATION_QUEUE_BUMP_TTL_SECONDS", "30")
)
TRANSLATION_EVENT_HOST = os.getenv("TRANSLATION_EVENT_HOST", "127.0.0.1")
TRANSLATION_EVENT_PORT = int(os.getenv("TRANSLATION_EVENT_PORT", "9000"))
TRANSLATION_EVENT_SCHEME = os.getenv("TRANSLATION_EVENT_SCHEME", "http")
TRANSLATION_EVENT_CHANNEL = os.getenv(
    "TRANSLATION_EVENT_CHANNEL",
    "translation-queue",
)
TRANSLATION_SSE_PATH = os.getenv(
    "TRANSLATION_SSE_PATH",
    "/api/app_qy_v1/ai_tools/translation/queue/stream",
)
TRANSLATION_EVENT_SUPERVISOR_INTERVAL = int(
    os.getenv("TRANSLATION_EVENT_SUPERVISOR_INTERVAL", "5")
)
TRANSLATION_EVENT_WORD_TTL_SECONDS = int(
    os.getenv("TRANSLATION_EVENT_WORD_TTL_SECONDS", "120")
)
TTS_WORKER_BATCH = int(os.getenv("PYCORE_TTS_WORKER_BATCH", "10"))
TTS_WORKER_INTERVAL = int(os.getenv("PYCORE_TTS_WORKER_INTERVAL", "60"))
TTS_WORKER_CONCURRENCY = int(os.getenv("PYCORE_TTS_WORKER_CONCURRENCY", "0"))
TTS_SENTENCE_WORKER_BATCH = int(
    os.getenv("PYCORE_TTS_SENTENCE_WORKER_BATCH", "10")
)
TTS_SENTENCE_WORKER_INTERVAL = int(
    os.getenv("PYCORE_TTS_SENTENCE_WORKER_INTERVAL", "60")
)
TTS_SENTENCE_WORKER_CONCURRENCY = int(
    os.getenv("PYCORE_TTS_SENTENCE_WORKER_CONCURRENCY", "0")
)
