import { STORAGE_KEYS } from '@/utils/storage-keys';

/**
 * Qwen3-TTS (HuggingFace Gradio) automation — shared types & constants.
 * Official docs: use the embedded Gradio app URL (hf.space), not the Space page URL,
 * for API calls; UI automation opens the Space page and drives the iframe.
 * Last verified: 2026-07-13
 */

export const QWEN_TTS_LAST_VERIFIED = '2026-07-13';

/** User-facing Space page — open/reuse this tab. */
export const QWEN_TTS_SPACE_URL = 'https://huggingface.co/spaces/Qwen/Qwen3-TTS';

/** Embedded Gradio app (iframe src). Per HF/Gradio docs, API + DOM live here. */
export const QWEN_TTS_APP_URL = 'https://qwen-qwen3-tts.hf.space/?__theme=system';
export const QWEN_TTS_GRADIO_HOST = 'qwen-qwen3-tts.hf.space';
export const QWEN_TTS_SPACE_PATH = '/spaces/Qwen/Qwen3-TTS';
export const QWEN_TTS_GRADIO_API_BASE = 'https://qwen-qwen3-tts.hf.space';

export const QWEN_TTS_PROGRESS_KEY = STORAGE_KEYS.QWEN_TTS_PROGRESS;

export type QwenTtsMode = 'voice_design' | 'voice_clone' | 'custom_voice';

export type QwenTtsStatus = 'idle' | 'running' | 'waiting' | 'ok' | 'error' | 'timeout';

export interface QwenTtsRequest {
  text: string;
  mode?: QwenTtsMode;
  voiceDescription?: string;
  language?: string;
  styleInstruction?: string;
  speaker?: string;
  waitTimeoutMs?: number;
  openInNewTab?: boolean;
  tabId?: number;
  download?: boolean;
  filename?: string;
}

export interface QwenTtsAudioPayload {
  ok: boolean;
  mime?: string;
  bytes?: number[];
  src?: string;
  error?: string;
}

export interface QwenTtsResult {
  ok: boolean;
  status: QwenTtsStatus;
  message: string;
  text: string;
  mode: QwenTtsMode;
  url: string;
  tabId?: number;
  frameId?: number;
  audio?: QwenTtsAudioPayload;
  downloadId?: number;
  downloadFilename?: string;
  elapsedMs: number;
  lastVerified: string;
  error?: string;
}

export interface QwenTtsProgress {
  running: boolean;
  phase: string;
  detail: string;
  status: QwenTtsStatus;
  mode: QwenTtsMode;
  text: string;
  tabId: number | null;
  updatedAt: number;
}

export const DEFAULT_QWEN_TTS_TEXT =
  "Hello! This is a short test of Qwen3 text-to-speech generated by the Chrome extension.";

export const DEFAULT_QWEN_VOICE_DESCRIPTION =
  'Speak in a clear, friendly tone with natural pacing.';

export function isQwenTtsTabUrl(url: string | undefined | null): boolean {
  if (!url) return false;
  return url.includes(QWEN_TTS_SPACE_PATH) || url.includes(QWEN_TTS_GRADIO_HOST);
}

export function emptyQwenTtsProgress(): QwenTtsProgress {
  return {
    running: false,
    phase: 'Idle',
    detail: '',
    status: 'idle',
    mode: 'voice_design',
    text: '',
    tabId: null,
    updatedAt: 0,
  };
}

export function qwenTtsTabLabel(mode: QwenTtsMode): string {
  if (mode === 'voice_clone') return 'Voice Clone (Base)';
  if (mode === 'custom_voice') return 'TTS (CustomVoice)';
  return 'Voice Design';
}

export function qwenTtsGenerateButtonLabel(mode: QwenTtsMode): string {
  if (mode === 'voice_clone') return 'Clone & Generate';
  if (mode === 'custom_voice') return 'Generate Speech';
  return 'Generate with Custom Voice';
}

export function qwenTtsGradioApiName(mode: QwenTtsMode): string {
  if (mode === 'voice_clone') return 'generate_voice_clone';
  if (mode === 'custom_voice') return 'generate_custom_voice';
  return 'generate_voice_design';
}
