/** WordNew-owned persistence registry. Key values preserve installed data. */
const PREFIX = 'nexus_' as const;

export const WordNewStorageKeys = {
  WORDNEW_SETTINGS: `${PREFIX}wordnew_settings`,
  WORDNEW_CLIENT_ID: `${PREFIX}wordnew_client_id`,
  WORDNEW_FINGERPRINT_VISITOR: 'wordnew_client_fp_visitor',
  WORDNEW_CLIENT_ID_CURRENT_LEGACY: 'wordnew_client_local_id',
  WORDNEW_CLIENT_ID_LEGACY: 'wf_client_local_id',
  WORDNEW_FINGERPRINT_VISITOR_LEGACY: 'wf_client_fp_visitor',
  WORDNEW_SOCIAL: `${PREFIX}wordnew_social`,
  WORDNEW_ACCOUNTS: `${PREFIX}wordnew_accounts`,
  WORDNEW_API_PREFS: `${PREFIX}wordnew_api_prefs`,
  WORDNEW_API_CUSTOM_ENDPOINTS: `${PREFIX}wordnew_api_custom_endpoints`,
  WORDNEW_API_USER_ENDPOINT: `${PREFIX}wordnew_api_user_endpoint`,
  WORDNEW_API_AUTO_ENDPOINT: `${PREFIX}wordnew_api_auto_endpoint`,
  WORDNEW_API_CURRENT: `${PREFIX}wordnew_api_current`,
  WORDNEW_API_RECHECK_INTERVAL_MS: `${PREFIX}wordnew_api_recheck_interval_ms`,
  WORDNEW_API_QUEUE: 'wordnew_api_queue',
  WORDNEW_API_QUEUE_LEGACY: 'wf_api_queue',
  WORDNEW_AUTH_TOKEN: 'wfnew_auth_token',
  WORDNEW_READING_PROGRESS: 'wordnew_reading_progress',
  WORDNEW_READER_DAILY: 'wfnew_reader_daily_v1',
  WORDNEW_STUDY_PROGRESS: 'wfnew_study_progress_v1',
  WORDNEW_SENTENCE_WORD_CLIENT_KEY: 'wfnew.sentenceWords.clientKey',
  WORDNEW_ADMIN_LANGUAGE: 'wfnew_admin_lang',
  WORDNEW_ADMIN_TAB: 'wfnew_admin_tab',
  WORDNEW_DAILY_READING_PLAYER: 'wfnew.dailyReading.player',
  WORDNEW_SUPER_TOAST: 'wfnew_super_toast',
  WORDNEW_MOCK_AUTH_USERS: 'wfnew_auth_mock_users',
  WORDNEW_MOCK_PREFERENCES: 'wfnew_prefs_mock',
  WORDNEW_MOCK_DEVICE_SETTINGS: 'wfnew_device_settings_mock',
  WORDNEW_MOCK_LANGUAGES: 'wfnew_langs_mock',
  WORDNEW_MOCK_FRIENDS: 'wfnew_friends_mock',
  WORDNEW_MOCK_CONVERSATIONS: 'wfnew_convos_mock',
  WORDNEW_MOCK_MESSAGES: 'wfnew_messages_mock',
  WORDNEW_MOCK_REQUESTS: 'wfnew_requests_mock',
  WORDNEW_MOCK_NOTIFICATIONS: 'wfnew_notifs_mock',
  WORDNEW_MOCK_POSTS: 'wfnew_posts_mock',
  WORDNEW_MOCK_COMMENTS: 'wfnew_comments_mock',
  WORDNEW_MOCK_LIVE: 'wfnew_live_mock',
  WORDNEW_MOCK_LIVE_CHAT: 'wfnew_live_chat_mock',
} as const;

export type WordNewStorageKey = (typeof WordNewStorageKeys)[keyof typeof WordNewStorageKeys];
