import 'package:qyflutter/apps/app_vipclub/localization_app_vipclub/localization_keys_app_vipclub.dart';

final Map<String, String> enAppVipClub = {
  VipClubTextKeys.vipclubAppName: 'VIP Club',
  VipClubTextKeys.vipclubWelcome: 'Welcome to VIP Club',
  VipClubTextKeys.vipclubTagline: 'Luxury Shooting, Golf & Hotel Services',

  VipClubTextKeys.vipclubSplashTitle1: 'Welcome to VIP Club',
  VipClubTextKeys.vipclubSplashDesc1: 'Experience luxury and exclusivity with premium services',
  VipClubTextKeys.vipclubSplashTitle2: 'World-Class Facilities',
  VipClubTextKeys.vipclubSplashDesc2: 'Access premium shooting ranges, golf courses, and luxury hotel rooms',
  VipClubTextKeys.vipclubSplashTitle3: 'Exclusive Benefits',
  VipClubTextKeys.vipclubSplashDesc3: 'Enjoy special discounts and VIP member privileges',
  VipClubTextKeys.vipclubSplashTitle4: 'Easy Booking',
  VipClubTextKeys.vipclubSplashDesc4: 'Book facilities anytime, anywhere with our convenient app',
  VipClubTextKeys.vipclubSplashTitle5: 'Join the Elite',
  VipClubTextKeys.vipclubSplashDesc5: 'Become a member today and unlock premium experiences',
  VipClubTextKeys.vipclubSplashSkip: 'Skip',
  VipClubTextKeys.vipclubSplashNext: 'Next',
  VipClubTextKeys.vipclubSplashGetStarted: 'Get Started',

  VipClubTextKeys.vipclubLogin: 'Login',
  VipClubTextKeys.vipclubRegister: 'Register',
  VipClubTextKeys.vipclubLogout: 'Logout',
  VipClubTextKeys.vipclubEmail: 'Email',
  VipClubTextKeys.vipclubPassword: 'Password',
  VipClubTextKeys.vipclubFullName: 'Full Name',
  VipClubTextKeys.vipclubPhone: 'Phone',
  VipClubTextKeys.vipclubForgotPassword: 'Forgot Password?',

  VipClubTextKeys.vipclubHome: 'Home',
  VipClubTextKeys.vipclubFacilities: 'Facilities',
  VipClubTextKeys.vipclubBookings: 'Bookings',
  VipClubTextKeys.vipclubProfile: 'Profile',
  VipClubTextKeys.vipclubVipZone: 'VIP Zone',

  VipClubTextKeys.vipclubShooting: 'Shooting',
  VipClubTextKeys.vipclubShootingRange: 'Shooting Range',
  VipClubTextKeys.vipclubGolf: 'Golf',
  VipClubTextKeys.vipclubGolfCourse: 'Golf Course',
  VipClubTextKeys.vipclubHotel: 'Hotel',
  VipClubTextKeys.vipclubHotelRoom: 'Hotel Room',

  VipClubTextKeys.vipclubBookNow: 'Book Now',
  VipClubTextKeys.vipclubViewDetails: 'View Details',
  VipClubTextKeys.vipclubCancel: 'Cancel',
  VipClubTextKeys.vipclubConfirm: 'Confirm',
  VipClubTextKeys.vipclubMyBookings: 'My Bookings',
  VipClubTextKeys.vipclubBookingHistory: 'Booking History',

  VipClubTextKeys.vipclubMemberType: 'Member Type',
  VipClubTextKeys.vipclubRegularMember: 'Regular Member',
  VipClubTextKeys.vipclubGoldMember: 'Gold Member',
  VipClubTextKeys.vipclubPlatinumMember: 'Platinum Member',
  VipClubTextKeys.vipclubDiamondMember: 'Diamond Member',

  VipClubTextKeys.vipclubVipPoints: 'VIP Points',
  VipClubTextKeys.vipclubVipBenefits: 'VIP Benefits',
  VipClubTextKeys.vipclubVipCard: 'VIP Card',
  VipClubTextKeys.vipclubVipExclusive: 'VIP Exclusive',
  VipClubTextKeys.vipclubUpgradeNow: 'Upgrade Now',

  VipClubTextKeys.vipclubDate: 'Date',
  VipClubTextKeys.vipclubTime: 'Time',
  VipClubTextKeys.vipclubDuration: 'Duration',
  VipClubTextKeys.vipclubPrice: 'Price',
  VipClubTextKeys.vipclubDiscount: 'Discount',
  VipClubTextKeys.vipclubTotalPrice: 'Total Price',

  VipClubTextKeys.vipclubAvailableSlots: 'Available Slots',
  VipClubTextKeys.vipclubFullyBooked: 'Fully Booked',
  VipClubTextKeys.vipclubSelectDate: 'Select Date',
  VipClubTextKeys.vipclubSelectTime: 'Select Time',

  VipClubTextKeys.vipclubInstructor: 'Instructor',
  VipClubTextKeys.vipclubCaddy: 'Caddy',
  VipClubTextKeys.vipclubEquipmentRental: 'Equipment Rental',
  VipClubTextKeys.vipclubAddons: 'Add-ons',

  VipClubTextKeys.vipclubCheckIn: 'Check In',
  VipClubTextKeys.vipclubCheckOut: 'Check Out',
  VipClubTextKeys.vipclubGuests: 'Guests',
  VipClubTextKeys.vipclubRoomType: 'Room Type',

  VipClubTextKeys.vipclubPayNow: 'Pay Now',
  VipClubTextKeys.vipclubPayWithPoints: 'Pay with Points',
  VipClubTextKeys.vipclubPaymentMethod: 'Payment Method',

  VipClubTextKeys.vipclubSuccess: 'Success',
  VipClubTextKeys.vipclubError: 'Error',
  VipClubTextKeys.vipclubLoading: 'Loading...',
  VipClubTextKeys.vipclubNoData: 'No Data Available',

  VipClubTextKeys.vipclubAbout: 'About',
  VipClubTextKeys.vipclubContact: 'Contact',
  VipClubTextKeys.vipclubSettings: 'Settings',
  VipClubTextKeys.vipclubLanguage: 'Language',
  VipClubTextKeys.vipclubTheme: 'Theme',

  VipClubTextKeys.vipclubLoginTitle: 'Welcome Back',
  VipClubTextKeys.vipclubLoginSubtitle: 'Sign in to access your exclusive VIP benefits',
  VipClubTextKeys.vipclubLoginWelcome: 'Welcome to VIP Club',
  VipClubTextKeys.vipclubLoginAccount: 'Account',
  VipClubTextKeys.vipclubLoginPhone: 'Phone',
  VipClubTextKeys.vipclubLoginUsername: 'Username',
  VipClubTextKeys.vipclubLoginUsernameRequired: 'Username is required',
  VipClubTextKeys.vipclubLoginPassword: 'Password',
  VipClubTextKeys.vipclubLoginPasswordRequired: 'Password is required',
  VipClubTextKeys.vipclubLoginRememberMe: 'Remember Me',
  VipClubTextKeys.vipclubLoginForgotPassword: 'Forgot Password?',
  VipClubTextKeys.vipclubLoginPhoneNumber: 'Phone Number',
  VipClubTextKeys.vipclubLoginVerificationCode: 'Verification Code',
  VipClubTextKeys.vipclubLoginOr: 'OR',
  VipClubTextKeys.vipclubLoginWechat: 'WeChat',
  VipClubTextKeys.vipclubLoginGoogle: 'Google',
  VipClubTextKeys.vipclubLoginNoAccount: 'Don\'t have an account?',
  VipClubTextKeys.vipclubLoginRegister: 'Register Now',
  VipClubTextKeys.vipclubNoAccount: 'Don\'t have an account?',
  VipClubTextKeys.vipclubCreateAccount: 'Create Account',
  VipClubTextKeys.vipclubEmailRequired: 'Email is required',
  VipClubTextKeys.vipclubEmailInvalid: 'Please enter a valid email',
  VipClubTextKeys.vipclubPasswordRequired: 'Password is required',
  VipClubTextKeys.vipclubPasswordTooShort: 'Password must be at least 6 characters',
  VipClubTextKeys.vipclubLoginSuccess: 'Login successful!',
  VipClubTextKeys.vipclubLoginFailed: 'Login failed. Please check your credentials.',

  VipClubTextKeys.vipclubWelcomeBack: 'Welcome Back',
  VipClubTextKeys.vipclubMemberSince: 'Member Since',
  VipClubTextKeys.vipclubMemberExpiry: 'Membership Expiry',
  VipClubTextKeys.vipclubMyAccount: 'My Account',
  VipClubTextKeys.vipclubEditProfile: 'Edit Profile',
  VipClubTextKeys.vipclubAccountInfo: 'Account Information',

  VipClubTextKeys.vipclubHomeWelcome: 'Welcome to VIP Club',
  VipClubTextKeys.vipclubHomeSubtitle: 'Your gateway to luxury experiences',
  VipClubTextKeys.vipclubQuickAccess: 'Quick Access',
  VipClubTextKeys.vipclubFeaturedFacilities: 'Featured Facilities',
};
