import 'package:qyflutter/apps/app_vipclub/localization_app_vipclub/localization_keys_app_vipclub.dart';

final Map<String, String> zhAppVipClub = {
  VipClubTextKeys.vipclubAppName: 'VIP俱乐部',
  VipClubTextKeys.vipclubWelcome: '欢迎来到VIP俱乐部',
  VipClubTextKeys.vipclubTagline: '豪华射击、高尔夫与酒店服务',

  VipClubTextKeys.vipclubSplashTitle1: '欢迎来到VIP俱乐部',
  VipClubTextKeys.vipclubSplashDesc1: '尊享奢华与尊贵的优质服务体验',
  VipClubTextKeys.vipclubSplashTitle2: '世界级设施',
  VipClubTextKeys.vipclubSplashDesc2: '畅享顶级射击场、高尔夫球场和豪华酒店客房',
  VipClubTextKeys.vipclubSplashTitle3: '专属权益',
  VipClubTextKeys.vipclubSplashDesc3: '享受特别折扣和VIP会员专属特权',
  VipClubTextKeys.vipclubSplashTitle4: '便捷预订',
  VipClubTextKeys.vipclubSplashDesc4: '随时随地通过我们的便捷应用预订设施',
  VipClubTextKeys.vipclubSplashTitle5: '加入精英',
  VipClubTextKeys.vipclubSplashDesc5: '立即成为会员，解锁专属高端体验',
  VipClubTextKeys.vipclubSplashSkip: '跳过',
  VipClubTextKeys.vipclubSplashNext: '下一步',
  VipClubTextKeys.vipclubSplashGetStarted: '开始使用',

  VipClubTextKeys.vipclubLogin: '登录',
  VipClubTextKeys.vipclubRegister: '注册',
  VipClubTextKeys.vipclubLogout: '登出',
  VipClubTextKeys.vipclubEmail: '邮箱',
  VipClubTextKeys.vipclubPassword: '密码',
  VipClubTextKeys.vipclubFullName: '姓名',
  VipClubTextKeys.vipclubPhone: '电话',
  VipClubTextKeys.vipclubForgotPassword: '忘记密码？',

  VipClubTextKeys.vipclubHome: '首页',
  VipClubTextKeys.vipclubFacilities: '设施',
  VipClubTextKeys.vipclubBookings: '预订',
  VipClubTextKeys.vipclubProfile: '个人资料',
  VipClubTextKeys.vipclubVipZone: 'VIP专区',

  VipClubTextKeys.vipclubShooting: '射击',
  VipClubTextKeys.vipclubShootingRange: '射击场',
  VipClubTextKeys.vipclubGolf: '高尔夫',
  VipClubTextKeys.vipclubGolfCourse: '高尔夫球场',
  VipClubTextKeys.vipclubHotel: '酒店',
  VipClubTextKeys.vipclubHotelRoom: '酒店客房',

  VipClubTextKeys.vipclubBookNow: '立即预订',
  VipClubTextKeys.vipclubViewDetails: '查看详情',
  VipClubTextKeys.vipclubCancel: '取消',
  VipClubTextKeys.vipclubConfirm: '确认',
  VipClubTextKeys.vipclubMyBookings: '我的预订',
  VipClubTextKeys.vipclubBookingHistory: '预订历史',

  VipClubTextKeys.vipclubMemberType: '会员类型',
  VipClubTextKeys.vipclubRegularMember: '普通会员',
  VipClubTextKeys.vipclubGoldMember: '金卡会员',
  VipClubTextKeys.vipclubPlatinumMember: '白金会员',
  VipClubTextKeys.vipclubDiamondMember: '钻石会员',

  VipClubTextKeys.vipclubVipPoints: 'VIP积分',
  VipClubTextKeys.vipclubVipBenefits: 'VIP权益',
  VipClubTextKeys.vipclubVipCard: 'VIP卡',
  VipClubTextKeys.vipclubVipExclusive: 'VIP专属',
  VipClubTextKeys.vipclubUpgradeNow: '立即升级',

  VipClubTextKeys.vipclubDate: '日期',
  VipClubTextKeys.vipclubTime: '时间',
  VipClubTextKeys.vipclubDuration: '时长',
  VipClubTextKeys.vipclubPrice: '价格',
  VipClubTextKeys.vipclubDiscount: '折扣',
  VipClubTextKeys.vipclubTotalPrice: '总价',

  VipClubTextKeys.vipclubAvailableSlots: '可用时段',
  VipClubTextKeys.vipclubFullyBooked: '已预订满',
  VipClubTextKeys.vipclubSelectDate: '选择日期',
  VipClubTextKeys.vipclubSelectTime: '选择时间',

  VipClubTextKeys.vipclubInstructor: '教练',
  VipClubTextKeys.vipclubCaddy: '球童',
  VipClubTextKeys.vipclubEquipmentRental: '设备租赁',
  VipClubTextKeys.vipclubAddons: '附加服务',

  VipClubTextKeys.vipclubCheckIn: '入住',
  VipClubTextKeys.vipclubCheckOut: '退房',
  VipClubTextKeys.vipclubGuests: '客人',
  VipClubTextKeys.vipclubRoomType: '房型',

  VipClubTextKeys.vipclubPayNow: '立即支付',
  VipClubTextKeys.vipclubPayWithPoints: '积分支付',
  VipClubTextKeys.vipclubPaymentMethod: '支付方式',

  VipClubTextKeys.vipclubSuccess: '成功',
  VipClubTextKeys.vipclubError: '错误',
  VipClubTextKeys.vipclubLoading: '加载中...',
  VipClubTextKeys.vipclubNoData: '暂无数据',

  VipClubTextKeys.vipclubAbout: '关于',
  VipClubTextKeys.vipclubContact: '联系我们',
  VipClubTextKeys.vipclubSettings: '设置',
  VipClubTextKeys.vipclubLanguage: '语言',
  VipClubTextKeys.vipclubTheme: '主题',

  VipClubTextKeys.vipclubLoginTitle: '欢迎回来',
  VipClubTextKeys.vipclubLoginSubtitle: '登录以访问您的专属VIP权益',
  VipClubTextKeys.vipclubLoginWelcome: '欢迎来到VIP俱乐部',
  VipClubTextKeys.vipclubLoginAccount: '账号',
  VipClubTextKeys.vipclubLoginPhone: '手机',
  VipClubTextKeys.vipclubLoginUsername: '用户名',
  VipClubTextKeys.vipclubLoginUsernameRequired: '请输入用户名',
  VipClubTextKeys.vipclubLoginPassword: '密码',
  VipClubTextKeys.vipclubLoginPasswordRequired: '请输入密码',
  VipClubTextKeys.vipclubLoginRememberMe: '记住我',
  VipClubTextKeys.vipclubLoginForgotPassword: '忘记密码？',
  VipClubTextKeys.vipclubLoginPhoneNumber: '手机号',
  VipClubTextKeys.vipclubLoginVerificationCode: '验证码',
  VipClubTextKeys.vipclubLoginOr: '或',
  VipClubTextKeys.vipclubLoginWechat: '微信',
  VipClubTextKeys.vipclubLoginGoogle: 'Google',
  VipClubTextKeys.vipclubLoginNoAccount: '还没有账户？',
  VipClubTextKeys.vipclubLoginRegister: '立即注册',
  VipClubTextKeys.vipclubNoAccount: '还没有账户？',
  VipClubTextKeys.vipclubCreateAccount: '创建账户',
  VipClubTextKeys.vipclubEmailRequired: '请输入邮箱',
  VipClubTextKeys.vipclubEmailInvalid: '请输入有效的邮箱地址',
  VipClubTextKeys.vipclubPasswordRequired: '请输入密码',
  VipClubTextKeys.vipclubPasswordTooShort: '密码至少需要6个字符',
  VipClubTextKeys.vipclubLoginSuccess: '登录成功！',
  VipClubTextKeys.vipclubLoginFailed: '登录失败，请检查您的账户信息。',

  VipClubTextKeys.vipclubWelcomeBack: '欢迎回来',
  VipClubTextKeys.vipclubMemberSince: '成为会员于',
  VipClubTextKeys.vipclubMemberExpiry: '会员到期时间',
  VipClubTextKeys.vipclubMyAccount: '我的账户',
  VipClubTextKeys.vipclubEditProfile: '编辑资料',
  VipClubTextKeys.vipclubAccountInfo: '账户信息',

  VipClubTextKeys.vipclubHomeWelcome: '欢迎来到VIP俱乐部',
  VipClubTextKeys.vipclubHomeSubtitle: '您的奢华体验之门',
  VipClubTextKeys.vipclubQuickAccess: '快速访问',
  VipClubTextKeys.vipclubFeaturedFacilities: '精选设施',
};
