"""
Command Content Generator for Linux

Generates bash scripts for Linux systems.
This is the Linux-specific version of CommandContentGenerator.ps1
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional

from config.path_config import get_path_config
from script_sections.mcp_section import MCPSectionGenerator
from script_sections.user_directory_section import UserDirectorySectionGenerator
from script_sections.env_loading_section import EnvLoadingSectionGenerator
from script_sections.ssh_command_generator import SSHCommandGenerator


class LinuxCommandContentGenerator:
    """Generate Linux bash command scripts"""

    def __init__(self):
        self.path_config = get_path_config()
        self.project_root = self.path_config.project_root
        self.scripts_dir = self.path_config.scripts_dir
        self.mcp_generator = MCPSectionGenerator(self.path_config)
        self.user_dir_generator = UserDirectorySectionGenerator()
        self.env_loading_generator = EnvLoadingSectionGenerator()
        self.ssh_generator = SSHCommandGenerator()

    def get_mcp_sync_script_path(self, tool_type: str) -> Path:
        """Get MCP sync script path for a specific tool"""
        return self.path_config.get_mcp_sync_script_path(tool_type)

    def get_pre_launch_script_path(self, tool_type: str) -> Path:
        """Get pre-launch script path for a specific tool"""
        return self.path_config.get_pre_launch_script_path(tool_type, 'linux')

    def get_update_script_path(self, tool_type: str) -> Path:
        """Get update/upgrade script path for a specific tool"""
        return self.path_config.get_update_script_path(tool_type, 'linux')

    def generate_mcp_section(self, tool_type: str, tool_display_name: str,
                           target_name: str, support_upgrade: bool = True, support_npm_update: bool = False) -> str:
        """Generate MCP synchronization section for any AI tool

        Args:
            tool_type: Type of AI tool (e.g., 'claude', 'codex')
            tool_display_name: Display name for the tool (e.g., 'Claude Code')
            target_name: Target name for MCP sync (e.g., 'claude')
            support_upgrade: Whether to include upgrade option
            support_npm_update: Whether to include npm/npx update option
        """
        return self.mcp_generator.generate_linux_mcp_section(
            tool_type, tool_display_name, target_name, support_upgrade, support_npm_update
        )

    def generate_command_content(self, config_name: str, command_prefix: str,
                                bash_command: str, file_number: int,
                                variables: List[Dict[str, Any]],
                                mcp_section: str = "", file_name: str = "") -> str:
        """Generate complete bash command content"""
        # Add --dangerously-skip-permissions for claude commands
        # Skip this flag if running as root (root doesn't need permission skipping)
        root_check_section = ""
        if bash_command == "claude":
            root_check_section = """
# Check if running as root - skip --dangerously-skip-permissions flag for root
if [ "$EUID" -eq 0 ]; then
    echo ""
    echo "============================================================"
    echo "WARNING: Running as root user"
    echo "============================================================"
    echo "Root user already has all permissions."
    echo "--dangerously-skip-permissions flag is NOT added."
    echo "============================================================"
    echo ""
    claude_command="claude"
else
    claude_command="claude --dangerously-skip-permissions"
fi
"""
            bash_command = "$claude_command"
        
        header = f"""#!/bin/bash
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\\..\\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# {config_name} Global File #{file_number}
# =============================================================================
#
# Synopsis:
#     {config_name} Launch Script
#
# Description:
#     This file is automatically generated by Special Software Environment Manager
#     Contains tool startup functionality for Linux systems
#
# Notes:
#     - Tool Name: {config_name}
#     - Command Prefix: {command_prefix}
#     - Command: {bash_command}
#     - File Number: {file_number}
#     - File Name: {file_name}
#     - Generation Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
#
# Environment Variables:
#     Environment variables are managed by linux_path_function.sh
#     This script focuses on command execution only
# =============================================================================

set -e
{root_check_section}"""

        file_name_display = ""
        if file_name:
            file_name_display = f"""
echo ""
echo "============================================================"
echo "Running: {file_name}"
echo "============================================================"
echo ""
"""

        # Path resolution section
        path_resolution = """
#region Initialize Path Variables
script_source="${BASH_SOURCE[0]}"
if [ -L "$script_source" ]; then
    script_source="$(readlink -f "$script_source" 2>/dev/null || echo "$script_source")"
fi
script_current_path="$(cd "$(dirname "$script_source")" && pwd)"
scripts_dir_path="$(cd "$script_current_path/.." && pwd)"
project_root_path="$(cd "$scripts_dir_path/.." && pwd)"
pytools_dir_path="$scripts_dir_path/pytools"
ai_tools_dir_path="$pytools_dir_path/ai_tools"
#endregion
"""

        # Generate environment variable loading section
        env_loading_section = self.env_loading_generator.generate_linux_env_loading_section(variables, file_number)

        # Build command display code
        build_command_code = """
#region Build Launch Command Display
env_vars_parts=()

"""
        for var in variables:
            var_name = var['Name']
            build_command_code += f"""if [ -n "${{{var_name}:-}}" ]; then
    env_vars_parts+=("{var_name}='${{{var_name}}}'")
fi

"""

        build_command_code += f"""if [ ${{#env_vars_parts[@]}} -gt 0 ]; then
    env_vars_command=$(IFS=' ' ; echo "${{env_vars_parts[*]}}")
    full_command_display="$env_vars_command {bash_command}"
else
    full_command_display="{bash_command}"
fi
#endregion

"""

        env_section = env_loading_section + build_command_code + "\n"

        mcp_section_content = ""
        if mcp_section:
            mcp_section_content = f"""
#region MCP Server Synchronization
echo ""
echo "============================================================"
echo "MCP Server Synchronization"
echo "============================================================"
echo ""

{mcp_section}
#endregion

"""

        launch_section = f"""
#region Launch Tool
echo ""
echo "============================================================"
echo "Press Enter to start {config_name}..."
echo "============================================================"
read -p "Press Enter to continue"

echo ""
echo "Executing: {bash_command}"
echo ""
echo "Command: $full_command_display"
echo ""
echo "Press Enter to continue..."
read
eval "$full_command_display"

echo ""
echo "Press Enter to exit..."
read
#endregion
"""

        return f"""{header}{file_name_display}{path_resolution}{env_section}{mcp_section_content}{launch_section}"""

    def generate_ssh_command_content(self, config_name: str, file_number: int,
                                    user_inputs: Dict[str, str], file_name: str = "") -> str:
        """Generate SSH connection bash script"""
        return self.ssh_generator.generate_linux_ssh_command(config_name, file_number, file_name)


__all__ = ['LinuxCommandContentGenerator']

