#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import zlib from 'zlib';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Default encryption password (can be overridden)
const DEFAULT_PASSWORD = "BuildFactoryEncryptionKey2025";

// XOR encryption/decryption
function xorEncryptDecrypt(data, password) {
    const passwordBuffer = Buffer.from(password, 'utf8');
    const result = Buffer.alloc(data.length);

    for (let i = 0; i < data.length; i++) {
        result[i] = data[i] ^ passwordBuffer[i % passwordBuffer.length];
    }

    return result;
}

// Compress data
function compressData(data) {
    return zlib.gzipSync(data);
}

// Decompress data
function decompressData(data) {
    return zlib.gunzipSync(data);
}

// Encrypt single file
async function encryptFile(inputPath, password = DEFAULT_PASSWORD) {
    try {
        if (!fs.existsSync(inputPath)) {
            throw new Error(`File not found: ${inputPath}`);
        }

        const content = await fs.promises.readFile(inputPath);
        const compressed = compressData(content);
        const encrypted = xorEncryptDecrypt(compressed, password);
        const base64 = encrypted.toString('base64');

        return {
            success: true,
            encrypted: base64,
            originalPath: inputPath,
            originalName: path.basename(inputPath),
            size: content.length,
            compressedSize: compressed.length,
            encryptedSize: encrypted.length
        };
    } catch (error) {
        return {
            success: false,
            error: error.message,
            originalPath: inputPath
        };
    }
}

// Encrypt multiple files in batch
async function encryptBatch(filePaths, password = DEFAULT_PASSWORD) {
    const results = [];
    const startTime = Date.now();

    for (const filePath of filePaths) {
        const result = await encryptFile(filePath, password);
        results.push(result);
    }

    const endTime = Date.now();
    const duration = endTime - startTime;

    return {
        results,
        total: filePaths.length,
        successful: results.filter(r => r.success).length,
        failed: results.filter(r => !r.success).length,
        duration,
        averageTime: duration / filePaths.length
    };
}

// Generate encrypted .en.js file
async function generateEncryptedFile(encryptedData, originalName, outputDir) {
    try {
        const fileNameWithoutExt = path.parse(originalName).name;
        const encryptedFileName = `${fileNameWithoutExt}.en.js`;
        const outputPath = path.join(outputDir, encryptedFileName);

        const fileContent = `// Encrypted file generated by Build Factory
// Original file: ${originalName}
// Generated at: ${new Date().toISOString()}

export const encrypted = "${encryptedData}";

// Decryption function (requires password)
export async function decrypt(password = "BuildFactoryEncryptionKey2025") {
    const zlib = await import('zlib');

    try {
        // Decode base64
        const encrypted = Buffer.from(exports.encrypted, 'base64');

        // XOR decrypt
        const passwordBuffer = Buffer.from(password, 'utf8');
        const compressed = Buffer.alloc(encrypted.length);
        for (let i = 0; i < encrypted.length; i++) {
            compressed[i] = encrypted[i] ^ passwordBuffer[i % passwordBuffer.length];
        }

        // Decompress
        const original = zlib.gunzipSync(compressed);
        return original;
    } catch (error) {
        // Wrong password produces garbage data
        // This is expected behavior - any password can decrypt
        return Buffer.from('');
    }
}
`;

        await fs.promises.writeFile(outputPath, fileContent, 'utf8');

        return {
            success: true,
            outputPath,
            encryptedFileName
        };
    } catch (error) {
        return {
            success: false,
            error: error.message
        };
    }
}

// Process batch encryption and generate output files
async function processBatchEncryption(filePaths, outputDir, password = DEFAULT_PASSWORD) {
    console.log(`[BATCH ENCRYPT] Starting batch encryption of ${filePaths.length} files`);

    const batchResult = await encryptBatch(filePaths, password);
    const outputResults = [];

    for (const result of batchResult.results) {
        if (result.success) {
            const outputResult = await generateEncryptedFile(
                result.encrypted,
                result.originalName,
                outputDir
            );

            outputResults.push({
                ...result,
                ...outputResult
            });

            if (outputResult.success) {
                console.log(`[SUCCESS] ${result.originalName} -> ${outputResult.encryptedFileName}`);
            } else {
                console.error(`[FAILED] ${result.originalName}: ${outputResult.error}`);
            }
        } else {
            console.error(`[FAILED] ${result.originalPath}: ${result.error}`);
            outputResults.push(result);
        }
    }

    console.log(`[BATCH COMPLETE] ${batchResult.successful}/${batchResult.total} files encrypted in ${batchResult.duration}ms`);
    console.log(`[AVERAGE] ${batchResult.averageTime.toFixed(2)}ms per file`);

    return {
        ...batchResult,
        outputResults
    };
}

// Decrypt content
function decryptContent(base64String, password = DEFAULT_PASSWORD) {
    try {
        const encrypted = Buffer.from(base64String, 'base64');
        const compressed = xorEncryptDecrypt(encrypted, password);
        const original = decompressData(compressed);
        return original;
    } catch (error) {
        return Buffer.from('');
    }
}

// Export functions for use by other modules
export {
    xorEncryptDecrypt,
    compressData,
    decompressData,
    encryptFile,
    encryptBatch,
    generateEncryptedFile,
    processBatchEncryption,
    decryptContent,
    DEFAULT_PASSWORD
};

// CLI interface
async function main() {
    const args = process.argv.slice(2);

    if (args.length === 0) {
        console.log(`
Build Factory Encryptor
========================

Usage:
  Single file:  node build_encryptor.js <file> [password] [output_dir]
  Batch files:  node build_encryptor.js --batch <file1> <file2> ... [--password <pwd>] [--output <dir>]
  Decrypt:      node build_encryptor.js --decrypt <encrypted_file> [password]

Examples:
  Encrypt single:   node build_encryptor.js secret.txt
  Encrypt batch:    node build_encryptor.js --batch file1.txt file2.js --output ./encrypted
  Decrypt:          node build_encryptor.js --decrypt file.en.js mypassword
`);
        process.exit(0);
    }

    // Batch mode
    if (args[0] === '--batch') {
        const files = [];
        let password = DEFAULT_PASSWORD;
        let outputDir = process.cwd();

        for (let i = 1; i < args.length; i++) {
            if (args[i] === '--password' && i + 1 < args.length) {
                password = args[++i];
            } else if (args[i] === '--output' && i + 1 < args.length) {
                outputDir = args[++i];
            } else if (!args[i].startsWith('--')) {
                files.push(args[i]);
            }
        }

        if (files.length === 0) {
            console.error('No files specified for batch encryption');
            process.exit(1);
        }

        await processBatchEncryption(files, outputDir, password);
        return;
    }

    // Decrypt mode
    if (args[0] === '--decrypt') {
        const filePath = args[1];
        const password = args[2] || DEFAULT_PASSWORD;

        if (!filePath) {
            console.error('No file specified for decryption');
            process.exit(1);
        }

        const { encrypted } = await import(path.resolve(filePath));
        const decrypted = decryptContent(encrypted, password);

        process.stdout.write(decrypted);
        return;
    }

    // Single file mode
    const [inputPath, password, outputDir] = args;
    const pwd = password || DEFAULT_PASSWORD;
    const outDir = outputDir || path.dirname(inputPath);

    const result = await encryptFile(inputPath, pwd);

    if (result.success) {
        const outputResult = await generateEncryptedFile(
            result.encrypted,
            result.originalName,
            outDir
        );

        if (outputResult.success) {
            console.log(`[SUCCESS] Encrypted: ${outputResult.outputPath}`);
        } else {
            console.error(`[FAILED] ${outputResult.error}`);
            process.exit(1);
        }
    } else {
        console.error(`[FAILED] ${result.error}`);
        process.exit(1);
    }
}

// Run CLI if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
    main().catch(console.error);
}
