class CitiesAppTravel {
  static const List<String> popularCities = [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Hangzhou',
    'Chongqing',
    'Wuhan',
    'Xi\'an',
    'Suzhou',
    'Tianjin',
    'Nanjing',
    'Zhengzhou',
    'Changsha',
    'Shenyang',
    'Qingdao',
    'Xiamen',
    'Dalian',
    'Kunming',
    'Luoyang',
    '塞班',
  ];

  static const List<String> allCities = [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Hangzhou',
    'Chongqing',
    'Wuhan',
    'Xi\'an',
    'Suzhou',
    'Tianjin',
    'Nanjing',
    'Zhengzhou',
    'Changsha',
    'Shenyang',
    'Qingdao',
    'Xiamen',
    'Dalian',
    'Kunming',
    'Luoyang',
    '塞班',
    'Harbin',
    'Jinan',
    'Fuzhou',
    'Shijiazhuang',
    'Changchun',
    'Taiyuan',
    'Nanchang',
    'Guiyang',
    'Nanning',
    'Hefei',
    'Urumqi',
    'Hohhot',
    'Lhasa',
    'Lanzhou',
    'Yinchuan',
    'Xining',
    'Haikou',
    'Sanya',
  ];

  static const String defaultCity = '塞班';

  static bool isCityValid(String city) {
    return allCities.contains(city);
  }
}
