#!/usr/bin/env python3

class KeysCenter:
    KEY_SCAN_RESULTS = "POLY_APP_SCAN_RESULTS"
    KEY_USER_SELECTION = "POLY_APP_USER_SELECTION"
    KEY_MENU_CACHE = "POLY_APP_MENU_CACHE"
    KEY_PORT_ASSIGNMENTS = "POLY_APP_PORT_ASSIGNMENTS"

    KEY_PROJECT_NAME = "POLY_APP_PROJECT_NAME"
    KEY_PROJECT_TYPE = "POLY_APP_PROJECT_TYPE"
    KEY_PROJECT_PATH = "POLY_APP_PROJECT_PATH"
    KEY_PROJECT_PORT = "POLY_APP_PROJECT_PORT"
    KEY_PROJECT_FRAMEWORK = "POLY_APP_PROJECT_FRAMEWORK"
    KEY_PROJECT_PLATFORMS = "POLY_APP_PROJECT_PLATFORMS"

    KEY_SELECTED_PROJECT_INDEX = "POLY_APP_SELECTED_PROJECT_INDEX"
    KEY_SELECTED_ACTION_INDEX = "POLY_APP_SELECTED_ACTION_INDEX"
    KEY_SELECTED_PLATFORM_INDEX = "POLY_APP_SELECTED_PLATFORM_INDEX"
    KEY_SELECTED_PROJECT_NAME = "POLY_APP_SELECTED_PROJECT_NAME"
    KEY_SELECTED_ACTION_NAME = "POLY_APP_SELECTED_ACTION_NAME"
    KEY_SELECTED_PLATFORM_NAME = "POLY_APP_SELECTED_PLATFORM_NAME"

    KEY_LAST_SCAN_TIMESTAMP = "POLY_APP_LAST_SCAN_TIMESTAMP"
    KEY_BASE_PORT = "POLY_APP_BASE_PORT"
    KEY_SCAN_BASE_PATH = "POLY_APP_SCAN_BASE_PATH"

    PROJECT_TYPE_NUXT = "nuxt"
    PROJECT_TYPE_NEXT = "nextjs"
    PROJECT_TYPE_REACT = "react"
    PROJECT_TYPE_REACT_NATIVE = "react-native"
    PROJECT_TYPE_VUE = "vue"
    PROJECT_TYPE_VITE = "vite"
    PROJECT_TYPE_FLUTTER = "flutter"
    PROJECT_TYPE_LARAVEL = "laravel"
    PROJECT_TYPE_UNKNOWN = "unknown"

    ACTION_DEBUG = "debug"
    ACTION_BUILD = "build"
    ACTION_GENERATE = "generate"
    ACTION_RELEASE = "release"
    ACTION_PREVIEW = "preview"

    PLATFORM_WEB = "web"
    PLATFORM_ANDROID = "android"
    PLATFORM_IOS = "ios"
    PLATFORM_LINUX = "linux"
    PLATFORM_WINDOWS = "windows"
    PLATFORM_MACOS = "macos"
    PLATFORM_DEPLOY_LARAVEL = "deploy_laravel"
