# Main Build Orchestrator Script
# Generated by script_generator.py


# Path normalization helper function
function Normalize-Path {
    param(
        [string]$Path,
        [string]$TargetFormat = "flutter",
        [bool]$Debug = $false
    )
    
    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $Path
    }
    
    $Path = $Path.Trim()
    
    if ($Debug) {
        Write-Host "[PATH] Input: '$Path'" -ForegroundColor Gray
    }
    
    if ($TargetFormat -eq "flutter" -or $TargetFormat -eq "auto") {
        $Path = $Path -replace "\\+", "/"
        $Path = $Path -replace "\", "/"
        $Path = $Path -replace "/+", "/"
    }
    elseif ($TargetFormat -eq "windows") {
        $Path = $Path -replace "/+", "\"
        $Path = $Path -replace "/", "\"
        $Path = $Path -replace "\+", "\"
    }
    
    if ($Path.StartsWith("/") -and -not $Path.StartsWith("//")) {
        $Path = $Path.Substring(1)
    }
    if ($Path.StartsWith("\") -and -not $Path.StartsWith("\\")) {
        $Path = $Path.Substring(1)
    }
    
    if ($Debug) {
        Write-Host "[PATH] Output: '$Path'" -ForegroundColor Gray
    }
    
    return $Path
}

# Flutter command path fix helper function
function Fix-FlutterCommandPath {
    param(
        [string]$Command,
        [bool]$Debug = $false
    )
    
    if ([string]::IsNullOrWhiteSpace($Command)) {
        return $Command
    }
    
    if ($Debug) {
        Write-Host "[CMD] Original: '$Command'" -ForegroundColor Gray
    }
    
    $Command = $Command -replace " -t ([^\s]+)", {
        $path = $matches[1]
        $normalizedPath = Normalize-Path -Path $path -TargetFormat "flutter" -Debug $Debug
        " -t $normalizedPath"
    }
    
    if ($Debug) {
        Write-Host "[CMD] Fixed: '$Command'" -ForegroundColor Gray
    }
    
    return $Command
}


Write-Host "[ORCHESTRATOR] Starting Flutter build orchestration..." -ForegroundColor Yellow

# Step 1: Comprehensive cleanup
Write-Host "[ORCHESTRATOR] Step 1: Running comprehensive cleanup..." -ForegroundColor Cyan
try {
    & "build_scripts\01_cleanup.ps1"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ORCHESTRATOR] Cleanup failed, but continuing..." -ForegroundColor Yellow
    }
} catch {
    Write-Host "[ORCHESTRATOR] Cleanup script error: $_" -ForegroundColor Red
}

# Step 2: Kotlin configuration fix
Write-Host "[ORCHESTRATOR] Step 2: Running Kotlin configuration fix..." -ForegroundColor Cyan
try {
    & "build_scripts\02_kotlin_fix.ps1"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ORCHESTRATOR] Kotlin fix failed, but continuing..." -ForegroundColor Yellow
    }
} catch {
    Write-Host "[ORCHESTRATOR] Kotlin fix script error: $_" -ForegroundColor Red
}

# Step 3: Main build with retry logic
Write-Host "[ORCHESTRATOR] Step 3: Starting main build process..." -ForegroundColor Cyan
$maxRetries = 2
$retryCount = 0
$exitCode = 1

while ($retryCount -le $maxRetries -and $exitCode -ne 0) {
    if ($retryCount -gt 0) {
        Write-Host "[ORCHESTRATOR] Retry attempt $retryCount of $maxRetries..." -ForegroundColor Yellow
        
        # Run retry cleanup
        try {
            & "build_scripts\03_retry_cleanup.ps1"
        } catch {
            Write-Host "[ORCHESTRATOR] Retry cleanup error: $_" -ForegroundColor Red
        }
    }
    
    # Run main build
    try {
        & "build_scripts\04_build.ps1"
        $exitCode = $LASTEXITCODE
    } catch {
        Write-Host "[ORCHESTRATOR] Build script error: $_" -ForegroundColor Red
        $exitCode = 1
    }
    
    $retryCount++
}

# Final result
if ($exitCode -eq 0) {
    Write-Host "[ORCHESTRATOR] Build completed successfully!" -ForegroundColor Green
} else {
    Write-Host "[ORCHESTRATOR] Build failed after $maxRetries retries" -ForegroundColor Red
    Write-Host "[ORCHESTRATOR] Common solutions:" -ForegroundColor Yellow
    Write-Host "[ORCHESTRATOR] 1. Check if Kotlin incremental compilation is disabled in android/gradle.properties" -ForegroundColor Gray
    Write-Host "[ORCHESTRATOR] 2. Ensure all dependencies are up to date: flutter pub upgrade" -ForegroundColor Gray
    Write-Host "[ORCHESTRATOR] 3. Try building debug version first: flutter build apk --debug" -ForegroundColor Gray
    Write-Host "[ORCHESTRATOR] 4. Check Flutter and Dart versions: flutter doctor" -ForegroundColor Gray
}

exit $exitCode
