# Comprehensive Cache Cleanup Script
# Generated by script_generator.py


# Path normalization helper function
function Normalize-Path {
    param(
        [string]$Path,
        [string]$TargetFormat = "flutter",
        [bool]$Debug = $false
    )
    
    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $Path
    }
    
    $Path = $Path.Trim()
    
    if ($Debug) {
        Write-Host "[PATH] Input: '$Path'" -ForegroundColor Gray
    }
    
    if ($TargetFormat -eq "flutter" -or $TargetFormat -eq "auto") {
        $Path = $Path -replace "\\+", "/"
        $Path = $Path -replace "\", "/"
        $Path = $Path -replace "/+", "/"
    }
    elseif ($TargetFormat -eq "windows") {
        $Path = $Path -replace "/+", "\"
        $Path = $Path -replace "/", "\"
        $Path = $Path -replace "\+", "\"
    }
    
    if ($Path.StartsWith("/") -and -not $Path.StartsWith("//")) {
        $Path = $Path.Substring(1)
    }
    if ($Path.StartsWith("\") -and -not $Path.StartsWith("\\")) {
        $Path = $Path.Substring(1)
    }
    
    if ($Debug) {
        Write-Host "[PATH] Output: '$Path'" -ForegroundColor Gray
    }
    
    return $Path
}

# Flutter command path fix helper function
function Fix-FlutterCommandPath {
    param(
        [string]$Command,
        [bool]$Debug = $false
    )
    
    if ([string]::IsNullOrWhiteSpace($Command)) {
        return $Command
    }
    
    if ($Debug) {
        Write-Host "[CMD] Original: '$Command'" -ForegroundColor Gray
    }
    
    $Command = $Command -replace " -t ([^\s]+)", {
        $path = $matches[1]
        $normalizedPath = Normalize-Path -Path $path -TargetFormat "flutter" -Debug $Debug
        " -t $normalizedPath"
    }
    
    if ($Debug) {
        Write-Host "[CMD] Fixed: '$Command'" -ForegroundColor Gray
    }
    
    return $Command
}


Write-Host "[CLEANUP] Starting comprehensive cache cleanup..." -ForegroundColor Yellow

# Stop Gradle daemons
Write-Host "[CLEANUP] Stopping Gradle daemons..." -ForegroundColor Yellow
try {
    $gradleWrapperPath = Join-Path $env:USERPROFILE ".gradle\wrapper\dists\gradle-8.11.1-bin"
    $gradleBatPath = Join-Path $gradleWrapperPath "*\gradle-8.11.1\bin\gradle.bat"
    & $gradleBatPath --stop 2>$null
} catch {
    Write-Host "Could not stop Gradle daemons (this is normal if no daemons are running)" -ForegroundColor Yellow
}

# Clean Gradle cache using dynamic paths
Write-Host "[CLEANUP] Cleaning Gradle cache..." -ForegroundColor Yellow
$gradleCacheDir = Join-Path $env:USERPROFILE ".gradle\caches"
if (Test-Path $gradleCacheDir) { Remove-Item -Path $gradleCacheDir -Recurse -Force -ErrorAction SilentlyContinue }
$gradleWrapperDir = Join-Path $env:USERPROFILE ".gradle\wrapper"
if (Test-Path $gradleWrapperDir) { Remove-Item -Path $gradleWrapperDir -Recurse -Force -ErrorAction SilentlyContinue }
$gradleDaemonDir = Join-Path $env:USERPROFILE ".gradle\daemon"
if (Test-Path $gradleDaemonDir) { Remove-Item -Path $gradleDaemonDir -Recurse -Force -ErrorAction SilentlyContinue }

# Clean Flutter build directories using Python-provided paths
Write-Host "[CLEANUP] Cleaning Flutter build directories..." -ForegroundColor Yellow
flutter clean
Remove-Item -Path "build" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path ".dart_tool" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path "android\.gradle" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path "android\build" -Recurse -Force -ErrorAction SilentlyContinue

# Clean additional cache directories
Write-Host "[CLEANUP] Cleaning additional cache directories..." -ForegroundColor Yellow
$rootCacheDir = Join-Path (Get-Location) "cache"
if (Test-Path $rootCacheDir) {
    try {
        Remove-Item $rootCacheDir -Recurse -Force
        Write-Host "[CLEANUP] Removed root cache directory" -ForegroundColor Gray
    } catch {
        Write-Host "[CLEANUP] Could not remove root cache directory" -ForegroundColor Yellow
    }
}

# Get Flutter packages
Write-Host "[CLEANUP] Getting Flutter packages..." -ForegroundColor Yellow
flutter pub get

Write-Host "[CLEANUP] Comprehensive cleanup completed!" -ForegroundColor Green
