const IMAGE_MODULES = import.meta.glob<string>('./images/*.webp', { eager: true, import: 'default' });
const ICON_MODULES = import.meta.glob<string>('./icons/*.webp', { eager: true, import: 'default' });
const IMAGE_DIRECTORY = './images/';
const ICON_DIRECTORY = './icons/';
const ASSET_EXTENSION = '.webp';

export interface CmImageSpec {
  width: number;
  height: number;
  /** cm locale key of the alt text; null marks a decorative image (empty alt). */
  altKey: string | null;
  /** Below the fold where it is used: loaded lazily unless the caller asks for eager loading. */
  lazy: boolean;
}

export interface CmImageAsset extends CmImageSpec {
  src: string;
}

/** Illustrations generated by generate_cm_images.py into assets/images/. */
const CM_IMAGE_SPECS = {
  'hero-delivery': { width: 1280, height: 720, altKey: 'publicHome.hero.slide1Alt', lazy: false },
  'hero-marketplace': { width: 1280, height: 720, altKey: 'publicHome.hero.slide2Alt', lazy: false },
  'hero-escrow': { width: 1280, height: 720, altKey: 'publicHome.hero.slide3Alt', lazy: false },
  'about-mission': { width: 960, height: 720, altKey: 'infoPages.about.intro.alt', lazy: false },
  'service-managed': { width: 720, height: 540, altKey: null, lazy: true },
  'service-marketplace': { width: 720, height: 540, altKey: null, lazy: true },
  'service-review': { width: 720, height: 540, altKey: null, lazy: true },
  'service-escrow': { width: 720, height: 540, altKey: null, lazy: true },
  'process-overview': { width: 1280, height: 720, altKey: 'infoPages.delivery.overview.alt', lazy: false },
  'estimate-calculator': { width: 720, height: 540, altKey: 'estimate.imageAlt', lazy: false },
  'showcase-projects': { width: 1280, height: 720, altKey: null, lazy: false },
  'auth-welcome': { width: 720, height: 960, altKey: null, lazy: false },
  'download-devices': { width: 900, height: 675, altKey: 'downloadPage.features.alt', lazy: true },
  'contact-support': { width: 720, height: 540, altKey: 'infoPages.information.contactAlt', lazy: false },
  'empty-workspace': { width: 480, height: 480, altKey: null, lazy: true },
  'admin-console': { width: 1280, height: 720, altKey: null, lazy: false },
} as const satisfies Record<string, CmImageSpec>;

/** Icon set generated into assets/icons/ (navigation, feature, category and empty-state icons). */
const CM_ICON_SPECS = {} as const satisfies Record<string, CmImageSpec>;

export type CmImageName = keyof typeof CM_IMAGE_SPECS;
export type CmIconName = keyof typeof CM_ICON_SPECS;

function resolveAsset(modules: Record<string, string>, directory: string, name: string, spec: CmImageSpec): CmImageAsset | null {
  const src = modules[`${directory}${name}${ASSET_EXTENSION}`];
  return src ? { ...spec, src } : null;
}

/** Bundled illustration by name, or null while its file is not generated yet. */
export function cmImage(name: CmImageName): CmImageAsset | null {
  return resolveAsset(IMAGE_MODULES, IMAGE_DIRECTORY, name, CM_IMAGE_SPECS[name]);
}

/** Bundled icon by name, or null while its file is not generated yet. */
export function cmIcon(name: CmIconName): CmImageAsset | null {
  return resolveAsset(ICON_MODULES, ICON_DIRECTORY, name, CM_ICON_SPECS[name]);
}
