<!-- 
  This file was automatically generated by switch-app-entry.js
<<<<<<< HEAD
  Source: pages/index.pymatrix.vue
  Generated at: 2025-11-03T21:17:11.362Z
  App Entry: pymatrix
  
  DO NOT EDIT THIS FILE DIRECTLY
  Edit pages/index.pymatrix.vue instead
-->
<!--
  PYMATRIX PAGE - SIMPLIFIED

  This page now only contains the content area (device grid).
  All navigation components (TopBar, LeftPanel, RightPanel) are in the layout.
=======
  Source: pages/index.example.vue
  Generated at: 2025-11-03T16:19:16.818Z
  App Entry: example
  
  DO NOT EDIT THIS FILE DIRECTLY
  Edit pages/index.example.vue instead
-->
<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
    <div class="container mx-auto px-4 py-16">
      <!-- Header -->
      <div class="text-center mb-16">
        <h1 class="text-5xl font-bold text-gray-900 mb-4">
          Core Node Platform
        </h1>
        <p class="text-xl text-gray-600 mb-8">
          Multi-Application Entry Point System
        </p>
        <div class="flex items-center justify-center space-x-4">
          <span class="px-4 py-2 bg-blue-100 text-blue-800 rounded-full text-sm font-medium">
            Fallback Index Page
          </span>
          <span class="px-4 py-2 bg-yellow-100 text-yellow-800 rounded-full text-sm font-medium">
            Redirecting...
          </span>
        </div>
      </div>

      <!-- Example App Content -->
      <div class="max-w-4xl mx-auto">
        <h2 class="text-3xl font-semibold text-gray-900 text-center mb-12">
          Example Application Features
        </h2>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-8">
          <!-- Data Sources -->
          <NuxtLink
            to="/datasources-admin"
            class="block p-8 bg-white rounded-xl shadow-lg hover:shadow-xl transition-shadow border-2 border-transparent hover:border-blue-500"
          >
            <div class="text-center">
              <div class="text-6xl mb-4">🗄️</div>
              <h3 class="text-xl font-semibold text-gray-900 mb-2">Data Sources</h3>
              <p class="text-gray-600">Manage data connections</p>
            </div>
          </NuxtLink>

          <!-- Dashboard -->
          <NuxtLink
            to="/mainsite-dashboard"
            class="block p-8 bg-white rounded-xl shadow-lg hover:shadow-xl transition-shadow border-2 border-transparent hover:border-green-500"
          >
            <div class="text-center">
              <div class="text-6xl mb-4">📊</div>
              <h3 class="text-xl font-semibold text-gray-900 mb-2">Dashboard</h3>
              <p class="text-gray-600">View analytics and reports</p>
            </div>
          </NuxtLink>

          <!-- Components -->
          <div class="p-8 bg-white rounded-xl shadow-lg border-2 border-transparent">
            <div class="text-center">
              <div class="text-6xl mb-4">🧩</div>
              <h3 class="text-xl font-semibold text-gray-900 mb-2">Components</h3>
              <p class="text-gray-600">UI component examples</p>
            </div>
          </div>
        </div>

        <!-- App Switching Info -->
        <div class="bg-blue-50 rounded-lg p-6">
          <h2 class="text-xl font-semibold text-gray-900 mb-4">Application Switching</h2>
          <p class="text-gray-700 mb-4">
            To switch between applications, use the command line scripts:
          </p>
          <div class="bg-white rounded-lg p-4 font-mono text-sm">
            <div class="space-y-2">
              <div><span class="text-blue-600">yarn dev:example</span> - Switch to Example App (current)</div>
              <div><span class="text-green-600">yarn dev:codemart</span> - Switch to CodeMart App</div>
              <div><span class="text-purple-600">yarn dev:dev</span> - Switch to Dev Tools App</div>
              <div><span class="text-red-600">yarn dev:admin</span> - Switch to Admin App</div>
              <div><span class="text-indigo-600">yarn dev:dashboard</span> - Switch to Dashboard App</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
>>>>>>> 69335e7eef0a6931b106b558e8f7443958785c84

  Key: definePageMeta specifies to use the custom PyMatrix layout.
-->
<script setup lang="ts">
<<<<<<< HEAD
import { computed } from 'vue';
import { useDeviceStore } from '~/apps/app_pymatrix/stores_app_pymatrix/deviceStore';
import { useGroupStore } from '~/apps/app_pymatrix/stores_app_pymatrix/groupStore';

import PyMatrixDeviceGrid from '~/apps/app_pymatrix/components_app_pymatrix/PyMatrixDeviceGrid.vue';
import PyMatrixEmptyState from '~/apps/app_pymatrix/components_app_pymatrix/PyMatrixEmptyState.vue';
=======
import { ref, onMounted } from 'vue';
import { getAppEntryConfig } from '@/app-entry';
>>>>>>> 69335e7eef0a6931b106b558e8f7443958785c84

// Page metadata
definePageMeta({
<<<<<<< HEAD
  layout: 'pymatrix'
});

useHead({
  title: 'pyMatrix - Device Control',
  meta: [
    { name: 'description', content: 'Android device mirroring and group control system' }
  ]
});

const deviceStore = useDeviceStore();
const groupStore = useGroupStore();

const baseUrl = computed(() => 'ws://localhost:8000');

async function handleDisconnect(serial: string) {
  try {
    const response = await fetch(`http://localhost:8000/api/devices/${serial}/disconnect`, {
      method: 'POST'
    });

    const data = await response.json();

    if (data.success) {
      deviceStore.removeDevice(serial);

      if (groupStore.isHost(serial)) {
        if (groupStore.hostSerial) {
          deviceStore.updateDevice(groupStore.hostSerial, { isHost: false });
        }
        groupStore.destroyGroup();
      } else if (groupStore.isSlave(serial)) {
        groupStore.removeSlave(serial);
      }
    }
  } catch (error) {
    console.error('Disconnect error:', error);
  }
}
</script>

<template>
  <div class="pymatrix-content">
    <!-- Device Grid - only content, navigation is in layout -->
    <PyMatrixDeviceGrid
      v-if="deviceStore.deviceCount > 0"
      :devices="deviceStore.deviceList"
      :base-url="baseUrl"
      :group-enabled="groupStore.enabled"
      @disconnect="handleDisconnect"
    />

    <!-- Empty State - when no devices connected -->
    <PyMatrixEmptyState
      v-else
      @connect-device="() => {}"
    />
  </div>
</template>

<style scoped>
.pymatrix-content {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
}
</style>
=======
  title: 'Example App Home',
  layout: 'default',
  namespace: 'example'
});

// App configuration
const appConfig = ref(getAppEntryConfig('example'));

// Lifecycle
onMounted(() => {
  console.log('Example App Index loaded', appConfig.value);
});
</script>

<style scoped>
/* Custom styles for the app selector */
</style>
>>>>>>> 69335e7eef0a6931b106b558e8f7443958785c84
