<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\DotCore.Foundations\DotCore.Foundations.csproj" />
    <ProjectReference Include="..\..\DotCore.Common\DotCore.Common.csproj" />
    <ProjectReference Include="..\..\DotCore.Utils\DotCore.Utils.csproj" />
  </ItemGroup>
</Project>
