#!/bin/bash
# Workspace Shortcut Installer (terminal grid + apps)
#
# Creates a cross-desktop-environment shortcut (application menu + every user's
# Desktop) whose click opens a developer workspace. Idempotent on each click:
#   1. Opens a 4-column x 3-row grid (12) of native terminals via the pycore
#      launcher (pycore.pyutils.launcher) -- on X11 as separate positioned
#      windows, on Wayland as one kitty/tmux paned window. SKIPPED when more than
#      12 terminal windows are already open (never stacks a second grid).
#   2. Starts Chrome, WeChat and Cursor -- each only when installed AND not already
#      running. An already-running app is skipped; the others still start.
#
# The grid size (4x3) is forced via WindowLauncher's public API, independent of the
# launcher's shared config.json. Apps are detected by their freedesktop .desktop
# entry + pgrep and launched via that entry's Exec, so each app's configured
# wrappers apply (Chrome RAM/CPU rlimit cap, Cursor pkexec/--no-sandbox, WeChat
# sandbox workaround). Works on Debian / Ubuntu / Kali.
#
# IDEMPOTENT: the helper is overwritten in place, the .desktop entry is upserted by
# the shared desktop_shortcut_manager, and prerequisites are skipped when present.
# NON-FATAL: a missing tool/python only degrades the launch; install never aborts.
#
# Usage:
#   ./152_install_terminal_grid_shortcut.sh
#
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

set -o pipefail

# Script identification and path setup
SCRIPT_INDEX="152"
SCRIPT_CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR_LEVEL_1="$(dirname "$SCRIPT_CURRENT_DIR")"
PARENT_DIR_LEVEL_2="$(dirname "$PARENT_DIR_LEVEL_1")"

# Source global variables and shared helpers
source "$PARENT_DIR_LEVEL_2/common/gvar_common.sh"
source "$PARENT_DIR_LEVEL_2/common/common_functions.sh"
source "$PARENT_DIR_LEVEL_2/common/app_paths.sh"
source "$PARENT_DIR_LEVEL_2/common/desktop_shortcut_manager.sh"

# Initialize global variables (sets USE_SUDO, etc.)
init_global_vars

# ---- variable declarations (all at top) -------------------------------------
GRID_COLUMNS=4
GRID_ROWS=3
GRID_TOTAL=$((GRID_COLUMNS * GRID_ROWS))
CORE_NODE_ROOT="$CORE_NODE_ROOT_FROM_SCRIPTS"
LAUNCHER_PY="$CORE_NODE_ROOT/pycore/pyutils/launcher/launcher.py"
ICON_PATH="$CORE_NODE_ROOT/pycore/pyutils/launcher/icon.png"
HELPER_PATH="/usr/local/bin/devlauncher"
SHORTCUT_ID="pylauncher"
SHORTCUT_NAME="PyLauncher"
OLD_HELPER_PATH="/usr/local/bin/core-node-terminal-grid"
OLD_SHORTCUT_ID="core-node-terminal-grid"
PYTHON_BIN=""
SUDO=""

# Privilege prefix: prefer the gvar_common-provided USE_SUDO; else derive it.
if [ -n "${USE_SUDO+x}" ]; then
    SUDO="$USE_SUDO"
elif [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
fi

# Resolve the interpreter: prefer the project venv python, fall back to python3.
if [ -x /usr/local/bin/python ]; then
    PYTHON_BIN="/usr/local/bin/python"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
else
    PYTHON_BIN="python3"
fi

# ---- functions --------------------------------------------------------------

# Install grid shortcut prerequisites inline (launcher is a separate script in the
# numbered sweep / prepare_pycore_prerequisites.sh — do not call it from here).
ensure_launcher_prerequisites() {
    if command -v wt.exe >/dev/null 2>&1 || command -v wt >/dev/null 2>&1; then
        echo "[grid] Windows Terminal (wt) present."
        return 0
    fi
    echo "[grid] [i] wt not on PATH; run 105_install_launcher.sh or prepare_pycore_prerequisites.sh separately."
    return 0
}

# Write the tiny launch helper that the .desktop Exec points at. It forces the
# 4x3 grid through WindowLauncher's public API, bypassing the interactive menu and
# the Windows-only shortcut/bat preamble in launcher.main().
write_launch_helper() {
    # Header: shebang + baked configuration (expanded at install time).
    $SUDO tee "$HELPER_PATH" >/dev/null <<EOF
#!/bin/bash
# Core Node workspace launcher (generated by ${SCRIPT_INDEX}_install_terminal_grid_shortcut.sh).
# Re-run that installer to refresh. Baked configuration:
CORE_NODE_ROOT="${CORE_NODE_ROOT}"
PYTHON_BIN="${PYTHON_BIN}"
GRID_COLUMNS="${GRID_COLUMNS}"
GRID_ROWS="${GRID_ROWS}"
GRID_TOTAL="${GRID_TOTAL}"
EOF
    # Body: literal logic (appended verbatim; references the vars baked above).
    $SUDO tee -a "$HELPER_PATH" >/dev/null <<'EOF'
# Idempotent click behavior (Debian / Ubuntu / Kali):
#   1. TOP UP the terminal grid to GRID_TOTAL: if that many terminal windows are
#      already open, skip; otherwise open only the missing count (the deficit),
#      laid out GRID_COLUMNS x GRID_ROWS with auto gaps between rows and columns.
#   2. Start Chrome / WeChat / Cursor: each only when installed AND not running.
#      Already-running ones are skipped; the others still start.
# Each app is launched the way its prerequisite installer configured it, REUSING
# any prior CPU/memory cap: prefer /usr/local/bin/<id>-rlimit (the cgroup wrapper),
# else the app's .desktop Exec (install-logic binary; already the rlimit wrapper
# for Chrome), else a known fallback binary. "running" = exact comm (pgrep -x).
set -o pipefail
APP_DIRS="/usr/share/applications $HOME/.local/share/applications"
RLIMIT_DIR="/usr/local/bin"
TERM_CLASSES='qterminal|gnome-terminal|xfce4-terminal|konsole|xterm|kitty|terminator|tilix|alacritty|lxterminal|mate-terminal|deepin-terminal|st-256color'

# Count currently-open terminal-emulator windows (X11 via wmctrl), else processes.
count_terminals() {
    if command -v wmctrl >/dev/null 2>&1; then
        wmctrl -lx 2>/dev/null | awk '{print tolower($3)}' | grep -Ec "$TERM_CLASSES"
    else
        ps -e -o comm= 2>/dev/null | grep -Eic "^($TERM_CLASSES)$"
    fi
}

# Print the first existing .desktop among the given ids (system, then per-user).
find_desktop() {
    local id d
    for id in "$@"; do
        for d in $APP_DIRS; do
            [ -f "$d/$id.desktop" ] && { printf '%s' "$d/$id.desktop"; return 0; }
        done
    done
    return 1
}

# Print the [Desktop Entry] Exec line with field codes (%U %F ...) stripped.
desktop_exec() {
    awk '
        /^\[/ { entry = ($0 == "[Desktop Entry]") }
        entry && /^Exec=/ { sub(/^Exec=/, ""); print; exit }
    ' "$1" | sed -E 's/%[fFuUdDnNickvm]//g; s/[[:space:]]+$//'
}

# Launch a command fully detached from this script / the clicking session.
launch_detached() {
    if command -v setsid >/dev/null 2>&1; then
        setsid bash -c "$1" >/dev/null 2>&1 < /dev/null &
    else
        nohup bash -c "$1" >/dev/null 2>&1 < /dev/null &
    fi
}

# Resolve an app's launch command, REUSING its previously-configured resource cap:
#   1) /usr/local/bin/<stem>-rlimit if present (the cgroup CPU/memory wrapper),
#   2) else the .desktop Exec (install-logic binary; the rlimit wrapper for Chrome),
#   3) else the first fallback binary on PATH.
resolve_launch_cmd() {  # $1=rlimit stem  $2=.desktop file ("")  $3=fallback bins
    local stem="$1" dfile="$2" fb="$3" wrapper ex b
    wrapper="$RLIMIT_DIR/${stem}-rlimit"
    if [ -x "$wrapper" ]; then printf '%s' "$wrapper"; return 0; fi
    if [ -n "$dfile" ]; then
        ex="$(desktop_exec "$dfile")"
        [ -n "$ex" ] && { printf '%s' "$ex"; return 0; }
    fi
    for b in $fb; do command -v "$b" >/dev/null 2>&1 && { command -v "$b"; return 0; }; done
    return 1
}

# start_app <label> <rlimit-stem> <comma .desktop ids> <pgrep test> <fallback bins>
# "running" uses exact comm matching (pgrep -x), which cannot false-match a shell
# whose argv merely mentions the app. Chrome/Cursor/WeChat are single-instance, so
# an occasional under-detection just focuses the existing window -- never a dupe.
start_app() {
    local label="$1" stem="$2" ids="$3" runtest="$4" fb="$5" dfile cmd
    dfile="$(find_desktop ${ids//,/ })" || dfile=""
    cmd="$(resolve_launch_cmd "$stem" "$dfile" "$fb")" || { echo "[apps] $label: not installed -> skip"; return 0; }
    if eval "$runtest" >/dev/null 2>&1; then echo "[apps] $label: already running -> skip"; return 0; fi
    echo "[apps] $label: starting -> $cmd"
    launch_detached "$cmd"
}

# 1) Terminal grid -- top up to GRID_TOTAL (open only the deficit; skip if enough).
open_now="$(count_terminals 2>/dev/null)"; [ -n "$open_now" ] || open_now=0
deficit=$(( GRID_TOTAL - open_now ))
if [ "$deficit" -le 0 ]; then
    echo "[grid] $open_now terminals already open (>= $GRID_TOTAL) -> enough, skip"
else
    echo "[grid] $open_now open; topping up $deficit to reach $GRID_TOTAL (${GRID_COLUMNS}x${GRID_ROWS})"
    cd "$CORE_NODE_ROOT" 2>/dev/null || true
    # PYCORE_SKIP_DEP_CHECK=1: importing pycore triggers third_party.py's import-time
    # dependency check (which can kick off the multi-GB torch (re)install). The launcher only
    # opens terminal windows and needs no heavy deps, so skip that here — it must never run
    # the package installer against this user's site as a side effect of launching a grid.
    PYCORE_SKIP_DEP_CHECK=1 PYTHONPATH="$CORE_NODE_ROOT${PYTHONPATH:+:$PYTHONPATH}" "$PYTHON_BIN" -c \
        "from pycore.pyutils.launcher.launcher import WindowLauncher; WindowLauncher(grid_columns=$GRID_COLUMNS, grid_rows=$GRID_ROWS).launch_windows(limit=$deficit)" \
        >/dev/null 2>&1 || echo "[grid] launcher returned non-zero (continuing)"
fi

# 2) Apps: each only if installed and not already running (others still start).
start_app "Chrome" "google-chrome" "google-chrome,com.google.Chrome,chromium,chromium-browser" "pgrep -x chrome || pgrep -x chromium || pgrep -x chromium-browser" "google-chrome-stable google-chrome chromium chromium-browser"
start_app "WeChat" "wechat" "wechat,com.tencent.wechat" "pgrep -x wechat" "wechat"
start_app "Cursor" "cursor" "cursor" "pgrep -x cursor" "cursor"

exit 0
EOF
    $SUDO chmod 0755 "$HELPER_PATH" 2>/dev/null || true
    echo "[grid] Launch helper: $HELPER_PATH"
}

# Remove artifacts from the previous shortcut id / helper path (rename migration),
# so re-running does not leave a stale entry/helper behind. Idempotent.
remove_old_artifacts() {
    [ "$OLD_SHORTCUT_ID" != "$SHORTCUT_ID" ] || return 0
    if command -v remove_desktop_shortcut_from_desktop_shortcut_manager >/dev/null 2>&1; then
        remove_desktop_shortcut_from_desktop_shortcut_manager --id "$OLD_SHORTCUT_ID" >/dev/null 2>&1 || true
    fi
    [ -e "$OLD_HELPER_PATH" ] && { $SUDO rm -f "$OLD_HELPER_PATH" 2>/dev/null || true; }
}

# Create (or idempotently update) the cross-DE shortcut: app menu + every user's
# Desktop. Terminal=false: clicking spawns the grid + apps directly (no extra
# console). The grid terminals and app windows are the visible result.
create_grid_shortcut() {
    local icon_arg
    if ! command -v create_desktop_shortcut_from_desktop_shortcut_manager >/dev/null 2>&1; then
        echo "[grid] desktop_shortcut_manager not loaded; skipping shortcut." >&2
        return 0
    fi
    if [ -f "$ICON_PATH" ]; then
        icon_arg="$ICON_PATH"
    else
        icon_arg="utilities-terminal"
    fi
    create_desktop_shortcut_from_desktop_shortcut_manager \
        --id "$SHORTCUT_ID" \
        --name "$SHORTCUT_NAME" \
        --generic "Developer Workspace" \
        --comment "Top up a ${GRID_COLUMNS}x${GRID_ROWS} terminal grid (${GRID_TOTAL} total) and start Chrome, WeChat, Cursor if not already running" \
        --exec "$HELPER_PATH" \
        --icon "$icon_arg" \
        --categories "System;Utility;TerminalEmulator;Development;" \
        --keywords "terminal;grid;launcher;pycore;workspace;chrome;wechat;cursor;${GRID_COLUMNS}x${GRID_ROWS};" \
        --desktop all
}

# ---- main -------------------------------------------------------------------
main() {
    echo "============================================================"
    echo " Installing PyLauncher shortcut -> $HELPER_PATH"
    echo " (${GRID_COLUMNS}x${GRID_ROWS} terminal grid top-up + Chrome/WeChat/Cursor)"
    echo "============================================================"

    if [ ! -f "$LAUNCHER_PY" ]; then
        echo "[grid] Launcher module not found at $LAUNCHER_PY; nothing to do." >&2
        exit 0
    fi

    ensure_launcher_prerequisites
    remove_old_artifacts
    write_launch_helper
    create_grid_shortcut

    echo "[grid] Done. Launch from the application menu or the desktop icon: \"$SHORTCUT_NAME\"."
    exit 0
}

main "$@"
