/**
 * Extended Mock Data for Multi-Role System
 * New System - All financial data starts at 0, calculated dynamically
 */
import {
  AppStatus,
  AppCategory,
  UserRole,
  AppInstance,
  CustomerService,
  TechMember,
  DailyStat,
  CSAppRevenue,
  AppGenerationRequest,
  User,
  PromotionTrack,
  AppRelease,
  PromotionRecord,
  Promoter,
  LocationRecord,
  Notification,
  Bug,
  Build,
  ChatSession,
  ChatMessage,
  ScriptTemplate,
  PaymentVerificationRequest,
  AvatarProvider,
  AvatarProvidersListResponse,
  AvatarCacheStatsResponse,
} from './types';
import { CSLevel, getCommissionRateByLevel, SYSTEM_INIT_DATE } from './constants/modelConstants';

/**
 * Avatar seed helper - stores only seed, not full URL
 * Full URL is generated dynamically at runtime using avatarUtils.generateAvatarUrl()
 */
const getAvatarSeed = (seed: string): string => seed;

// Admin Users - Fixed real Chinese names
export const MOCK_ADMINS: User[] = [
  {
    id: 'admin1',
    name: '王建国',
    email: 'admin@multichat.com',
    role: UserRole.ADMIN,
    avatar: getAvatarSeed('admin1'),
    phone: '13800000001',
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
  },
];

// Customer Service Team (New System - All financial data starts at 0)
// Fixed real Chinese names - no random generation
export const MOCK_CS: CustomerService[] = [
  {
    id: 'cs1',
    name: '李淑芬',
    email: 'cs1@multichat.com',
    role: UserRole.CS,
    avatar: getAvatarSeed('cs1'),
    status: 'Online',
    totalEarnings: 0, // Calculated dynamically
    assignedAppIds: ['app1', 'app2'],
    commissionRate: getCommissionRateByLevel(CSLevel.SENIOR),
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
    photo: getAvatarSeed('cs1'),
    contact: '13800001001',
    joinDate: SYSTEM_INIT_DATE,
    level: CSLevel.SENIOR,
    nickname: '小雨',
    businessAmount: 0, // Calculated dynamically
    commissionAmount: 0, // Calculated dynamically
    commissionPercentage: getCommissionRateByLevel(CSLevel.SENIOR),
    totalPrice: 0, // Calculated dynamically
    totalDeduction: 0, // Calculated dynamically
    totalSettlement: 0, // Calculated dynamically
    approverId: 'admin1',
    approverName: MOCK_ADMINS[0].name,
    settledAmount: 0, // Calculated dynamically
    unsettledAmount: 0, // Calculated dynamically
    paymentAddress: undefined,
  },
  {
    id: 'cs2',
    name: '张建宏',
    email: 'cs2@multichat.com',
    role: UserRole.CS,
    avatar: getAvatarSeed('cs2'),
    status: 'Online',
    totalEarnings: 0,
    assignedAppIds: ['app2', 'app3'],
    commissionRate: getCommissionRateByLevel(CSLevel.INTERMEDIATE),
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
    photo: getAvatarSeed('cs2'),
    contact: '13800001002',
    joinDate: SYSTEM_INIT_DATE,
    level: CSLevel.INTERMEDIATE,
    nickname: '小云',
    businessAmount: 0,
    commissionAmount: 0,
    commissionPercentage: getCommissionRateByLevel(CSLevel.INTERMEDIATE),
    totalPrice: 0,
    totalDeduction: 0,
    totalSettlement: 0,
    approverId: 'admin1',
    approverName: MOCK_ADMINS[0].name,
    settledAmount: 0,
    unsettledAmount: 0,
    paymentAddress: undefined,
  },
  {
    id: 'cs3',
    name: '刘美玲',
    email: 'cs3@multichat.com',
    role: UserRole.CS,
    avatar: getAvatarSeed('cs3'),
    status: 'Offline',
    totalEarnings: 0,
    assignedAppIds: ['app1', 'app4'],
    commissionRate: getCommissionRateByLevel(CSLevel.JUNIOR),
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
    photo: getAvatarSeed('cs3'),
    contact: '13800001003',
    joinDate: SYSTEM_INIT_DATE,
    level: CSLevel.JUNIOR,
    nickname: '小月',
    businessAmount: 0,
    commissionAmount: 0,
    commissionPercentage: getCommissionRateByLevel(CSLevel.JUNIOR),
    totalPrice: 0,
    totalDeduction: 0,
    totalSettlement: 0,
    approverId: 'admin1',
    approverName: MOCK_ADMINS[0].name,
    settledAmount: 0,
    unsettledAmount: 0,
    paymentAddress: undefined,
  },
  {
    id: 'cs4',
    name: '陈志明',
    email: 'cs4@multichat.com',
    role: UserRole.CS,
    avatar: getAvatarSeed('cs4'),
    status: 'Online',
    totalEarnings: 0,
    assignedAppIds: ['app3', 'app5'],
    commissionRate: getCommissionRateByLevel(CSLevel.SENIOR),
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
    photo: getAvatarSeed('cs4'),
    contact: '13800001004',
    joinDate: SYSTEM_INIT_DATE,
    level: CSLevel.SENIOR,
    nickname: '小星',
    businessAmount: 0,
    commissionAmount: 0,
    commissionPercentage: getCommissionRateByLevel(CSLevel.SENIOR),
    totalPrice: 0,
    totalDeduction: 0,
    totalSettlement: 0,
    approverId: 'admin1',
    approverName: MOCK_ADMINS[0].name,
    settledAmount: 0,
    unsettledAmount: 0,
    paymentAddress: undefined,
  },
  {
    id: 'cs5',
    name: '杨雅婷',
    email: 'cs5@multichat.com',
    role: UserRole.CS,
    avatar: getAvatarSeed('cs5'),
    status: 'Online',
    totalEarnings: 0,
    assignedAppIds: ['app6', 'app7'],
    commissionRate: getCommissionRateByLevel(CSLevel.INTERMEDIATE),
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
    photo: getAvatarSeed('cs5'),
    contact: '13800001005',
    joinDate: SYSTEM_INIT_DATE,
    level: CSLevel.INTERMEDIATE,
    nickname: '小阳',
    businessAmount: 0,
    commissionAmount: 0,
    commissionPercentage: getCommissionRateByLevel(CSLevel.INTERMEDIATE),
    totalPrice: 0,
    totalDeduction: 0,
    totalSettlement: 0,
    approverId: 'admin1',
    approverName: MOCK_ADMINS[0].name,
    settledAmount: 0,
    unsettledAmount: 0,
    paymentAddress: undefined,
  },
];

// Technical Team (New System) - Fixed real Chinese names
export const MOCK_TECH: TechMember[] = [
  {
    id: 'tech1',
    name: '黄家豪',
    email: 'tech1@multichat.com',
    role: UserRole.TECH,
    avatar: getAvatarSeed('tech1'),
    specialization: 'Frontend',
    appsGenerated: 0, // New system starts at 0
    status: 'Available',
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
  },
  {
    id: 'tech2',
    name: '赵美惠',
    email: 'tech2@multichat.com',
    role: UserRole.TECH,
    avatar: getAvatarSeed('tech2'),
    specialization: 'Backend',
    appsGenerated: 0,
    status: 'Available',
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
  },
  {
    id: 'tech3',
    name: '吴俊杰',
    email: 'tech3@multichat.com',
    role: UserRole.TECH,
    avatar: getAvatarSeed('tech3'),
    specialization: 'DevOps',
    appsGenerated: 0,
    status: 'Available',
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
  },
  {
    id: 'tech4',
    name: '周淑惠',
    email: 'tech4@multichat.com',
    role: UserRole.TECH,
    avatar: getAvatarSeed('tech4'),
    specialization: 'Full Stack',
    appsGenerated: 0,
    status: 'Available',
    createdAt: SYSTEM_INIT_DATE,
    lastLogin: undefined,
  },
];

// Extended APP Instances (New System - starts fresh)
export const MOCK_APPS: AppInstance[] = [
  {
    id: 'app1',
    name: '多聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0, // New system starts at 0
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '多人在线聊天社交平台，支持群聊、语音、视频通话',
    assignedCSIds: ['cs1', 'cs3'],
    assignedTechId: 'tech1',
    features: ['群聊', '语音通话', '视频通话', '表情包', '文件传输'],
    targetAudience: '社交用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined, // No rating yet in new system
    icon: '/encrypted_assets/app_icon1.en.js',
    splash: '/encrypted_assets/app_splash1.en.js',
  },
  {
    id: 'app2',
    name: '爱聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '专注于情感交流的聊天应用，寻找心灵伴侣',
    assignedCSIds: ['cs1', 'cs2'],
    assignedTechId: 'tech2',
    features: ['匹配推荐', '语音聊天', '情感分析', '隐私保护'],
    targetAudience: '寻找伴侣的用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
    icon: '/encrypted_assets/app_icon2.en.js',
    splash: '/encrypted_assets/app_splash2.en.js',
  },
  {
    id: 'app3',
    name: '夜聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '夜间专属聊天社区，深夜陪伴，温暖心灵',
    assignedCSIds: ['cs2', 'cs4'],
    assignedTechId: 'tech4',
    features: ['夜间模式', '匿名聊天', '话题讨论', '情感支持'],
    targetAudience: '夜猫子用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
    icon: '/encrypted_assets/app_icon3.en.js',
    splash: '/encrypted_assets/app_splash3.en.js',
  },
  {
    id: 'app4',
    name: '心聊',
    status: AppStatus.PENDING,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '心灵交流平台，深度对话，寻找知音',
    assignedCSIds: ['cs3'],
    assignedTechId: 'tech3',
    features: ['深度对话', '心理测试', '情感咨询', '话题匹配'],
    targetAudience: '寻求深度交流的用户',
    rating: undefined,
    icon: '/encrypted_assets/app_icon4.en.js',
    splash: '/encrypted_assets/app_splash4.en.js',
  },
  {
    id: 'app5',
    name: '密聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '加密私密聊天应用，保护隐私，安全可靠',
    assignedCSIds: ['cs4'],
    assignedTechId: 'tech4',
    features: ['端到端加密', '阅后即焚', '私密空间', '安全传输'],
    targetAudience: '注重隐私的用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
    icon: '/encrypted_assets/app_icon5.en.js',
    splash: '/encrypted_assets/app_splash5.en.js',
  },
  {
    id: 'app6',
    name: '缘聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '缘分匹配聊天应用，AI智能推荐，遇见对的人',
    assignedCSIds: ['cs1', 'cs5'],
    assignedTechId: 'tech1',
    features: ['AI匹配', '缘分测试', '视频相亲', '情感分析'],
    targetAudience: '寻找缘分的用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
  },
  {
    id: 'app7',
    name: '甜聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '甜蜜恋爱聊天应用，情侣专属，记录美好时光',
    assignedCSIds: ['cs2', 'cs5'],
    assignedTechId: 'tech2',
    features: ['情侣空间', '纪念日提醒', '甜蜜日记', '情侣游戏'],
    targetAudience: '情侣用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
  },
  {
    id: 'app8',
    name: '暖聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '温暖陪伴聊天应用，倾听心声，给予温暖',
    assignedCSIds: ['cs3'],
    assignedTechId: 'tech3',
    features: ['情感陪伴', '心理疏导', '温暖社区', '正能量分享'],
    targetAudience: '需要陪伴的用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
  },
  {
    id: 'app9',
    name: '趣聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '趣味聊天社交应用，游戏互动，轻松愉快',
    assignedCSIds: ['cs4'],
    assignedTechId: 'tech4',
    features: ['趣味游戏', '语音互动', '表情包', '话题挑战'],
    targetAudience: '喜欢娱乐的用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
  },
  {
    id: 'app10',
    name: '悦聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '愉悦聊天社交平台，分享快乐，传递正能量',
    assignedCSIds: ['cs4'],
    assignedTechId: 'tech2',
    features: ['快乐分享', '正能量社区', '趣味话题', '心情日记'],
    targetAudience: '追求快乐的用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
  },
  {
    id: 'app11',
    name: '知聊',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '知识交流聊天应用，学习讨论，共同成长',
    assignedCSIds: ['cs5'],
    assignedTechId: 'tech1',
    features: ['知识分享', '学习小组', '专家答疑', '话题讨论'],
    targetAudience: '学习型用户',
    launchDate: SYSTEM_INIT_DATE,
    rating: undefined,
  },
  {
    id: 'app12',
    name: '情聊',
    status: AppStatus.GENERATING,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '情感交流聊天应用，表达真情，传递温暖',
    assignedCSIds: [],
    assignedTechId: 'tech2',
    features: ['情感表达', '真情告白', '情感故事', '温暖社区'],
    targetAudience: '情感交流用户',
    rating: undefined,
  },
  {
    id: 'app13',
    name: '友聊',
    status: AppStatus.IDLE,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '朋友聊天社交应用，保持联系，维系友谊',
    assignedCSIds: [],
    assignedTechId: 'tech3',
    features: ['好友圈', '群组聊天', '活动组织', '友谊记录'],
    targetAudience: '重视友谊的用户',
    rating: undefined,
  },
  {
    id: 'app14',
    name: '私聊',
    status: AppStatus.PENDING,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '私密聊天应用，一对一交流，保护隐私',
    assignedCSIds: [],
    assignedTechId: 'tech4',
    features: ['私密对话', '加密传输', '匿名聊天', '隐私保护'],
    targetAudience: '注重隐私的用户',
    rating: undefined,
  },
  {
    id: 'app15',
    name: '轻聊',
    status: AppStatus.FAILED,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
    description: '轻量级聊天应用，简洁界面，快速交流',
    assignedCSIds: [],
    assignedTechId: 'tech1',
    features: ['简洁界面', '快速启动', '轻量设计', '流畅体验'],
    targetAudience: '追求简洁的用户',
    rating: undefined,
  },
];

// CS-APP Revenue Tracking (Many-to-Many) - New System starts empty
export const MOCK_CS_APP_REVENUE: CSAppRevenue[] = [];

// Daily Statistics - New System starts empty (calculated dynamically)
export const MOCK_DAILY_STATS: DailyStat[] = [];

// APP Generation Requests - New System starts empty
export const MOCK_APP_REQUESTS: AppGenerationRequest[] = [];

// APP发布记录
// App Releases
// Note: appName is kept for backward compatibility but should be derived from central data sources
// Use getAppNameById() from utils/dataHelpers.ts to get names from central data
export const MOCK_APP_RELEASES: AppRelease[] = [];

// 推广轨迹记录 - New System starts empty
export const MOCK_PROMOTION_TRACKS: PromotionTrack[] = [];

// 推广人员 (New System - All financial data starts at 0) - Fixed real Chinese names
export const MOCK_PROMOTERS: Promoter[] = [
  {
    id: 'promoter1',
    name: '徐志强',
    photo: getAvatarSeed('promoter1'),
    contact: '13800002001',
    joinDate: SYSTEM_INIT_DATE,
    region: '北京大兴',
    totalValidCount: 0, // Calculated dynamically
    unitPrice: 50, // Constant from modelConstants
    totalPrice: 0, // Calculated dynamically
    totalDeduction: 0, // Calculated dynamically
    totalSettlement: 0, // Calculated dynamically
    approverId: 'admin1',
    approverName: MOCK_ADMINS[0].name,
    settledAmount: 0, // Calculated dynamically
    unsettledAmount: 0, // Calculated dynamically
    paymentAddress: undefined,
    recordIds: [], // New system starts empty
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
  {
    id: 'promoter2',
    name: '孙秀英',
    photo: getAvatarSeed('promoter2'),
    contact: '13800002002',
    joinDate: SYSTEM_INIT_DATE,
    region: '上海浦东',
    totalValidCount: 0,
    unitPrice: 50,
    totalPrice: 0,
    totalDeduction: 0,
    totalSettlement: 0,
    approverId: 'admin1',
    approverName: MOCK_ADMINS[0].name,
    settledAmount: 0,
    unsettledAmount: 0,
    paymentAddress: undefined,
    recordIds: [],
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
  {
    id: 'promoter3',
    name: '马文华',
    photo: getAvatarSeed('promoter3'),
    contact: '13800002003',
    joinDate: SYSTEM_INIT_DATE,
    region: '广州天河',
    totalValidCount: 0,
    unitPrice: 50,
    totalPrice: 0,
    totalDeduction: 0,
    totalSettlement: 0,
    approverId: 'admin1',
    approverName: MOCK_ADMINS[0].name,
    settledAmount: 0,
    unsettledAmount: 0,
    paymentAddress: undefined,
    recordIds: [],
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
];

// Promotion Records - New System starts empty
// Note: appName and promoterName are kept for backward compatibility but should be derived from central data sources
// Use getAppNameById() and getPromoterNameById() from utils/dataHelpers.ts to get names from central data
export const MOCK_PROMOTION_RECORDS: PromotionRecord[] = [
  // New system starts with no promotion records
  /* Example structure for reference:
  {
    id: 'record1',
    appId: 'app1',
    appName: '多聊',
    promoterId: 'promoter1',
    promoterName: '推广人员1',
    startTime: '2025-12-18 08:00:00',
    endTime: '2025-12-18 18:00:00',
    validCount: 0,
    unitPrice: 50,
    totalPrice: 0,
    deduction: 0,
    settlement: 0,
    isSettled: false,
    tracks: [],
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
  */
];

// Notifications - New System starts empty
export const MOCK_NOTIFICATIONS: Notification[] = [];

// Bugs - New System starts empty
export const MOCK_BUGS: Bug[] = [];

// Builds - New System starts empty
export const MOCK_BUILDS: Build[] = [];

// Chat Sessions
export const MOCK_CHAT_SESSIONS: ChatSession[] = [
  {
    id: 'session1',
    customerId: 'customer1',
    customerName: '张先生',
    customerAvatar: getAvatarSeed('customer1'),
    csId: 'cs1',
    csName: '李淑芬',
    appId: 'app1',
    appName: '多聊',
    status: 'active',
    lastMessage: '您好，我想了解一下这个产品的价格',
    lastMessageTime: new Date().toISOString(),
    unreadCount: 2,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'session2',
    customerId: 'customer2',
    customerName: '王女士',
    customerAvatar: getAvatarSeed('customer2'),
    csId: 'cs2',
    csName: '张建宏',
    appId: 'app2',
    appName: '爱聊',
    status: 'active',
    lastMessage: '谢谢您的帮助！',
    lastMessageTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    unreadCount: 0,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'session3',
    customerId: 'customer3',
    customerName: '李先生',
    customerAvatar: getAvatarSeed('customer3'),
    appId: 'app3',
    appName: '夜聊',
    status: 'waiting',
    lastMessage: '请问有人在线吗？',
    lastMessageTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    unreadCount: 1,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'session4',
    customerId: 'customer4',
    customerName: '刘小姐',
    customerAvatar: getAvatarSeed('customer4'),
    csId: 'cs3',
    csName: '刘美玲',
    appId: 'app1',
    appName: '多聊',
    status: 'active',
    lastMessage: '好的，我明白了',
    lastMessageTime: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'session5',
    customerId: 'customer5',
    customerName: '陈先生',
    customerAvatar: getAvatarSeed('customer5'),
    csId: 'cs4',
    csName: '陈志明',
    appId: 'app3',
    appName: '夜聊',
    status: 'active',
    lastMessage: '我想了解一下夜聊的功能',
    lastMessageTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    unreadCount: 0,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'session6',
    customerId: 'customer6',
    customerName: '赵女士',
    customerAvatar: getAvatarSeed('customer6'),
    csId: 'cs3',
    csName: '刘美玲',
    appId: 'app4',
    appName: '心聊',
    status: 'active',
    lastMessage: '我想找一个可以深度交流的平台',
    lastMessageTime: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    unreadCount: 1,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'session7',
    customerId: 'customer7',
    customerName: '孙先生',
    customerAvatar: getAvatarSeed('customer7'),
    csId: 'cs4',
    csName: '陈志明',
    appId: 'app5',
    appName: '密聊',
    status: 'active',
    lastMessage: '这个应用的隐私保护怎么样？',
    lastMessageTime: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    unreadCount: 0,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'session8',
    customerId: 'customer8',
    customerName: '周女士',
    customerAvatar: getAvatarSeed('customer8'),
    csId: 'cs1',
    csName: '李淑芬',
    appId: 'app6',
    appName: '缘聊',
    status: 'active',
    lastMessage: 'AI匹配功能真的很智能',
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    unreadCount: 0,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'session9',
    customerId: 'customer9',
    customerName: '吴先生',
    customerAvatar: getAvatarSeed('customer9'),
    csId: 'cs5',
    csName: '杨雅婷',
    appId: 'app6',
    appName: '缘聊',
    status: 'active',
    lastMessage: '谢谢你的推荐',
    lastMessageTime: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    unreadCount: 0,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'session10',
    customerId: 'customer10',
    customerName: '郑女士',
    customerAvatar: getAvatarSeed('customer10'),
    appId: 'app7',
    appName: '甜聊',
    status: 'waiting',
    lastMessage: '这个应用适合年轻人吗？',
    lastMessageTime: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    unreadCount: 1,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
];

// Chat Messages
export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg1',
    sessionId: 'session1',
    senderId: 'customer1',
    senderName: '张先生',
    senderType: 'customer',
    content: '您好，我想了解一下这个产品的价格',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg2',
    sessionId: 'session1',
    senderId: 'cs1',
    senderName: '李淑芬',
    senderType: 'cs',
    content: '您好！很高兴为您服务。请问您想了解哪个产品呢？',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000 + 1 * 60 * 1000).toISOString(),
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000 + 1 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg3',
    sessionId: 'session1',
    senderId: 'customer1',
    senderName: '张先生',
    senderType: 'customer',
    content: '我想了解多聊这个APP',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    isRead: true,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg4',
    sessionId: 'session1',
    senderId: 'cs1',
    senderName: '李淑芬',
    senderType: 'cs',
    content: '好的，多聊是一款非常优秀的社交应用，具有以下特点...',
    timestamp: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    isRead: false,
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg5',
    sessionId: 'session2',
    senderId: 'customer2',
    senderName: '王女士',
    senderType: 'customer',
    content: '谢谢您的帮助！',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    isRead: true,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'msg6',
    sessionId: 'session3',
    senderId: 'customer3',
    senderName: '李先生',
    senderType: 'customer',
    content: '请问有人在线吗？',
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    isRead: false,
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
];

// Script Templates
export const MOCK_SCRIPT_TEMPLATES: ScriptTemplate[] = [
  {
    id: 'script1',
    title: 'Greeting',
    content: '您好！欢迎咨询，我是{csName}，很高兴为您服务。请问有什么可以帮助您的吗？',
    category: 'greeting',
    tags: ['greeting', 'welcome'],
    usageCount: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
  {
    id: 'script2',
    title: 'Product Introduction',
    content: '我们的产品具有以下特点：1. 功能强大 2. 操作简单 3. 价格优惠。您想了解哪个方面呢？',
    category: 'product_info',
    tags: ['product', 'introduction'],
    usageCount: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
  {
    id: 'script3',
    title: 'Price Inquiry',
    content: '关于价格，我们目前有优惠活动，原价{originalPrice}，现在只需{currentPrice}。您觉得怎么样？',
    category: 'pricing',
    tags: ['price', 'discount'],
    usageCount: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
  {
    id: 'script4',
    title: 'Closing',
    content: '感谢您的咨询！如果您还有其他问题，随时可以联系我。祝您生活愉快！',
    category: 'closing',
    tags: ['closing', 'thanks'],
    usageCount: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
  {
    id: 'script5',
    title: 'Follow Up',
    content: '您好，我是{csName}，之前和您沟通过。请问您对我们的产品还有什么疑问吗？',
    category: 'follow_up',
    tags: ['follow_up', 'reminder'],
    usageCount: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
  {
    id: 'script6',
    title: 'Problem Solving',
    content: '我理解您的问题。让我来帮您解决这个问题。请稍等，我会尽快为您处理。',
    category: 'problem_solving',
    tags: ['problem', 'solution'],
    usageCount: 0,
    createdAt: SYSTEM_INIT_DATE,
    updatedAt: SYSTEM_INIT_DATE,
  },
];

// Payment Verification Requests
export const MOCK_PAYMENT_VERIFICATION_REQUESTS: PaymentVerificationRequest[] = [
  {
    id: 'pvr1',
    sessionId: 'session1',
    customerId: 'customer1',
    customerName: '张先生',
    customerAvatar: getAvatarSeed('customer1'),
    appId: 'app1',
    appName: '多聊',
    amount: 198,
    username: 'zhang123',
    status: 'pending',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pvr2',
    sessionId: 'session2',
    customerId: 'customer2',
    customerName: '王女士',
    customerAvatar: getAvatarSeed('customer2'),
    appId: 'app2',
    appName: '爱聊',
    amount: 698,
    screenshot: 'https://via.placeholder.com/400x300?text=Payment+Screenshot',
    status: 'pending',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'pvr3',
    sessionId: 'session4',
    customerId: 'customer4',
    customerName: '刘小姐',
    customerAvatar: getAvatarSeed('customer4'),
    appId: 'app1',
    appName: '多聊',
    amount: 3888,
    username: 'liu456',
    status: 'verified',
    reply: '您的款项已确认到账，感谢您的支持！',
    repliedBy: 'admin1',
    repliedByName: '王建国',
    repliedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

// Avatar Providers Mock Data
export const MOCK_AVATAR_PROVIDERS: AvatarProvider[] = [
  {
    short_code: 'pravatar',
    name: 'Pravatar',
    max_size: 512,
    supports_size: true,
    deterministic: false,
  },
  {
    short_code: 'dicebear',
    name: 'DiceBear (Avataaars)',
    max_size: 512,
    supports_size: true,
    deterministic: true,
  },
  {
    short_code: 'uiavatars',
    name: 'UI Avatars',
    max_size: 512,
    supports_size: true,
    deterministic: true,
  },
  {
    short_code: 'robohash',
    name: 'RoboHash',
    max_size: 512,
    supports_size: true,
    deterministic: true,
  },
  {
    short_code: 'gravatar',
    name: 'Gravatar',
    max_size: 2048,
    supports_size: true,
    deterministic: true,
  },
  {
    short_code: 'dicebear-bottts',
    name: 'DiceBear (Bottts)',
    max_size: 512,
    supports_size: true,
    deterministic: true,
  },
  {
    short_code: 'dicebear-pixel',
    name: 'DiceBear (Pixel Art)',
    max_size: 512,
    supports_size: true,
    deterministic: true,
  },
];

// Avatar Providers List Response Mock Data
export const MOCK_AVATAR_PROVIDERS_LIST_RESPONSE: AvatarProvidersListResponse = {
  success: true,
  providers: MOCK_AVATAR_PROVIDERS,
  default: 'pravatar',
};

// Avatar Cache Stats Mock Data
export const MOCK_AVATAR_CACHE_STATS: AvatarCacheStatsResponse = {
  cache_dir: '/www/wwwroot/laravel_db/cache/avatars',
  total_files: 19,
  total_size: 204440,
  total_size_mb: 0.19,
};
