/**
 * Extended Mock Data for Multi-Role System
 */
import {
  AppStatus,
  AppCategory,
  UserRole,
  AppInstance,
  CustomerService,
  TechMember,
  DailyStat,
  CSAppRevenue,
  AppGenerationRequest,
  User
} from './types';

// Admin Users
export const MOCK_ADMINS: User[] = [
  {
    id: 'admin1',
    name: 'John Admin',
    email: 'john@appfactory.com',
    role: UserRole.ADMIN,
    avatar: 'https://i.pravatar.cc/150?u=admin1',
    phone: '+1-555-0101',
    createdAt: '2024-01-01',
    lastLogin: '2025-12-18',
  },
];

// Customer Service Team (Extended)
export const MOCK_CS: CustomerService[] = [
  {
    id: 'cs1',
    name: 'Alice Chen',
    email: 'alice@appfactory.com',
    role: UserRole.CS,
    avatar: 'https://i.pravatar.cc/150?u=alice',
    status: 'Online',
    totalEarnings: 12500,
    assignedAppIds: ['app1', 'app2', 'app6'],
    commissionRate: 15,
    createdAt: '2024-02-01',
    lastLogin: '2025-12-18',
  },
  {
    id: 'cs2',
    name: 'Bob Smith',
    email: 'bob@appfactory.com',
    role: UserRole.CS,
    avatar: 'https://i.pravatar.cc/150?u=bob',
    status: 'Online',
    totalEarnings: 10200,
    assignedAppIds: ['app2', 'app3', 'app7'],
    commissionRate: 12,
    createdAt: '2024-02-15',
    lastLogin: '2025-12-18',
  },
  {
    id: 'cs3',
    name: 'Carol Wang',
    email: 'carol@appfactory.com',
    role: UserRole.CS,
    avatar: 'https://i.pravatar.cc/150?u=carol',
    status: 'Offline',
    totalEarnings: 8900,
    assignedAppIds: ['app1', 'app4', 'app8'],
    commissionRate: 10,
    createdAt: '2024-03-01',
    lastLogin: '2025-12-17',
  },
  {
    id: 'cs4',
    name: 'David Lee',
    email: 'david@appfactory.com',
    role: UserRole.CS,
    avatar: 'https://i.pravatar.cc/150?u=david',
    status: 'Online',
    totalEarnings: 15300,
    assignedAppIds: ['app3', 'app5', 'app9', 'app10'],
    commissionRate: 18,
    createdAt: '2024-03-15',
    lastLogin: '2025-12-18',
  },
  {
    id: 'cs5',
    name: 'Emma Zhang',
    email: 'emma@appfactory.com',
    role: UserRole.CS,
    avatar: 'https://i.pravatar.cc/150?u=emma',
    status: 'Online',
    totalEarnings: 11800,
    assignedAppIds: ['app6', 'app7', 'app11'],
    commissionRate: 14,
    createdAt: '2024-04-01',
    lastLogin: '2025-12-18',
  },
];

// Technical Team
export const MOCK_TECH: TechMember[] = [
  {
    id: 'tech1',
    name: 'Frank Zhang',
    email: 'frank@appfactory.com',
    role: UserRole.TECH,
    avatar: 'https://i.pravatar.cc/150?u=frank',
    specialization: 'Frontend',
    appsGenerated: 25,
    status: 'Available',
    createdAt: '2024-01-15',
    lastLogin: '2025-12-18',
  },
  {
    id: 'tech2',
    name: 'Grace Liu',
    email: 'grace@appfactory.com',
    role: UserRole.TECH,
    avatar: 'https://i.pravatar.cc/150?u=grace',
    specialization: 'Backend',
    appsGenerated: 30,
    status: 'Busy',
    createdAt: '2024-01-20',
    lastLogin: '2025-12-18',
  },
  {
    id: 'tech3',
    name: 'Henry Wu',
    email: 'henry@appfactory.com',
    role: UserRole.TECH,
    avatar: 'https://i.pravatar.cc/150?u=henry',
    specialization: 'DevOps',
    appsGenerated: 18,
    status: 'Available',
    createdAt: '2024-02-01',
    lastLogin: '2025-12-18',
  },
  {
    id: 'tech4',
    name: 'Ivy Chen',
    email: 'ivy@appfactory.com',
    role: UserRole.TECH,
    avatar: 'https://i.pravatar.cc/150?u=ivy',
    specialization: 'Full Stack',
    appsGenerated: 35,
    status: 'Busy',
    createdAt: '2024-02-10',
    lastLogin: '2025-12-18',
  },
];

// Extended APP Instances (15 apps)
export const MOCK_APPS: AppInstance[] = [
  {
    id: 'app1',
    name: 'Smart Expense Pro',
    status: AppStatus.LIVE,
    category: AppCategory.FINANCE,
    visits: 12540,
    revenue: 5200,
    monthlyRevenue: 8500,
    dailyActiveUsers: 2100,
    createdAt: '2025-12-10',
    updatedAt: '2025-12-17',
    description: 'Advanced expense tracking with AI insights',
    assignedCSIds: ['cs1', 'cs3'],
    assignedTechId: 'tech1',
    features: ['AI Analytics', 'Budget Planning', 'Receipt Scanner'],
    targetAudience: 'Small Business Owners',
    launchDate: '2025-12-10',
    rating: 4.5,
  },
  {
    id: 'app2',
    name: 'FitTrack Plus',
    status: AppStatus.LIVE,
    category: AppCategory.HEALTH,
    visits: 8920,
    revenue: 3800,
    monthlyRevenue: 6200,
    dailyActiveUsers: 1500,
    createdAt: '2025-12-11',
    updatedAt: '2025-12-17',
    description: 'Comprehensive fitness and health tracker',
    assignedCSIds: ['cs1', 'cs2'],
    assignedTechId: 'tech2',
    features: ['Workout Plans', 'Calorie Tracker', 'Progress Charts'],
    targetAudience: 'Fitness Enthusiasts',
    launchDate: '2025-12-11',
    rating: 4.7,
  },
  {
    id: 'app3',
    name: 'LearnHub Academy',
    status: AppStatus.LIVE,
    category: AppCategory.EDUCATION,
    visits: 15600,
    revenue: 6500,
    monthlyRevenue: 10200,
    dailyActiveUsers: 2800,
    createdAt: '2025-12-09',
    updatedAt: '2025-12-17',
    description: 'Interactive learning platform with expert courses',
    assignedCSIds: ['cs2', 'cs4'],
    assignedTechId: 'tech4',
    features: ['Video Courses', 'Quizzes', 'Certificates'],
    targetAudience: 'Students & Professionals',
    launchDate: '2025-12-09',
    rating: 4.8,
  },
  {
    id: 'app4',
    name: 'TravelMate Pro',
    status: AppStatus.PENDING,
    category: AppCategory.TRAVEL,
    visits: 4200,
    revenue: 1800,
    monthlyRevenue: 2500,
    dailyActiveUsers: 600,
    createdAt: '2025-12-15',
    updatedAt: '2025-12-17',
    description: 'Smart travel planning and booking assistant',
    assignedCSIds: ['cs3'],
    assignedTechId: 'tech3',
    features: ['Itinerary Planner', 'Price Alerts', 'Local Guides'],
    targetAudience: 'Travelers',
    rating: 4.2,
  },
  {
    id: 'app5',
    name: 'TaskFlow Manager',
    status: AppStatus.LIVE,
    category: AppCategory.PRODUCTIVITY,
    visits: 10800,
    revenue: 4900,
    monthlyRevenue: 7800,
    dailyActiveUsers: 1900,
    createdAt: '2025-12-08',
    updatedAt: '2025-12-17',
    description: 'Team collaboration and task management tool',
    assignedCSIds: ['cs4'],
    assignedTechId: 'tech4',
    features: ['Kanban Boards', 'Time Tracking', 'Team Chat'],
    targetAudience: 'Teams & Businesses',
    launchDate: '2025-12-08',
    rating: 4.6,
  },
  {
    id: 'app6',
    name: 'ShopSmart Connect',
    status: AppStatus.LIVE,
    category: AppCategory.SHOPPING,
    visits: 18200,
    revenue: 9800,
    monthlyRevenue: 15600,
    dailyActiveUsers: 3400,
    createdAt: '2025-12-07',
    updatedAt: '2025-12-17',
    description: 'AI-powered shopping assistant and price comparison',
    assignedCSIds: ['cs1', 'cs5'],
    assignedTechId: 'tech1',
    features: ['Price Comparison', 'Wishlist', 'Cashback Deals'],
    targetAudience: 'Online Shoppers',
    launchDate: '2025-12-07',
    rating: 4.9,
  },
  {
    id: 'app7',
    name: 'SocialHub Connect',
    status: AppStatus.LIVE,
    category: AppCategory.SOCIAL,
    visits: 22500,
    revenue: 11200,
    monthlyRevenue: 18900,
    dailyActiveUsers: 4500,
    createdAt: '2025-12-06',
    updatedAt: '2025-12-17',
    description: 'Next-gen social networking platform',
    assignedCSIds: ['cs2', 'cs5'],
    assignedTechId: 'tech2',
    features: ['Stories', 'Live Streaming', 'Groups'],
    targetAudience: 'Social Media Users',
    launchDate: '2025-12-06',
    rating: 4.4,
  },
  {
    id: 'app8',
    name: 'MindCare Wellness',
    status: AppStatus.LIVE,
    category: AppCategory.HEALTH,
    visits: 9500,
    revenue: 4200,
    monthlyRevenue: 6800,
    dailyActiveUsers: 1600,
    createdAt: '2025-12-12',
    updatedAt: '2025-12-17',
    description: 'Mental health and meditation companion',
    assignedCSIds: ['cs3'],
    assignedTechId: 'tech3',
    features: ['Meditation', 'Mood Tracking', 'Expert Guidance'],
    targetAudience: 'Mental Health Conscious',
    launchDate: '2025-12-12',
    rating: 4.7,
  },
  {
    id: 'app9',
    name: 'CryptoTrade Hub',
    status: AppStatus.LIVE,
    category: AppCategory.FINANCE,
    visits: 16800,
    revenue: 8900,
    monthlyRevenue: 14200,
    dailyActiveUsers: 2900,
    createdAt: '2025-12-05',
    updatedAt: '2025-12-17',
    description: 'Cryptocurrency trading and portfolio management',
    assignedCSIds: ['cs4'],
    assignedTechId: 'tech4',
    features: ['Real-time Trading', 'Portfolio Analytics', 'Price Alerts'],
    targetAudience: 'Crypto Investors',
    launchDate: '2025-12-05',
    rating: 4.5,
  },
  {
    id: 'app10',
    name: 'GameZone Plus',
    status: AppStatus.LIVE,
    category: AppCategory.ENTERTAINMENT,
    visits: 28000,
    revenue: 15600,
    monthlyRevenue: 25800,
    dailyActiveUsers: 5600,
    createdAt: '2025-12-04',
    updatedAt: '2025-12-17',
    description: 'Premium gaming platform with exclusive titles',
    assignedCSIds: ['cs4'],
    assignedTechId: 'tech2',
    features: ['Cloud Gaming', 'Multiplayer', 'Achievements'],
    targetAudience: 'Gamers',
    launchDate: '2025-12-04',
    rating: 4.8,
  },
  {
    id: 'app11',
    name: 'CodeLearn Pro',
    status: AppStatus.LIVE,
    category: AppCategory.EDUCATION,
    visits: 13400,
    revenue: 6200,
    monthlyRevenue: 9800,
    dailyActiveUsers: 2300,
    createdAt: '2025-12-13',
    updatedAt: '2025-12-17',
    description: 'Interactive coding courses and challenges',
    assignedCSIds: ['cs5'],
    assignedTechId: 'tech1',
    features: ['Code Editor', 'Challenges', 'Certificates'],
    targetAudience: 'Developers',
    launchDate: '2025-12-13',
    rating: 4.9,
  },
  {
    id: 'app12',
    name: 'FoodieMap',
    status: AppStatus.GENERATING,
    category: AppCategory.SOCIAL,
    visits: 0,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: '2025-12-18',
    updatedAt: '2025-12-18',
    description: 'Discover and share local food experiences',
    assignedCSIds: [],
    assignedTechId: 'tech2',
    features: ['Restaurant Reviews', 'Food Photos', 'Maps'],
    targetAudience: 'Food Lovers',
  },
  {
    id: 'app13',
    name: 'BudgetWise',
    status: AppStatus.IDLE,
    category: AppCategory.FINANCE,
    visits: 3200,
    revenue: 1200,
    monthlyRevenue: 1800,
    dailyActiveUsers: 450,
    createdAt: '2025-12-14',
    updatedAt: '2025-12-17',
    description: 'Personal budgeting made simple',
    assignedCSIds: [],
    assignedTechId: 'tech3',
    features: ['Budget Tracking', 'Expense Categories', 'Reports'],
    targetAudience: 'Budget Conscious',
    rating: 4.3,
  },
  {
    id: 'app14',
    name: 'WorkoutPal',
    status: AppStatus.PENDING,
    category: AppCategory.HEALTH,
    visits: 5600,
    revenue: 2400,
    monthlyRevenue: 3600,
    dailyActiveUsers: 890,
    createdAt: '2025-12-16',
    updatedAt: '2025-12-17',
    description: 'AI-powered workout planner',
    assignedCSIds: [],
    assignedTechId: 'tech4',
    features: ['Custom Workouts', 'Progress Tracking', 'Video Guides'],
    targetAudience: 'Fitness Beginners',
    rating: 4.1,
  },
  {
    id: 'app15',
    name: 'StreamFlix',
    status: AppStatus.FAILED,
    category: AppCategory.ENTERTAINMENT,
    visits: 1200,
    revenue: 0,
    monthlyRevenue: 0,
    dailyActiveUsers: 0,
    createdAt: '2025-12-17',
    updatedAt: '2025-12-17',
    description: 'Video streaming platform',
    assignedCSIds: [],
    assignedTechId: 'tech1',
    features: ['HD Streaming', 'Offline Download', 'Recommendations'],
    targetAudience: 'Entertainment Seekers',
  },
];

// CS-APP Revenue Tracking (Many-to-Many)
export const MOCK_CS_APP_REVENUE: CSAppRevenue[] = [
  { id: 'rev1', csId: 'cs1', appId: 'app1', revenue: 5200, commission: 780, promotions: 45, lastUpdated: '2025-12-17' },
  { id: 'rev2', csId: 'cs1', appId: 'app2', revenue: 3800, commission: 570, promotions: 32, lastUpdated: '2025-12-17' },
  { id: 'rev3', csId: 'cs1', appId: 'app6', revenue: 4900, commission: 735, promotions: 52, lastUpdated: '2025-12-17' },
  { id: 'rev4', csId: 'cs2', appId: 'app2', revenue: 3800, commission: 456, promotions: 28, lastUpdated: '2025-12-17' },
  { id: 'rev5', csId: 'cs2', appId: 'app3', revenue: 6500, commission: 780, promotions: 38, lastUpdated: '2025-12-17' },
  { id: 'rev6', csId: 'cs2', appId: 'app7', revenue: 5600, commission: 672, promotions: 41, lastUpdated: '2025-12-17' },
  { id: 'rev7', csId: 'cs3', appId: 'app1', revenue: 5200, commission: 520, promotions: 30, lastUpdated: '2025-12-17' },
  { id: 'rev8', csId: 'cs3', appId: 'app4', revenue: 1800, commission: 180, promotions: 12, lastUpdated: '2025-12-17' },
  { id: 'rev9', csId: 'cs3', appId: 'app8', revenue: 4200, commission: 420, promotions: 25, lastUpdated: '2025-12-17' },
  { id: 'rev10', csId: 'cs4', appId: 'app3', revenue: 6500, commission: 1170, promotions: 48, lastUpdated: '2025-12-17' },
  { id: 'rev11', csId: 'cs4', appId: 'app5', revenue: 4900, commission: 882, promotions: 35, lastUpdated: '2025-12-17' },
  { id: 'rev12', csId: 'cs4', appId: 'app9', revenue: 8900, commission: 1602, promotions: 65, lastUpdated: '2025-12-17' },
  { id: 'rev13', csId: 'cs4', appId: 'app10', revenue: 15600, commission: 2808, promotions: 92, lastUpdated: '2025-12-17' },
  { id: 'rev14', csId: 'cs5', appId: 'app6', revenue: 4900, commission: 686, promotions: 38, lastUpdated: '2025-12-17' },
  { id: 'rev15', csId: 'cs5', appId: 'app7', revenue: 5600, commission: 784, promotions: 44, lastUpdated: '2025-12-17' },
  { id: 'rev16', csId: 'cs5', appId: 'app11', revenue: 6200, commission: 868, promotions: 51, lastUpdated: '2025-12-17' },
];

// Daily Statistics (Extended - Last 30 days)
export const MOCK_DAILY_STATS: DailyStat[] = [
  { date: '12-18', visits: 15200, revenue: 8900, newApps: 2, activeUsers: 28500 },
  { date: '12-17', visits: 14800, revenue: 8200, newApps: 1, activeUsers: 27800 },
  { date: '12-16', visits: 13900, revenue: 7800, newApps: 1, activeUsers: 26200 },
  { date: '12-15', visits: 15600, revenue: 9100, newApps: 2, activeUsers: 29000 },
  { date: '12-14', visits: 14200, revenue: 8400, newApps: 1, activeUsers: 27000 },
  { date: '12-13', visits: 16800, revenue: 9800, newApps: 3, activeUsers: 30500 },
  { date: '12-12', visits: 13500, revenue: 7500, newApps: 1, activeUsers: 25800 },
];

// APP Generation Requests
export const MOCK_APP_REQUESTS: AppGenerationRequest[] = [
  {
    id: 'req1',
    name: 'RecipeShare',
    category: AppCategory.SOCIAL,
    description: 'Share and discover recipes from around the world',
    features: ['Recipe Upload', 'Search', 'Rating System'],
    targetAudience: 'Home Cooks',
    requestedBy: 'admin1',
    requestedAt: '2025-12-18 09:00',
    status: 'pending',
  },
  {
    id: 'req2',
    name: 'PetCare Pro',
    category: AppCategory.HEALTH,
    description: 'Comprehensive pet health tracking',
    features: ['Health Records', 'Vet Appointments', 'Medication Reminders'],
    targetAudience: 'Pet Owners',
    requestedBy: 'admin1',
    requestedAt: '2025-12-18 10:30',
    status: 'in_progress',
    assignedTechId: 'tech2',
    estimatedCompletionDate: '2025-12-20',
  },
  {
    id: 'req3',
    name: 'FoodieMap',
    category: AppCategory.SOCIAL,
    description: 'Discover local food experiences',
    features: ['Restaurant Reviews', 'Food Photos', 'Maps'],
    targetAudience: 'Food Lovers',
    requestedBy: 'admin1',
    requestedAt: '2025-12-18 08:00',
    status: 'in_progress',
    assignedTechId: 'tech2',
    estimatedCompletionDate: '2025-12-19',
  },
];
