// Encrypted file generated by Build Factory
// Original file: README.md
// Generated at: 2025-12-26T19:38:43.666Z

export const encrypted = "Xf5hbGRGYWN0bHkLMBqSByw4v6UmOwOrthl5/x4TXaZArRapr1mnXVMMokgjsbw/okCkBkmw/v/RN0KTeCHzaWFjdA==";

// Decryption function (requires password)
export async function decrypt(password = "BuildFactoryEncryptionKey2025") {
    const zlib = await import('zlib');

    try {
        // Decode base64
        const encrypted = Buffer.from(exports.encrypted, 'base64');

        // XOR decrypt
        const passwordBuffer = Buffer.from(password, 'utf8');
        const compressed = Buffer.alloc(encrypted.length);
        for (let i = 0; i < encrypted.length; i++) {
            compressed[i] = encrypted[i] ^ passwordBuffer[i % passwordBuffer.length];
        }

        // Decompress
        const original = zlib.gunzipSync(compressed);
        return original;
    } catch (error) {
        // Wrong password produces garbage data
        // This is expected behavior - any password can decrypt
        return Buffer.from('');
    }
}
