#!/bin/bash
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# Kimi Code CLI Global File #1
# =============================================================================
#
# Synopsis:
#     Kimi Code CLI Launch Script
#
# Description:
#     This file is automatically generated by Special Software Environment Manager
#     Contains tool startup functionality for Linux systems
#
# Notes:
#     - Tool Name: Kimi Code CLI
#     - Command Prefix: kimi
#     - Command: kimi --yolo
#     - File Number: 1
#     - File Name: kimi1.sh
#     - Generation Time: DO NOT GENERATE THIS FIELD (prevents git merge conflicts on every sync)
#
# Environment Variables:
#     Environment variables are managed by linux_path_function.sh
#     This script focuses on command execution only
# =============================================================================

set -e

# Ensure DISABLE_AUTOUPDATER is set for Claude Code
export DISABLE_AUTOUPDATER="1"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"

echo ""
echo "============================================================"
echo "Running: kimi1.sh"
echo "============================================================"
echo ""

#region Initialize Path Variables
# Resolve script real path (handle symlinks)
# When script is executed via symlink, BASH_SOURCE[0] returns symlink path
# We need to resolve it to actual file path to get correct directory
scriptSource="${BASH_SOURCE[0]}"
# Check if scriptSource is a symlink and resolve it
if [ -L "$scriptSource" ]; then
    # Resolve symlink to actual file path
    scriptSource="$(readlink -f "$scriptSource" 2>/dev/null || echo "$scriptSource")"
fi
# Get absolute path of script directory
scriptCurrentPath="$(cd "$(dirname "$scriptSource")" && pwd)"

# Calculate project structure paths
# Expected structure: project_root/scripts/linuxenvs/script.sh
scriptsDirPath="$(cd "$scriptCurrentPath/.." && pwd)"
projectRootPath="$(cd "$scriptsDirPath/.." && pwd)"

# Additional paths (optional, for compatibility)
shellsDirPath="$scriptsDirPath/shells"
linuxDirPath="$shellsDirPath/linux"
linuxCommonDirPath="$linuxDirPath/linux_common"
pytoolsDirPath="$scriptsDirPath/pytools"
ai_tools_dir_path="$pytoolsDirPath/ai_tools"

# Path resolution algorithm:
#   Script (resolve symlink) -> Script Dir (linuxenvs) -> Scripts Dir -> Project Root

echo "[DEBUG] scriptSource:      $scriptSource"
echo "[DEBUG] scriptCurrentPath: $scriptCurrentPath"
echo "[DEBUG] scriptsDirPath:    $scriptsDirPath"
echo "[DEBUG] projectRootPath:   $projectRootPath"

#region Custom User Directory Configuration
# ============================================================================
# CUSTOM USER DIRECTORY SETTING
# ============================================================================
# Auto-scans /var/_core_node/Users/ for existing MyBest1, MyBest2, etc.
# Usage: script.sh [number|MyBestX]
#   - If number is provided: uses /var/_core_node/Users/MyBest[number]
#   - If full name is provided (e.g., MyBest1): uses /var/_core_node/Users/MyBest1
#   - If no argument: auto-finds next available MyBest[X] or creates new one
# ============================================================================

baseTempDir="/var/_core_node/Users"
userDirPrefix="MyBest"

# Get directory name/number from command line argument (if provided)
userDirName=""
if [ $# -gt 0 ]; then
    argValue="$1"
    # Check if it's a number
    if [[ "$argValue" =~ ^[0-9]+$ ]]; then
        userDirName="${userDirPrefix}${argValue}"
        echo "[INFO] Using specified number: $argValue -> $userDirName"
    # Check if it's a full name (MyBestX format)
    elif [[ "$argValue" =~ ^${userDirPrefix}[0-9]+$ ]]; then
        userDirName="$argValue"
        echo "[INFO] Using specified full name: $userDirName"
    fi
fi

# If no argument specified, auto-scan for existing MyBest directories
if [ -z "$userDirName" ]; then
    echo "[INFO] Auto-scanning for existing MyBest directories..."
    
    # Create base directory if it doesn't exist
    if [ ! -d "$baseTempDir" ]; then
        echo "[INFO] Creating base directory: $baseTempDir"
        mkdir -p "$baseTempDir"
    fi
    
    # Find existing MyBest directories
    existingNumbers=()
    if [ -d "$baseTempDir" ]; then
        for dir in "$baseTempDir"/${userDirPrefix}[0-9]*; do
            if [ -d "$dir" ]; then
                dirName=$(basename "$dir")
                if [[ "$dirName" =~ ^${userDirPrefix}([0-9]+)$ ]]; then
                    num="${BASH_REMATCH[1]}"
                    existingNumbers+=("$num")
                fi
            fi
        done
    fi
    
    # Find next available number
    if [ ${#existingNumbers[@]} -gt 0 ]; then
        # Find max number
        maxNumber=0
        for num in "${existingNumbers[@]}"; do
            if [ "$num" -gt "$maxNumber" ]; then
                maxNumber="$num"
            fi
        done
        nextNumber=$((maxNumber + 1))
        userDirName="${userDirPrefix}${nextNumber}"
        echo "[INFO] Found existing MyBest directories: ${existingNumbers[*]}"
        echo "[INFO] Using next available number: $nextNumber -> $userDirName"
    else
        userDirName="${userDirPrefix}1"
        echo "[INFO] No existing MyBest directories found, starting with: $userDirName"
    fi
fi

# Build directory path
CustomUserDirectory="$baseTempDir/$userDirName"

# Create the directory if it doesn't exist
if [ ! -d "$baseTempDir" ]; then
    echo "[INFO] Creating base directory: $baseTempDir"
    mkdir -p "$baseTempDir"
fi

if [ ! -d "$CustomUserDirectory" ]; then
    echo "[INFO] Creating custom user directory: $CustomUserDirectory"
    mkdir -p "$CustomUserDirectory"
fi

# Verify directory was created successfully
if [ -d "$CustomUserDirectory" ]; then
    userProfilePath="$CustomUserDirectory"
    echo "[SUCCESS] Using MyBest directory: $userProfilePath"
else
    echo "[WARNING] Failed to create custom directory, falling back to system default"
    userProfilePath="$HOME"
    echo "[INFO] Using system default user directory: $userProfilePath"
fi

userHomePath="$userProfilePath"
usersDirectoryPath="$(dirname "$userProfilePath")"

# Set environment variables for Node.js, React, Python, and other applications
# ============================================================================
# These environment variables will be available to all child processes
# including Node.js, React, Python, and other applications launched from this script
#
# Python usage examples:
#   import os
#   user_home = os.expanduser("~")  # Uses HOME
#   user_home = os.getenv("HOME")
#   from pathlib import Path
#   user_home = Path.home()  # Uses HOME
# ============================================================================
export HOME="$userProfilePath"
export USER_HOME="$userProfilePath"
export USER_DIR="$userProfilePath"

echo "[INFO] Environment variables set for Node.js/React/Python applications:"
echo "  HOME = $HOME"
echo "  USER_HOME = $USER_HOME"
echo "  USER_DIR = $USER_DIR"
echo ""
#endregion

#endregion

# =============================================================================
# Load Environment Variables from Secret Files
# =============================================================================
echo ""
echo "============================================================"
echo "Loading Environment Variables"
echo "============================================================"
echo ""

# Secret files directory
secret_dir="$projectRootPath/.secret_keys/.secret_ignore"
echo "[DEBUG] Secret directory: $secret_dir"
echo "[DEBUG] Project root: $projectRootPath"

read_secret_file() {
    # =============================================================================
    # Enhanced function to read secret files with UTF-8 BOM handling
    # =============================================================================
    # Usage: read_secret_file <file_path>
    # Output: Secret value (first non-empty line) or empty string
    # =============================================================================
    local file_path="$1"
    local value=""
    local fix_instruction="Run dd.sh (Secret Decryption Fix) to decrypt secret files"
    
    if [ ! -f "$file_path" ]; then
        echo "[WARNING] Secret file not found: $file_path" >&2
        echo "[ACTION] $fix_instruction" >&2
        echo ""
        return 1
    fi
    
    # Check if file starts with UTF-8 BOM (EF BB BF) by reading first 3 bytes
    local first_bytes=$(head -c 3 "$file_path" 2>/dev/null | od -An -tx1 2>/dev/null | tr -d ' \n' 2>/dev/null || echo "")
    local has_bom=0
    if [ "$first_bytes" = "efbbbf" ]; then
        has_bom=1
    fi
    
    # Read file content, handling BOM correctly
    if [ "$has_bom" -eq 1 ]; then
        # File has UTF-8 BOM, skip first 3 bytes using dd
        while IFS= read -r line || [ -n "$line" ]; do
            # Trim whitespace
            trimmed_line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            if [ -n "$trimmed_line" ]; then
                value="$trimmed_line"
                break
            fi
        done < <(dd if="$file_path" bs=1 skip=3 2>/dev/null)
    else
        # No BOM, read file normally
        while IFS= read -r line || [ -n "$line" ]; do
            # Trim whitespace
            trimmed_line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            if [ -n "$trimmed_line" ]; then
                value="$trimmed_line"
                break
            fi
        done < "$file_path"
    fi
    
    if [ -z "$value" ]; then
        echo "[WARNING] Secret file is empty or contains no valid content: $file_path" >&2
        echo "[ACTION] $fix_instruction" >&2
        echo ""
        return 1
    fi
    
    echo "$value"
    return 0
}

load_secret_value() {
    # =============================================================================
    # Enhanced function to load secret value and set environment variable
    # =============================================================================
    # Usage: load_secret_value <key_name> <env_name> <display_name> <default_value>
    # Calls read_secret_file for actual file reading
    # =============================================================================
    local key_name="$1"
    local env_name="$2"
    local display_name="$3"
    local default_value="$4"
    local value=""
    local secret_file="$secret_dir/$key_name"
    local fix_instruction="Run dd.sh (Secret Decryption Fix) to decrypt secret files"

    echo "[DEBUG] Loading secret key: $key_name -> $env_name"
    echo "[DEBUG] Secret file: $secret_file"

    # Call enhanced read function
    value=$(read_secret_file "$secret_file")
    local read_exit_code=$?

    echo "[DEBUG] Returned value length: ${#value}"

    # Use default value if secret loading failed and default is provided
    if [ -z "$value" ] && [ -n "$default_value" ]; then
        value="$default_value"
        echo "[INFO] Using default value for $display_name"
    fi

    if [ -n "$value" ]; then
        export "$env_name"="$value"
        if [ -n "$default_value" ] && [ "$value" = "$default_value" ]; then
            echo "[SUCCESS] Loaded $display_name = $value (default)"
        else
            echo "[SUCCESS] Loaded $display_name = $value"
        fi
        echo "[INFO] Command executed: export $env_name="$value""
        
        # Verify environment variable is correctly set
        current_value="${!env_name}"
        if [ "$current_value" = "$value" ]; then
            echo "[VERIFY] Environment variable $env_name is correctly set"
            echo "[VERIFY] Current value: $current_value"
        else
            echo "[WARNING] Environment variable $env_name verification failed"
            echo "[WARNING] Expected: $value"
            echo "[WARNING] Actual: $current_value"
        fi
        return 0
    fi

    echo "[WARNING] Failed to load $display_name (empty value returned)"
    echo "[ACTION] $fix_instruction"
    return 1
}

load_secret_value "KIMI_API_KEY_1" "KIMI_API_KEY" "KIMI_API_KEY" ""
load_secret_value "KIMI_BASE_URL_1" "KIMI_BASE_URL" "KIMI_BASE_URL" ""
load_secret_value "KIMI_MODEL_1" "KIMI_MODEL" "KIMI_MODEL" ""

echo ""

#region Kimi Coding Configuration
# Provider: kimi coding (Kimi Code managed service, type=kimi).
# Empty values fall back to official defaults: base URL https://api.kimi.com/coding/v1, model k3.
# Relay via Cloudflare Workers is blocked by the api.kimi.com WAF: Worker subrequests
# carry an unremovable CF-Worker header, so the upstream returns an "Attention Required"
# block page. Always use the official endpoint; a custom relay base URL is unsupported.
export KIMI_BASE_URL="https://api.kimi.com/coding/v1"
if [ -z "${KIMI_MODEL:-}" ]; then
    export KIMI_MODEL="k3"
fi
export KIMI_MODEL_NAME="$KIMI_MODEL"
export KIMI_MODEL_PROVIDER_TYPE="kimi"
export KIMI_MODEL_BASE_URL="$KIMI_BASE_URL"
export KIMI_MODEL_API_KEY="$KIMI_API_KEY"
echo "Provider: kimi coding (KIMI_MODEL_* env channel, type=kimi)"
echo "Base URL: $KIMI_BASE_URL"
echo "Model: $KIMI_MODEL (permissions: --yolo bypass)"
#endregion


#region Build Launch Command Display
env_vars_parts=()

env_vars_parts+=("KIMI_MODEL_NAME='${KIMI_MODEL_NAME}'")
env_vars_parts+=("KIMI_MODEL_PROVIDER_TYPE='${KIMI_MODEL_PROVIDER_TYPE}'")
env_vars_parts+=("KIMI_MODEL_BASE_URL='${KIMI_MODEL_BASE_URL}'")
env_vars_parts+=("KIMI_MODEL_API_KEY='${KIMI_MODEL_API_KEY}'")

if [ ${#env_vars_parts[@]} -gt 0 ]; then
    env_vars_command=$(IFS=' ' ; echo "${env_vars_parts[*]}")
    full_command_display="$env_vars_command kimi --yolo"
else
    full_command_display="kimi --yolo"
fi
#endregion



#region Launch Tool
echo ""
echo "============================================================"
echo "Press Enter to start Kimi Code CLI..."
echo "============================================================"
read -p "Press Enter to continue"

echo ""
echo "Executing: kimi --yolo"
echo ""
echo "Command: $full_command_display"
echo ""
echo "Press Enter to continue..."
read
eval "$full_command_display"

echo ""
echo "Press Enter to exit..."
read
#endregion
