#!/bin/bash
# =============================================================================
# Ark CLI (Volcano Ark / GLM) Launch Script #6 - [piark -> Pi]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Standalone script based on piyolo.sh template.
# =============================================================================
SCRIPT_SOURCE="${BASH_SOURCE[0]}"
SCRIPT_CURRENT_DIR=""
SCRIPTS_DIR=""
CORE_NODE_DIR=""
LINUX_COMMON_DIR=""
GVAR_COMMON_PATH=""
SHELLS_COMMON_DIR=""
HARNESS_SETTINGS_SCRIPT=""
MODE="volc-coding"
PROVIDER="openai-codex"
MODEL="gpt-5.6-sol"
THINKING="high"
THINKING_SET_BY_USER="false"
PARSED_ARGS=()
PI_BIN_PATH=""
PI_USER_DIR=""
PI_AGENT_DIR=""
PI_SETTINGS_PATH=""
PI_MODELS_PATH=""
PACKAGE_SOURCE="-"
PACKAGE_SOURCES=()
PACKAGE_NAMES=()
KIMI_PROVIDER_PACKAGE="npm:pi-provider-kimi-code"
KIMI_PROVIDER_PACKAGE_NAME="pi-provider-kimi-code"
CLAUDE_AUTH_PACKAGE="npm:pi-claude-auth"
CLAUDE_AUTH_PACKAGE_NAME="pi-claude-auth"
NATIVE_WEB_SEARCH_PACKAGE="npm:pi-web-search"
NATIVE_WEB_SEARCH_PACKAGE_NAME="pi-web-search"
PORTABLE_WEB_PACKAGE="npm:pi-web-kit"
PORTABLE_WEB_PACKAGE_NAME="pi-web-kit"
MCP_PACKAGE="npm:pi-mcp-extension"
MCP_PACKAGE_NAME="pi-mcp-extension"
ORIGINAL_HOME="$HOME"
ORIGINAL_CLAUDE_CONFIG_DIR="${CLAUDE_CONFIG_DIR:-$ORIGINAL_HOME/.claude}"
ORIGINAL_CODEX_HOME="${CODEX_HOME:-$ORIGINAL_HOME/.codex}"
CLAUDE_SKILLS_PATH="$ORIGINAL_CLAUDE_CONFIG_DIR/skills"
CODEX_SKILLS_PATH="$ORIGINAL_CODEX_HOME/skills"
KIMI_CODE_HOME_PATH="${KIMI_CODE_HOME:-$ORIGINAL_HOME/.kimi-code}"
KIMI_SKILLS_PATH="$KIMI_CODE_HOME_PATH/skills"
SKILL_PATHS=()
CODEX_MODELS="openai-codex/gpt-5.3-codex-spark,openai-codex/gpt-5.4,openai-codex/gpt-5.4-mini,openai-codex/gpt-5.5,openai-codex/gpt-5.6-luna,openai-codex/gpt-5.6-sol,openai-codex/gpt-5.6-terra"
CLAUDE_MODELS="anthropic/*"
KIMI_MODELS="kimi-coding/kimi-for-coding,kimi-coding/kimi-for-coding-highspeed,kimi-coding/k3"
ENABLED_MODELS=""
FORWARD_ARGS=()
PI_ARGS=()
PREREQUISITES_READY=0
KIMI_CONFIG_PATH=""
PI_AUTH_PATH=""
PACKAGE_NAME=""
CODEX_AUTH_PATH=""
CLAUDE_CREDENTIAL_PATH=""
ISOLATED_CLAUDE_DIR=""
ISOLATED_CLAUDE_CREDENTIAL_PATH=""
PROVIDER_READY=1
VOLC_PROFILE_TYPE=""
VOLC_PROVIDER=""
VOLC_API_KEY=""
VOLC_BASE_URL=""
VOLC_API_KEY_REFERENCE='$PI_VOLC_API_KEY'
VOLC_AGENT_DEFAULT_BASE_URL="https://ark.cn-beijing.volces.com/api/plan/v3"
VOLC_CODING_DEFAULT_BASE_URL="https://ark.cn-beijing.volces.com/api/coding/v3"
VOLC_AGENT_DEFAULT_MODEL="kimi-k3"
VOLC_CODING_DEFAULT_MODEL="kimi-k3"
VOLC_CODING_FALLBACK_MODEL="ark-code-latest"
VOLC_MODELS=()
ARKCLI_CONFIG_CANDIDATES=()
ARKCLI_CONFIG_PATH=""
ARKCLI_PROFILE_RESULT=""
ARKCLI_PROFILE_BASE_URL=""
LEGACY_SECRET_PATH=""
LEGACY_BASE_URL_PATH=""
LEGACY_MODEL_PATH=""
LEGACY_SECRET_VALUE=""
MCP_SOURCE_CANDIDATE=""
KIMI_PROVIDER_CONFIG_PATH=""
PI_MCP_CONFIG_PATH=""
PI_WEB_KIT_CONFIG_PATH=""
ARK_DOCS_MCP_NAME="ark-docs-mcp"
ARK_DOCS_MCP_URL="https://sd6j8o9hu8aldae0o6es0.apigateway-cn-beijing.volceapi.com/mcp"
VOLC_SEARCH_MCP_NAME="mcp-server-askecho-search-infinity"
VOLC_AGENT_MCP_CANDIDATES=()
VOLC_AGENT_MCP_SOURCE_PATH=""
UVX_BIN_PATH=""

# Maintenance references:
# - Pi providers/auth.json: https://pi.dev/docs/latest/providers
# - Pi environment overrides: https://pi.dev/docs/latest/environment-variables
# - Claude Code auth bridge: https://pi.dev/packages/pi-claude-auth
# - Kimi Code integration: https://pi.dev/packages/pi-provider-kimi-code
# - Provider-native Codex search: https://pi.dev/packages/pi-web-search
# - Provider-independent Claude/Kimi/Volc search/fetch: https://pi.dev/packages/pi-web-kit
# - Pi MCP client: https://pi.dev/packages/pi-mcp-extension
# Keep this flow aligned with scripts/winenvs/piyolo.ps1: isolated user data,
# absolute Node/pnpm binaries from gvar_common.sh, and independent idempotency
# for every package and credential substep. Pi already supplies openai-codex.

if [ -L "$SCRIPT_SOURCE" ]; then
    SCRIPT_SOURCE="$(readlink -f "$SCRIPT_SOURCE" 2>/dev/null || echo "$SCRIPT_SOURCE")"
fi
SCRIPT_CURRENT_DIR="$(cd "$(dirname "$SCRIPT_SOURCE")" && pwd)"
SCRIPTS_DIR="$(dirname "$SCRIPT_CURRENT_DIR")"
CORE_NODE_DIR="$(dirname "$SCRIPTS_DIR")"
LINUX_COMMON_DIR="$CORE_NODE_DIR/scripts/shells/linux/common"
GVAR_COMMON_PATH="$LINUX_COMMON_DIR/gvar_common.sh"
SHELLS_COMMON_DIR="$CORE_NODE_DIR/scripts/shells/common"
HARNESS_SETTINGS_SCRIPT="$SHELLS_COMMON_DIR/pi_harness_settings.js"

source "$GVAR_COMMON_PATH"

ARKCLI_CONFIG_CANDIDATES=(
    "$PROGRAMING_USERS_DIR/ark1/.arkcli/config.yaml"
    "$PROGRAMING_USERS_DIR/ark2/.arkcli/config.yaml"
    "$PROGRAMING_USERS_DIR/ark3/.arkcli/config.yaml"
    "$ORIGINAL_HOME/.arkcli/config.yaml"
)
VOLC_AGENT_MCP_CANDIDATES=(
    "$PROGRAMING_USERS_DIR/ark1/.claude.json"
    "$PROGRAMING_USERS_DIR/ark2/.claude.json"
    "$PROGRAMING_USERS_DIR/ark3/.claude.json"
)
UVX_BIN_PATH="$(command -v uvx 2>/dev/null || true)"

PI_BIN_PATH="$PNPM_GLOBAL_BIN_DIR/pi"
if [ ! -x "$PI_BIN_PATH" ] && [ -x /usr/local/bin/pi ]; then
    PI_BIN_PATH="/usr/local/bin/pi"
fi


while [ "$#" -gt 0 ]; do
    case "$1" in
        --thinking)
            if [ -z "${2:-}" ]; then
                echo "[ERROR] --thinking requires a value."
                echo "[INFO] Supported levels: off, minimal, low, medium, high, xhigh, max"
                exit 1
            fi
            THINKING="$2"
            THINKING_SET_BY_USER="true"
            shift 2
            ;;
        --thinking=*)
            THINKING="${1#*=}"
            THINKING_SET_BY_USER="true"
            shift
            ;;
        *)
            PARSED_ARGS+=("$1")
            shift
            ;;
    esac

done

FORWARD_ARGS=("${PARSED_ARGS[@]}")

if [ "$MODE" = "claude" ]; then
    PROVIDER="anthropic"
    MODEL="claude-opus-4-8"
    ENABLED_MODELS="$CLAUDE_MODELS"
    PI_USER_DIR="$PI_CLAUDE_CODE_USER_DIR"
    PI_AGENT_DIR="$PI_CLAUDE_CODE_AGENT_DIR"
    PACKAGE_SOURCES=("$CLAUDE_AUTH_PACKAGE" "$PORTABLE_WEB_PACKAGE")
    PACKAGE_NAMES=("$CLAUDE_AUTH_PACKAGE_NAME" "$PORTABLE_WEB_PACKAGE_NAME")
    if [ -d "$CLAUDE_SKILLS_PATH" ]; then
        SKILL_PATHS=("$CLAUDE_SKILLS_PATH")
    fi
elif [ "$MODE" = "kimi" ]; then
    PROVIDER="kimi-coding"
    MODEL="k3"
    ENABLED_MODELS="$KIMI_MODELS"
    PI_USER_DIR="$PI_KIMI_USER_DIR"
    PI_AGENT_DIR="$PI_KIMI_AGENT_DIR"
    PACKAGE_SOURCE="$KIMI_PROVIDER_PACKAGE"
    PACKAGE_SOURCES=("$KIMI_PROVIDER_PACKAGE" "$PORTABLE_WEB_PACKAGE")
    PACKAGE_NAMES=("$KIMI_PROVIDER_PACKAGE_NAME" "$PORTABLE_WEB_PACKAGE_NAME")
    if [ -d "$KIMI_SKILLS_PATH" ]; then
        SKILL_PATHS=("$KIMI_SKILLS_PATH")
    fi
elif [ "$MODE" = "codex" ]; then
    ENABLED_MODELS="$CODEX_MODELS"
    PI_USER_DIR="$PI_CODEX_USER_DIR"
    PI_AGENT_DIR="$PI_CODEX_AGENT_DIR"
    PACKAGE_SOURCES=("$NATIVE_WEB_SEARCH_PACKAGE")
    PACKAGE_NAMES=("$NATIVE_WEB_SEARCH_PACKAGE_NAME")
    if [ -d "$CODEX_SKILLS_PATH" ]; then
        SKILL_PATHS=("$CODEX_SKILLS_PATH")
    fi
elif [ "$MODE" = "volc-agent" ]; then
    PROVIDER="volcengine-agent-plan"
    MODEL="$VOLC_AGENT_DEFAULT_MODEL"
    VOLC_MODELS=("$VOLC_AGENT_DEFAULT_MODEL" "auto" "doubao-seed-evolving" "doubao-seed-2.0-pro")
    ENABLED_MODELS="$PROVIDER/$VOLC_AGENT_DEFAULT_MODEL,$PROVIDER/auto,$PROVIDER/doubao-seed-evolving,$PROVIDER/doubao-seed-2.0-pro"
    PI_USER_DIR="$PI_VOLC_AGENT_USER_DIR"
    PI_AGENT_DIR="$PI_VOLC_AGENT_AGENT_DIR"
    VOLC_PROFILE_TYPE="agent-plan"
    VOLC_PROVIDER="$PROVIDER"
    VOLC_BASE_URL="$VOLC_AGENT_DEFAULT_BASE_URL"
    PROVIDER_READY=0
    PACKAGE_SOURCES=("$PORTABLE_WEB_PACKAGE" "$MCP_PACKAGE")
    PACKAGE_NAMES=("$PORTABLE_WEB_PACKAGE_NAME" "$MCP_PACKAGE_NAME")
elif [ "$MODE" = "volc-coding" ]; then
    PROVIDER="volcengine-coding-plan"
    MODEL="$VOLC_CODING_DEFAULT_MODEL"
    VOLC_MODELS=("$VOLC_CODING_DEFAULT_MODEL" "$VOLC_CODING_FALLBACK_MODEL")
    ENABLED_MODELS="$PROVIDER/$VOLC_CODING_DEFAULT_MODEL,$PROVIDER/$VOLC_CODING_FALLBACK_MODEL"
    PI_USER_DIR="$PI_VOLC_CODING_USER_DIR"
    PI_AGENT_DIR="$PI_VOLC_CODING_AGENT_DIR"
    VOLC_PROFILE_TYPE="coding-plan"
    VOLC_PROVIDER="$PROVIDER"
    VOLC_BASE_URL="$VOLC_CODING_DEFAULT_BASE_URL"
    PROVIDER_READY=0
    PACKAGE_SOURCES=("$PORTABLE_WEB_PACKAGE" "$MCP_PACKAGE")
    PACKAGE_NAMES=("$PORTABLE_WEB_PACKAGE_NAME" "$MCP_PACKAGE_NAME")
else
    ENABLED_MODELS="$CODEX_MODELS,$CLAUDE_MODELS,$KIMI_MODELS"
    PI_USER_DIR="$PI_COMMON_USER_DIR"
    PI_AGENT_DIR="$PI_COMMON_AGENT_DIR"
    PACKAGE_SOURCE="$KIMI_PROVIDER_PACKAGE"
    PACKAGE_SOURCES=("$KIMI_PROVIDER_PACKAGE" "$CLAUDE_AUTH_PACKAGE" "$PORTABLE_WEB_PACKAGE")
    PACKAGE_NAMES=("$KIMI_PROVIDER_PACKAGE_NAME" "$CLAUDE_AUTH_PACKAGE_NAME" "$PORTABLE_WEB_PACKAGE_NAME")
    if [ -d "$CLAUDE_SKILLS_PATH" ]; then
        SKILL_PATHS+=("$CLAUDE_SKILLS_PATH")
    fi
    if [ -d "$CODEX_SKILLS_PATH" ]; then
        SKILL_PATHS+=("$CODEX_SKILLS_PATH")
    fi
    if [ -d "$KIMI_SKILLS_PATH" ]; then
        SKILL_PATHS+=("$KIMI_SKILLS_PATH")
    fi
fi

if [ "$MODE" = "codex" ]; then
    if [ "$THINKING_SET_BY_USER" = "false" ] && [ "$THINKING" = "high" ]; then
        THINKING="xhigh"
    fi
    case "$THINKING" in
        xhigh)
            ;;
        minimal|off|low|medium|high|max)
            THINKING="xhigh"
            ;;
        *)
            echo "[WARN] Unsupported thinking level '$THINKING' for codex; fallback to xhigh."
            THINKING="xhigh"
            ;;
    esac
fi

if [ "${#PACKAGE_SOURCES[@]}" -gt 0 ]; then
    PACKAGE_SOURCE="$(IFS=,; echo "${PACKAGE_SOURCES[*]}")"
fi
PI_SETTINGS_PATH="$PI_AGENT_DIR/settings.json"
PI_MODELS_PATH="$PI_AGENT_DIR/models.json"
KIMI_PROVIDER_CONFIG_PATH="$PI_USER_DIR/.pi/providers/kimi-coding/config.json"
PI_MCP_CONFIG_PATH="$PI_AGENT_DIR/mcp.json"
PI_WEB_KIT_CONFIG_PATH="$PI_AGENT_DIR/pi-web-kit.json"
ISOLATED_CLAUDE_DIR="$PI_USER_DIR/.claude"
ISOLATED_CLAUDE_CREDENTIAL_PATH="$ISOLATED_CLAUDE_DIR/.credentials.json"
if [ -x "$PI_BIN_PATH" ] && [ -x "$NODE_BIN" ] && [ -x "$PNPM_BIN" ] && [ -f "$HARNESS_SETTINGS_SCRIPT" ]; then
    PREREQUISITES_READY=1
    if [ ! -d "$PI_AGENT_DIR" ]; then
        mkdir -p "$PI_AGENT_DIR"
    fi
    "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" pi "$PI_SETTINGS_PATH" /bin/bash "$PNPM_BIN" "$PACKAGE_SOURCE" "${SKILL_PATHS[@]}"

    # Official Volcengine integration reference:
    # https://www.volcengine.com/docs/82379/2205646
    # https://www.volcengine.com/docs/82379/1528783
    # Pi custom-provider reference: https://pi.dev/docs/latest/models
    # Reuse the existing ark1/ark2/ark3 authorization for the requested plan
    # without changing arkcli's default profile. Agent Plan and Coding Plan are
    # separate quota gateways, so each gets an isolated Pi provider and HOME.
    if [ -n "$VOLC_PROFILE_TYPE" ]; then
        for ARKCLI_CONFIG_PATH in "${ARKCLI_CONFIG_CANDIDATES[@]}"; do
            if [ -z "$VOLC_API_KEY" ] && [ -f "$ARKCLI_CONFIG_PATH" ]; then
                ARKCLI_PROFILE_RESULT="$("$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" arkcli-profile "$ARKCLI_CONFIG_PATH" "$VOLC_PROFILE_TYPE")"
                if [ -n "$ARKCLI_PROFILE_RESULT" ]; then
                    VOLC_API_KEY="${ARKCLI_PROFILE_RESULT%%$'\t'*}"
                    if [[ "$ARKCLI_PROFILE_RESULT" == *$'\t'* ]]; then
                        ARKCLI_PROFILE_BASE_URL="${ARKCLI_PROFILE_RESULT#*$'\t'}"
                    fi
                    if [ -n "$ARKCLI_PROFILE_BASE_URL" ]; then
                        VOLC_BASE_URL="${ARKCLI_PROFILE_BASE_URL%/}"
                        if [[ "$VOLC_BASE_URL" != */v3 ]]; then
                            VOLC_BASE_URL="$VOLC_BASE_URL/v3"
                        fi
                    fi
                fi
            fi
        done

        # claudevolc predates arkcli profiles. Preserve its Coding Plan files as
        # a fallback, but never mix that key into the Agent Plan provider.
        if [ "$MODE" = "volc-coding" ] && [ -z "$VOLC_API_KEY" ]; then
            for LEGACY_SECRET_PATH in \
                "$CORE_NODE_DIR/.secret_keys/.secret_ignore/ARKCLI_API_KEY_6" \
                "$CORE_NODE_DIR/.secret_keys/.secret_ignore/ARK_API_KEY_6"
            do
                if [ -z "$VOLC_API_KEY" ]; then
                    VOLC_API_KEY="$("$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" secret-file "$LEGACY_SECRET_PATH")"
                    if [ -n "$VOLC_API_KEY" ]; then
                        echo "[INFO] Loaded Volcengine API Key from $(basename "$LEGACY_SECRET_PATH")"
                    fi
                fi
            done
            if [ -z "$VOLC_API_KEY" ]; then
                echo "[WARN] Volcengine API Key not found in ARKCLI_API_KEY_6 (or ARK_API_KEY_6). A valid API key is required."
            fi
            
            LEGACY_BASE_URL_PATH="$CORE_NODE_DIR/.secret_keys/.secret_ignore/ARKCLI_API_6"
            LEGACY_SECRET_VALUE="$("$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" secret-file "$LEGACY_BASE_URL_PATH")"
            if [ -z "$LEGACY_SECRET_VALUE" ]; then
                LEGACY_BASE_URL_PATH="$CORE_NODE_DIR/.secret_keys/.secret_ignore/ARK_BASE_URL_1"
                LEGACY_SECRET_VALUE="$("$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" secret-file "$LEGACY_BASE_URL_PATH")"
            fi
            if [ -n "$LEGACY_SECRET_VALUE" ]; then
                echo "[INFO] Loaded Volcengine Base URL: $LEGACY_SECRET_VALUE"
                VOLC_BASE_URL="${LEGACY_SECRET_VALUE%/}"
                if [[ "$VOLC_BASE_URL" != */v3 ]]; then
                    VOLC_BASE_URL="$VOLC_BASE_URL/v3"
                fi
            fi
        fi
        if [ "$MODE" = "volc-coding" ]; then
            LEGACY_MODEL_PATH="$CORE_NODE_DIR/.secret_keys/.secret_ignore/ARKCLI_MODEL_6"
            LEGACY_SECRET_VALUE="$("$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" secret-file "$LEGACY_MODEL_PATH")"
            if [ -n "$LEGACY_SECRET_VALUE" ]; then
                echo "[INFO] Loaded Volcengine Model: $LEGACY_SECRET_VALUE"
                MODEL="$LEGACY_SECRET_VALUE"
                if [ "$LEGACY_SECRET_VALUE" = "$VOLC_CODING_DEFAULT_MODEL" ] || [ "$LEGACY_SECRET_VALUE" = "$VOLC_CODING_FALLBACK_MODEL" ]; then
                    VOLC_MODELS=("$VOLC_CODING_DEFAULT_MODEL" "$VOLC_CODING_FALLBACK_MODEL")
                    ENABLED_MODELS="$PROVIDER/$VOLC_CODING_DEFAULT_MODEL,$PROVIDER/$VOLC_CODING_FALLBACK_MODEL"
                else
                    VOLC_MODELS=("$LEGACY_SECRET_VALUE" "$VOLC_CODING_DEFAULT_MODEL" "$VOLC_CODING_FALLBACK_MODEL")
                    ENABLED_MODELS="$PROVIDER/$LEGACY_SECRET_VALUE,$PROVIDER/$VOLC_CODING_DEFAULT_MODEL,$PROVIDER/$VOLC_CODING_FALLBACK_MODEL"
                fi
            else
                LEGACY_MODEL_PATH="$CORE_NODE_DIR/.secret_keys/.secret_ignore/ARKCLI_MODEL_2"
                LEGACY_SECRET_VALUE="$("$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" secret-file "$LEGACY_MODEL_PATH")"
                if [ -n "$LEGACY_SECRET_VALUE" ]; then
                    if [ "$LEGACY_SECRET_VALUE" = "$VOLC_CODING_DEFAULT_MODEL" ] || [ "$LEGACY_SECRET_VALUE" = "$VOLC_CODING_FALLBACK_MODEL" ]; then
                        VOLC_MODELS=("$VOLC_CODING_DEFAULT_MODEL" "$VOLC_CODING_FALLBACK_MODEL")
                        ENABLED_MODELS="$PROVIDER/$VOLC_CODING_DEFAULT_MODEL,$PROVIDER/$VOLC_CODING_FALLBACK_MODEL"
                    else
                        VOLC_MODELS=("$VOLC_CODING_DEFAULT_MODEL" "$LEGACY_SECRET_VALUE" "$VOLC_CODING_FALLBACK_MODEL")
                        ENABLED_MODELS="$PROVIDER/$VOLC_CODING_DEFAULT_MODEL,$PROVIDER/$LEGACY_SECRET_VALUE,$PROVIDER/$VOLC_CODING_FALLBACK_MODEL"
                    fi
                fi
            fi
        fi
        if [ -n "$VOLC_API_KEY" ]; then
            PROVIDER_READY=1
            export PI_VOLC_API_KEY="$VOLC_API_KEY"
            "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" pi-provider "$PI_MODELS_PATH" "$VOLC_PROVIDER" "$VOLC_BASE_URL" "$VOLC_API_KEY_REFERENCE" "${VOLC_MODELS[@]}"
        fi
    fi

    # A settings package entry is not an installation check. Repair each missing
    # package manifest separately so one installed provider cannot mask another.
    for PACKAGE_NAME in "${PACKAGE_NAMES[@]}"; do
        "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" pi-package "$PI_AGENT_DIR" "$PNPM_BIN" "$PACKAGE_NAME"
    done

    # Kimi search/fetch uses the same OAuth session as the Kimi model provider.
    # Codex uses provider-native server search through pi-web-search. Claude,
    # Kimi, and Volcengine keep web access independent from model credential
    # type through pi-web-kit; Volcengine also loads the public Ark docs MCP.
    if [ -n "$VOLC_PROFILE_TYPE" ] || [ "$MODE" = "claude" ] || [ "$MODE" = "kimi" ] || [ "$MODE" = "auto" ]; then
        "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" pi-web-kit "$PI_WEB_KIT_CONFIG_PATH"
    fi
    if [ -n "$VOLC_PROFILE_TYPE" ]; then
        "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" pi-mcp-server "$PI_MCP_CONFIG_PATH" "$ARK_DOCS_MCP_NAME" "$ARK_DOCS_MCP_URL"
    fi
    if [ "$MODE" = "volc-agent" ] && [ -n "$UVX_BIN_PATH" ]; then
        for MCP_SOURCE_CANDIDATE in "${VOLC_AGENT_MCP_CANDIDATES[@]}"; do
            if [ -z "$VOLC_AGENT_MCP_SOURCE_PATH" ] && [ -f "$MCP_SOURCE_CANDIDATE" ]; then
                VOLC_AGENT_MCP_SOURCE_PATH="$MCP_SOURCE_CANDIDATE"
            fi
        done
        if [ -n "$VOLC_AGENT_MCP_SOURCE_PATH" ]; then
            "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" pi-mcp-source "$VOLC_AGENT_MCP_SOURCE_PATH" "$PI_MCP_CONFIG_PATH" "$VOLC_SEARCH_MCP_NAME" "$UVX_BIN_PATH"
        fi
    fi

    # Import Codex CLI OAuth only when Pi lacks its own entry. Pi refresh tokens
    # may rotate, so repeated source-to-destination overwrites are unsafe.
    if [ "$MODE" = "codex" ] || [ "$MODE" = "auto" ]; then
        if [ -f "$ORIGINAL_CODEX_HOME/auth.json" ]; then
            CODEX_AUTH_PATH="$ORIGINAL_CODEX_HOME/auth.json"
        fi
        if [ -n "$CODEX_AUTH_PATH" ]; then
            PI_AUTH_PATH="$PI_AGENT_DIR/auth.json"
            "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" codex-auth "$CODEX_AUTH_PATH" "$PI_AUTH_PATH"
        fi
    fi

    # pi-claude-auth reads credentials relative to HOME. Seed the isolated HOME
    # once and preserve subsequent token refreshes written by the extension.
    if [ "$MODE" = "claude" ] || [ "$MODE" = "auto" ]; then
        if [ -f "$ORIGINAL_CLAUDE_CONFIG_DIR/.credentials.json" ]; then
            CLAUDE_CREDENTIAL_PATH="$ORIGINAL_CLAUDE_CONFIG_DIR/.credentials.json"
        fi
        if [ -n "$CLAUDE_CREDENTIAL_PATH" ]; then
            "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" credential-file "$CLAUDE_CREDENTIAL_PATH" "$ISOLATED_CLAUDE_CREDENTIAL_PATH"
        fi
    fi
    if [ "$MODE" = "kimi" ] || [ "$MODE" = "auto" ]; then
        if [ -f "$KIMI_CODE_HOME_PATH/config.toml" ]; then
            KIMI_CONFIG_PATH="$KIMI_CODE_HOME_PATH/config.toml"
        elif [ -f "$ORIGINAL_HOME/.kimi-code/config.toml" ]; then
            KIMI_CONFIG_PATH="$ORIGINAL_HOME/.kimi-code/config.toml"
        fi
        if [ -n "$KIMI_CONFIG_PATH" ]; then
            PI_AUTH_PATH="$PI_AGENT_DIR/auth.json"
            "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" kimi-auth "$KIMI_CONFIG_PATH" "$PI_AUTH_PATH"
        fi
        if [ "$MODE" = "kimi" ]; then
            PI_AUTH_PATH="$PI_AGENT_DIR/auth.json"
            "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" pi-kimi-k3 "$PI_MODELS_PATH"
            "$NODE_BIN" "$HARNESS_SETTINGS_SCRIPT" kimi-tools "$KIMI_PROVIDER_CONFIG_PATH" "$PI_AUTH_PATH"
        fi
    fi
fi
export KIMI_CODE_HOME="$KIMI_CODE_HOME_PATH"
if [ "$MODE" = "claude" ] || [ "$MODE" = "auto" ]; then
    export CLAUDE_CONFIG_DIR="$ISOLATED_CLAUDE_DIR"
fi
export HOME="$PI_USER_DIR"
export USER_HOME="$PI_USER_DIR"
export USER_DIR="$PI_USER_DIR"
export PI_CODING_AGENT_DIR="$PI_AGENT_DIR"

PI_ARGS=(
    --approve
    --provider "$PROVIDER"
    --model "$MODEL"
    --thinking "$THINKING"
    --models "$ENABLED_MODELS"
)

echo ""
echo "============================================================"
echo "piyolo.sh"
echo "============================================================"
echo "[INFO] Mode: $MODE"
echo "[INFO] Default model: $PROVIDER/$MODEL ($THINKING)"
echo "[TIP] Thinking levels supported by Pi: off, minimal, low, medium, high, xhigh, max (xhigh = Extra High)."
echo "[TIP] Override temporarily with: ./piyolo.sh <mode> --thinking <level> or --thinking=<level>"
echo "[INFO] Pi user data: $PI_USER_DIR"
echo "[INFO] Project trust: approved; provider model cycling enabled"
echo "============================================================"
echo ""

if [ "$PREREQUISITES_READY" -eq 1 ] && [ "$PROVIDER_READY" -eq 1 ]; then
    unset SUDO_USER SUDO_UID SUDO_GID
    "$PI_BIN_PATH" "${PI_ARGS[@]}" "${FORWARD_ARGS[@]}"
elif [ "$PREREQUISITES_READY" -eq 1 ] && [ "$PROVIDER_READY" -eq 0 ]; then
    echo "[ERROR] No reusable $VOLC_PROFILE_TYPE API key was found in the local Ark profiles."
else
    if [ "${PIYOLO_AUTO_INSTALL:-0}" -eq 1 ]; then
        echo "[ERROR] Pi prerequisites are still incomplete after automatic installation."
        exit 1
    fi
    echo "[INFO] Pi prerequisites are incomplete. Automatically running 185_install_pi_harness.sh..."
    PI_HARNESS_SCRIPT="$CORE_NODE_DIR/scripts/shells/linux/debian/install_shells/185_install_pi_harness.sh"
    if [ -f "$PI_HARNESS_SCRIPT" ]; then
        bash "$PI_HARNESS_SCRIPT"
        echo "[INFO] Restarting piyolo.sh..."
        export PIYOLO_AUTO_INSTALL=1
        exec "$SCRIPT_SOURCE" "${FORWARD_ARGS[@]}"
    else
        echo "[ERROR] Pi prerequisites are incomplete. Run 185_install_pi_harness.sh first."
        exit 1
    fi
fi
