#!/bin/bash
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# SSH Connection Global File #1
# =============================================================================
#
# Synopsis:
#     SSH Connection Script
#
# Description:
#     This file is automatically generated by Special Software Environment Manager
#     Contains SSH connection setup for Linux systems with encrypted password storage
#
# Notes:
#     - Configuration: SSH Connection
#     - SSH Connection: Loaded dynamically from secret key SSH_CONNECTION_1
#     - File Number: 1
#     - File Name: ssh1.sh
# =============================================================================

set -e

echo ""
echo "============================================================"
echo "Running: ssh1.sh"
echo "============================================================"
echo ""

# =============================================================================
# Initialize Path Variables
# =============================================================================
# Resolve script real path (handle symlinks)
# When script is executed via symlink (e.g., from /usr/local/bin),
# BASH_SOURCE[0] returns symlink path. We need to resolve it to actual
# file path to get correct directory structure.
scriptSource="${BASH_SOURCE[0]}"

# Check if scriptSource is a symlink and resolve it
if [ -L "$scriptSource" ]; then
    # Resolve symlink to actual file path
    scriptSource="$(readlink -f "$scriptSource" 2>/dev/null || echo "$scriptSource")"
fi

# Get absolute path of script directory using cd + pwd for reliability
scriptCurrentPath="$(cd "$(dirname "$scriptSource")" && pwd)"

# Calculate project structure paths
# Expected structure: project_root/scripts/linuxenvs/script.sh
scriptsDirPath="$(cd "$scriptCurrentPath/.." && pwd)"
projectRootPath="$(cd "$scriptsDirPath/.." && pwd)"

echo "[DEBUG] Script Source: $scriptSource"
echo "[DEBUG] Script Path: $scriptCurrentPath"
echo "[DEBUG] Scripts Dir: $scriptsDirPath"
echo "[DEBUG] Project Root: $projectRootPath"
echo ""

# =============================================================================
# Load SSH Configuration via PyCore
# =============================================================================
echo ""
echo "============================================================"
echo "Loading SSH Configuration"
echo "============================================================"
echo ""

# Detect Python executable
PYTHON_EXECUTABLE=""
if command -v python3 &> /dev/null; then
    PYTHON_EXECUTABLE="python3"
elif command -v python &> /dev/null; then
    PYTHON_EXECUTABLE="python"
else
    echo "[ERROR] Python not found. Cannot load SSH secrets."
    exit 1
fi

SECRET_MANAGER_SCRIPT="$projectRootPath/pycore/pyfoundations/secret_manager.py"
echo "[DEBUG] Python executable: $PYTHON_EXECUTABLE"
echo "[DEBUG] Secret manager script: $SECRET_MANAGER_SCRIPT"
echo ""

# Function to get secret value
get_secret_value() {
    local key_name="$1"
    echo "[DEBUG] Loading secret key: $key_name" >&2

    # Switch to project root for Python execution
    cd "$projectRootPath"

    local value
    value=$("$PYTHON_EXECUTABLE" "$SECRET_MANAGER_SCRIPT" get_secret_key "$key_name" 2>/dev/null)
    local exit_code=$?

    if [ $exit_code -eq 0 ] && [ -n "$value" ]; then
        echo "$value"
        return 0
    else
        echo "[DEBUG] Failed to load secret: $key_name (exit code: $exit_code)" >&2
        return 1
    fi
}

SSH_CONNECTION=$(get_secret_value "SSH_CONNECTION_1")
if [ -n "$SSH_CONNECTION" ]; then
    echo "[SUCCESS] SSH Connection loaded: $SSH_CONNECTION"
else
    echo "[ERROR] SSH_CONNECTION not found"
    exit 1
fi

SSH_PASSWORD=$(get_secret_value "SSH_PASSWORD_1")
if [ -n "$SSH_PASSWORD" ]; then
    echo "[SUCCESS] SSH password loaded: $SSH_PASSWORD"
else
    echo "[INFO] No password configured (using SSH key authentication)"
fi
echo ""

# =============================================================================
# Execute SSH Connection
# =============================================================================
echo ""
echo "============================================================"
echo "Connecting to SSH Server"
echo "============================================================"
echo ""

if [ -z "$SSH_CONNECTION" ]; then
    echo "[ERROR] SSH connection string is empty"
    exit 1
fi

if [ -n "$SSH_PASSWORD" ]; then
    # SSH Key setup guide
    LOCAL_KEY="$HOME/.ssh/id_ed25519"
    LOCAL_PUB="$LOCAL_KEY.pub"
    echo ""
    echo "============================================================"
    echo "  SSH Key Setup Guide (passwordless login)"
    echo "============================================================"
    echo ""
    echo "  After login, run these commands to enable SSH key auth:"
    echo ""
    echo "  --- Step 1: Generate key on LOCAL machine (if not exists) ---"
    echo ""
    echo "  [ -f "$LOCAL_PUB" ] || ssh-keygen -t ed25519 -f "$LOCAL_KEY" -N """
    echo ""
    echo "  --- Step 2: Copy key to server (run on LOCAL) ---"
    echo ""
    echo "  # Option A: ssh-copy-id (Debian/Ubuntu/CentOS/Fedora):"
    echo "  ssh-copy-id -i "$LOCAL_PUB" $SSH_CONNECTION"
    echo ""
    echo "  # Option B: Manual (works on all distros):"
    echo "  cat "$LOCAL_PUB" | ssh $SSH_CONNECTION "mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys""
    echo ""
    echo "  --- Step 3: Verify (run on LOCAL) ---"
    echo ""
    echo "  ssh $SSH_CONNECTION "echo 'SSH key auth OK'""
    echo ""
    echo "  --- Notes ---"
    echo "  * Works on Debian/Ubuntu/CentOS/RHEL/AlmaLinux/Fedora"
    echo "  * Safe if server already has other keys (appends, not overwrites)"
    echo "  * Safe if local machine has other keys (ed25519 is separate from rsa)"
    echo "  * If server has SELinux: ssh $SSH_CONNECTION "restorecon -Rv ~/.ssh""
    echo "  * If using custom port: ssh -p PORT $SSH_CONNECTION"
    echo ""

    # Display password for copy-paste
    echo "============================================================"
    echo "  SSH PASSWORD (Copy this to clipboard):"
    echo "  $SSH_PASSWORD"
    echo "============================================================"
    echo ""
    echo "[INFO] SSH will prompt for password. Please paste the password above when prompted."
    echo ""
    echo "Executing: ssh $SSH_CONNECTION"
    echo ""

    # Execute SSH connection - it will prompt for password
    ssh "$SSH_CONNECTION" "$@"
else
    # No password configured, use SSH key authentication
    echo "[INFO] No password configured, using SSH key authentication"
    echo "Executing: ssh $SSH_CONNECTION"
    echo ""

    ssh "$SSH_CONNECTION" "$@"
fi

echo ""
echo "SSH session ended"
echo ""
