"""
Script Generator for Flutter Build Process
Generates multiple independent PowerShell scripts for different build phases

REAL-TIME OUTPUT BEST PRACTICES
================================

PowerShell output can be buffered in various scenarios. To ensure real-time output:

✅ DO use these methods:
1. Direct execution in current process:
   Invoke-Expression "flutter build apk"

2. Calling scripts with & operator (in current process):
   & $scriptPath

3. Start-Transcript for logging (doesn't buffer console output):
   Start-Transcript -Path "log.txt"
   flutter build apk
   Stop-Transcript

❌ DON'T use these (they buffer output):
1. Tee-Object (buffers entire pipeline):
   flutter build apk | Tee-Object -FilePath "log.txt"

2. Starting new PowerShell process:
   & powershell -File $scriptPath
   powershell -Command "flutter build apk"

3. Redirecting to file (buffers output):
   flutter build apk > log.txt
   flutter build apk *>&1 | Out-File log.txt

IMPLEMENTATION PATTERN
======================

For real-time output + logging:

```powershell
try {
    # Start transcript for logging
    Start-Transcript -Path "build_log.txt" -Force | Out-Null

    # Execute command directly (real-time output)
    Invoke-Expression "flutter build apk --release"
    $exitCode = $LASTEXITCODE

    # Stop transcript
    Stop-Transcript | Out-Null
} catch {
    Stop-Transcript -ErrorAction SilentlyContinue | Out-Null
    $exitCode = 1
}
```

This ensures:
- Console output appears in real-time
- Full output is logged to file
- Exit codes are preserved
- Errors are handled gracefully
"""

import os
import sys
from pathlib import Path
from typing import Dict, List, Any
import json

# Import path helper for unified path handling
from utils.path_helper import PathHelper

class ScriptGenerator:
    """Generate multiple independent PowerShell scripts for build process"""
    
    def __init__(self, build_root: str):
        self.build_root = Path(build_root)
        self.scripts_dir = self.build_root / "build_scripts"
        self.scripts_dir.mkdir(exist_ok=True)
    
    def generate_powershell_helpers(self) -> str:
        """Generate PowerShell helper functions"""
        return '''
# Path normalization helper function
function Normalize-Path {
    param(
        [string]$Path,
        [string]$TargetFormat = "flutter",
        [bool]$Debug = $false
    )
    
    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $Path
    }
    
    $Path = $Path.Trim()
    
    if ($Debug) {
        Write-Host "[PATH] Input: '$Path'" -ForegroundColor Gray
    }
    
    if ($TargetFormat -eq "flutter" -or $TargetFormat -eq "auto") {
        $Path = $Path -replace "\\\\+", "/"
        $Path = $Path -replace "\\", "/"
        $Path = $Path -replace "/+", "/"
    }
    elseif ($TargetFormat -eq "windows") {
        $Path = $Path -replace "/+", "\\"
        $Path = $Path -replace "/", "\\"
        $Path = $Path -replace "\\+", "\\"
    }
    
    if ($Path.StartsWith("/") -and -not $Path.StartsWith("//")) {
        $Path = $Path.Substring(1)
    }
    if ($Path.StartsWith("\\") -and -not $Path.StartsWith("\\\\")) {
        $Path = $Path.Substring(1)
    }
    
    if ($Debug) {
        Write-Host "[PATH] Output: '$Path'" -ForegroundColor Gray
    }
    
    return $Path
}

# Flutter command path fix helper function
function Fix-FlutterCommandPath {
    param(
        [string]$Command,
        [bool]$Debug = $false
    )
    
    if ([string]::IsNullOrWhiteSpace($Command)) {
        return $Command
    }
    
    if ($Debug) {
        Write-Host "[CMD] Original: '$Command'" -ForegroundColor Gray
    }
    
    $Command = $Command -replace " -t ([^\\s]+)", {
        $path = $matches[1]
        $normalizedPath = Normalize-Path -Path $path -TargetFormat "flutter" -Debug $Debug
        " -t $normalizedPath"
    }
    
    if ($Debug) {
        Write-Host "[CMD] Fixed: '$Command'" -ForegroundColor Gray
    }
    
    return $Command
}
'''
    
    def generate_cleanup_script(self, cleanup_info: Dict[str, Any], comprehensive_paths: Dict[str, Any]) -> str:
        """Generate comprehensive cleanup script with user confirmation"""
        script_content = f'''# Comprehensive Cache Cleanup Script
# Generated by script_generator.py

{self.generate_powershell_helpers()}

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  CLEANUP CONFIRMATION" -ForegroundColor Yellow
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This will clean the following:" -ForegroundColor White
Write-Host "  [1] Gradle cache (~/.gradle/caches)" -ForegroundColor Gray
Write-Host "  [2] Gradle wrapper (~/.gradle/wrapper)" -ForegroundColor Gray
Write-Host "  [3] Gradle daemon (~/.gradle/daemon)" -ForegroundColor Gray
Write-Host "  [4] Flutter build directories (build, .dart_tool)" -ForegroundColor Gray
Write-Host "  [5] Android build directories (android/build, android/.gradle)" -ForegroundColor Gray
Write-Host ""
Write-Host "WARNING: This operation cannot be undone!" -ForegroundColor Red
Write-Host ""

# Ask for confirmation
$confirmation = Read-Host "Do you want to proceed with cleanup? (Y/N) [N]"
if ([string]::IsNullOrWhiteSpace($confirmation)) {{ $confirmation = 'N' }}

if ($confirmation -eq 'Y' -or $confirmation -eq 'y') {{
    Write-Host ""
    Write-Host "[CLEANUP] Starting comprehensive cache cleanup..." -ForegroundColor Yellow

    # Stop Gradle daemons
    Write-Host "[CLEANUP] Stopping Gradle daemons..." -ForegroundColor Yellow
    try {{
        $gradleWrapperPath = Join-Path $env:USERPROFILE ".gradle\\wrapper\\dists\\gradle-8.11.1-bin"
        $gradleBatPath = Join-Path $gradleWrapperPath "*\\gradle-8.11.1\\bin\\gradle.bat"
        & $gradleBatPath --stop 2>$null
    }} catch {{
        Write-Host "[CLEANUP] Could not stop Gradle daemons (this is normal if no daemons are running)" -ForegroundColor Yellow
    }}

    # Clean Gradle cache using dynamic paths
    Write-Host "[CLEANUP] Cleaning Gradle cache..." -ForegroundColor Yellow
    $gradleCacheDir = Join-Path $env:USERPROFILE ".gradle\\caches"
    if (Test-Path $gradleCacheDir) {{
        Remove-Item -Path $gradleCacheDir -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "[CLEANUP]   Removed: $gradleCacheDir" -ForegroundColor Gray
    }}
    $gradleWrapperDir = Join-Path $env:USERPROFILE ".gradle\\wrapper"
    if (Test-Path $gradleWrapperDir) {{
        Remove-Item -Path $gradleWrapperDir -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "[CLEANUP]   Removed: $gradleWrapperDir" -ForegroundColor Gray
    }}
    $gradleDaemonDir = Join-Path $env:USERPROFILE ".gradle\\daemon"
    if (Test-Path $gradleDaemonDir) {{
        Remove-Item -Path $gradleDaemonDir -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "[CLEANUP]   Removed: $gradleDaemonDir" -ForegroundColor Gray
    }}

    # Check if pubspec cache optimization is enabled
    $skipPubGetFlag = ".skip_pub_get"
    $pubCacheOptimized = Test-Path $skipPubGetFlag

    if ($pubCacheOptimized) {{
        Write-Host "[CLEANUP] Pubspec cache optimization detected - preserving .pub-cache" -ForegroundColor Green
        Write-Host "[CLEANUP] Using selective cleanup instead of flutter clean" -ForegroundColor Yellow

        # Manual selective cleanup (excluding .pub-cache)
        $cleanupPaths = @("build", ".dart_tool")
        foreach ($path in $cleanupPaths) {{
            if (Test-Path $path) {{
                Remove-Item -Path $path -Recurse -Force -ErrorAction SilentlyContinue
                Write-Host "[CLEANUP]   Removed: $path" -ForegroundColor Gray
            }}
        }}

        # Clean Android build directories
        $androidCleanupPaths = @("android\\.gradle", "android\\build")
        foreach ($path in $androidCleanupPaths) {{
            if (Test-Path $path) {{
                Remove-Item -Path $path -Recurse -Force -ErrorAction SilentlyContinue
                Write-Host "[CLEANUP]   Removed: $path" -ForegroundColor Gray
            }}
        }}
    }} else {{
        Write-Host "[CLEANUP] Cleaning Flutter build directories..." -ForegroundColor Yellow
        flutter clean
        {chr(10).join([f'if (Test-Path "{path}") {{ Remove-Item -Path "{path}" -Recurse -Force -ErrorAction SilentlyContinue; Write-Host "[CLEANUP]   Removed: {path}" -ForegroundColor Gray }}' for path in comprehensive_paths['flutter_paths']])}
        {chr(10).join([f'if (Test-Path "{android_path}") {{ Remove-Item -Path "{android_path}" -Recurse -Force -ErrorAction SilentlyContinue; Write-Host "[CLEANUP]   Removed: {android_path}" -ForegroundColor Gray }}' for android_path in ['android' + chr(92) + path for path in comprehensive_paths['android_paths']]])}
    }}

    # Clean additional cache directories
    Write-Host "[CLEANUP] Cleaning additional cache directories..." -ForegroundColor Yellow
    $rootCacheDir = Join-Path (Get-Location) "cache"
    if (Test-Path $rootCacheDir) {{
        try {{
            Remove-Item $rootCacheDir -Recurse -Force
            Write-Host "[CLEANUP]   Removed root cache directory" -ForegroundColor Gray
        }} catch {{
            Write-Host "[CLEANUP]   Could not remove root cache directory: $_" -ForegroundColor Yellow
        }}
    }}

    # NOTE: flutter pub get removed - it will be called automatically by flutter build
    # This prevents duplicate dependency resolution that was causing infinite loops

    Write-Host ""
    Write-Host "[CLEANUP] Comprehensive cleanup completed!" -ForegroundColor Green
    Write-Host ""
}} else {{
    Write-Host ""
    Write-Host "[CLEANUP] Cleanup cancelled by user" -ForegroundColor Yellow
    Write-Host "[CLEANUP] Skipping cleanup and continuing with build..." -ForegroundColor Yellow
    Write-Host ""
}}
'''
        return script_content
    
    def generate_kotlin_fix_script(self, cleanup_info: Dict[str, Any]) -> str:
        """Generate Kotlin configuration fix script"""
        script_content = f'''# Kotlin Configuration Fix Script
# Generated by script_generator.py

{self.generate_powershell_helpers()}

Write-Host "[KOTLIN] Starting Kotlin incremental compilation fix..." -ForegroundColor Yellow

# Fix Kotlin incremental compilation using Python script
if ("{str(cleanup_info['kotlin']['needs_fix']).lower()}" -eq "true") {{
    Write-Host "[KOTLIN] Fixing Kotlin incremental compilation..." -ForegroundColor Yellow
    $kotlinScriptPath = "{cleanup_info['kotlin']['python_script_path']}"
    if (Test-Path $kotlinScriptPath) {{
        try {{
            $result = python $kotlinScriptPath fix (Get-Location) 2>&1
            if ($LASTEXITCODE -eq 0) {{
                Write-Host "[KOTLIN] Kotlin configuration fixed successfully" -ForegroundColor Green
            }} else {{
                Write-Host "[KOTLIN] Kotlin configuration fix failed: $result" -ForegroundColor Red
            }}
        }} catch {{
            Write-Host "[KOTLIN] Error running Kotlin config script: $_" -ForegroundColor Red
        }}
    }} else {{
        Write-Host "[KOTLIN] Kotlin config script not found: $kotlinScriptPath" -ForegroundColor Yellow
    }}
}} else {{
    Write-Host "[KOTLIN] Kotlin incremental compilation is already disabled" -ForegroundColor Green
}}

Write-Host "[KOTLIN] Kotlin fix completed!" -ForegroundColor Green
'''
        return script_content
    
    def generate_retry_cleanup_script(self, retry_paths: Dict[str, Any], attempt: int) -> str:
        """Generate retry cleanup script"""
        script_content = f'''# Retry Cleanup Script (Attempt {attempt})
# Generated by script_generator.py

{self.generate_powershell_helpers()}

Write-Host "[RETRY] Performing aggressive cleanup for retry attempt {attempt}..." -ForegroundColor Red

# Stop Gradle daemons
try {{
    $gradleWrapperPath = Join-Path $env:USERPROFILE ".gradle\\wrapper\\dists\\gradle-8.11.1-bin"
    $gradleBatPath = Join-Path $gradleWrapperPath "*\\gradle-8.11.1\\bin\\gradle.bat"
    & $gradleBatPath --stop 2>$null
}} catch {{
    Write-Host "Could not stop Gradle daemons" -ForegroundColor Yellow
}}

# Check if pubspec cache optimization is enabled
$skipPubGetFlag = ".skip_pub_get"
$pubCacheOptimized = Test-Path $skipPubGetFlag

if ($pubCacheOptimized) {{
    Write-Host "[RETRY] Pubspec cache optimization detected - preserving .pub-cache" -ForegroundColor Green
    Write-Host "[RETRY] Using selective cleanup" -ForegroundColor Yellow

    # Manual selective cleanup (excluding .pub-cache)
    $cleanupPaths = @("build", ".dart_tool")
    foreach ($path in $cleanupPaths) {{
        if (Test-Path $path) {{
            Remove-Item -Path $path -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "[RETRY]   Removed: $path" -ForegroundColor Gray
        }}
    }}

    # Clean Android build directories
    $androidCleanupPaths = @("android\\.gradle", "android\\build")
    foreach ($path in $androidCleanupPaths) {{
        if (Test-Path $path) {{
            Remove-Item -Path $path -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "[RETRY]   Removed: $path" -ForegroundColor Gray
        }}
    }}
}} else {{
    # Aggressive cleanup using Python-provided paths
    flutter clean
    {chr(10).join([f'Remove-Item -Path "{path}" -Recurse -Force -ErrorAction SilentlyContinue' for path in retry_paths['flutter_paths']])}
    {chr(10).join([f'Remove-Item -Path "{android_path}" -Recurse -Force -ErrorAction SilentlyContinue' for android_path in ['android' + chr(92) + path for path in retry_paths['android_paths']]])}
}}

# Clean Gradle cache using dynamic paths
$gradleCacheDir = Join-Path $env:USERPROFILE ".gradle\\caches"
if (Test-Path $gradleCacheDir) {{ Remove-Item -Path $gradleCacheDir -Recurse -Force -ErrorAction SilentlyContinue }}

Write-Host "[RETRY] Additional cleanup completed, retrying build..." -ForegroundColor Green
'''
        return script_content
    
    def generate_build_script(self, flutter_command: str) -> str:
        """Generate main build script"""
        script_content = f'''# Flutter Build Script
# Generated by script_generator.py

{self.generate_powershell_helpers()}

Write-Host "[BUILD] Starting Flutter build process..." -ForegroundColor Yellow

# ================================================================
# PUBSPEC CACHE OPTIMIZATION CHECK
# ================================================================
$skipPubGetFlag = ".skip_pub_get"
$offlineMode = $false

if (Test-Path $skipPubGetFlag) {{
    Write-Host ""
    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host "  PUBSPEC CACHE OPTIMIZATION ENABLED" -ForegroundColor Green
    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host "[INFO] pubspec.yaml unchanged, using cached packages" -ForegroundColor Gray
    Write-Host "[INFO] Skipping network download, using offline mode" -ForegroundColor Gray
    Write-Host "================================================================" -ForegroundColor Cyan
    Write-Host ""
    $offlineMode = $true
}} else {{
    Write-Host "[INFO] No cache optimization flag found, will download packages as needed" -ForegroundColor Gray
}}

# ================================================================
# STATIC ANALYSIS PHASE (Disabled to avoid duplicate pub get)
# ================================================================
# Note: flutter analyze has been disabled because:
# 1. It triggers pub get, causing duplicate downloads before flutter build
# 2. Analysis errors don't prevent compilation from succeeding
# 3. Compilation will catch actual blocking errors
#
# To run analysis separately, use: flutter analyze
# Or enable this section if needed for CI/CD
Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  SKIPPING STATIC ANALYSIS (Avoiding duplicate pub get)" -ForegroundColor Yellow
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "[INFO] flutter analyze disabled to prevent duplicate dependency downloads" -ForegroundColor Gray
Write-Host "[INFO] Proceeding directly to compilation..." -ForegroundColor Gray
Write-Host "[INFO] Run 'flutter analyze' separately if needed" -ForegroundColor Gray
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# ================================================================
# COMPILATION PHASE (Targets specific entry point)
# ================================================================
Write-Host "[BUILD] Proceeding with compilation..." -ForegroundColor Green

# Modify flutter command based on offline mode
$flutterCommand = "{flutter_command}"
if ($offlineMode) {{
    # Add --offline flag to use cached packages
    $flutterCommand = $flutterCommand + " --offline"
    Write-Host "[BUILD] Using offline mode (cached packages)" -ForegroundColor Green
}}

Write-Host "[BUILD] Executing: $flutterCommand" -ForegroundColor Cyan
Write-Host "[BUILD] Starting real-time output..." -ForegroundColor Yellow
Write-Host "" # Empty line for clarity

# Execute command directly with real-time output
# Important: Don't use Tee-Object or pipeline - they buffer output!
# Instead, execute directly and log separately
try {{
    # Start transcript for logging
    $logFile = "build_log.txt"
    Start-Transcript -Path $logFile -Force | Out-Null

    # Execute command directly (real-time output to console)
    Invoke-Expression $flutterCommand
    $exitCode = $LASTEXITCODE

    # Stop transcript
    Stop-Transcript | Out-Null
}} catch {{
    Write-Host "[BUILD] Error executing command: $_" -ForegroundColor Red
    Stop-Transcript -ErrorAction SilentlyContinue | Out-Null
    $exitCode = 1
}}

if ($exitCode -eq 0) {{
    Write-Host "[BUILD] Command completed successfully" -ForegroundColor Green

    # Scan for APK files after successful build
    Write-Host "[BUILD] Scanning for APK files..." -ForegroundColor Cyan
    $apkSearchPaths = @(
        "build/app/outputs/flutter-apk",
        "build/app/outputs/apk/debug",
        "build/app/outputs/apk/release"
    )

    $foundApks = @()
    foreach ($searchPath in $apkSearchPaths) {{
        $fullPath = Join-Path (Get-Location) $searchPath
        if (Test-Path $fullPath) {{
            $apkFiles = Get-ChildItem -Path $fullPath -Filter "*.apk" -File
            foreach ($apk in $apkFiles) {{
                $foundApks += $apk.FullName
            }}
        }}
    }}

    if ($foundApks.Count -gt 0) {{
        Write-Host "[BUILD] Found APK files:" -ForegroundColor Green
        foreach ($apk in $foundApks) {{
            Write-Host "[BUILD]   $apk" -ForegroundColor Gray
        }}

        # Collect unique APK directories and open each in Explorer
        $apkDirs = $foundApks | ForEach-Object {{ (Resolve-Path -LiteralPath (Split-Path -Parent $_)).Path }} | Sort-Object -Unique
        Write-Host ""
        Write-Host "[BUILD] Opening APK directory in Explorer... (count: $($apkDirs.Count))" -ForegroundColor Cyan
        foreach ($apkDir in $apkDirs) {{
            Write-Host "[BUILD]   Directory: $apkDir" -ForegroundColor Gray
            try {{
                $openCmd = "Invoke-Item -LiteralPath `"$apkDir`""
                Write-Host "[BUILD] Open command: $openCmd" -ForegroundColor Gray
                Invoke-Item -LiteralPath $apkDir
                Write-Host "[BUILD] Explorer opened successfully" -ForegroundColor Green
            }} catch {{
                Write-Host "[BUILD] Failed to open Explorer: $_" -ForegroundColor Yellow
            }}
        }}
        # Print adb install command for easy copy (use first release APK, else first found)
        $apkForAdb = $foundApks | Where-Object {{ $_.ToString() -like '*release*.apk' }} | Select-Object -First 1
        if (-not $apkForAdb) {{ $apkForAdb = $foundApks[0] }}
        if ($apkForAdb) {{
            Write-Host ""
            Write-Host "[BUILD] ADB install (copy): adb install -r `"$apkForAdb`"" -ForegroundColor Cyan
        }}
    }} else {{
        Write-Host "[BUILD] No APK files found in expected locations" -ForegroundColor Yellow
    }}
}} else {{
    Write-Host "[BUILD] Command failed with exit code: $exitCode" -ForegroundColor Red
}}

Write-Host "[BUILD] Build process completed with exit code: $exitCode" -ForegroundColor $(if ($exitCode -eq 0) {{ "Green" }} else {{ "Red" }})
exit $exitCode
'''
        return script_content
    
    def generate_main_orchestrator_script(self, script_files: Dict[str, str]) -> str:
        """Generate main orchestrator script that calls other scripts"""

        try:
            # Normalize all paths using PathHelper for consistency
            cleanup_script = PathHelper.normalize_for_powershell(script_files.get('cleanup_script', ''))
            kotlin_fix_script = PathHelper.normalize_for_powershell(script_files.get('kotlin_fix_script', ''))
            build_script = PathHelper.normalize_for_powershell(script_files.get('build_script', ''))

            # Validate that all required scripts exist
            if not cleanup_script or not kotlin_fix_script or not build_script:
                raise ValueError(f"Missing required script files: {script_files}")
        except Exception as e:
            print(f"[ScriptGenerator ERROR] Failed to normalize script paths: {e}")
            # Fallback to original paths
            cleanup_script = script_files.get('cleanup_script', '')
            kotlin_fix_script = script_files.get('kotlin_fix_script', '')
            build_script = script_files.get('build_script', '')

        script_content = f'''# Main Build Orchestrator Script
# Generated by script_generator.py

{self.generate_powershell_helpers()}

Write-Host "[ORCHESTRATOR] Starting Flutter build orchestration..." -ForegroundColor Yellow

# Step 1: Comprehensive cleanup (only on first run, not on retries)
Write-Host "[ORCHESTRATOR] Step 1: Running comprehensive cleanup..." -ForegroundColor Cyan
try {{
    & "{cleanup_script}"
    if ($LASTEXITCODE -ne 0) {{
        Write-Host "[ORCHESTRATOR] Cleanup failed, but continuing..." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "[ORCHESTRATOR] Cleanup script error: $_" -ForegroundColor Red
}}

# Step 2: Kotlin configuration fix
Write-Host "[ORCHESTRATOR] Step 2: Running Kotlin configuration fix..." -ForegroundColor Cyan
try {{
    & "{kotlin_fix_script}"
    if ($LASTEXITCODE -ne 0) {{
        Write-Host "[ORCHESTRATOR] Kotlin fix failed, but continuing..." -ForegroundColor Yellow
    }}
}} catch {{
    Write-Host "[ORCHESTRATOR] Kotlin fix script error: $_" -ForegroundColor Red
}}

# Step 3: Main build with retry logic (reduced retries to prevent infinite loops)
Write-Host "[ORCHESTRATOR] Step 3: Starting main build process..." -ForegroundColor Cyan
$maxRetries = 1
$retryCount = 0
$exitCode = 1

while ($retryCount -le $maxRetries -and $exitCode -ne 0) {{
    if ($retryCount -gt 0) {{
        Write-Host "[ORCHESTRATOR] Retry attempt $retryCount of $maxRetries..." -ForegroundColor Yellow
        Write-Host "[ORCHESTRATOR] Waiting 5 seconds before retry..." -ForegroundColor Gray
        Start-Sleep -Seconds 5

        # Ask for retry cleanup confirmation
        Write-Host ""
        Write-Host "[ORCHESTRATOR] Build failed. Do you want to clean and retry?" -ForegroundColor Yellow
        $retryConfirmation = Read-Host "Clean build directories and retry? (Y/N) [N]"
        if ([string]::IsNullOrWhiteSpace($retryConfirmation)) {{ $retryConfirmation = 'N' }}

        if ($retryConfirmation -eq 'Y' -or $retryConfirmation -eq 'y') {{
            # Run retry cleanup (lighter cleanup for retries)
            try {{
                Write-Host "[ORCHESTRATOR] Running retry cleanup..." -ForegroundColor Yellow

                # Check if pubspec cache optimization is enabled
                $skipPubGetFlag = ".skip_pub_get"
                if (Test-Path $skipPubGetFlag) {{
                    Write-Host "[ORCHESTRATOR] Pubspec cache optimization enabled - using selective cleanup" -ForegroundColor Green
                    # Only clean build and .dart_tool, preserve .pub-cache
                    if (Test-Path "build") {{ Remove-Item -Path "build" -Recurse -Force -ErrorAction SilentlyContinue }}
                    if (Test-Path ".dart_tool") {{ Remove-Item -Path ".dart_tool" -Recurse -Force -ErrorAction SilentlyContinue }}
                    if (Test-Path "android\\.gradle") {{ Remove-Item -Path "android\\.gradle" -Recurse -Force -ErrorAction SilentlyContinue }}
                    if (Test-Path "android\\build") {{ Remove-Item -Path "android\\build" -Recurse -Force -ErrorAction SilentlyContinue }}
                }} else {{
                    flutter clean
                }}

                Write-Host "[ORCHESTRATOR] Note: flutter pub get will be called automatically by flutter build" -ForegroundColor Gray
            }} catch {{
                Write-Host "[ORCHESTRATOR] Retry cleanup error: $_" -ForegroundColor Red
            }}
        }} else {{
            Write-Host "[ORCHESTRATOR] Retry cancelled by user" -ForegroundColor Yellow
            break  # Exit retry loop
        }}
    }}

    # Run main build with timeout protection
    try {{
        Write-Host "[ORCHESTRATOR] Executing build script (attempt $($retryCount + 1))..." -ForegroundColor Cyan
        & "{build_script}"
        $exitCode = $LASTEXITCODE

        if ($exitCode -ne 0) {{
            Write-Host "[ORCHESTRATOR] Build failed with exit code: $exitCode" -ForegroundColor Red
        }}
    }} catch {{
        Write-Host "[ORCHESTRATOR] Build script error: $_" -ForegroundColor Red
        $exitCode = 1
    }}

    $retryCount++
}}

# Final result
if ($exitCode -eq 0) {{
    Write-Host "[ORCHESTRATOR] Build completed successfully!" -ForegroundColor Green
}} else {{
    Write-Host "[ORCHESTRATOR] Build failed after $maxRetries retries" -ForegroundColor Red
    Write-Host "[ORCHESTRATOR] Common solutions:" -ForegroundColor Yellow
    Write-Host "[ORCHESTRATOR] 1. Check network connectivity for pub.dev dependencies" -ForegroundColor Gray
    Write-Host "[ORCHESTRATOR] 2. Check if Kotlin incremental compilation is disabled in android/gradle.properties" -ForegroundColor Gray
    Write-Host "[ORCHESTRATOR] 3. Ensure all dependencies are up to date: flutter pub upgrade" -ForegroundColor Gray
    Write-Host "[ORCHESTRATOR] 4. Try building debug version first: flutter build apk --debug" -ForegroundColor Gray
    Write-Host "[ORCHESTRATOR] 5. Check Flutter and Dart versions: flutter doctor" -ForegroundColor Gray
    Write-Host "[ORCHESTRATOR] 6. Check error log at: build_log.txt" -ForegroundColor Gray
}}

exit $exitCode
'''
        return script_content
    
    def generate_all_scripts(self, cleanup_info: Dict[str, Any], comprehensive_paths: Dict[str, Any],
                           retry_paths: Dict[str, Any], flutter_command: str) -> Dict[str, str]:
        """Generate all script files and return their paths"""
        script_files = {}

        try:
            # Generate cleanup script
            cleanup_script_path = self.scripts_dir / "01_cleanup.ps1"
            cleanup_script_path.write_text(self.generate_cleanup_script(cleanup_info, comprehensive_paths), encoding='utf-8')
            script_files['cleanup_script'] = str(cleanup_script_path)

            # Generate Kotlin fix script
            kotlin_fix_script_path = self.scripts_dir / "02_kotlin_fix.ps1"
            kotlin_fix_script_path.write_text(self.generate_kotlin_fix_script(cleanup_info), encoding='utf-8')
            script_files['kotlin_fix_script'] = str(kotlin_fix_script_path)

            # Generate retry cleanup script
            retry_cleanup_script_path = self.scripts_dir / "03_retry_cleanup.ps1"
            retry_cleanup_script_path.write_text(self.generate_retry_cleanup_script(retry_paths, 1), encoding='utf-8')
            script_files['retry_cleanup_script'] = str(retry_cleanup_script_path)

            # Generate main build script
            build_script_path = self.scripts_dir / "04_build.ps1"
            build_script_path.write_text(self.generate_build_script(flutter_command), encoding='utf-8')
            script_files['build_script'] = str(build_script_path)

            # Generate main orchestrator script
            orchestrator_script_path = self.scripts_dir / "00_orchestrator.ps1"
            orchestrator_script_path.write_text(self.generate_main_orchestrator_script(script_files), encoding='utf-8')
            script_files['orchestrator_script'] = str(orchestrator_script_path)

            print(f"[ScriptGenerator] Successfully generated {len(script_files)} scripts")
            return script_files

        except Exception as e:
            print(f"[ScriptGenerator ERROR] Failed to generate scripts: {e}")
            import traceback
            traceback.print_exc()
            raise


def main():
    """Main function for command line usage"""
    if len(sys.argv) < 2:
        print("Usage: python script_generator.py <command> [args...]")
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "test":
        # Test script generation
        build_root = sys.argv[2] if len(sys.argv) > 2 else "."
        generator = ScriptGenerator(build_root)
        
        # Mock data for testing - use dynamic paths
        import os
        user_home = os.path.expanduser("~")
        gradle_home = os.path.join(user_home, '.gradle')
        
        cleanup_info = {
            'gradle': {'gradle_wrapper_path': os.path.join(gradle_home, 'wrapper', 'dists', 'gradle-8.11.1-bin')},
            'kotlin': {'needs_fix': True, 'python_script_path': 'scripts/build_scripts/utils/kotlin_config_manager.py'}
        }
        comprehensive_paths = {
            'gradle_paths': [os.path.join(gradle_home, 'caches')],
            'flutter_paths': ['build', '.dart_tool'],
            'android_paths': ['.gradle', 'build']
        }
        retry_paths = {
            'gradle_bin_path': os.path.join(gradle_home, 'wrapper', 'dists', 'gradle-8.11.1-bin', '*', 'gradle-8.11.1', 'bin', 'gradle.bat'),
            'gradle_paths': [os.path.join(gradle_home, 'caches')],
            'flutter_paths': ['build', '.dart_tool'],
            'android_paths': ['.gradle', 'build']
        }
        flutter_command = "flutter build apk --release"
        apk_search_paths = ["build/app/outputs/flutter-apk"]
        
        script_files = generator.generate_all_scripts(cleanup_info, comprehensive_paths, retry_paths, flutter_command, apk_search_paths)
        print(f"Generated scripts: {json.dumps(script_files, indent=2)}")
    
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)


if __name__ == "__main__":
    main()
