# -*- coding: utf-8 -*-
"""Canonical Win32 window styles, show commands, and positioning constants."""

GWL_EXSTYLE = -20
GWLP_HWNDPARENT = -8

WS_EX_TOPMOST = 0x00000008
WS_EX_TOOLWINDOW = 0x00000080
WS_EX_APPWINDOW = 0x00040000

SW_HIDE = 0
SW_SHOWNORMAL = 1
SW_SHOWMINIMIZED = 2
SW_SHOWMAXIMIZED = 3
SW_SHOWNOACTIVATE = 4
SW_SHOW = 5
SW_MINIMIZE = 6
SW_RESTORE = 9

SWP_NOSIZE = 0x0001
SWP_NOMOVE = 0x0002
SWP_NOZORDER = 0x0004
SWP_NOACTIVATE = 0x0010
SWP_FRAMECHANGED = 0x0020
SWP_SHOWWINDOW = 0x0040

HWND_TOP = 0

__all__ = [
    "GWLP_HWNDPARENT",
    "GWL_EXSTYLE",
    "HWND_TOP",
    "SWP_FRAMECHANGED",
    "SWP_NOACTIVATE",
    "SWP_NOMOVE",
    "SWP_NOSIZE",
    "SWP_NOZORDER",
    "SWP_SHOWWINDOW",
    "SW_HIDE",
    "SW_MINIMIZE",
    "SW_RESTORE",
    "SW_SHOW",
    "SW_SHOWMAXIMIZED",
    "SW_SHOWMINIMIZED",
    "SW_SHOWNOACTIVATE",
    "SW_SHOWNORMAL",
    "WS_EX_APPWINDOW",
    "WS_EX_TOOLWINDOW",
    "WS_EX_TOPMOST",
]
