#!/usr/bin/env python3
"""
Directory Tree Generator
Generate directory tree structure with filtering and cross-platform path handling
"""

import os
import sys
import argparse
from pathlib import Path

# Directories to skip (at any level)
SKIP_DIRS = {
    'node_modules', '__pycache__', '.git', '.svn', '.hg', 'dist', 'build', 
    'tmp', 'temp', '.vscode', '.idea', '.cache', 'logs', 'vendor',
    'venv', '.venv', 'env', '.env', 'site-packages', '.pub-cache',
    'flutter', '.flutter', '.dart_tool', 'coverage', '.nyc_output'
}

# File extensions to skip
SKIP_EXTENSIONS = {
    '.log', '.tmp', '.temp', '.cache', '.lock', '.pid', '.swp', '.swo',
    '.DS_Store', '.Thumbs.db', '.desktop', '.lnk', '.url'
}

def normalize_path(path_str):
    """Normalize path, handle Windows/Linux differences"""
    if not path_str:
        return None
    
    # Handle relative paths
    if not os.path.isabs(path_str):
        # Get parent directory of parent directory (../..)
        script_dir = Path(__file__).parent
        base_dir = script_dir.parent.parent
        return base_dir / path_str
    else:
        return Path(path_str)

def should_skip_directory(dir_name):
    """Check if directory should be skipped"""
    return dir_name in SKIP_DIRS

def should_skip_file(file_name):
    """Check if file should be skipped"""
    ext = Path(file_name).suffix.lower()
    return ext in SKIP_EXTENSIONS

def should_skip_hidden(item_name):
    """Check if hidden file/directory should be skipped"""
    return item_name.startswith('.') and item_name not in {'.env', '.gitignore'}


def generate_tree(path, prefix="", max_depth=None, current_depth=0):
    """Generate directory tree structure"""
    if max_depth is not None and current_depth >= max_depth:
        return []
    
    try:
        items = sorted(os.listdir(path))
    except PermissionError:
        return [f"{prefix}├── [Permission Denied]"]
    except Exception as e:
        return [f"{prefix}├── [Error: {e}]"]
    
    # Separate directories and files
    dirs = []
    files = []
    
    for item in items:
        if should_skip_hidden(item):
            continue
            
        item_path = os.path.join(path, item)
        if os.path.isdir(item_path):
            if not should_skip_directory(item):
                dirs.append(item)
        else:
            if not should_skip_file(item):
                files.append(item)
    
    result = []
    all_items = []
    
    # Add directories
    for dir_name in dirs:
        all_items.append((dir_name, 'dir'))
    
    # Add all files individually
    for file_name in files:
        all_items.append((file_name, 'file'))
    
    # Generate tree structure
    for i, (name, item_type) in enumerate(all_items):
        is_last = i == len(all_items) - 1
        current_prefix = "└── " if is_last else "├── "
        
        if item_type == 'dir':
            result.append(f"{prefix}{current_prefix}{name}/")
            # Recursively process subdirectory
            sub_path = os.path.join(path, name)
            next_prefix = prefix + ("    " if is_last else "│   ")
            sub_items = generate_tree(sub_path, next_prefix, max_depth, current_depth + 1)
            result.extend(sub_items)
        else:
            result.append(f"{prefix}{current_prefix}{name}")
    
    return result

def save_tree_to_file(tree_items, target_path, output_path):
    """Save directory tree to file"""
    content = []
    content.append(f"# Directory Tree: {target_path.name}")
    content.append("")
    content.append(f"**Path:** `{target_path}`")
    content.append("")
    content.append("```")
    content.append(f"{target_path.name}/")
    content.extend(tree_items)
    content.append("```")
    content.append("")
    content.append("---")
    content.append("*Generated by Directory Tree Generator*")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(content))

def main():
    parser = argparse.ArgumentParser(
        description="Generate directory tree structure",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python directory_tree.py                    # Generate ../../ directory tree
  python directory_tree.py ./apps             # Generate specified directory tree
        """
    )
    
    parser.add_argument('path', nargs='?', help='Target directory path (relative or absolute)')
    
    args = parser.parse_args()
    
    # Determine target path
    if args.path:
        target_path = normalize_path(args.path)
    else:
        # Default to ../../ directory
        script_dir = Path(__file__).parent
        target_path = script_dir.parent.parent
    
    if not target_path.exists():
        print(f"Error: Path does not exist: {target_path}")
        sys.exit(1)
    
    if not target_path.is_dir():
        print(f"Error: Not a directory: {target_path}")
        sys.exit(1)
    
    print(f"Generating directory tree: {target_path}")
    
    # Generate directory tree
    tree_items = generate_tree(str(target_path))
    
    # Output to file
    output_path = target_path / f"{target_path.name}_tree.md"
    save_tree_to_file(tree_items, target_path, output_path)
    print(f"Directory tree saved to: {output_path}")

if __name__ == "__main__":
    main()
