#!/bin/bash
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###
#
# =============================================================================
# desktop_browser_bridge.sh - shared browser-launch bridge for root-mode GUI apps.
#
# Root-mode Electron apps (pkexec launchers, e.g. Cursor / Antigravity / VS Code)
# must not spawn the web browser as root: Chrome/Chromium abort as root ("Running
# as root without --no-sandbox is not supported") and a root-owned browser cannot
# reach the desktop user's login session, so "Sign in" buttons silently do
# nothing. This library installs ONE shared shim directory containing an xdg-open
# that re-invokes the REAL xdg-open as the active desktop user. Root-mode
# launchers prepend that directory to PATH so every openExternal/URL open inside
# the app tree lands in the user's session (login pages, "open folder", etc.).
# Non-root callers pass straight through, so user-mode apps are unaffected.
#
# Public API (ONE function):
#   ensure_desktop_browser_bridge   - idempotently (re)write the shim; safe to
#                                     call from every installer run.
#   DBB_BRIDGE_DIR                  - directory to prepend to PATH in launchers.
# =============================================================================

# ---- variable declarations (all at top) -------------------------------------
DBB_BRIDGE_DIR="/usr/local/lib/core_node/browser-bridge"
DBB_REAL_XDG_OPEN="/usr/bin/xdg-open"

# Privilege prefix: honor a caller-set USE_SUDO (gvar_common); else derive it.
_dbb_sudo() {
    if [ -n "${USE_SUDO+x}" ]; then printf '%s' "$USE_SUDO"; return 0; fi
    if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then printf 'sudo'; fi
}

# Idempotently install the xdg-open shim. Resolves the desktop user at RUNTIME
# (pkexec sets PKEXEC_UID, sudo sets SUDO_UID; otherwise the seated loginctl
# session owner) so one shim serves every root-mode app and every user.
ensure_desktop_browser_bridge() {
    local sudo=""
    sudo="$(_dbb_sudo)"

    $sudo mkdir -p "$DBB_BRIDGE_DIR" 2>/dev/null || true

    $sudo tee "$DBB_BRIDGE_DIR/xdg-open" >/dev/null <<'DBBEOF'
#!/bin/bash
# core_node browser bridge (generated by desktop_browser_bridge.sh -- do not edit).
# Re-invokes the real xdg-open as the active desktop user when called as root, so
# browsers and URL handlers start inside the desktop session (root-spawned
# Chrome/Chromium refuse to run, which silently kills app "Sign in" buttons).
DBB_REAL_XDG_OPEN="/usr/bin/xdg-open"
DBB_TARGET_UID="${PKEXEC_UID:-${SUDO_UID:-}}"
DBB_TARGET_HOME=""

# Not root: nothing to bridge.
if [ "$(id -u)" -ne 0 ]; then
    exec "$DBB_REAL_XDG_OPEN" "$@"
fi

# Resolve desktop user: pkexec/sudo caller first, else the seated session owner.
if [ -z "$DBB_TARGET_UID" ] || [ "$DBB_TARGET_UID" = "0" ]; then
    DBB_TARGET_UID="$(loginctl list-sessions --no-legend 2>/dev/null | awk '$4 != "" && $4 != "-" {print $2; exit}')"
fi
if [ -z "$DBB_TARGET_UID" ] || [ "$DBB_TARGET_UID" = "0" ]; then
    exec "$DBB_REAL_XDG_OPEN" "$@"
fi

DBB_TARGET_HOME="$(getent passwd "$DBB_TARGET_UID" 2>/dev/null | cut -d: -f6)"
[ -n "$DBB_TARGET_HOME" ] || exec "$DBB_REAL_XDG_OPEN" "$@"

exec sudo -u "#$DBB_TARGET_UID" env \
    HOME="$DBB_TARGET_HOME" \
    XDG_RUNTIME_DIR="/run/user/$DBB_TARGET_UID" \
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$DBB_TARGET_UID/bus" \
    DISPLAY="${DISPLAY:-:0}" \
    WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-wayland-0}" \
    ${XAUTHORITY:+XAUTHORITY="$XAUTHORITY"} \
    "$DBB_REAL_XDG_OPEN" "$@"
DBBEOF

    $sudo chmod +x "$DBB_BRIDGE_DIR/xdg-open" 2>/dev/null || true
    return 0
}
