#!/bin/bash
# Full-installation order (caller: install_item_runner.sh get_installation_scripts); Linux twin of
# Windows win_common/InstallerScriptsList.ps1 $InstallerScripts. Small essentials first, the largest
# downloads last; each entry only depends on entries above it. Script names are install_shells/*.sh
# basenames; a numbered script missing here still runs, after this list, in numeric order.

declare -a INSTALL_ORDER=(
    # 1. System base and basic libraries (7-Zip, Git, FFmpeg)
    "1_stop_cloud_monitors"
    "3_setting_base"
    "5_system_maintenance"
    "9_fix_dns"
    "23_setup_ssh_remote"
    "10_install_chinese_wubi"
    "27_install_git_ssh"
    "7_project_validator"
    "69_install_p7zip"
    "115_install_ffmpeg"
    "87_install_shama"
    # 2. Programming base: Python, Node, PHP/FrankenPHP/nginx, databases, other runtimes
    "11_cuda_nvidia_prereq"
    "13_install_default_python"
    "14_install_python310"
    "15_install_default_python_prereq_packages"
    "19_install_default_pipx"
    "21_install_default_poetry"
    "25_install_uv"
    "119_install_launcher"
    "121_install_document_parsing"
    "123_install_dictionaries"
    "17_install_node_toolchain_26"
    "37_ensure_pnpm_packages"
    "39_ensure_npmrc"
    "197_install_frontend_packages"
    "55_install_puppeteer_plugins"
    "63_install_ittools_binaries"
    "93_install_php"
    "33_install_nginx"
    "35_install_certbot"
    "75_install_postgresql"
    "85_install_mysql"
    "73_install_redis"
    "71_ensure_dragonfly_intelligent"
    "57_install_dotnet"
    "91_install_golang"
    "92_install_java"
    "65_install_ruby"
    "67_install_rust"
    "101_core_node_finish"
    "159_install_gitea"
    # 3. AI tools: one script installs every AI CLI (claude/codex/gemini/...)
    "99_install_ai_tools"
    # 4. Mesh VPN (tailscale/headscale) and network, then the services that publish on it
    "97_install_tailscale"
    "98_install_headscale_server"
    "113_natgateway"
    "175_laravel_main_start"
    "176_laravel_ui_service"
    "191_install_octane_watcher_daemon"
    "189_install_pycore_http_service"
    # 5. Chrome, VS Code (155 also refreshes Cursor/Antigravity) and the desktop applications
    "41_install_browsers"
    "155_install_ides"
    "103_install_code_server"
    "153_install_desktop_applications"
    "167_install_wechat"
    "161_install_rustdesk_client_1.4.4"
    "169_install_rustdesk_server_1.1.14"
    "163_setup_gnome_rdp"
    "195_install_remmina"
    "193_install_window_launcher_shortcut"
    "154_repair_desktop_icons"
    # 6. Large development software (Android, Flutter), smaller first
    "149_install_device_tools"
    "59_install_flutter"
    "61_install_android_studio"
    "187_install_android_sdk"
    # 7. Docker
    "79_install_docker"
    "83_docker-compose-finish"
    # 8. AI models, smallest download first
    "29_install_edge_tts"
    "125_install_ocr"
    "31_install_tts_offline"
    "129_install_vosk"
    "151_install_faster_whisper"
    "127_install_whisper"
    "145_install_kokoro"
    "139_install_melotts"
    "131_install_chattts"
    "135_install_f5tts"
    "111_install_nllb200"
    "117_install_ollama"
    "133_install_cosyvoice"
    "137_install_gptsovits"
    "143_install_fishspeech"
    "147_install_voxcpm2"
    "141_install_bark"
    "181_install_parler"
    "183_install_qwen3tts"
    "109_install_qwen25"
    "107_install_deepseek_ocr"
    "105_install_deepseek"
    # Final consistency check
    "999_check_circular_symlinks"
)
