<Project>
  <PropertyGroup>
    <AssemblyName>DotCore.UITheme</AssemblyName>
    <IntermediateOutputPath>E:\_win10_dev\cache\dotnet-artifacts\d3d4tester\obj\DotCore.UITheme\debug\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>E:\_win10_dev\cache\dotnet-artifacts\d3d4tester\obj\DotCore.UITheme\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>E:\_win10_dev\cache\dotnet-artifacts\d3d4tester\obj\DotCore.UITheme\</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>DotCore.UITheme</_TargetAssemblyProjectName>
    <RootNamespace>DotCore.UITheme</RootNamespace>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <RootNamespace>DotCore.UITheme</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\Accessibility.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\Microsoft.CSharp.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\Microsoft.VisualBasic.Core.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\Microsoft.VisualBasic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\Microsoft.Win32.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\Microsoft.Win32.Registry.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\Microsoft.Win32.Registry.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\Microsoft.Win32.SystemEvents.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\mscorlib.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\netstandard.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationCore.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationFramework.Aero.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationFramework.Aero2.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationFramework.AeroLite.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationFramework.Classic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationFramework.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationFramework.Luna.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationFramework.Royale.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\PresentationUI.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\ReachFramework.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\System.AppContext.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\8.0.31\ref\net8.0\System.Buffers.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.31\ref\net8.0\System.CodeDom.dll" />
    <ReferencePath Include="