<?php

namespace App\Http\Controllers;

use App\Models\InviteCode;
use App\Models\User;
use App\Support\InstallationAccessCode;
use App\Traits\ApiResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class InviteCodeController extends Controller
{
    use ApiResponse;

    public function listPublic(Request $request): JsonResponse
    {
        $codes = InviteCode::publicCodes(10);

        return $this->success($codes, __('api.messages.public_invite_codes_retrieved_successfully'));
    }

    public function validate(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'code' => 'required|string',
        ]);

        $code = InviteCode::findByCode($validated['code']);
        if (!$code) {
            return $this->error(__('api.messages.invalid_invite_code'), 400);
        }

        $canBeUsed = $code->canBeUsed();
        $data = $canBeUsed ? [
            'type' => $code->type,
            'role_level' => $code->getRoleLevel(),
            'role_name' => $code->getRoleName(),
        ] : null;

        return $this->success([
            'valid' => $canBeUsed,
            'data' => $data,
        ], $canBeUsed ? 'Valid invite code' : 'Invite code is expired or already used');
    }

    /**
     * Redeem the single super-admin code generated by scripts/start.sh or start.ps1.
     */
    public function redeemSuperCode(Request $request): JsonResponse
    {
        $user = $request->user();
        if (!$user) {
            return $this->unauthorized();
        }

        $validated = $request->validate([
            'code' => 'required|string|max:255',
        ]);

        $codeValue = trim($validated['code']);
        $canonicalAccessCode = trim((string) InstallationAccessCode::value());
        if ($canonicalAccessCode === '' || !hash_equals($canonicalAccessCode, $codeValue)) {
            return $this->error(__('api.messages.invalid_super_admin_code'), 400);
        }

        $userId = (int) $user->id;
        if ($user->isSuperAdmin()) {
            return $this->success([
                'user' => $this->superAdminUserPayload($user),
            ], __('api.messages.user_already_has_super_admin_access'));
        }

        $fresh = User::grantSuperAdmin($userId);
        if (!$fresh) {
            return $this->error(__('api.messages.user_not_found_after_role_update'), 500);
        }

        return $this->success([
            'user' => $this->superAdminUserPayload($fresh),
        ], __('api.messages.super_admin_access_granted'));
    }

    private function superAdminUserPayload(User $user): array
    {
        return [
            'id' => $user->id,
            'username' => $user->username,
            'nickname' => $user->nickname,
            'name' => $user->name,
            'email' => $user->email,
            'avatar' => $user->avatar,
            'bio' => $user->bio,
            'location' => $user->location,
            'rolelevel' => (int) ($user->rolelevel ?? 0),
            'role_level' => (int) ($user->rolelevel ?? 0),
            'rolename' => $user->rolename,
            'role_name' => $user->rolename,
        ];
    }
}
