#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
WordNew brand-icon generator
=============================

PURPOSE
    Take the single LARGEST source app icon from the flutter_bloom app_qy icon
    set and turn it into the full set of web-ready brand assets used by the
    /wordnew sub-app (pycore UI), at multiple sizes, so one source of truth
    drives the header mark, the welcome/onboarding splash and the About card.

SOURCE
    <repo>/poly_apps/flutter_bloom/assets/apps/app_qy/icons/
    The largest icon is auto-selected by (pixel area, then file size), skipping
    *.backup.* and the tiny notification_icon; ties prefer a file named "logo".
    The chosen file is copied here verbatim as `wordnew-logo-source.png` for
    provenance.

OUTPUTS (written next to this script, in apps/wordnew/assets/)
    - wordnew-logo-source.png          the unmodified largest source icon
    - wordnew-logo-<n>.png             square PNGs at n = 16,32,48,64,128,256,512
    - wordnew-logo.ico                 multi-resolution Windows icon (16..256)
    - ../WfNewBrandData.ts             TS module exposing Vite-managed asset URLs
                                       for the 64/128 PNGs used by the UI.

RE-RUN
    python generate_wordnew_brand.py
    Re-running is idempotent: it overwrites the generated assets in place.

DEPENDENCIES
    Pillow (PIL). Everything else is Python standard library.
"""

import os
import sys
import shutil
from pathlib import Path

from PIL import Image

# --- paths ----------------------------------------------------------------- #
ASSETS_DIR = Path(__file__).resolve().parent          # apps/wordnew/assets
WORDNEW_DIR = ASSETS_DIR.parent                        # apps/wordnew
REPO_ROOT = ASSETS_DIR.parents[4]                      # core_node
SOURCE_ICONS_DIR = REPO_ROOT / "poly_apps" / "flutter_bloom" / "assets" / "apps" / "app_qy" / "icons"

# PNG sizes written to disk (multiple-size versions kept on disk).
PNG_SIZES = [16, 32, 48, 64, 128, 256, 512]
# Sizes packed into the .ico container.
ICO_SIZES = [16, 32, 48, 64, 128, 256]

BRAND_DATA_TS = WORDNEW_DIR / "WfNewBrandData.ts"


def pick_largest_source() -> Path:
    """Pick the largest usable source icon (area, then bytes; prefer 'logo')."""
    if not SOURCE_ICONS_DIR.is_dir():
        raise SystemExit(f"Source icon directory not found: {SOURCE_ICONS_DIR}")

    best = None  # (area, bytes, prefers_logo, path)
    for name in os.listdir(SOURCE_ICONS_DIR):
        lower = name.lower()
        if not lower.endswith(".png"):
            continue
        if ".backup." in lower or "notification" in lower:
            continue
        path = SOURCE_ICONS_DIR / name
        try:
            with Image.open(path) as im:
                area = im.size[0] * im.size[1]
        except Exception:
            continue
        key = (area, path.stat().st_size, 1 if "logo" in lower else 0)
        if best is None or key > best[0]:
            best = (key, path)
    if best is None:
        raise SystemExit(f"No usable .png icons found in {SOURCE_ICONS_DIR}")
    return best[1]


def main() -> int:
    src = pick_largest_source()
    with Image.open(src) as im:
        print(f"[brand] source : {src}  ({im.size[0]}x{im.size[1]}, {im.mode})")
        base = im.convert("RGBA")

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    # 1) provenance copy of the chosen source
    shutil.copyfile(src, ASSETS_DIR / "wordnew-logo-source.png")

    # 2) multi-size PNGs (high-quality LANCZOS downscale)
    rendered = {}
    for size in PNG_SIZES:
        img = base.resize((size, size), Image.LANCZOS)
        out = ASSETS_DIR / f"wordnew-logo-{size}.png"
        img.save(out, format="PNG", optimize=True)
        rendered[size] = out
        print(f"[brand] png    : {out.name}  ({size}x{size}, {out.stat().st_size}B)")

    # 3) multi-resolution .ico
    ico_path = ASSETS_DIR / "wordnew-logo.ico"
    base.save(ico_path, format="ICO", sizes=[(s, s) for s in ICO_SIZES])
    print(f"[brand] ico    : {ico_path.name}  sizes={ICO_SIZES}  ({ico_path.stat().st_size}B)")

    # 4) TS asset module for the React app
    lines = [
        "/* AUTO-GENERATED by apps/wordnew/assets/generate_wordnew_brand.py - DO NOT EDIT BY HAND.",
        " * Vite owns the emitted asset URLs so browsers and extensions never parse a large",
        " * inline data URI. Re-run the script to refresh the PNG assets. */",
        "",
        "import wordNewLogo64 from './assets/wordnew-logo-64.png';",
        "import wordNewLogo128 from './assets/wordnew-logo-128.png';",
        "",
        "export const WORDNEW_LOGO_64 = wordNewLogo64;",
        "export const WORDNEW_LOGO_128 = wordNewLogo128;",
    ]
    lines.append("")
    BRAND_DATA_TS.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"[brand] ts     : {BRAND_DATA_TS.name}  (Vite asset imports)  "
          f"({BRAND_DATA_TS.stat().st_size}B)")

    print("[brand] done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
