// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

/// English localization for AChat App
class AChatLocalizationEN {
  static const Map<String, String> values = {
    // App Name and Slogans
    'achat_app_name': 'AChat',
    'achat_app_description': 'AI Chat Application',
    'achat_slogan_words': 'Words are not barriers',
    'achat_slogan_eyes': 'They are your eyes to see the world',
    'achat_lets_start': "Let's start",

    // Home Screen
    'achat_home_title': 'AChat Home',
    'achat_welcome_title': 'Welcome to AChat',
    'achat_welcome_description': 'Connect, communicate, and collaborate with ease',
    'achat_quick_actions': 'Quick Actions',
    'achat_start_chat': 'Start Chat',
    'achat_notification_settings': 'Notifications',

    // Advertisement Popup
    'achat_advertisement_title': 'Special Offer!',
    'achat_advertisement_subtitle': 'Discover amazing features and exclusive offers!',
    'achat_advertisement_description': 'Upgrade your experience with premium features and unlock new possibilities.',
    'achat_advertisement_button': 'Get Started',
    'achat_advertisement_image_placeholder': 'Advertisement Image',
    'achat_advertisement_click_to_close': 'Click to close',

    // Advertisement Announcements
    'achat_advertisement_announcements_title': 'Latest Announcements',
    'achat_advertisement_announcement_1_title': '🎉 New Features Available',
    'achat_advertisement_announcement_1_content': 'Enhanced chat experience with voice messages and file sharing',
    'achat_advertisement_announcement_2_title': '🔒 Security Update',
    'achat_advertisement_announcement_2_content': 'End-to-end encryption now available for all conversations',
    'achat_advertisement_announcement_3_title': '📱 Mobile App Update',
    'achat_advertisement_announcement_3_content': 'Improved performance and bug fixes in version 2.1.0',

    // Common
    'achat_home': 'Home',
    'achat_next': 'Next',
    'achat_skip': 'Skip',
    'achat_cancel': 'Cancel',
    'achat_success': 'Success',
    'achat_error': 'Error',
    'achat_loading': 'Loading...',
    'achat_see_all': 'See All',
    'achat_save': 'Save',
    'achat_delete': 'Delete',
    'achat_edit': 'Edit',
    'achat_back': 'Back',
    'achat_previous': 'Previous',
    'achat_close': 'Close',
    'achat_ok': 'OK',
    'achat_yes': 'Yes',
    'achat_no': 'No',
    'achat_confirm': 'Confirm',

    // Language Selection
    'achat_language': 'Language',
    'achat_language_english': 'English',
    'achat_language_chinese': '中文',
    'achat_language_select': 'Select Language',
    'achat_language_current': 'Current Language',

    // Auth
    'achat_signup_for_free': 'Sign up for free',
    'achat_sign_in_account': 'Sign in to your account',
    'achat_email': 'Email',
    'achat_password': 'Password',
    'achat_sign_in': 'Sign In',
    'achat_sign_up': 'Sign Up',
    'achat_continue': 'Continue',
    'achat_continue_with': 'Or continue with',
    'achat_forgot_the_password': 'Forgot the password?',
    'achat_forgot_password': 'Forgot Password',
    'achat_remember_me': 'Remember me',
    'achat_do_not_have_account': 'Don\'t have an account?',
    'achat_already_have_account': 'Already have an account?',
    'achat_email_hint': 'Enter your email',
    'achat_password_hint': 'Enter your password',
    'achat_username': 'Username',
    'achat_please_enter_username': 'Please enter your username',
    'achat_please_enter_password': 'Please enter your password',
    'achat_login_failed': 'Login failed. Please try again.',
    'achat_connection_error': 'An error occurred. Please check your connection and try again.',

    // Settings
    'achat_settings': 'Settings',
    'achat_common_settings': 'Common Settings',
    'achat_dark_mode': 'Dark Mode',
    'achat_notifications': 'Notifications',
    'achat_privacy_security': 'Privacy & Security',
    'achat_help_support': 'Help & Support',
    'achat_about': 'About',
    'achat_account_settings': 'Account Settings',
    'achat_theme': 'Theme',
    'achat_light': 'Light',
    'achat_dark': 'Dark',
    'achat_system': 'System',
    'achat_profile': 'Profile',
    'achat_notification': 'Notification',
    'achat_security': 'Security',
    'achat_help': 'Help',
    'achat_invite_friends': 'Invite Friends',
    'achat_logout': 'Logout',
    'achat_logout_confirm': 'Are you sure you want to logout?',
    'achat_yes_logout': 'Yes, Logout',
    'achat_logout_success': 'You have been successfully logged out',
    'achat_logout_failed': 'Failed to logout. Please try again',

    // Search
    'achat_search': 'Search',
    'achat_enter_search_text': 'Enter search text',
    'achat_search_placeholder': 'Search for anything',
    'achat_search_hint': 'Search chats...',
    'achat_clear': 'Clear',

    // Social
    'achat_social_title': 'Social',
    'achat_social_facebook': 'Continue with Facebook',
    'achat_social_google': 'Continue with Google',
    'achat_social_apple': 'Continue with Apple',

    // Validation
    'achat_validation_email_required': 'Email is required',
    'achat_validation_email_invalid': 'Please enter a valid email',
    'achat_validation_password_required': 'Password is required',
    'achat_validation_password_length': 'Password must be at least 8 characters',

    // Verify
    'achat_verify_title': 'Verify Your Account',
    'achat_verify_subtitle': 'We\'ve sent a code to your email',
    'achat_verify_code': 'Verification Code',
    'achat_verify_resend': 'Resend Code',
    'achat_verify_verify': 'Verify',

    // Forgot Password
    'achat_forgot_title': 'Reset Password',
    'achat_forgot_subtitle': 'Enter your email to receive a reset link',
    'achat_forgot_send': 'Send Reset Link',

    // Login
    'achat_login_credentials_error': 'Invalid credentials or username or password',
    'achat_login_invalid_credentials': 'These credentials do not match our records.',

    // Other
    'achat_connection_to_api_server_failed': 'Connection to API server failed',

    // AI Chat Core Features
    'achat_title': 'Chat',
    'achat_search_chats': 'Search',
    'achat_manage_mode_done': 'Done',
    'achat_manage_mode_mark_read': 'All Read',
    'achat_manage_mode_delete': 'Delete',
    'achat_menu_start_chat': 'New Chat',
    'achat_menu_new_group': 'New Group',
    'achat_menu_add_friend': 'Add Friend',
    'achat_menu_scan': 'Scan',
    'achat_toast_marked_read': 'Marked {name} as read',
    'achat_toast_deleted': 'Chat with {name} deleted',
    'achat_tab_chat': 'Chat',
    'achat_tab_contacts': 'Contacts',
    'achat_tab_discover': 'Discover',
    'achat_tab_me': 'Me',

    // Add Contacts
    'achat_add_contacts_title': 'Add Contacts',
    'achat_add_contacts_search_hint': 'Search by ID/Name/Department',
    'achat_add_contacts_enterprise_code': 'My Enterprise Code',
    'achat_add_contacts_enterprise_code_desc': 'Scan QR code to add work contacts',
    'achat_add_contacts_scan': 'Scan',
    'achat_add_contacts_scan_desc': 'Scan colleague\'s enterprise code',
    'achat_add_contacts_invite': 'Invite More',
    'achat_add_contacts_invite_desc': 'Invite via: Teams, Slack, Enterprise Email, etc.',

    // Contacts
    'achat_contacts_add_contact': 'Add Contact',
    'achat_contacts_search_hint': 'Search contacts...',
    'achat_contacts_empty': 'No contacts yet',
    'achat_contacts_no_search_results': 'No contacts found',
    'achat_contacts_add_first': 'Add Your First Contact',

    // App Lock
    'achat_app_lock_title': 'Lock Code',
    'achat_app_lock_lock_code': 'Lock Code',
    'achat_app_lock_change_lock_code': 'Change Lock Code',
    'achat_app_lock_description': 'After setting up a lock code, a lock icon will appear above the chat list. Click it to lock or unlock enterprise communication. Note: If you forget your lock code, you will need to uninstall and reinstall the enterprise communication app. After reinstalling, you will lose all encrypted conversations.',

    // Chat Details
    'achat_details_input_hint': 'Send message...',
    'achat_details_send': 'Send',
    'achat_details_add_attachment': 'Add Attachment',
    'achat_details_emoji': 'Emoji',
    'achat_details_more': 'More',

    // Create Group
    'achat_create_group_title': 'Create Group',
    'achat_create_group_cancel': 'Cancel',
    'achat_create_group_next': 'Next',
    'achat_create_group_search_hint': 'Search user',
    'achat_create_group_select_tip': 'Select one or more contacts to start a group chat',

    // Chat List
    'achat_chat_list_title': 'Enterprise Communication',
    'achat_chat_list_search_hint': 'Search group/department/message',
    'achat_chat_list_announcement': 'Announcement',
    'achat_select_all': 'Select All',
    'achat_clear_selection': 'Clear Selection',
    'achat_more_options': 'More Options',
    'achat_select_mode': 'Select Mode',
    'achat_refresh': 'Refresh',
    'achat_mark_read': 'Mark as Read',
    'achat_confirm_delete': 'Confirm Delete',
    'achat_delete_chats_message': 'Are you sure you want to delete the selected chats? This action cannot be undone.',

    // Chat List Alt
    

    // New Chat
    'achat_new_chat_title': 'New Chat',
    'achat_new_chat_cancel': 'Cancel',
    'achat_new_chat_search_hint': 'Search user',
    'achat_new_chat_last_online': 'Last online at {date}',

    // Notification Settings
    'achat_notification_title': 'Notification',
    'achat_notification_section_general': 'Message Notification',
    'achat_notification_section_group': 'Group Message Notification',
    'achat_notification_section_channel': 'Channel Notification',
    'achat_notification_section_app': 'In-app Notification',
    'achat_notification_section_setting': 'Notification Settings',
    'achat_notification_section_unread': 'Unread Message Settings',
    'achat_notification_section_worktime': 'Work Time Settings',
    'achat_notification_section_other': 'Other Settings',
    'achat_notification_show': 'Show Notification',
    'achat_notification_show_desc': 'Show message notifications in notification center',
    'achat_notification_preview': 'Message Preview',
    'achat_notification_preview_desc': 'Show message content in notification center',
    'achat_notification_banner': 'Banner Notification',
    'achat_notification_banner_desc': 'Show notification banner on screen',
    'achat_notification_sound': 'Notification Sound',
    'achat_notification_sound_value': 'Work Reminder',
    'achat_notification_group_important': 'Important Group Notification',
    'achat_notification_group_important_desc': 'Prioritize important group message reminders',
    'achat_notification_group_atme': '@Me Message',
    'achat_notification_group_atme_desc': 'Special reminder when someone @me',
    'achat_notification_channel_project': 'Project Update Reminder',
    'achat_notification_channel_project_desc': 'Receive project channel update notifications',
    'achat_notification_channel_task': 'Task Deadline Reminder',
    'achat_notification_channel_task_desc': 'Remind 2 days before task deadline',
    'achat_notification_app_sound': 'In-app Play Reminder Sound',
    'achat_notification_app_sound_desc': 'Use in-app play reminder sound',
    'achat_notification_app_preview': 'In-app Message Preview',
    'achat_notification_app_preview_desc': 'Show message preview in app',
    'achat_notification_unread_include_closed': 'Include Closed Conversations',
    'achat_notification_unread_include_closed_desc': 'If off, show unread conversation count instead of unread message count',
    'achat_notification_unread_by_message': 'Count Unread by Message',
    'achat_notification_unread_by_message_desc': 'If off, show unread conversation count instead of unread message count',
    'achat_notification_worktime_notify': 'Work Time Notification',
    'achat_notification_worktime_notify_desc': 'Receive notifications only during work time',
    'achat_notification_worktime_range': 'Work Time Range',
    'achat_notification_other_new_contact': 'New Contact Joined',
    'achat_notification_other_new_contact_desc': 'Receive push notification when new contact joins',
    'achat_notification_other_priority': 'Priority Message',
    'achat_notification_other_priority_desc': 'Messages from important contacts will be prioritized',
    'achat_notification_footer': 'Note: Notification settings affect the timeliness of your work messages. It is recommended to keep them on. System notifications and some important messages cannot be turned off. Please ensure notification permissions are enabled in system settings.',

    // Discover
    'achat_discover_popular': 'Popular',
    'achat_discover_popular_subtitle': 'Trending features and content',
    'achat_discover_moments_coming_soon': 'Moments feature coming soon! Share your life moments with friends.',
    'achat_discover_channels_coming_soon': 'Channels feature coming soon! Join interesting channels and communities.',
    'achat_discover_games_coming_soon': 'Games feature coming soon! Fun games to play with friends.',
    'achat_discover_mini_programs_coming_soon': 'Mini Programs feature coming soon! Useful tools and applications.',
    'achat_discover_more_coming': 'More features coming soon',
    'achat_discover_stay_tuned': 'Stay tuned for updates',
    'achat_discover_error_title': 'Failed to load content',
    'achat_discover_retry': 'Retry',
    'achat_discover_got_it': 'Got it',
    'achat_discover_search': 'Search',
    'achat_discover_search_title': 'Search Discover',
    'achat_discover_search_coming_soon': 'Search functionality coming soon! You will be able to search for features, content, and more.',

    // Privacy & Security
    'achat_privacy_title': 'Privacy & Security Settings',
    'achat_privacy_section_account': 'Account Protection',
    'achat_privacy_account_protect': 'Account Protection',
    'achat_privacy_account_protect_desc': 'Enable to enhance account security and prevent hacking',
    'achat_privacy_section_message': 'Message Security',
    'achat_privacy_message_encrypt': 'Message Encryption',
    'achat_privacy_message_encrypt_desc': 'Enable for end-to-end encryption of messages',
    'achat_privacy_section_add_method': 'Add Method',
    'achat_privacy_allow_add_by_phone': 'Allow add by phone number',
    'achat_privacy_allow_add_by_phone_desc': 'If off, others cannot add you by phone number',
    'achat_privacy_allow_add_by_id': 'Allow add by ID',
    'achat_privacy_allow_add_by_id_desc': 'If off, others cannot add you by ID',
    'achat_privacy_section_manage': 'Manage',
    'achat_privacy_blacklist': 'Blacklist Management',
    'achat_privacy_privacy_policy': 'Privacy Policy',
    'achat_privacy_security_tips': 'Security Tips',
    'achat_privacy_section_security': 'Security',
    'achat_privacy_blocked_users': 'Blocked Users',
    'achat_privacy_lock_code': 'Lock Code',
    'achat_privacy_security_tip': 'Control your sessions on other devices.',
    'achat_privacy_section_privacy': 'Privacy',
    'achat_privacy_phone': 'Phone Number',
    'achat_privacy_online_status': 'Online Status',
    'achat_privacy_invite_control': 'Invite Permission Control',
    'achat_privacy_privacy_tip': 'Control who can invite you to groups or channels.',
    'achat_privacy_section_advanced': 'Advanced',
    'achat_privacy_delete_account': 'Delete my account if offline for',
    'achat_privacy_data_usage': 'Data Usage Settings',
    'achat_privacy_enabled': 'Enabled',
    'achat_privacy_disabled': 'Disabled',

    // Additional privacy keys for refactored code
    'achat_privacy_phone_visibility_enabled': 'Phone visibility enabled',
    'achat_privacy_phone_visibility_disabled': 'Phone visibility disabled',
    'achat_privacy_online_status_enabled': 'Online status enabled',
    'achat_privacy_online_status_disabled': 'Online status disabled',
    'achat_privacy_invite_control_enabled': 'Invite control enabled',
    'achat_privacy_invite_control_disabled': 'Invite control disabled',
    'achat_privacy_delete_account_enabled': 'Delete account enabled',
    'achat_privacy_delete_account_disabled': 'Delete account disabled',
    'achat_privacy_message_encryption_enabled': 'Message encryption enabled',
    'achat_privacy_message_encryption_disabled': 'Message encryption disabled',
    'achat_privacy_account_protection_enabled': 'Account protection enabled',
    'achat_privacy_account_protection_disabled': 'Account protection disabled',
    'achat_privacy_allow_add_by_phone_enabled': 'Allow add by phone enabled',
    'achat_privacy_allow_add_by_phone_disabled': 'Allow add by phone disabled',
    'achat_privacy_allow_add_by_id_enabled': 'Allow add by ID enabled',
    'achat_privacy_allow_add_by_id_disabled': 'Allow add by ID disabled',
    'achat_privacy_blocked_users_coming_soon': 'Blocked users feature coming soon',
    'achat_privacy_data_usage_coming_soon': 'Data usage feature coming soon',
    'achat_privacy_policy_coming_soon': 'Privacy policy feature coming soon',
    'achat_privacy_security_tips_coming_soon': 'Security tips feature coming soon',
    'achat_privacy_load_error': 'Failed to load privacy settings',

    // Profile (Personal Center)
    'achat_profile_name': 'Zhang Manager',
    'achat_profile_id': 'ID: PM8023',
    'achat_profile_complete_tip': 'Complete your profile to help colleagues know you better',
    'achat_profile_privacy': 'Privacy & Security',
    'achat_profile_notification': 'Notification Sound',
    'achat_profile_language': 'Language Settings',
    'achat_profile_version': 'Enterprise IM Android Client v1.0.5',

    // Proxy Settings
    'achat_proxy_title': 'Proxy Settings',
    'achat_proxy_use_proxy': 'Use Proxy',
    'achat_proxy_use_proxy_desc': 'Enable proxy server for network connections',
    'achat_proxy_call_proxy': 'Enable Proxy for Calls',
    'achat_proxy_call_proxy_desc': 'Use proxy server for voice and video calls. May reduce call quality.',
    'achat_proxy_connection': 'Proxy Connection',
    'achat_proxy_connection_desc': 'Configure proxy connection settings',
    'achat_proxy_add': 'Add Proxy Server',
    'achat_proxy_add_desc': 'Add a new proxy server configuration',

    // QR Profile
    'achat_qr_profile_title': 'QR Profile',
    'achat_qr_profile_name': 'Zhang Ming',
    'achat_qr_profile_title_text': 'Technical Director | R&D Center',
    'achat_qr_profile_verified': 'Enterprise Verified User',
    'achat_qr_profile_qr_title': 'My Enterprise QR',
    'achat_qr_profile_qr_placeholder': 'QR Code',
    'achat_qr_profile_qr_tip': 'Scan the QR code above to add me as a work contact',
    'achat_qr_profile_save': 'Save QR Code',
    'achat_qr_profile_share': 'Share QR Code',
    'achat_qr_profile_retry': 'Retry',
    'achat_qr_profile_save_success': 'QR code saved successfully',
    'achat_qr_profile_save_error': 'Failed to save QR code',
    'achat_qr_profile_share_success': 'QR code shared successfully',
    'achat_qr_profile_share_error': 'Failed to share QR code',
    'achat_qr_profile_update_success': 'Profile updated successfully',
    'achat_qr_profile_update_error': 'Failed to update profile',
    'achat_qr_profile_edit_title': 'Edit Profile',
    'achat_qr_profile_edit_name': 'Name',
    'achat_qr_profile_edit_name_hint': 'Enter your name',
    'achat_qr_profile_edit_title_field': 'Title',
    'achat_qr_profile_edit_title_hint': 'Enter your title',
    'achat_qr_profile_edit_avatar': 'Avatar Text',
    'achat_qr_profile_edit_avatar_hint': 'Enter avatar text (1-2 characters)',
    'achat_qr_profile_edit_verified': 'Verified User',
    'achat_qr_profile_edit_cancel': 'Cancel',
    'achat_qr_profile_edit_save': 'Save',

    // AI Chat Specific Features
    'achat_ai_assistant': 'AI Assistant',
    'achat_ai_chat_history': 'Chat History',
    'achat_ai_clear_history': 'Clear History',
    'achat_ai_export_chat': 'Export Chat',
    'achat_ai_voice_input': 'Voice Input',
    'achat_ai_image_recognition': 'Image Recognition',
    'achat_ai_translation': 'Translation',
    'achat_ai_smart_reply': 'Smart Reply',
    'achat_ai_context_aware': 'Context Aware',
    'achat_ai_learning_mode': 'Learning Mode',
    'achat_ai_personality': 'AI Personality',
    'achat_ai_response_style': 'Response Style',
    'achat_ai_language_model': 'Language Model',
    'achat_ai_temperature': 'Creativity Level',
    'achat_ai_max_tokens': 'Response Length',
    'achat_ai_system_prompt': 'System Prompt',
    'achat_ai_custom_instructions': 'Custom Instructions',

    // Chat Screen
    'achat_clear_chat': 'Clear Chat',
    'achat_chat_cleared': 'Chat cleared',
    'achat_export_chat': 'Export Chat',
    'achat_import_chat': 'Import Chat',
    'achat_search_messages': 'Search Messages',
    'achat_chat_info': 'Chat Info',
    'achat_search_term': 'Enter search term...',
    'achat_search_results': 'Search Results for "{0}"',
    'achat_no_messages_found': 'No messages found',
    'achat_chat_information': 'Chat Information',
    'achat_total_messages': 'Total Messages: {0}',
    'achat_unread_messages': 'Unread Messages: {0}',
    'achat_chat_status': 'Chat Status: {0}',
    'achat_last_message': 'Last Message: {0}',
    'achat_empty': 'Empty',
    'achat_active': 'Active',
    'achat_clear_chat_confirm': 'Are you sure you want to clear all messages? This action cannot be undone.',
    'achat_exported_messages': 'Exported {0} messages',
    'achat_import_not_implemented': 'Import functionality not implemented',
    'achat_you': 'You',
    'achat_ai': 'AI',

    // Navigation
    'achat_nav_chats': 'Chats',
    'achat_nav_contacts': 'Contacts',
    'achat_nav_discover': 'Discover',
    'achat_nav_profile': 'Profile',

    // Group Chat
    'achat_group_chat_default_name': 'Mobile Development Group',
    'achat_group_chat_default_members': 'Zhang Manager, Li Designer, Wang Engineer, Zhao Product Manager',
    'achat_group_chat_search_tooltip': 'Search messages',
    'achat_group_chat_more_tooltip': 'More options',
    'achat_group_chat_load_error': 'Failed to load group chat messages',
    'achat_group_chat_search_coming_soon': 'Search functionality coming soon',
    'achat_group_chat_more_coming_soon': 'More options coming soon',

    // Chat Messages
    'achat_chat_me': 'Me',
    'achat_chat_unknown_file': 'Unknown File',
    'achat_chat_image_preview': 'Image Preview',
    'achat_chat_download_started': 'Download started',
    'achat_chat_image_error': 'Failed to send image',
    'achat_chat_file_error': 'Failed to send file',
    'achat_chat_voice_message': 'Voice Message',
    'achat_chat_voice_error': 'Failed to send voice message',
    'achat_chat_add_attachment': 'Add attachment',
    'achat_chat_input_hint': 'Type a message...',
    'achat_chat_emoji': 'Emoji',
    'achat_chat_send': 'Send',
    'achat_chat_attachment_options': 'Attachment Options',
    'achat_chat_image': 'Image',
    'achat_chat_image_subtitle': 'Send photo from gallery',
    'achat_chat_file': 'File',
    'achat_chat_file_subtitle': 'Send document or file',
    'achat_chat_voice': 'Voice',
    'achat_chat_voice_subtitle': 'Record voice message',
    'achat_chat_emoji_coming_soon': 'Emoji picker coming soon',
  };
}
