// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

/// Chinese localization for AChat App
class AChatLocalizationZH {
  static const Map<String, String> values = {
    // App Name and Slogans
    'achat_app_name': 'AChat',
    'achat_app_description': 'AI聊天应用',
    'achat_slogan_words': '单词不是障碍',
    'achat_slogan_eyes': '是你看世界的眼睛',
    'achat_lets_start': '开始使用',

    // Home Screen
    'achat_home_title': 'AChat 首页',
    'achat_welcome_title': '欢迎使用 AChat',
    'achat_welcome_description': '轻松连接、沟通和协作',
    'achat_quick_actions': '快捷操作',
    'achat_start_chat': '开始聊天',
    'achat_notification_settings': '通知设置',

    // Advertisement Popup
    'achat_advertisement_title': '特别优惠！',
    'achat_advertisement_subtitle': '持续30分动馨直播内容:美女主播自慰、互动！',
    'achat_advertisement_description': '升级您的体验，享受高级功能，解锁新的可能性。',
    'achat_advertisement_button': '立即开始',
    'achat_advertisement_image_placeholder': '广告图片',
    'achat_advertisement_click_to_close': '点击关闭',

    // Advertisement Announcements
    'achat_advertisement_announcements_title': '[Notice]',
    'achat_advertisement_announcement_1_title': '🎉 セックスクラプ平台免费福利直播大派送!!!',
    'achat_advertisement_announcement_1_content': '直播时间:每天中午13:00-凌晨01:00',
    'achat_advertisement_announcement_2_title': '每小时直播:整点开始，持续30分动馨直播内容:美女主播自慰、互动、男女双啪等待你来探索·',
    'achat_advertisement_announcement_2_content': '每场直播的时间安排:。13:00-13:30',
    'achat_advertisement_announcement_3_title': '📱 端到端加秘',
    'achat_advertisement_announcement_3_content': '私密性最好的约炮APP',

    // Common
    'achat_home': '首页',
    'achat_next': '下一步',
    'achat_skip': '跳过',
    'achat_cancel': '取消',
    'achat_success': '成功',
    'achat_error': '错误',
    'achat_loading': '加载中...',
    'achat_see_all': '查看全部',
    'achat_save': '保存',
    'achat_delete': '删除',
    'achat_edit': '编辑',
    'achat_back': '返回',
    'achat_previous': '上一步',
    'achat_close': '关闭',
    'achat_ok': '确定',
    'achat_yes': '是',
    'achat_no': '否',
    'achat_confirm': '确认',

    // Language Selection
    'achat_language': '语言',
    'achat_language_english': 'English',
    'achat_language_chinese': '中文',
    'achat_language_select': '选择语言',
    'achat_language_current': '当前语言',

    // Auth
    'achat_signup_for_free': '免费注册',
    'achat_sign_in_account': '登录您的账号',
    'achat_email': '邮箱',
    'achat_password': '密码',
    'achat_sign_in': '登录',
    'achat_sign_up': '注册',
    'achat_continue': '继续',
    'achat_continue_with': '或使用以下方式继续',
    'achat_forgot_the_password': '忘记密码？',
    'achat_forgot_password': '忘记密码',
    'achat_remember_me': '记住我',
    'achat_do_not_have_account': '还没有账号？',
    'achat_already_have_account': '已有账号？',
    'achat_email_hint': '请输入您的邮箱',
    'achat_password_hint': '请输入您的密码',
    'achat_username': '用户名',
    'achat_please_enter_username': '请输入用户名',
    'achat_please_enter_password': '请输入密码',
    'achat_login_failed': '登录失败，请重试',
    'achat_connection_error': '发生错误，请检查网络连接后重试',

    // Settings
    'achat_settings': '设置',
    'achat_common_settings': '通用设置',
    'achat_dark_mode': '深色模式',
    'achat_notifications': '通知',
    'achat_privacy_security': '隐私与安全',
    'achat_help_support': '帮助与支持',
    'achat_about': '关于',
    'achat_account_settings': '账号设置',
    'achat_theme': '主题',
    'achat_light': '浅色',
    'achat_dark': '深色',
    'achat_system': '系统',
    'achat_profile': '个人资料',
    'achat_notification': '通知',
    'achat_security': '安全',
    'achat_help': '帮助',
    'achat_invite_friends': '邀请好友',
    'achat_logout': '退出登录',
    'achat_logout_confirm': '确定要退出登录吗？',
    'achat_yes_logout': '确定退出',
    'achat_logout_success': '您已成功退出登录',
    'achat_logout_failed': '退出登录失败，请重试',

    // Search
    'achat_search': '搜索',
    'achat_enter_search_text': '输入搜索内容',
    'achat_search_placeholder': '搜索任何内容',
    'achat_search_hint': '搜索聊天...',
    'achat_clear': '清除',

    // Social
    'achat_social_title': '社交',
    'achat_social_facebook': '使用Facebook继续',
    'achat_social_google': '使用Google继续',
    'achat_social_apple': '使用Apple继续',

    // Validation
    'achat_validation_email_required': '邮箱为必填项',
    'achat_validation_email_invalid': '请输入有效的邮箱地址',
    'achat_validation_password_required': '密码为必填项',
    'achat_validation_password_length': '密码长度至少为8个字符',

    // Verify
    'achat_verify_title': '验证您的账号',
    'achat_verify_subtitle': '我们已向您的邮箱发送验证码',
    'achat_verify_code': '验证码',
    'achat_verify_resend': '重新发送验证码',
    'achat_verify_verify': '验证',

    // Forgot Password
    'achat_forgot_title': '重置密码',
    'achat_forgot_subtitle': '输入您的邮箱以接收重置链接',
    'achat_forgot_send': '发送重置链接',

    // Login
    'achat_login_credentials_error': '无效的凭据或用户名或密码',
    'achat_login_invalid_credentials': '这些凭据与我们的记录不匹配',

    // Other
    'achat_connection_to_api_server_failed': '连接API服务器失败',

    // AI Chat Core Features
    'achat_title': '聊天',
    'achat_search_chats': '搜索',
    'achat_manage_mode_done': '完成',
    'achat_manage_mode_mark_read': '全部已读',
    'achat_manage_mode_delete': '删除',
    'achat_menu_start_chat': '新建聊天',
    'achat_menu_new_group': '新建群组',
    'achat_menu_add_friend': '添加好友',
    'achat_menu_scan': '扫一扫',
    'achat_toast_marked_read': '已将{name}标记为已读',
    'achat_toast_deleted': '与{name}的聊天已删除',
    'achat_tab_chat': '聊天',
    'achat_tab_contacts': '通讯录',
    'achat_tab_discover': '发现',
    'achat_tab_me': '我',

    // Add Contacts
    'achat_add_contacts_title': '添加联系人',
    'achat_add_contacts_search_hint': '通过ID/姓名/部门搜索',
    'achat_add_contacts_enterprise_code': '我的企业码',
    'achat_add_contacts_enterprise_code_desc': '扫描二维码添加工作联系人',
    'achat_add_contacts_scan': '扫一扫',
    'achat_add_contacts_scan_desc': '扫描同事的企业码',
    'achat_add_contacts_invite': '邀请更多',
    'achat_add_contacts_invite_desc': '通过以下方式邀请：Teams、Slack、企业邮箱等',

    // Contacts
    'achat_contacts_add_contact': '添加联系人',
    'achat_contacts_search_hint': '搜索联系人...',
    'achat_contacts_empty': '暂无联系人',
    'achat_contacts_no_search_results': '未找到联系人',
    'achat_contacts_add_first': '添加您的第一个联系人',

    // App Lock
    'achat_app_lock_title': '锁定密码',
    'achat_app_lock_lock_code': '锁定密码',
    'achat_app_lock_change_lock_code': '更改锁定密码',
    'achat_app_lock_description': '设置锁定密码后，聊天列表上方会出现锁定图标。点击可锁定或解锁企业通信。注意：如果忘记锁定密码，需要卸载并重新安装企业通信应用。重新安装后，您将丢失所有加密对话。',

    // Chat Details
    'achat_details_input_hint': '发送消息...',
    'achat_details_send': '发送',
    'achat_details_add_attachment': '添加附件',
    'achat_details_emoji': '表情',
    'achat_details_more': '更多',

    // Create Group
    'achat_create_group_title': '创建群组',
    'achat_create_group_cancel': '取消',
    'achat_create_group_next': '下一步',
    'achat_create_group_search_hint': '搜索用户',
    'achat_create_group_select_tip': '选择一个或多个联系人开始群聊',

    // Chat List
    'achat_chat_list_title': '企业通信',
    'achat_chat_list_search_hint': '搜索群组/部门/消息',
    'achat_chat_list_announcement': '公告',
    'achat_select_all': '全选',
    'achat_clear_selection': '清除选择',
    'achat_more_options': '更多选项',
    'achat_select_mode': '选择模式',
    'achat_refresh': '刷新',
    'achat_mark_read': '标记为已读',
    'achat_confirm_delete': '确认删除',
    'achat_delete_chats_message': '确定要删除选中的聊天吗？此操作无法撤销。',

    // Chat List Alt
    

    // New Chat
    'achat_new_chat_title': '新建聊天',
    'achat_new_chat_cancel': '取消',
    'achat_new_chat_search_hint': '搜索用户',
    'achat_new_chat_last_online': '最后在线时间：{date}',

    // Notification Settings
    'achat_notification_title': '通知',
    'achat_notification_section_general': '消息通知',
    'achat_notification_section_group': '群消息通知',
    'achat_notification_section_channel': '频道通知',
    'achat_notification_section_app': '应用内通知',
    'achat_notification_section_setting': '通知设置',
    'achat_notification_section_unread': '未读消息设置',
    'achat_notification_section_worktime': '工作时间设置',
    'achat_notification_section_other': '其他设置',
    'achat_notification_show': '显示通知',
    'achat_notification_show_desc': '在通知中心显示消息通知',
    'achat_notification_preview': '消息预览',
    'achat_notification_preview_desc': '在通知中心显示消息内容',
    'achat_notification_banner': '横幅通知',
    'achat_notification_banner_desc': '在屏幕上显示通知横幅',
    'achat_notification_sound': '通知声音',
    'achat_notification_sound_value': '工作提醒',
    'achat_notification_group_important': '重要群组通知',
    'achat_notification_group_important_desc': '优先提醒重要群组消息',
    'achat_notification_group_atme': '@我的消息',
    'achat_notification_group_atme_desc': '有人@我时特别提醒',
    'achat_notification_channel_project': '项目更新提醒',
    'achat_notification_channel_project_desc': '接收项目频道更新通知',
    'achat_notification_channel_task': '任务截止提醒',
    'achat_notification_channel_task_desc': '任务截止前2天提醒',
    'achat_notification_app_sound': '应用内播放提醒音',
    'achat_notification_app_sound_desc': '使用应用内播放提醒音',
    'achat_notification_app_preview': '应用内消息预览',
    'achat_notification_app_preview_desc': '在应用内显示消息预览',
    'achat_notification_unread_include_closed': '包含已关闭的对话',
    'achat_notification_unread_include_closed_desc': '关闭时，显示未读对话数而不是未读消息数',
    'achat_notification_unread_by_message': '按消息计算未读',
    'achat_notification_unread_by_message_desc': '关闭时，显示未读对话数而不是未读消息数',
    'achat_notification_worktime_notify': '工作时间通知',
    'achat_notification_worktime_notify_desc': '仅在工作时间接收通知',
    'achat_notification_worktime_range': '工作时间范围',
    'achat_notification_other_new_contact': '新联系人加入',
    'achat_notification_other_new_contact_desc': '新联系人加入时接收推送通知',

    // Discover
    'achat_discover_popular': '热门',
    'achat_discover_popular_subtitle': '热门功能和内容',
    'achat_discover_moments_coming_soon': '朋友圈功能即将推出！与朋友分享您的生活瞬间。',
    'achat_discover_channels_coming_soon': '频道功能即将推出！加入有趣的频道和社区。',
    'achat_discover_games_coming_soon': '游戏功能即将推出！与朋友一起玩有趣的游戏。',
    'achat_discover_mini_programs_coming_soon': '小程序功能即将推出！实用的工具和应用程序。',
    'achat_discover_more_coming': '更多功能即将推出',
    'achat_discover_stay_tuned': '敬请期待更新',
    'achat_discover_error_title': '加载内容失败',
    'achat_discover_retry': '重试',
    'achat_discover_got_it': '知道了',
    'achat_discover_search': '搜索',
    'achat_discover_search_title': '搜索发现',
    'achat_discover_search_coming_soon': '搜索功能即将推出！您将能够搜索功能、内容等。',
    'achat_notification_other_priority': '优先消息',
    'achat_notification_other_priority_desc': '来自重要联系人的消息将被优先处理',
    'achat_notification_footer': '注意：通知设置影响您工作消息的及时性。建议保持开启。系统通知和一些重要消息无法关闭。请确保在系统设置中启用通知权限。',

    // Privacy & Security
    'achat_privacy_title': '隐私与安全设置',
    'achat_privacy_section_account': '账号保护',
    'achat_privacy_account_protect': '账号保护',
    'achat_privacy_account_protect_desc': '启用以增强账号安全性并防止被盗',
    'achat_privacy_section_message': '消息安全',
    'achat_privacy_message_encrypt': '消息加密',
    'achat_privacy_message_encrypt_desc': '启用消息端到端加密',
    'achat_privacy_section_add_method': '添加方式',
    'achat_privacy_allow_add_by_phone': '允许通过手机号添加',
    'achat_privacy_allow_add_by_phone_desc': '关闭后，其他人无法通过手机号添加您',
    'achat_privacy_allow_add_by_id': '允许通过ID添加',
    'achat_privacy_allow_add_by_id_desc': '关闭后，其他人无法通过ID添加您',
    'achat_privacy_section_manage': '管理',
    'achat_privacy_blacklist': '黑名单管理',
    'achat_privacy_privacy_policy': '隐私政策',
    'achat_privacy_security_tips': '安全提示',
    'achat_privacy_section_security': '安全',
    'achat_privacy_blocked_users': '已屏蔽用户',
    'achat_privacy_lock_code': '锁定密码',
    'achat_privacy_security_tip': '控制您在其他设备上的会话。',
    'achat_privacy_section_privacy': '隐私',
    'achat_privacy_phone': '手机号码',
    'achat_privacy_online_status': '在线状态',
    'achat_privacy_invite_control': '邀请权限控制',
    'achat_privacy_privacy_tip': '控制谁可以邀请您加入群组或频道。',
    'achat_privacy_section_advanced': '高级',
    'achat_privacy_delete_account': '离线时删除我的账号',
    'achat_privacy_data_usage': '数据使用设置',
    'achat_privacy_enabled': '已启用',
    'achat_privacy_disabled': '已禁用',

    // Additional privacy keys for refactored code
    'achat_privacy_phone_visibility_enabled': '手机号可见性已启用',
    'achat_privacy_phone_visibility_disabled': '手机号可见性已禁用',
    'achat_privacy_online_status_enabled': '在线状态已启用',
    'achat_privacy_online_status_disabled': '在线状态已禁用',
    'achat_privacy_invite_control_enabled': '邀请控制已启用',
    'achat_privacy_invite_control_disabled': '邀请控制已禁用',
    'achat_privacy_delete_account_enabled': '删除账号已启用',
    'achat_privacy_delete_account_disabled': '删除账号已禁用',
    'achat_privacy_message_encryption_enabled': '消息加密已启用',
    'achat_privacy_message_encryption_disabled': '消息加密已禁用',
    'achat_privacy_account_protection_enabled': '账号保护已启用',
    'achat_privacy_account_protection_disabled': '账号保护已禁用',
    'achat_privacy_allow_add_by_phone_enabled': '允许手机号添加已启用',
    'achat_privacy_allow_add_by_phone_disabled': '允许手机号添加已禁用',
    'achat_privacy_allow_add_by_id_enabled': '允许ID添加已启用',
    'achat_privacy_allow_add_by_id_disabled': '允许ID添加已禁用',
    'achat_privacy_blocked_users_coming_soon': '屏蔽用户功能即将推出',
    'achat_privacy_data_usage_coming_soon': '数据使用功能即将推出',
    'achat_privacy_policy_coming_soon': '隐私政策功能即将推出',
    'achat_privacy_security_tips_coming_soon': '安全提示功能即将推出',
    'achat_privacy_load_error': '加载隐私设置失败',

    // Profile (Personal Center)
    'achat_profile_name': '张经理',
    'achat_profile_id': 'ID: PM8023',
    'achat_profile_complete_tip': '完善您的资料，帮助同事更好地了解您',
    'achat_profile_privacy': '隐私与安全',
    'achat_profile_notification': '通知声音',
    'achat_profile_language': '语言设置',
    'achat_profile_version': '企业IM Android客户端 v1.0.5',

    // Proxy Settings
    'achat_proxy_title': '代理设置',
    'achat_proxy_use_proxy': '使用代理',
    'achat_proxy_use_proxy_desc': '为网络连接启用代理服务器',
    'achat_proxy_call_proxy': '为通话启用代理',
    'achat_proxy_call_proxy_desc': '为语音和视频通话使用代理服务器。可能会降低通话质量。',
    'achat_proxy_connection': '代理连接',
    'achat_proxy_connection_desc': '配置代理连接设置',
    'achat_proxy_add': '添加代理服务器',
    'achat_proxy_add_desc': '添加新的代理服务器配置',

    // QR Profile
    'achat_qr_profile_title': '二维码名片',
    'achat_qr_profile_name': '张明',
    'achat_qr_profile_title_text': '技术总监 | 研发中心',
    'achat_qr_profile_verified': '企业认证用户',
    'achat_qr_profile_qr_title': '我的企业二维码',
    'achat_qr_profile_qr_placeholder': '二维码',
    'achat_qr_profile_qr_tip': '扫描上方二维码，添加我为工作联系人',
    'achat_qr_profile_save': '保存二维码',
    'achat_qr_profile_share': '分享二维码',
    'achat_qr_profile_retry': '重试',
    'achat_qr_profile_save_success': '二维码保存成功',
    'achat_qr_profile_save_error': '二维码保存失败',
    'achat_qr_profile_share_success': '二维码分享成功',
    'achat_qr_profile_share_error': '二维码分享失败',
    'achat_qr_profile_update_success': '个人资料更新成功',
    'achat_qr_profile_update_error': '个人资料更新失败',
    'achat_qr_profile_edit_title': '编辑个人资料',
    'achat_qr_profile_edit_name': '姓名',
    'achat_qr_profile_edit_name_hint': '请输入您的姓名',
    'achat_qr_profile_edit_title_field': '职位',
    'achat_qr_profile_edit_title_hint': '请输入您的职位',
    'achat_qr_profile_edit_avatar': '头像文字',
    'achat_qr_profile_edit_avatar_hint': '请输入头像文字（1-2个字符）',
    'achat_qr_profile_edit_verified': '认证用户',
    'achat_qr_profile_edit_cancel': '取消',
    'achat_qr_profile_edit_save': '保存',

    // AI Chat Specific Features
    'achat_ai_assistant': 'AI助手',
    'achat_ai_chat_history': '聊天历史',
    'achat_ai_clear_history': '清除历史',
    'achat_ai_export_chat': '导出聊天',
    'achat_ai_voice_input': '语音输入',
    'achat_ai_image_recognition': '图像识别',
    'achat_ai_translation': '翻译',
    'achat_ai_smart_reply': '智能回复',
    'achat_ai_context_aware': '上下文感知',
    'achat_ai_learning_mode': '学习模式',
    'achat_ai_personality': 'AI个性',
    'achat_ai_response_style': '回复风格',
    'achat_ai_language_model': '语言模型',
    'achat_ai_temperature': '创造力水平',
    'achat_ai_max_tokens': '回复长度',
    'achat_ai_system_prompt': '系统提示',
    'achat_ai_custom_instructions': '自定义指令',

    // Navigation
    'achat_nav_chats': '聊天',
    'achat_nav_contacts': '联系人',
    'achat_nav_discover': '发现',
    'achat_nav_profile': '我的',

    // Group Chat
    'achat_group_chat_default_name': '移动端开发组',
    'achat_group_chat_default_members': '张经理, 李设计师, 王工程师, 赵产品经理',
    'achat_group_chat_search_tooltip': '搜索消息',
    'achat_group_chat_more_tooltip': '更多选项',
    'achat_group_chat_load_error': '加载群聊消息失败',
    'achat_group_chat_search_coming_soon': '搜索功能即将推出',
    'achat_group_chat_more_coming_soon': '更多选项即将推出',

    // Chat Messages
    'achat_chat_me': '我',
    'achat_chat_unknown_file': '未知文件',
    'achat_chat_image_preview': '图片预览',
    'achat_chat_download_started': '开始下载',
    'achat_chat_image_error': '发送图片失败',
    'achat_chat_file_error': '发送文件失败',
    'achat_chat_voice_message': '语音消息',
    'achat_chat_voice_error': '发送语音消息失败',
    'achat_chat_add_attachment': '添加附件',
    'achat_chat_input_hint': '输入消息...',
    'achat_chat_emoji': '表情',
    'achat_chat_send': '发送',
    'achat_chat_attachment_options': '附件选项',
    'achat_chat_image': '图片',
    'achat_chat_image_subtitle': '从相册发送照片',
    'achat_chat_file': '文件',
    'achat_chat_file_subtitle': '发送文档或文件',
    'achat_chat_voice': '语音',
    'achat_chat_voice_subtitle': '录制语音消息',
    'achat_chat_emoji_coming_soon': '表情选择器即将推出',
  };
}
