"""
Command Content Generator for Linux

Generates bash scripts for Linux systems.
Linux scripts do NOT handle environment variables (handled by linux_path_function.sh)
Only ensure command availability for production.

This is the Linux-specific version of CommandContentGenerator.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any


class LinuxCommandContentGenerator:
    """Generate Linux bash command scripts"""

    def __init__(self):
        self.project_root = self._get_project_root()
        self.scripts_dir = self.project_root / 'scripts'

    @staticmethod
    def _get_project_root() -> Path:
        """Get project root directory"""
        current_file = Path(__file__)
        pytools_dir = current_file.parent.parent
        scripts_dir = pytools_dir.parent
        return scripts_dir.parent

    def generate_command_content(self, config_name: str, command_prefix: str,
                                ps_command: str, file_number: int,
                                variables: List[Dict[str, Any]], file_name: str = "") -> str:
        """
        Generate Linux bash script content for AI tools

        Note: Linux scripts do NOT handle environment variables.
        Environment variables are managed by linux_path_function.sh
        This script focuses on command execution only.
        """
        header = f"""#!/bin/bash
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\\..\\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# {config_name} Global File #{file_number}
# =============================================================================
#
# Synopsis:
#     {config_name} Launch Script
#
# Description:
#     This file is automatically generated by Special Software Environment Manager
#     Contains tool startup functionality for Linux systems
#
# Notes:
#     - Tool Name: {config_name}
#     - Command Prefix: {command_prefix}
#     - Command: {ps_command}
#     - File Number: {file_number}
#     - File Name: {file_name}
#     - Generation Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
#
# Environment Variables:
#     Environment variables are managed by linux_path_function.sh
#     This script focuses on command execution only
# =============================================================================

set -e
"""

        file_name_display = ""
        if file_name:
            file_name_display = f"""
echo ""
echo "============================================================"
echo "Running: {file_name}"
echo "============================================================"
echo ""
"""

        launch_section = f"""
# =============================================================================
# Launch Tool
# =============================================================================
echo ""
echo "============================================================"
echo "Starting {config_name}..."
echo "============================================================"
echo ""

# Execute command
{ps_command}

echo ""
echo "Session ended"
echo ""
"""

        return f"{header}{file_name_display}{launch_section}"

    def generate_ssh_command_content(self, config_name: str, file_number: int,
                                    user_inputs: Dict[str, str], file_name: str = "") -> str:
        """Generate Linux SSH connection bash script"""
        ssh_connection = user_inputs.get('SSH_CONNECTION', '')
        ssh_password = user_inputs.get('SSH_PASSWORD', '')

        header = f"""#!/bin/bash
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\\..\\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# {config_name} Global File #{file_number}
# =============================================================================
#
# Synopsis:
#     SSH Connection Script
#
# Description:
#     This file is automatically generated by Special Software Environment Manager
#     Contains SSH connection setup for Linux systems
#
# Notes:
#     - Configuration: {config_name}
#     - SSH Connection: {ssh_connection}
#     - File Number: {file_number}
#     - File Name: {file_name}
#     - Generation Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# =============================================================================

set -e

SSH_CONNECTION="{ssh_connection}"
"""

        password_section = ""
        if ssh_password:
            password_section = f'SSH_PASSWORD="{ssh_password}"\n'

        file_name_display = ""
        if file_name:
            file_name_display = f"""
echo ""
echo "============================================================"
echo "Running: {file_name}"
echo "============================================================"
echo ""
"""

        connection_section = f"""
# =============================================================================
# Execute SSH Connection
# =============================================================================
echo ""
echo "============================================================"
echo "Connecting to SSH Server"
echo "============================================================"
echo ""

if [ -z "$SSH_CONNECTION" ]; then
    echo "[ERROR] SSH connection string is empty"
    exit 1
fi

echo "Executing: ssh $SSH_CONNECTION"
echo ""

if [ -n "$SSH_PASSWORD" ]; then
    if command -v sshpass &> /dev/null; then
        echo "[INFO] Using sshpass for password authentication"
        sshpass -p "$SSH_PASSWORD" ssh "$SSH_CONNECTION" "$@"
    else
        echo "[WARNING] sshpass not found, falling back to interactive password prompt"
        ssh "$SSH_CONNECTION" "$@"
    fi
else
    ssh "$SSH_CONNECTION" "$@"
fi

echo ""
echo "SSH session ended"
echo ""
"""

        return f"{header}{password_section}{file_name_display}{connection_section}"

    def write_linux_script(self, content: str, command_prefix: str, file_number: int) -> bool:
        """Write Linux script to liunxenvs directory"""
        liunxenvs_dir = self.scripts_dir / 'liunxenvs'

        if not liunxenvs_dir.exists():
            liunxenvs_dir.mkdir(parents=True, exist_ok=True)
            print(f"Created liunxenvs directory: {liunxenvs_dir}")

        file_name = f"{command_prefix}{file_number}.sh"
        target_path = liunxenvs_dir / file_name

        try:
            with open(target_path, 'w', encoding='utf-8') as f:
                f.write(content)

            # Make script executable on Linux
            import platform
            if platform.system() != 'Windows':
                import stat
                os.chmod(target_path, os.stat(target_path).st_mode | stat.S_IEXEC)

            print(f"Linux script written to: {target_path}")

            if target_path.exists():
                file_size = target_path.stat().st_size
                print(f"File verification: SUCCESS - Size: {file_size} bytes")
                return True
            else:
                print("File verification: FAILED")
                return False

        except Exception as e:
            print(f"Failed to write Linux script: {e}")
            return False
