<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use App\Services\SafeMigrationHelper;
use App\Constants\AppKeys;
use App\Providers\AppTablePrefixServiceProvider;

/**
 * Cover provenance — record WHO/HOW generated each cover (detailed processing
 * records). The assist worker (pycore) reports the image provider/model/latency
 * on /assist/submit; these columns persist that provenance alongside the
 * existing cover_last_generated_at timestamp, so the dashboard can show "cover
 * X generated by zhipuai cogview-3-flash in 8.2s" instead of just a file.
 *
 * Add-only via SafeMigrationHelper — never drops or rewrites existing data.
 */
return new class extends Migration
{
    protected $connection;
    protected $appKey;
    protected $tableName;

    public function __construct()
    {
        $this->appKey = AppKeys::APPQYV1;
        $this->connection = AppTablePrefixServiceProvider::getConnection($this->appKey);
        $this->tableName = AppTablePrefixServiceProvider::buildTableName($this->appKey, 'vocabulary_libraries');
    }

    public function up(): void
    {
        SafeMigrationHelper::safeAddColumns($this->connection, $this->tableName, [
            'cover_provider' => function (Blueprint $table, string $col) {
                $table->string($col, 64)->nullable()
                    ->comment('AI provider that generated the cover (e.g. zhipuai, gemini)');
            },
            'cover_model' => function (Blueprint $table, string $col) {
                $table->string($col, 128)->nullable()
                    ->comment('Model id used to generate the cover (e.g. cogview-3-flash)');
            },
            'cover_latency_ms' => function (Blueprint $table, string $col) {
                $table->integer($col)->nullable()
                    ->comment('Generation latency in ms as reported by the assist worker');
            },
        ]);
    }

    public function down(): void
    {
        // Add-only migration: no destructive rollback (provenance is additive).
    }
};
