// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

import 'localization_keys_app_travel.dart';

Map<String, String> enAppTravel = {
  TravelLocalizationKeys.travelAppName: 'Travel',
  TravelLocalizationKeys.travelHome: 'Home',
  TravelLocalizationKeys.travelCity: 'City',
  TravelLocalizationKeys.travelSight: 'Sight',
  TravelLocalizationKeys.travelFavorites: 'Favorites',
  TravelLocalizationKeys.travelBookmarks: 'Bookmarks',
  TravelLocalizationKeys.travelSearch: 'Search',
  TravelLocalizationKeys.travelSettings: 'Settings',
  TravelLocalizationKeys.travelAbout: 'About',

  TravelLocalizationKeys.travelSearchPlaceholder: 'Search destinations...',
  TravelLocalizationKeys.travelSearchHistory: 'Search History',
  TravelLocalizationKeys.travelSearchNoResults: 'No results found',
  TravelLocalizationKeys.travelClearHistory: 'Clear History',

  TravelLocalizationKeys.travelHotCities: 'Hot Cities',
  TravelLocalizationKeys.travelAllCities: 'All Cities',
  TravelLocalizationKeys.travelCurrentCity: 'Current City',
  TravelLocalizationKeys.travelSelectCity: 'Select City',

  TravelLocalizationKeys.travelHotel: 'Hotel',
  TravelLocalizationKeys.travelFlight: 'Flight',
  TravelLocalizationKeys.travelTrain: 'Train',
  TravelLocalizationKeys.travelTravel: 'Travel',
  TravelLocalizationKeys.travelMinsu: 'Homestay',
  TravelLocalizationKeys.travelCustom: 'Custom',

  TravelLocalizationKeys.travelPopular: 'Popular',
  TravelLocalizationKeys.travelRecommend: 'Recommend',
  TravelLocalizationKeys.travelLocalHot: 'Local Hot',
  TravelLocalizationKeys.travelAttractions: 'Attractions',
  TravelLocalizationKeys.travelAccommodation: 'Accommodation',
  TravelLocalizationKeys.travelFood: 'Food',
  TravelLocalizationKeys.travelShopping: 'Shopping',

  TravelLocalizationKeys.travelAddToFavorites: 'Add to Favorites',
  TravelLocalizationKeys.travelRemoveFromFavorites: 'Remove from Favorites',
  TravelLocalizationKeys.travelAddToBookmarks: 'Add to Bookmarks',
  TravelLocalizationKeys.travelRemoveFromBookmarks: 'Remove from Bookmarks',

  TravelLocalizationKeys.travelShare: 'Share',
  TravelLocalizationKeys.travelDetails: 'Details',
  TravelLocalizationKeys.travelReviews: 'Reviews',
  TravelLocalizationKeys.travelRating: 'Rating',
  TravelLocalizationKeys.travelLocation: 'Location',
  TravelLocalizationKeys.travelOpeningHours: 'Opening Hours',
  TravelLocalizationKeys.travelTicketPrice: 'Ticket Price',

  TravelLocalizationKeys.travelNoData: 'No data available',
  TravelLocalizationKeys.travelLoading: 'Loading...',
  TravelLocalizationKeys.travelError: 'Error occurred',
  TravelLocalizationKeys.travelRetry: 'Retry',
  TravelLocalizationKeys.travelRefresh: 'Refresh',

  TravelLocalizationKeys.travelLanguage: 'Language',
  TravelLocalizationKeys.travelTheme: 'Theme',
  TravelLocalizationKeys.travelLightMode: 'Light Mode',
  TravelLocalizationKeys.travelDarkMode: 'Dark Mode',
  TravelLocalizationKeys.travelSystemMode: 'System Mode',

  TravelLocalizationKeys.travelCancel: 'Cancel',
  TravelLocalizationKeys.travelConfirm: 'Confirm',
  TravelLocalizationKeys.travelOk: 'OK',
  TravelLocalizationKeys.travelClose: 'Close',
  TravelLocalizationKeys.travelBack: 'Back',
  TravelLocalizationKeys.travelNext: 'Next',
  TravelLocalizationKeys.travelDone: 'Done',

  TravelLocalizationKeys.travelLogin: 'Login',
  TravelLocalizationKeys.travelLogout: 'Logout',
  TravelLocalizationKeys.travelUsername: 'Username',
  TravelLocalizationKeys.travelPassword: 'Password',
  TravelLocalizationKeys.travelLoginSuccess: 'Login successful',
  TravelLocalizationKeys.travelLoginFailed: 'Login failed',
  TravelLocalizationKeys.travelPleaseEnterUsername: 'Please enter username',
  TravelLocalizationKeys.travelPleaseEnterPassword: 'Please enter password',
  TravelLocalizationKeys.travelDebugModeHint: 'Debug Mode - Any credentials work',
  TravelLocalizationKeys.travelSkipLogin: 'Skip Login',
  TravelLocalizationKeys.travelWelcomeBack: 'Welcome Back',
  TravelLocalizationKeys.travelProfile: 'Profile',
  TravelLocalizationKeys.travelUser: 'User',
  TravelLocalizationKeys.travelGuestUser: 'Guest User',
  TravelLocalizationKeys.travelPopularCities: 'Popular Cities',
  TravelLocalizationKeys.travelCustomCity: 'Custom City',
  TravelLocalizationKeys.travelEnterCityName: 'Enter city name',
  TravelLocalizationKeys.travelCityChangedTo: 'City changed to',

  TravelLocalizationKeys.travelNewUserGift: 'New User Gift',
  TravelLocalizationKeys.travelWelcomeToCity: 'Hello, welcome to',
  TravelLocalizationKeys.travelAttractionRanking: 'Attraction Ranking',
  TravelLocalizationKeys.travelRanking: 'Ranking',
  TravelLocalizationKeys.travelMore: 'More',
  TravelLocalizationKeys.travelDailyCoupon: 'Daily Coupon',
  TravelLocalizationKeys.travelSignInCoupon: 'Sign-in Coupon',
  TravelLocalizationKeys.travelCheapFlights: 'Cheap Flights',
  TravelLocalizationKeys.travel30DayLowPrice: '30-day Low Price',
  TravelLocalizationKeys.travelDiscountFlight: '10% Off Flight',
  TravelLocalizationKeys.travelStartingPrice: 'Starting from ¥200',
  TravelLocalizationKeys.travelHotelStock: 'Hotel Stock',
  TravelLocalizationKeys.travelFlashDeal: 'Flash Deal ¥69',
  TravelLocalizationKeys.travelAIItinerary: 'AI Itinerary',
  TravelLocalizationKeys.travelSmartPlanning: 'Smart Planning',
  TravelLocalizationKeys.travelEnableLocation: 'Enable location to view nearby tourism resources',
  TravelLocalizationKeys.travelGoEnable: 'Enable',
  TravelLocalizationKeys.travelCoupon: 'Coupon',
  TravelLocalizationKeys.travelFavoritesAndViews: 'Favorites & Views',
  TravelLocalizationKeys.travelPoints: 'Points',
  TravelLocalizationKeys.travelPendingPayment: 'Pending Payment',
  TravelLocalizationKeys.travelPendingTrip: 'Pending Trip',
  TravelLocalizationKeys.travelPendingReview: 'Pending Review',
  TravelLocalizationKeys.travelRefundAfterSales: 'Refund/After-sales',
  TravelLocalizationKeys.travelMyOrders: 'My Orders',
  TravelLocalizationKeys.travelCreditLoan: 'Credit Loan',
  TravelLocalizationKeys.travelMaxAmount: 'Max Amount',
  TravelLocalizationKeys.travelNakuHua: 'Spend Now',
  TravelLocalizationKeys.travelMaxCredit: 'Max Credit',
  TravelLocalizationKeys.travelBusinessLoan: 'Business Loan',
  TravelLocalizationKeys.travelBankZone: 'Bank Zone',
  TravelLocalizationKeys.travelCommonInfo: 'Common Info',
  TravelLocalizationKeys.travelMyInvoice: 'My Invoice',
  TravelLocalizationKeys.travelRightsCard: 'Rights Card',
  TravelLocalizationKeys.travelMyReviews: 'My Reviews',
  TravelLocalizationKeys.travelMyNotes: 'My Notes',
  TravelLocalizationKeys.travelCreationCenter: 'Creation Center',
  TravelLocalizationKeys.travelMyCommunity: 'My Community',
  TravelLocalizationKeys.travelTravelFootprint: 'Travel Footprint',
  TravelLocalizationKeys.travelComplaint: 'Complaint',
  TravelLocalizationKeys.travelMyCredit: 'My Credit',
  TravelLocalizationKeys.travelPublicMember: 'Public Member',
  TravelLocalizationKeys.travelPointsRedeem: 'Points Redeem',
  TravelLocalizationKeys.travel12306Prompt: 'Login to 12306 for express ticketing and priority refunds',
  TravelLocalizationKeys.travelGoCheck: 'Go Check',
  TravelLocalizationKeys.travelMyWallet: 'My Wallet',
  TravelLocalizationKeys.travelWonderfulRecommendation: 'Wonderful Recommendations',
  TravelLocalizationKeys.travelWonderful: 'Wonderful',
  TravelLocalizationKeys.travelMyItinerary: 'My Itinerary',
  TravelLocalizationKeys.travelAllOrders: 'All Orders',
  TravelLocalizationKeys.travelCustomerService: 'Customer Service',
  TravelLocalizationKeys.travelServiceCenter: 'Service Center',
  TravelLocalizationKeys.travelOnlineServiceDev: 'Online service in development',
  TravelLocalizationKeys.travelExploreWorld: 'Explore World',
  TravelLocalizationKeys.travelTravelGuide: 'Travel Guide',
  TravelLocalizationKeys.travelMine: 'Mine',
  TravelLocalizationKeys.travelJourney: 'Journey',
};
