// ### AI SPECIAL ATTENTION RULES START ###
// When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
// 1. Write all code in English only.
// 2. Never execute, create, or modify test code.
// 3. Never create or update documentation (*.md).
// 4. Never write summaries during development or thinking process.
// 5. Declare all variables at the beginning of the file.
// 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
// 7. Do not modify these rules.
// VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
// ### AI SPECIAL ATTENTION RULES END ###

import 'localization_keys_app_travel.dart';

Map<String, String> zhAppTravel = {
  TravelLocalizationKeys.travelAppName: '旅游',
  TravelLocalizationKeys.travelHome: '首页',
  TravelLocalizationKeys.travelCity: '城市',
  TravelLocalizationKeys.travelSight: '景点',
  TravelLocalizationKeys.travelFavorites: '收藏',
  TravelLocalizationKeys.travelBookmarks: '书签',
  TravelLocalizationKeys.travelSearch: '搜索',
  TravelLocalizationKeys.travelSettings: '设置',
  TravelLocalizationKeys.travelAbout: '关于',

  TravelLocalizationKeys.travelSearchPlaceholder: '搜索目的地...',
  TravelLocalizationKeys.travelSearchHistory: '搜索历史',
  TravelLocalizationKeys.travelSearchNoResults: '未找到结果',
  TravelLocalizationKeys.travelClearHistory: '清除历史',

  TravelLocalizationKeys.travelHotCities: '热门城市',
  TravelLocalizationKeys.travelAllCities: '全部城市',
  TravelLocalizationKeys.travelCurrentCity: '当前城市',
  TravelLocalizationKeys.travelSelectCity: '选择城市',

  TravelLocalizationKeys.travelHotel: '酒店',
  TravelLocalizationKeys.travelFlight: '机票',
  TravelLocalizationKeys.travelTrain: '火车票',
  TravelLocalizationKeys.travelTravel: '旅游',
  TravelLocalizationKeys.travelMinsu: '民宿',
  TravelLocalizationKeys.travelCustom: '定制',

  TravelLocalizationKeys.travelPopular: '热门推荐',
  TravelLocalizationKeys.travelRecommend: '推荐',
  TravelLocalizationKeys.travelLocalHot: '当地热门',
  TravelLocalizationKeys.travelAttractions: '景点',
  TravelLocalizationKeys.travelAccommodation: '住宿',
  TravelLocalizationKeys.travelFood: '美食',
  TravelLocalizationKeys.travelShopping: '购物',

  TravelLocalizationKeys.travelAddToFavorites: '添加到收藏',
  TravelLocalizationKeys.travelRemoveFromFavorites: '从收藏中移除',
  TravelLocalizationKeys.travelAddToBookmarks: '添加到书签',
  TravelLocalizationKeys.travelRemoveFromBookmarks: '从书签中移除',

  TravelLocalizationKeys.travelShare: '分享',
  TravelLocalizationKeys.travelDetails: '详情',
  TravelLocalizationKeys.travelReviews: '评价',
  TravelLocalizationKeys.travelRating: '评分',
  TravelLocalizationKeys.travelLocation: '位置',
  TravelLocalizationKeys.travelOpeningHours: '开放时间',
  TravelLocalizationKeys.travelTicketPrice: '门票价格',

  TravelLocalizationKeys.travelNoData: '暂无数据',
  TravelLocalizationKeys.travelLoading: '加载中...',
  TravelLocalizationKeys.travelError: '发生错误',
  TravelLocalizationKeys.travelRetry: '重试',
  TravelLocalizationKeys.travelRefresh: '刷新',

  TravelLocalizationKeys.travelLanguage: '语言',
  TravelLocalizationKeys.travelTheme: '主题',
  TravelLocalizationKeys.travelLightMode: '浅色模式',
  TravelLocalizationKeys.travelDarkMode: '深色模式',
  TravelLocalizationKeys.travelSystemMode: '跟随系统',

  TravelLocalizationKeys.travelCancel: '取消',
  TravelLocalizationKeys.travelConfirm: '确认',
  TravelLocalizationKeys.travelOk: '确定',
  TravelLocalizationKeys.travelClose: '关闭',
  TravelLocalizationKeys.travelBack: '返回',
  TravelLocalizationKeys.travelNext: '下一步',
  TravelLocalizationKeys.travelDone: '完成',

  TravelLocalizationKeys.travelLogin: '登录',
  TravelLocalizationKeys.travelLogout: '退出登录',
  TravelLocalizationKeys.travelUsername: '用户名',
  TravelLocalizationKeys.travelPassword: '密码',
  TravelLocalizationKeys.travelLoginSuccess: '登录成功',
  TravelLocalizationKeys.travelLoginFailed: '登录失败',
  TravelLocalizationKeys.travelPleaseEnterUsername: '请输入用户名',
  TravelLocalizationKeys.travelPleaseEnterPassword: '请输入密码',
  TravelLocalizationKeys.travelDebugModeHint: '调试模式 - 任何凭据均可',
  TravelLocalizationKeys.travelSkipLogin: '跳过登录',
  TravelLocalizationKeys.travelWelcomeBack: '欢迎回来',
  TravelLocalizationKeys.travelProfile: '我的',
  TravelLocalizationKeys.travelUser: '用户',
  TravelLocalizationKeys.travelGuestUser: '游客用户',
  TravelLocalizationKeys.travelPopularCities: '热门城市',
  TravelLocalizationKeys.travelCustomCity: '自定义城市',
  TravelLocalizationKeys.travelEnterCityName: '输入城市名称',
  TravelLocalizationKeys.travelCityChangedTo: '城市已更改为',

  TravelLocalizationKeys.travelNewUserGift: '新人大礼包',
  TravelLocalizationKeys.travelWelcomeToCity: '您好,欢迎来到',
  TravelLocalizationKeys.travelAttractionRanking: '景点人气榜',
  TravelLocalizationKeys.travelRanking: '排行榜',
  TravelLocalizationKeys.travelMore: '更多',
  TravelLocalizationKeys.travelDailyCoupon: '天天神券',
  TravelLocalizationKeys.travelSignInCoupon: '签到领券',
  TravelLocalizationKeys.travelCheapFlights: '低价机票',
  TravelLocalizationKeys.travel30DayLowPrice: '30天低价',
  TravelLocalizationKeys.travelDiscountFlight: '1折机票',
  TravelLocalizationKeys.travelStartingPrice: '200元起',
  TravelLocalizationKeys.travelHotelStock: '酒店囤货',
  TravelLocalizationKeys.travelFlashDeal: '69元秒底',
  TravelLocalizationKeys.travelAIItinerary: 'AI行程',
  TravelLocalizationKeys.travelSmartPlanning: '智能规划',
  TravelLocalizationKeys.travelEnableLocation: '开启定位后，查看周边旅游资源',
  TravelLocalizationKeys.travelGoEnable: '去开启',
  TravelLocalizationKeys.travelCoupon: '优惠券',
  TravelLocalizationKeys.travelFavoritesAndViews: '收藏浏览',
  TravelLocalizationKeys.travelPoints: '积分',
  TravelLocalizationKeys.travelPendingPayment: '待付款',
  TravelLocalizationKeys.travelPendingTrip: '待出行',
  TravelLocalizationKeys.travelPendingReview: '待点评',
  TravelLocalizationKeys.travelRefundAfterSales: '退款/售后',
  TravelLocalizationKeys.travelMyOrders: '我的订单',
  TravelLocalizationKeys.travelCreditLoan: '信用贷',
  TravelLocalizationKeys.travelMaxAmount: '最高可借',
  TravelLocalizationKeys.travelNakuHua: '拿去花',
  TravelLocalizationKeys.travelMaxCredit: '最高额度',
  TravelLocalizationKeys.travelBusinessLoan: '生意人贷',
  TravelLocalizationKeys.travelBankZone: '银行专区',
  TravelLocalizationKeys.travelCommonInfo: '常用信息',
  TravelLocalizationKeys.travelMyInvoice: '我的发票',
  TravelLocalizationKeys.travelRightsCard: '权益卡',
  TravelLocalizationKeys.travelMyReviews: '我的点评',
  TravelLocalizationKeys.travelMyNotes: '我的笔记',
  TravelLocalizationKeys.travelCreationCenter: '创作中心',
  TravelLocalizationKeys.travelMyCommunity: '我的社区',
  TravelLocalizationKeys.travelTravelFootprint: '旅行足迹',
  TravelLocalizationKeys.travelComplaint: '我要吐槽',
  TravelLocalizationKeys.travelMyCredit: '我的信用',
  TravelLocalizationKeys.travelPublicMember: '大众会员',
  TravelLocalizationKeys.travelPointsRedeem: '积分抵现',
  TravelLocalizationKeys.travel12306Prompt: '登录12306账号可享极速出票、优先退改',
  TravelLocalizationKeys.travelGoCheck: '去查看',
  TravelLocalizationKeys.travelMyWallet: '我的钱包',
  TravelLocalizationKeys.travelWonderfulRecommendation: '精彩推荐 一玩到底',
  TravelLocalizationKeys.travelWonderful: '精彩推荐',
  TravelLocalizationKeys.travelMyItinerary: '我的行程',
  TravelLocalizationKeys.travelAllOrders: '全部订单',
  TravelLocalizationKeys.travelCustomerService: '客服',
  TravelLocalizationKeys.travelServiceCenter: '客服中心',
  TravelLocalizationKeys.travelOnlineServiceDev: '在线客服功能开发中',
  TravelLocalizationKeys.travelExploreWorld: '看世界',
  TravelLocalizationKeys.travelTravelGuide: '旅行攻略',
  TravelLocalizationKeys.travelMine: '我的',
  TravelLocalizationKeys.travelJourney: '行程',
};
