# Kotlin Configuration Fix Script
# Generated by script_generator.py


# Path normalization helper function
function Normalize-Path {
    param(
        [string]$Path,
        [string]$TargetFormat = "flutter",
        [bool]$Debug = $false
    )
    
    if ([string]::IsNullOrWhiteSpace($Path)) {
        return $Path
    }
    
    $Path = $Path.Trim()
    
    if ($Debug) {
        Write-Host "[PATH] Input: '$Path'" -ForegroundColor Gray
    }
    
    if ($TargetFormat -eq "flutter" -or $TargetFormat -eq "auto") {
        $Path = $Path -replace "\\+", "/"
        $Path = $Path -replace "\", "/"
        $Path = $Path -replace "/+", "/"
    }
    elseif ($TargetFormat -eq "windows") {
        $Path = $Path -replace "/+", "\"
        $Path = $Path -replace "/", "\"
        $Path = $Path -replace "\+", "\"
    }
    
    if ($Path.StartsWith("/") -and -not $Path.StartsWith("//")) {
        $Path = $Path.Substring(1)
    }
    if ($Path.StartsWith("\") -and -not $Path.StartsWith("\\")) {
        $Path = $Path.Substring(1)
    }
    
    if ($Debug) {
        Write-Host "[PATH] Output: '$Path'" -ForegroundColor Gray
    }
    
    return $Path
}

# Flutter command path fix helper function
function Fix-FlutterCommandPath {
    param(
        [string]$Command,
        [bool]$Debug = $false
    )
    
    if ([string]::IsNullOrWhiteSpace($Command)) {
        return $Command
    }
    
    if ($Debug) {
        Write-Host "[CMD] Original: '$Command'" -ForegroundColor Gray
    }
    
    $Command = $Command -replace " -t ([^\s]+)", {
        $path = $matches[1]
        $normalizedPath = Normalize-Path -Path $path -TargetFormat "flutter" -Debug $Debug
        " -t $normalizedPath"
    }
    
    if ($Debug) {
        Write-Host "[CMD] Fixed: '$Command'" -ForegroundColor Gray
    }
    
    return $Command
}


Write-Host "[KOTLIN] Starting Kotlin incremental compilation fix..." -ForegroundColor Yellow

# Fix Kotlin incremental compilation using Python script
if (true) {
    Write-Host "[KOTLIN] Fixing Kotlin incremental compilation..." -ForegroundColor Yellow
    $kotlinScriptPath = "scripts/build_scripts/utils/kotlin_config_manager.py"
    if (Test-Path $kotlinScriptPath) {
        try {
            $result = python $kotlinScriptPath fix (Get-Location) 2>&1
            if ($LASTEXITCODE -eq 0) {
                Write-Host "[KOTLIN] Kotlin configuration fixed successfully" -ForegroundColor Green
            } else {
                Write-Host "[KOTLIN] Kotlin configuration fix failed: $result" -ForegroundColor Red
            }
        } catch {
            Write-Host "[KOTLIN] Error running Kotlin config script: $_" -ForegroundColor Red
        }
    } else {
        Write-Host "[KOTLIN] Kotlin config script not found: $kotlinScriptPath" -ForegroundColor Yellow
    }
} else {
    Write-Host "[KOTLIN] Kotlin incremental compilation is already disabled" -ForegroundColor Green
}

Write-Host "[KOTLIN] Kotlin fix completed!" -ForegroundColor Green
