#!/bin/bash
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# Codex CLI Global File #1
# =============================================================================
#
# Synopsis:
#     Codex CLI Launch Script
#
# Description:
#     This file is automatically generated by Special Software Environment Manager
#     Contains environment variable setup and tool startup functionality for Linux systems
#
# Notes:
#     - Tool Name: Codex CLI
#     - Command Prefix: codex
#     - Command: codex
#     - File Number: 1
#     - File Name: codex1.sh
#     - Generation Time: 2025-11-10 07:16:54
#
# Environment Variables:
#     Environment variables are loaded from encrypted storage using secret_manager.sh
# =============================================================================

set -e

echo ""
echo "============================================================"
echo "Running: codex1.sh"
echo "============================================================"
echo ""

#region Initialize Path Variables
scriptCurrentPath="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -L "${BASH_SOURCE[0]}" ]; then
    scriptRealPath="$(readlink -f "${BASH_SOURCE[0]}")"
    scriptCurrentPath="$(cd "$(dirname "$scriptRealPath")" && pwd)"
fi
scriptsDirPath="$(cd "$scriptCurrentPath/.." && pwd)"
shellsDirPath="$scriptsDirPath/shells"
linuxDirPath="$shellsDirPath/linux"
linuxCommonDirPath="$linuxDirPath/linux_common"
pytoolsDirPath="$scriptsDirPath/pytools"
aiToolsDirPath="$pytoolsDirPath/ai_tools"
projectRootPath="$(cd "$scriptsDirPath/.." && pwd)"
# Path resolution algorithm:
#   Script -> Scripts Dir -> Project Root -> Tool-specific directories

#region Custom User Directory Configuration
# ============================================================================
# CUSTOM USER DIRECTORY SETTING
# ============================================================================
# Automatically generates user directory at /tmp/Users/时间�?# Format: /tmp/Users/YYYYMMDD_HHMMSS
# ============================================================================

# Generate timestamp for directory name
timestamp=$(date +"%Y%m%d_%H%M%S")
baseTempDir="/tmp/Users"
CustomUserDirectory="$baseTempDir/$timestamp"

# Create the directory if it doesn't exist
if [ ! -d "$baseTempDir" ]; then
    echo "[INFO] Creating base directory: $baseTempDir"
    mkdir -p "$baseTempDir"
fi

if [ ! -d "$CustomUserDirectory" ]; then
    echo "[INFO] Creating custom user directory: $CustomUserDirectory"
    mkdir -p "$CustomUserDirectory"
fi

# Verify directory was created successfully
if [ -d "$CustomUserDirectory" ]; then
    userProfilePath="$CustomUserDirectory"
    echo "[SUCCESS] Using auto-generated custom user directory: $userProfilePath"
else
    echo "[WARNING] Failed to create custom directory, falling back to system default"
    userProfilePath="$HOME"
    echo "[INFO] Using system default user directory: $userProfilePath"
fi

userHomePath="$userProfilePath"
usersDirectoryPath="$(dirname "$userProfilePath")"

# Set environment variables for Node.js, React, Python, and other applications
# ============================================================================
# These environment variables will be available to all child processes
# including Node.js, React, Python, and other applications launched from this script
#
# Python usage examples:
#   import os
#   user_home = os.path.expanduser("~")  # Uses HOME
#   user_home = os.getenv("HOME")
#   from pathlib import Path
#   user_home = Path.home()  # Uses HOME
# ============================================================================
export HOME="$userProfilePath"
export USER_HOME="$userProfilePath"
export USER_DIR="$userProfilePath"

echo "[INFO] Environment variables set for Node.js/React/Python applications:"
echo "  HOME = $HOME"
echo "  USER_HOME = $USER_HOME"
echo "  USER_DIR = $USER_DIR"
echo ""
#endregion

#endregion

# =============================================================================
# Load Environment Variables from Secret Manager
# =============================================================================
echo ""
echo "============================================================"
echo "Loading Environment Variables"
echo "============================================================"
echo ""

python_exec="python3"
if ! command -v "$python_exec" &> /dev/null; then
    if command -v python &> /dev/null; then
        python_exec="python"
    else
        echo "[ERROR] Python is required to load secrets"
        exit 1
    fi
fi

pycore_launcher="/www/programing/core_node/pycore_module_caller.py"

load_secret_value() {
    local key_name="$1"
    local env_name="$2"
    local display_name="$3"
    local value=""

    value=$($python_exec "$pycore_launcher"         --module pyfoundations.secret_manager         --call get_secret_key         "$key_name" 2>/dev/null)

    if [ -n "$value" ]; then
        printf -v "$env_name" '%s' "$value"
        export "$env_name"
        echo "[SUCCESS] Loaded $display_name"
        return 0
    fi

    echo "[WARNING] Failed to load $display_name"
    return 1
}

load_secret_value "OPENAI_API_KEY_1" "OPENAI_API_KEY" "OPENAI_API_KEY"
load_secret_value "OPENAI_BASE_URL_1" "OPENAI_BASE_URL" "OPENAI_BASE_URL"

echo ""

# =============================================================================
# MCP Server Synchronization
# =============================================================================
echo ""
echo "============================================================"
echo "MCP Server Synchronization"
echo "============================================================"
echo ""

echo "Codex CLI - Pre-Launch Tasks"
echo ""

# Execute pre-launch script if it exists
preLaunchScript="$aiToolsDirPath/codex_pre_launch.sh"
if [ -f "$preLaunchScript" ]; then
    current_working_dir="$(pwd)"
    echo "[INFO] Executing pre-launch script: $preLaunchScript"
    echo "[INFO] Working Directory: $current_working_dir"
    echo ""
    bash "$preLaunchScript" "$current_working_dir"
    echo ""
fi

echo "Available tasks:"
echo "  [1] Upgrade Codex CLI to latest version (runs in separate terminal)"
echo "  [2] Sync MCP server configurations (runs now)"
echo ""

read -p "Do you want to upgrade Codex CLI? (y/N): " upgrade_choice
if [ "$upgrade_choice" = "y" ] || [ "$upgrade_choice" = "Y" ]; then
    echo ""
    echo "[INFO] Launching Codex CLI upgrade in separate terminal..."
    upgrade_script="$aiToolsDirPath/codex_update.sh"
    if [ -f "$upgrade_script" ]; then
        # Launch in background to avoid blocking current environment
        if command -v gnome-terminal &> /dev/null; then
            gnome-terminal -- bash -c "$upgrade_script; read -p 'Press Enter to close'"
        elif command -v xterm &> /dev/null; then
            xterm -e "bash $upgrade_script; read -p 'Press Enter to close'" &
        else
            bash "$upgrade_script" &
        fi
        echo "[SUCCESS] Upgrade terminal opened"
    else
        echo "[WARNING] Upgrade script not found: $upgrade_script"
    fi
else
    echo "[INFO] Skipping upgrade"
fi


current_working_dir="$(pwd)"
echo ""
echo "Syncing MCP Server Configurations..."
echo ""
sync_script="$aiToolsDirPath/codex_sync_mcp_servers.py"
if [ -f "$sync_script" ]; then
    echo "[INFO] Executing: python -u '$sync_script' --target codex --working-dir '$current_working_dir'"
    echo "[INFO] Working Directory: $current_working_dir"
    echo ""

    # Detect Python command
    if command -v python3 &> /dev/null; then
        PYTHON_CMD="python3"
    elif command -v python &> /dev/null; then
        PYTHON_CMD="python"
    else
        echo "[ERROR] Python not found"
        exit 1
    fi

    $PYTHON_CMD -u "$sync_script" --target codex --working-dir "$current_working_dir"
else
    echo "[WARNING] MCP sync script not found: $sync_script"
    echo "[INFO] Skipping MCP synchronization"
fi

echo ""
echo "============================================================"
echo "Press Enter to start Codex CLI..."
echo "============================================================"
read -p "Press Enter to continue"



# =============================================================================
# Launch Tool
# =============================================================================
echo ""
echo "============================================================"
echo "Press Enter to start Codex CLI..."
echo "============================================================"
read -p "Press Enter to continue"

echo ""
echo "Executing: codex"
echo ""
echo "Environment Variables:"
if [ -n "${OPENAI_API_KEY}" ]; then
    echo "  OPENAI_API_KEY=${OPENAI_API_KEY}"
fi
if [ -n "${OPENAI_BASE_URL}" ]; then
    echo "  OPENAI_BASE_URL=${OPENAI_BASE_URL}"
fi


echo ""
echo "Starting Codex CLI..."
echo ""

# Execute command with environment variables
codex

echo ""
echo "Session ended"
echo ""
