#!/bin/bash

# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For Shell (*.sh) scripts: Always use absolute paths, avoid relative paths like "../".
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# Codex CLI Environment Variables Global File #1
# =============================================================================
#
# Synopsis:
#     Codex CLI Launch Script
#
# Description:
#     This file is automatically generated by Special Software Environment Manager
#     Contains environment variable setup and tool startup functionality for Codex CLI
#
# Notes:
#     - Tool Name: Codex CLI Environment Variables
#     - Command Prefix: codex
#     - Command: codex
#     - File Number: 1
#     - File Name: codex1.sh
#     - Generation Time: 2025-01-27
# =============================================================================

set -eo pipefail

# Declare variables at the beginning
AUTH_TOKEN_PREFIX=""
AUTH_TOKEN_PART1=""
AUTH_TOKEN_PART2=""
AUTH_TOKEN_PART3=""
AUTH_TOKEN_SUFFIX=""
COMBINED_AUTH_TOKEN=""
API_ENDPOINT_SCHEME=""
API_ENDPOINT_DOMAIN=""
API_ENDPOINT_PATH=""
OPENAI_API_KEY=""
OPENAI_BASE_URL=""
ENV_VARS_COMMAND=""
FULL_COMMAND=""

echo ""
echo "============================================================"
echo "Running: codex1.sh"
echo "============================================================"
echo ""

# =============================================================================
# Load Environment Variables
# =============================================================================
echo ""
echo "============================================================"
echo "Loading Environment Variables"
echo "============================================================"
echo ""

# Set API Key
export OPENAI_API_KEY="cr_d48129e9dd3f7ed60087a1e52f7246754f23fc49710e7b3c24117aa3a1be9889"

if [ -n "$OPENAI_API_KEY" ]; then
    echo "[SUCCESS] Loaded OPENAI_API_KEY"
    echo "OPENAI_API_KEY=$OPENAI_API_KEY"
else
    echo "[WARNING] Failed to load OPENAI_API_KEY"
fi

# Set Base URL
export OPENAI_BASE_URL="https://api.fastaicode.top/openai/"

if [ -n "$OPENAI_BASE_URL" ]; then
    echo "[SUCCESS] Loaded OPENAI_BASE_URL"
    echo "OPENAI_BASE_URL=$OPENAI_BASE_URL"
else
    echo "[WARNING] Failed to load OPENAI_BASE_URL"
fi

# =============================================================================
# Launch Tool
# =============================================================================
echo ""
echo "============================================================"
echo "Press Enter to start Codex CLI Environment Variables..."
echo "============================================================"
read -r

echo ""
echo "Executing: codex"
echo ""
echo "Environment variables are set:"
echo "  OPENAI_API_KEY=$OPENAI_API_KEY"
echo "  OPENAI_BASE_URL=$OPENAI_BASE_URL"
echo ""

# Execute codex command directly (environment variables are already exported)
codex --yolo

echo ""
echo "Session ended"
echo ""

