<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotCore.Foundations\DotCore.Foundations.csproj" />
    <ProjectReference Include="..\DotCore.Common\DotCore.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PaddleOCRSharp" />
  </ItemGroup>
</Project>
