"""
Ark CLI v4 launcher template generator.

Generates numbered ``ark${index}.ps1`` / ``ark${index}.sh`` launchers (the v4
lean-launcher path) that run the NATIVE Volcano Ark CLI (``arkcli`` from the
``@volcengine/ark-cli`` npm package) - NOT Claude Code.

Each generated script:

- Ensures ``arkcli`` is installed and working (idempotent: ``arkcli --version``
  succeeds -> skip; else ``npm install -g @volcengine/ark-cli@latest``).
- Optionally runs ``arkcli auth login`` (opt-in prompt, default No) so the user
  can (re)authenticate on first run or after token expiry; arkcli caches
  credentials itself.
- Execs ``arkcli`` natively, forwarding all pass-through args.

It deliberately does NOT set any ``ANTHROPIC_*`` / ``CLAUDE_CODE_*`` env vars
and does NOT launch ``claude`` - the native arkcli owns endpoint, model and
auth (configured via ``arkcli auth login`` / ``arkcli helper``).

The config ``Variables`` (``ARK_API_KEY`` / ``ARK_BASE_URL`` /
``ANTHROPIC_MODEL``) are intentionally NOT read here. They stay in the config
only so the Special Software Env Manager can discover stored secret file
numbers (e.g. ``ARK_API_KEY_1``) and reuse the key shared with the
``'Volcano Ark'`` encrypted-constant config + ``claudevolc.ps1``.

Official Ark CLI facts (verified sources: Volcano Ark docs + repo installer
``scripts/shells/linux/debian/install_shells/137_install_arkcli.sh``):
- Install: ``npm install -g @volcengine/ark-cli@latest``
- Verify: ``arkcli --version``
- Login: ``arkcli auth login`` (interactive: select login method, project,
  agent-plan consumption type)
- Optional ``arkcli helper`` auto-configures Claude Code - NOT used by this
  launcher, which runs arkcli natively instead.
"""

from typing import List, Dict, Any


class ArkLauncherSectionGenerator:
    """Generate the ark${index} v4 launcher scripts (ps1 + sh) - native arkcli."""

    ARK_NPM_PACKAGE = "@volcengine/ark-cli@latest"

    def generate_ps1(self, display_name: str, file_number: int,
                     variables: List[Dict[str, Any]], command_prefix: str) -> str:
        """Generate the Windows PowerShell native arkcli launcher script content.

        ``variables`` / ``command_prefix`` are accepted for interface parity with
        ``ScriptManager.generate_v4_launcher_for_config`` but intentionally unused
        (the native arkcli launcher does not read any secrets - see module docstring).
        """
        ark_package = self.ARK_NPM_PACKAGE
        return f'''# =============================================================================
# {display_name} Launch Script #{file_number} - v4 [native arkcli]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Runs the NATIVE Volcano Ark CLI (arkcli from @volcengine/ark-cli) - NOT Claude.
# Ensures arkcli is installed (idempotent), optional arkcli auth login, then
#   execs arkcli natively with pass-through args.
# No ANTHROPIC_*/CLAUDE_CODE_* env vars, no claude binary - arkcli owns
#   endpoint/model/auth (configured via arkcli auth login / arkcli helper).
# =============================================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Variables declared at the top of the file (project rule).
$arkcliCmd = $null
$arkcliOk = $false
$npmCmd = $null
$loginChoice = $null
$exitCode = 0
$scriptActualPath = $null
$item = $null
$scriptCurrentPath = $null
$scriptsDirPath = $null
$projectRootPath = $null
$shellsWinPath = $null
$winCommonDirPath = $null
$windowsPathFunctionScript = $null

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "{display_name} #{file_number} - v4 [native arkcli]" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Initialize path variables (resolve symlinks, then scripts/project roots).
$scriptActualPath = $PSCommandPath
$item = Get-Item -LiteralPath $PSCommandPath
if ($item -and $item -is [System.IO.FileInfo] -and $item.LinkType) {{
    $scriptActualPath = $item.Target
}}
$scriptCurrentPath = Split-Path $scriptActualPath -Parent
if (-not $scriptCurrentPath) {{
    $scriptCurrentPath = $PSScriptRoot
    if (-not $scriptCurrentPath) {{
        $scriptCurrentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
    }}
}}
$scriptsDirPath = Split-Path $scriptCurrentPath -Parent
$projectRootPath = Split-Path $scriptsDirPath -Parent

# Ensure PATH is prepared via WindowsPathFunction (makes npm/arkcli resolvable).
$shellsWinPath = Join-Path $scriptsDirPath "shells"
$shellsWinPath = Join-Path $shellsWinPath "win"
$winCommonDirPath = Join-Path $shellsWinPath "win_common"
$windowsPathFunctionScript = Join-Path $winCommonDirPath "WindowsPathFunction.ps1"
. $windowsPathFunctionScript
Set-CoreNodePaths

# Ensure arkcli is installed and working (idempotent).
$arkcliCmd = Get-Command arkcli -ErrorAction SilentlyContinue
if ($arkcliCmd) {{
    & arkcli --version *> $null
    if ($LASTEXITCODE -eq 0) {{ $arkcliOk = $true }}
}}
if (-not $arkcliOk) {{
    Write-Host "arkcli not found; installing {ark_package}..." -ForegroundColor Yellow
    $npmCmd = Get-Command npm -ErrorAction SilentlyContinue
    if (-not $npmCmd) {{
        Write-Host "[ERROR] npm not found on PATH (install Node.js first)." -ForegroundColor Red
        exit 1
    }}
    & npm install -g "{ark_package}"
    if ($LASTEXITCODE -ne 0) {{
        Write-Host "[ERROR] npm install of @volcengine/ark-cli failed." -ForegroundColor Red
        exit 1
    }}
    # Re-resolve arkcli (npm global bin should already be on PATH from the Node
    # installer; if not, the user must restart their shell).
    $arkcliCmd = Get-Command arkcli -ErrorAction SilentlyContinue
    if (-not $arkcliCmd) {{
        Write-Host "[ERROR] arkcli installed but not on PATH. Restart your shell and re-run this script." -ForegroundColor Red
        exit 1
    }}
}}

Write-Host "arkcli: $(& arkcli --version 2>$null | Select-Object -First 1)" -ForegroundColor White
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Optional auth login (opt-in, default No). arkcli caches credentials, so this
# is only needed on first run or after the token expires.
$loginChoice = Read-Host "Run 'arkcli auth login' now? [y/N]"
if ($loginChoice -eq 'y' -or $loginChoice -eq 'Y') {{
    & arkcli auth login
}}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Press Enter to start {display_name} #{file_number} (native arkcli)..." -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
$null = Read-Host "Press Enter to continue"

Write-Host ""
Write-Host "Executing: arkcli" -ForegroundColor White
Write-Host ""

& arkcli @args
$exitCode = $LASTEXITCODE
if ($null -eq $exitCode) {{ $exitCode = 0 }}

exit $exitCode
'''

    def generate_sh(self, display_name: str, file_number: int,
                    variables: List[Dict[str, Any]], command_prefix: str) -> str:
        """Generate the Linux bash native arkcli launcher script content.

        ``variables`` / ``command_prefix`` are accepted for interface parity with
        ``ScriptManager.generate_v4_launcher_for_config`` but intentionally unused
        (the native arkcli launcher does not read any secrets - see module docstring).
        """
        ark_package = self.ARK_NPM_PACKAGE
        return f'''#!/bin/bash
# =============================================================================
# {display_name} Launch Script #{file_number} - v4 [native arkcli]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Runs the NATIVE Volcano Ark CLI (arkcli from @volcengine/ark-cli) - NOT Claude.
# Ensures arkcli is installed (idempotent), optional arkcli auth login, then
#   execs arkcli natively with pass-through args.
# No ANTHROPIC_*/CLAUDE_CODE_* env vars, no claude binary - arkcli owns
#   endpoint/model/auth (configured via arkcli auth login / arkcli helper).
# =============================================================================

set -e

# Variables declared at the top of the file (project rule).
arkcliOk=0
loginChoice=""
scriptSource=""
scriptCurrentPath=""
scriptsDirPath=""
projectRootPath=""

echo ""
echo "============================================================"
echo "{display_name} #{file_number} - v4 [native arkcli]"
echo "============================================================"
echo ""

# Path resolution kept for parity; arkcli/npm are expected on PATH via the
# 137_install_arkcli.sh installer + /etc/environment.
scriptSource="${{BASH_SOURCE[0]}}"
if [ -L "$scriptSource" ]; then
    scriptSource="$(readlink -f "$scriptSource" 2>/dev/null || echo "$scriptSource")"
fi
scriptCurrentPath="$(cd "$(dirname "$scriptSource")" && pwd)"
scriptsDirPath="$(cd "$scriptCurrentPath/.." && pwd)"
projectRootPath="$(cd "$scriptsDirPath/.." && pwd)"

# Ensure arkcli is installed and working (idempotent).
if command -v arkcli >/dev/null 2>&1 && arkcli --version >/dev/null 2>&1; then
    arkcliOk=1
fi
if [ "$arkcliOk" -eq 0 ]; then
    echo "arkcli not found; installing {ark_package}..."
    if ! command -v npm >/dev/null 2>&1; then
        echo "[ERROR] npm not found on PATH (install Node.js first)." >&2
        exit 1
    fi
    npm install -g "{ark_package}" || {{ echo "[ERROR] npm install of @volcengine/ark-cli failed." >&2; exit 1; }}
fi

echo "arkcli: $(arkcli --version 2>/dev/null | head -1)"
echo "============================================================"
echo ""

# Optional auth login (opt-in, default No). arkcli caches credentials, so this
# is only needed on first run or after the token expires.
read -r -p "Run 'arkcli auth login' now? [y/N]: " loginChoice || loginChoice=""
if [ "$loginChoice" = "y" ] || [ "$loginChoice" = "Y" ]; then
    arkcli auth login
fi

echo ""
echo "============================================================"
echo "Press Enter to start {display_name} #{file_number} (native arkcli)..."
echo "============================================================"
read -r -p "Press Enter to continue..." _

echo ""
echo "Executing: arkcli"
echo ""

exec arkcli "$@"
'''


__all__ = ['ArkLauncherSectionGenerator']
