"""
Kimi Code CLI launcher template generator.

Generates numbered ``kimi${index}.ps1`` / ``kimi${index}.sh`` launchers that:

1. Isolate the CLI under a per-slot user profile
   (Windows: ``D:\\.tmp\\Users\\Kimi${index}``,
    Linux: ``/var/_core_node/Users/Kimi${index}``) so Kimi Code config,
    MCP registration, and sessions do not touch the global user home.
2. Read the slot secrets ``KIMI_API_KEY_${index}`` (required) and
   ``KIMI_BASE_URL_${index}`` (optional ``--base-url`` override) from
   ``.secret_keys/.secret_ignore`` and print the key unmasked.
3. Ensure the CLI is installed (Linux): run the official native installer
   directly (no apt update, no install-library pnpm permission fixing),
   add the slot bin dir to PATH, source the slot ``.bashrc``, and link the
   binary into ``/usr/local/bin`` so ``kimi`` is available to all users.
   Every step is idempotent.
4. Offer an upgrade prompt [y/N] (default N) when the installed CLI lags
   the latest published version; the upgrade re-runs the official native
   installer so the ``/usr/local/bin`` link stays valid.
5. Prompt for the model [1-4] with a 5-second auto-select timeout
   (default 1 = kimi k3 256K / ``k3-256k``; 2 = k3 1M;
   3 = kimi-for-coding / kimi2.8 preview;
   4 = kimi-for-coding-highspeed / kimi2.7 code highspeed).
6. Configure the Kimi For Coding provider non-interactively via the
   official ``kimi provider catalog add kimi-for-coding --api-key ...
   --default-model ...`` command; on failure print /provider manual steps
   with the unmasked key.
7. Force ``default_permission_mode = "auto"`` in config.toml and launch
   ``kimi --auto`` (Never Ask) so no "Approve once" prompts appear.
8. On desktop systems, offer Chrome MCP (apps/mcp-chrome) installation
   [Y/n] (default Y); skipped silently when already installed, and the
   first install builds missing artifacts automatically.
"""

from typing import List, Dict, Any


class KimiLauncherSectionGenerator:
    """Generate kimi${index} launchers (kimiyolo-style, per-slot isolated)."""

    PROVIDER_ID = "kimi-for-coding"
    NPM_PACKAGE = "@moonshot-ai/kimi-code@latest"
    DEFAULT_MODEL = "k3-256k"

    def generate_ps1(self, display_name: str, file_number: int,
                     variables: List[Dict[str, Any]], command_prefix: str) -> str:
        """Generate the Windows PowerShell kimi launcher script."""
        return (
            _PS1_TEMPLATE
            .replace("@@DISPLAY_NAME@@", display_name)
            .replace("@@FILE_NUMBER@@", str(file_number))
            .replace("@@PROVIDER_ID@@", self.PROVIDER_ID)
            .replace("@@NPM_PACKAGE@@", self.NPM_PACKAGE)
            .replace("@@DEFAULT_MODEL@@", self.DEFAULT_MODEL)
        )

    def generate_sh(self, display_name: str, file_number: int,
                    variables: List[Dict[str, Any]], command_prefix: str) -> str:
        """Generate the Linux bash kimi launcher script."""
        return (
            _SH_TEMPLATE
            .replace("@@DISPLAY_NAME@@", display_name)
            .replace("@@FILE_NUMBER@@", str(file_number))
            .replace("@@PROVIDER_ID@@", self.PROVIDER_ID)
            .replace("@@NPM_PACKAGE@@", self.NPM_PACKAGE)
            .replace("@@DEFAULT_MODEL@@", self.DEFAULT_MODEL)
        )


_PS1_TEMPLATE = r'''# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# @@DISPLAY_NAME@@ Launch Script #@@FILE_NUMBER@@ [Kimi For Coding]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Flow: isolate profile (D:\.tmp\Users\Kimi@@FILE_NUMBER@@) -> load secrets
#   -> pnpm upgrade prompt [y/N] -> model selection [1-4] (default 1, 5s timeout)
#   -> kimi provider catalog add @@PROVIDER_ID@@ (non-interactive provider setup)
#   -> config.toml default_permission_mode = "auto" (no approve prompts)
#   -> Chrome MCP install prompt [Y/n] (skipped when already installed)
#   -> launch kimi --auto.
# Secrets: KIMI_API_KEY_@@FILE_NUMBER@@ (required),
#   KIMI_BASE_URL_@@FILE_NUMBER@@ (optional --base-url override).

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptPath = $null
$scriptsDirPath = $null
$coreNodePath = $null
$shellsWinPath = $null
$winCommonDirPath = $null
$windowsPathFunctionScript = $null
$serviceContractScript = $null
$kimiUserBaseDirPath = "D:\.tmp\Users"
$kimiUserDirPath = $null
$kimiSecretDirPath = $null
$kimiApiKeySecretPath = $null
$kimiBaseUrlSecretPath = $null
$kimiApiKey = ""
$kimiBaseUrl = ""
$kimiCodeHomeCandidatePath = $null
$kimiCodeHomePath = $null
$kimiConfigTomlPath = $null
$kimiMcpConfigPath = $null
$permissionLine = 'default_permission_mode = "auto"'
$permissionFound = $false
$configLines = @()
$configLineIndex = 0
$utf8Encoding = $null
$mcpChromePath = $null
$mcpChromeNodeModulesPath = $null
$mcpChromeSharedArtifactPath = $null
$mcpChromeNativeArtifactPath = $null
$mcpChromeExtensionManifestPath = $null
$mcpChromeRegisterScriptPath = $null
$mcpChromeEnsureWinBinScriptPath = $null
$mcpChromeSupervisorScriptPath = $null
$mcpChromeNeedsDependencies = $false
$mcpChromeNeedsBuild = $false
$mcpChromeInstalled = $false
$mcpChromeSetup = $false
$mcpChromeJustInstalled = $false
$mcpChromeHost = $null
$mcpChromeUrl = $null
$mcpChromePort = 0
$mcpChromePortReady = $false
$mcpChromePortWaitCount = 0
$mcpChromePython = $null
$mcpChromeSupervisorArgs = @()
$existingMcpJsonText = ""
$mcpConfig = $null
$mcpServersProperty = $null
$mcpServers = $null
$chromeMcpConfig = $null
$chromeMcpProperty = $null
$mcpJson = $null
$previousLocation = $null
$modelPick = $null
$modelDeadline = $null
$modelKey = $null
$mcpInstallChoice = $null
$pnpmCommand = $null
$aiCliProvisionCommonScript = $null
$nodeCommand = $null
$kimiCommand = $null
$kimiModel = "@@DEFAULT_MODEL@@"
$kimiModelLabel = "kimi k3 256K"
$providerArgs = @()
$providerExitCode = 0
$kimiArgs = @("--auto")
$displayArgs = $null

$scriptPath = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($scriptPath)) {
    $scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
}
$scriptsDirPath = Split-Path $scriptPath -Parent
$coreNodePath = Split-Path $scriptsDirPath -Parent
$shellsWinPath = Join-Path $scriptsDirPath "shells"
$shellsWinPath = Join-Path $shellsWinPath "win"
$winCommonDirPath = Join-Path $shellsWinPath "win_common"
$windowsPathFunctionScript = Join-Path $winCommonDirPath "WindowsPathFunction.ps1"
$serviceContractScript = Join-Path $winCommonDirPath "ServiceContract.ps1"
. $windowsPathFunctionScript
. $serviceContractScript
Set-CoreNodePaths

$mcpChromePath = Join-Path $coreNodePath "apps"
$mcpChromePath = Join-Path $mcpChromePath "mcp-chrome"
$mcpChromeNodeModulesPath = Join-Path $mcpChromePath "node_modules"
$mcpChromeSharedArtifactPath = Join-Path $mcpChromePath "packages"
$mcpChromeSharedArtifactPath = Join-Path $mcpChromeSharedArtifactPath "shared"
$mcpChromeSharedArtifactPath = Join-Path $mcpChromeSharedArtifactPath "dist"
$mcpChromeSharedArtifactPath = Join-Path $mcpChromeSharedArtifactPath "index.js"
$mcpChromeNativeArtifactPath = Join-Path $mcpChromePath "app"
$mcpChromeNativeArtifactPath = Join-Path $mcpChromeNativeArtifactPath "native-server"
$mcpChromeNativeArtifactPath = Join-Path $mcpChromeNativeArtifactPath "dist"
$mcpChromeNativeArtifactPath = Join-Path $mcpChromeNativeArtifactPath "index.js"
$mcpChromeExtensionManifestPath = Join-Path $mcpChromePath ".output"
$mcpChromeExtensionManifestPath = Join-Path $mcpChromeExtensionManifestPath "build_extension"
$mcpChromeExtensionManifestPath = Join-Path $mcpChromeExtensionManifestPath "manifest.json"
$mcpChromeRegisterScriptPath = Join-Path $mcpChromePath "scripts"
$mcpChromeEnsureWinBinScriptPath = Join-Path $mcpChromeRegisterScriptPath "ensure_win_bin.ps1"
$mcpChromeSupervisorScriptPath = Join-Path $mcpChromeRegisterScriptPath "service_supervisor.py"
$mcpChromeRegisterScriptPath = Join-Path $mcpChromeRegisterScriptPath "register-local-dev.cjs"
$mcpChromeHost = Get-ServiceContractHost -Name "loopback"
$mcpChromePort = Get-ServiceContractPort -Name "mcp_chrome"
$mcpChromeUrl = New-ServiceContractUrl -Protocol "http" -HostName $mcpChromeHost -Port $mcpChromePort -Path "mcp"
$mcpChromePython = (Resolve-Path -LiteralPath $Global:PYTHON_EXE_PATH).Path

# Isolated per-slot user profile: D:\.tmp\Users\Kimi@@FILE_NUMBER@@
$kimiUserDirPath = Join-Path $kimiUserBaseDirPath "Kimi@@FILE_NUMBER@@"
if (-not (Test-Path -LiteralPath $kimiUserDirPath)) {
    New-Item -ItemType Directory -Path $kimiUserDirPath -Force | Out-Null
}
$env:USERPROFILE = $kimiUserDirPath
$env:HOME = $kimiUserDirPath
$env:USER_HOME = $kimiUserDirPath
$env:HOMEPATH = $kimiUserDirPath
$env:USER_DIR = $kimiUserDirPath
Write-Host "[INFO] User Profile: $kimiUserDirPath" -ForegroundColor White

if ([string]::IsNullOrWhiteSpace($env:KIMI_CODE_HOME)) {
    $kimiCodeHomeCandidatePath = Join-Path $kimiUserDirPath ".kimi-code"
} elseif ([System.IO.Path]::IsPathRooted($env:KIMI_CODE_HOME)) {
    $kimiCodeHomeCandidatePath = $env:KIMI_CODE_HOME
} else {
    $kimiCodeHomeCandidatePath = Join-Path (Get-Location).Path $env:KIMI_CODE_HOME
}
if (-not (Test-Path -LiteralPath $kimiCodeHomeCandidatePath)) {
    New-Item -ItemType Directory -Path $kimiCodeHomeCandidatePath -Force | Out-Null
}
$kimiCodeHomePath = (Resolve-Path -LiteralPath $kimiCodeHomeCandidatePath).Path
$kimiConfigTomlPath = Join-Path $kimiCodeHomePath "config.toml"
$kimiMcpConfigPath = Join-Path $kimiCodeHomePath "mcp.json"

$kimiSecretDirPath = Join-Path $coreNodePath ".secret_keys"
$kimiSecretDirPath = Join-Path $kimiSecretDirPath ".secret_ignore"
$kimiApiKeySecretPath = Join-Path $kimiSecretDirPath "KIMI_API_KEY_@@FILE_NUMBER@@"
$kimiBaseUrlSecretPath = Join-Path $kimiSecretDirPath "KIMI_BASE_URL_@@FILE_NUMBER@@"

function Read-KimiSecretFile {
    param([string]$FilePath)
    $value = ""
    if (-not (Test-Path -LiteralPath $FilePath)) {
        return $value
    }
    try {
        $bytes = [System.IO.File]::ReadAllBytes($FilePath)
        if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
            $bytes = $bytes[3..($bytes.Length - 1)]
        }
        $content = [System.Text.Encoding]::UTF8.GetString($bytes)
        foreach ($line in ($content -split "`r?`n")) {
            $trimmedLine = $line.Trim()
            if ($trimmedLine) {
                $value = $trimmedLine
                break
            }
        }
    } catch {
        $value = ""
    }
    return $value
}

$kimiApiKey = Read-KimiSecretFile -FilePath $kimiApiKeySecretPath
$kimiBaseUrl = Read-KimiSecretFile -FilePath $kimiBaseUrlSecretPath

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "kimi@@FILE_NUMBER@@.ps1" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan

$kimiCommand = Get-Command kimi -ErrorAction SilentlyContinue
if ($null -eq $kimiCommand) {
    throw "kimi is not available on PATH."
}
$pnpmCommand = Get-Command pnpm -ErrorAction SilentlyContinue
$nodeCommand = Get-Command node -ErrorAction SilentlyContinue

Write-Host "[INFO] KIMI_API_KEY_@@FILE_NUMBER@@: $(if ([string]::IsNullOrWhiteSpace($kimiApiKey)) { "[empty]" } else { $kimiApiKey })" -ForegroundColor White
Write-Host "[INFO] KIMI_BASE_URL_@@FILE_NUMBER@@: $(if ([string]::IsNullOrWhiteSpace($kimiBaseUrl)) { "[empty]" } else { $kimiBaseUrl })" -ForegroundColor White
if ([string]::IsNullOrWhiteSpace($kimiApiKey)) {
    Write-Host "[WARN] KIMI_API_KEY_@@FILE_NUMBER@@ is empty; provider setup will fail." -ForegroundColor Yellow
}

# Version check + optional upgrade, shared with every other launcher
# (scripts/shells/win/win_common/AiCliProvisionCommon.ps1): prompts only when a
# newer version is published, defaults to N and auto-skips after 5 seconds.
$aiCliProvisionCommonScript = Join-Path $winCommonDirPath "AiCliProvisionCommon.ps1"
. $aiCliProvisionCommonScript
Invoke-AiCliUpgradePrompt -Tool "kimi"

# Model selection (default 1 = kimi k3 256K / @@DEFAULT_MODEL@@; auto-selects after 5s).
Write-Host "Select model (default 1 = kimi k3 256K / @@DEFAULT_MODEL@@; auto-select in 5 seconds):" -ForegroundColor Yellow
Write-Host "  [1] kimi k3 256K (k3-256k)" -ForegroundColor White
Write-Host "  [2] kimi k3 1M (k3)" -ForegroundColor White
Write-Host "  [3] kimi2.8 preview (kimi-for-coding, 1M)" -ForegroundColor White
Write-Host "  [4] kimi2.7 code highspeed (kimi-for-coding-highspeed, 256K)" -ForegroundColor White
Write-Host "Model number [1-4] (Enter or timeout = 1): " -ForegroundColor Yellow -NoNewline
$modelDeadline = (Get-Date).AddSeconds(5)
while ((Get-Date) -lt $modelDeadline) {
    if ([Console]::KeyAvailable) {
        $modelKey = [Console]::ReadKey($true)
        if ($modelKey.Key -ne [ConsoleKey]::Enter) {
            $modelPick = [string]$modelKey.KeyChar
            Write-Host $modelPick
        }
        break
    }
    Start-Sleep -Milliseconds 100
}
while ([Console]::KeyAvailable) {
    [Console]::ReadKey($true) | Out-Null
}
if ([string]::IsNullOrWhiteSpace($modelPick)) {
    Write-Host "1 (auto)"
}
switch ($modelPick) {
    "2" { $kimiModel = "k3"; $kimiModelLabel = "kimi k3 1M" }
    "3" { $kimiModel = "kimi-for-coding"; $kimiModelLabel = "kimi2.8 preview" }
    "4" { $kimiModel = "kimi-for-coding-highspeed"; $kimiModelLabel = "kimi2.7 code highspeed" }
    default { $kimiModel = "@@DEFAULT_MODEL@@"; $kimiModelLabel = "kimi k3 256K" }
}
Write-Host "[INFO] Model: $kimiModelLabel ($kimiModel)" -ForegroundColor White

# Non-interactive provider setup (official kimi provider command).
if (-not [string]::IsNullOrWhiteSpace($kimiApiKey)) {
    $providerArgs = @("provider", "catalog", "add", "@@PROVIDER_ID@@", "--api-key", $kimiApiKey, "--default-model", $kimiModel)
    if (-not [string]::IsNullOrWhiteSpace($kimiBaseUrl)) {
        $providerArgs += @("--base-url", $kimiBaseUrl)
    }
    & $kimiCommand.Source @providerArgs
    $providerExitCode = $LASTEXITCODE
    if ($providerExitCode -ne 0) {
        Write-Host "[WARN] Automatic provider setup failed (exit $providerExitCode)." -ForegroundColor Yellow
        Write-Host "[INFO] Manual setup: run kimi, type /provider, choose Known third-party -> Kimi For Coding," -ForegroundColor White
        Write-Host "[INFO]   and paste this key: $kimiApiKey" -ForegroundColor White
    } else {
        Write-Host "[INFO] Provider @@PROVIDER_ID@@ configured (default model: $kimiModel)." -ForegroundColor Green
    }
} else {
    Write-Host "[INFO] Manual setup: run kimi, type /provider, choose Known third-party -> Kimi For Coding," -ForegroundColor White
    Write-Host "[INFO]   and paste the key saved via the environment manager." -ForegroundColor White
}

# Permission mode: Never Ask (disables "Approve once" prompts) by default.
$utf8Encoding = New-Object System.Text.UTF8Encoding($false)
if (Test-Path -LiteralPath $kimiConfigTomlPath) {
    $configLines = [System.IO.File]::ReadAllLines($kimiConfigTomlPath)
    $permissionFound = $false
    for ($configLineIndex = 0; $configLineIndex -lt $configLines.Count; $configLineIndex++) {
        if ($configLines[$configLineIndex] -match '^\s*default_permission_mode\s*=') {
            $configLines[$configLineIndex] = $permissionLine
            $permissionFound = $true
            break
        }
    }
    if (-not $permissionFound) {
        $configLines = @($permissionLine) + $configLines
    }
    [System.IO.File]::WriteAllLines($kimiConfigTomlPath, [string[]]$configLines, $utf8Encoding)
} else {
    [System.IO.File]::WriteAllText($kimiConfigTomlPath, $permissionLine + "`r`n", $utf8Encoding)
}
Write-Host "[INFO] Permission mode: auto (Never Ask; approve prompts disabled) in $kimiConfigTomlPath" -ForegroundColor Green

# Chrome MCP (apps/mcp-chrome): skip silently when already installed,
# otherwise offer install [Y/n] (default Y); first install builds artifacts.
$mcpChromeNeedsDependencies = -not (Test-Path -LiteralPath $mcpChromeNodeModulesPath)
$mcpChromeNeedsBuild = (-not (Test-Path -LiteralPath $mcpChromeSharedArtifactPath)) -or
    (-not (Test-Path -LiteralPath $mcpChromeNativeArtifactPath)) -or
    (-not (Test-Path -LiteralPath $mcpChromeExtensionManifestPath))
$mcpChromeInstalled = $false
if ((Test-Path -LiteralPath $kimiMcpConfigPath) -and (-not $mcpChromeNeedsBuild)) {
    $existingMcpJsonText = [System.IO.File]::ReadAllText($kimiMcpConfigPath)
    if ($existingMcpJsonText -match '"chrome"') {
        $mcpChromeInstalled = $true
    }
}
if ($mcpChromeInstalled) {
    Write-Host "[INFO] Chrome MCP already installed; skipping install prompt." -ForegroundColor Green
    $mcpChromeSetup = $true
} else {
    Write-Host "Install Chrome MCP (apps/mcp-chrome)? [Y/n]: " -ForegroundColor Yellow -NoNewline
    $mcpInstallChoice = Read-Host
    if ([string]::IsNullOrWhiteSpace($mcpInstallChoice) -or ($mcpInstallChoice -eq "y") -or ($mcpInstallChoice -eq "Y")) {
        if ($null -eq $nodeCommand) {
            throw "node is required to install Chrome MCP."
        }
        if (($mcpChromeNeedsDependencies -or $mcpChromeNeedsBuild) -and ($null -eq $pnpmCommand)) {
            throw "pnpm is required to install Chrome MCP."
        }
        Write-Host "[INFO] Ensuring Chrome MCP is installed..." -ForegroundColor Cyan
        $previousLocation = Get-Location
        try {
            Set-Location -LiteralPath $mcpChromePath
            if ($mcpChromeNeedsDependencies) {
                Write-Host "[INFO] Installing Chrome MCP dependencies..." -ForegroundColor Cyan
                & $pnpmCommand.Source install
            }
            if ($mcpChromeNeedsBuild) {
                & $mcpChromeEnsureWinBinScriptPath -WorkspaceRoot $mcpChromePath
                Write-Host "[INFO] Building missing Chrome MCP artifacts..." -ForegroundColor Cyan
                & $pnpmCommand.Source run build:all
            }
            & $nodeCommand.Source $mcpChromeRegisterScriptPath
        } finally {
            Set-Location -LiteralPath $previousLocation
        }
        $mcpChromeSetup = $true
        $mcpChromeJustInstalled = $true
    } else {
        Write-Host "[INFO] Chrome MCP install skipped." -ForegroundColor DarkGray
    }
}

if ($mcpChromeSetup) {
    if (Test-Path -LiteralPath $kimiMcpConfigPath) {
        $mcpConfig = Get-Content -Raw -LiteralPath $kimiMcpConfigPath | ConvertFrom-Json
    } else {
        $mcpConfig = [PSCustomObject]@{}
    }
    if ($null -eq $mcpConfig) {
        $mcpConfig = [PSCustomObject]@{}
    }
    $mcpServersProperty = $mcpConfig.PSObject.Properties["mcpServers"]
    if ($null -eq $mcpServersProperty) {
        $mcpServers = [PSCustomObject]@{}
        $mcpConfig | Add-Member -MemberType NoteProperty -Name "mcpServers" -Value $mcpServers
    } elseif ($null -eq $mcpServersProperty.Value) {
        $mcpServers = [PSCustomObject]@{}
        $mcpServersProperty.Value = $mcpServers
    } else {
        $mcpServers = $mcpServersProperty.Value
    }
    $chromeMcpConfig = [PSCustomObject]@{
        url = $mcpChromeUrl
    }
    $chromeMcpProperty = $mcpServers.PSObject.Properties["chrome"]
    if ($null -eq $chromeMcpProperty) {
        $mcpServers | Add-Member -MemberType NoteProperty -Name "chrome" -Value $chromeMcpConfig
    } else {
        $chromeMcpProperty.Value = $chromeMcpConfig
    }
    $mcpJson = $mcpConfig | ConvertTo-Json -Depth 20
    [System.IO.File]::WriteAllText($kimiMcpConfigPath, $mcpJson, $utf8Encoding)
    Write-Host "[INFO] Chrome MCP registered in Kimi Code: $kimiMcpConfigPath" -ForegroundColor Green

    if ($mcpChromeJustInstalled) {
        $mcpChromePortReady = $null -ne (Get-NetTCPConnection -LocalPort $mcpChromePort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1)
        if ($mcpChromeNeedsBuild -or -not $mcpChromePortReady) {
            $mcpChromeSupervisorArgs = @(
                $mcpChromeSupervisorScriptPath,
                "--project-root", $mcpChromePath,
                "--watch-mode", "dev",
                "--recover-on-start"
            )
        } else {
            $mcpChromeSupervisorArgs = @(
                $mcpChromeSupervisorScriptPath,
                "--project-root", $mcpChromePath,
                "--watch-mode", "dev"
            )
        }
        Write-Host "[INFO] Starting Chrome MCP development service..." -ForegroundColor Cyan
        Start-Process -FilePath $mcpChromePython -ArgumentList $mcpChromeSupervisorArgs -WindowStyle Hidden
        while (-not $mcpChromePortReady -and $mcpChromePortWaitCount -lt 60) {
            Start-Sleep -Milliseconds 500
            $mcpChromePortReady = $null -ne (Get-NetTCPConnection -LocalPort $mcpChromePort -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1)
            $mcpChromePortWaitCount = $mcpChromePortWaitCount + 1
        }
        if ($mcpChromePortReady) {
            Write-Host ("[INFO] Chrome MCP is listening on {0}:{1}." -f $mcpChromeHost, $mcpChromePort) -ForegroundColor Green
        } else {
            Write-Host "[WARN] Chrome MCP did not become ready; reload the unpacked extension once." -ForegroundColor Yellow
        }
    } else {
        Write-Host "[INFO] Chrome MCP already installed; skipping supervisor start." -ForegroundColor DarkGray
    }
}

$displayArgs = if ($args.Count -gt 0) {
    [string]::Format("; extra args: {0}", ($args -join " "))
} else {
    ""
}

Write-Host "[INFO] Launch: kimi --auto (Never Ask mode; provider @@PROVIDER_ID@@, model $kimiModel)$displayArgs" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

& $kimiCommand.Source @kimiArgs @args
'''


_SH_TEMPLATE = r'''#!/bin/bash

# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\..\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# @@DISPLAY_NAME@@ Launch Script #@@FILE_NUMBER@@ [Kimi For Coding]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Flow: isolate profile (/var/_core_node/Users/Kimi@@FILE_NUMBER@@) -> load secrets
#   -> ensure kimi installed (official native installer; no apt update, no
#      install-library permission fixing; linked into /usr/local/bin for all
#      users; idempotent)
#   -> upgrade prompt [y/N] -> model selection [1-4] (default 1, 5s timeout)
#   -> kimi provider catalog add @@PROVIDER_ID@@ (non-interactive provider setup)
#   -> config.toml default_permission_mode = "auto" (no approve prompts)
#   -> Chrome MCP install prompt [Y/n] (desktop only; skipped when installed)
#   -> launch kimi --auto.
# Secrets: KIMI_API_KEY_@@FILE_NUMBER@@ (required),
#   KIMI_BASE_URL_@@FILE_NUMBER@@ (optional --base-url override).

model_pick=""
mcp_install_choice=""
kimi_installer_url="https://code.kimi.com/kimi-code/install.sh"
ai_cli_provision_common_path=""
script_dir_path=""
script_source_path=""
scripts_dir_path=""
core_node_path=""
kimi_user_dir=""
kimi_code_home_path=""
kimi_config_toml_path=""
kimi_mcp_config_path=""
kimi_slot_bin_path=""
kimi_local_bin_link_path=""
kimi_secret_dir_path=""
kimi_api_key=""
kimi_base_url=""
kimi_model="@@DEFAULT_MODEL@@"
kimi_model_label="kimi k3 256K"
mcp_chrome_path=""
mcp_chrome_node_modules_path=""
mcp_chrome_shared_artifact_path=""
mcp_chrome_native_artifact_path=""
mcp_chrome_extension_manifest_path=""
mcp_chrome_register_script_path=""
mcp_chrome_supervisor_script_path=""
mcp_chrome_dev_log_path=""
mcp_chrome_linux_common_dir=""
mcp_chrome_gvar_common_path=""
mcp_chrome_venv_python_common_path=""
mcp_chrome_service_contract_common_path=""
mcp_chrome_python_path=""
mcp_chrome_url=""
mcp_chrome_port=""
mcp_chrome_port_ready=0
mcp_chrome_port_wait_count=0
mcp_chrome_needs_build=0
mcp_chrome_installed=0
mcp_chrome_setup=0
mcp_chrome_just_installed=0
mcp_chrome_enabled=0
kimi_args=(--auto)

script_source_path="${BASH_SOURCE[0]}"
if [ -L "$script_source_path" ]; then
    script_source_path="$(readlink -f "$script_source_path" 2>/dev/null || echo "$script_source_path")"
fi
script_dir_path="$(cd "$(dirname "$script_source_path")" && pwd)"
scripts_dir_path="$(dirname "$script_dir_path")"
core_node_path="$(dirname "$scripts_dir_path")"
mcp_chrome_path="$core_node_path/apps/mcp-chrome"
mcp_chrome_node_modules_path="$mcp_chrome_path/node_modules"
mcp_chrome_shared_artifact_path="$mcp_chrome_path/packages/shared/dist/index.js"
mcp_chrome_native_artifact_path="$mcp_chrome_path/app/native-server/dist/index.js"
mcp_chrome_register_script_path="$mcp_chrome_path/scripts/register-local-dev.cjs"
mcp_chrome_supervisor_script_path="$mcp_chrome_path/scripts/service_supervisor.py"
mcp_chrome_dev_log_path="/tmp/mcp-chrome-kimi@@FILE_NUMBER@@.log"
mcp_chrome_linux_common_dir="$core_node_path/scripts/shells/linux/common"
mcp_chrome_gvar_common_path="$mcp_chrome_linux_common_dir/gvar_common.sh"
mcp_chrome_venv_python_common_path="$mcp_chrome_linux_common_dir/venv_python_common.sh"
mcp_chrome_service_contract_common_path="$mcp_chrome_linux_common_dir/service_contract_common.sh"
source "$mcp_chrome_gvar_common_path"
source "$mcp_chrome_venv_python_common_path"
source "$mcp_chrome_service_contract_common_path"
mcp_chrome_extension_manifest_path="$mcp_chrome_path/$(sc_require mcp_chrome.build_output_dir)/$(sc_require mcp_chrome.extension_dir)/manifest.json"
mcp_chrome_port="$(sc_require ports.mcp_chrome)"
mcp_chrome_url="http://$(sc_require hosts.loopback):${mcp_chrome_port}/mcp"
mcp_chrome_python_path="$VENV_PYTHON3"
if [ "${HAS_DESKTOP_ENVIRONMENT:-false}" = "true" ]; then
    mcp_chrome_enabled=1
fi

# Isolated per-slot user profile: /var/_core_node/Users/Kimi@@FILE_NUMBER@@
kimi_user_dir="/var/_core_node/Users/Kimi@@FILE_NUMBER@@"
if ! mkdir -p "$kimi_user_dir" 2>/dev/null; then
    kimi_user_dir="$HOME/.kimi_slots/Kimi@@FILE_NUMBER@@"
    mkdir -p "$kimi_user_dir"
fi
export HOME="$kimi_user_dir"
export USER_HOME="$kimi_user_dir"
export USER_DIR="$kimi_user_dir"
echo "[INFO] User Profile: $kimi_user_dir"

kimi_code_home_path="${KIMI_CODE_HOME:-$kimi_user_dir/.kimi-code}"
mkdir -p "$kimi_code_home_path"
kimi_config_toml_path="$kimi_code_home_path/config.toml"
kimi_mcp_config_path="$kimi_code_home_path/mcp.json"
kimi_secret_dir_path="$core_node_path/.secret_keys/.secret_ignore"

kimi_read_secret_file() {
    local file_path="$1"
    local value=""
    local first_bytes=""
    local trimmed_line=""
    if [ ! -f "$file_path" ]; then
        return 0
    fi
    first_bytes="$(head -c 3 "$file_path" 2>/dev/null | od -An -tx1 2>/dev/null | tr -d ' \n' 2>/dev/null || echo "")"
    if [ "$first_bytes" = "efbbbf" ]; then
        while IFS= read -r trimmed_line || [ -n "$trimmed_line" ]; do
            trimmed_line="$(echo "$trimmed_line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            if [ -n "$trimmed_line" ]; then
                value="$trimmed_line"
                break
            fi
        done < <(dd if="$file_path" bs=1 skip=3 2>/dev/null)
    else
        while IFS= read -r trimmed_line || [ -n "$trimmed_line" ]; do
            trimmed_line="$(echo "$trimmed_line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            if [ -n "$trimmed_line" ]; then
                value="$trimmed_line"
                break
            fi
        done < "$file_path"
    fi
    echo "$value"
}

kimi_api_key="$(kimi_read_secret_file "$kimi_secret_dir_path/KIMI_API_KEY_@@FILE_NUMBER@@")"
kimi_base_url="$(kimi_read_secret_file "$kimi_secret_dir_path/KIMI_BASE_URL_@@FILE_NUMBER@@")"

echo ""
echo "============================================================"
echo "kimi@@FILE_NUMBER@@.sh"
echo "============================================================"

kimi_slot_bin_path="$kimi_code_home_path/bin/kimi"
kimi_local_bin_link_path="/usr/local/bin/kimi"

if ! command -v kimi >/dev/null 2>&1; then
    if [ -x "$kimi_slot_bin_path" ]; then
        echo "[INFO] kimi found in the slot profile ($kimi_slot_bin_path); linking it onto PATH."
    elif command -v curl >/dev/null 2>&1; then
        echo "[INFO] kimi is not available on PATH; installing via the official native installer..."
        curl -fsSL "$kimi_installer_url" | bash
        hash -r
    else
        echo "[ERROR] kimi is not available on PATH and curl is missing for the official installer."
        exit 1
    fi
fi

# PATH: prefer the slot bin dir; the installer also registers it in the slot .bashrc.
if [ -x "$kimi_slot_bin_path" ]; then
    case ":$PATH:" in
        *":$kimi_code_home_path/bin:"*) ;;
        *) export PATH="$kimi_code_home_path/bin:$PATH" ;;
    esac
fi
if [ -f "$kimi_user_dir/.bashrc" ]; then
    source "$kimi_user_dir/.bashrc" >/dev/null 2>&1 || true
fi

# Make kimi available to all users via /usr/local/bin (idempotent).
if [ -x "$kimi_slot_bin_path" ] &&
    [ "$(readlink -f "$kimi_local_bin_link_path" 2>/dev/null || echo "")" != "$kimi_slot_bin_path" ]; then
    if [ "$EUID" -eq 0 ]; then
        ln -sf "$kimi_slot_bin_path" "$kimi_local_bin_link_path"
        echo "[INFO] Linked kimi for all users: $kimi_local_bin_link_path -> $kimi_slot_bin_path"
    elif command -v sudo >/dev/null 2>&1 &&
        sudo ln -sf "$kimi_slot_bin_path" "$kimi_local_bin_link_path" 2>/dev/null; then
        echo "[INFO] Linked kimi for all users: $kimi_local_bin_link_path -> $kimi_slot_bin_path"
    else
        echo "[WARN] Could not create $kimi_local_bin_link_path; kimi stays slot-local ($kimi_slot_bin_path)."
    fi
    hash -r
fi

if ! command -v kimi >/dev/null 2>&1; then
    echo "[ERROR] kimi installation did not succeed; kimi is still not available on PATH."
    exit 1
fi

echo "[INFO] KIMI_API_KEY_@@FILE_NUMBER@@: ${kimi_api_key:-[empty]}"
echo "[INFO] KIMI_BASE_URL_@@FILE_NUMBER@@: ${kimi_base_url:-[empty]}"
if [ -z "$kimi_api_key" ]; then
    echo "[WARN] KIMI_API_KEY_@@FILE_NUMBER@@ is empty; provider setup will fail."
fi

# Version check + optional upgrade, shared with every other launcher
# (scripts/shells/linux/common/ai_cli_provision_common.sh): prompts only when a
# newer version is published, defaults to N and auto-skips after 5 seconds.
ai_cli_provision_common_path="$core_node_path/scripts/shells/linux/common/ai_cli_provision_common.sh"
. "$ai_cli_provision_common_path"
ai_cli_upgrade_prompt "kimi"

# Model selection (default 1 = kimi k3 256K / @@DEFAULT_MODEL@@; auto-selects after 5s).
echo "Select model (default 1 = kimi k3 256K / @@DEFAULT_MODEL@@; auto-select in 5 seconds):"
echo "  [1] kimi k3 256K (k3-256k)"
echo "  [2] kimi k3 1M (k3)"
echo "  [3] kimi2.8 preview (kimi-for-coding, 1M)"
echo "  [4] kimi2.7 code highspeed (kimi-for-coding-highspeed, 256K)"
printf '\033[33mModel number [1-4] (Enter or timeout = 1): \033[0m'
read -r -t 5 model_pick || model_pick=""
if [ -z "$model_pick" ]; then
    model_pick="1"
    echo "1 (auto)"
fi
case "$model_pick" in
    2) kimi_model="k3"; kimi_model_label="kimi k3 1M" ;;
    3) kimi_model="kimi-for-coding"; kimi_model_label="kimi2.8 preview" ;;
    4) kimi_model="kimi-for-coding-highspeed"; kimi_model_label="kimi2.7 code highspeed" ;;
    *) kimi_model="@@DEFAULT_MODEL@@"; kimi_model_label="kimi k3 256K" ;;
esac
echo "[INFO] Model: $kimi_model_label ($kimi_model)"

# Non-interactive provider setup (official kimi provider command).
if [ -n "$kimi_api_key" ]; then
    if [ -n "$kimi_base_url" ]; then
        kimi provider catalog add @@PROVIDER_ID@@ --api-key "$kimi_api_key" --default-model "$kimi_model" --base-url "$kimi_base_url"
    else
        kimi provider catalog add @@PROVIDER_ID@@ --api-key "$kimi_api_key" --default-model "$kimi_model"
    fi
    if [ $? -ne 0 ]; then
        echo "[WARN] Automatic provider setup failed."
        echo "[INFO] Manual setup: run kimi, type /provider, choose Known third-party -> Kimi For Coding,"
        echo "[INFO]   and paste this key: $kimi_api_key"
    else
        echo "[INFO] Provider @@PROVIDER_ID@@ configured (default model: $kimi_model)."
    fi
else
    echo "[INFO] Manual setup: run kimi, type /provider, choose Known third-party -> Kimi For Coding,"
    echo "[INFO]   and paste the key saved via the environment manager."
fi

# Permission mode: Never Ask (disables "Approve once" prompts) by default.
if [ -f "$kimi_config_toml_path" ] && grep -qE '^[[:space:]]*default_permission_mode[[:space:]]*=' "$kimi_config_toml_path"; then
    sed -i -E 's/^[[:space:]]*default_permission_mode[[:space:]]*=.*/default_permission_mode = "auto"/' "$kimi_config_toml_path"
elif [ -f "$kimi_config_toml_path" ]; then
    printf 'default_permission_mode = "auto"\n' | cat - "$kimi_config_toml_path" > "$kimi_config_toml_path.tmp"
    mv "$kimi_config_toml_path.tmp" "$kimi_config_toml_path"
else
    printf 'default_permission_mode = "auto"\n' > "$kimi_config_toml_path"
fi
echo "[INFO] Permission mode: auto (Never Ask; approve prompts disabled) in $kimi_config_toml_path"

if [ "$mcp_chrome_enabled" -eq 1 ]; then
# Chrome MCP (apps/mcp-chrome): skip silently when already installed,
# otherwise offer install [Y/n] (default Y); first install builds artifacts.
if [ ! -f "$mcp_chrome_shared_artifact_path" ] ||
    [ ! -f "$mcp_chrome_native_artifact_path" ] ||
    [ ! -f "$mcp_chrome_extension_manifest_path" ]; then
    mcp_chrome_needs_build=1
fi
if [ -f "$kimi_mcp_config_path" ] && [ "$mcp_chrome_needs_build" -eq 0 ] &&
    grep -q '"chrome"' "$kimi_mcp_config_path" 2>/dev/null; then
    mcp_chrome_installed=1
fi
if [ "$mcp_chrome_installed" -eq 1 ]; then
    echo "[INFO] Chrome MCP already installed; skipping install prompt."
    mcp_chrome_setup=1
else
    printf '\033[33mInstall Chrome MCP (apps/mcp-chrome)? [Y/n]: \033[0m'
    read -r mcp_install_choice || mcp_install_choice=""
    if [ -z "$mcp_install_choice" ] || [ "$mcp_install_choice" = "y" ] || [ "$mcp_install_choice" = "Y" ]; then
        if ! command -v node >/dev/null 2>&1; then
            echo "[ERROR] node is required to install Chrome MCP."
            exit 1
        fi
        if { [ ! -d "$mcp_chrome_node_modules_path" ] || [ "$mcp_chrome_needs_build" -eq 1 ]; } &&
            ! command -v pnpm >/dev/null 2>&1; then
            echo "[ERROR] pnpm is required to install Chrome MCP."
            exit 1
        fi
        echo "[INFO] Ensuring Chrome MCP is installed..."
        if [ ! -d "$mcp_chrome_node_modules_path" ]; then
            echo "[INFO] Installing Chrome MCP dependencies..."
            (
                cd "$mcp_chrome_path"
                pnpm install
            )
        fi
        if [ "$mcp_chrome_needs_build" -eq 1 ]; then
            echo "[INFO] Building missing Chrome MCP artifacts..."
            (
                cd "$mcp_chrome_path"
                pnpm run build:all
            )
        fi
        (
            cd "$mcp_chrome_path"
            node "$mcp_chrome_register_script_path"
        )
        mcp_chrome_setup=1
        mcp_chrome_just_installed=1
    else
        echo "[INFO] Chrome MCP install skipped."
    fi
fi

if [ "$mcp_chrome_setup" -eq 1 ]; then
    mkdir -p "$kimi_code_home_path"
    node - "$kimi_mcp_config_path" "$mcp_chrome_url" <<'NODE'
const fs = require("node:fs");
const configPath = process.argv[2];
const chromeUrl = process.argv[3];
const config = fs.existsSync(configPath)
    ? JSON.parse(fs.readFileSync(configPath, "utf8"))
    : {};

config.mcpServers ??= {};
config.mcpServers.chrome = { url: chromeUrl };
fs.writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
NODE
    echo "[INFO] Chrome MCP registered in Kimi Code: $kimi_mcp_config_path"

    if [ "$mcp_chrome_just_installed" -eq 1 ]; then
        if (echo >"/dev/tcp/127.0.0.1/$mcp_chrome_port") >/dev/null 2>&1; then
            mcp_chrome_port_ready=1
        fi
        echo "[INFO] Ensuring the singleton Chrome MCP supervisor is running..."
        if [ "$mcp_chrome_needs_build" -eq 1 ] || [ "$mcp_chrome_port_ready" -eq 0 ]; then
            "$mcp_chrome_python_path" "$mcp_chrome_supervisor_script_path" --project-root "$mcp_chrome_path" --watch-mode dev --recover-on-start >"$mcp_chrome_dev_log_path" 2>&1 &
        else
            "$mcp_chrome_python_path" "$mcp_chrome_supervisor_script_path" --project-root "$mcp_chrome_path" --watch-mode dev >"$mcp_chrome_dev_log_path" 2>&1 &
        fi
        while [ "$mcp_chrome_port_ready" -eq 0 ] && [ "$mcp_chrome_port_wait_count" -lt 60 ]; do
            sleep 0.5
            if (echo >"/dev/tcp/127.0.0.1/$mcp_chrome_port") >/dev/null 2>&1; then
                mcp_chrome_port_ready=1
            fi
            mcp_chrome_port_wait_count=$((mcp_chrome_port_wait_count + 1))
        done
        if [ "$mcp_chrome_port_ready" -eq 1 ]; then
            echo "[INFO] Chrome MCP is listening on 127.0.0.1:$mcp_chrome_port."
        else
            echo "[WARN] Chrome MCP did not become ready; reload the unpacked extension once."
        fi
    else
        echo "[INFO] Chrome MCP already installed; skipping supervisor start."
    fi
fi
else
    echo "[INFO] No desktop environment; skipping Chrome MCP setup (no install, no build, no registration)."
fi

echo "[INFO] Launch: kimi --auto (Never Ask mode; provider @@PROVIDER_ID@@, model $kimi_model); extra args: $#"
echo "============================================================"
echo ""

exec kimi "${kimi_args[@]}" "$@"
'''
