"""
Pi Launcher Generator.

Generates standalone piark${index}.ps1 / piark${index}.sh launchers by using
piyolo.sh and piyolo.ps1 as templates. The piyolo mode argument parser is
stripped so every piark launcher can only run Pi with the Volcengine coding
plan provider; passing a mode name such as 'claude' never switches harness.
"""

import re
from typing import List, Dict, Any

from utils.common_utils import get_linuxenvs_dir, get_winenvs_dir

SH_MODE_ARG_PARSER = re.compile(
    r'if \[ "\$#" -gt 0 \]; then\n'
    r'[ \t]*case "\$1" in\n'
    r'[ \t]*[^)\n]*\)\n'
    r'[ \t]*MODE="\$1"\n'
    r'[ \t]*shift\n'
    r'[ \t]*;;\n'
    r'[ \t]*esac\n'
    r'fi\n'
)

PS1_MODE_ARG_PARSER = re.compile(
    r'if \(\$args\.Count -gt 0 -and \$supportedModes -contains '
    r'\$args\[0\]\.ToLowerInvariant\(\)\) \{.*?\}\s*else \{.*?\}',
    re.DOTALL,
)


class PiLauncherSectionGenerator:
    """Generate standalone piark${index} launchers."""

    def generate_sh(self, display_name: str, file_number: int,
                    variables: List[Dict[str, Any]], command_prefix: str) -> str:
        """Generate the Linux bash piark -> Pi launcher script."""
        linuxenvs_dir = get_linuxenvs_dir()
        piyolo_sh_path = linuxenvs_dir / "piyolo.sh"
        
        if not piyolo_sh_path.exists():
            raise FileNotFoundError(f"Template not found: {piyolo_sh_path}")
            
        content = piyolo_sh_path.read_text(encoding='utf-8')

        if 'MODE="auto"' not in content:
            raise ValueError('piyolo.sh no longer defines the default MODE; update the piark generator')

        # Pin the mode: piark always runs Pi on the Volcengine coding plan.
        content = content.replace('MODE="auto"', 'MODE="volc-coding"')

        # Remove argument parsing so the mode can never be overridden.
        content = SH_MODE_ARG_PARSER.sub('', content, count=1)
        if 'MODE="$1"' in content:
            raise ValueError('piyolo.sh mode argument parser was not stripped; update SH_MODE_ARG_PARSER')

        # Replace secrets index
        content = content.replace('ARK_API_KEY_1', f'ARK_API_KEY_{file_number}')
        content = content.replace('ARKCLI_API_KEY_1', f'ARKCLI_API_KEY_{file_number}')
        content = content.replace('ARKCLI_API_1', f'ARKCLI_API_{file_number}')
        content = content.replace('ARKCLI_MODEL_1', f'ARKCLI_MODEL_{file_number}')
        
        # Add header
        header = f'''#!/bin/bash
# =============================================================================
# {display_name} Launch Script #{file_number} - [piark -> Pi]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Standalone script based on piyolo.sh template.
# =============================================================================
'''
        # Replace the original shebang and rules with our header
        lines = content.split('\n')
        start_idx = 0
        for i, line in enumerate(lines):
            if line.startswith('SCRIPT_SOURCE='):
                start_idx = i
                break
                
        content = header + '\n'.join(lines[start_idx:])
        
        return content

    def generate_ps1(self, display_name: str, file_number: int,
                     variables: List[Dict[str, Any]], command_prefix: str) -> str:
        """Generate the Windows PowerShell piark -> Pi launcher script."""
        winenvs_dir = get_winenvs_dir()
        piyolo_ps1_path = winenvs_dir / "piyolo.ps1"
        
        if not piyolo_ps1_path.exists():
            raise FileNotFoundError(f"Template not found: {piyolo_ps1_path}")
            
        content = piyolo_ps1_path.read_text(encoding='utf-8')

        if "$mode = 'auto'" not in content:
            raise ValueError('piyolo.ps1 no longer defines the default $mode; update the piark generator')

        # Pin the mode: piark always runs Pi on the Volcengine coding plan.
        content = content.replace("$mode = 'auto'", "$mode = 'volc-coding'")

        # Remove argument parsing so the mode can never be overridden.
        content = PS1_MODE_ARG_PARSER.sub('$forwardArgs = @($args)', content, count=1)
        if '$mode = $args[0]' in content:
            raise ValueError('piyolo.ps1 mode argument parser was not stripped; update PS1_MODE_ARG_PARSER')

        # Replace secrets index
        content = content.replace('ARK_API_KEY_1', f'ARK_API_KEY_{file_number}')
        content = content.replace('ARKCLI_API_KEY_1', f'ARKCLI_API_KEY_{file_number}')
        content = content.replace('ARKCLI_API_1', f'ARKCLI_API_{file_number}')
        content = content.replace('ARKCLI_MODEL_1', f'ARKCLI_MODEL_{file_number}')
        
        # Add header
        header = f'''# =============================================================================
# {display_name} Launch Script #{file_number} - [piark -> Pi]
# =============================================================================
# Auto-generated by Special Software Environment Manager.
# Standalone script based on piyolo.ps1 template.
# =============================================================================
'''
        # Replace the original rules with our header
        lines = content.split('\n')
        start_idx = 0
        for i, line in enumerate(lines):
            if line.startswith('Set-StrictMode'):
                start_idx = i
                break
                
        content = header + '\n'.join(lines[start_idx:])
        
        return content
