"""
SSH Command Generator

Generates SSH connection scripts for Windows and Linux.
"""

from typing import Dict


class SSHCommandGenerator:
    """Generates SSH connection scripts"""

    @staticmethod
    def generate_windows_ssh_command(config_name: str, file_number: int, file_name: str = "") -> str:
        """Generate Windows PowerShell SSH connection script"""
        ssh_conn_key = f"SSH_CONNECTION_{file_number}"
        password_key_name = f"SSH_PASSWORD_{file_number}"

        header = f"""# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\\..\\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

<#
.SYNOPSIS
    {config_name} Global File #{file_number}

.DESCRIPTION
    This file is automatically generated by Special Software Environment Manager
    Contains SSH connection setup with encrypted password storage

.NOTES
    - Configuration: {config_name}
    - SSH Connection: Loaded dynamically from secret key {ssh_conn_key}
    - File Number: {file_number}
    - File Name: {file_name}
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
"""

        file_name_display = ""
        if file_name:
            file_name_display = f"""
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Running: {file_name}" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
"""

        path_resolution = """
#region Initialize Path Variables
$scriptActualPath = $PSCommandPath
$item = Get-Item -LiteralPath $PSCommandPath
if ($item -and $item -is [System.IO.FileInfo] -and $item.LinkType) {
    $scriptActualPath = $item.Target
}
$scriptCurrentPath = Split-Path $scriptActualPath -Parent
if (-not $scriptCurrentPath) {
    $scriptCurrentPath = $PSScriptRoot
    if (-not $scriptCurrentPath) {
        $scriptCurrentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
    }
}
$scriptsDirPath = Split-Path $scriptCurrentPath -Parent
$projectRootPath = Split-Path $scriptsDirPath -Parent
$shellsDirPath = Join-Path $scriptsDirPath "shells"
$winDirPath = Join-Path $shellsDirPath "win"
$winCommonDirPath = Join-Path $winDirPath "win_common"
Write-Host "[DEBUG] Script Path: $scriptCurrentPath" -ForegroundColor DarkGray
Write-Host "[DEBUG] Scripts Dir: $scriptsDirPath" -ForegroundColor DarkGray
Write-Host "[DEBUG] Project Root: $projectRootPath" -ForegroundColor DarkGray
#endregion

$windowsPathFunctionScript = Join-Path $winCommonDirPath "WindowsPathFunction.ps1"
. $windowsPathFunctionScript
Set-CoreNodePaths
"""

        load_secret_manager = f"""
#region Load SSH Configuration via PyCore caller
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Loading SSH Configuration" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Ensure GlobalVars loaded so $Global:PYTHON_EXE_PATH / $Global:PYTHON_DIR are available (same as DevInstaller / Run DevInstaller)
$globalVarsPath = Join-Path $winCommonDirPath "GlobalVars.ps1"
. $globalVarsPath

# Resolve Python: prefer GLOBAL PYTHON EXE (DevInstaller), then python.exe in PATH (avoid Store "python" alias)
$pythonExecutable = $null
if ($Global:PYTHON_EXE_PATH -and (Test-Path -LiteralPath $Global:PYTHON_EXE_PATH)) {{
    $pythonExecutable = $Global:PYTHON_EXE_PATH
}} elseif ($Global:PYTHON_DIR -and (Test-Path -LiteralPath $Global:PYTHON_DIR)) {{
    $pythonExeFromDir = Join-Path $Global:PYTHON_DIR "python.exe"
    if (Test-Path -LiteralPath $pythonExeFromDir) {{
        $pythonExecutable = $pythonExeFromDir
    }}
}}
if (-not $pythonExecutable) {{
    $pythonCmd = Get-Command python.exe -ErrorAction SilentlyContinue
    if ($pythonCmd -and $pythonCmd.Source) {{
        $pythonExecutable = $pythonCmd.Source
    }}
}}
if (-not $pythonExecutable) {{
    $pythonCmd = Get-Command python3 -ErrorAction SilentlyContinue
    if ($pythonCmd -and $pythonCmd.Source) {{
        $pythonExecutable = $pythonCmd.Source
    }}
}}
if (-not $pythonExecutable) {{
    Write-Host "[ERROR] Python not found. Cannot load SSH secrets. Run DevInstaller (dd menu -> Run DevInstaller) to install Python, or add python.exe to PATH." -ForegroundColor Red
}}

# Use relative path from script location to project root
$secretReaderScript = Join-Path $projectRootPath "scripts\\pytools\\special_software_env_manager\\secret_read.py"
$fixScriptPath = Join-Path $winCommonDirPath "SecretDecryptionCheck.ps1"
$fixInstruction = "Run dd.cmd (Secret Decryption Fix) or powershell -ExecutionPolicy Bypass -File `"$fixScriptPath`""
Write-Host "[DEBUG] Python executable: $pythonExecutable" -ForegroundColor DarkGray
Write-Host "[DEBUG] Secret reader script: $secretReaderScript" -ForegroundColor DarkGray
Write-Host "[DEBUG] Project root: $projectRootPath" -ForegroundColor DarkGray
function Get-SSHSecret {{
    param([string]$KeyName)
    if (-not $pythonExecutable) {{ return "" }}
    Write-Host "[DEBUG] Loading SSH secret key: $KeyName" -ForegroundColor DarkGray

    $originalLocation = Get-Location
    Set-Location $projectRootPath

    $result = & $pythonExecutable $secretReaderScript $KeyName
    $exitCode = $LASTEXITCODE
    Set-Location $originalLocation

    if ($exitCode -ne 0 -or -not $result) {{
        Write-Host "[WARNING] Secret reader failed for $KeyName" -ForegroundColor Yellow
        Write-Host "[ACTION] $fixInstruction" -ForegroundColor Yellow
        return ""
    }}

    # Note: BOM is already handled by secret_read.py, no need to strip again
    return $result
}}

$sshConnection = Get-SSHSecret "{ssh_conn_key}"
if ($sshConnection) {{
    Write-Host "[SUCCESS] SSH Connection loaded = $sshConnection" -ForegroundColor Green
}} else {{
    Write-Host "[ERROR] SSH_CONNECTION not found" -ForegroundColor Red
    Write-Host "Press any key to exit..." -ForegroundColor Yellow
    $null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

$sshPassword = Get-SSHSecret "{password_key_name}"
if ($sshPassword) {{
    Write-Host "[SUCCESS] SSH password loaded = $sshPassword" -ForegroundColor Green
}} else {{
    Write-Host "[INFO] No password configured (using SSH key authentication)" -ForegroundColor Yellow
}}
#endregion

#region Execute SSH Connection
Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "Connecting to SSH Server" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

if ([string]::IsNullOrWhiteSpace($sshConnection)) {{
    Write-Host "[ERROR] SSH connection string is empty" -ForegroundColor Red
    Write-Host "Press any key to exit..." -ForegroundColor Yellow
    $null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

if ($sshPassword) {{
    # Extract user and host from connection string (e.g. root@1.2.3.4)
    $sshUser = ""
    $sshHost = ""
    if ($sshConnection -match '^(.+)@(.+)$') {{
        $sshUser = $Matches[1]
        $sshHost = $Matches[2]
    }}

    # SSH Key setup guide
    Write-Host ""
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host "  SSH Key Setup Guide (passwordless login)" -ForegroundColor Cyan
    Write-Host "============================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  After login, run these commands on the SERVER to enable" -ForegroundColor White
    Write-Host "  SSH key authentication (no password next time):" -ForegroundColor White
    Write-Host ""
    Write-Host "  --- Step 1: Generate key on LOCAL machine (if not exists) ---" -ForegroundColor Yellow
    Write-Host ""
    $localKeyPath = Join-Path $env:USERPROFILE ".ssh\\id_ed25519"
    $localPubPath = "$localKeyPath.pub"
    Write-Host "  # Check if key already exists:" -ForegroundColor DarkGray
    Write-Host "  if (!(Test-Path `"$localPubPath`")) {{ ssh-keygen -t ed25519 -f `"$localKeyPath`" -N `"`" }}" -ForegroundColor Green
    Write-Host ""
    Write-Host "  --- Step 2: Copy key to server (run on LOCAL) ---" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  # Option A: One-liner (works on all distros):" -ForegroundColor DarkGray
    Write-Host "  type `"$localPubPath`" | ssh $sshConnection `"mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys`"" -ForegroundColor Green
    Write-Host ""
    Write-Host "  # Option B: If ssh-copy-id is available (Git Bash / WSL):" -ForegroundColor DarkGray
    Write-Host "  ssh-copy-id -i `"$localPubPath`" $sshConnection" -ForegroundColor Green
    Write-Host ""
    Write-Host "  --- Step 3: Verify (run on LOCAL) ---" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  ssh $sshConnection `"echo 'SSH key auth OK'`"" -ForegroundColor Green
    Write-Host ""
    Write-Host "  --- Notes ---" -ForegroundColor Yellow
    Write-Host "  * Works on Debian/Ubuntu/CentOS/RHEL/AlmaLinux/Fedora" -ForegroundColor DarkGray
    Write-Host "  * Safe if server already has other keys (appends, not overwrites)" -ForegroundColor DarkGray
    Write-Host "  * Safe if local machine has other keys (ed25519 is separate from rsa)" -ForegroundColor DarkGray
    Write-Host "  * If server has SELinux: ssh $sshConnection `"restorecon -Rv ~/.ssh`"" -ForegroundColor DarkGray
    Write-Host "  * If using custom port: ssh -p PORT $sshConnection" -ForegroundColor DarkGray
    Write-Host ""

    # Display password for copy-paste
    Write-Host "============================================================" -ForegroundColor Yellow
    Write-Host "  SSH PASSWORD (Copy this to clipboard):" -ForegroundColor Yellow
    Write-Host "  $sshPassword" -ForegroundColor Green
    Write-Host "============================================================" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "[INFO] SSH will prompt for password. Please paste the password above when prompted." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Executing: ssh $sshConnection" -ForegroundColor White
    Write-Host ""

    # Execute SSH connection - it will prompt for password
    & ssh $sshConnection
}} else {{
    # No password configured, use SSH key authentication
    Write-Host "[INFO] No password configured, using SSH key authentication" -ForegroundColor Cyan
    Write-Host "Executing: ssh $sshConnection" -ForegroundColor White
    Write-Host ""

    & ssh $sshConnection
}}

Write-Host ""
Write-Host "SSH session ended" -ForegroundColor Cyan
Write-Host ""
Write-Host "Press any key to exit..." -ForegroundColor Yellow
$null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
#endregion
"""

        return f"{header}{file_name_display}{path_resolution}{load_secret_manager}"

    @staticmethod
    def generate_linux_ssh_command(config_name: str, file_number: int, file_name: str = "") -> str:
        """Generate Linux bash SSH connection script"""
        ssh_conn_key = f"SSH_CONNECTION_{file_number}"
        password_key_name = f"SSH_PASSWORD_{file_number}"

        header = f"""#!/bin/bash
# ### AI SPECIAL ATTENTION RULES START ###
# When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
# 1. Write all code in English only.
# 2. Never execute, create, or modify test code.
# 3. Never create or update documentation (*.md).
# 4. Never write summaries during development or thinking process.
# 5. Declare all variables at the beginning of the file.
# 6. For PowerShell (*.ps1) scripts: Do not append strings directly to variables, Do not use relative paths such as "..\\..\\"; instead resolve absolute paths using parent path parsing (Split-Path, Join-Path, or Resolve-Path).
# 7. Do not modify these rules.
# VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
# ### AI SPECIAL ATTENTION RULES END ###

# =============================================================================
# {config_name} Global File #{file_number}
# =============================================================================
#
# Synopsis:
#     SSH Connection Script
#
# Description:
#     This file is automatically generated by Special Software Environment Manager
#     Contains SSH connection setup for Linux systems with encrypted password storage
#
# Notes:
#     - Configuration: {config_name}
#     - SSH Connection: Loaded dynamically from secret key {ssh_conn_key}
#     - File Number: {file_number}
#     - File Name: {file_name}
# =============================================================================

set -e
"""

        file_name_display = ""
        if file_name:
            file_name_display = f"""
echo ""
echo "============================================================"
echo "Running: {file_name}"
echo "============================================================"
echo ""
"""

        path_resolution = """
# =============================================================================
# Initialize Path Variables
# =============================================================================
# Resolve script real path (handle symlinks)
# When script is executed via symlink (e.g., from /usr/local/bin),
# BASH_SOURCE[0] returns symlink path. We need to resolve it to actual
# file path to get correct directory structure.
scriptSource="${BASH_SOURCE[0]}"

# Check if scriptSource is a symlink and resolve it
if [ -L "$scriptSource" ]; then
    # Resolve symlink to actual file path
    scriptSource="$(readlink -f "$scriptSource" 2>/dev/null || echo "$scriptSource")"
fi

# Get absolute path of script directory using cd + pwd for reliability
scriptCurrentPath="$(cd "$(dirname "$scriptSource")" && pwd)"

# Calculate project structure paths
# Expected structure: project_root/scripts/linuxenvs/script.sh
scriptsDirPath="$(cd "$scriptCurrentPath/.." && pwd)"
projectRootPath="$(cd "$scriptsDirPath/.." && pwd)"

echo "[DEBUG] Script Source: $scriptSource"
echo "[DEBUG] Script Path: $scriptCurrentPath"
echo "[DEBUG] Scripts Dir: $scriptsDirPath"
echo "[DEBUG] Project Root: $projectRootPath"
echo ""
"""

        load_secret_manager = f"""
# =============================================================================
# Load SSH Configuration via PyCore
# =============================================================================
echo ""
echo "============================================================"
echo "Loading SSH Configuration"
echo "============================================================"
echo ""

# Detect Python executable
PYTHON_EXECUTABLE=""
if command -v python3 &> /dev/null; then
    PYTHON_EXECUTABLE="python3"
elif command -v python &> /dev/null; then
    PYTHON_EXECUTABLE="python"
else
    echo "[ERROR] Python not found. Cannot load SSH secrets."
    exit 1
fi

SECRET_MANAGER_SCRIPT="$projectRootPath/pycore/pyfoundations/secret_manager.py"
echo "[DEBUG] Python executable: $PYTHON_EXECUTABLE"
echo "[DEBUG] Secret manager script: $SECRET_MANAGER_SCRIPT"
echo ""

# Function to get secret value
get_secret_value() {{
    local key_name="$1"
    echo "[DEBUG] Loading secret key: $key_name" >&2

    # Switch to project root for Python execution
    cd "$projectRootPath"

    local value
    value=$("$PYTHON_EXECUTABLE" "$SECRET_MANAGER_SCRIPT" get_secret_key "$key_name" 2>/dev/null)
    local exit_code=$?

    if [ $exit_code -eq 0 ] && [ -n "$value" ]; then
        echo "$value"
        return 0
    else
        echo "[DEBUG] Failed to load secret: $key_name (exit code: $exit_code)" >&2
        return 1
    fi
}}

SSH_CONNECTION=$(get_secret_value "{ssh_conn_key}")
if [ -n "$SSH_CONNECTION" ]; then
    echo "[SUCCESS] SSH Connection loaded: $SSH_CONNECTION"
else
    echo "[ERROR] SSH_CONNECTION not found"
    exit 1
fi

SSH_PASSWORD=$(get_secret_value "{password_key_name}")
if [ -n "$SSH_PASSWORD" ]; then
    echo "[SUCCESS] SSH password loaded: $SSH_PASSWORD"
else
    echo "[INFO] No password configured (using SSH key authentication)"
fi
echo ""
"""

        connection_section = f"""
# =============================================================================
# Execute SSH Connection
# =============================================================================
echo ""
echo "============================================================"
echo "Connecting to SSH Server"
echo "============================================================"
echo ""

if [ -z "$SSH_CONNECTION" ]; then
    echo "[ERROR] SSH connection string is empty"
    exit 1
fi

if [ -n "$SSH_PASSWORD" ]; then
    # SSH Key setup guide
    LOCAL_KEY="$HOME/.ssh/id_ed25519"
    LOCAL_PUB="$LOCAL_KEY.pub"
    echo ""
    echo "============================================================"
    echo "  SSH Key Setup Guide (passwordless login)"
    echo "============================================================"
    echo ""
    echo "  After login, run these commands to enable SSH key auth:"
    echo ""
    echo "  --- Step 1: Generate key on LOCAL machine (if not exists) ---"
    echo ""
    echo "  [ -f \"$LOCAL_PUB\" ] || ssh-keygen -t ed25519 -f \"$LOCAL_KEY\" -N \"\""
    echo ""
    echo "  --- Step 2: Copy key to server (run on LOCAL) ---"
    echo ""
    echo "  # Option A: ssh-copy-id (Debian/Ubuntu/CentOS/Fedora):"
    echo "  ssh-copy-id -i \"$LOCAL_PUB\" $SSH_CONNECTION"
    echo ""
    echo "  # Option B: Manual (works on all distros):"
    echo "  cat \"$LOCAL_PUB\" | ssh $SSH_CONNECTION \"mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys\""
    echo ""
    echo "  --- Step 3: Verify (run on LOCAL) ---"
    echo ""
    echo "  ssh $SSH_CONNECTION \"echo 'SSH key auth OK'\""
    echo ""
    echo "  --- Notes ---"
    echo "  * Works on Debian/Ubuntu/CentOS/RHEL/AlmaLinux/Fedora"
    echo "  * Safe if server already has other keys (appends, not overwrites)"
    echo "  * Safe if local machine has other keys (ed25519 is separate from rsa)"
    echo "  * If server has SELinux: ssh $SSH_CONNECTION \"restorecon -Rv ~/.ssh\""
    echo "  * If using custom port: ssh -p PORT $SSH_CONNECTION"
    echo ""

    # Display password for copy-paste
    echo "============================================================"
    echo "  SSH PASSWORD (Copy this to clipboard):"
    echo "  $SSH_PASSWORD"
    echo "============================================================"
    echo ""
    echo "[INFO] SSH will prompt for password. Please paste the password above when prompted."
    echo ""
    echo "Executing: ssh $SSH_CONNECTION"
    echo ""

    # Execute SSH connection - it will prompt for password
    ssh "$SSH_CONNECTION" "$@"
else
    # No password configured, use SSH key authentication
    echo "[INFO] No password configured, using SSH key authentication"
    echo "Executing: ssh $SSH_CONNECTION"
    echo ""

    ssh "$SSH_CONNECTION" "$@"
fi

echo ""
echo "SSH session ended"
echo ""
"""

        return f"{header}{file_name_display}{path_resolution}{load_secret_manager}{connection_section}"


__all__ = ['SSHCommandGenerator']

