/**
 * PcAiImagePage — pycore image generation + SHARED image history.
 *
 * Two sections over the pycore AI gateway (`/api/local/ai/*` via the /pyapi proxy):
 *   - Image Gen  : prompt + aspect ratio + optional provider/model → POST /image;
 *                  renders the returned base64 image (data URI), shows which
 *                  provider/model/latency produced it. Results are auto-saved.
 *   - Image History : gallery from GET /image/history (metadata only; bytes via
 *                  the per-id file endpoint). The store is SHARED with laravel, so
 *                  both runtimes' images appear here (an origin badge distinguishes
 *                  them). Per-tile Delete + a Clear-all; click to enlarge / reuse.
 *
 * A compact strip of image-capable providers (with their bound image_model) is
 * shown at the top, reusing the same AI catalog the Capability Status page uses.
 */
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import {
  Image as ImageIcon, Sparkles, RefreshCcw, Trash2, AlertTriangle,
  Download, X, RotateCcw, Activity, Wand2,
} from 'lucide-react';
import { pycoreApi } from '../../../core/api-libs/pycore';
import type { AiProvider, ImageHistoryEntry } from '../../../core/api-libs/pycore';

// Aspect-ratio options surfaced as the `size` field of the image contract.
const SIZE_OPTIONS = ['1:1', '16:9', '9:16', '4:3'] as const;
type SizeOption = (typeof SIZE_OPTIONS)[number];

function dataUri(mime: string, b64: string): string {
  return `data:${mime || 'image/png'};base64,${b64}`;
}

function fmtTime(iso: string, ts: number): string {
  const d = iso ? new Date(iso) : (ts ? new Date(ts * 1000) : null);
  if (!d || Number.isNaN(d.getTime())) return '';
  return d.toLocaleString();
}

const OriginBadge: React.FC<{ origin: string }> = ({ origin }) => {
  const isLaravel = origin === 'laravel';
  return (
    <span
      className={`inline-flex items-center px-1.5 py-0.5 rounded-md text-[9px] font-bold uppercase tracking-wide ${
        isLaravel ? 'bg-rose-500/15 text-rose-500' : 'bg-indigo-500/15 text-indigo-500'
      }`}
      title={`Generated by the ${origin} runtime`}>
      {origin || 'pycore'}
    </span>
  );
};

const PcAiImagePage: React.FC = () => {
  const { t } = useTranslation('pc');

  // --- image-capable providers (catalog; cheap, no live test) -------------- #
  const [providers, setProviders] = useState<AiProvider[] | null>(null);

  // --- generation form + result ------------------------------------------- #
  const [prompt, setPrompt] = useState('');
  const [size, setSize] = useState<SizeOption>('1:1');
  const [provider, setProvider] = useState(''); // '' = auto
  const [model, setModel] = useState('');
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState<string | null>(null);
  const [result, setResult] = useState<{
    src: string; provider: string; model: string; latency_ms: number | null;
  } | null>(null);

  // --- history ------------------------------------------------------------- #
  const [history, setHistory] = useState<ImageHistoryEntry[] | null>(null);
  const [historyLoading, setHistoryLoading] = useState(true);
  const [historyError, setHistoryError] = useState<string | null>(null);
  const [clearing, setClearing] = useState(false);
  const [deleting, setDeleting] = useState<Set<string>>(new Set());
  const [preview, setPreview] = useState<ImageHistoryEntry | null>(null);

  const imageProviders = useMemo(
    () => (providers ?? []).filter((p) => p.image),
    [providers],
  );

  const loadCatalog = useCallback(async () => {
    try {
      const r = await pycoreApi.getAiCatalog();
      setProviders(Array.isArray(r?.providers) ? r.providers : []);
    } catch { /* keep last */ }
  }, []);

  const loadHistory = useCallback(async (refresh = false) => {
    if (refresh) setHistoryError(null);
    setHistoryLoading(true);
    try {
      const r = await pycoreApi.getImageHistory(50);
      setHistory(Array.isArray(r?.entries) ? r.entries : []);
      setHistoryError(r?.error ?? null);
    } catch (e: any) {
      setHistoryError(e?.message || t('aiImage.unreachable'));
    } finally {
      setHistoryLoading(false);
    }
  }, [t]);

  useEffect(() => { void loadCatalog(); void loadHistory(); }, [loadCatalog, loadHistory]);

  const handleGenerate = useCallback(async () => {
    const text = prompt.trim();
    if (!text) { setGenError(t('aiImage.emptyPrompt')); return; }
    setGenerating(true);
    setGenError(null);
    try {
      const r = await pycoreApi.generateImage({
        prompt: text,
        size,
        ...(provider ? { provider } : {}),
        ...(model.trim() ? { model: model.trim() } : {}),
        source: 'pycore-ai-tools',
      });
      if (r?.success && r.image_base64) {
        setResult({
          src: dataUri(r.mime, r.image_base64),
          provider: r.provider,
          model: r.model,
          latency_ms: r.latency_ms,
        });
        // The backend auto-records into the shared store — refresh the gallery.
        void loadHistory();
      } else {
        setGenError(r?.error || t('aiImage.genFailed'));
      }
    } catch (e: any) {
      setGenError(e?.message || t('aiImage.genFailed'));
    } finally {
      setGenerating(false);
    }
  }, [prompt, size, provider, model, loadHistory, t]);

  const handleDelete = useCallback(async (id: string) => {
    setDeleting((s) => { const n = new Set(s); n.add(id); return n; });
    try {
      const r = await pycoreApi.deleteImageHistory(id);
      if (r?.success) {
        setHistory((prev) => (prev ? prev.filter((e) => e.id !== id) : prev));
        setPreview((p) => (p && p.id === id ? null : p));
      }
    } catch { /* keep */ }
    finally {
      setDeleting((s) => { const n = new Set(s); n.delete(id); return n; });
    }
  }, []);

  const handleClearAll = useCallback(async () => {
    if (!window.confirm(t('aiImage.confirmClear'))) return;
    setClearing(true);
    try {
      const r = await pycoreApi.clearImageHistory();
      if (r?.success) { setHistory([]); setPreview(null); }
    } catch { /* keep */ }
    finally {
      setClearing(false);
    }
  }, [t]);

  const reusePrompt = useCallback((p: string) => {
    setPrompt(p);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  return (
    <div className="p-6 md:p-8 space-y-5 min-w-0 max-w-full">
      {/* Sticky page chrome — title + actions pinned below PcTopBar. */}
      <div
        className="sticky top-0 z-20 -mx-6 md:-mx-8 px-6 md:px-8 py-3 -mt-6 md:-mt-8 mb-1 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200/80 dark:border-slate-800/80 bg-white/70 dark:bg-slate-900/50 backdrop-blur-xl"
        style={{ paddingRight: 'max(1.5rem, var(--shell-dock-right-gutter, 264px))' }}
      >
        <div className="min-w-0">
          <h1 className="text-xl font-bold flex items-center gap-2 text-slate-800 dark:text-slate-100">
            <ImageIcon className="w-5 h-5 text-indigo-500" /> {t('aiImage.title')}
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            {t('aiImage.subtitle')}
          </p>
        </div>
        <div className="flex shrink-0 gap-2 self-end sm:self-auto">
          <Link
            to="/pycore-manager/ai-status"
            title={t('aiImage.openStatusTitle')}
            className="px-3 py-2 pc-glass hover:bg-indigo-500/10 text-xs font-bold rounded-xl flex items-center gap-1 transition text-slate-700 dark:text-slate-200">
            <Activity className="w-3.5 h-3.5" /> {t('aiImage.openStatus')}
          </Link>
          <button
            onClick={() => loadHistory(true)}
            disabled={historyLoading}
            title={t('aiImage.refreshHistory')}
            className="px-3 py-2 pc-glass hover:bg-indigo-500/10 text-xs font-bold rounded-xl flex items-center gap-1 transition disabled:opacity-50 text-slate-700 dark:text-slate-200">
            <RefreshCcw className={`w-3.5 h-3.5 ${historyLoading ? 'animate-spin' : ''}`} /> {t('common.refresh')}
          </button>
        </div>
      </div>

      {/* ===================== Image-capable providers ===================== */}
      <section className="pc-glass p-5">
        <h2 className="text-sm font-bold flex items-center gap-2 text-slate-700 dark:text-slate-200 mb-1">
          <Sparkles className="w-4 h-4 text-indigo-500" /> {t('aiImage.capableProviders')}
        </h2>
        <p className="text-xs text-slate-500 dark:text-slate-400 mb-3">{t('aiImage.capableProvidersHint')}</p>
        {imageProviders.length === 0 ? (
          <p className="text-[11px] italic text-slate-400">{t('aiImage.noImageProviders')}</p>
        ) : (
          <div className="flex flex-wrap gap-2">
            {imageProviders.map((p) => (
              <span
                key={p.name}
                title={`${p.image_ready ? 'Image generation ready (API key present).' : 'Image-capable, but no API key configured yet.'}${p.image_model ? ` Model: ${p.image_model}` : ''}`}
                className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-[11px] font-semibold max-w-[220px] ${
                  p.image_ready
                    ? 'bg-pink-500/15 text-pink-500'
                    : 'border border-pink-400/40 text-pink-400/70'
                }`}>
                <ImageIcon className="w-3.5 h-3.5 shrink-0" />
                <span className="font-bold text-slate-700 dark:text-slate-200">{p.name}</span>
                {p.image_model && <span className="truncate font-mono text-[10px] opacity-80">{p.image_model}</span>}
              </span>
            ))}
          </div>
        )}
      </section>

      {/* ===================== Image generation ===================== */}
      <section className="pc-glass p-5">
        <h2 className="text-sm font-bold flex items-center gap-2 text-slate-700 dark:text-slate-200 mb-4">
          <Wand2 className="w-4 h-4 text-indigo-500" /> {t('aiImage.genSection')}
        </h2>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          {/* form */}
          <div className="space-y-3">
            <div>
              <label className="block text-[11px] font-semibold uppercase tracking-wider text-slate-500 mb-1.5">
                {t('aiImage.prompt')}
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={5}
                placeholder={t('aiImage.promptPlaceholder')}
                className="w-full rounded-xl border bg-white/60 dark:bg-white/5 border-slate-300/50 dark:border-white/10 px-3 py-2 text-sm text-slate-700 dark:text-slate-200 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/40 resize-y"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-slate-500 mb-1.5">
                  {t('aiImage.size')}
                </label>
                <select
                  value={size}
                  onChange={(e) => setSize(e.target.value as SizeOption)}
                  className="w-full rounded-xl border bg-white/60 dark:bg-white/5 border-slate-300/50 dark:border-white/10 px-3 py-2 text-sm text-slate-700 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500/40">
                  {SIZE_OPTIONS.map((s) => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-slate-500 mb-1.5">
                  {t('aiImage.provider')} <span className="text-slate-400 normal-case font-normal">({t('aiImage.optional')})</span>
                </label>
                <select
                  value={provider}
                  onChange={(e) => setProvider(e.target.value)}
                  className="w-full rounded-xl border bg-white/60 dark:bg-white/5 border-slate-300/50 dark:border-white/10 px-3 py-2 text-sm text-slate-700 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500/40">
                  <option value="">{t('aiImage.auto')}</option>
                  {imageProviders.map((p) => <option key={p.name} value={p.name}>{p.name}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-[11px] font-semibold uppercase tracking-wider text-slate-500 mb-1.5">
                  {t('aiImage.model')} <span className="text-slate-400 normal-case font-normal">({t('aiImage.optional')})</span>
                </label>
                <input
                  type="text"
                  value={model}
                  onChange={(e) => setModel(e.target.value)}
                  placeholder={t('aiImage.auto')}
                  className="w-full rounded-xl border bg-white/60 dark:bg-white/5 border-slate-300/50 dark:border-white/10 px-3 py-2 text-sm text-slate-700 dark:text-slate-200 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/40"
                />
              </div>
            </div>

            {genError && (
              <div className="flex items-start gap-2 text-xs rounded-2xl p-3 border bg-amber-500/10 border-amber-500/30 text-amber-600 dark:text-amber-400">
                <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
                <span className="break-words">{genError}</span>
              </div>
            )}

            <div className="flex items-center gap-3">
              <button
                onClick={handleGenerate}
                disabled={generating || !prompt.trim()}
                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold rounded-xl flex items-center gap-1.5 transition disabled:opacity-50">
                {generating ? <RefreshCcw className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                {generating ? t('aiImage.generating') : t('aiImage.generate')}
              </button>
              <span className="text-[11px] text-slate-400">{t('aiImage.autoSaved')}</span>
            </div>
          </div>

          {/* result */}
          <div className="rounded-2xl border border-dashed border-slate-300/60 dark:border-white/10 bg-white/30 dark:bg-white/5 p-4 flex flex-col items-center justify-center min-h-[260px]">
            {generating ? (
              <div className="text-xs text-slate-500 flex flex-col items-center gap-2">
                <RefreshCcw className="w-6 h-6 animate-spin text-slate-400" /> {t('aiImage.generating')}
              </div>
            ) : result ? (
              <div className="w-full flex flex-col items-center gap-3">
                <img
                  src={result.src}
                  alt="Generated"
                  className="max-h-[320px] w-auto rounded-xl shadow-md object-contain"
                />
                <div className="flex items-center justify-between w-full gap-2">
                  <p className="text-[11px] font-mono text-slate-500 truncate">
                    {t('aiImage.resultVia', { provider: result.provider, model: result.model })}
                    {result.latency_ms != null ? ` · ${t('aiImage.latency', { ms: Math.round(result.latency_ms) })}` : ''}
                  </p>
                  <a
                    href={result.src}
                    download={`pycore-image-${Date.now()}.png`}
                    className="shrink-0 px-2.5 py-1.5 rounded-lg text-[11px] font-bold flex items-center gap-1 transition pc-glass hover:bg-indigo-500/10 text-indigo-500">
                    <Download className="w-3.5 h-3.5" /> {t('aiImage.download')}
                  </a>
                </div>
              </div>
            ) : (
              <div className="text-xs text-slate-400 flex flex-col items-center gap-2">
                <ImageIcon className="w-8 h-8 opacity-50" />
                {t('aiImage.promptPlaceholder')}
              </div>
            )}
          </div>
        </div>
      </section>

      {/* ===================== Image history ===================== */}
      <section className="pc-glass p-5">
        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3 mb-3">
          <div className="min-w-0">
            <h2 className="text-sm font-bold flex items-center gap-2 text-slate-700 dark:text-slate-200">
              <ImageIcon className="w-4 h-4 text-indigo-500" /> {t('aiImage.historySection')}
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{t('aiImage.historyHint')}</p>
          </div>
          <div className="flex shrink-0 gap-2">
            <button
              onClick={() => loadHistory(true)}
              disabled={historyLoading}
              title={t('aiImage.refreshHistory')}
              className="px-3 py-2 pc-glass hover:bg-indigo-500/10 text-xs font-bold rounded-xl flex items-center gap-1 transition disabled:opacity-50 text-slate-700 dark:text-slate-200">
              <RefreshCcw className={`w-3.5 h-3.5 ${historyLoading ? 'animate-spin' : ''}`} />
            </button>
            <button
              onClick={handleClearAll}
              disabled={clearing || !(history && history.length > 0)}
              className="px-3 py-2 bg-rose-500/15 hover:bg-rose-500/25 text-rose-600 dark:text-rose-400 text-xs font-bold rounded-xl flex items-center gap-1 transition disabled:opacity-40 disabled:cursor-not-allowed">
              {clearing ? <RefreshCcw className="w-3.5 h-3.5 animate-spin" /> : <Trash2 className="w-3.5 h-3.5" />}
              {clearing ? t('aiImage.clearing') : t('aiImage.clearAll')}
            </button>
          </div>
        </div>

        {historyError && (
          <div className="flex items-start gap-2 text-xs rounded-2xl p-3 mb-3 border bg-amber-500/10 border-amber-500/30 text-amber-600 dark:text-amber-400">
            <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
            <span className="break-words">{historyError}</span>
          </div>
        )}

        {historyLoading && !history ? (
          <div className="text-xs text-slate-500 py-8 text-center flex flex-col items-center gap-2">
            <RefreshCcw className="w-5 h-5 animate-spin text-slate-400" /> {t('aiImage.loadingHistory')}
          </div>
        ) : !history || history.length === 0 ? (
          <div className="text-xs text-slate-500 py-8 text-center border border-dashed border-slate-300 dark:border-white/10 rounded-2xl">
            {t('aiImage.emptyHistory')}
          </div>
        ) : (
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-3">
            {history.map((e) => {
              const busy = deleting.has(e.id);
              return (
                <div
                  key={e.id}
                  className="group rounded-2xl border bg-white/40 dark:bg-white/5 border-slate-300/35 dark:border-white/5 overflow-hidden flex flex-col">
                  <button
                    type="button"
                    onClick={() => setPreview(e)}
                    title={t('aiImage.enlargeTitle')}
                    className="relative block aspect-square bg-slate-200/40 dark:bg-white/5 overflow-hidden">
                    <img
                      src={pycoreApi.imageHistoryFileUrl(e.id)}
                      alt={e.prompt}
                      loading="lazy"
                      className="w-full h-full object-cover transition-transform group-hover:scale-105"
                    />
                    <span className="absolute top-1.5 left-1.5">
                      <OriginBadge origin={e.origin} />
                    </span>
                  </button>
                  <div className="p-2.5 flex flex-col gap-1.5 min-w-0">
                    <p className="text-[11px] text-slate-600 dark:text-slate-300 line-clamp-2 leading-snug" title={e.prompt}>
                      {e.prompt || '—'}
                    </p>
                    <p className="text-[10px] font-mono text-slate-400 truncate" title={`${e.provider} · ${e.model}`}>
                      {e.provider}{e.model ? ` · ${e.model}` : ''}
                    </p>
                    <p className="text-[10px] text-slate-400 truncate">{fmtTime(e.iso, e.ts)}</p>
                    <div className="flex items-center gap-1.5 mt-0.5">
                      <button
                        type="button"
                        onClick={() => reusePrompt(e.prompt)}
                        title={t('aiImage.reusePromptTitle')}
                        className="flex-1 px-2 py-1 rounded-lg text-[10px] font-bold flex items-center justify-center gap-1 transition pc-glass hover:bg-indigo-500/10 text-indigo-500">
                        <RotateCcw className="w-3 h-3" /> {t('aiImage.reusePrompt')}
                      </button>
                      <button
                        type="button"
                        onClick={() => handleDelete(e.id)}
                        disabled={busy}
                        title={t('aiImage.deleteTitle')}
                        className="px-2 py-1 rounded-lg text-[10px] font-bold flex items-center justify-center gap-1 transition bg-rose-500/10 hover:bg-rose-500/20 text-rose-500 disabled:opacity-40">
                        {busy ? <RefreshCcw className="w-3 h-3 animate-spin" /> : <Trash2 className="w-3 h-3" />}
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </section>

      {/* ===================== Enlarge / detail modal ===================== */}
      {preview && (
        <div
          className="fixed inset-0 z-[200] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
          onClick={() => setPreview(null)}>
          <div
            className="relative max-w-3xl w-full max-h-[90vh] rounded-2xl bg-white dark:bg-slate-900 shadow-2xl overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}>
            <button
              type="button"
              onClick={() => setPreview(null)}
              title={t('aiImage.close')}
              className="absolute top-3 right-3 z-10 p-1.5 rounded-lg bg-black/30 hover:bg-black/50 text-white transition">
              <X className="w-4 h-4" />
            </button>
            <div className="flex-1 min-h-0 overflow-auto bg-slate-100 dark:bg-black/40 flex items-center justify-center">
              <img
                src={pycoreApi.imageHistoryFileUrl(preview.id)}
                alt={preview.prompt}
                className="max-w-full max-h-[60vh] object-contain"
              />
            </div>
            <div className="p-4 space-y-2 border-t border-slate-200/80 dark:border-slate-800/80">
              <div className="flex items-center gap-2">
                <OriginBadge origin={preview.origin} />
                <span className="text-[11px] font-mono text-slate-500 truncate">
                  {preview.provider}{preview.model ? ` · ${preview.model}` : ''} · {preview.size} · {fmtTime(preview.iso, preview.ts)}
                </span>
              </div>
              <p className="text-sm text-slate-700 dark:text-slate-200 break-words">{preview.prompt || '—'}</p>
              <div className="flex items-center gap-2 pt-1">
                <button
                  type="button"
                  onClick={() => { reusePrompt(preview.prompt); setPreview(null); }}
                  className="px-3 py-1.5 rounded-lg text-[11px] font-bold flex items-center gap-1 transition pc-glass hover:bg-indigo-500/10 text-indigo-500">
                  <RotateCcw className="w-3.5 h-3.5" /> {t('aiImage.reusePrompt')}
                </button>
                <a
                  href={pycoreApi.imageHistoryFileUrl(preview.id)}
                  download={`pycore-image-${preview.id}.${(preview.mime.split('/')[1] || 'png')}`}
                  className="px-3 py-1.5 rounded-lg text-[11px] font-bold flex items-center gap-1 transition pc-glass hover:bg-indigo-500/10 text-indigo-500">
                  <Download className="w-3.5 h-3.5" /> {t('aiImage.download')}
                </a>
                <button
                  type="button"
                  onClick={() => handleDelete(preview.id)}
                  disabled={deleting.has(preview.id)}
                  className="px-3 py-1.5 rounded-lg text-[11px] font-bold flex items-center gap-1 transition bg-rose-500/10 hover:bg-rose-500/20 text-rose-500 disabled:opacity-40">
                  <Trash2 className="w-3.5 h-3.5" /> {t('aiImage.delete')}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default PcAiImagePage;
