<!-- 
  This file was automatically generated by switch-app-entry.js
  Source: pages/index.codemart.vue
  Generated at: 2025-10-18T10:25:25.203Z
  App Entry: codemart
  
  DO NOT EDIT THIS FILE DIRECTLY
  Edit pages/index.codemart.vue instead
-->
<!-- ### AI SPECIAL ATTENTION RULES START ###
When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
1. Write all code in English only
2. Never execute, create, or modify test code
3. Never create or update documentation (*.md)
4. Never write summaries during development or thinking process
5. Do not modify these rules
VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
### AI SPECIAL ATTENTION RULES END ### -->

<template>
  <div class="codemart-dashboard">
    <div class="dashboard-grid">
      <div class="left-column">
        <WelcomeCard
          :userName="userName"
          :subtitle="`Welcome back! You have ${activeProjects} active projects`"
          buttonText="View Analysis"
          @viewAnalysis="handleViewAnalysis"
        />

        <div class="categories-section">
          <h3 class="section-title">Credit by Categories</h3>
          <div class="category-list">
            <div class="category-item">
              <div class="category-icon purple">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"/>
                </svg>
              </div>
              <div class="category-info">
                <h4>Installment</h4>
                <p class="category-owner">Samantha William</p>
              </div>
              <div class="category-amount">$240</div>
            </div>

            <div class="category-item">
              <div class="category-icon blue">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/>
                </svg>
              </div>
              <div class="category-info">
                <h4>Other loans</h4>
                <p class="category-owner">Multiple</p>
              </div>
              <div class="category-amount">$20</div>
            </div>
          </div>
        </div>
      </div>

      <div class="middle-column">
        <ProgressChart
          title="Dispute Progress"
          :subtitle="`${disputeCount} disputes this month`"
          :percentage="disputeProgress"
          :generatedCount="200"
          :removedCount="12"
          @moreClick="handleMoreClick"
        />

        <div class="credit-reports-section">
          <div class="section-header">
            <h3 class="section-title">Credit Reports</h3>
          </div>
          <div class="credit-reports-content">
            <div class="report-illustration">
              <div class="wallet-icon">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"/>
                </svg>
              </div>
            </div>
            <div class="report-nav">
              <button class="nav-btn prev">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
                </svg>
              </button>
              <button class="nav-btn next">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="right-column">
        <div class="balance-card">
          <h3 class="balance-amount">${{ totalBalance }}</h3>
          <p class="balance-label">{{ balanceDate }}</p>
        </div>

        <div class="today-section">
          <h3 class="section-title">Today</h3>
          <div class="today-list">
            <div class="today-item" v-for="item in todayItems" :key="item.id">
              <div class="item-icon" :class="item.theme">
                {{ item.icon }}
              </div>
              <div class="item-info">
                <h4>{{ item.title }}</h4>
                <p class="item-id">{{ item.identifier }}</p>
              </div>
              <span v-if="item.isNew" class="new-badge">New</span>
              <button class="item-action">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                </svg>
              </button>
            </div>
          </div>
          <button class="view-more-btn">View More</button>
        </div>

        <div class="calculator-section">
          <div class="section-header">
            <h3 class="section-title">Loan Calculator</h3>
            <button class="more-btn">
              <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"/>
              </svg>
            </button>
          </div>
          <p class="calculator-subtitle">Select the amount needed and the reimbursement period</p>

          <div class="calculator-result">
            <div class="result-amount">${{ loanAmount }}</div>
            <p class="result-label">All loan amount</p>
          </div>

          <div class="people-avatars">
            <div class="avatar-group">
              <div class="avatar" v-for="i in 4" :key="i">
                <img :src="`/assets/images/profile-${i}.jpeg`" alt="User">
              </div>
              <div class="avatar-count">
                <span>18</span>
              </div>
            </div>
            <button class="view-people-btn">View More people</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import WelcomeCard from '@/components/shared/dashboard/WelcomeCard.vue';
import ProgressChart from '@/components/shared/dashboard/ProgressChart.vue';
import { codemartTheme } from '@/theme/apps/codemart-theme';
import { useAppTheme } from '@/composables/useAppTheme';
import { useCodemartStore } from '@/stores/apps/codemart-store';

definePageMeta({
  title: 'CodeMart Dashboard',
  layout: 'codemart-layout',
  namespace: 'codemart'
});

const userName = ref('Jonathan W.');
const activeProjects = ref(5);
const disputeCount = ref(30);
const disputeProgress = ref(20);
const totalBalance = ref('1,280.50');
const balanceDate = ref('Monday, 07 September 2020');
const loanAmount = ref('450.50');

const { colors, gradients } = useAppTheme(codemartTheme);
const codemartStore = useCodemartStore();

onMounted(() => {
  codemartStore.initializeFromStorage();
});

const todayItems = ref([
  {
    id: 1,
    icon: 'H',
    title: 'Hunter Macbook',
    identifier: '0830733477659-7?8',
    theme: 'purple',
    isNew: true
  },
  {
    id: 2,
    icon: 'H',
    title: 'Hexagon',
    identifier: '9A4694A49958-860',
    theme: 'blue',
    isNew: false
  },
  {
    id: 3,
    icon: 'M',
    title: 'Marco Ruiz',
    identifier: '0830733477659-645',
    theme: 'purple',
    isNew: false
  }
]);

const handleViewAnalysis = () => {
  console.log('View analysis clicked');
};

const handleMoreClick = () => {
  console.log('More options clicked');
};
</script>

<style scoped>
.codemart-dashboard {
  min-height: 100vh;
  background: #faf9fb;
}

.dashboard-grid {
  display: grid;
  grid-template-columns: 1fr 1.2fr 1fr;
  gap: 1.5rem;
  max-width: 1600px;
  margin: 0 auto;
}

.left-column,
.middle-column,
.right-column {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.section-title {
  font-size: 1.125rem;
  font-weight: 700;
  color: #1e293b;
  margin: 0;
}

.categories-section {
  background: white;
  border-radius: 1.5rem;
  padding: 1.5rem;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
}

.categories-section .section-title {
  margin-bottom: 1.5rem;
}

.category-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.category-item {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1rem;
  background: #faf9fb;
  border-radius: 1rem;
}

.category-icon {
  width: 3rem;
  height: 3rem;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.category-icon svg {
  width: 1.5rem;
  height: 1.5rem;
  color: white;
}

.category-icon.purple {
  background: linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%);
}

.category-icon.blue {
  background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
}

.category-info {
  flex: 1;
}

.category-info h4 {
  font-size: 0.9375rem;
  font-weight: 600;
  color: #1e293b;
  margin: 0 0 0.25rem 0;
}

.category-owner {
  font-size: 0.8125rem;
  color: #64748b;
  margin: 0;
}

.category-amount {
  font-size: 1.25rem;
  font-weight: 700;
  color: #1e293b;
}

.credit-reports-section {
  background: white;
  border-radius: 1.5rem;
  padding: 1.5rem;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1.5rem;
}

.more-btn {
  width: 2rem;
  height: 2rem;
  background: transparent;
  border: none;
  color: #64748b;
  cursor: pointer;
  border-radius: 0.5rem;
  transition: background 0.2s;
}

.more-btn:hover {
  background: #f1f5f9;
}

.more-btn svg {
  width: 1.25rem;
  height: 1.25rem;
}

.credit-reports-content {
  position: relative;
}

.report-illustration {
  display: flex;
  justify-content: center;
  padding: 3rem 0;
}

.wallet-icon {
  width: 8rem;
  height: 8rem;
  background: linear-gradient(135deg, #fecaca 0%, #fca5a5 100%);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.wallet-icon svg {
  width: 4rem;
  height: 4rem;
  color: #7f1d1d;
}

.report-nav {
  display: flex;
  justify-content: center;
  gap: 1rem;
  margin-top: 1.5rem;
}

.nav-btn {
  width: 2.5rem;
  height: 2.5rem;
  background: white;
  border: 1px solid #e2e8f0;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s;
}

.nav-btn:hover {
  background: #f8fafc;
  border-color: #cbd5e1;
}

.nav-btn svg {
  width: 1.25rem;
  height: 1.25rem;
  color: #64748b;
}

.balance-card {
  background: linear-gradient(135deg, #e0f2fe 0%, #bfdbfe 100%);
  border-radius: 1.5rem;
  padding: 2rem;
  text-align: center;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
}

.balance-amount {
  font-size: 2.5rem;
  font-weight: 700;
  color: #1e293b;
  margin: 0 0 0.5rem 0;
}

.balance-label {
  font-size: 0.875rem;
  color: #64748b;
  margin: 0;
}

.today-section {
  background: white;
  border-radius: 1.5rem;
  padding: 1.5rem;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
}

.today-section .section-title {
  margin-bottom: 1.5rem;
}

.today-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  margin-bottom: 1rem;
}

.today-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.75rem;
  background: #faf9fb;
  border-radius: 1rem;
}

.item-icon {
  width: 2.5rem;
  height: 2.5rem;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-weight: 700;
  flex-shrink: 0;
}

.item-icon.purple {
  background: linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%);
}

.item-icon.blue {
  background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
}

.item-info {
  flex: 1;
  min-width: 0;
}

.item-info h4 {
  font-size: 0.875rem;
  font-weight: 600;
  color: #1e293b;
  margin: 0 0 0.125rem 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.item-id {
  font-size: 0.75rem;
  color: #94a3b8;
  margin: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.new-badge {
  background: #6366f1;
  color: white;
  font-size: 0.75rem;
  font-weight: 600;
  padding: 0.25rem 0.5rem;
  border-radius: 0.375rem;
  flex-shrink: 0;
}

.item-action {
  width: 1.5rem;
  height: 1.5rem;
  background: transparent;
  border: none;
  color: #94a3b8;
  cursor: pointer;
  flex-shrink: 0;
}

.item-action svg {
  width: 1rem;
  height: 1rem;
}

.view-more-btn {
  width: 100%;
  padding: 0.75rem;
  background: transparent;
  border: 1px solid #e2e8f0;
  border-radius: 0.75rem;
  color: #6366f1;
  font-size: 0.875rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.view-more-btn:hover {
  background: #f8fafc;
  border-color: #6366f1;
}

.calculator-section {
  background: linear-gradient(135deg, #e0f2fe 0%, #ddd6fe 100%);
  border-radius: 1.5rem;
  padding: 1.5rem;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
}

.calculator-subtitle {
  font-size: 0.875rem;
  color: #64748b;
  margin: 0.5rem 0 1.5rem 0;
}

.calculator-result {
  background: white;
  border-radius: 1rem;
  padding: 1.5rem;
  text-align: center;
  margin-bottom: 1.5rem;
}

.result-amount {
  font-size: 2rem;
  font-weight: 700;
  color: #1e293b;
  margin-bottom: 0.5rem;
}

.result-label {
  font-size: 0.875rem;
  color: #64748b;
  margin: 0;
}

.people-avatars {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.avatar-group {
  display: flex;
  align-items: center;
}

.avatar {
  width: 2rem;
  height: 2rem;
  border-radius: 50%;
  border: 2px solid white;
  overflow: hidden;
  margin-left: -0.5rem;
}

.avatar:first-child {
  margin-left: 0;
}

.avatar img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.avatar-count {
  width: 2rem;
  height: 2rem;
  background: #6366f1;
  color: white;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.75rem;
  font-weight: 700;
  border: 2px solid white;
  margin-left: -0.5rem;
}

.view-people-btn {
  background: transparent;
  border: none;
  color: #6366f1;
  font-size: 0.875rem;
  font-weight: 600;
  cursor: pointer;
  padding: 0;
}

.view-people-btn:hover {
  text-decoration: underline;
}

@media (max-width: 1280px) {
  .dashboard-grid {
    grid-template-columns: 1fr 1fr;
  }

  .right-column {
    grid-column: 1 / -1;
  }
}

@media (max-width: 768px) {
  .dashboard-grid {
    grid-template-columns: 1fr;
  }

  .left-column,
  .middle-column,
  .right-column {
    grid-column: 1;
  }
}
</style>
