<!-- 
  This file was automatically generated by switch-app-entry.js
  Source: pages/index.ittools.vue
  Generated at: 2025-11-02T22:57:59.669Z
  App Entry: ittools
  
  DO NOT EDIT THIS FILE DIRECTLY
  Edit pages/index.ittools.vue instead
-->
<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
    <!-- Header -->
    <header class="bg-white shadow-sm sticky top-0 z-50">
      <div class="max-w-7xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-4">
            <h1 class="text-2xl font-bold text-gray-900">
              <i class="fas fa-tools text-blue-600 mr-2"></i>IT Tools
            </h1>
            <span class="text-sm text-gray-500">88+ Developer Utilities</span>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <!-- Categories Navigation -->
      <div class="mb-8 overflow-x-auto">
        <div class="flex space-x-4 pb-2">
          <button
            v-for="category in itToolsStore.categoriesWithCounts"
            :key="category.id"
            @click="itToolsStore.setSelectedCategory(category.id)"
            :class="[
              'px-4 py-2 rounded-lg font-medium whitespace-nowrap transition',
              itToolsStore.selectedCategory === category.id
                ? 'bg-blue-600 text-white'
                : 'bg-white text-gray-700 border border-gray-200 hover:border-blue-300'
            ]"
          >
            <span class="mr-2">{{ category.icon }}</span>
            {{ category.name }}
            <span class="ml-1 text-xs">{{ category.count }}</span>
          </button>
        </div>
      </div>

      <!-- Tools Grid -->
      <div v-if="activeTab === 'tools'" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <div
          v-for="tool in itToolsStore.filteredTools"
          :key="tool.id"
          @click="selectToolAndOpen(tool)"
          class="bg-white rounded-lg shadow hover:shadow-lg transition cursor-pointer border border-gray-200 hover:border-blue-300 p-4"
        >
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <h3 class="font-semibold text-gray-900">{{ tool.name }}</h3>
              <p class="text-sm text-gray-600 mt-1">{{ tool.description }}</p>
            </div>
          </div>
        </div>
      </div>
    </main>

    <!-- Tool Modal -->
    <ToolModal
      v-if="selectedTool"
      :tool="selectedTool"
      @close="selectedTool = null"
      @execute="executeTool"
    />

    <!-- Settings Modal -->
    <SettingsModal
      v-if="showSettings"
      @close="showSettings = false"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useItToolsStore } from '@/apps/app_ittools/stores_app_ittools/ittools-store';
import type { Tool, HistoryEntry } from '@/apps/app_ittools/types_app_ittools';
import ToolModal from '@/apps/app_ittools/components_app_ittools/ToolModal.vue';
import SettingsModal from '@/apps/app_ittools/components_app_ittools/SettingsModal.vue';

definePageMeta({
  title: 'IT Tools - Developer Utilities',
  layout: 'default',
  namespace: 'ittools'
});

const itToolsStore = useItToolsStore();
const activeTab = ref('tools');
const showSettings = ref(false);
const selectedTool = ref<Tool | null>(null);

const favorites = computed(() => itToolsStore.favoriteTools);
const history = computed(() => itToolsStore.history.sort((a, b) => b.timestamp - a.timestamp).slice(0, 20));

onMounted(() => {
  itToolsStore.loadPreferences();
  itToolsStore.filterTools();
});

const selectToolAndOpen = (tool: Tool) => {
  itToolsStore.selectTool(tool);
  selectedTool.value = tool;
};

const executeTool = async (toolId: string, params: Record<string, any>) => {
  const tool = itToolsStore.allTools.find(t => t.id === toolId);
  if (tool) {
    const { ItToolsMainAPI } = await import('@/apps/app_ittools/services_app_ittools/ittools-main-api');
    const api = new ItToolsMainAPI();
    try {
      const response = await api.executeTool(tool.endpoint, tool.method, params);
      if (response.success) {
        itToolsStore.addToHistory(tool.id, params, response.data);
      }
    } catch (error) {
      console.error('Tool execution error:', error);
    }
  }
};

const copyHistoryEntry = async (entry: HistoryEntry) => {
  const text = JSON.stringify(entry.output, null, 2);
  await navigator.clipboard.writeText(text);
};

const formatDate = (timestamp: number): string => {
  return new Date(timestamp).toLocaleString();
};
</script>

<!-- NO <style> tag - All styles defined in theme files -->
