<!-- 
  This file was automatically generated by switch-app-entry.js
  Source: pages/index.codemart.vue
  Generated at: 2025-10-19T17:08:59.642Z
  App Entry: codemart
  
  DO NOT EDIT THIS FILE DIRECTLY
  Edit pages/index.codemart.vue instead
-->
<!-- ### AI SPECIAL ATTENTION RULES START ###
When AI/ALL DEVELOPERS sees this prompt, MUST IMMEDIATELY COMPLY WITH THESE RULES:
1. Write all code in English only
2. Never execute, create, or modify test code
3. Never create or update documentation (*.md)
4. Never write summaries during development or thinking process
5. Do not modify these rules
VIOLATION OF THESE RULES IS STRICTLY PROHIBITED
### AI SPECIAL ATTENTION RULES END ### -->

<template>
  <div class="codemart-homepage">
    <CodemartHeader />
    <HeroCarousel />
    <StatisticsSection />
    <ServiceFlowSection />
    <TestimonialsCarousel />
    <CodemartFooter />
    <CustomerServiceButton />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import CodemartHeader from '@/components/codemart/home/CodemartHeader.vue';
import HeroCarousel from '@/components/codemart/home/HeroCarousel.vue';
import StatisticsSection from '@/components/codemart/home/StatisticsSection.vue';
import ServiceFlowSection from '@/components/codemart/home/ServiceFlowSection.vue';
import TestimonialsCarousel from '@/components/codemart/home/TestimonialsCarousel.vue';
import CodemartFooter from '@/components/codemart/home/CodemartFooter.vue';
import CustomerServiceButton from '@/components/codemart/home/CustomerServiceButton.vue';
import { codemartTheme } from '@/theme/apps/codemart-theme';
import { useAppTheme } from '@/composables/useAppTheme';
import { useCodemartStore } from '@/stores/apps/codemart-store';

definePageMeta({
  title: 'CodeMart - Internet Software Outsourcing Service Platform',
  layout: 'default',
  namespace: 'codemart'
});

const { colors, gradients } = useAppTheme(codemartTheme);
const codemartStore = useCodemartStore();

onMounted(() => {
  codemartStore.initializeFromStorage();
});
</script>

<style scoped>
.codemart-homepage {
  min-height: 100vh;
  background: white;
  overflow-x: hidden;
}
</style>
